tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs

- We always compare body content if matching against the body. `Content-Length` header is almost immaterial given that.
- If we _don't_ compare body (aka `bodilessmatcher`) then the value of Content-Length doesn't matter anyway
In cases where the Content-Length values don't align (specifically due to bugfixes in test-proxy), it will likely be a test failure, when the Content-Length doesn't actually matter. This most recent proxy release stopped sanitizing binary content. This means that we have a bunch of content that's been sanitized differently in such a way that playback of tests won't fail, but the _matching_ now fails because the Content-Length doesn't align.
We obviously don't want to have this happen often, but we'll future-proof just in case.

[Test-Proxy] Add content length to ignored headers

---

eng/common/scripts/Verify-Links.ps1

Add timeout on all web request call.
This is for the issue: https://github.com/azure/azure-sdk-tools/issues/2600

Add timeout on Invoke-request call

---

src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs

Revision ID is null when generating diff URL so diff is always defaulted against latest revision.

Set revision ID in APIView diff request

---

eng/common/scripts/Update-DocsMsToc.ps1

Move Set-StrictMode to run after PSModule-Helpers.ps1 operations which violate strict mode and cause a falure as in https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1389880&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=61cf404c-fb38-582c-ffd7-16eb9e7ec7ac&l=97
Successful run after moving Set-StrictMode -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1390051&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=61cf404c-fb38-582c-ffd7-16eb9e7ec7ac
@benbp -- PTAL

Move Set-StrictMode to run after PSModule-Helpers.ps1 operations

---

eng/containers/ci.yml
tools/test-proxy/ci.yml

This needed to have a period in the name. Like the nuget package: `1.0.0-dev.20220210.1`

Clean up Test-Proxy docker update. Bugfix for docker tag name

---

eng/pipelines/azuresdkpartnerdrops-to-devops.yml
eng/pipelines/azuresdkpartnerdrops-to-nuget.yml
eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml

- Update parameters for azuresdkpartnerdrops-to-nugetfeed.yml.
Pipelines to replace old UI release pipelines.
[net - partnerdrops-to-devOps-feed](https://dev.azure.com/azure-sdk/internal/_build?definitionId=4583&_a=summary) for [azuresdkpartnerdrops to (nuget)devOps Feed](https://dev.azure.com/azure-sdk/internal/_release?_a=releases&view=all&definitionId=101)
[net - partnerdrops-to-nuget-feed](https://dev.azure.com/azure-sdk/internal/_build?definitionId=4442&_a=summary) for [azuresdkpartnerdrops to nuget](https://dev.azure.com/azure-sdk/internal/_release?_a=releases&view=mine&definitionId=3)

Fix azuresdkpartnerdrops-to-nugetfeed.yml parameters

---

packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py

Prevent `SomeType[Blah][Blah]` on Python 3.9. Instead will display as `SomeType[Blah]`. Necessary in order to use stable Python 3.9 because 3.10 is introducing instability to APIView. 
https://apiviewstaging.azurewebsites.net/Assemblies/Review/a52112cbbdb64806b476d9fe0f444ef5

[Python APIView] Fix for Python 3.9

---

.azure-pipelines/apiview.yml
eng/pipelines/templates/steps/use-python-version.yml
scripts/python/util/install_python_version.py

Latest python version 3.10.2 broke API review for Python packages. This PR is to pin API version to 3.10.1 to get consistent review for each CI run.

Pin python version for APIVIew to 3.10.1

---

eng/pipelines/notifications.yml
eng/pipelines/templates/variables/globals.yml

We update the code of the github-codeowner-subscriber to use the env var.
The PR is to use the latest version.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1405006&view=results

Update to github-codeowner-subscriber version and use env variable

---

eng/common/scripts/git-diff-changes.ps1

Have a common script for git diff changes.
Test proposal:
PR triggered(Compliance credscan): https://github.com/Azure/azure-sdk-for-js/pull/20643
Manually triggered(Build print diff): https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1407323&view=results
Test on Add, Update, Delete, Rename cases(Compliance credscan): https://github.com/Azure/azure-sdk-for-js/pull/20643
Test on sparse-checkout cases(Build print diff): https://github.com/Azure/azure-sdk-for-java/pull/27335
The git diff changes will add the file outside of the sparse checkout

The common scripts of PR git diff changes.

---

src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs

We do not create API review diff if baseline is not available, and new package which doesn't have any baseline from main branch yet will not have API review created from PR. This PR is to create new API review for such packages that are not yet present in main branch.

Create API review without diff for new package

---

eng/common/pipelines/templates/steps/detect-api-changes.yml
eng/common/scripts/Detect-Api-Changes.ps1

Currently API detection step sends request to APIView production instance. This PR is to support alternate environment to test API change detection from test pipeline (specially to test SDK automation).

Support staging URl to run detect API changes in test env

---

packages/python-packages/api-stub-generator/CHANGELOG.md
packages/python-packages/api-stub-generator/apistub/_apiview.py
packages/python-packages/api-stub-generator/apistub/_node_index.py
packages/python-packages/api-stub-generator/apistub/_stub_generator.py
packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
packages/python-packages/api-stub-generator/apistub/nodes/_enum_node.py
packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
packages/python-packages/api-stub-generator/tests/apiview_test.py
packages/python-packages/api-stub-generator/tests/class_parsing_test.py
packages/python-packages/apistubgentest/apistubgentest/models/__init__.py
packages/python-packages/apistubgentest/apistubgentest/models/_models.py

Fixes #2865. Fixes how aliases are displayed and creates diagnostic warning if there is a mismatch.
Fixes #1963. Fix so that enums that map to the same value are all displayed.
No diff to AzureCore from this change:
https://apiviewstaging.azurewebsites.net/Assemblies/Review/037455a30cce4057ae52ed9357ba66d3/446bf344023c4158ae2fff6ced4a9fff?diffRevisionId=cd3145dc03aa42bfacd3100fe0128f15&doc=False&diffOnly=True

[Python APIView] Fix alias display names and enum values

---

eng/common/TestResources/New-TestResources.ps1
eng/common/TestResources/SubConfig-Helpers.ps1

I think it could be helpful to set this variable for any tests that need to use it in the future. For example, the cpp tests using
the service directory to look up the environment variable name prefix.

Add AZURE_SERVICE_DIRECTORY environment variable in test deployment script

---

eng/common/TestResources/New-TestResources.ps1

There are cases where it useful to run the provision script locally, but with a subscription config object like we do in
our pipelines. For example, when testing new subscription configs, or when using test credentials for sovereign clouds
instead of provisioning sovereign cloud domain-joined user accounts. Currently to use the provisioner parameter set,
you must also pass `-CI` otherwise you get an error like below:
```
Set-AzContext: /home/ben/sdk/azure-sdk-for-python/eng/common/TestResources/New-TestResources.ps1:410
Line |
410 |  …           $null = Select-AzSubscription -Subscription $SubscriptionId
|                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Please provide a valid tenant or a valid subscription.
```
The downside to passing `-CI` when running locally …

Support local test resources behavior with provisioner config

---

eng/common/scripts/Update-DocsMsMetadata.ps1

Our original `ms.service` assign value as follows:
1. If csv `ServiceName` exists, then Normalize `Key Vault - > keyvault`
2. Otherwise, use the service directory
The proposal:
1. If csv `MSDocService` exists, then use the value directly. PM or service owner will update this to the right value
2. Otherwise, use the service directory
Testing pipeline on redis:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1432407&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1432410&view=results

Read the ms.service value from csv metadata

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

@JoshLove-msft @mikeharder 
Tested locally with record/playback of a few tables tests. Unfortunately that highlighted an issue with my previous PR during my local testing.

[Test-Proxy] Remove Explicit List of Content-Headers

---

eng/common/TestResources/New-TestResources.ps1

This sets up user-created resource groups to have the right metadata so that one has the option to remove DeleteAfter
tags to create long-lived resources. The alternative approach would be to update `$BaseName` generation to be formatted
like `$UserName-$ServiceDirectory` so we could parse and query the alias, but I think that would cause downstream
resource deployments that use the basename to fail validation (e.g. storage accounts don't support dash characters).

Set owners tag in test resource deployments

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ContentTypeUtilities.cs

Issue we need to tackle in the near future so that we can re-record tests and be happy going into the future is #2900

[Test-Proxy] Disable multipart/mixed sanitization until the additional work is done

---

packages/python-packages/api-stub-generator/CHANGELOG.md
packages/python-packages/api-stub-generator/apistub/_apiview.py
packages/python-packages/api-stub-generator/apistub/_stub_generator.py
packages/python-packages/api-stub-generator/apistub/_version.py
packages/python-packages/api-stub-generator/tests/apiview_test.py
packages/python-packages/api-stub-generator/tests/class_parsing_test.py

Closes #2757.
https://apiview.dev/Assemblies/Review/fb60229791b043e590c31f5d7ee4b33e
The link isn't live, but can by copy-pasted. To be live, we need #2650 implemented.

[Python APIView] Support `--source-url`

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs

We were using `GetRequiredService<>` which will fail if requested service can't be loaded. .NET test framework don't have that service accessible, and so are broken on startup.
Swapping to `GetService` to avoid the startup error. @JoshLove-msft

[Test-PRoxy] Optional <configuration> requirement

---

eng/common/pipelines/templates/steps/credscan.yml

Hey @sima-zhu I was looking into an issue posted by @ArthurMa1978 and I discovered this scenario.
Effectively, we never generate a `credscan.tsv` because we don't find any service folders with changed files. That's due to the fact that Azure/azure-sdk-for-net#27448 only _deletes_ two files. There is nothing to run compliance _on_!
I am now catching this explicitly with this conditional.
Another way we could handle this is adjust the `diff` call to also show deleted files I think, but that has the downside of running credscan when you've only _deleted files_.

[Credscan] Compliance w/out changed files shouldn't crash

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs

The .NET test framework greps the port number from server output. By dumping those configuration values BEFORE the app.run() output, we were sending unexpected input to their parser.

[Test-Proxy] Ensure compatibility with .NET Unit Tests

---

tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl

There is an issue where if the same stress test is deployed to two different namespaces, the generated resource group names will be identical. This causes issues with test overlap, but also when a test in namespace A completes and the resource group deletion triggers, it will remove the test resource targets used by the test in namespace B.
Fixes #2954

Add k8s namespace to stress test resource group name

---

eng/common/scripts/Update-DocsMsToc.ps1

Encountered this when auto-generating ToC for `Database for MySQL/PostgreSQL` service from [Python metadata](https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/python-packages.csv).

Add support for service names containing a forward slash

---

src/swift/CHANGELOG.md
src/swift/SwiftAPIView/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView.xcscheme
src/swift/SwiftAPIViewCore/Sources/Extensions/DeclarationModifier+Extensions.swift
src/swift/SwiftAPIViewCore/Sources/Models/TokenFile.swift

Partially addresses #2536. Ultimately, there will be significant work needed to correctly support extensions, but this PR ensures that extensions that are not themselves public or have any public members are not displayed.
This PR will temporarily allow duplicate IDs, which will revive the potential that comments will not appear correctly in APIView. Commenting on an extension will act like you are commenting on the original thing. For now, this is preferable to making APIView crash since the ultimate fix is non-trivial.

[Swift APIView] Do not display empty extensions

---

src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml

In some packages' revision page Edge offers to translate *from* Portuguese. `<html lang="en">` was added to no avail. After digging into the problem and asking internally, adding a "notranslate" meta prevents the automatic suggestion, but the page still is detected as Portuguese if you right-click and choose to translate anyway. Seems there's no way to change that. Typical language elements/attributes seem to be ignored in modern browsers.

Disable automatic translation of revision pages

---

.github/CODEOWNERS
tools/keyvault-mock-attestation/index.js
tools/keyvault-mock-attestation/package-lock.json
tools/keyvault-mock-attestation/package.json

- Bump the min-version of node-jose to 2.1.0 as the min-version
- Remove the maa-ehd field
- Fixes a few vulnerabilities in our dependency tree (mainly identified
vulnerabilities in node-forge < 1.0.0)
- maa-ehd is not necessary and if supplied we shouldn't just put any string in
there. While not harmful for our tests, it's not correct either.

[mock-attestation] - Update node-jose

---

tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_deploy_configmap.tpl

I have another change coming soon for addons so I'll hold off on bumping the version and release until then.
@richardpark-msft @m-redding this should fix the hidden error issue with missing ARM templates.

[stress testing] Fail helm deployments when ARM template does not exist

---

eng/common/scripts/job-matrix/Create-JobMatrix.ps1
eng/common/scripts/job-matrix/job-matrix-functions.ps1
eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1

Fixes #2932
- Fix bug where job matrices with leading numbers generated duplicate job names
- Fail matrix generation when config path or import paths are not found

Fix bug where job matrices with leading numbers generated duplicate job names

---

packages/python-packages/api-stub-generator/CHANGELOG.md
packages/python-packages/api-stub-generator/apistub/__init__.py
packages/python-packages/api-stub-generator/apistub/__main__.py
packages/python-packages/api-stub-generator/apistub/_version.py
src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs

This PR has changes to optimize virtual env creation step to use APP-DATA and symlinks and also run api stub gen using package module.

Run API stub generator using published package

---

eng/common/testproxy/test-proxy-tool.yml

Fixes https://github.com/Azure/azure-sdk-for-go/issues/17461
After adding this and testing it, it seems like it's really just a couple seconds that's needed to ensure the proxy is ready to receive requests. We could consider adding `Start-Sleep 2` as an alternative to all this extra checking.
CC @chlowell

Wait for test proxy startup

---

eng/common/TestResources/New-TestResources.ps1
eng/common/TestResources/Remove-TestResources.ps1
eng/common/TestResources/Remove-TestResources.ps1.md
eng/common/TestResources/SubConfig-Helpers.ps1
eng/common/TestResources/Update-TestResources.ps1
eng/common/TestResources/remove-test-resources.yml

Fixes #1904
This changes the remove resources script to stop referencing the static `AZURE_RESOURCEGROUP_NAME` variable and instead reference the `<SERVICEDIRECTORY>_RESOURCE_GROUP` variable, which can support scenarios where multiple groups are deployed in a pipeline.

Support resource group name override in remove test resources template

---

tools/test-proxy/ci.yml
tools/test-proxy/docker/dockerfile-arm64

@HarshaNalluru unfortunately this doesn't address the issue yet, as recall in a local `concurrent` invocation starts your tests and starts the test-proxy by a _specific target image_.
This PR merely adds a ARM64 image so you can unblock them with a local patch. I don't know if there is any magic I can do behind the scenes on our container registry that would allow us to simply pull from `testproxy-lin` repo and get an appropriate platform. Checking into that now.

[Test-Proxy] Publish an ARM64 Image

---

src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml

Added `swagger` in languages review filter. This will allow users to easily filter swagger reviews only.

Add Swagger review filter

---

eng/common/scripts/ChangeLog-Operations.ps1

- If the version being verified has a date as the release status verify the changelog like it is being released. 
- Removed the strict date verification that check to make sure the date is within the current month. Now it just checks to make sure the date for the verified version is the latest in the CHANGELOG file.
-This should finally resolve https://github.com/Azure/azure-sdk/issues/3690

Verify Changelog Like ForRelease

---

packages/python-packages/api-stub-generator/CHANGELOG.md
packages/python-packages/api-stub-generator/apistub/nodes/_astroid_parser.py
packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
packages/python-packages/api-stub-generator/tests/apiview_test.py
packages/python-packages/api-stub-generator/tests/class_parsing_test.py
packages/python-packages/api-stub-generator/tests/function_parsing_test.py
packages/python-packages/apistubgentest/apistubgentest/models/__init__.py
packages/python-packages/apistubgentest/apistubgentest/models/_models.py

Fixes #3028.  This was a pretty simple bug in the logic to parse decorators.
Closes #3012, #3011, #3010. This was a much more involved fix because inspect cannot see overloads. Instead, I have to parse the source of the enclosing class and parse the decorators from the AST nodes, which is messy (and unfortunate!).
Here's the APIVIew for this. See "SomethingWithDecorators" and "SomethingWithOverloads":
https://apiviewstaging.azurewebsites.net/Assemblies/Review/b821d6b6f4c94d6a907be8773e8767ab
Note that the diagnostics will go away once #2933 is merged. 
Test to verify this addresses recently reported issues:

[Python APIView] Support @overloads and fix issue with parameterized decorators

---

eng/common/TestResources/Remove-TestResources.ps1
eng/common/TestResources/SubConfig-Helpers.ps1

When the deploy test resources step fails before setting the env var, the current error condition can be misleading. We
should still warn but not fail.
[Example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1495413&view=logs&j=0f4ab11a-fb23-53e2-ab9a-978e66fa5cd6&t=85c56a18-30b3-577e-de2a-38f6e10423b8&l=24)
Also rolling in a fix to handle empty service directories failing with a misleading/inscrutable error:
```
Remove-TestResources.ps1: Cannot bind argument to parameter 'Path' because it is an empty string.
```

Do not fail remove test resources step when env var is not set.

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
tools/test-proxy/docker/dockerfile
tools/test-proxy/docker/dockerfile-win

Both avoiding crashing of the .NET usage, but also avoiding random errors when ending the test-proxy application.

[Test-Proxy] Taking advantage of new boolean switch that will dump configuration

---

eng/common/TestResources/New-TestResources.ps1

We need to be able to override the randomly generated basename for stress testing, so that we can use top level values for resources and propagate them across configs (e.g. network blocking for a service bus namespace A record).

Support BaseName overrides in CI mode for New-TestResources.ps1

---

tools/stress-cluster/chaos/README.md
tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_chaos.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_container_env.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_env_volumes.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_env.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_util.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-cluster-secret-provider.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-file-share-secret-provider.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/stress-test-static-secret-provider.yaml

- Fixes #2816
- Moves `.Scenario` into a new helm context `.Stress`, which includes `.Stress.Scenario` and `.Stress.ResourceGroupName`
- Adds a chaos template wrapper to add in custom helm contexts
- Updates stress-test-addons to 0.1.16 which also includes #3047

[stress testing] Add resource group name to helm context. Add chaos wrapper.

---

eng/common/TestResources/New-TestResources.ps1
eng/common/TestResources/New-TestResources.ps1.md
eng/common/TestResources/deploy-test-resources.yml

PR #3145 changed `$BaseName` to generate when null, but our pipelines were actually passing "Generated" such that `$BaseName` was never null. Our validation didn't catch this because they used resource types where it didn't matter, but a number of other live tests failed because other resource types did care (mostly about the uppercase "G").

Do not pass "Generated" to live tests as BaseName

---

tools/sdk-generation-pipeline/packages/sdk-generation-cli/package.json

add the publishLog command back, for it's accidentally deleted
Signed-off-by: Zhou Zheng <zhouzheng@microsoft.com>

bugfix: add the publishLog command back, for it's accidentally deleted

---

eng/common/docgeneration/Generate-DocIndex.ps1

Fixed the toc.yml order by sorting service name first.
After the fix.

Sort by service name first

---

tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/file-plugin/README.md
tools/stress-cluster/cluster/kubernetes/stress-test-addons/file-plugin/bin/file.ps1
tools/stress-cluster/cluster/kubernetes/stress-test-addons/file-plugin/plugin.yaml

This PR adds a helm plugin to make switching between remote and local versions of the stress-test-addons library chart much easier to do. The references can be switched by adding/changing the URL of the stresstestcharts helm repository via the `helm repo` command (which does not support the `file://` by default).

Add helm file plugin and local dependency chart usage readme

---

src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml

- Remove invalid characters from foldableClass so that it is a valid css class name.

Sanitize table foldableClass to be valid css

---

eng/common/scripts/Update-DocsMsMetadata.ps1

Refactor `Update-DocsMsMetadata.ps1` to support batch processing in `$ValidateDocsMsPackagesFn`
It appears that only azure-sdk-for-java and azure-sdk-for-python implement `$ValidateDocsMsPackagesFn`.  Both repos have been updated to support the `-PackageInfos` parameter to `$ValidateDocsMsPackagesFn`

Use the batch version of ValidateDocsMsPackagesFn

---

tools/sdk-generation-pipeline/packages/sdk-generation-lib/package.json

https://github.com/Azure/azure-sdk-tools/security/dependabot?q=is%3Aopen
The drama with the NPM package has subsided, but we can clear this out of our CG alerts as well.

[sdk-generation-package] Bump `colors.js` dependency to address CG alert

---

src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs

API review is refreshed to use latest baseline from main branch if it finds additional change in new commit. But this leads to a new revision ID which invalidates previously generated API review link. So anyone still refreshes previous link will return 404 error.
This PR is to reuse previous revision ID so link will still be valid and any comments added on previous revision will still be visible on API review.

Reuse revision ID when refreshing API review from PR is refreshed 

---

src/swift/SwiftAPIViewCore/Sources/Models/Miscellaneous/TypeModels/TypeIdentifierModel.swift
src/swift/SwiftAPIViewTests/Sources/AttributesTestFile.swift
src/swift/SwiftAPIViewTests/Sources/EnumerationsTestFile.swift

Fixes #3192.
Here's the APIView showing the `@unchecked Sendable` annotation that was breaking (and is new in Swift 5.x):
https://apiviewstaging.azurewebsites.net/Assemblies/Review/b48cf38e94c34e73afdcd02b492ad273

[Swift APIView] Allow attributes in type inheritance clauses

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/appsettings.json

~~On both `go 1.17` and `go 1.18` we generate some wonky headers.~~
- `:authority`
- `:method`
~~It is an artifact of the client, as per my understanding these aren't actually used by the service. Correct me if I'm wrong @seankane-msft~~
~~In the past, we were actually silently omitting them, but we got explicit with [this PR](https://github.com/Azure/azure-sdk-tools/commit/80fc22045fefe1140565e46ae0a768c42c057c3d).~~
~~This PR brings it back to excluding them by default.~~
Kestrel by default listens for both `http/1.1` and `http/2` communication. The issue is that because we were allowing both, the `go` clients don't know which to select. This is why we are seemingly randomly getting `:authority` and `:method` headers. The go client thinks it's talking http/2!
By disallowing test-proxy …

[Test-Proxy] Enforce Http 1.1 only

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/appsettings.json

After beating my face into why [builds fail]() it's due to the fact that when running as a tool relying on the appsettings, something is resolving wonkily within the CI runs for go. 
Specifically, it is still allowing HTTP/2.0 traffic to flow. I can tell this because when I run `test-proxy` locally using the CI-targeted version, it is _still getting_ a `:method` header value and sending with protocol `http/2`.
F5-ed through VS it did _not_ have these issues. That tells me it's something in the resolution of appsettings vs launchsettings vs startup.cs. 
I have confirmed `go` tests pass just fine locally using the version of test-proxy published from this PR branch. Will do another eng/common update and remove the go-override tomorrow.

[Test-Proxy] Remove Reliance on Appsettings, Update Startup.cs

---

eng/common/scripts/Update-DocsMsMetadata.ps1

https://raw.githubusercontent.com/Azure/azure-docs-sdk-java/main/docs-ref-services/preview/sdk-template-readme.md
Metadata definition: https://review.docs.microsoft.com/en-us/help/contribute/metadata-attributes?branch=main

Make docs.ms link relative link

---

eng/common/scripts/Delete-RemoteBranches.ps1
eng/common/scripts/Invoke-GitHubAPI.ps1

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1535947&view=results

Fixed bug of deleting more than expected.

---

eng/pipelines/mirror-pypi-to-dev-feed.yml
eng/scripts/download_targeted_packages.py
eng/scripts/download_targeted_packages_requirements.txt

This has been brewing for a while. I finally hit a situation with
- `api-stub-generator`
- `pylint-guidelines-checker` 
That I couldn't elegantly solve. I don't want to have people needing to remember some wonky installation order or
> install dependencies of package first through this script, then install the package
As such, I will just populate our dev feed with a few packages (and make it super easy to add more). 
@tjprescott  We will be able to target our dev feed as the index url and _no other feeds_, keeping ourselves secure and also making it super easy on command side.
The pipelines in this PR will
- Take the top level packages passed in as parameters
- Evaluate them for their complete dependency tree
- Deduplicate the total dependency tree, find all associated wheels/sdists for …

[Python Dev Feed] Create Pipeline Definition for uploading packages from PyPI

---

src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs

APIView startup runs background tasks continuously for a longer time to update service name and package name and this causes sometimes startup task to time out. This PR is to add a delay between each review details sync so startup task will not have to wait until it's completed.

Reduce APIView startup time

---

tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/PipelineGenerationContext.cs

Using a selective scope (not Full Access) PAT in ADO, REST calls to _apis/sourceproviders/* fail with a no-auth response.  This prevents us from getting GitHub repository details using the ADO rest api.
We're able to create pipelines using the information in hand about the remote repositories, so the client.ListRepositoriesAsync call can be safely removed.

Remove REST calls that are rejected for new PAT

---

src/dotnet/APIView/APIViewWeb/HostedServices/PullRequestBackgroundHostedService.cs
src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs

Currently we don't have any details in app insights about any failure in background tasks. This PR has changes to report exception from background tasks.

Handle startup exceptions and add it to telemetry

---

src/swift/SwiftAPIViewCore/Sources/Models/Declarations/VariableModel.swift
src/swift/SwiftAPIViewCore/Sources/Models/PackageModel.swift
src/swift/SwiftAPIViewTests/Sources/PropertiesTestFile.swift
src/swift/SwiftAPIViewTests/SwiftAPIViewTests.xcodeproj/project.pbxproj

Also ignores compiler control statements.

[Swift APIView] Support default values in willSet/didSet block expressions

---

tools/notification-configuration/notification-creator/NotificationConfigurator.cs

Fix failed pipeline:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1561441&view=results
Root cause:
The failed pipeline is from our pipeline-generator scripts. We used to put {"manageUrl":"\<url\>"} in pipeline repository properties. Since we cannot fetch the properties after renew the devOp PAT, we decided not to generate properties them from repository. This affect notification pipeline which read the repo url from pipeline repository `manageUrl`. The PR is to use another way of retrieving the codeowner
Testing pipeline:https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1561040&view=logs&s=7e5a62c6-a3ae-5561-387a-bc0babb014af

Add exception handling for notification pipeline

---

src/swift/SwiftAPIViewCore/Sources/Extensions/ThrowsKind+Extensions.swift
src/swift/SwiftAPIViewCore/Sources/Models/Declarations/InitializerModel.swift
src/swift/SwiftAPIViewCore/Sources/Models/Declarations/SubscriptModel.swift
src/swift/SwiftAPIViewCore/Sources/Models/Miscellaneous/SignatureModel.swift
src/swift/SwiftAPIViewTests/Sources/InitializersTestFile.swift

Recent refactor dropped `throws` annotations from throwing inits. This PR restores them.

[Swift APIView] Fix issue with throwing inits

---

eng/common/TestResources/New-TestResources.ps1
eng/common/TestResources/SubConfig-Helpers.ps1

These updates allow us to handle service directory parameters like `storage/Azure.Storage.Blobs`. The perf test ARM templates need to reside in directories like this. I also shortened the service name generation in local usage to only use the leaf directory name to avoid naming length restrictions with some resource types (e.g. storage).

[testresources] String parsing improvements to service directory resource names

---

eng/common/TestResources/remove-test-resources.yml

In case people want to leave their resources around for debugging after test failures.
The naming format was chosen to be consistent with our other user-facing Skip variables used in the release pipelines (e.g. [here](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/pipelines/templates/stages/archetype-net-release.yml#L97)).

Add skip variable for remove test resources to support debugging

---

src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs

APIView bot writes a comment even if api changes are not present for a package. This was done as per the feedback but this is causing bot to spam with multiple comments when PR touches large number of packages. Disabling no change comment as interim solution until we come up with a solution to create single bot comment from apiview for entire PR.

Create consolidated APIView comment

---

.github/workflows/event.yaml

**NOTE** Based on feedback, I have moved the main action implementation into its own repository [here](https://github.com/Azure/azure-sdk-actions/pull/1). This PR now contains a simple yaml file for referencing the external repository action.
<hr>
This adds a new implementation of check enforcer intended to be run within a github actions context. To see an example of it running for a repository, check out the [actions in my fork](https://github.com/benbp/azure-sdk-tools/actions).
- Reduce ongoing maintenance and knowledge costs of the current check enforcer. By using github actions we won't have to maintain a check enforcer service ourselves.
- Improve check enforcer scaling. While the current check enforcer app can process webhook events much more quickly than github actions (since it …

Add github action based check enforcer

---

eng/common/scripts/Delete-RemoteBranches.ps1
eng/common/scripts/Invoke-GitHubAPI.ps1
eng/pipelines/branch-cleanup.yml
eng/pipelines/eng-common-sync.yml

Testing on whatif enabled:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1594264&view=logs&j=80f7b2d8-9c8c-53b8-36c5-63dcddd43cb4&t=fd53712b-8238-551a-0702-451e8924fb63
| Central PR | Sync PR status | Sync PR status after work | Branch | Test branch                                                | 
|------------|----------------|---------------------------|--------|------------------------------------------------------------|
| Not exist | Open           | No change | Keep   | sync-eng/common-branch_cleanups-13342                      | 
| Not exist | Otherwise      | No change                 | keep | sync-eng/common-branch_clean-13343                         | 
| Open       | Open           | No change | Keep   | sync-eng/common-branch_cleanup-3342 …

Delete PR and branch which central PR is closed

---

src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
src/dotnet/APIView/APIViewWeb/Repositories/PackageNameManager.cs
src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs

--hide-report is an invalid flag in latest api-stub-generator. Remove this unrecognized flag. 
Fixes #3356

Remove invalid arg to python api stub gen

---

src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs

Host service methods to upgrade reviews and archive pull requests are long running operations and these are run from hosted service start method. Start method should not run longer tasks and this should be run by background hosted service.

Update long running background tasks to BackgroundHostedService

---

eng/common/pipelines/templates/steps/check-spelling.yml

For the most part, this being present is not a big deal. When onboarding services though, ignoring spellcheck errors is usually pretty nice to begin with. It's only after getting all the other integration points figured out do we actually care about those errors.

Spell-check skippable by variable

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TransformTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/AssetsConfiguration.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitAssetsConfiguration.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/IAssetsOperations.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/IAssetsStore.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/NullStore.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/StoreResolver.cs

Fixes #3324
~~- [ ] Document storage functionality in readme~~ I'll document it when adding the _actual_ functionality that will work. All that it has is `NoOp` operations right now.

[Test-Proxy] Support Extensible Storage

---

eng/common/scripts/Save-Package-Properties.ps1

Go package name contains path delimiter and this break current assumption of generated path for json property file for package. This PR is to create property file in nested path based on the package name. for e.g. package name for go is `sdk/template/aztemplate`  then aztemplate.json will be created in `<outdir>/sdk/template/aztemplate.json`

Create json package property parent directory

---

src/go/cmd/api_view.go
src/go/cmd/models.go

PackageName field is not set in Go APIView token file and we use this field to identify automatic review created for a package.
This PR is to set PackageName field.

Update package name in Go APIView token file

---

eng/common/pipelines/templates/steps/sparse-checkout.yml

This will disable those pesky `You are in 'detached HEAD' state` warnings we get in the sparse checkout logs.

Disable detached head warnings on sparse checkout to commit

---

eng/common/scripts/job-matrix/job-matrix-functions.ps1
eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1

This was resulting in verbose job titles where imported matrix display name filters were not being applied.

Fix issue where matrix replace was not using imported display names

---

src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs

New UI accidentally added close button for automatic reviews and user mistakenly closed automatic review. This has caused disruption to release pipeline APIView approval check workflow.

Hide Close button for automatic review and raise exception 

---

eng/common/pipelines/templates/steps/create-apireview.yml

Fixes https://github.com/Azure/azure-sdk-tools/issues/3427

[APIView] Disable build step `Create API Review` for private repos

---

eng/common/docgeneration/templates/matthews/partials/class.header.tmpl.partial
eng/common/docgeneration/templates/matthews/partials/class.tmpl.partial

We have different definition for the order of `<remarks>` and `<examples>`.
Update our template to align with mdoc.
[Link](https://ceapex.visualstudio.com/Engineering/_git/docs-ui?path=/packages/docfx-templates/partials/dotnet/member.tmpl.partial&version=GBmaster&line=14&lineEnd=22&lineStartColumn=1&lineEndColumn=13&lineStyle=plain&_a=contents)
In github io: 
In Docs.ms:

Update the order of remarks and examples to align with docs.ms

---

eng/common/pipelines/templates/steps/credscan.yml

See [this failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1617183&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=27a9db8a-8f0c-5ed5-0322-7c4d0e71b2e0) as an example.
A supply-chain governance task was auto-injected and failed. As a result of incorrect condition settings, we don't run the `setup` of credscan, and as such fail to run it.
This PR will remain on-hold until after release week.

Ensure Credscan job works properly even when wonkiness is auto-injected

---

tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/Dockerfile

Transient Az install failures were not preventing docker build from succeeding and the image pipeline from pushing a bad image.

Force error on failure to install Az

---

eng/common/TestResources/New-TestResources.ps1
eng/common/TestResources/Remove-TestResources.ps1
eng/common/TestResources/deploy-test-resources.yml
eng/common/TestResources/remove-test-resources.yml

- Selects live test or perf test resources

Add ResourceType parameter

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml

Update the Java storage packages to the latest GA versions.  This is specific to Java, since the other languages have not released new GA packages since the last update.
Currently, the perf `tests.yml` needs to be manually updated when new GA packages are released.  This is a known issue that will be addressed soon, either as part of the perf automation refactoring, or sooner as a tactical fix.

[Perf] Update Java storage packages to latest GA versions

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs

Make initial and max heap equal to avoid resizing. But make them depend on RAM size instead of hardcoding.
For reference
https://stackoverflow.com/questions/43651167/is-there-any-advantage-in-setting-xms-and-xmx-to-the-same-value
https://developer.jboss.org/thread/149559

Perf framework

---

eng/common/pipelines/templates/steps/cosmos-emulator.yml

We had continueOnError set to true so if the emulator failed to start we would still try to run the tests which all fail but take a long time to run.  The timeout for this step is about 10mins of trying so that should be enough time and so we also don't really need another retry step.

Fail if the emulator doesn't start

---

eng/common/pipelines/templates/steps/verify-readme.yml
eng/common/scripts/Verify-Readme.ps1

The current verify-readme only takes a single path and there's a need, in Java, to be able to scan multiple paths with a single template call. The changes are as follows:
1. Changed ScanPath to ScanPaths in the powershell script which can now take a single path or a comma delimited list.
2. Coalesce the template variables so we only have a single one being passed into the script. 
3. Overhauled the script adding verification of the inputs, verification that the pip install commands were successful.
For existing pipeline usages, nothing should change.

Update the verify-readme script/template to take a single or multiple paths

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml

- .NET, Java, and Python are adding storage-blob perf tests that require the latest preview to compile and/or run
- Verified no regressions between latest GA and latest preview, so it's safe to use latest preview as the new baseline
- Fixes #3529

[Perf] Upgrade storage-blob packages to latest preview

---

tools/stress-cluster/chaos/README.md
tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
tools/stress-cluster/chaos/examples/stress-deployment-example/stress-test-resources.bicep
tools/stress-cluster/chaos/examples/stress-deployment-example/templates/deploy-job.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/deploy-stress-test-resources.ps1
tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_util.tpl

Resolves #3263
* Adds a 6 character random string `{{ .Stress.BaseName }}` that can be used for naming that doesn't break
validation for resources like service bus, storage, etc. Bicep templates can consume this by adding a `BaseName`
parameter.
* Inject `BASE_NAME` environment variable to deployment init container.
* Add resourceGroupName and baseName labels to job template.

[stress-testing] Flexible resource naming: add BaseName to stress-test-addons helm context

---

eng/common/pipelines/templates/steps/verify-samples.yml

Similar to the [verify-readme.yml](https://github.com/Azure/azure-sdk-tools/pull/3510) changes, update verify-samples to handle multiple service directories.

Enable verify-samples to handle multiple service directories

---

eng/common/scripts/Helpers/Metadata-Helpers.ps1
eng/common/scripts/Service-Level-Readme-Automation.ps1
eng/common/scripts/Update-DocsMsToc.ps1

Our current mgmt toc structure does not have readme in place.
arm packages have their dedicated readme copied to docs repo. It is not linked anywhere in toc. 
The PR is to align mgmt with client packages.
Proposed structure:
```
Overview
Client1
Overview
APIs
Client2
Overview
APIs
Management
Mgmt1
Overview
APIs
Mgmt2
Overview
APIs
```
Here is the testing review site:
https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/?view=azure-node-latest&branch=daily%2F2022-05-02-ci-succeeded
Testing in other langs:
1. Java:https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1685594&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739
Diff in Java:
https://github.com/Azure/azure-docs-sdk-java/commit/a162d01837990b84e6beaa262147a219cea23267
Review site: …

Update mgmt toc structure

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs

- In some scenarios, if there is an OutOfMemoryError inside a Reactor operation, the process may hang instead of crashing
- Adding this flag ensures the test process will crash immediately.

[Perf] Add JVM flag to crash on OutOfMemoryError

---

eng/common/scripts/Helpers/PSModule-Helpers.ps1
tools/stress-cluster/chaos/README.md

Fixes #3497 #3354
The common powershell module helper script contains functions used both in CI scripts and local scripts. However, the script was originally written to target azure pipelines agents. As a result, it does not always work for people when run locally. This PR moves powershell module path overwriting behind a flag so it only runs when needed in CI environments.
Also I'm shoehorning in a minor doc update on app insights keys.

Only update/override powershell module path when in CI on module script import

---

eng/common/scripts/SetTestPipelineVersion.ps1
eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml

- Fix null errors in SetTestPipelineVersion
- Rename Publish Packages to Upload Packages in azuresdkpartnerdrops-to-nugetfeed.yml

Fix null errors in SetTestPipelineVersion

---

eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
eng/common/scripts/SetTestPipelineVersion.ps1

This is the same type of changes I've made to verify-readme and verify-samples. Add an argument to the yml file, PackageNames, that'll accept a comma separated list of package names. Coalesce PackageName and PackageNames to snag whichever one is set.
The script file just splits on comma into an array and processes them individually. 
The reason I'm doing this is because Java has multiple template libraries and instead having [3 consecutive templates](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/pipelines/templates/stages/archetype-java-release-batch.yml#L95), one for each library, in several different places, I want to use the template once and give it all 3 of our template libraries.

Update set-test-pipeline-version logic to handle one or more packages

---

eng/common/pipelines/templates/steps/sparse-checkout.yml

The latest update to git 2.37.0 adds cone and non-cone mode options [explanation](https://github.blog/2022-06-27-highlights-from-git-2-37/#tidbits). In code mode, our previously used sparse checkout pattern filtering does not work, as the command expects directories instead. This PR updates our sparse checkout command to set `--no-cone` for no cone mode.

Use --no-cone in pipeline sparse checkout script

---

tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/ApplicationInsights/ApplicationVersionTelemetryInitializer.cs
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/BlobUploadProcessor.cs
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/PipelineWitnessSettings.cs
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/BuildCompleteQueueWorker.cs
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/BuildLogBundleQueueWorker.cs
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/QueueWorkerBackgroundService.cs
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.development.json
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.json

- Improve logging in PipelineWitness
- Add support for multiple workers per queue (in-process scaling)
- Add support for updating config at runtime (useful when locally debugging)
- Stop enqueueing messages for async log processing.  Because failure analysis requires loading log files and because we no longer have a function execution time limit, we should stay in process and complete the build blobs as a single queue message
- The queue processing loop should throw an exception if the message renewal task cannot extend a message lease

Improve logging in PipelineWitness

---

src/dotnet/APIView/APIView/CodeFileRenderer.cs
src/dotnet/APIView/APIViewTest/CodeFileRendererTests.cs

Line ID is used to identify where to show each comment and this line Id is stored in cosmos DB. So any run time alteration to this line ID will cause a mismatch and comments will not be displayed in main review page.

Skip updating line ID when rendering review file

---

src/dotnet/APIView/APIViewWeb/Filters/TelemetryIpAddressFilter.cs
src/dotnet/APIView/APIViewWeb/Startup.cs

Remove IP address from app insights telemetry to disable collecting Geo info.
Fixes #3139

Remove IP address information from telemetry

---

eng/common/testproxy/test-proxy-docker.yml
eng/common/testproxy/test-proxy-tool.yml

@iscai-msft is hitting issues when running tests just prior to autorest release. As part of that release verification, they need to run storage against the latest version just prior to release. Now that storage uses test-proxy, that is breaking in their pipeline.
To enable this, I originally referred @iscai-msft to pull in the repo using 
```
resources:
repositories:
- repository: azure-sdk-tools
type: git
name: Azure/azure-sdk-tools
ref: refs/heads/main
```
But they can't simply activate the template, because the template _assumes_ that it is in the original `$(Build.SourcesDirectory)`. This PR just backs that assumption out, without changing anything if you don't provide an argument.

[Test-Proxy] Allow eng/common/testproxy to be used via external reference

---

packages/python-packages/api-stub-generator/apistub/_apiview.py

Python parser needs to set parser version in code file so offline generated code file can be tagged using correct version number so auto upgrade will upgrade these reviews as well when parser is changed. This is part of the work to generate API code file outside APIView server.
Fixes #3627

Add Parser version in Python APIView code file

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

I hit this issue while trying to use the new Transport customization feature from a real client. Apparently, the object in the `dictionary<string, object>` is actually a `JsonElement` (System.Text.Json) rather than a `JObject` (NewtonSoft).

Fix deserialization of Transport config

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml

Since we don't share OkHttp instances (with pools and threads) we should give it opportunity to compete with netty where it makes sense with current setup.

Tweak parallelism for core tests.

---

packages/python-packages/api-stub-generator/apiview_reqs.txt

I believe this does need to be updated for apiview to have the new checker/warning fixes, as ApiView does not pull in the pylint changes automatically.

[ApiView] updating pylint dep

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml

Reverts Azure/azure-sdk-tools#3707
After finding this https://github.com/Azure/azure-sdk-for-java/pull/30072 .

Revert "Tweak parallelism for core tests."

---

tools/test-proxy/documentation/trusting-cert-per-language.md

eng/common/testproxy/import-dev-cert.sh ->
eng/common/testproxy/apply-dev-cert.sh

Docs: filename typo in eng/common/testproxy

---

eng/common/pipelines/templates/steps/sparse-checkout.yml

We sometimes have issues with the sparse checkout pipeline step. When it breaks, it breaks almost all pipelines. This change adds a failsafe to clone the full repository normally when sparse checkout fails.
For example, this recent failure highlighted the need for more resiliency with this core step:
https://github.com/Azure/azure-sdk-tools/pull/3606.

Add full clone fallback to sparse checkout

---

eng/common/scripts/Detect-Api-Changes.ps1

Create API review from pull request using code file created by CI. APIView will use this approach instead of converting artifact to code file within server if review file name is passed as a parameter.

Detect API changes using pre-generated code file by CI approach

---

tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Chart.yaml
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Dockerfile
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/poll.sh
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/templates/network_loss.yaml
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/templates/testjob.yaml
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/values.yaml
tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_container_env.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_util.tpl

Resolves #3743
The current basename approach is causing issues with chaos policies correlating to test jobs, because the random shortnames generated for the BaseName property used in the templates does not match up on subsequent invocations.
- Use deterministic shortname for stress BaseName
- Add network stress example with scenarios and basename targeting

Use deterministic shortname for stress test BaseName

---

eng/pipelines/apiview-review-gen-python.yml
eng/pipelines/templates/steps/apiview-review-gen.yml
eng/scripts/Create-Apiview-Token-Files.ps1
eng/scripts/Create-Apiview-Token-Python.ps1

New pipeline to create stub file outside APIView web app

Sandboxing changes: create apireview gen pipeline

---

src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs

APIView returns 500 server error even when authorization fails for API detect change request comes from PR pipeline. This PR is to  return 401 in case of auth failure so SDK automation can handle it.

Return 401 error code if org info is not available for PR owner

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/NumberFormatterTests.cs
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/NumberFormatter.cs
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs

Language PRs which show results before/after this change:
* https://github.com/Azure/azure-sdk-for-net/pull/30170
* https://github.com/Azure/azure-sdk-for-java/pull/30187
* https://github.com/Azure/azure-sdk-for-js/pull/22742
* https://github.com/Azure/azure-sdk-for-python/pull/25462

[Perf] Display results with 4 significant figures

---

eng/common/TestResources/setup-environments.yml

The name of this step is misleading and needed renaming.

Fix misleading step name in az module install

---

src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
src/dotnet/APIView/APIViewWeb/Controllers/ReviewController.cs
src/dotnet/APIView/APIViewWeb/Languages/LanguageProcessor.cs
src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
src/dotnet/APIView/APIViewWeb/Models/ReviewGenPipelineParamModel.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
src/dotnet/APIView/APIViewWeb/Repositories/BlobOriginalsRepository.cs
src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs

Server-side changes to support converting artifact to API review code file using pipeline instead of running inside APIView server

Server changes to create manual and upgrade required API reviews using pipeline(sandboxing)

---

tools/test-proxy/documentation/trusting-cert-per-language.md

During our setup at the Open Source Software Contribution Academy (OSSCA) in Korea, we had trouble with the `SETX` command because people overlooked the last line and filepath. We've tried to make it clear in the documentation.
Please consider this commit from a student's point of view.
Thank you so much for your hard work and fantastic repo.
Love from Korea!

[test-proxy] add disclaimer and specificity to docs

---

src/java/apiview-java-processor/pom.xml
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java

The indentation error and HTML escape characters have been rectified. The padding around the first line in each text section was deemed an APIView bug and an issue has been created to address it.
Fixes #3769 
**Indentation Before/After:**
**HTML escape characters Before/After:**

Improved Java reference docs in APIView

---

src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml

Revision and Diff drop down labels are in in upper case.

Fix label case in review dropdown

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/results/java.json
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/results/js.json
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/results/net.json
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/results/python.json
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/TableGenerator.cs

- Change percentages from two to one decimal place, since our results are not stable enough to justify two decimals
- Update sample results to 4 significant figures
- Fixes #3703
```
|----------|----------------------------------------------------------|---------|---------|---------|
| Test     | Arguments                                                | 12.10.0 | source  | %Change |
|----------|----------------------------------------------------------|---------|---------|---------|
| download | --size 10240 --parallel 64                               | 14,999  | 16,317  | 8.79%   |
| download | --size 10485760 --parallel 32                            | 166.8   | 166.5   | -0.19%  |
| download | --size 1073741824 --parallel 1 --warmup 60 --duration 60 | 0.1100  | 0.1200  | 9.09%   |
| …
```

[perf] Right-align numerical values in tables

---

packages/python-packages/api-stub-generator/CHANGELOG.md
packages/python-packages/api-stub-generator/apistub/_stub_generator.py
packages/python-packages/api-stub-generator/apistub/_version.py

APIView code file created on Ubuntu and Windows machine has modules listed in code file in different order even though same version of Python and APIStubGen parser used. So order of module names is not guaranteed. This PR is to sort module name before we parse individual modules to ensure it is listed in correct sort order.

Create API review using modules in consistent order

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/StringSanitizer.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/RegexEntrySanitizer.cs

Add `RegexEntrySanitizer`

---

tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj

I didn't see any references to `Azure.Storage.Blobs` in the code, and it seems to build fine without this dependency, so I think it can be removed.

[check-enforcer] Remove unused dependency Azure.Storage.Blobs

---

packages/python-packages/api-stub-generator/CHANGELOG.md
packages/python-packages/api-stub-generator/apistub/_apiview.py
packages/python-packages/api-stub-generator/apistub/_stub_generator.py
packages/python-packages/api-stub-generator/apistub/_version.py
packages/python-packages/api-stub-generator/apistub/nodes/_pylint_parser.py
packages/python-packages/api-stub-generator/apistubgen.py
tools/pylint-extensions/pylint-guidelines-checker/pylint_guidelines_checker.py

Closes #3842.
This PR changes APIView so that if pylint parsing fails (for whatever reason), rather than causing APIView to exit with error code 1, which fails CI, instead it will generate the APIView and add an error diagnostic. The diagnostic directs the team to reach out to us to figure out why parsing fails.
See example:
https://apiview.dev/Assemblies/Review/f22f5092d8fd4179b52f81e78a2281fc

[Python APIView] Add error diagnostic if pylint parsing fails rather than fail APIView (and thus CI)

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/TransportCustomizations.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

@lynshi @mccoyp 
Users can now say:
> apply this for this hostname only.
And a standard server validation callback will be used otherwise.
Example updates to your unit tests: 
Am facing a new issue when recording though. It doesn't look like we're getting a valid key back.
The value we're getting is `----BEGIN CERTIFICATE KEY-----\n` and that's it 👍 
Specifically, this is the setting from [the second `SetRecordingOptions()` ](https://github.com/lynshi/azure-sdk-for-python/blob/50ffaf746bf05c11ef6924c4c5c126fbbc0de60b/sdk/confidentialledger/azure-confidentialledger/tests/test_confidential_ledger_client.py#L83)
I will push the test changes directly to your branch after the new version of the proxy is published and follow-up on the new error.

[Test-Proxy] Add Optional Specificity to the TLSValidationCert

---

packages/python-packages/api-stub-generator/CHANGELOG.md
packages/python-packages/api-stub-generator/apistub/_diagnostic.py
packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
packages/python-packages/api-stub-generator/apiview_reqs.txt

Fixes #3712.
Example:
https://apiview.dev/Assemblies/Review/bb9acfe54154462fb036f502819d90c3
Rev 0 represents the original behavior.
Rev 1 represents the fix.
Note: this _will_ cause a diff between 0.3.3 because it changes how the line id is calculated for these inherited methods.

[Python APIView] Fix issue with duplicated diagnostics

---

eng/pipelines/publish-docker-image.yml

Resolves #3907
Example definition highlighting what a `stabletag` looks like: https://github.com/Azure/azure-sdk-tools/blob/e72dc36392d5eee4605ba3711586a6460880537b/tools/test-proxy/ci.yml#L56-L60
[Additional Build Highlighting Tag Overwrite Works](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1775143&view=results)

Honor `stabletags` variable

---

src/dotnet/APIView/APIViewWeb/Models/ReviewRevisionModelList.cs
src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs

PR API reviews generated from pull request for a brand-new package (package doesn't exists in repo) is creating duplicate revisions within review and this is causing an issue when reviewing such API reviews. This PR is removing any such duplicate revisions when a new request for that review comes as well as to avoid such duplicate revisions in the future.

Remove duplicate PR API review revisions

---

src/go/cmd/api_view.go
src/go/cmd/api_view_test.go
src/go/cmd/content.go
src/go/cmd/module.go
src/go/cmd/pkg.go
src/go/cmd/testdata/test_alias_diagnostics/go.mod
src/go/cmd/testdata/test_alias_diagnostics/internal/internal.go
src/go/cmd/testdata/test_alias_diagnostics/test.go
src/go/cmd/token_makers.go

Issue a diagnostic error if an exported, aliased type contains nested
types that aren't exported from the same package.
Include methods for aliased types in the source package.
Removed references to ioutil as it's been deprecated.

Improvements around aliased types

---

packages/java-packages/codesnippet-maven-plugin/CHANGELOG.md
packages/java-packages/codesnippet-maven-plugin/README.md
packages/java-packages/codesnippet-maven-plugin/pom.xml
packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetDictionary.java
packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java

Adds an explicit error message when codesnippet aliases have mismatch BEGIN and END tags.

Explicit Error Message for Mismatch BEGIN and END Aliases

---

packages/java-packages/codesnippet-maven-plugin/CHANGELOG.md
packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
packages/java-packages/codesnippet-maven-plugin/src/test/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacerTests.java
packages/java-packages/codesnippet-maven-plugin/src/test/resources/project-to-test/basic_readme_insertion_before.txt
packages/java-packages/codesnippet-maven-plugin/src/test/resources/project-to-test/full_class_parse.txt
packages/java-packages/codesnippet-maven-plugin/src/test/resources/project-to-test/full_class_readme_insertion_after.txt
packages/java-packages/codesnippet-maven-plugin/src/test/resources/project-to-test/full_class_readme_insertion_before.txt

Fixes an issue where non-indented codesnippets wouldn't be injected properly into READMEs.

Fix codesnippet-maven-plugin Bug with Full Class Codesnippets

---

src/go/cmd/api_view.go

Allows support for the poorly named "internal" module.

Only skip /internal sub-directories

---

tools/stress-cluster/chaos/README.md

The access and quick setup sections were intended to illustrate the underlying commands run by our scripts, but in practice they mostly confuse new users who get hung up running these commands and not the actual deployment script which handles edge cases better.

Update stress readme to remove misleading sections

---

packages/python-packages/api-stub-generator/CHANGELOG.md
packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
packages/python-packages/api-stub-generator/tests/class_parsing_test.py
packages/python-packages/apistubgentest/apistubgentest/models/__init__.py
packages/python-packages/apistubgentest/apistubgentest/models/_models.py

Allow type aliases with `typing.NewType`

---

eng/pipelines/publish-docker-image.yml

The original change that added this code turned out to be unnecessary, but I left it in for cohesion.
Now I realize _why_ I left it out to begin with. We cannot have a docker login on a part of the build that runs on `public`. It'll just fail, rightfully so.
[Manually queued proxy build showing the issue is fixed.](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1822286&view=results)

Repair Test-Proxy public CI

---

eng/common/pipelines/templates/steps/update-docsms-metadata.yml

This was causing `checkout: none` to appear twice in release pipeline yaml, which caused someone to add `SkipDefaultCheckout` to the sparse checkout parameters in order to avoid the conflict. However, this meant that we were then doing full clones in some places.

Remove unnecessary checkout: none that causes conflicts with sparse checkout declarations

---

eng/pipelines/notifications.yml

Adds notification configurations for azd pipelines. 
Example successful pipeline run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1821283&view=logs&j=bc477995-0c4a-574b-536f-2e0d94a7118e&t=330da002-0be6-5a2c-2b14-ef5f270c12c9&l=191

Add notification for azd failures

---

eng/common/pipelines/templates/steps/docs-metadata-release.yml
eng/common/pipelines/templates/steps/sparse-checkout.yml
eng/common/pipelines/templates/steps/update-docsms-metadata.yml
eng/pipelines/templates/steps/sync-directory.yml

Attempting to find a name for this parameter that causes less confusion

Migrate SkipDefaultCheckout to SkipCheckoutNone

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpRequestInteractions.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/IAssetsStore.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/NullStore.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Vendored/LightweightPkcs8Decoder.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Vendored/PemReader.cs

@JimSuplizio for FYI.
Related to #4056
This PR is intended to cover the gap between `planning` and `execution` for the asset sync shims.
I am working through .NET and Python tests to ensure we cover our bases.
Currently:
We may want to adjust the efficiency of the check for whether or not an assets.json is restored to save the server disk querying.

Test-Proxy Integration updates

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/ShortHashGeneratorTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ShortHashGenerator.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitAssetsConfiguration.cs

Right now, pulling the assets locally will result in a pretty long path. This was partially the result of using the AssetsRepo (which is something like Azure/azure-sdk-assets converted to Azure-azure-sdk-assets) and the hex string from the hash computed from the AssetsJsonRelativeLocation (which is something like sdk/<service>/assets.json). Unfortunately, the hex string from the hash ends up being 40 characters. Converted the same hash to base64 still produces a character string that's 28 characters, which is too long. It can also produce non-alphanumeric characters which won't be okay for a directory name. 
We needed something "good enough" to make things unique to prevent on disk collisions when pulling assets but also reproducible, the same inputs need to generate the same string. …

Shorten the internal assets SHA

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitStoreTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationResetTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationRestoreTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitAssetsConfiguration.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

[Asset-Sync] Use tags not branches

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

This will allow us to hoist a bunch of calculations as necessary. Right now, I'm using it to track which tag is currently checked out by the assets repo. 
Probably still need to force the GitProcessHandler to wait for the previous git command in the targeted directory to resolve before invoking, but this is still valuable.
Resolves #4081
Also Resolves #4056

Optimize `Restore` path to leverage a local cache

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs

This is being done for the following [bug](https://github.com/Azure/azure-sdk-tools/issues/4116).

Temporarily disable the git version check on Windows

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/TaskQueue.cs

This PR ensures that we will ever run git commands in **serial** against a given working directory. Controlling per directory means that concurrent tests from various service areas will still be able to work alongside each other.
@benbp what do you think about this? I like that it is _entirely_ atomic to the class. When we move this guy to a common core, this functionality should definitely merge IMO.

Control Parallel Git Invocation

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/EnvironmentConditionalSkipTheory.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
tools/test-proxy/tests.yml

The push tests, when running on in automation, were failing because the commit message didn't have the user.name or user.email set when running on the lab machines. 
1. Change the token environment variable to GIT_TOKEN
2. Add GIT_COMMIT_OWNER and GIT_COMMIT_EMAIL as environment variables to the server in tests.yml
3. If neither of the environment variables in step 2 are set, check git for these values. If those aren't set, I'm probably going to have to prompt the user to enter them. That is still to be decided and part of this PR.
Right now, this PR is to unblock the failures that are happening when running **tools - test-proxy - tests** pipeline.

Fix push tests by adding user.name and user.email to the commit

---

tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/BlobUploadProcessor.cs

Retries of builds in the same day weren't being exported to Kusto because their blob paths already existed.  This change makes the blob path unique to the retry by adding a date component to the build blob paths.
This may introduce duplicates for builds that are being processed during deployment. This is acceptable as duplicates should be expected in kusto and filtered out in-query

Add a time component to build blob paths

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/JavaScript.cs
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml

- Fixes #4131 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1854773&view=logs&j=e9a82041-32c4-5afc-7c62-6957ea0e4504&t=0431ff2a-151f-558c-7484-13e3a9e1b0ea&l=26
All package versions are aligned (except for outlier `core-tracing`), all source versions point to source tree.

[Perf] Pin versions of JS core packages

---

tools/test-proxy/docker/dockerfile
tools/test-proxy/docker/dockerfile-win
tools/test-proxy/docker/windows-git-install.ps1

So that the `gitstore` has something to operate against.
Verified presence of git by changing ENTRYPOINT to `git --version` locally before submitting.
Resolves #4139

Update docker files to have `git` available

---

src/dotnet/APIView/APIViewWeb/Client/css/site.scss
src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml

This updates the comment parser to be line-by-line, including parsing code blocks, so that newlines are not squashed by the inbuilt method. This resolves #4030.
Before:
After:
Here we have a comment that spans several lines.
This should be on a new line. 
\```
// This is a java code block
System.out.println("Hello, world!");
int i = 0;
\```
And a continued comment.
Now an additional paragraph, to test all cases I am aware of.
Here we have a comment that spans several lines.
This should be on a new line. 
```
// This is a java code block
System.out.println("Hello, world!");
int i = 0;
```
And a continued comment.
Now an additional paragraph, to test all cases I am aware of.

Adding paragraph support in comments

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationRestoreTests.cs

During integration I sometimes see _nothing_ and I'm trying to figure out the scenarios that cause that.

Adding one restore test that checks for expected exceptions

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

Adds a lock around the critical section that modifies the entries list.

Fix race condition in RecordingHandler when there are concurrent requests

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.sln
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandParserOptions/CLICommandOptions.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandParserOptions/DefaultOptions.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandParserOptions/PushOptions.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandParserOptions/ResetOptions.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandParserOptions/RestoreOptions.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandParserOptions/StartOptions.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs

This is the initial CLI (subject to change) using CommandLineParser. The CommandLineParser directory contains the command hierarchy.
- DefaultOptions.cs is the base for all CommandLineParser verbs.
- CLICommandOptions.cs inherits from DefaultOptions and adds the option common to all CLI command verbs (push, reset and restore)
- PushOptions.cs, ResetOptions.cs and RestoreOptions.cs are pretty empty right now as they don't have any command specific options.
- StartOptions.cs contains the options specific to start. There's one thing of note here the AdditionalArgs is defined differently than every other option. The reason being is this, we needed the ability to pass additional options that would get consumed by Host.CreateDefaultBuilder. This may or may not be there and could be of an …

Initial CLI using CommandLineParser

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs

Effectively, use the current `context` directory as the "root" if we receive an assets.json that isn't fully qualified.
EG:
Absolute Reference:
```json
"x-recording-assets-file": "C:/repo/sdk-for-python/sdk/tables/assets.json"
```
versus:
Relative Reference:
`<test proxy started in C:/repo/sdk-for-python>`
```json
"x-recording-assets-file": "sdk/tables/assets.json"
```
We're doing this so that folks can run the docker _with a command_ that passes in the relative path to their assets.json (so that writing can actually happen).

Support Relative AssetsJson Paths

---

tools/perf-automation/tests.yml

- Depends on https://github.com/Azure/azure-sdk-for-cpp/pull/3953

[Perf] Add Cpp to test pipeline

---

tools/js-sdk-release-tools/package.json
tools/js-sdk-release-tools/src/hlc/generateMgmt.ts
tools/perf-automation/tests.yml
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
tools/test-proxy/test-scripts/CLIIntegration.Tests.ps1
tools/test-proxy/test-scripts/assets.Tests.Helpers.ps1

1. Update Start.cs to deal with a CommandLineParser [issue](https://github.com/commandlineparser/commandline/issues/849). If a default verb is set, CommandLineParser doesn't verify whether or not the verb passed in is actually a supported verb. It assumes it to be the default verb. Something like "test-proxy foo" would end up running test-proxy start instead of erroring. The VerifyVerb function checks for this and outputs an error message that would be output by CommandLineParser if there were no default verb and an incorrect verb was passed in.
2. GitStoreIntegrationPushTests.cs - Just updated the description here. These tests changed purpose when we went from branches to Tag. They're now similar tests but acting on different Tags that have different files and different file versions.
3. …

Initial push of CLI command line tests

---

src/dotnet/APIView/APIViewWeb/Pages/Shared/_SampleCommentFormPartial.cshtml

Fixes usage sample comments believing they are locked without potential to toggle (checkbox beside creation button)

(Hotfix) Adding resolution locking checkbox to usage sample comments

---

tools/test-proxy/docker/dockerfile

When locally testing, I was building and running on WSL.
The published images are built on Ubuntu.
Unbeknownst to me, due to my test platform, the `test-proxy` shell script that I add to the container will execute. However, when invoking the container built on ubuntu, it fails as we never properly `chmod`-ed the test-proxy shim.
This PR takes care of that.

Hotfix `test-proxy` executable in dockerfile

---

eng/pipelines/apiview-review-gen-swagger.yml

Azure Devops .Net client doesn't allow to pass run time parameters and parameters passed to pipeline run are set as variables. So this PR is read inputs to API review gen as variables.

Update swagger review gen pipeline to use variables

---

src/dotnet/APIView/APIViewWeb/Languages/SwaggerLanguageService.cs
src/dotnet/APIView/APIViewWeb/Repositories/BlobCodeFileRepository.cs

Updated code file is not refreshed in cache so this causes unnecessary blob fetch.

Store updated code file in cache

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/documentation/asset-sync/README.md

Update the Azure.Sdk.Tools.TestProxy/README.md and documentation/asset-sync/README.md to accurately reflect the CLI commands and start arguments.

Update Readmes for TestProxy CLI

---

src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java

fixes #4052 
Issue introduced with #3806 - I'm assuming that this issue was fixed twice, and it ended up giving a negative indentation twice, causing the documentation to be indented one level below the code it documents.
Before fix:
After fix:

Solved formatting issue in Java API view

---

eng/scripts/live-test-resource-cleanup.ps1

This fixes an issue where we fail trying to update groups that are already being deleted, e.g. [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1895128&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=2ae92968-c003-547a-10d9-00fa5e34d21d&l=99).

Only add DeleteAfter tag to resource groups in terminal state

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitStoreTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

Without this bugfix, our autorestore was totally broken where a prefix path is used.

Properly Handling `AssetsRepoPrefixPath` when autoretrieving a recording file

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

@mikeharder I definitely want your opinion here. I probably should be doing this a bit safer.
@timovv your little test scenario repro test was **god tier** here. Thank you so so much for the easy repeatability. (they pass after this code change).

`Test-Proxy` shouldn't add `Content-Length:0` if one exists

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

Ensure that a multi-value `Transfer-Encoding` header is properly checked

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

This is due to the fact that comma separated `Transfer-Encoding` values EG: `gzip, chunked` are _not_ split into multiple StringValues entries. We have to split them ourselves.

Adding deeper nested check of chunked transfer-encoding

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs

- Bunch of small files
- Couple of large files
This is an attempt at repro-ing the issue #4286
I've got a working solution that I really like the look of. We shouldn't ever get in a deadlock situation now, and the LargePushPerf tests are passing locally for the worst case scenario (1000 files of ~150KB random bytes each)

Updating how Test-Proxy shells out, adding tests for long running add operations

---

eng/common/scripts/Verify-Links.ps1

We have hit a few 50x errors while pulling a page to get links and that has caused the rest of the link checking to terminate early. To fix that we switching to LogError which will output an error in devops instead of Write-Error which terminates immediately. We also add some retry count to the page retrieval and cache file retrieval to help with these transitent 50x issues.

Fix 50x errors while loading page links

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

The test scenario isn't being added with this PR as it'll take a bit of time. The scenario is this:
1. Restore into the default .assets directory from an existing tag.
2. Push another tag from somewhere else
3. Try to restore that tag into the default .assets directory from step 1. <-- this step will fail
The problem is that restore does a git fetch origin which won't pull new tags. The fix is just to change it to git fetch --tags origin which will get the tags.

Add --tags to git fetch

---

src/dotnet/APIView/APIViewWeb/Client/src/review.ts
src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/RequestedReviews.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/RequestedReviews.cshtml.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs

Resolves #2281
This adds a dropdown as follows to each review created:
You can either check the boxes of each user you want to select, or hit request all and request every listed approver. This will be improved to just be language-specific approvers after #4164. Email notifications to approvers should also come once this issue is resolved.
One a request is submitted, the reviewers get a page as follows:
The top table in unapproved reviews, sorted by newest first, and the bottom is approved reviews, sorted by most recently approved. The bottom table is limited to 1 week since approval was given.  
Additional note, once the user profile system is there, the IConfiguration could also be removed once again from Reviews.cshtml.cs and replaced with a different method to get approvers from the …

Review assignment/requesting 

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitStoreTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

Remove directory climbing for assets.json. The path to the assets.json is either the full path to the assets.json file or it is the directory in which the assets.json file exists. Don't climb the directory looking for it.
In GitStore.cs renamed FileName, which is the name of the assets.json file, to AssetsJsonFileName to more clearly define what it refers to.
Also added a test case for #4339, which adds --tags to git fetch.
Fixes #3960

Remove directory climbing for assets.json

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitProcessHandlerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandParserOptions/DefaultOptions.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
tools/test-proxy/transition-scripts/README.md

Previously, test proxy was printing out its own version string which was `1.0.0-dev.1.0.0-dev.20221007.1` which required us to have a version option on all of our commands because CommandLineParser's --version option was disabled. This change removes our version and uses CommandLineParser's default version, `Azure.Sdk.Tools.TestProxy 1.0.0-dev.20221011.1`, which differs from the previous version in that it outputs the binary name along with the version as well as the version, itself. I think the original version wasn't quite right anyways.
This also means that executing test-proxy --version will immediately return and --version cannot be executed as part of a command. I've updated the README to reflect this.
This is part of the fix for #4352
Enable the git version check and set the min …

Use CommandLineParser's --version

---

src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadInnerPartial.cshtml

Restore changes added in https://github.com/Azure/azure-sdk-tools/pull/4113/files, removed in error by https://github.com/Azure/azure-sdk-tools/pull/4091

Restore Paragraph Support in Comments

---

src/dotnet/APIView/APIViewUITests/SmokeTests.cs

- Disabling UI test due to flakiness.
- They will be re-enabled as part of more comprehensive testing work https://github.com/Azure/azure-sdk-tools/issues/4196

Disable UI test

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1

1. Add a min test-proxy version check to generate-assets-json.ps1
2. Moved the git version check from Main into Run method in Startup.cs. The reason for this was that when running test-proxy --version it was spitting out the stdout from the git --version check. The check was in the wrong place. We shouldn't check the git version until we've successfully ensured that the command has been parsed and is valid.
3. Minor tweaks to test-proxy's README.md. Add the uninstall command and updated the link to the dev feed. 
Fixes #4352

Add a min proxy version check to generate-assets-json.ps1

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md

This updates the install command to be more flexible:
1. Removing the leading `>` so that you can click the copy button on the code snippet and have a runnable command on paste.
2. Changing `install` to `update` so that the command works even if you already have an older version. `update` still works if you don't have it installed.
3. Surrounding the version glob in quotes since some shells will try to do expansion on them.

Improve test proxy install command

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs

Couple things here:
1.  Just as `--help` and `--version` are default options, apparently `help `and `version `are default verbs. Add those to the verify verb array so they behave correctly.
2. `help`/`--help` and `version`/`--version`, parse as errors which is totally awesome, but not really. @benbp, this is why you were seeing exit code of 1, when running help and version. Before exiting with an exit code of 1, check to see what the error tag is. If there's only 1 error and its tag indicates a help or version request error, then exit 0 since that means the user only requested help or version. Note: ErrorType.HelpVerbRequestedError is the ErrorType you see with `help` but help used to be ErrorType.HelpRequestedError I added both in case they change this. `version` only has one ErrorType, …

Fix help and version

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Cpp.cs

since the presence of the ENV triggers the build against the vcpkg published version needs to be removed when we build against source

need to remove ENV for source compile

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Console/ConsoleWrapperTester.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

This update makes an attempt to discover if the user is using ssh-based authentication to github by looking at the url of the remote for the local repository. If the user is not in a repository, default to the https remote. We could consider adding a flag to override, but I think it's better to try to just handle it automatically rather than introduction an extra option. I think the number of people trying to run test proxy outside of a repo context AND using ssh is going to be rare.
I don't have a great idea for how to detect ssh based auth otherwise, aside from maybe checking if there's a credential store being used (but I don't think that guarantees it one way or the other). There are also options like `git push --dry-run` to see if one protocol or the other works, but that gets …

Support test proxy asset sync commands and tests with git ssh login

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
tools/test-proxy/docker/dockerfile
tools/test-proxy/scripts/transition-scripts/README.md
tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1

1. Add an update to enable proxy to handle git directory ownership warnings when in container mode
2. Add documentation and tooling for handling github ssh authentication in container mode
3. Make all readme code snippet commands copy/paste runnable

Minor fixes for test proxy asset sync container mode issues

---

src/dotnet/APIView/APIViewWeb/Pages/Assemblies/RequestedReviews.cshtml.cs
src/dotnet/APIView/APIViewWeb/Repositories/CommentsManager.cs
src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs

Added new cosmos query to fetch only review requested API reviews from cosmos DB to avoid fetching all and filtering in app side.
I have also commented loading GitHub users to avoid issue in loading some reviews due to GitHub exception. I will submit another PR to load these user details as background task and cache it,

Fetch only review requested API reviews for logged in user

---

tools/test-proxy/documentation/test-proxy/trusting-cert-per-language.md

I had issue setting up my mac, and found out that I have customized proxy environment vars in my .zshrc file, update the doc  for troubleshooting

Update docs/trusting-cert-per-language for Mac

---

eng/scripts/Github-Project-Helpers.ps1

This is something we're having to do a bit more of lately, so I decided to automate it. The code favors "any source" for our required status checks.
The only unknown is I'm not sure how this will behave when the extra 2fa for admin changes is expired, since I currently have it set. I will do a test update tomorrow.
Example run:
```
$ Add-BranchProtectionCheck -org Azure -repo "azure-sdk-tools" -ruleName "license/cla" -WhatIf
Backing up original rules to Azure.azure-sdk-tools.main.required-checks.20221018.011815.json
New rules: [{"context":"https://aka.ms/azsdk/checkenforcer","app_id":null},{"context":"license/cla","app_id":-1}]
What if: Performing the operation "Add-BranchProtectionCheck" on target "Add rule license/cla for main?".
$ Remove-BranchProtectionCheck -org Azure -repo …
```

Add automation for updating github branch protection required status checks

---

eng/common/spelling/Invoke-Cspell.ps1
eng/common/spelling/package-lock.json
eng/common/spelling/package.json

to address dependabot issue https://github.com/Azure/azure-sdk-for-js/security/dependabot/13

Upgrade cspell packages to version `^6.12.0`

---

eng/common/scripts/Update-DocsMsToc.ps1

Docs toc linked to the readme information for Overview page.
.NET uses different readme path than other languages. 
.NET: `api/overview/azure`. Ref [link](https://github.com/Azure/azure-docs-sdk-dotnet/tree/main/api/overview/azure)
Java/Python/JS: `docs-ref-services`. Ref [link](https://github.com/Azure/azure-docs-sdk-java/tree/main/docs-ref-services)
To have the flexibility of using different path for .NET Toc, we add one more parameter in common script. As the common script currently run in prod, so we default to what we had before.

Add extra parameters for .net readme path

---

src/dotnet/APIView/APIViewWeb/Controllers/UserProfileController.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs

Fixes a few minor nits with PR #4382, listed below.
- Corrected cache to update ApprovedLanguages rather than languages. (Languages being the language filter for reviews, ApprovedLanguages being the preferred approval languages)
- Changed `approvers` to `PreferredApprovers` to avoid confusion with existing `Approvers` list (People you can request/approve vs those who have approved)
- Default behavior if no languages selected changed from never showing to always showing (old behavior) 
Functionality unchanged otherwise

Hotfix for #4382

---

eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1

1. Handle case where the matrix produces a single length array. Powershell by default will return the array item type (object) instead of an array, which messes things up the generated values file.
2. Handle case where there is no values.yaml file defined.

[stress testing] Improve scenario matrix edge case handling

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

Resolves #4118
We always checkout a new branch just before pushing it to the new tag. This new branch is always the same name. This means that if something goes wrong between creating the branch to hold the changeset and pushing the new tag, we'll be in a stuck state that can't even be fixed by a `reset` because the branch will already exist. `git branch <branchname>` will continually fail, we already created a branch of that name!
We can avoid a weird broken state if we create a new one each time we try to push.
If we're _already_ in the middle of the push, we'll already be on another branch, and it'll just checkout a new one with all the information still present, and the tag push will succeed.

Prevent broken state on cancelled push

---

eng/pipelines/live-test-cleanup.yml

Reverts Azure/azure-sdk-tools#4502
Seems to have been transient.

Revert "Remove translation from resource cleanup"

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs

~~Skip compiling tests in Java performance pipelines as the test JARs will never be used.~~
Updated to only increase build parallelization as it turned out the from source runs did require the test compile.

Increase Java Perf Pipeline Build Parallelization

---

eng/common/TestResources/New-TestResources.ps1

We don't really need this verbose logging anymore. Removing it to save log space, as well as mitigate potential issues in the NET storage pipelines where the log output gets truncated, meaning pipeline variables don't get set.

Dump out correlation id without verbose logging for resource deployment

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

Resolves #4557
Repro Azure/azure-sdk-for-js/pull/23655
It's technically allowed. It was our _methodology_ of creating the URI that was actually breaking.
By limiting this logic to only apply in this _specific_ situation, I believe we should be able to safely use this string concatenation.
@mikeharder for discussion. @hallipr for FYI. @timovv lmk when the repro is updated with the fix for base uri. Should just turn green with this change.
EDIT after Timo's update:

Allow multiple leading / on path

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs

Add the missing `Azure.Monitor` namespace, which is being used by both the Azure Monitor Query and Azure Monitor Ingestion libraries. It's already listed at https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-namespace-naming. This PR also alphabetizes the namespace lists.

Add Azure.Monitor to the allowlist of .NET namespaces

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/BreadcrumbTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitStoreTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationResetTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationRestoreTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/NormalizedString.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/AssetsConfiguration.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitAssetsConfiguration.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStoreBreadcrumb.cs

This PR **forces** every string going through our configuration structure to maintain linux-style path separators.
I'm really tired of wonky bugs being caused by inconsistent `\` vs `/`.
Resolves #4568

Consistent path handling

---

eng/common/scripts/stress-testing/find-all-stress-packages.ps1

This handles versions like `~0.1.21` appropriately.
Fixes #4590

Handle helm version modifiers in stress test min version check

---

eng/common/scripts/Update-DocsMsToc.ps1

The parameter is needed to determine the source of package repository.
Will pass through the value docindex pipeline.

Add package source override to toc script.

---

src/dotnet/APIView/APIView/CodeFileHtmlRenderer.cs
src/dotnet/APIView/APIView/CodeFileRenderer.cs
src/dotnet/APIView/APIView/CodeLine.cs
src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
src/dotnet/APIView/APIView/Model/CodeFileTokenKind.cs
src/dotnet/APIView/APIView/Model/NavigationItem.cs
src/dotnet/APIView/APIViewUnitTests/ExactFormatting/Attributes.cs
src/dotnet/APIView/APIViewWeb/Client/css/site.scss
src/dotnet/APIView/APIViewWeb/Client/src/helpers.ts
src/dotnet/APIView/APIViewWeb/Client/src/review.ts
src/dotnet/APIView/APIViewWeb/Controllers/UserProfileController.cs
src/dotnet/APIView/APIViewWeb/Helpers/AutoMapperProfiles.cs
src/dotnet/APIView/APIViewWeb/Helpers/PageModelHelpers.cs
src/dotnet/APIView/APIViewWeb/Models/UserPreferenceModel.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Shared/Navigation.cshtml

Fixes https://github.com/Azure/azure-sdk-tools/issues/3900
- EditorBrowsable attribute is itself now always hidden
- Members attributed with this are hidden by default
- There is a checkbox to show the hidden members - the checkbox is only visible if review contains hidden API elements.
- Value is added to user preferences (just like show left nav, hide line numbers, etc) which is valid for current session - it does not get written to Cosmos like the more permanent settings such as preferred language
- When diffing, if there is a change in any hidden members they are shown
- Hidden members are italicized and grayed out
- Namespaces with only hidden types are also hidden
- Navigation items that correspond to hidden namespaces or types are hidden
EBN applied to constructor:
Show Hidden APIs …

Hide EditorBrowsableNever members by default

---

src/dotnet/APIView/APIViewWeb/Filters/ApiKeyAuthorizeAsyncFilter.cs

Add support for multiple API Key to use REST API by other teams as well. Communication calling team require this change to integrate with APIView.

Add more than one APIKey support

---

eng/common/TestResources/New-TestResources.ps1

Resolves #4450
This adds an optional `TestResourcesDirectory` parameter to `New-TestResources.ps1` to enable searching for templates outside the immediate service directory (the specific scenario in mind is a sub-project directory).
There are a couple benefits and drawbacks to the approach I took here:
- In this PR, the resource and environment variable naming is still determined by the service directory. This means that no test code needs to be changed to handle new environment variable prefixes.
- A drawback of ^^ is parallel local testing of multiple sub-projects within the same service directory will cause resource and environment variable naming conflicts, unless `-BaseName` is also passed in. 
- The above drawback could be partially addressed by determining resource naming based on …

Add optional TestResourcesDirectory override parameter

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj

[See build failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1981636&view=results).
Need to speak with .NET folks before removing .NET 5 support, and need an eng/common update out the door. Need builds green again 👍

Disable target framework check

---

tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.lock
tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
tools/stress-cluster/services/Stress.Watcher/src/JobEventHandler.cs
tools/stress-cluster/services/Stress.Watcher/src/PodEventHandler.cs
tools/stress-cluster/services/Stress.Watcher/src/Stress.Watcher.csproj
tools/stress-cluster/services/Stress.Watcher/tests/Stress.Watcher.Tests.csproj

Potentially fixes some issues with the watcher and http connections/re-connections. The latest version of the client has better handling for keepalive issues.
This also fixes build/deploy of the chart, which needed to be updated to the latest addons.

Bump kubernetes client version and addons version for stress watcher

---

src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs

1. Run upgrade review pipeline once for all revisions instead of a pipeline run per revision.
2. Add 30 seconds before running upgrade pipeline to avoid queueing too many jobs
3. Add delay if devops return 429 with RetryAfter instead of success status when downloading artifact from devops after pipeline is completed.

handle apiview devops throttle

---

eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1

In some environments, the lack of quoting is causing `$pkg.ReleaseName` to not resolve, resulting in a bad secret query.
```
Error from server (BadRequest): Unable to find "/v1, Resource=secrets" that match label 
selector "status=deployed,name=$($pkg.ReleaseName)", field selector "": unable to parse 
requirement: values[0][name]: Invalid value: "$": a valid label must be an empty string or 
consist of alphanumeric characters, '-', '_' or '.', and must start and end with an 
alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for 
validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the …
```

Fix minor issue getting stress secret labels with quoting and error handling

---

tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1

It _should_ be yelling at you for not having your environment variables set. Instead it's throwing 
```
A positional parameter cannot be found that accepts argument '+'.
```
This PR fixes the reason. Resolves #4724

Transition script not throwing error properly

---

eng/common/scripts/Helpers/Metadata-Helpers.ps1

Use the new audience for service readme script.
For docs:
1. We use the APIs in release pipeline through Metadata-Helpers.ps1. (Fixed in this PR)
2. We use the API in docindex pipeline through Metadata-Helpers.ps1. (Fixed in this PR)
For notification:
1. We use the APIs from `NotificationCreator` through the `GitHubToAADConverter`
For pipeline owner extractor:
1. We use the APIs from `pipeline-owners-extractor` through the `GitHubToAADConverter`
Testing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1993950&view=results

Use the new audience field

---

eng/common/scripts/git-branch-push.ps1

With new PS command line parsing update in 7.3 they explicitly pass "" to the native commands which in our usage here we don't want. However setting the variable to null instead works for our scenario with both command line parsing strategies so using it here.

Fix push script passing in optional argument

---

tools/stress-cluster/services/Stress.Watcher/src/JobEventHandler.cs
tools/stress-cluster/services/Stress.Watcher/tests/JobEventHandlerTest.cs

@liukun-msft this should fix the issue you have been seeing with resources not being deleted on uninstall/upgrade.

Fix stress watcher to delete test resources on job deletion events

---

src/go/cmd/api_view.go
src/go/cmd/module.go

Crete package name using relative path after `sdk` for internal package and set package name using base module name for non internal package.

APIvIew - Go package name for internal package

---

eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
eng/pipelines/templates/steps/produce-net-standalone-packs.yml
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
tools/test-proxy/ci.yml

Adding additional capability to archetype-dotnet-tool.
I still need to do work in `azure-sdk-build-tools` to handle the addition of these new artifacts. I want to upload them to git release that was created in the remote template.
@timovv @billwert I still have orchestration work to do, but I can merge this and ensure that you have test clients for all your platforms.

Produce Standalone .NET Executables

---

eng/pipelines/merge-docs-main-to-live.yml

This is the PR to enable merge main to live for .NET.
The pre-requisite PR in dotnet repo has been merged.
https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/docsms-allowlist/dotnet-allowlist.txt
Testing pipeline with whatif: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2007538&view=results

Enable .NET merge main to live

---

tools/notification-configuration/ci.proj
tools/notification-configuration/notification-configuration.sln

This PR makes it easy to open in Visual Studio the `.csproj` files that are descendants of `tools/notification-configuration` path, by adding a `.sln` file containing minimum set of projects required to do a successful build.
I created the `.sln` file by doing the following in VS:
- new project -> blank solution; named it `notification-configuration` and placed in the dir `tools\notification-configuration`
- added `tools\notification-configuration\github-codeowner-subscriber\Azure.Sdk.Tools.GithubCodeownerSubscriber.csproj`  
- added `tools\notification-configuration\notification-creator\Azure.Sdk.Tools.NotificationConfiguration.csproj`
- added the two other required projects to make the build succeed;
- added `ci.yml` as solution file.
I also deleted `ci.proj` to avoid the `MSBUILD : …

Create a missing .sln file for notification-configuration tool

---

tools/notification-configuration/README.md
tools/notification-configuration/notification-configuration.sln

This PR adds a README.md file to `tools/notification-configuration`.
This README most notably just points to the wiki article describing the feature that is implemented by the sources in the directory to which the README was added, i.e.:
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/63/Subscribe-to-Notifications
As accompanying change to this PR, I made several updates to the doc hyperlinked from the README. [You can find the full diff of my wiki changes here](https://dev.azure.com/azure-sdk/internal/_git/internal.wiki?path=/Engineering-System/Testing-Guidelines/Subscribe-to-Notifications.md&version=GBwikiMaster&_a=compare&oversion=GC35202cb5a14fcf5a8a49c82795dd25c6b6babfdf&mversion=GCbf3ad8946b4544958d67a5429849ef9b28de1f73).

Move internal wiki page "Subscribe to Notifications" next to tools/notification-configuration

---

tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/ConsoleOutput.cs
tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/MainTests.cs
tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
tools/code-owners-parser/CodeOwnersParser.sln
tools/code-owners-parser/CodeOwnersParser.sln.DotSettings
tools/code-owners-parser/CodeOwnersParser/CodeOwnerEntry.cs
tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs
tools/code-owners-parser/CodeOwnersParser/FileHelpers.cs
tools/identity-resolution/Services/GitHubService.cs
tools/notification-configuration/notification-configuration.sln.DotSettings

In preparation for making changes for #2770 I submit this PR with a set of assorted refactorings on `tools/code-owners-parser/CodeOwnersParser.sln` and `tools/notification-configuration/notification-configuration.sln`. 
Here is what I did on both of these solutions:
- Applied various refactorings suggested by [ReSharper](https://www.jetbrains.com/resharper/); this includes, but is not limited to: simplifying code, adding missing `readonly` attributes, fixing member capitalization [to match official convention](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) (which also matches the convention used by majority of the codebase), and removing unused `using` statements and fixing typos.
- Added some of the highlighted words and abbreviations to …

Assorted set of minor refactorings for logic related to CODEOWNERS processing

---

eng/pipelines/apiview-review-gen-cadl.yml
eng/scripts/Create-Apiview-Token-Cadl.ps1
src/dotnet/APIView/APIViewWeb/Languages/CadlLanguageService.cs
src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml.cs

1. Fix script to check git info path before removing it.
2. Remove path separator from sparse checkout path if it is present
3. Update review name using package root path for CADL review
4. Show URL path input field when creating revision on CADL review.

CADL manual API review additional changes

---

tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1

@xiangyan99 was running the `generate-assets-json.ps1` script earlier today and got the following error message:
```
The language, python/ (fetch), does not have an entry in the LangRecordingDirs dictionary.
```
This was because the language repo parsing method couldn't correctly parse the format of Xiang's `git remote -v` output:
```
PS D:\Github\azure-sdk-for-python\sdk\search\azure-search-documents> git remote -v
origin  https://github.com/Azure/azure-sdk-for-python/ (fetch)
origin  https://github.com/Azure/azure-sdk-for-python/ (push)
```
This fixes that by adding `/` as a terminating character for parsing the language string.
Resolves https://github.com/Azure/azure-sdk-tools/issues/4748
@scbedd

[Asset sync] Handle additional git remote format

---

tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
tools/pipeline-generator/ci.yml

This PR, in tandem with PR #4930, addresses #4888 by updating the `PipelineGenerator` tool target framework from `netcoreapp3.1` to `net60` ([version reference](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#latest-versions)). The `net60` SDK is supported both by the Ubuntu pool image we are pinning too, `20.04` (see analysis below), as well as should future-proof us at list until November 12, 2024, as this is when [net6.0 support ends](https://dotnet.microsoft.com/en-us/download/dotnet).
This PR also contributes to solving #4934 and #4935, together with PR #4937.
I have identified two pipeline kinds calling into the `PipelineGenerator` tool:
1. The [azure-sdk / internal / Pipelines / automation / automation - pipeline-generation](https://dev.azure.com/azure-sdk/internal/_bui …

Update PipelineGenerator target framework from netcoreapp3.1 to net6.0

---

eng/common/pipelines/templates/jobs/prepare-pipelines.yml
eng/common/pipelines/templates/steps/prepare-pipelines.yml

This PR, in tandem with PRs #4915 and #4916, addresses https://github.com/Azure/azure-sdk-tools/issues/4888. This PR subsumes the abandoned PR of #4911.
Specifically, this PR ensures that `prepare-pipelines.yml` is configured to use specific `pool`, set to use Ubuntu 20.04:
```
pool:
name: azsdk-pool-mms-ubuntu-2004-general
vmImage: MMSUbuntu20.04
```
Without the [pool](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pool?view=azure-pipelines) definition pointing to Ubuntu 20.04, the steps within the file used an implicit default, which resolves to `ubuntu-latest`. This caused breakage as explained in #4888. Setting the pool to Ubuntu 20.04 will allow us to:
- Immediately unblock the language repos `prepare-pipelines.yml` pipelines [1], as Ubuntu 20.04 has the .NET …

Introduce "job" version of prepare-pipelines.yml, with "pool" defined to use Ubuntu 20.04

---

eng/common/scripts/stress-testing/deploy-stress-tests.ps1
eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1

Adding in feature for stress deployment script to do a dry run and generate helm templates locally without deploying

Helm template for deploy script

---

eng/pipelines/templates/stages/archetype-sdk-tool-azure-function.yml
eng/pipelines/templates/stages/archetype-sdk-tool-azure-webapp.yml
eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
eng/pipelines/templates/variables/globals.yml
src/dotnet/Azure.ClientSdk.Analyzers/ci.yml
tools/CreateRuleFabricBot/ci.yml
tools/apiview/parsers/swagger-api-parser/ci.yml
tools/code-owners-parser/ci.yml
tools/github-issues/Azure.Sdk.Tools.GitHubIssues.Tests/Azure.Sdk.Tools.GitHubIssues.Tests.csproj
tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
tools/http-fault-injector/ci.yml
tools/identity-resolution/ci.yml
tools/notification-configuration/ci.yml
tools/pipeline-generator/ci.yml
tools/snippet-generator/ci.yml
tools/stress-cluster/cluster/kubernetes/generator/ci.yml
tools/version-guard/ci.yml

Updating .NET SDK version from `3.1.405` to `6.x` for our pipelines because:
- `.NET Core 3.1` support [is ending on December 13, 2022](https://dotnet.microsoft.com/en-us/download/dotnet), hence we want to move to a supported SDK. See also #4934.
- As `.NET Core 3.1` support is ending, [it got removed from latest Ubuntu images](https://github.com/Azure/azure-sdk-tools/issues/4888#issuecomment-1342033218), and in some places we we didn't pin the Ubuntu image, thus resulting in us using the latest image, thus leading to issues, like #4888.
- To address #4888 we need to move `PipelineGenerator` to .NET 6, which we do in PR #4915. But for the PR #4915 to successfully build, this PR needs to be merged first, as explained in https://github.com/Azure/azure-sdk-tools/pull/4915#issuecomment-1342167 …

Bump globals.yml .NET SDK version from 3.1.405 to 6.x + assorted changes

---

eng/common/pipelines/templates/jobs/prepare-pipelines.yml

Was trying to set up live test pipeline for this [pr](https://github.com/Azure/azure-sdk-for-js/pull/24225). The prepare-pipeline job failed due to [not being able to find install-pipeline-generation.yml](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2056101&view=results).

prepare pipeline job bug fix

---

src/dotnet/Mgmt.CI.BuildTools/CI/CI.BuildTasks/Tests/CI.BuildTasks.Tests/Tests.CI.BuildTasks.csproj
src/dotnet/Mgmt.CI.BuildTools/CI/CI.Common/Tests/Tests.CI.Common.csproj

This PR is a follow-up to:
- #4937
it contributes to addressing:
- #4934
Here I migrate some more projects from `netcoreapp2.1` to `net6.0`.
I also quenched the error (escalated from warning):
> MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference (...) AMD64"
by forcing the relevant tests project to be win10-x64 too.

Migrate Tests.CI.BuildTasks.csproj and Tests.CI.Common.csproj to net6.0

---

eng/common/scripts/Test-SampleMetadata.ps1

`azure-load-testing` is an approved product slug in https://review.docs.microsoft.com/help/contribute/metadata-taxonomies?branch=main#product but is not present in the SampleMetadata.ps1 file. Adding it here as pipelines are failing due to this

Add load-testing to list of valid sample slugs

---

tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/CommandParserOptions/DefaultOptions.cs
tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/CommandParserOptions/GenerateOptions.cs
tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/PipelineGenerationContext.cs
tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs

I'm extending pipeline-generator to enable scenarios detailed in #2572. To do this, pipeline-generator will have multiple sub-commands:
```
pipeline-generator generate   # Current functionality, generate/sync pipelines from yaml files
pipeline-generator bootstrap  # (new) Create or update service principals and service connections for pipeline usage
pipeline-generator onboard    # (new) Set up keyvaults and/or access policies for new teams onboarding to Bring Your Own Subscription
```
As part of adding sub-command support, this PR updates the project to use CommandLineParser in line with our other C# CLI projects. I have also set up defaults for a lot of the common values to make local invocation much more concise, for example:
```
pipeline-generator generate --path …
```

Refactor pipeline-generator to use CommandLineParser

---

tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer.Tests/Azure.Sdk.Tools.CheckEnforcer.Tests.csproj
tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
tools/webhook-router/Azure.Sdk.Tools.WebhookRouter.Tests/Azure.Sdk.Tools.WebhookRouter.Tests.csproj
tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj

This is a follow-up to PR
- #4937
That PR at first didn't migrate these two tools because we believed we can just delete them, but this turned out to require some extra work, as captured by these two issues:
- #4991 
- #4992 
Hence we need to migrate these tools to `net6.0` to address:
- #4888

Migrate CheckEnforcer and WebhookRouter to net6.0

---

eng/common/scripts/Helpers/Package-Helpers.ps1
eng/common/scripts/Update-DocsMsMetadata.ps1
eng/common/scripts/Update-DocsMsPackages.ps1
eng/common/scripts/common.ps1

**Problem**:
For package which is not "New" to csv, we have to use package.json to onboard the package. However, the best practice is to depend on csv file as many as possible. The PR change here is to add flexibility to use csv to onboard a new package.
**New onboard rule:**
1. If package sets "New" to true, then we will onboard the package.
2. If package sets some value to "MSDocService", then we will onboard the package. 
3. If nothing set for these two fields, then the package will not onboard to Docs.Ms.
**Pros:**
In this way, we can also push people to update `ms.service` as many as possible. If somehow we don't have the right `ms.service`, then we can use `placeholder` for temporary placement.
Testing onboarding logic:
1. Testing in Java, removed the `durabletask-azure-functions` …

Give the csv flexibility to onboard "not New" package to Docs.Ms

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml

This is no longer necessary and should reduce the runtime a little.

[Perf automation] Remove Eventhubs Python v5.9 from passes

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
tools/code-owners-parser/CodeOwnersParser/Azure.Sdk.Tools.CodeOwnersParser.csproj

Contributes to:
- #4888 
By updating all projects whose `TargetFramework` was `nestandard2.0` to `net6.0`.
Notably it does leftover update to `CodeOwnersParser`, which was missed by this PR:
- #4937
Note that this PR might require a follow-up package update, same as it was done b this PR:
- #4988
For a list of all PRs doing migration to `net6.0`, see this comment:
- https://github.com/Azure/azure-sdk-tools/issues/4888#issuecomment-1356639653
- `APIView` build, the only tool iun `azure-sdk-tools` that depends on `Azure.ClientSdk.Analyzers`:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2083442&view=results

Update `<TargetFramework>netstandard2.0` to `net6.0` in `Azure.ClientSdk.Analyzers` and `CodeOwnersParser`

---

tools/apiview/emitters/cadl-apiview/CHANGELOG.md
tools/apiview/emitters/cadl-apiview/package.json
tools/apiview/emitters/cadl-apiview/src/apiview.ts
tools/apiview/emitters/cadl-apiview/src/namespace-model.ts
tools/apiview/emitters/cadl-apiview/src/navigation.ts
tools/apiview/emitters/cadl-apiview/src/version.ts

Fixes #4977.
Example for OpenAI Inference:
https://apiviewstaging.azurewebsites.net/Assemblies/Review/05b84c030c904b208aa0eefbe5a8b55f

[Cadl APIView] Show Aliases in their own category within navigation

---

eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
eng/pipelines/templates/steps/produce-net-standalone-packs.yml

This PR addresses following comment:
- https://github.com/Azure/azure-sdk-tools/pull/4916#discussion_r1049896767
- added variable to deduplicate `$(Build.ArtifactStagingDirectory)/packages`;
- now listing contents of `$(Build.ArtifactStagingDirectory)/packages`;
- made improvements to task message and name;
- also improved the name and diagnostic output of `Create destination directory` task, coming from [produce-net-standalone-packs.yml](https://github.com/Azure/azure-sdk-tools/pull/5007/files#diff-79ac80271b4abca08d08ecc17c0ade284347c8a119af78c01889600d30b264fa), as it was too vague and misleading.
Tested by making a build from this PR branch and observing it behaved correctly:
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2069738&view=logs&j=6d7966cd-0423-5022-78e0-a …

Improve diagnostic output + refactor handling of packages-to-be-published directory in `archetype-sdk-tool-dotnet.yml`

---

eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
eng/common/pipelines/templates/jobs/perf.yml
eng/common/pipelines/templates/jobs/prepare-pipelines.yml

This is a companion PR to:
- #4996
In this PR, I migrate all occurrences of Ubuntu to `22.04` in the directory `eng/common`, but excluding `eng/commons/scripts/job-matrix`, as this it will be handled by:
- #4995

Update Ubuntu images in `eng/common` to Ubuntu 22.04

---

src/dotnet/APIView/APIViewIntegrationTests/ReviewManagerTests.cs
src/dotnet/APIView/APIViewWeb/Client/src/revisions.ts
src/dotnet/APIView/APIViewWeb/Managers/IReviewManager.cs
src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml.cs

CADL review can only be created using a link to CADL repo. This is not sufficient in all cases if CADL source repo has different folder structure or when a user wants to emit token file locally and upload as a revision using different cadl emitter version. This PR is to add an option so user can choose Json token file as source to create a revision.

Support uploading API review token file for CADL review

---

.github/CODEOWNERS

This PR contributes to:
- #5009
With this PR merged, the CODEOWNERS file should have 100% coverage of all files and directories currently in the repository.

Add `global.json` and other missing paths to `CODEOWNERS`

---

doc/common/matrix_generator.md

In preparation to address:
- #4995 
I was reading through the `job-matrix/README.md` and took the liberty to make some improvements.
- review the entire document and rewrite or add sections for clarity, consistency and completeness;
- fix or suppress all [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) warnings;
- replace all mentions of .NET 5 and Ubuntu 18 to .NET 6 and Ubuntu 22.04
- (NOT YET DONE) update the file paths once #5027 is merged
This PR cannot be merged until the following PR is merged:
- #5027
Once that PR is merged, this PR will be updated to modify the newly introduced `matrix_generator.md` instead of `README.md`.

Update `doc/common/matrix_generator.md`: review and rewrite for clarity

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
tools/perf-automation/ci.yml
tools/pipeline-owners-extractor/ci.yml
tools/stress-cluster/services/Stress.Watcher/ci.yml
tools/test-proxy/ci.yml

This PR:
- contributes to addressing #4888;
- migrates `perf-automation` to `net6.0`, per https://github.com/Azure/azure-sdk-tools/issues/4888#issuecomment-1356639653;
- removes obsolete `DotNetCoreVersion` overrides, which no longer make sense since the default .NET version was changed to `6.x` in #4916. For full list of relevant PRs doing .NET version migration, see https://github.com/Azure/azure-sdk-tools/issues/4888#issuecomment-1356639653.

Update perf-automation to `net6.0`; get rid of remaining, now no-op, overrides of `DotNetCoreVersion`

---

tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/Azure.Sdk.Tools.CodeOwnersParser.Tests.csproj
tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeOwnersFileTests.cs
tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/MainTests.cs
tools/code-owners-parser/CodeOwnersParser.sln
tools/code-owners-parser/CodeOwnersParser/Azure.Sdk.Tools.CodeOwnersParser.csproj
tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs
tools/code-owners-parser/CodeOwnersParser/MatchedCodeOwnerEntry.cs

This is a first PR to address:
- #2770 
Changes in [CodeOwnersFile.cs](https://github.com/Azure/azure-sdk-tools/pull/5030/files#diff-ee9b4b68edf43f257d84470fb4a37ffebc78b42e9d6fa0eedaabeb1416628427):
- In this PR I add a new implementation for matching entries in our CODEOWNERS file. **This implementation is disabled**, hidden behind a method feature flag parameter. 
- The method targeted by this PR is `CodeOwnersFile.FindOwnersForClosestMatch`. It now either calls its previous, unchanged, legacy implementation, now located in [CodeOwnersFile.FindOwnersForClosestMatchLegacyImpl](https://github.com/Azure/azure-sdk-tools/pull/5030/files#diff-ee9b4b68edf43f257d84470fb4a37ffebc78b42e9d6fa0eedaabeb1416628427R81), or the newly introduced implementation. The decision is [made …

Add glob-based support for wildcards in `CODEOWNERS` file parser (disabled, behind a feature flag)

---

eng/common/scripts/job-matrix/README.md

This PR is a follow-up to 
- #5027
This change couldn't have been made before #5027 was merged because it caused CI link validation to fail.

Hyperlink from eng/common job-matrix README to matrix_generator.md

---

tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeOwnersFileTests.cs
tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
tools/code-owners-parser/CodeOwnersParser/Azure.Sdk.Tools.CodeOwnersParser.csproj
tools/code-owners-parser/CodeOwnersParser/MatchedCodeOwnerEntry.cs
tools/identity-resolution/identity-resolution.csproj
tools/notification-configuration/notification-creator/Azure.Sdk.Tools.NotificationConfiguration.csproj
tools/notification-configuration/notification-creator/Program.cs

This PR is a follow-up to:
- #5030
It rewrites the new parser logic to match the rules as outlined in:
- https://github.com/Azure/azure-sdk-tools/issues/4859#issuecomment-1370360622
The new parser now supports diagnostic logging via `Microsoft.Extensions.Logging.Console`. To make this work, I took a dependency on this package, version `7.0.0`, and updated that package and `Microsoft.Extensions.Logging` to `7.0.0` in the code that uses `CodeOwnersParser` as dependency, to avoid the "package version downgrade detected" build failure.

Replace the glob-based CODEOWNERS parser with regex-based

---

global.json

This PR contributes to:
- #5009
Reference:
https://www.nuget.org/packages/Microsoft.Build.Traversal#versions-body-tab

Update `global.json` `Microsoft.Build.Traversal` from `1.0.45` to `3.2.0`

---

eng/common/scripts/get-codeowners.ps1
eng/pipelines/templates/variables/globals.yml

code-owners-parser:
- https://dev.azure.com/azure-sdk/internal/_build?definitionId=3188
- https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Azure.Sdk.Tools.RetrieveCodeOwners/overview/1.0.0-dev.20230108.6
notification-configurator:
- https://dev.azure.com/azure-sdk/internal/_build?definitionId=1815
- https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Azure.Sdk.Tools.NotificationConfiguration/overview/1.0.0-dev.20230108.1
pipeline-owners-extractor:
- https://dev.azure.com/azure-sdk/internal/_build?definitionId=5109
- https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Azure.Sdk.Tools.PipelineOwnersExtractor/overview/1.0.0-dev.20230105.1
This PR should unblock currently failing pipeline of [automation - …

Update versions of packages `RetrieveCodeOwners`, `NotificationConfiguration` and `PipelineOwnersExtractor` to most recent as of 1/8/2023

---

eng/common-tests/matrix-generator/samples/matrix-test.yml
eng/common-tests/matrix-generator/tests/job-matrix-functions.filter.tests.ps1
eng/common-tests/matrix-generator/tests/job-matrix-functions.modification.tests.ps1
eng/common-tests/matrix-generator/tests/job-matrix-functions.tests.ps1
eng/common/scripts/job-matrix/job-matrix-functions.ps1

This PR fixes paths I forgot to update when I did this PR:
- #5027
And as such this PR contributes to addressing:
- #4995
It also adds `UnitTest` tags to the `matrix-generator` tests so [`common-tests/ci.yml` pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5809) executes them.
- #5098

Fix broken relative paths in `matrix-generator` tests and samples + make the tests runnable by `common-tests/ci.yml`.

---

.github/workflows/event.yml
.github/workflows/label-to-project.yml
eng/pipelines/setup-tutorial-branch.yml
tools/js-sdk-release-tools/ci.yml
tools/mock-service-host/ci.yml
tools/sdk-testgen/ci.yml

This is a companion PR to:
- #4996
In this PR, I migrate occurrences of `ubuntu-latest` to Ubuntu 22.04 XOR I add a comment explaining they are intentionally set to `latest`.
I do not have enough context to guess which images should be updated - this is just my best guess. Thus I kindly ask reviewers to verify if my guess is correct.
This PR has revealed following issue:
- #5102

Update `ubuntu-latest` images: set them to Ubuntu 22.04 XOR comment they are `latest` intentionally

---

.azure-pipelines/apiview.yml
eng/pipelines/templates/steps/produce-net-standalone-packs.yml

Ensure that the produced linux binary has the executable bit set

---

tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeOwnersFileTests.cs

Follow-up to:
- #5063 
As such, contributes to:
- #2770

Add regex-based CODEOWNERS matcher tests for "/" and file names with spaces.

---

src/go/cmd/module.go

Fixes empty package name issue for GO API reviews when review is generated using uploaded source files.

Set Package name for GO API reviews

---

eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1

Our Docs.Ms is using `Github` instead of the right name `GitHub`. Fixed the naming in PR.

Fix Github to GitHub

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
tools/code-owners-parser/CodeOwnersParser/Azure.Sdk.Tools.CodeOwnersParser.csproj

**UPDATE** 1/13/2023: this PR is required as it broke things. See:
- https://github.com/Azure/azure-sdk-tools/pull/5048#issuecomment-1382298227
- https://github.com/Azure/azure-sdk-tools/pull/5029/files#r1069929465
**UPDATE** 1/4/2023: I decided to abandon this PR. See [my comment below](https://github.com/Azure/azure-sdk-tools/pull/5048#issuecomment-1371768721) why.
This PR reverts changes in:
- #5029
plus adds a comment why.

Revert `Azure.ClientSdk.Analyzers` library to target `netstandard2.0` instead of `net6.0`.

---

eng/common/scripts/Update-DocsMsMetadata.ps1

The PR is to update the existing metadata json instead of check in a new one.
The updated metadata json: https://github.com/Azure/azure-docs-sdk-dotnet/commit/2af2828fb2694080520f1e6b6e0fd465d226985e#diff-afa38ac4d7e2700dd78b4ca6547bd0cab8fbff7794dd803d18600eb8783bd1dc
Testing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2115645&view=logs&j=72a39880-3efd-52c2-15be-d04db16925c9

Update on existing metadata json file.

---

tools/sdk-generation-pipeline/Dockerfile

It's a temp solution. I will change it to download .Net sdk by fetch configuration from .Net sdk repository automatically when user start the docker container. (tracking issue: https://github.com/Azure/azure-sdk-tools/issues/5148)

Upgrade .Net sdk version (Temp Solution)

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj

From conversations with .NET regarding #5048, make sure we test against
.NET Framework TFMs to help make sure we don't break analyzers again.

Test Roslyn analyzer changes against net472

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

This reverts commit f1c5c78b27b6f9510ffab2d9dba522472ea67916.
Re-opening #4720
All livetests broken by this change. Apparently this configuration element is honored a different way than I originally coded it. Need to figure out what's going on in livetests and resolve. Reverting this until I can do that (as the test-proxy asset-sync functionality is currently broken by the original PR)

Revert "Disable auto gpg signing (#5047)"

---

tools/test-proxy/tests.yml

We really should be doing a find/replace when we delete/rename an existing template :|

fix failing test-proxy livetests -- the run-pester-tests template was renamed

---

tools/notification-configuration/notification-creator/NotificationConfigurator.cs

In this PR I am printing out to STDOUT the full URL of the repository from which the `CODEOWNERS` file is be parsed by the `notification-configurator`.
I need this because I am planning to make the `CODEOWNERS` file path matching logic to behave differently based on the repository from which the file is originating. This will enable me to do gradual rollout of the regex-based matcher.
Details here:
- https://github.com/Azure/azure-sdk-tools/pull/5088#issuecomment-1397427097

`notification-configuration`: write out repo URL used to obtain CODEOWNERS file

---

eng/Directory.Build.props
src/dotnet/APIView/APIView/APIView.csproj
src/dotnet/APIView/APIViewIntegrationTests/APIViewIntegrationTests.csproj
src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj
tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/SwaggerApiParserTest.csproj
tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/Azure.Sdk.Tools.CodeOwnersParser.Tests.csproj
tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/Azure.Sdk.Tools.RetrieveCodeOwners.Tests.csproj
tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Azure.Sdk.Tools.RetrieveCodeOwners.csproj
tools/code-owners-parser/CodeOwnersParser/Azure.Sdk.Tools.CodeOwnersParser.csproj
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Azure.Sdk.Tools.PipelineWitness.csproj
tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/Azure.Sdk.Tools.SnippetGenerator.Tests.csproj
tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator/Azure.Sdk.Tools.SnippetGenerator.csproj

As in subject. Because we use `net6.0`, [currently the default lang version is `10.0`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults).
Previously the lang version was forced by [`eng/Directory.Build.props`](https://github.com/Azure/azure-sdk-tools/pull/5175/files#diff-81138f4f0bdd24607d3d5979bdc08f91e9cfe44255de13ce958719925f1ae88b), hence many projects were overriding it. With this PR this is no longer necessary.
The need for this work was discovered during the following:
- https://github.com/Azure/azure-sdk-tools/pull/5134#discussion_r1070172769

Unhardcode C# lang versions, making them use TFM default (currently `10.0` due to TFM of `net6.0`).

---

tools/identity-resolution/Services/GitHubService.cs
tools/notification-configuration/notification-creator/Contacts.cs
tools/notification-configuration/notification-creator/NotificationConfigurator.cs

This PR improves logged messages and refactors `NotificationConfigurator` class logic related to obtaining list of contacts to send notifications to based on CODEOWNERS file from repository to which given pipeline pertains.
The main change is extraction of `Contacts` class from `NotificationConfigurator` class, with entry method being `Contacts.GetFromBuildDefinitionRepoCodeowners(BuildDefinition buildDefinition)`.
I also made related improvements to log messages and naming in surrounding code. Most notably, I made the naming more consistent and got rid of some synonyms or mismatched names, like `BuildDefinition` being named `Pipeline`.
Once this PR is merged and package published, I will run the [`automation - build-failure-notification-subscriptions` …

Extract `Contacts` class + related refactorings to `NotificationConfigurator` class.

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/DebugLogger.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs

test-proxy always logs exceptions on console

---

eng/common/testproxy/publish-proxy-logs.yml
eng/common/testproxy/test-proxy-tool.yml

If you're using a simple invocation of the `test-proxy-tool.yml`, you will be able to call the following before your tests run.
```yml
- template: /eng/common/testproxy/test-proxy-tool.yml
parameters:
rootFolder: $(Build.SourcesDirectory)/sdk/core
```
One will be able to call:
```yml
- template: /eng/common/testproxy/publish-proxy-logs.yml
parameters:
rootFolder: $(Build.SourcesDirectory)/sdk/core
```
As long as you reflect the same `rootFolder` argument to publish-proxy-logs, they will be picked up and uploaded as artifacts.
[Example Invocation](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2139544)
What the artifacts look like:
Resolves the other half of #5204

Add Template for Upload of Proxy Logs

---

eng/common/TestResources/New-TestResources.ps1
eng/common/TestResources/Remove-TestResources.ps1
eng/common/TestResources/SubConfig-Helpers.ps1
eng/common/TestResources/Update-TestResources.ps1

Follow up fix related to discussion on https://github.com/Azure/azure-sdk-for-net/pull/33262
- Make name generation simpler and more consistent across test resource scripts (found a bug where remove-testresources.ps1 would not have worked for nested service directories like data/aztables)
- Use a short hash for resource names deployed locally, to avoid edge cases where a long service directory or username causes resource names to be too long for validation (e.g. keyvault).
- Fix issue with `EnvironmentVariables` ref getting updated from the parameters when splatting in CI mode and polluting the env variable outputs on subsequent runs in the same shell.
- Add more warning logging if we're overwriting environment variables, for #4931
Fixes #4931

[test resources] Consolidate naming logic and generate short hash names for local use

---

tools/notification-configuration/notification-creator/Contacts.cs

This PR is part of an incremental roll-out of:
- #5088
- #2770
It rolls out the new regex-based wildcard-supporting matcher to the `azure-sdk-for-net` repository.
Related preliminary work done to make this PR happen:
- https://github.com/Azure/azure-sdk-for-net/pull/33584
- https://github.com/Azure/azure-sdk-for-net/pull/33595
- https://github.com/Azure/azure-sdk-for-net/pull/33597

Enable regex-based wildcard-supporting CODEOWNERS matcher for `azure-sdk-for-net` repo

---

tools/notification-configuration/notification-configuration.sln
tools/notification-configuration/notification-creator.Tests/Azure.Sdk.Tools.NotificationConfiguration.Tests.csproj
tools/notification-configuration/notification-creator.Tests/ProgramTests.cs
tools/notification-configuration/notification-creator/Program.cs

This PR adds most basic test for `Azure.Sdk.Tools.NotificationConfiguration.Program.Main` plus makes improvements to structure and logging in `Azure.Sdk.Tools.NotificationConfiguration.Program.Main`.
This PR is a follow-up refactoring to:
- #5214
Please see that PR for more information on the wider context of this work.
The introduced project names are subject to change in upcoming PR:
- #5089

Add `Azure.Sdk.Tools.NotificationConfiguration.Tests` + improve `NotificationConfiguration.Program.Main`

---

eng/pipelines/templates/variables/globals.yml

Update the [`NotificationConfiguration` package](https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Azure.Sdk.Tools.NotificationConfiguration), to deploy these changes:
- #5214
- #5241
- #5247
See `Test Plan` here:
- https://github.com/Azure/azure-sdk-tools/pull/5214#issue-1556099565
- [the `notification-configuration` tool doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/63/Subscribe-to-Notifications?anchor=pipelines-and-sources)
- [the `automation - build-failure-notification-subscriptions` pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=679&_a=summary)

Update `NotificationConfiguration` package from `20230119.1` to `20230127.4`

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0015Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AzureAnalyzerTest.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AzureAnalyzerVerifier.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs

fixes #4444
This should pass checks once Azure.Core 1.26.0 ships.

Include NullableResponse<T> as an accepted response type

---

src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
src/dotnet/APIView/APIViewWeb/Managers/IReviewManager.cs
src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs

API review is updated when parser version changes as part of background task during server startup. This causes too many pipelines running in parallel when running one pipeline for each review to be updated. This PR has changes to:
1. Batch process reviews to be updated with an option to configure batch size
2. Also add an option to disable a specific language from background update task instead of disabling the task for all languages due to an issue in one language.

Batch background review update when parser version changes

---

tools/apiview/parsers/js-api-parser/export.ts
tools/apiview/parsers/js-api-parser/package.json
tools/apiview/parsers/js-api-parser/tokensBuilder.ts

API review JSON input file has namespace model and all public API details are under this namespace model.  APIView parser currently ignores namespace and any below members which causes issues for packages that has all it's members under a namespace. For e.g API review for change in  PR https://github.com/Azure/azure-sdk-for-js-pr/pull/236/files#diff-6dc05287911739aecce4b2d7cbc4df5699df151c14f032b5a14990cd3f5b2762 is empty.
This PR will process namespace model and its child nodes.

Create API review for JS packages with namespace in api extractor model

---

tools/apiview/parsers/js-api-parser/package.json

Pin @types/node and api-extractor model dependencies

Pin dependencies used by api parser

---

eng/common/scripts/stress-testing/deploy-stress-tests.ps1
eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
tools/stress-cluster/chaos/README.md
tools/stress-cluster/cluster/README.md
tools/stress-cluster/cluster/azure/cluster/acr.bicep
tools/stress-cluster/cluster/azure/cluster/cluster.bicep
tools/stress-cluster/cluster/azure/main.bicep
tools/stress-cluster/cluster/azure/monitoring/stress-status-workbook.bicep
tools/stress-cluster/cluster/azure/monitoring/stress-test-workbook.bicep
tools/stress-cluster/cluster/azure/parameters/dev.json
tools/stress-cluster/cluster/azure/parameters/pg.json
tools/stress-cluster/cluster/azure/parameters/prod.json
tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
tools/stress-cluster/cluster/provision.ps1

- Updating stress cluster node SKUs - use d4v4 everywhere, separate system from user pools, and add stress-watcher to the system pool
- Enable updating stress cluster nodepools via bicep deployment via an `-UpdateNodes` switch.
- Remove warnings from bicep build
- Update documentation for pool SKU label selectors
- Minor provision script fixes: missing object id and custom environment parameter validation
Fixes #4830

[stress testing] Enable nodepool update via bicep and update node SKUs

---

eng/common/scripts/Helpers/Resource-Helpers.ps1

Follow-up tracked in https://github.com/Azure/azure-sdk-tools/pull/5316

Temporarily disable error handling for Get-AzKeyVault -InRemovedState

---

tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs

This PR improves some warning messages on invalid `CODEOWNERS` paths. It is a follow-up to PR:
- #5308
As such, it contribute to:
- #2770

Improve warning messages on invalid `CODEOWNERS` paths.

---

tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Configuration/PostConfigureKeyVaultSettings.cs
tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Configuration/SecretClientProvider.cs
tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Processor.cs
tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Program.cs
tools/pipeline-owners-extractor/PipelineOwnersExtractor.sln.DotSettings

Recently I made some changes to our `Azure.Sdk.Tools.CodeOwnersParser` and somehow missed the fact this project depends on it. I also:
- de-`var`-ified some assignments and broke lines at 120 chars.

Make `PipelineOwnersExtractor` compile again + refactor

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml

- Fixes build break running perf tests on older package versions caused by Azure/azure-sdk-for-java#32573
Validation build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2171243&view=results

[Perf] Upgrade java core package versions

---

eng/pipelines/templates/steps/install-dotnet.yml
global.json

This .NET version is available on the Ubuntu 22.04 pools we use per:
- https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#net-tools
- https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-hosted-azure-devops-pools/createpoolimage
This PR also sets `DOTNET_ROLL_FORWARD` to `Major` so that tools targetting .NET `6.0` can run on .NET `7.0`.
For context, please see [this teams chat](https://teams.microsoft.com/l/message/19:59dbfadafb5e41c4890e2cd3d74cc7ba@thread.skype/1675890941633?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1675885183657&teamName=Azure%20SDK&channelName=Engineering%20System%20%F0%9F%9B%A0%EF%B8%8F&createdTime=1675890941633) and this comment:
- …

Update `.NET` from `6.0.403` to `7.0.102` + `DOTNET_ROLL_FORWARD`: `Major` + fix wrong quotes in `install-net.yml`

---

eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
eng/pipelines/templates/steps/install-dotnet.yml

Changes made per this comment:
- https://github.com/Azure/azure-sdk-tools/pull/5379#issuecomment-1424766311
and my discussion with @weshaggard 
We were already using the newest .NET SDK to build things; it comes from [`global.json`](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json). But with this PR, we also install `.NET 6.0.x` runtime, so that our tooling targeting it runs against it.
I have removed `DotNetCoreVersion` because:
- Setting `global.json` `.NET` to `6.0.x` and trying to override with `DotNetCoreVersion 7.0.x` does not work (<- this may not be true, but we want to have newest .NET in `global.json` anyway).
- Setting `global.json` `.NET` to `7.0.x` and overriding with `DotNetCoreVersion 6.0.x` would work, but then the parameter would have to be passed in many …

Install  `.NET 6.0.x` runtime. Remove `DotNetCoreVersion` param. Undo `DOTNET_ROLL_FORWARD`.

---

eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
eng/pipelines/templates/steps/install-dotnet.yml

This reverts commit 3efd6804e9eb976d9e60bc9b5dfa2fecb9a9aac7.
Reason: failure of `tools - test-proxy - ci`:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=2177474&view=results
Build to verify that the reversal works:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=2177528&view=results
Possibly related doc to help debug the issue:
https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md#global-locations

Revert "Install `.NET 7.0.x` from `global.json` and `.NET 6.0.0` runtime. Remove `DotNetCoreVersion` param. (#5395)

---

tools/apiview/emitters/cadl-apiview/CHANGELOG.md
tools/apiview/emitters/cadl-apiview/README.md
tools/apiview/emitters/cadl-apiview/package.json
tools/apiview/emitters/cadl-apiview/src/apiview.ts
tools/apiview/emitters/cadl-apiview/src/emitter.ts
tools/apiview/emitters/cadl-apiview/src/lib.ts
tools/apiview/emitters/cadl-apiview/src/version.ts
tools/apiview/emitters/cadl-apiview/test/apiview-options.test.ts
tools/apiview/emitters/cadl-apiview/test/apiview.test.ts
tools/apiview/emitters/cadl-apiview/test/test-host.ts

Closes #5289.
Updates APIView for the latest release of Cadl compiler and cadl-azure.
- **BREAKING CHANGE**: removed the `--namespace` option.
- Updates for cadl compiler 0.40 and cadl-azure 0.26.
- Adds multi-service spec support. Adds the `--service` option to filter which service to output. If not provided, it will output all services, 1 token file per service.
- Updates logic for `--output-file` and `--version` so that they can only use used on a multi-service spec if `--service` is provided.
- Adds a new option `--include-global-namespace` to allow rendering the global namespace (which would normally be excluded). ([example](https://apiview.dev/Assemblies/Review/6cb4ff5b4cb64a4f98f07ad1fcd825dc))
- Fixes a bug where namespaces that are _not_ proper subnamespaces may be included (ex: …

[Cadl APIView] Version 0.3.5

---

eng/pipelines/templates/steps/test-proxy-local-tool.yml

Because I renamed the proxy _back_ to `azure.sdk.tools.testproxy`. 😤 
Example of current failure:

Repair Failing Livetests Again

---

eng/common/pipelines/templates/jobs/perf.yml
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/LanguageBase.cs
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs
tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Util.cs

Updates profiling in performance pipeline to use new profiling directory. Performance test runs will now only run one language so there is no need to prefix the profiling directory with the language name and it can now just be called `profile`.

Update Profile Directory

---

tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Program.cs

Instead of using `DefaultAzureCredential`, we use `ChainedTokenCredential` that works like `DefaultAzureCredential` but excludes `ManagedIdentityCredential` to avoid picking up the undesired managed identity when running [
automation - pipeline-owners-extraction](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5112&_a=summary) pipeline.
Proof this code works:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2168130&view=results
For full context, please see [this added code comment](https://github.com/Azure/azure-sdk-tools/pull/5354/files#diff-290498d2f29653ea465ccfffa120a2a3b32948db397328b73cc20eee08454e2dR50-R81).

Introduce `DefaultAzureCredentialWithoutManagedIdentity` to `PipelineOwnersExtractor` to work around issue with unexpected managed identity

---

tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/CodeownersManualAnalysisTests.cs
tools/code-owners-parser/CodeOwnersParser/MatchedCodeownersEntry.cs

Before this change, commented out paths in `CODEOWNERS` violated the rule that the paths should start with `/`. As a result, the `Console.Err` was spammed with error messages, resulting in `Console.Out` truncation for `azure-sdk-for-js` and `azure-sdk-for-java` repos, making it impossible to deserialize the result written to `Console.Out` into valid json. This broke `CodeownersManualAnalysisTests` with `OutOfMemoryException` upon getting value from `Console.Err`.
This bug was introduced by:
- #5330
as that PR stopped prepending missing `/` and instead started outputting message to `Console.Err` if they were missing.
This PR also fixes a bug related to validating paths.

Bugfix: when looking for a match in `CODEOWNERS`, do not emit error message for commented out paths

---

src/dotnet/APIView/APIViewWeb/Client/src/pages/review.ts
src/dotnet/APIView/APIViewWeb/Managers/IPullRequestManager.cs
src/dotnet/APIView/APIViewWeb/Managers/PullRequestManager.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
src/dotnet/APIView/APIViewWeb/Repositories/ICosmosPullRequestsRepository.cs

Should fix https://github.com/Azure/azure-sdk-tools/issues/5143 and https://github.com/Azure/azure-sdk-tools/issues/5142

Show associated PRS and associated reviews in review page

---

src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/BadAnnotationDiagnosticRule.java

Currently, annotation ids include line numbers which can change when the source code changes and results in incorrectly showing a diff in API view.
This PR changes the annotation id to use the context (i.e the node on which the annotation is defined) to create the id.
Before:
```json
{
"DefinitionId" : "com.azure.data.appconfiguration.ConfigurationAsyncClient.ServiceClient-L51",
"Kind" : 6,
"Value" : "@ServiceClient"
},
```
After
```json
{
"DefinitionId" : "com.azure.data.appconfiguration.ConfigurationAsyncClient.ServiceClient-ConfigurationAsyncClient",
"Kind" : 6,
"Value" : "@ServiceClient"
},
```

Java ApiView: Add context to annotation id

---

eng/pipelines/templates/variables/globals.yml

Update the package version to deploy following change:
- https://github.com/Azure/azure-sdk-tools/pull/5354

Update `PipelineOwnersExtractorVersion` to `1.0.0-dev.20230211.1` to deploy `PipelineOwnersExtractor` pipeline fix for spurious MSI Azure credential

---

tools/code-owners-parser/CodeOwnersParser/CodeownersFile.cs

This PR enables the parser introduced in:
- #5063
And as such, this PR contributes to:
- #2770
Before a package published out of this PR is depended upon, a review of affected `CODEOWNERS` files is necessary, as explained in `Behavior change of existing CODEOWNERS paths with wildcards` section of this comment:
- https://github.com/Azure/azure-sdk-tools/issues/2770#issuecomment-1338923752
Full behavior difference between the old and new parser can be determined by comparing the two rightmost columns of this [test battery](https://github.com/Azure/azure-sdk-tools/blob/61a1d763b704d3d787c667a968fbbd6bb089c9fb/tools/code-owners-parser/Azure.Sdk.Tools.CodeOwnersParser.Tests/CodeOwnersFileTests.cs#L29-L132).
This parser will be executed by the [`automation - …

Enable the new, regex-based, wildcard-supporting CODEOWNERS matcher

---

eng/pipelines/templates/steps/install-dotnet.yml

For context, please see:
- https://github.com/Azure/azure-sdk-tools/pull/5405#discussion_r1105006774

Comment update: clarify we need `sdk` in `install-dotnet.yml` due to `asp.net core` runtime

---

eng/common/scripts/Cadl-Project-Sync.ps1

`[.git]` is a char set which means the url should ends with either `.`, or `g`, or `i`, or `t`. So if the url doesn't end with `.git` then there is no match which results in error.
The fix is to remove `[.git]` char set. We don't need `(.git)*` either, because `\S+` will suppress it.

fix(build): cadl build error when repo url does not end with `.git`

---

src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml

Approve label is incorrect when there are open conversations. Updated label from `Approval with Modal` to `Approve`

Update Approve label

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/InfoTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/Exceptions/SessionNotActiveException.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Info.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/ActiveMetadataModel.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/RunTimeMetadataModel.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/ActiveExtensions.cshtml
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/Error.cshtml

Resolves #5362 
@samvaity is working on transition appconfiguration to test-proxy for java. As she was doing that, she wanted to see the `order of application` of the sanitizers _after_ they are registered. This is because the java framework does a lot of behind-the-scenes work to pregister more than a few sanitizers.
It is a much easier experience to debug if folks can _actually see_ the session level customizations when they view the `Info/Active` page.
Of course, the proviso is that you can't get active information for a recording or playback session that has ended, but the test-proxy should enable this regardless.
How to use it? Before your recording stops, and while you have that recordingId on hand, hit a browser with URL:
`<proxyurl>/Info/Active?id=<recordingId>`
TODO:

`Info/Active/` now offers data for individual sessions

---

tools/test-proxy/CONTRIBUTING.md

@mario-guerra when you have a couple minutes please take a look.
Resolves #5392

Add `test-proxy` contributing.md

---

eng/pipelines/templates/variables/globals.yml

As in subject; the following PR gets deployed with this change:
- https://github.com/Azure/azure-sdk-tools/pull/5437
As a result, all build failure notification recipients will be determined based on the new regex-based, wildcard-supporting `CODEOWNERS` matcher, as opposed to the obsolete prefix-based one.
As a result, after this PR is merged, the next run of the pipeline [`automation - build-failure-notification-subscriptions`](https://dev.azure.com/azure-sdk/internal/_build?definitionId=679&_a=summary) will change the build failure notification recipients.
Related work:
- #2770

Update `NotificationConfiguration` package to `20230214.1` to enable `CODEOWNERS` regex matcher everywhere

---

.github/CODEOWNERS
eng/common/scripts/get-codeowners.ps1
eng/pipelines/agent-pool-migration.yml

This PR is part of work required in preparation to merge:
- #5088
Specifically, to enable review of ownership changes due to upcoming wildcards support, as explained in:
- https://github.com/Azure/azure-sdk-tools/pull/5088#issuecomment-1376542202
As such, this PR contributes to:
- #2770
This PR is a prerequisite for following PRs:
- https://github.com/Azure/azure-sdk-tools/pull/5431
This PR can be merged only after the following PRs are merged and relevant NuGet package published
- https://github.com/Azure/azure-sdk-tools/pull/5437
- #5104
This is because this PR depends on that NuGet package.

Update `get-codeowners.ps1` to work with the updated `RetrieveCodeOwners` executable + add some tests; make assorted refactorings

---

tools/notification-configuration/notification-creator/Contacts.cs

This PR is a follow-up to:
- https://github.com/Azure/azure-sdk-tools/pull/5452
- #5437
That previous PR was aiming to enable the new regex-based matcher everywhere, but didn't. Now it will, once the NuGet feed is updated. This is because by not passing the `useRegexMatcher` argument, I am relying on the default of `true`, set by:
- #5088
- #5437
Related work:
- #2770

Always use regex matcher when determining contacts for build failure notifications

---

eng/pipelines/templates/variables/globals.yml

This PR is a follow-up to:
- #5487
- #5452
As in subject; the following PR gets deployed with this change:
- https://github.com/Azure/azure-sdk-tools/pull/5487
As a result, all build failure notification recipients will be determined based on the new regex-based, wildcard-supporting `CODEOWNERS` matcher, as opposed to the obsolete prefix-based one.
As a result, after this PR is merged, the next run of the pipeline [`automation - build-failure-notification-subscriptions`](https://dev.azure.com/azure-sdk/internal/_build?definitionId=679&_a=summary) will change the build failure notification recipients.
Related work:
- #2770

Update `NotificationConfiguration` NuGet package version to `1.0.0-dev.20230216.1` to enable `CODEOWNERS` regex matcher everywhere

---

doc/common/matrix_generator.md
eng/common-tests/matrix-generator/samples/matrix.json
eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
eng/pipelines/agent-pool-migration.yml
eng/pipelines/apiview-review-gen-swagger.yml
eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
src/dotnet/APIView/apiview-sync-staging.yml
src/dotnet/APIView/apiview.yml
tools/apiview/parsers/cpp-api-parser/ci.yml

Where applicable, update Windows pools used to `azsdk-pool-mms-win-2022-general` and rename `vmImage` to the `windows-20xx` format.
This discussion explains why chose given `vmImage` format:
[Mike Harder: 1ES Hosted Pool image name changes](https://teams.microsoft.com/l/message/19:59dbfadafb5e41c4890e2cd3d74cc7ba@thread.skype/1676491855184?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1676491855184&teamName=Azure%20SDK&channelName=Engineering%20System%20%F0%9F%9B%A0%EF%B8%8F&createdTime=1676491855184)
posted in Azure SDK / Engineering System 🛠️ at Wednesday, February 15, 2023 12:10 PM
For further context, please see:
- https://github.com/Azure/azure-sdk-tools/issues/3407
Note that:
- searching for `MMS2021` returned no results
- …

Where applicable, update Windows pools used to `azsdk-pool-mms-win-2022-general` and rename `vmImage` to the `windows-20xx` format

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md

@xboxeer if you want to chat about these, I'll be happy to have a meeting.

Readme updates to bring clarity around questions that Elendil was asking

---

eng/common/testproxy/transition-scripts/README.md
eng/common/testproxy/transition-scripts/generate-assets-json.ps1

@billwert I had a local run of `appconfiguration` built locally for java, and my local verification absolutely omitted stuff from `target`.
Resolves #5565

Adjust Migration Guidance + which files `java` transition run picks up

---

src/dotnet/APIView/APIViewWeb/Client/src/pages/index.ts
src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml

- Load languages from static list

Don't load languages list from server

---

tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Azure/Azure.Sdk.Tools.SecretRotation.Azure.csproj
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Azure/ISecretProvider.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Azure/SecretProvider.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Cli/Azure.Sdk.Tools.SecretRotation.Cli.csproj
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Cli/Commands/RotationCommandBase.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Configuration/RotationConfiguration.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Configuration/StoreConfiguration.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Core/RotationPlan.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Core/SecretStore.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Core/SecretValue.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.AzureAppService/Azure.Sdk.Tools.SecretRotation.Stores.AzureAppService.csproj
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.AzureAppService/AzureWebsiteStore.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.AzureDevOps/Azure.Sdk.Tools.SecretRotation.Stores.AzureDevOps.csproj
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.AzureDevOps/ServiceAccountPersonalAccessTokenStore.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.KeyVault/KeyVaultCertificateStore.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.KeyVault/KeyVaultSecretStore.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/CoreTests/RotationConfigurationTests.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.sln

- Add Azure DevOps PAT store for service accounts
- This uses service account credentials defined in the store's parameters to authenticate into ADO
- PATs are issued against the service account, not the tool runner
- Add Azure App Service store for restarting websites after rotation
- The store is configured with UpdateAfterPrimary so the website restart happens after the secret is stored in the vault.
- Update rotation logic to support post-primary stores and rotation-complete annotation
- To accommodate the post-primary website restart, the new rotation flow is:
1. Originate in origin
2. Write to Secondaries where UpdateAfterPrimary == false
3. Write to Primary if Primary != Origin
4. Write to Secondaries where UpdateAfterPrimary == true
5. Annotate Primary with "rotation-complete: …

Add devops-pat and az website stores to secret rotation

---

tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/CHANGELOG
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Program.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj

Swagger API review is generated from source as well as target branch when a user submits a swagger PR. We can correct file path if swagger file path is incorrect in source side as part of PR changes. API review gen step from target branch is failing if any swagger file path is already incorrect on readme in target branch. This PR is to temporarily skip any invalid file to unblock Swagger  API review gen step.
@chidozieononiwu @ruowan @maririos

Skip invalid file path when generating swagger API review

---

tools/code-owners-parser/CodeOwnersParser/CodeownersEntry.cs

As in subject.
Candidate to be added to:
- https://github.com/Azure/azure-sdk-tools/issues/5281
Note I didn't change the type of `CodeownersEntry` to `record` as it would not help, per this doc:
- https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records
> Two variables of a class type are equal if the objects referred to are the same class type and the variables refer to the same object.

Make `CodeownersEntry.GetHashCode` support Enumerables

---

packages/python-packages/api-stub-generator/CHANGELOG.md
packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
packages/python-packages/api-stub-generator/tests/class_parsing_test.py
packages/python-packages/apistubgentest/apistubgentest/models/_models.py

[Python APIView] Fix `datetime.datetime` not appearing

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Python.cs

This enables python profiling in the perf automation framework.

[Perf][Python] Enable python profiling

---

src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs

Support searching by pull request in general search.
Resolves https://github.com/Azure/azure-sdk-tools/issues/5465

Extend APIView Search to support PullRequest in General Search

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/documentation/asset-sync/README.md

Follow-up PR to multiple proxy conversations I've had over the past week. Last remaining item is to add a `--debug` flag to the argument instead of needing to remember `Logging__LogLevel__Default`.

Readme for standalone executable + codespaces token conflicts

---

eng/common/testproxy/override-proxy-version.ps1
eng/common/testproxy/test-proxy-docker.yml
eng/common/testproxy/test-proxy-tool.yml

In the event that I actually break folks with a proxy version upgrade in `target_version.txt`, I want to be certain that our templates have true override that we can easily set when calling our template.
Even if they set it so that it doesn't start the proxy, they can invoke the `test-proxy-tool` yaml with `runProxy` set to false, so it still overrides the version but doesn't actually run it for them. Then if their tooling looks at `target_version.txt` that will be properly overwritten.
Before this change, _our_ tooling would boot up the proper proxy override version, but not update the actual file at rest in the repo. Any dependent tooling would therefor be looking for the wrong version of the proxy.
This PR is in reaction to a situation that came up with @billwert and @samvaity . They …

True Version Override in Proxy Tooling

---

src/dotnet/APIView/APIViewIntegrationTests/ReviewManagerTests.cs
src/dotnet/APIView/APIViewIntegrationTests/TestsBaseFixture.cs
src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewsPartial.cshtml
src/dotnet/APIView/APIViewWeb/Repositories/UnDeletableReviewException.cs

We currently allow deletion of API reviews created from PR and this causes baseline of PR API review (which is current latest of automatic API review revision) also to get deleted. Besides deleting a API review from PR causes to leave incomplete data about API review in APIView. We should not allow deleting API review created by automatically.

Disable delete option for PR API reviews

---

eng/pipelines/apiview-review-gen-python.yml
eng/pipelines/doc-warden.yml
eng/pipelines/mirror-pypi-to-dev-feed.yml
eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
eng/pipelines/templates/steps/use-python-version.yml
packages/python-packages/api-stub-generator/ci.yml
src/dotnet/APIView/apiview-sync-staging.yml
src/dotnet/APIView/apiview.yml
tools/pylint-extensions/pylint-guidelines-checker/ci.yml
tools/test-proxy/tests.yml

In favor of calling the pip module via `python -m `.
This should be an entirely 1:1 change. I don't expect any new issues from this.

Remove remaining bare `pip install` usage

---

tools/github-event-processor/YmlAndConfigFiles/event-processor.yml
tools/github-event-processor/YmlAndConfigFiles/scheduled-event-processor.yml
tools/github-event-processor/ci.yml

Clean up the triggers so the CI build only happens in main.
Also added a working-directory to the install steps in the actions yml files. It turns out, on Linux and Mac, dotnet tool install will fail it the working directory has any proj files in. This is, apparently, [a known issue](https://github.com/dotnet/sdk/issues/9623#issuecomment-1476692192) that's been around for several years.

Update github-event-processor's ci.yml triggers to only include main

---

tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Cli/Commands/StatusCommand.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Configuration/PlanConfiguration.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Core/RotationPlan.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Core/RotationPlanStatus.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.KeyVault/KeyVaultCertificateStore.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Stores.KeyVault/KeyVaultSecretStore.cs
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/four.json
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/named-1.json
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/named-2.json
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/one.json
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/three.json
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/TagMatching/two.json
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/Valid/manual-value.json
tools/secret-rotation/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/Valid/random-string.json
tools/secret-rotation/schema/1.0.0/plan.json

Move schema into the tool folder
Greatly improve status command output
Fix exception handling in Key Vault stores
- Key Vault 404 exception messages are very long, causing overly verbose console output when a secret is missing

Improve status command output and improve error handling

---

eng/common/scripts/trust-proxy-certificate.ps1

[Query of failures graciously provided by @benbp](https://dataexplorer.azure.com/clusters/azsdkengsys.westus2/databases/Pipelines?query=H4sIAAAAAAAAA2WPTU/DMAyG7/sVVk4taputnYaYVBC7IXFAgztKE7fL6JIocZlA/Hj6gdimXXyw/fp5vOl0q970AVttcIvSejXj/AeOO/QIryQ8DVOokI6IBiIlCKnvRPk8L9J5kS6WMWQZXPdXcTy7PnQPorHRYqniM84WnQ2arP96UlCWwB6/O49cDDUN6iOtrU+lc+wssxnMp/V8VeTF3e0/7QakNSS0CcCehWk60fQKDqWutWQgjOqJoWtpZNVCt6hYn3be7lHSyTa5MEsgkJeCIrYjcmHNucLPbJTMpD2cdDlL4GW6NaQYf68GWe5HaHioJvWyX/v7Iv4Fh2EaS4gBAAA=)
This is occurring _most often_ when there is no output from this script due to no implementation of `Import-Dev-Cert-<Language>`. This _should not be failing_ and I truly believe this is a devops issue, but in the meantime perhaps this can reduce incidence.

Add default output to call to `trust-proxy-certificate.ps1`

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitProcessHandlerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs

Attempts to address #5660
Given the fact that we're shelling out and the exit code isn't different for every error, this looks like the way to go.

Add retry on specific git output

---

src/dotnet/APIView/APIViewUnitTests/LanguageServiceTests.cs
src/dotnet/APIView/APIViewWeb/Client/src/pages/index.ts
src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
src/dotnet/APIView/APIViewWeb/Languages/CLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/CSharpLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/GoLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/JsonLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/ProtocolLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/SwaggerLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/TypeSpecLanguageService.cs
src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Profile.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewUploadHelp.cshtml
src/dotnet/APIView/APIViewWeb/README.md
src/dotnet/APIView/APIViewWeb/Startup.cs

CADL to TypeSpec rename. Should resolve https://github.com/Azure/azure-sdk-tools/issues/5635
Blocked by:
Updates to https://github.com/Azure/azure-sdk-tools/blob/7c10ce5ef4641263b81e775aa181d82750a83da1/src/dotnet/APIView/APIViewWeb/Languages/CadlLanguageService.cs
Updated to DataBase

Update cadl to TypeSpec

---

eng/common/scripts/git-branch-push.ps1

https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.3#psnativecommandargumentpassing Do to that breaking change in PS 7.3 we need to opt into the legacy arg parsing.

Explicitly set PSNativeCommandArgumentPassing to Legacy for git push script

---

tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/MockGitHubEventClient.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Constants/RateLimitConstants.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/ScheduledEventProcessing.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs

Previously, I was ulta-conservative on the governor for scheduled events. The limit was set to 100 items per scheduled task run which is still correct for non-enterprise repository actions. For enterprise, however, the actions rate limit is 15,000 and, in that case, we can allow the scheduled tasks to process up to 1000, which is the number of results you can get back from search calls in a given time without hitting the secondary rate limit.
I also put the scheduled event into a try/finally since, we can hit the secondary rate limit on subsequent calls to get the next page of results. If that happens, we still need to process any pending changes made from previous pages of search results, if there are any.

Update the scheduled event governor based upon the actions rate limit

---

src/dotnet/APIView/APIViewWeb/Managers/NotificationManager.cs

- Add trace for each email notification
- Fix issue when override email address for testing is empty. Currently request is sent to logic app with empty email address.

Fix issue in email notification when override email is not set

---

eng/common/pipelines/templates/steps/credscan.yml

The current pinned version of credscan now fails due to missing NET 3.1

Bump credscan to 2.3.12.23

---

tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ApiViewMessage.cpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ApiViewMessage.hpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstNode.cpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/CMakeLists.txt
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ProcessorImpl.cpp
tools/apiview/parsers/cpp-api-parser/ParseTests/CMakeLists.txt
tools/apiview/parsers/cpp-api-parser/ParseTests/TestCases/SimpleTest.cpp
tools/apiview/parsers/cpp-api-parser/ParseTests/TestCases/UsingNamespace.cpp
tools/apiview/parsers/cpp-api-parser/ParseTests/tests.cpp
tools/apiview/parsers/cpp-api-parser/README.md
tools/apiview/parsers/cpp-api-parser/ports/llvm/0001-Fix-install-paths.patch
tools/apiview/parsers/cpp-api-parser/ports/llvm/0002-Fix-DR-1734.patch
tools/apiview/parsers/cpp-api-parser/ports/llvm/0003-Fix-tools-path.patch
tools/apiview/parsers/cpp-api-parser/ports/llvm/0004-Fix-compiler-rt-install-path.patch
tools/apiview/parsers/cpp-api-parser/ports/llvm/0005-Fix-tools-install-path.patch
tools/apiview/parsers/cpp-api-parser/ports/llvm/0006-Fix-libffi.patch
tools/apiview/parsers/cpp-api-parser/ports/llvm/0007-Fix-install-bolt.patch
tools/apiview/parsers/cpp-api-parser/ports/llvm/clang_usage.txt
tools/apiview/parsers/cpp-api-parser/ports/llvm/flang_usage.txt
tools/apiview/parsers/cpp-api-parser/ports/llvm/lld_usage.txt
tools/apiview/parsers/cpp-api-parser/ports/llvm/llvm_usage.txt
tools/apiview/parsers/cpp-api-parser/ports/llvm/mlir_usage.txt
tools/apiview/parsers/cpp-api-parser/ports/llvm/portfile.cmake
tools/apiview/parsers/cpp-api-parser/ports/llvm/vcpkg.json
tools/apiview/parsers/cpp-api-parser/vcpkg.json

Use a custom vcpkg port for clang-15 because vcpkg currently doesn't have clang-15 available.
clang-15 port files liberally stolen from https://github.com/microsoft/vcpkg/pull/26902.

Updated ApiView to use clang-15 to work around MSVC STL changes; fixed warning in keyvault-admin ApiView

---

eng/common/TestResources/SubConfig-Helpers.ps1

This PR fixes an issue introduced in https://github.com/Azure/azure-sdk-tools/pull/5242 which stopped respecting BaseName parameter overrides in CI mode. This caused issues in stress deployments where we intentionally override BaseName to get a short name hash and need the value to match up with other places where inject it.
CC @richardpark-msft @lmolkova

[test resources] Fix regression - base name overrides in CI

---

src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ExpandableStringEnumDiagnosticRule.java

Add diagnostic rules for ExpandableStringEnum

---

eng/common/scripts/Add-RetentionLease.ps1
eng/common/scripts/Invoke-DevOpsAPI.ps1
eng/common/scripts/Queue-Pipeline.ps1
eng/common/scripts/logging.ps1
eng/pipelines/templates/steps/sync-directory.yml

For most of these we can use the standard System.AccessToken given to the build instead of maintaining a specific token. However that token isn't base 64 encoded so we need to encode it.
With this we can stop explicitly passing PAT's unless we need to access another DevOps org and we also don't have to remember to keep the PAT's in KV base 64 encoded.

Switch to using standard PAT tokens instead of base 64

---

tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/ApiPath.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/fixtures/azureopenai.json

Ensure ApiPath does not get a NullReferenceExcepton when copying common parameters to operation method parameters.
Previously, when the operation method does not have any parameters a NullRefferenceException occurs when attempting to copy the common parameters to the operation method.
I encountered this when working on DevCenter RP and it looks like others have hit this issue as well: #5810

Fix NullReferenceException happening in ApiPath

---

tools/github-event-processor/RULES.md

The rule name is actually ResetApprovalsForUntrustedChanges and the criteria listed was incorrect. There is no more auto-merge label, the rule is looking at whether or not Enable auto-merge was set on the PR through the GitHub UI.

Update rule name and criteria

---

tools/apiview/emitters/typespec-apiview/CHANGELOG.md
tools/apiview/emitters/typespec-apiview/package.json
tools/apiview/emitters/typespec-apiview/src/version.ts

Should allow APIView to "just work" with future TypeSpec releases without the need for a release.

[TypeSpec APIView] ﻿Unrestrict dependencies

---

tools/test-proxy/documentation/asset-sync/README.md

@benbp I had a 3rd person today reach out with proxy issues started with
> so I'm doing this on WSL
and I see `/mnt/c/blah/` in the problem description and immediately know what happened. Adding some documentation 👍

Add note about sharing between WSL / windows

---

eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1

Stress test deployment now requires helm version 3.11.0+, now throwing a more descriptive error

stress test error out for breaking helm versions

---

tools/stress-cluster/chaos/examples/network-stress-example/.gitignore
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/.gitignore
tools/stress-cluster/chaos/examples/stress-debug-share-example/.gitignore
tools/stress-cluster/chaos/examples/stress-debug-share-example/scenarios-matrix.yaml
tools/stress-cluster/chaos/examples/stress-debug-share-example/templates/debug-share-job.yaml
tools/stress-cluster/chaos/examples/stress-deployment-example/.gitignore

Just adding in some comments to make it a bit easier to understand what's mandatory and what's not and adding in individual .gitignore files for common stuff.

Updating the stress-debug-share-example

---

tools/sdk-testgen/ci.yml

A follow-up to:
- https://github.com/Azure/azure-sdk-tools/pull/6004
Applying this change, which has been reverted in #6004:
- https://github.com/Azure/azure-sdk-tools/pull/6004/commits/ac1c9b7652274f9961e76f718ec3ea9c9ad4f268
Related work:
- https://github.com/Azure/azure-sdk-tools/issues/5472

Update sdk-testgen vmImage to ubuntu-22.04

---

tools/code-owners-parser/CodeOwnersParser/FileHelpers.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/MockGitHubEventClient.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Constants/ConfigConstants.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Program.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Utils/CodeOwnerUtils.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Utils/RulesConfiguration.cs

Instead if requiring a sparse-checkout in the action, pull the config files (CODEOWNERS and rules config) files from the raw githubusercontent.
One thing of note here: I realize it's odd that I'm using the FileHelpers from the CodeOwnersParser to load the rules config file but there's no common utilities project and I really didn't want to copy the code and have to add the retry logic in multiple places.
The other change was when rules are loaded. Previously rules were loaded when the GitHubEventClient was constructed but now, like the CODEOWNERS, which is loaded when it's first needed.
The DirectoryUtil is going to remain until we know we can absolutely remove it.

Have event processor get configs from raw githubusercontent instead of needing a sparse checkout

---

eng/common/scripts/Verify-RequiredDocsJsonMembers.ps1

A while back there were changes made to the metadata json files a docs repository that caused doc entries on MsDocs to disappear and we had to ferret out where that happened. It happened because the json files contained empty versions which, ultimately, ended up causing them to get removed. This is a bare bones script that takes a few seconds to run and verifies that the json files in the metadata\latest and metadata\preview directories has the have the minimum required members and that they are non-null. It does not verify correctness of these entries. The script will scan and report all errors encountered.
Once this script is checked into common and propagated out to the language repositories, the docindex pipelines will have a task inserted after ToC generation (which can update/change …

Script to verify that the json files used to generate docs have the required members.

---

tools/apiview/parsers/js-api-parser/export.ts
tools/apiview/parsers/js-api-parser/tokensBuilder.ts

This change adds support for displaying api-extractor release tags [(doc)](https://api-extractor.com/pages/tsdoc/tag_beta/)

[TypeScript Parser] support release tags

---

tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Program.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerAPIViewGenerator.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewRoot.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/SchemaCache.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/SwaggerTypes.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Utils.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/SwaggerAPIViewGeneratorTest.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/SwaggerAPIViewTest.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/fixtures/devcenter.json

This fixes 
https://github.com/Azure/azure-sdk-tools/issues/5837
However, the bigger issue is that the parser does not account properly for schema referenced in other swagger files. I have created [this issue](https://github.com/Azure/azure-sdk-tools/issues/6008) to continue tracking work on the parser.

Make Swagger Parser Pull in Properties referenced in other files

---

eng/pipelines/templates/steps/apiview-ui-tests.yml
src/dotnet/APIView/APIView/CodeFileRenderer.cs
src/dotnet/APIView/APIView/Model/CodeFile.cs
src/dotnet/APIView/APIViewIntegrationTests/APIViewIntegrationTests.csproj
src/dotnet/APIView/APIViewIntegrationTests/ReviewManagerTests.cs
src/dotnet/APIView/APIViewIntegrationTests/TestsBaseFixture.cs
src/dotnet/APIView/APIViewUnitTests/CodeFileRendererTests.cs
src/dotnet/APIView/APIViewUnitTests/ReviewManagerTests.cs.cs
src/dotnet/APIView/APIViewWeb/Client/css/shared/codeline.scss
src/dotnet/APIView/APIViewWeb/HostedServices/SwaggerReviewsBackgroundHostedService.cs
src/dotnet/APIView/APIViewWeb/Managers/IReviewManager.cs
src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
src/dotnet/APIView/APIViewWeb/Startup.cs
src/dotnet/APIView/apiview.yml

- Split Swagger Inline Tables into separated code lines.
- Add Background task that
- Updates Precomputed Line Numbers Metadata.
- Updates referencing comments
- Updates Precomputed Diff Line Metadata.
Resolves https://github.com/Azure/azure-sdk-tools/issues/5831
Demo Link https://apiviewuat.azurewebsites.net/Assemblies/Review/1872ee16e46e4b288026e05aff3a5776?revisionId=14688791636e4b73ae1e9426155031f7&diffRevisionId=9a716effb6174b98ae0da797cf5903d3&doc=False&diffOnly=False
BEFORE
AFTER

Convert Inline Table Rows to Individual CodeLines

---

src/dotnet/APIView/APIViewUITests/SmokeTests.cs

Modified smoke test to create C# api review is blocking API view release. This PR is to unblock the release by disabling this failing test.

Skip failing create API review test case

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/InvocationTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/OptionsGenerator.cs

Really....not an issue that should be occuring.
@timovv @KarishmaGhiya thank you for raising the issue. This one makes me 🤦

Resolve broken `storageLocation` short alias

---

tools/test-proxy/tests.yml

CC @billwert @samvaity 
Ensuring that I can't accidentally break your use-case in the future!
Resolves #6084

Add Java Local Tests to Proxy Nightly Integration Tests

---

doc/workflows/engsys_workflows.md
eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
eng/common/scripts/Delete-RemoteBranches.ps1
eng/pipelines/branch-cleanup.yml
eng/pipelines/eng-workflows-sync.yml

Changes so we can sync .github/workflows the same way we're doing with eng/common.
1. eng/pipelines/eng-workflows-sync.yml - similar to [eng/pipelines/eng-common-sync.yml](https://github.com/Azure/azure-sdk-tools/blob/main/eng/pipelines/eng-common-sync.yml) except this does the .github/workflows directory. The common code was already factored out into a template, [eng/pipelines/templates/stages/archetype-sdk-tool-repo-sync.yml](https://github.com/Azure/azure-sdk-tools/blob/main/eng/pipelines/templates/stages/archetype-sdk-tool-repo-sync.yml) as part of this [PR](https://github.com/Azure/azure-sdk-tools/pull/6034). Once this has been merged a pipeline will need to be created from this.
2. eng/pipelines/branch-cleanup.yml - updated to add Azure/azure-sdk to the list of repositories and a …

Eng workflows sync and branch cleanup additions

---

.github/workflows/event-processor.yml
.github/workflows/scheduled-event-processor.yml

The full description of the update is in the [tools PR](https://github.com/Azure/azure-sdk-tools/pull/6099) with the code changes. This removes the pull_request_review processing from the event-processor.yml file and updates the version of the GitHubEventProcessor install.

Update GitHubEventProcessor version and remove pull_request_review procesing

---

eng/scripts/download_targeted_packages_requirements.txt

`urllib3` 2.0.0+ has released. This is a breaking change package.
`twine` has an unsafe requirement on `urllib3`, so we started blowing up on upload. Attempting a pin to work around.
[Successful Test run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2763176&view=results)

Ensure old version of urllib3 is pinned

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs

In order to skip matching the browser's dynamic headers for our recordings, we skipped the headers listed in https://github.com/Azure/azure-sdk-tools/pull/2185#discussion_r751718764
And this was Scott's reaction and the typo crept in
[[Test-Proxy] Header Exclusion Updates by scbedd · Pull Request #2317 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/pull/2317)
@jeremymeng was upgrading the puppeteer version and the `"sec-ch-ua"` header mismatch occurred, and @timovv pointed out the list. 
We could've used a sanitizer, but fixing the source feels righteous.

[Test Proxy] Fix typo - Update RecordMatcher.cs

---

eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml

If we aren't building standalone exe's skip the job all together.
Looks like this wasn't covered in the original change at https://github.com/Azure/azure-sdk-tools/pull/5174#discussion_r1137972871

Skip Produce Executable Job if not needed

---

eng/pipelines/githubio-linkcheck.yml

We need to add a place to help catch broken links in things like eng/common so that we can fix them before they break more pipelines in the other languages. This will enable us to find them from the nightly run.

Add tool link checks in nightly link checks

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/OptionsGenerator.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/documentation/asset-sync/README.md

@samvaity for FYI, totally missed doing so with the original PR.

Add documentation covering usage of the test-proxy config feature

---

eng/common/testproxy/publish-proxy-logs.yml

Two fixes:
1) Add `condition: succeededOrFailed()` to the copy/delete steps so they run if there are earlier failures in the pipeline.
2) Add more discrimination to the artifact name to prevent potential collisions.

Fixes for uploading proxy logs

---

eng/common/scripts/TypeSpec-Project-Process.ps1

- Refine regex
- Remove temp tspconfig.yaml
- Use relative path as directory in tsplocation.yaml
@weshaggard , the third change is a fix of a bug and needs to get merged to unblock integration work with other languages.

Updated typespec common script

---

eng/common/scripts/TypeSpec-Project-Generate.ps1

Currently, the Autorest Regen Preview pipeline for autorest.csharp publishes alpha versions of the c# emitter package to an alternate package feed. This is breaking the validation builds of azure-sdk-for-net because the alpha version specified doesn't exist in the default public repository.
To fix this, if we detect an alpha package version number in emitter-package.json, we create an npmrc file prior to running the code generation check.

Use test registry in npmrc for alpha packages

---

eng/common/scripts/TypeSpec-Project-Process.ps1

- Revert change of `TypeSpecProjectDirectory` path match as it's used to load tspconfig firstly
- Stop execution if returning failure after call sync script
- Add repo variable assignment in local path scenario
//CC: @weshaggard

Few update on common process script

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs

Before this PR, a user could start a recording with a a target file, or _no_ target file. No target file being provided means the recording should be entirely in-memory.
```jsonc
// POST /Record/Playback
// body
{
"x-recording-file": "blah.json"
}
// returns x-recording-id for use by recording framework
```
```jsonc
// POST /Record/Playback
// body
{
}
// returns x-recording-id for use by recording framework
```
@samvaity recently was debugging a proxy start, and while the issue ended up being that the request body wasn't being formed correctly, the test-proxy didn't _inform_ Sameeksha about that problem. To the test-proxy, @samvaity was just starting an in-memory recording.
The perf framework currently sends _no_ body when attempting to start an in-memory recording. We will take …

Add differentiation between a null body and an empty body 

---

eng/common/scripts/Update-DocsMsPackages.ps1

Make Json files the source of truth when generating the ToC/Docs. For libraries released from our engineering system the json files get updated as part of the release process. For libraries released outside of our engineering system, [we have a process](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/953/Releasing-docs-outside-of-Azure-SDK-Engineering-System) which we've trimmed down so the team just needs to add/update their own json files. As a result of this, pulling data from the CSV is no longer necessary.
Fixes #6117

Make Json files the source of truth for DocsMS

---

eng/common/scripts/TypeSpec-Project-Generate.ps1
eng/common/scripts/TypeSpec-Project-Process.ps1
eng/common/scripts/TypeSpec-Project-Sync.ps1

- Add `LocalSpecRepoPath` to sync script
- Code style fix
@weshaggard , this PR shouldn't be merged until all sdk language repos adopt new common scripts.
Fixing this issue in sync script.
https://github.com/Azure/azure-sdk-tools/issues/6279

Support localspecrepo if pass in this parameter

---

eng/common/scripts/TypeSpec-Project-Process.ps1

In local spec repo scenario, script would use the local cloned spec repo HEAD commit to create `tsp-location.yaml` if the file doesn't exist. Once the file is created, script would proceed the sdk generation based upon the local spec repo folder.
@weshaggard

Use local HEAD commit to create tsp-location.yaml

---

tools/test-proxy/documentation/asset-sync/README.md

@konrad-jamrozik  you said that we never really specified what an `asset` was in another PR. I thought you were right right up until I read the intro to the doc
```
The `test-proxy` optionally offers integration with other git repositories for **storing** and **retrieving** recordings. This enables the proxy to work against repositories that do not emplace their test recordings directly alongside their test implementations.
```
I feel like this is extremely clear about  `asset-sync` does, but I never actually tied it to the keyword `assets`. This PR does that for clarity 👍

Asset-Sync Documentation Update

---

tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen/Azure.SDK.Management.ChangelogGen.csproj

Update changeloggen project's PackAsTool property to be true so that it can be installed and used through 'dotnet tool install' easily when using the tool from .net azure sdk repo.

Update changeloggen project's PackAsTool to true

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0002Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0017Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0018Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAnalyzerBase.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Descriptors.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/SymbolAnalyzerBase.cs

Update AZC00002 to match method pair with required requestcontext and optional convenience method

---

eng/common/pipelines/templates/steps/sparse-checkout.yml

@benbp I've tested this change in my throwaway Java [release branch](https://github.com/Azure/azure-sdk-for-java/blob/release/spring-test-no-release/eng/common/pipelines/templates/steps/sparse-checkout.yml#L49). The placement of the call was specifically after the clone command which is the command that first creates the git directory.
The [pipeline run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2842804&view=logs&j=3517b659-d3e8-545e-d9c6-aff172e087bb&t=0ebe3253-9a8a-510d-335c-c28d789c1ff8) I'd done also removed the interim call I'd added to Java's release yml to ensure everything worked.
Fixes #6294

Turn off git auto gc for sparse-checkout

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationRestoreTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

The original thought is that if you had pending changes, but wanted to swap to a different checked out tag for an `assets.json`, you would be **prevented** from doing so with
> you have pending changes
So that folks can avoid discarding recordings. However, because a lot of these are running behind a shim or some other surrounding script, folks don't see the proxy output clearly. Because they can't see what's going wrong with the proxy, they don't know what to try next.
This PR will eliminate this scenario.
CC @mssfang @samvaity  for FYI

Allow `Restore` to discard pending changes

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

Resolves #6238
This PR gates initialization of a git repo behind a tiny task queue. We do this because if we don't, we run into the following situation:
1. The Java team runs tests truly in parallel. This means that multiple tests are attempting to load up the recordings for playback.
2. As multiple tests are attempting to load, there is no assets repo present, so we have to do a `restore` operation for each.
3. Our `git` invocations are already work-queued, so the actual `restore` action won't throw. This is because once the repo is `git init`-ed, `git checkout` can be fired multiple times without error, as attempting to check out the same tag is an errorless action.
Given all the above context, we are wrapping the whole `Init` function that checks/initializes each assets repo slice (per …

Resolve Multi-Restore Deadlock

---

src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingAnnotationsDiagnosticRule.java
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingJavadocCodeSnippetsRule.java
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/UpperCaseEnumValuesDiagnosticRule.java
src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Pom.java

A number of fixes to the Java APIView tooling, discovered and developed as I went about creating APIView reviews for the Java Semantic Kernel library. You can see the generated APIView reviews for these libraries here:
https://apiview.dev/Assemblies/Review/8aa5b4eae87c47a9996bf9c80163812e
https://apiview.dev/Assemblies/Review/f52ac2e951734ee0a2c010481892fe32
https://apiview.dev/Assemblies/Review/73736094cf044f70b82a0618a97776f4
Here are the changes I have made:
* Support for when a pom.xml does not explicitly state a groupId or version - look up in parent, if it is available.
* Don't analyse files in META-INF, as some builds put .java files in there, and they are not always valid Java.
* Fixing issue where not all inner types are discovered when calling getClasses. This also resulted in …

Improvements to APIView/Java tooling

---

tools/openapihub-redirect/README.md
tools/openapihub-redirect/app.py
tools/openapihub-redirect/index.html

This is a simple web app we deploy to app services that `portal.azure-devex-tools.com` lands on. This app does a client-side check to see if `openapihub.azure-devex-tools.com` is accessible and if so redirects to it, preserving any path and query parameters. If it is not accessible, the site redirects to https://aka.ms/openapihub-landing which tells users how to get access to corp net if they are not on campus.

Add openapi hub redirect app

---

tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.json
tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.md
tools/sdk-testgen/packages/autorest.testmodeler/package.json
tools/sdk-testgen/packages/autorest.testmodeler/src/core/model.ts
tools/sdk-testgen/packages/autorest.testmodeler/test/unittest/core/__snapshots__/testModel.ts.snap
tools/sdk-testgen/packages/autorest.testmodeler/test/unittest/core/testModel.ts

We are supporting DFE(DataFactoryElement) in SDK Sample Generation which needs the corresponding support in SDK_Testgen to generate Example Model properly. In detail. the DFE is special and is defined as AnyObject schema now which causes its Example value won't be generated properly. We are adding support for it to generate Example model properly from it's x-ms-format definition. 
If you are interested, detail information about DataFactoryElement can be found at https://gist.github.com/JoshLove-msft/e7e85e44d6fd24c87e362a37260c9d21

Support DataFactoryElement in sdk_testgen

---

eng/pipelines/templates/steps/sync-repo-merge-branch.yml

In order to do preserve the merge commits for the branch merges I needed to make a fix to our existing git-push-branch script but instead of doing that I'm going to use this process to test out using gh cli for our branch creation and if this experiment goes well we can consider moving to this for all our pull request creation needs.

Use gh cli to create pull request for branch mirroring

---

tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_pylint_custom_plugins.py

varargs were not being pulled in when checking docstring args

[Pylint] vararg bug fix

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md

We recently had an instance where a partner team intended to set up the test proxy tool for testing their already-migrated Python library. Instead of referring to our language-specific test docs, though, they found this `azure-sdk-tools` documentation; this made them think that they had to set up the test proxy tool manually with .NET/Docker, but Python's tooling actually handles tool installation and startup for them.
To avoid this issue, I think it would be good to have a disclaimer at the start of this document to let people know that this isn't meant for test writers' reference. I added links to what seem to be the test-writing guides for each language, but it would be great if each language's test proxy owner could double-check them 🙂

[Test-Proxy] Point users to language repository test documentation

---

eng/pipelines/pipeline-owners-extraction.yml
tools/github-team-user-store/README.md

Add the build/run of github-team-user-store to the pipeline-owners-extraction. The variable group, [azuresdkartifacts azure-sdk-write-teams variables](https://dev.azure.com/azure-sdk/internal/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=133&path=azuresdkartifacts%20azure-sdk-write-teams%20variables), has already been added to the pipeline.

Add team/user store to pipeline-owners-extracton

---

.github/workflows/event-processor.yml
.github/workflows/scheduled-event-processor.yml
eng/common/scripts/get-codeowners.lib.ps1

There was a [recent change to CodeOwnersParser](https://github.com/Azure/azure-sdk-tools/pull/6366) and we'll now lookup the users for a team when we encounter a team in CODEOWNERS. _Note: The caveat with this is that teams in CODEOWNERS files need to have write permissions and should all be child teams of Azure/azure-sdk-write._ The update to CodeOwnersParser requires updates to the following:
1. github-event-processor uses CodeOwnersParser in a couple of existing rules and should allow us to expand the [Initial Issue Triage](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github-event-processor/RULES.md#initial-issue-triage) rule.
2. get-codeowners.lib.ps1 (currently only used by the [Metadata-Helpers.sp1](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Hel …

Updates for Codeowners changes

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationRestoreTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStoreBreadcrumb.cs
tools/test-proxy/scripts/test-scripts/CLIIntegration.Tests.ps1

The proxy maintains a tiny dictionary of `<assets-json-location>: <target-tag>`
We use this little dictionary to [short circuit](https://github.com/Azure/azure-sdk-tools/blob/b14dd081686ceb639049a2e0a7762eb7d179da27/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs#L324) our checkout process. However, when I refactored to allow automatic checkout to discard pending changes, I didn't properly account for loading this dictionary into memory. This caused us to always treat even the same tag that was currently checked out as a `new` tag, which causes us to discard changes when `restoring`.
By refreshing this local cache once per object lifetime, we can avoid this "I didn't know it was there already" discard of pending changes.
todo:

Fix playback always discarding pending changes

---

doc/common/TypeSpec-Project-Scripts.md
eng/common/scripts/TypeSpec-Project-Process.ps1
eng/common/scripts/TypeSpec-Project-Sync.ps1

What are the changes?
- doc update
- support sync script and generate script call when it's new sdk project
- remove duplicated 'specification' in `localSpecRepoPath` (reverted this point)
@weshaggard , please review.

Update typespec common scripts

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

I truly don't understand why we don't see this consistently.
[Example error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2905364&view=logs&j=c80ec937-014a-532d-a6f0-bd9912040eb3&t=a2f2a75c-2929-5547-c2c1-26b2dae91467&l=178)

Eliminate `*` is not a valid pathspec on non-windows machines

---

tools/pylint-extensions/azure-pylint-guidelines-checker/README.md
tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_pylint_custom_plugins.py

[pylint] do not import legacy six

---

tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/ScheduledEventProcessing.cs

Locking the issues after 90 days is a brand new rule. It's also the end of a long path (requiring 90 days of inactivity after 7 and then 14 days of inactivity respectively). As it turns out, after an issue has been closed and locked someone can come back and reopen the issue but leave it locked. The problem with locked issues is comments can't be added which is what most of our scheduled tasks do. This was causing processing failures. The correct solution is to modify the query to omit locked issues from the results. It's also worth noting that these queries should have been omitting locked items from the query result to begin with. Notice that the LockClosedIssues only ever looks for issues that aren't already locked which is what the other queries should have been doing to begin with.

Do not pull back locked issues/PRs in scheduled events queries

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

There are tests in the Java repo which parse the recording files for various reasons. Add a header on the response of playback start to share that location.
I also noticed that the tests were using the wrong assertion for headers, so I changed it to check for string empty/null. (Even null is unnecessary - could be a test against `String.Empty` if you prefer.)

Add recording file location

---

src/dotnet/APIView/APIViewWeb/Client/src/shared/comments.ts
src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadInnerPartial.cshtml

No change to functionality, just changing this from using the asp.net form component.
This is needed to support automatic comment updates.

Re-Implement Comment deletion without using asp.net core form

---

eng/common/pipelines/templates/steps/docsms-ensure-validation.yml
eng/common/scripts/Update-DocsMsMetadata.ps1

This PR adds the ability to fail nightly docs builds if validation fails. This capability is not active in this PR as these need to be individually wired up in `docindex.yml`
Example builds: 
* .NET 
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2928742&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2928743&view=results
* JS
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2928744&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2928746&view=results
* Python 
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2928748&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2928751&view=results
* Java
* Example build showing expected failure when wired up …

[eng/common] Update-DocsMsMetadata.ps1 can fail the build on invalid packages

---

eng/common/spelling/package-lock.json

To resolve some scan issues with old transitive deps.

Update deps for spelling tool

---

eng/common/scripts/Save-Package-Properties.ps1

Prevents overwrites of track 2 package info by track 1 packages.

Only save package properties for track 2 packages 

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

Paths can have characters that are illegal for header values. Base64 encoding the path will prevent issues here.

Base64 encode path

---

eng/common/TestResources/README.md
eng/common/scripts/X509Certificate2/README.md
eng/common/scripts/X509Certificate2/X509Certificate2.psm1

Copying from https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/X509Certificate2/X509Certificate2.psm1 so that we can share cert generating functionality.
Thanks for the suggestion @conniey

Make x509 certificate script from azure-sdk-for-net common to repos

---

tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Specs/Schema.cs

Show the first level properties of Models in Swagger response without showing nested models.
Example https://apiviewuat.azurewebsites.net/Assemblies/Review/a71b14f76bb9432bb56d22b98d43e103#-billingSubscription.json-Definitions-MoveEligibilityResult

Show model properties in response body

---

eng/pipelines/mirror-repos.yml

- We are frequently manually running this pipeline to mirror azure-rest-api-specs
- Only changes order repos/branches are mirrored, no repos/branches were added or removed

[mirror-repos] Mirror azure-rest-api-specs before other repos

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitStoreTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStoreBreadcrumb.cs
tools/test-proxy/scripts/test-scripts/CLIIntegration.Tests.ps1
tools/test-proxy/scripts/test-scripts/assets.Tests.Helpers.ps1
tools/test-proxy/tests.yml

See title. This addresses the issues that were temporarily mitigated by [this .NET PR](https://github.com/Azure/azure-sdk-for-net/pull/37868).

Use breadcrumbfiles associated with each asset, versus shared

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/DebugLogger.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md

This will allow users to set an env var Logging__LogLevel__Azure.Sdk.Tools.TestProxy = "Debug" instead of changing the Default or DebugLogging category. _Note changing Default will still work in the same way and I don't think we advertised "DebugLogging" to anyone so it hopefully won't break anyone._ However, changing the Default log level would break tests in .NET since it would cause tests to start emitting logs. 
By introducing a specific logging category (or more accurately renaming the specific logging category), we can let it still be configurable for users without requiring users to change the Default level.

Change logging category to include TestProxy

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Python.cs

The package doesn't need to be in editable mode, and we found that this can cause issues when dev dependencies that share the same namespace are installed alongside the main package.

[Perf][Python] Don't install package in editable mode

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs

Lower the StdErrErrorThreshold to `Error` so that `Logging.Error` show up on stderr.
Resolves #6563 so that the .NET framework will actually see the stderr output when collecting it for the error.

Update Exception Logging

---

tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.json
tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.md
tools/sdk-testgen/packages/autorest.testmodeler/package.json
tools/sdk-testgen/packages/autorest.testmodeler/src/core/model.ts

Fix the support of generating Example Model of DataFactoryKeyVaultReference type of DataFactoryElement according to the change in Azure.Core.Expression.DataFactory

Fix the support of generating Example Model of DataFactoryKeyVaultReference type of DataFactoryElement

---

eng/common/scripts/Helpers/Resource-Helpers.ps1

The previous property was calculated so didn't exist from the REST-based
call. Also updated the api-version to the latest stable control plane
version.

Used ScheduledPurgeDate for both KV, MHSM

---

src/dotnet/Azure.ClientSdk.Analyzers/readme.md

This is the steps that when you are changing the analyzer and want to see how it applies to azure-sdk-for-net.

Add document to test WIP analyzer

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/LoggingTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestLogger.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/DebugLogger.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs

Previously logging for admin requests was validating that the upstream request uri header was set, which was incorrect.

Fix admin logging

---

.github/event-processor.config

Enable the ManualIssueTriage rule for azure-sdk-tools.

Enable ManualIssueTriage for azure-sdk-tools

---

src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java

Fixes the filter that was skipping all files  in `META-INF` files which also included `pom.xml`.

Fix missing maven section in API view

---

eng/pipelines/pipeline-owners-extraction.yml
tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/Constants/ProductAndTeamConstants.cs
tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/GitHubEventClient.cs
tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/Program.cs
tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/RepositoryLabelGenerator.cs
tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/TeamUserGenerator.cs

The team/user store used to only store team/user data for teams with write permissions (teams under, and including, azure-sdk-write). _This data is used to expand teams in CODEOWNERS files for Azure repositories._ During the analysis for the development of a CODEOWNERS linter, it was quickly discovered that we needed more than just the team/user data. We needed the following:
1. User/Org visibility data. Our [documentation](https://eng.ms/docs/products/azure-developer-experience/onboard/access-repos) states that user's Azure org membership must be public and this information was needed to detect this specific case. The fact is, even GitHub's CODEOWNERS verification (which only verifies owners on source path/owner lines) flags owners as invalid if their membership to Azure is private, …

Update the team/user store to store additional information to be used in the upcoming CODEOWNERS linter

---

tools/secret-management/Azure.Sdk.Tools.AccessManagement/Azure.Sdk.Tools.AccessManagement.csproj
tools/secret-management/Directory.Build.props

Reverts Azure/azure-sdk-tools#6854
This didn't solve our problem, so we're going to go with an internal skip instead. Removing the strong name lib dependency in favor of the old NoWarn approach.

Revert "Strong name sign Sodium.Core in secret library"

---

eng/common/TestResources/SubConfig-Helpers.ps1
eng/common/TestResources/build-test-resource-config.yml

We've run into this a couple times as teams migrate away from hardcoded keyvault secrets but have duplicates in the yaml, causing hard to find issues when updating values in the wrong place. The identity team, for example, has some of their core variables in our base config (which should be moved).
I'm going to update the language test pipelines to pass down `EnvVars` from the tests/ci.yml files just to fail fast on any conflicts.

Fail fast on variable conflicts with subscription config

---

eng/common/pipelines/templates/steps/docsms-ensure-validation.yml

This fixes an issue discovered [in the spring pipelines for which no docs are published](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3034028&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=27412920-1ce6-5c15-b5b0-3baeb5d8a8ba&s=cc1c0c38-0f79-5da2-c09f-847e3abdf9ce). In that case, the Update-DocsMsMetadata.ps1 script [does not run](https://github.com/Azure/azure-sdk-for-java/blob/djurek/ignore-undocumentable-packages/eng/common/pipelines/templates/steps/update-docsms-metadata.yml#L36-L39) which means the `DocsMsPackagesAllValid` is not set. 
A couple of fixes are possible: 
1. Only check for valid docs if `DocsMsPackagesAllValid` variable is set
1. Ensure that `DocsMsPackagesAllValid` variable is always set by setting it in some prior step (drawbacks here include the …

Check for DocsMsPackagesAllValid before running validation step

---

eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1

Epic type is not set when prepare release script creates a work item for a new service or product. This change is to set epic type as service or product so it aligns with new dashboard changes for service and product work items.

Create Epic work item type as Service or product

---

tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ApiViewMessage.cpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ApiViewMessage.hpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstNode.cpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ProcessorImpl.cpp
tools/apiview/parsers/cpp-api-parser/ParseTests/CMakeLists.txt
tools/apiview/parsers/cpp-api-parser/ParseTests/TestCases/DestructorTests.cpp
tools/apiview/parsers/cpp-api-parser/ParseTests/tests.cpp

- Fixed issue creating ApiView for azure core
- Added output for override and final attributes
- Added diagnostics for the following cases:
- [destructors that aren't virtual](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c35-a-base-class-destructor-should-be-either-public-and-virtual-or-protected-and-non-virtual).
- method overrides without the override keyword.

Fixed several ApiView parser issues.

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs

This is an attempt at resolving Azure/azure-sdk-for-java#36669
I saw the following in a failed startPlayback request:
@samvaity FYI
```
[19:41:40] dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[9]
Connection id "0HMTFR2OL71BA" completed keep alive response.
[19:41:40] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
Request finished HTTP/1.1 POST http://localhost:5000/v2.1/track - 342 - 500 - application/json 5299.1726ms
[19:41:40] dbug: Microsoft.AspNetCore.Server.Kestrel.BadRequests[17]
Connection id "0HMTFR2OL71BA" bad request data: "Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate."
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See …
```

Allowing a bit more of a grace period on slow requests

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

Resolves Azure/azure-sdk-for-java#36669 and Azure/azure-sdk-for-java#36655
Here's the conflict.
When the proxy finishes restoring a test in playback, it updates a local ConcurrentDictionary with the checkout status. When that is matching what we expect, it exits early and returns.
> we're at where we need to be. no work to be done.
The problem is that in some circumstances with the `azure-resourcemanager-compute` tests all invoking in parallel. We're ending up in the situation where multiple tests are all starting at the same time. This is due to the fact that all of these are not yet "cached", so they all have to invoke the "fetch and clean" operation _additionally_. This additional operation is what is causing our timeouts in some cases.
We can avoid this by forcing the _entire_ …

Force entire `Restore` operation to enqueued

---

tools/stress-cluster/cluster/azure/cluster/cluster.bicep

This enables AKS node upgrades for security patches in stress clusters, and specifies a time window (early Mondays) for them to happen.

[stress] Add maintenance window and enable node security upgrades

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs

We should never have an issue with multiple startPlayback for the same assets.json, which would apply here.

Global `Restore` queue -> per asset restore

---

eng/common/scripts/Update-DocsMsMetadata.ps1

When merging the releasing metadata JSON properties with the existing metadata JSON, the `Update-DocsMsMetadata.ps1` script calls `ConvertTo-Json` without specifying `-Depth`. The result is a string serialization at depths greater than 2 which results in unintended docs build configurations: 
Example:
The metadata pushed into the docs repo from [this build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3065250&view=logs&j=18993cac-9748-5722-f1d8-b9d5549e160d&t=24de96b9-eee4-58d6-0b41-e984f23dd609&l=53) 
Included [this change](https://github.com/MicrosoftDocs/azure-docs-sdk-python/commit/38fa6e430d0ba7e281a6b11fac3ea5197c323f84#diff-04f3acc8bc7d0652741c709defc1638f060237e93cad50b70b6c41caabf9438cL14-L17).

Serialize with depth

---

eng/common/scripts/stress-testing/deploy-stress-tests.ps1
eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
tools/stress-cluster/chaos/README.md
tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Chart.lock
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Chart.yaml
tools/stress-cluster/chaos/examples/parallel-pod-example/Chart.lock
tools/stress-cluster/chaos/examples/parallel-pod-example/Chart.yaml
tools/stress-cluster/chaos/examples/parallel-pod-example/scenarios-matrix.yaml
tools/stress-cluster/chaos/examples/parallel-pod-example/templates/parallel-pod.yaml
tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_pod_disruption_budget.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl

This adds a parameter `LockDeletionForDays` to the stress deploy script, which will prevent a test and all its pods from being killed for a time period by the kubernetes api server. Possible reasons a pod may be killed:
1. Node rebalancing/scale down
2. Node security patch updates
3. Misc. node evictions and scheduler based pod deletions
It also creates a cron job resource set to delete the pod disruption budget after `LockDeletionForDays` days, so that evictions can then occur (meaning the test pods won't necessarily be killed, but they will no longer be locked).
This updates the parallel jobs feature to use the matrix config instead of a separate addons template. This is both more intuitive and allows for setting different parallel values per scenario (rather than per test).

[stress] Add LockDeletionForDays parameter to set PodDisruptionBudget and cleanup job

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/LoggingTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs

Just ensure that the unmatched key is quite clear to the user.
@srnagar

Update Error for Sanitizer Add

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0017Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0018Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0019Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Descriptors.cs

Overall, the logic is:
Regen PR: https://github.com/Azure/azure-sdk-for-net/pull/38603

Add rules for convenience method and protocol method

---

tools/github/data/common-labels.csv

Addresses https://github.com/Azure/azure-sdk-for-net/pull/38974#pullrequestreview-1645065266
These labels have already been removed from the public repos for .NET, Java, JS, Python, Go, and C++.

Remove unused Monitor labels from CSV

---

eng/pipelines/githubio-linkcheck.yml

- Pipeline normally runs in 3 hours, so 6 hours is plenty of time
- We should not use infinite timeouts, to avoid blocking build agents indefinitely

[githubio-linkcheck] Reduce timeout from infinite to 6 hours

---

eng/pipelines/live-test-cleanup.yml

- Pipeline normally runs in 15 minutes, so 60 minutes is plenty of time
- We should not use infinite timeouts, to avoid blocking build agents indefinitely

[live-test-cleanup] Reduce timeout from infinite to default (60 minutes)

---

.github/workflows/event-processor.yml
.github/workflows/scheduled-event-processor.yml
tools/github-event-processor/YmlAndConfigFiles/event-processor.yml
tools/github-event-processor/YmlAndConfigFiles/scheduled-event-processor.yml

The focus of these changes is to update the version of the package used by Actions to deploy the changes recently made to remove the "CXP Attention" rule and tweak the "needs-team-triage" criteria to ignore issues with an assignment already made.

[JimBot] Update package version in use

---

eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml

Fixes https://github.com/Azure/azure-sdk-tools/issues/5882
We need to set the difffilter to empty instead of the default of exclude deleted files when we are trying to verify there are no changes under eng/common.
See test PR https://github.com/Azure/azure-sdk-for-python/pull/32348 which demonstrates us not detecting a deleted file under eng/common. I'll use that same test PR to verify this now catches that issue.

Detect all file diff types for eng/common changes

---

tools/tsp-client/.gitignore
tools/tsp-client/.prettierrc.json
tools/tsp-client/README.md
tools/tsp-client/cmd/tsp-client.js
tools/tsp-client/package.json
tools/tsp-client/src/fileTree.ts
tools/tsp-client/src/fs.ts
tools/tsp-client/src/git.ts
tools/tsp-client/src/index.ts
tools/tsp-client/src/languageSettings.ts
tools/tsp-client/src/log.ts
tools/tsp-client/src/network.ts
tools/tsp-client/src/npm.ts
tools/tsp-client/src/options.ts
tools/tsp-client/src/typespec.ts
tools/tsp-client/test/fileTree.spec.ts
tools/tsp-client/test/network.spec.ts
tools/tsp-client/tsconfig.json

Per Issue #6838, this PR scaffolds out a new tool to invoke the TypeSpec compiler using Node/npm.
The largest enhancement is avoiding the need to clone the specs repository as URLs are supported as entrypoints rather than requiring the TSP files all be locally available.
Eventually this tool will grow to support all of the scenarios covered in https://github.com/Azure/azure-sdk-tools/blob/main/doc/common/TypeSpec-Project-Scripts.md

Create tool tsp-client

---

tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Constants/RulesConstants.cs

The CXPAttention rule and processing was removed from github-event-processor and the event-processor.config files but the rules constant was still there. Nothing bad happens, or will happen, but the logic that detects missing rules from the config file outputs the following informational message whenever it loads a config file. 
`CXPAttention was not in the rules config file. Missing rules default to Off.`
Since the rule, itself, is gone, the rules constant needs to go away as well.

Remove CXPAttention rules constant

---

eng/pipelines/templates/stages/archetype-autorest-preview.yml
eng/scripts/autorest/New-EmitterPackageJson.ps1
eng/scripts/autorest/New-EmitterPackageLock.ps1

Stop using internal feed for npmrc and instead use URL based version overrides

Allow overrides when creating emitter package json

---

tools/pylint-extensions/azure-pylint-guidelines-checker/CHANGELOG.md
tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py

Ignore mgmt-core for no legacy import check -- when bumping versions will bump version universal and disable the needed checkers so that this fix goes through

[Pylint] Add bug fix for mgmt-core 

---

.github/workflows/event-processor.yml
.github/workflows/scheduled-event-processor.yml

github-event-processor was recently updated to remove the CXPAttention rule but the Rules constant was left in the code.  The constant was removed with this [PR](https://github.com/Azure/azure-sdk-tools/pull/7092) which, after merging, runs the pipeline and publishes the tool to the NET dev feed. This PR simply updates the version being installed and will push the changes out to the other repositories.

Update github-event-processor version to 1.0.0-dev.20231010.2

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Net.cs

- Also update Azure.Core.TestFramework to ensure consistent versions
- If reference is missing, ignore instead of throwing
- Required when updating multiple projects which may not contain all references

[Perf Automation] Improve .NET package version update logic

---

eng/common/pipelines/templates/steps/sparse-checkout.yml

This will use the repository name in the step display name for single repo sparse checkouts:

Use better description for single repo sparse checkout

---

eng/common/TestResources/New-TestResources.ps1
eng/scripts/Remove-WormStorageAccounts.ps1
eng/scripts/live-test-resource-cleanup.ps1

- Resilient blob deletion handling
- Remove ARM deployment after deploy

Remove ARM deployment in test resources

---

tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ApiViewMessage.cpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ApiViewMessage.hpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ApiViewProcessor.hpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstDumper.cpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstDumper.hpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstNode.cpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstNode.hpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/CMakeLists.txt
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/CommentExtractor.cpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/CommentExtractor.hpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/JsonDumper.hpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ProcessorImpl.cpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ProcessorImpl.hpp
tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/TextDumper.hpp
tools/apiview/parsers/cpp-api-parser/ParseTests/CMakeLists.txt
tools/apiview/parsers/cpp-api-parser/ParseTests/TestCases/DocumentationTests.cpp
tools/apiview/parsers/cpp-api-parser/ParseTests/tests.cpp
tools/apiview/parsers/cpp-api-parser/README.md

This PR implements 3 new features to the C++ API View tool.
1. Enable comments in API Views.
2. Add a line to each type describing where the type is located in the source tree
3. Flag typedefs in the global namespace as being challenging. This raises the visibility of using types like uint8_t in the global namespace.

Added doxygen comment support to C++ API Reviews.

---

eng/pipelines/templates/variables/globals.yml

Update the tools versions of pipeline-owners-extractor and notification-configuration to use the published versions that now use CodeownersUtils.

Update tools versions for CodeownersUtils

---

eng/pipelines/live-test-cleanup.yml

We are seeing pipeline timeouts and getting email spam due to resource group build-up and deletion prevention in dogfood. Temporarily disabling cleanup to get things green again.

Temporarily disable ACS dogfood cleanup

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/LoggingTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/DebugLogger.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs

Specific start and stop actions are now `LogTraced`.

Add Additional Logging to Startup/Stop

---

tools/js-sdk-release-tools/package.json
tools/js-sdk-release-tools/src/utils/git.ts

fixes the failure https://github.com/Azure/azure-rest-api-specs/pull/26146/checks?check_run_id=18103044311
```
cmderr	[automation_generate.sh] [ERROR] Error:
cmderr	[automation_generate.sh] [ERROR] An error occurred while run build for typespec project: "specification/cognitiveservices/Vision.ImageAnalysis":
cmderr	[automation_generate.sh] [ERROR] Err: Error: Find unexpected generated file: sdk/vision/imageAnalysis/src/ImageAnalysisClient.ts. Please confirm whether the output-folder is correct.
cmderr	[automation_generate.sh] [ERROR] Stderr: "undefined"
cmderr	[automation_generate.sh] [ERROR] Stdout: "undefined"
cmderr	[automation_generate.sh] [ERROR] ErrorStack: "Error: Find unexpected generated file: sdk/vision/imageAnalysis/src/ImageAnalysisClient.ts. Please confirm whether the …
```

Disable folder check

---

src/dotnet/APIView/APIView/APIView.csproj
src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs

APIView search without any filters is taking around 6-7 seconds to find the records due to search against revision properties.
This change is to improve search performance to few milli seconds when searching without any filters by checking against review properties only.
Search query cost is reduced to 30 RUs from 2800 RUs and response time is few ms instead of 6 seconds with this change.

Reduce APIView search query cost when searching without filters

---

eng/common/scripts/Save-Package-Properties.ps1

On `python` `pypy39` platform, this script runs into a [weird problem.](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3209852&view=logs&j=8e5196d1-9c2a-56bb-41fd-e329e85c48fa&t=6cc1318c-0278-53f9-9f83-99109e387aaa)
The linked build isolates the error, along with a bunch of debug output showing where stuff is going wrong.
On this `pypy39` platform image, we are getting 2 _extra_ "blank" pkg props. That looks like this for the template project:
Here's the thing, these are _magically_ showing up. In the same build that produces this error for review, you can see clearly that the _actual_ `Language-Settings.ps1` function that is retrieving the package list, is **getting the correct list**. It just magically gets another two blank objects. I'm almost positive that we're …

Empty package models don't throw error

---

src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
tools/apiview/parsers/js-api-parser/export.ts
tools/apiview/parsers/js-api-parser/package.json

JS API review is not showing Enum members and this causes insufficient diff even when public level Enums are changed. This PR also has the change to upgrade all existing JS reviews.
Thanks and regards,
Praveen

Show enum members in JS API review

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/OptionsGenerator.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/StartOptions.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs

Addressing #7190 in a different way. Going to enable this new version of the proxy, then adjust `test-proxy-tool` to run with this new flag.
This is much much less hacky than just uploading the `stderr` output as a different file, and allows the proxy log to show up in a useful format, where errors are right next to the `info` logs that they are correlated with.

Add option to allow single-log output for test-proxy

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
tools/test-proxy/scripts/test-scripts/CLIIntegration.Tests.ps1

Resolves #6664  
For the most part, users are entirely self-service on the test-proxy, except for one common situation. This one:
1. User is onboarding to proxy for the first time
2. User records new recordings successfully
3. User attempts to `push` the new recordings. They fail with 403. They join the appropriate group.
4. User re-attempts `push`. `Push` silently just does nothing.
The origin of this is because we only `push` when there uncommitted changes _to be pushed_. There's nothing handling when a push fails.
By resetting the changes, users are unblocked from this common scenario, and a re-entry to the `push` function will act as if the failed push never happened. 
~~TODO:~~

Adding automatic reset on failed push

---

tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter/Azure.Sdk.Tools.CodeownersLinter.csproj

The CodeownersLinter project, part of the CodeownersUtils solution, didn't have PackAsTool set to true which means that it published the executable which wasn't all inclusive and lacked the CodeownersUtils library inclusion. Because of this, trying to install CodeownersLinter was failing because it couldn't find Azure.Sdk.Tools.CodeownersUtils which shouldn't be being published.

Fix Linter tool publish

---

.github/CODEOWNERS_baseline_errors.txt
eng/common/pipelines/codeowners-linter.yml

**codeowners-linter.yml** is going to be the pipeline yml file that'll run the linter. This is a unique pipeline in that it's the only yml file in eng/common that is a fully contained pipeline instead of a template that's included in other pipelines. This needs to be in common because, like github-actions, it needs to set the version of the CodeownersLinter to install in a common place that gets pushed out to the other repositories. 
Because the trigger is set to none, this shouldn't get picked up by pipeline generation which is we want. Once this is pushed out to the other repositories I'll need to do the following:
1. Create their baseline files and get those checked in.
2. Create the pipeline for that repository. The pipeline will run daily and the triggers are setup to run when there …

Add CODEOWNERS linter yml file to eng/common/pipelines

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/ModelName/AZC0030OptionsTest.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs

- change `GeneralSuffixAnalyzer` to ignore model classes with `Options` suffix if there is no serialization code
- Property bag model classes do not have any serialization code
- add test cases
fix #7247

fix(.net analyzer): ignore property bag with `Options` suffix

---

src/dotnet/APIView/APIView/Model/CodeFile.cs
src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
src/dotnet/APIView/APIViewWeb/Models/ReviewCodeFileModel.cs

Parser needs a property in CodeFile to send package version to APIView so each revision can be tagged with a package version.

Add new property in CodeFile model to get package version from parser

---

eng/pipelines/templates/stages/archetype-autorest-preview.yml

Replace the short script names with:
Initialize-Repository.ps1
Build-Packages.ps1
Test-Packages.ps1

Use better script names for init, build and test

---

eng/common/pipelines/codeowners-linter.yml

@benbp and I chatted briefly after standup. The linter needs the full repository but not the full history. azure-sdk-for-net's clone was taking 4 1/2-6 minutes because it was grabbing the history which we don't need. Flipping over to a shallow clone dropped the clone time down to 1m 1s. I'd grabbed the build definition check directly from net's [ci.tests.yml ](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/pipelines/templates/jobs/ci.tests.yml#L43) since that could eventually be a gotcha.

Use sparse-checkout to do a faster, shallow clone

---

tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Azure.Sdk.Tools.GitHubEventProcessor.Tests.csproj
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/MockGitHubEventClient.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/IssueProcessingTests.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Tests.FakeCodeowners/InitialIssueTriage_CODEOWNERS
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Tests.JsonEventPayloads/ServiceAttention_issue_labeled_already_has_ServiceAttention.json
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Azure.Sdk.Tools.GitHubEventProcessor.csproj
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/IssueProcessing.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Utils/CodeOwnerUtils.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Utils/LabelUtils.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Utils/RulesConfiguration.cs
tools/github-event-processor/GitHubEventProcessor.sln
tools/github-event-processor/RULES.md

The following updates have been made in this PR.
1. The primary change was to swap out the old CodeownersParser for the CodeownersUtils which will parse the new moniker, AzureSdkOwners, from CODEOWNERS files. 
2. With the updated parsing the InitialIssueTriage rule has been rewritten, updated to definition provided by @jsquire. The exact rule's processing can be found in the updated Rules.md file which part of this PR. Fixes #5743 
4. The ServiceAttention rule now checks every label added. If ServiceAttention is already on the Issue and a service label is added it'll perform the rule's actions. Fixes #6480 
5. The rate limit API call now has retries. Because this is called at the start/end of processing, there is no backoff and the time in between attempts is 200ms, for a total wait time …

Updates to github-event-processor

---

tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/IssueProcessingTests.cs
tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/IssueProcessing.cs

@jsquire wanted the InitialIssueTriage's rule temporarily reverted until the CODEOWNERS files have metadata to support the new rule. 
Everything new is commented out and the old rule's processing was re-enabled. This means that if the AI Label Service suggests labels, we add them and then add NeedsTeamTriage, otherwise we add NeedsTriage.
The original rule's code can be viewed [here](https://github.com/Azure/azure-sdk-tools/blob/370f3dfd9272275ce0022b4e1b255c4c5a266640/tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/IssueProcessing.cs#L89)

Disable updated InitialIssueTriage rule until CODEOWNERS files have new/updated/correct metadata

---

eng/common/pipelines/codeowners-linter.yml

There are two changes here:
1. Set the working directory. - dotnet tools install, on non-windows platforms, will fail if detects any other project in the working directory. Set the working directory to $(Build.SourcesDirectory)/eng/common which doesn't, and shouldn't, contain proj files.
2. Set nugetMultiFeedWarnLevel: 'none' so the Secure Supply Chain Analysys will pass when running in azure-sdk-for-net. While I believe this only matters for azure-sdk-for-net, it isn't going to hurt to have set for everything. I could just set the variable on the pipeline but this makes it more discoverable and obvious. Unfortunately, there's no actual way to disable this completely as the checks do not matter in the least to this pipeline.

Set WorkingDirectory so the dotnet tools install works on non-windows

---

.github/workflows/event-processor.yml
.github/workflows/scheduled-event-processor.yml

Update the version of GitHubEventProcessor so it uses the new CodeownersUtils to parse CODEOWNERS files. This is an interim change before updating the new InitialIssueTriage rule which requires metadata that isn't in the CODEOWNERS files yet.

Update GitHubEventProcessor to 1.0.0-dev.20231114.3

---

.gitignore
tools/tsp-client/ci.yml
tools/tsp-client/package-lock.json
tools/tsp-client/package.json

tsp-client should use `npm ci` in its CI pipeline to allow for deterministic builds.  For that, we need to:
- update the pipeline yaml to use 
- stop ignoring *-lock.json files in .gitignore
- pin the floating @typespec/compiler peer dependency in devDependencies
- add tsp-client's package-lock.json to the repository

Add package-lock.json for tsp-client

---

tools/tsp-client/package-lock.json
tools/tsp-client/package.json
tools/tsp-client/src/options.ts

tsp-client prompts the user for output directory confirmation.  In noninteractive sessions like CI builds, this causes an error like `ENXIO: no such device or address, open '/dev/tty'`.  This change only prompts for confirmation if the stdin stream is connected to a TTY context (has a user with a keyboard that can answer the prompt).

Allow tsp-client to be run in non-interactive sessions

---

packages/python-packages/apiview-stub-generator/CHANGELOG.md
packages/python-packages/apiview-stub-generator/apistub/_apiview.py
packages/python-packages/apiview-stub-generator/apistub/_metadata_map.py
packages/python-packages/apiview-stub-generator/apistub/_stub_generator.py
packages/python-packages/apiview-stub-generator/apistub/_version.py
packages/python-packages/apiview-stub-generator/apistub/nodes/_class_node.py
packages/python-packages/apiview-stub-generator/apistub/nodes/_function_node.py
tools/apiview/emitters/typespec-apiview/package.json
tools/apiview/emitters/typespec-apiview/src/apiview.ts
tools/apiview/emitters/typespec-apiview/src/emitter.ts
tools/apiview/emitters/typespec-apiview/src/lib.ts
tools/apiview/emitters/typespec-apiview/src/version.ts
tools/apiview/emitters/typespec-apiview/test/apiview.test.ts
tools/stress-cluster/services/Stress.Watcher/Dockerfile

**TypeSpec:** Also adds support for unnamed unions and the valueof keyword.
**Python:** Updates the default file to `apiview_mapping_python.json` so as not to conflict with other languages.

[APIView] Add support for CrossLanguageDefinitionIds

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0002Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0006Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0018Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAnalyzerBase.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientConstructorAnalyzer.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs

Fix https://github.com/Azure/autorest.csharp/issues/3710
Root cause: https://github.com/Azure/autorest.csharp/issues/3710#issuecomment-1707840791
Quote here:
> The get sub client method returns the sub client called `Operation`, which is a criterion of a service method in analyzer
> ```C#
> public virtual Operation GetOperationClient(string apiVersion = "1.0.0")
> {
>     Argument.AssertNotNull(apiVersion, nameof(apiVersion));
> 
>     return new Operation(ClientDiagnostics, _pipeline, _endpoint, apiVersion);
> }
> ```
Solution: When checking whether a method is a service method, not just checking the type name, but also checking the namespace name.
Fix https://github.com/Azure/autorest.csharp/issues/3708
Root cause: https://github.com/Azure/autorest.csharp/issues/3708#issuecomment-1788716 …

Fix analyzer issues

---

.github/CODEOWNERS
tools/codeowners-utils/METADATA.md
tools/codeowners-utils/README.md

When this is merged, I'm going to create an aka.ms link to the `## Linter errors and how to deal with them` section and add this to the output of the linter if errors are reported.

Codeowners-Utils README update to add a section for dealing with linter errors.

---

tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter/Program.cs

When the linter runs and encounters errors, after the errors are output, add one additional line which contains the aka.ms link on how to handle them. The exact line is:
`There were linter errors. Please visit https://aka.ms/azsdk/codeownersLinterErrors for guidance on how to handle them.`
There was one more piece I added. If there's a baseline file for the repository and no linter errors, it'll print a warning. If CODEOWNERS has been cleaned up to the point where there's no linting errors then there shouldn't be a baseline file.

Add newly created aka.ms link for guidance on dealing with linter errors

---

eng/common/pipelines/codeowners-linter.yml

The CodeownersLinter had two minor updates:
1. Added an AKA link into the output, when there's errors, that links to the [Linter errors and how to deal with them](https://github.com/Azure/azure-sdk-tools/blob/main/tools/codeowners-utils/README.md#linter-errors-and-how-to-deal-with-them) section of the tool's README doc.
2. If there's a CODEOWNERS baseline file, but no linting errors, it'll output a warning indicating that if the errors have been fixed that the file should be deleted.

Update CodeownersLinter to 1.0.0-dev.20231120.3

---

tools/secret-management/ci.yml

This tool contains native binaries that cause symbol publishing to fail so disable the symbols for this tool package
I've tried to update the symbol publishing tool but it doesn't like the native 3rd party *.so files and the symbols for our internal tools aren't that interesting so just disabling the publishing for this tool.

Disable symbol publishing for tool

---

eng/pipelines/devops-create-package-workitem.yml

Update pipeline parameters so it can be triggered from powerapps. Pipeline cannot be executed from powerapps without setting a default value from one of the options. Also, parameter values supplied to DevOps request is processed as run time variables, not parameters.

Remove default value for pipeline picklist params

---

tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/CHANGELOG
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerAPIViewGenerator.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/CodeFile.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewRoot.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewSpec.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/SwaggerAPIViewTest.cs

Changes to include API-version in API review code file for Swagger API review. Package version is consumed by API review to generate revision label.

Swagger API review parser changes to add package version in code file

---

eng/common/scripts/Verify-Links.ps1

Http Status code 401 just means unauthorized and not necessarily that the link isn't valid. Removing this from the list of codes to error from.

Lets not treat https code 401 as broken link

---

src/dotnet/APIView/APIViewUnitTests/APIRevisionsManagerTests.cs
src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
src/dotnet/APIView/APIViewWeb/Controllers/ReviewController.cs
src/dotnet/APIView/APIViewWeb/Helpers/PageModelHelpers.cs
src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewsPartial.cshtml

- Add APIRevisionsManager Tests
- Some rename of `revisionId` to `apiRevisionId`.
- Prevent Diffing between the exact same apiRevision
- Remove approve filter and checkmark on review page.
- Only allow approval when activeRevision is ahead (created after) diffRevision

Resolve APIView Issues Identified during Manual Testing

---

src/dotnet/APIView/APIViewIntegrationTests/ReviewManagerTests.cs
src/dotnet/APIView/APIViewIntegrationTests/TestsBaseFixture.cs
src/dotnet/APIView/APIViewWeb/Helpers/PageModelHelpers.cs
src/dotnet/APIView/APIViewWeb/LeanModels/ReviewRevisionPageModels.cs
src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs
src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
src/dotnet/APIView/APIViewWeb/Managers/Interfaces/ICodeFileManager.cs
src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IPullRequestManager.cs
src/dotnet/APIView/APIViewWeb/Managers/PullRequestManager.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/ICosmosPullRequestsRepository.cs
src/dotnet/APIView/apiview.yml

- Adds logic to properly handle page errors due to invalid review / apiRevision Id, or empty diff.
- Adds logic for creating manual reviews.
- Correct manual review `createdBy` field so it dies not default to review creator.
- Make Associated Reviews and Associated PullRequests dependent on APIRevisionId
- Hide the close Button

Re architect/review revision restructure

---

src/dotnet/APIView/APIViewWeb/README.md

Removing user facing information from here that will live now in Eng Hub. (PR https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/875)
For remaining tool information I have updated the review/revision concept for consistency with latest changes

Update APIView documentation

---

tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/BuildCompleteQueueWorker.cs

Right now, we only log that we're processing **a** build.complete event, not the actual event itself.
This update can be almost thoughtlessly deployed.

Pipeline Witness logs trigger event

---

src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs

1. Fix null pointer exception when baseline is not present in PR api change detection request
2. Prefer package name in CodeFile when it's present
3. Null check when comparing code file

Prefer PackageName in Code file to find existing PR reviews

---

eng/pipelines/agent-software-inventory.yml
eng/pipelines/inventory.yml

- Add inventory pipeline for PS modules
- Fix pipeline
- Try again
- Show `dotnet --info`
- Add custom agents as well
- Update inventory scripts
- Remove maxParallel

Add inventory pipeline to inventory software on machines we use for builds

---

tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/multipart_header.json
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/HeaderRegexSanitizer.cs
tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/HeaderStringSanitizer.cs

This was discovered by @mssfang , @billwert , and @samvaity . Example of failure:
```json
"headers": {
"Cookie": [
"val1",
"val2"
]
}
```
We weren't sanitizing val2 in the above construct.
This PR fixes that.

Ensure `HeaderSanitizer`s apply to list-value headers

---

src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
src/dotnet/APIView/APIViewWeb/Repositories/BlobCodeFileRepository.cs

Disable code file caching when computing swagger diff. Also reduce cache time to 10 minutes.

Avoid caching code file when running background task

---

eng/pipelines/templates/steps/sync-repo-branch.yml
eng/pipelines/templates/steps/sync-repo-merge-branch.yml
eng/scripts/Merge-Branch.ps1

- Enable continueonerror for our mirroring steps so one bad repo doesn't stop the others from mirroring
- React to recent change to git cli https://github.com/git/git/commit/54f98fee5069f50c6e96687504b82a7695c8648a Instead of passing --theirs we can get away with --ignore-unmerged given we are trying to avoid any merge conflicts at all and want to simply pick and choose which files we want to include from which branches

Enable continue on error for our mirror steps

---

tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/CHANGELOG
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerAPIViewGenerator.cs
tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj

Swagger file refers to a definition in another swagger file and sometimes this definition in second swagger file might have a schema reference to another definition within same file and this reference will be a local reference. API review parser incorrectly searches for this local reference in first swagger file instead of second file where it's defined.
PR has the fix to correctly refer the swagger file based on the parent reference if current reference path is local.
For e.g. data.json has a reference to 202response definition which is in common.json and 202response has a reference to longrunningoperationresult schema using local reference `#LongRunningOperationResult` and it's defined in common.json. We need to make sure parser refers common.json when processing …

Process swagger file cross reference when generating API review

---

src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Samples.cshtml
src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Samples.cshtml.cs

1. Samples page model is not set correctly and that causes issue to load samples.
2. Selecting a different revision throws error since it's compared against wrong samples revision property.

Set Samples page model and use correct property to find active revision

---

tools/pylint-extensions/azure-pylint-guidelines-checker/dev_requirements.txt
tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
tools/pylint-extensions/azure-pylint-guidelines-checker/setup.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/__init__.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/api_version_checker_acceptable_class.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/api_version_checker_acceptable_init.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/api_version_checker_violation.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/copyright_header_acceptable.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/copyright_header_violation.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/core_paging_acceptable.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/core_paging_acceptable_and_violation.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/core_paging_violation.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/enum_checker_acceptable.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_files/enum_checker_violation.py
tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_pylint_custom_plugins.py

Ran black
Fixed pylint 3.0 breaking changes (node.doc = node.node_doc, infer_call_result on FunctionDef takes a caller positional arg)

[pylint] Bump 3.0 checker

---

src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs

Handle null pointer exception to avoid invalid exceptions when processing automatic API reviews. Too many exceptions logged in app insights, makes the monitoring difficult.

Fix automatic review exception

---

src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs

Spec review pipeline gets failure status if a PR generates more than one API review. FIx is to get the review ID from pull request model that already has the info.

Return correct URL when processing API review from spec

---

tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Program.cs

When an error happens, fault-injector happily returns 200 with 0 content length pretending that things are good.
It complicates things on the SDK side and we'd prefer it to fail which is implemented in this change.
Also, it adds cancellation tokens to indefinite timeouts.

Fault injector: don't return 200 when error happens

---

tools/tsp-client/CHANGELOG.md
tools/tsp-client/src/index.ts
tools/tsp-client/src/typespec.ts

Use functions provided by `@typespec/compiler` to resolve emitter options and paths passed into the `compile()` call. 
Issues to be addressed in a follow up PR: #7124 , https://github.com/Azure/azure-sdk-tools/issues/7472 <-- will do a wider pass through all of the path operations we do in the tool and update to using the functions provided by typespec/compiler

[tsp-client] Fix typespec compiler usage

---

eng/pipelines/live-test-cleanup.yml

The environment is currently broken and we aren't even running tests currently see https://github.com/Azure/azure-sdk-for-python/pull/33483. Disabling this to reduce noise until that is fixed.

Disable translation sub cleanup

---

eng/pipelines/templates/stages/archetype-autorest-preview.yml

To prevent nightly autorest/typespec preview pipelines from creating a new draft PRs on every run, we want to reuse the branch and PR.
For this to work, we need to use a static PR title and force push when initializing the source branch to remove any changes from a previous scheduled run.

Scheduled autorest preview builds should reuse the branch and pr

---

eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1

When multiple docker files are used, one `imageTag` value was incorrectly applied to all images
Before:
```yaml
scenarios:
- testScenario: httpget
image: dockerfiles/java11
imageBuildDir: ..\..\..\
.....
- testScenario: httpget
image: dockerfiles/java21
imageBuildDir: ..\..\..\
```
resulted in followoing generated values
```yaml
scenarios:
- testScenario: httpget
image: dockerfiles/java11
imageBuildDir: ..\..\..\
Scenario: default11get
imageTag: stresspgs7b6dif73rup6.azurecr.io/limolkova/java-template2/java21:limolkova
- testScenario: httpget
image: dockerfiles/java21
imageBuildDir: ..\..\..\
Scenario: default21get
imageTag: stresspgs7b6dif73rup6.azurecr.io/limolkova/java-template2/java21:limolkova
```
Now proper `imageTag` is generated

Stress tests: Fix image tag for multiimage deployments

---

eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
eng/common/scripts/create-tags-and-git-release.ps1

By default we recursively discover packages in our release scripts. This is causing issues in the go repo where some packages have packages nested but that are represented in separate pipelines, namely `azidentity`. This PR adds a `-NoRecurse` option to the scripts and pipeline templates which changes our search depth to the artifact location only.
```
<package>/
go.mod
ci.yml
CHANGELOG.md
<sub package>/
go.mod
ci.yml
CHANGELOG.md
```
Resolves https://github.com/Azure/azure-sdk-for-go/issues/21737

Add package filter parameter for release

---

src/go/cmd/api_view_test.go
src/go/cmd/module.go
src/go/cmd/testdata/test_multi_module/A/B/go.mod
src/go/cmd/testdata/test_multi_module/A/B/test.go
src/go/cmd/testdata/test_multi_module/A/go.mod
src/go/cmd/testdata/test_multi_module/A/test.go
src/go/cmd/testdata/test_multi_module/go.mod
src/go/cmd/testdata/test_multi_module/test.go

A directory containing a go.mod is a module, even when below another directory containing a go.mod. For example:
```
Foo
├── Bar
│   └── go.mod
└── go.mod
```
Foo and Bar are separate modules--nothing in Bar is accessible through Foo--so when indexing Foo, apiviewgo mustn't include anything from Bar. This PR ensures it doesn't by having apiviewgo skip any subdirectory of the module it's indexing that contains a go.mod. Fixes #7520

apiviewgo skips nested modules

---

eng/common/scripts/Verify-RestApiSpecLocation.ps1

Fixed the variable name in an output message.

Correct the variable name in spec location validation script

---

eng/pipelines/mirror-container-images.yml
eng/scripts/mirror-container-image.ps1

This will help keep mirrored images up to date with vulnerability scans.

Apply optional changes to mirrored image

---

eng/common/scripts/artifact-metadata-parsing.ps1
eng/common/scripts/create-tags-and-git-release.ps1

VerifyPackages will also fail out in various scenarios, so moving the package filter into this function that generates the package list, instead of at the CreateRelease scope

Filter packages at verify step

---

eng/common/scripts/Generate-PR-Diff.ps1

Using `git-helpers` `Get-ChangedFiles`
Resolves #7504 
This will be used as the first step of a common build pipeline which we will add to all our repos.

Add script which generates a changeset for pipelinev3

---

tools/stress-cluster/cluster/kubernetes/stress-infrastructure/values.yaml

This makes it easier to bounce the containers and pull in newly published images with up to date packages.

Always pull chaos images

---

.gitignore
eng/common/scripts/Helpers/git-helpers.ps1
eng/common/scripts/Helpers/git-helpers.tests.ps1
eng/common/testproxy/onboarding/common-asset-functions.ps1
eng/common/testproxy/scripts/resolve-asset-conflict/README.md
eng/common/testproxy/scripts/resolve-asset-conflict/resolve-asset-conflict.ps1
eng/common/testproxy/scripts/tag-merge/README.md
eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1

auto-merge conflicted assets.json

---

eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
tools/stress-cluster/chaos/README.md
tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Chart.lock
tools/stress-cluster/chaos/examples/parallel-pod-example/Chart.lock
tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_container_env.tpl
tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl

Fixes #7521 #4644. See README.md diff in PR for details.
FYI @lmolkova @richardpark-msft

Add git commit details to stress environment

---

tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/JavaScript.cs

In the recent updates to the JS repository, "build caching for @microsoft/rush" step has been introduced, to expedite the build process, thereby enhancing build efficiency.
However, an unforeseen complication has arisen due to this update. The “build caching” mechanism appears to be incompatible with the sparse checkout procedure that is currently employed in our automation workflow for the perf pipelines.
To mitigate this issue, in this PR, adding a snippet to delete the "build cache" file in the JS repo prior to initiating the build process. This effectively disables the build caching feature, thereby allowing the sparse checkout to operate in conjunction with the “rush build” process without any conflicts. This restores the system/pipelines to previous behavior.
**This change is …

[JS] Fix perf pipelines - "fix build cache error"

---

eng/common/scripts/ChangeLog-Operations.ps1
eng/common/scripts/Invoke-DevOpsAPI.ps1
eng/common/scripts/Package-Properties.ps1
eng/common/scripts/Update-ChangeLog.ps1
eng/common/scripts/artifact-metadata-parsing.ps1
eng/common/scripts/git-branch-push.ps1

During Hacktober, @LukaszKokot discovered these typos is some scripts checked into `azure/azure-dev`.  He raised a PR against us to fix, them but they should actually be fixed here, since they are part of the common engineering system.
I offered to move his patch over here on his behalf (since we dropped the ball a little on getting back to him).
This change brings over what was in https://github.com/Azure/azure-dev/pull/2881, to here, which is where these file ultimately live.

Fix typos in ps1 scripts

---

eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1

Turns out, when a changeset includes _the same_ changes, but a different _parent_ commit, `cherry-pick` kinda flips out with a 
> conflicts present
then shows no modified files in `git status`.
Base commit: [Automatic asset update from test-proxy. · Azure/azure-sdk-assets@c56e4d5 (github.com)](https://github.com/Azure/azure-sdk-assets/commit/c56e4d52e12cfadf0310e4e670ea7f8b0aeb9aba)
Mergee commit: [Automatic asset update from test-proxy. · Azure/azure-sdk-assets@aa77628 (github.com)](https://github.com/Azure/azure-sdk-assets/commit/aa7762873d5b2eba002ca7ea5ea1931218dcfb90)
Notice that the actual contents of the commits are the same, but the source it's coming from is not. This is the origin of the confusion for `cherry-pick`.
You can resolve this situation with a `git cherry-pick --skip`, …

Adjustment to `merge-asset-tags`

---

tools/tsp-client/CHANGELOG.md
tools/tsp-client/README.md
tools/tsp-client/package.json
tools/tsp-client/src/index.ts
tools/tsp-client/src/log.ts
tools/tsp-client/src/options.ts

Add support for swagger->tsp conversion with `convert` command. 
Fixes https://github.com/Azure/azure-sdk-tools/issues/7502
Relies on changes in #7525 (merge after 7525)

[tsp-client] Support swagger to typespec conversion

---

eng/pipelines/mirror-repos.yml

@markcowl the merge into the providerhub branch has started failing due to submodule conflicts. Given we aren't using this currently anyway I'm removing it from the mirroring. Once we figure out the merge update process we can add it back or setup independent automation.

Remove providerhub from mirror pipeline

---

eng/common/TestResources/New-TestResources.ps1
eng/common/TestResources/New-TestResources.ps1.md

The way that this can be integrated into language test frameworks is by assuming that if no client secret is populated, a user credential should be created instead of a client secret credential.
Also, downstream test-resources templates should remove testApplicationSecret from the parameter list to avoid being prompted for it (assuming it is not actually necessary).

Support creating test resources based on logged in user

---

tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Program.cs

Fixes #7463
Tried with storage stress tests  under load:
- no new issues
- OOM no longer happens
- memory utilization is 10x lower
- throghput in stress test went up ~5x times
(fault-injector is now at 200MB, used to be > 2GB)

FaultInjector: stream response instead of buffering

---

eng/common/scripts/Verify-RestApiSpecLocation.ps1

There are two cases for the naming of JS package folder:
- RLC package case, removing the "azure-rest-" from package name then plus "-rest" to the end of the name.
- Non-RLC package case, removing the "azure-" from the package name.
The changes include:
- correct the name of package folder for JS case.
- correct the name prefix of JS ARM package.
- add exception catch handler
- style format fix
The [pipeline test run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3430267&view=logs&j=7bb69cc7-6f52-585e-8b13-5bae7c4a9fa4&t=7abbbe6b-d005-5c95-feb6-99ffe4e699e1) of JS template package release with same script change looks good.

Correct the name of JS package folder

---

src/dotnet/APIView/APIView/Model/CodeFile.cs
src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs
src/dotnet/APIView/APIViewWeb/Models/APICodeFileModel.cs

Allows for identifying packages across different languages.

Add CrossLanguagePackageId Property

---

src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
tools/apiview/parsers/js-api-parser/export.ts
tools/apiview/parsers/js-api-parser/package.json
tools/apiview/parsers/js-api-parser/tokensBuilder.ts

This PR uses the id of the token to determine whether it should be added as a member or a type.

[js-api-parser] don't add members as types

---

tools/apiview/emitters/typespec-apiview/package.json
tools/apiview/emitters/typespec-apiview/pnpm-lock.yaml
tools/apiview/emitters/typespec-apiview/src/apiview.ts
tools/apiview/emitters/typespec-apiview/src/namespace-model.ts
tools/apiview/emitters/typespec-apiview/src/version.ts
tools/apiview/emitters/typespec-apiview/test/apiview.test.ts

Fixes: https://github.com/Azure/azure-rest-api-specs-pr/issues/16808
**TODO**

[TypeSpec APIView] Support SyntaxKind.TemplateArgument

---

eng/common/scripts/Verify-RestApiSpecLocation.ps1

The script fails to find the package for the `Go` language because the Go language doesn't generate a package for release; instead, it simply pushes the code to the GitHub repository. 
However, since the `Verify-PackageVersion` function doesn't actually use the package found by the `APIView` related function, I removed that part of the code. Now, the script works for these five languages by retrieving package information from the `{packagename}.json` file.
In addition, I added the validation for `Go` data plane scenario.
Test run result: 
[Go](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3438606&view=logs&j=6a8552c2-2ada-5ee5-a4d2-6fcf45f87c55&t=63abb2ae-8b99-518c-37b5-ceb4c0582ab3)
[JS](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3438579&view=logs&j= …

Remove package retrieval when verify pkg version

---

tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen/Azure.SDK.Management.ChangelogGen.csproj
tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen/Program.cs

1. Upgrade Azure.ResourceManager to 1.10.1
2. Include System.ClientModel when compiling api file to avoid compile error

upgrade resource manager to 1.10.1 and include reference to System.ClientModel

---

tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness.Tests/BlobUploadProcessorIntegrationTests.cs
tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/BlobUploadProcessor.cs

To avoid `Maximum API LImit of 10k` results.

Batching for TestResults

---

eng/common/scripts/Prepare-Release.ps1

On my machine, I experimented with the registry, and the worst part is that I don't remember/know how to reset it back.
The work items that script produces, do have datetimes for the upcoming releases in the `MM-dd-yyyy` format, and then I have to correct them by hand.
`dateTime.ToString("MM/dd/yyyy")` does produce the date in the format of `MM-dd-yyyy` on my machine. This also happens if I write a corresponding .NET app.
The fix that I am proposing makes it work on my specific setup and hopefully breaks no one else. I understand if you are hesitant to take it. Let me know, I'll see how I can restore my setting.
But on the other hand, I don't think it makes anything worse, it only makes things more robust, so maybe take it?

Prepare-Release.ps1: Make dateTime.ToString("MM/dd/yyyy") to work on exotic setups

---

eng/common/scripts/Verify-Links.ps1

https://learn.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-74?view=powershell-7.4
- Add AllowInsecureRedirect switch to Web cmdlets (#18546)
That new option cause a new exception type that exposed a bug where we assumed if InnerException property existed that it was not null. This fix verifies that the property is not null.
We only seem to hit this issue in the ios pipeline at https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3458379&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0.

Fix issue in Verify-Link.ps1 after PS 7.4 update

---

tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/appsettings.json

"Urls" in appsettings,json does not work, which broke storage live tests in java. Fixing to define kestrel endpoints there, tested locally

Fix fault injector default ports

---

eng/common/pipelines/templates/steps/sparse-checkout.yml

This is found in pipelines which were using the Azure Pipelines pool (not 1ES) and invoked `sparse-checkout.yml` in this way: 
https://github.com/Azure/azure-sdk-for-java/blob/main/eng/pipelines/docindex.yml#L19-L29
```yml 
- template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
parameters:
SkipCheckoutNone: true
Paths:
- package.json
- metadata/
- docs-ref-mapping/reference-unified.yml
- docs-ref-services/
Repositories:
- Name: $(DocRepoOwner)/$(DocRepoName)
WorkingDirectory: $(DocRepoLocation)
```
The final command in the sparse checkout fails: 
```pwsh 
git -c advice.detachedHead=false checkout $commitish --
```
When checking on parameter binding a subtle difference occurs: 
```
$PSNativeCommandArgumentPassing = 'Windows' 
Trace-Command -PSHost -Expression { git -c …
```

Fix sparse-checkout git command line behavior

---

eng/common/scripts/Invoke-GitHubAPI.ps1

This PR is to fix the issue 
https://github.com/Azure/azure-sdk-tools/issues/7621#issue-2114362657

Add ContentType header to Update-GitHubIssue

---

tools/tsp-client/src/index.ts

Adding a temporary workaround to delete the sparse-spec/ directory to reduce issues for folks who ran into errors during program execution. Have a tracking issue to do this at the end of the program instead: https://github.com/Azure/azure-sdk-tools/issues/7636

[tsp-client] Delete sparse-spec dir if it exists

---

tools/tsp-client/CHANGELOG.md
tools/tsp-client/package-lock.json
tools/tsp-client/package.json
tools/tsp-client/src/index.ts

- Fix a user reported bug related to issues when processing tspconfig.yaml:
- We need to read the contents of the file to parse the data. 
- Support passing in the directory that contains the tspconfig.yaml instead of the full path to the file. 
- Updating the package-lock.json which hadnt been done for a while 🙃

[tsp-client] Fix tspconfig.yaml processing in init command

---

eng/pipelines/eng-common-sync.yml

After https://github.com/Azure/azure-sdk/pull/7201 azure-sdk will be dependent on changes from eng/common. It only depends on a few items but I decided it is better to add to eng/common instead of manually syncing or doing a reference.

Add azure-sdk to eng/common sync

---

.github/workflows/event-processor.yml

The azure/login@v1.6.0 task added pre/post Azure Login steps and the pre-step is seriously impacting the time it takes to run an Action because it takes 30 seconds to run. This is further exacerbated by the fact that we only need the azure/login step for the issues opened event and the pre/post Azure Login steps are being added to each and Action.

Pin azure/login action step to v1.5.1

---

eng/common/TestResources/New-TestResources.ps1

For people doing local debugging of their bicep templates for stress tests, enable the deployment script to actually find those templates!

Add stress test arm/bicep template prefix to New-TestResources ResourceType set

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs

The focus of these changes is to add the "Azure.Compute" namespace to the approved list, per Krzysztof's approval for use in the `Azure.Compute.Batch` package.

[.NET Analyzers] Add new approved namespace

---

eng/common/spelling/Invoke-Cspell.ps1
eng/scripts/Set-VcpkgWriteModeCache.ps1

For C++-only fixes, see https://github.com/Azure/azure-sdk-for-cpp/pull/5346

Fix case-sensitive spelling in scripts that get deployed to C++ repo

---

src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs

The focus of these changes is to move the template special case logic from an equality check to a `StartsWith`, matching the behavior of the other checks.  By design, this allows subnamespaces of `Azure.Template` which are needed due to the structure of the Template project.

[.NET Analyzers] Fix Template special case

---

src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IPullRequestManager.cs
src/dotnet/APIView/APIViewWeb/Managers/PullRequestManager.cs

Include API reviews affected by current commit only in the comment on GitHub whenever APIView process the request to detect API changes. This will eliminate showing links of any stale reviews that were created by previous commit.

Exclude any API reviews no longer affected by PR

---

tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter.Tests/Utils/MonikerUtilsTests.cs
tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Utils/MonikerUtils.cs
tools/codeowners-utils/METADATA.md

The CodeownersUtils was parsing Monikers case sensitive. The problem here is that any line that starts with # and doesn't match a moniker is treated as just a comment and ignored. CODEOWNERS files have blocks that are Moniker/Comment/MonikerOrSourceLine.
The main reason to make the moniker parsing case insensitive is that it would be more painful to try and plumb a casing error through the utils for just the linter. Parsing in any other context (github-event-processor or pipeline-owners-extractor) doesn't error, it throws out CODEOWNERS entries that are in error or, if the case of a mis cased moniker, would omit that piece of data from the entry. For example, if instead of PRLabel, the moniker in the file was prLabel it would treat that as a comment and ignore it but would still have the …

Case Insensitive Moniker Parsing

---

eng/pipelines/openapitools/repo-structure-cache-job.yml
eng/scripts/openapitools/python/cacherepostructure/sync-repo-structure-cache.py

In this PR I fixed errors found when running the script against PPE.
Also, I had a chat with @weshaggard and we decided to use the same pipeline for both PPE and PROD environments. I'm separating the pipeline into three steps:
1. Install dependencies
2. Update PROD cache
3. Update PPE cache
Also, following Wes's advice, I removed the parameters for the pipelines since it is not expected for them to be changed. Removing them will reduce room for error when running this pipeline.

Fix errors in repo structure cache script and improve pipeline

---

tools/secret-management/Azure.Sdk.Tools.SecretRotation.Stores.AzureDevOps/ServiceAccountPersonalAccessTokenStore.cs

I was hitting a null reference exception while rotating a PAT and after debugging realized we aren't handling this case so I added handling to make the error message easier to understand.

Handle DevOps PAT creation error

---

tools/github/data/common-labels.csv

The focus of these changes is to add a new label,  "Communication - Messages" to the common label set across all managed repositories.

[GitHub] Adding new communication label

---

tools/stress-cluster/services/otelcollector/Dockerfile
tools/stress-cluster/services/otelcollector/otel-collector-config.yml
tools/stress-cluster/services/otelcollector/startup.sh

This creates a Docker image that wraps the actual otel collector in a container which can pull the proper env variable and write out a config file.
Note, this is dependent on a fix that injects the .env file into all containers in a pod, not just one, but can be built and pushed independent of that work.
CC: @LarryOsterman

Stress: adding in a wrapper image for the otel collector so we can use it with our stress cluster

---

.github/event-processor.config
.github/workflows/event-processor.yml
.github/workflows/scheduled-event-processor.yml

1. The CodeownersUtils update to [change the way ServiceLabel parses with AzureSdkOwners](https://github.com/Azure/azure-sdk-tools/pull/7754)
2. github-event-processor has new scheduled to [event to enforce max life of issues](https://github.com/Azure/azure-sdk-tools/pull/7693) which needs to be added to the scheduled-event.yml.
3. Add the new rule, EnforceMaxLifeOfIssues, to azure-sdk-tools' config file. Default it to Off.
Note: The .github/workflows yml files will get pushed out to all of the repositories that have the github-event-processor enabled but the event-processor.config does not. These are repository specific and are not controlled from a central location.

Update version of github-event-processor

---

eng/common/pipelines/codeowners-linter.yml
eng/pipelines/templates/variables/globals.yml

Updates to the CodeownersLinter, NotificationConfiguration and PipelineOwnersExtractor tool versions for the CodeownersUtils update to [change the way ServiceLabel parses with AzureSdkOwners](https://github.com/Azure/azure-sdk-tools/pull/7754)

Updates to tools for CodeownerUtils updates

---

src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md

Local APIView development requires an app config instance to connect to. For basic scenarios
it does not require any values, so the documentation was updated to add the minimal config
required

[APIView] Update local development docs

---

packages/python-packages/apistubgentest/apiview_mapping_python.json
packages/python-packages/apiview-stub-generator/CHANGELOG.md
packages/python-packages/apiview-stub-generator/apistub/_apiview.py
packages/python-packages/apiview-stub-generator/apistub/_metadata_map.py
packages/python-packages/apiview-stub-generator/apistub/_version.py
packages/python-packages/apiview-stub-generator/tests/apiview_test.py

Support "CrossLanguagePackageId". Requires an entry in `apiview_mapping_python.json` file:
```json
{
"CrossLanguagePackageId": "Foo",
"CrossLanguageDefinitionId": {
... // same as before
}
}
```

Support CrossLanguagePackageId
