Azure/azure-sdk-tools

- packages/python-packages/doc-warden/README.md
- packages/python-packages/doc-warden/setup.py
- packages/python-packages/doc-warden/warden/WardenConfiguration.py
- packages/python-packages/doc-warden/warden/__init__.py
- packages/python-packages/doc-warden/warden/cmd_entry.py
- packages/python-packages/doc-warden/warden/enforce_readme_content.py
- packages/python-packages/doc-warden/warden/enforce_readme_presence.py
- packages/python-packages/doc-warden/warden/version.py
- packages/python-packages/doc-warden/warden/warden_common.py
* Cleaning up namespace to just pieces we want public. Getting rid of `import *`
* Adding verification of a readme content. 
* Currently works by looking at the section headers.
* Supports regex matching of said section headers
* Works with the `omitted_paths` configuration so we will ignore readmes as expected
Before merge, I will update the readme with additional details on example usage of the readme verification. 
[Issue](https://github.com/Azure/azure-sdk/issues/203)
> Readme Content Verification

- README.md
- scripts/python/readme_tracking/readme.md
- scripts/python/readme_tracking/update_readmes_for_tracking.py
- web/pixel-server/PixelServer/Controllers/TrackingController.cs
Adding a script that can be pointed at a repository to generate and insert the `md` or `rst` tags necessary to so that we can find out what readmes people are looking at.
This will be pulled into `doc-warden` when we want to make this part of our regular build automation. This is pending, as we don't currently have patterns for "add another commit for X".
For now, we want to see how valuable this data is, hence the tool checkin + associated PRs.
Additionally, this PR includes an update to how we HANDLE the requests as well. Turns out that any trailing `?blahblah` added to an image request will be *blocked* by adblockers and the like. Instead we handle the path as the image name itself.
> Readme Pixel Tool

- .azure-pipelines/warden.yml
Such that we don't have to specialcase handling `.whl` files during parsing of necessary tags.
> Adding Source Distribution Output to Warden Build

- packages/python-packages/doc-warden/README.md
- packages/python-packages/doc-warden/warden/version.py
As that is old and no longer required due to warden's improved code base!
> Readme Updates - Removing `Sudo` mentions

- .azure-pipelines/dotnet.yml
- eng/Directory.Build.props
- eng/Directory.Build.targets
- eng/Versioning.props
- eng/Versioning.targets
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
Mostly follows https://github.com/dotnet/arcade/blob/master/Documentation/CoreVersioning.md
but uses the full date for package version instead of the short date we need to use
for file versioning.
Fixes https://github.com/Azure/azure-sdk-tools/issues/27
PTAL @pakrym
> Add versioning support props and targets

- .azure-pipelines/warden.yml
To ease with pain during release.
> Moving Warden Output To Own SubDirectory

- packages/python-packages/doc-warden/README.md
- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/setup.py
- packages/python-packages/doc-warden/warden/PackageInfo.py
- packages/python-packages/doc-warden/warden/WardenConfiguration.py
- packages/python-packages/doc-warden/warden/__init__.py
- packages/python-packages/doc-warden/warden/cmd_entry.py
- packages/python-packages/doc-warden/warden/enforce_readme_presence.py
- packages/python-packages/doc-warden/warden/index_packages.py
- packages/python-packages/doc-warden/warden/version.py
- packages/python-packages/doc-warden/warden/warden_common.py
New Functionality
* `ward index` outputs a `packages.md` file at the root of the repository. Location can be overrided via `-p` or `--package-output` arguments.
ToDo:
- Respond to Feedback on individual `packages.md` per repo
> Enable Doc Warden Feature - Package Indexing

- packages/python-packages/doc-warden/warden/PackageInfo.py
The default case wasn't working as expected.
> Fix default behavior for TestURL and TransformationArguments

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0002Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0003Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0005Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0006Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0007Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/DiagnosticAnalyzerRunner.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/DiagnosticProject.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAnalyzerBase.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientConstructorAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Descriptors.cs
Fixes: https://github.com/Azure/azure-sdk-tools/issues/37
Add analyzers for client type methods and constructors.
You can see the list in `Descriptors.cs` diff.
> Add Client type analyzers

- tools/pipeline-generator/PipelineGenerator/PipelineConvention.cs
- tools/pipeline-generator/PipelineGenerator/PullRequestValidationPipelineConvention.cs
This change makes it so that when the pipeline generator tool runs it automatically sets/updates the folder on the definition. Also fixed up a bug where the slashes on the YAML path were around the wrong way. It worked, but would cause a few UI glitches in Azure DevOps when you went to edit a pipeline.
> Set/update folder name based on prefix.

- .azure-pipelines/js.yml
- tools/eslint-plugin-azure-sdk/ci.yml
Related to #54 - attempt at creating pipeline needed for #53.
To be honest, I have no idea if I'm doing this right but I want to have the following functionality:
- Build - `npm run build` and `npm pack`
- Analyze - `npm run lint` and `npm audit`
- Test - `npm test`
The project defined in #53 will reside in `src/ts/eslint-plugin-azure-sdk`, which I access by `cd`ing in through a script block, but I'm not sure if this is the correct way to do it or how to make it modular to other projects in `src/ts`.
> Set up JS pipelines

- .gitignore
- tools/notification-configuration/.gitignore
- tools/notification-configuration/Enums/TeamPurpose.cs
- tools/notification-configuration/Models/TeamMetadata.cs
- tools/notification-configuration/NotificationConfigurator.cs
- tools/notification-configuration/Program.cs
- tools/notification-configuration/Services/AzureDevOpsService.cs
- tools/notification-configuration/YamlHelper.cs
- tools/notification-configuration/notification-configuration.csproj
- tools/notification-configuration/notification-configuration.sln
A command line tool that generates teams and subscribes them to scheduled build failures for pipelines that have scheduled builds.
> add notification-configuration tool

- tools/eslint-plugin-azure-sdk/ci.yml
This PR swaps from the explicit publish artifacts task to the publish keyword which is a bit easier and will automatically kept current. It also fixes up a path issue where I was uploading too much.
> Moved to publish keyword.

- tools/eslint-plugin-azure-sdk/README.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-allowsyntheticdefaultimports.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-declaration.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-esmoduleinterop.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-exclude.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-forceconsistentcasinginfilenames.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-importhelpers.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-isolatedmodules.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-lib.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-module.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-no-experimentaldecorators.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-sourcemap.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-config-strict.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-author.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-bugs.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-homepage.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-keywords.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-license.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-name.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-repo.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-required-scripts.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-package-json-sideeffects.md
- tools/eslint-plugin-azure-sdk/package-lock.json
- tools/eslint-plugin-azure-sdk/package.json
- tools/eslint-plugin-azure-sdk/src/configs/index.ts
- tools/eslint-plugin-azure-sdk/tests/plugin.ts
For publishing to NPM, `eslint-plugin-azure-sdk` will be rescoped from `@azuresdktools` to `@azure`.
I also re-ran a format script that caused a bunch of changes in the documentation, making the PR size a bit larger than it would be otherwise.
> Rescope eslint-plugin-azure-sdk to @azure

- tools/eslint-plugin-azure-sdk/ci.yml
This PR adds a release stage that publishes to NPM. It retains the old release stage as pre-release. Eventually we'll break these stages out into a separate template. But for now this is just to get the eslint-plug-azure-sdk process unblocked and we can then iterate to refine this NPM release pipeline and make it more reusable.
> Setup for NPM release.

- tools/eslint-plugin-azure-sdk/package.json
- tools/eslint-plugin-azure-sdk/src/rules/ts-doc-internal.ts
The `ts-doc-internal` rule fetches type information about all exports from the main entrypoint of a package - to do so, if exports have not been fetched yet it uses the parser services to fetch the SourceFile corresponding to the main entrypoint and proceed from there.
However, running this rule on the scripts I set up in the [demo PR](https://github.com/Azure/azure-sdk-for-js/pull/4330) results in more lint errors than there should be, and upon examination it seems that `getSourceFile` in `src/utils/exports.ts` fails. This is because the first files executed on by ESLint in the scripts I ran on are `package.json` and `tsconfig.json`, and the compiler settings are likely different, leading to a failure to fetch a `SourceFile`. Without any changes, this could be solved by ensuring that …
> Fix ts-doc-internal

- tools/eslint-plugin-azure-sdk/ci.yml
- tools/eslint-plugin-azure-sdk/package.json
This PR swaps the prerelease process over to publish to the azure-sdk public feed instead of the internal feed.
> Publish to azure-sdk public feed.

- tools/eslint-plugin-azure-sdk/package-lock.json
- tools/eslint-plugin-azure-sdk/package.json
- tools/eslint-plugin-azure-sdk/src/rules/ts-doc-internal.ts
- tools/eslint-plugin-azure-sdk/src/rules/ts-use-interface-parameters.ts
- tools/eslint-plugin-azure-sdk/tests/rules/ts-use-interface-parameters.ts
Files that are marked as excluded by `typedoc.json` are being flagged for errors, which is not what we want.
To fix this, we define a list of excluded files as follows:
- If `typedoc.json` does not exist, the list is empty
- Otherwise, the list corresponds to all files matching the glob patterns specified in the `exclude` field in `typedoc.json` if found (excluding files in `node_modules`
Files in test directories were being flagged, which doesn't make sense for this rule as it exists to protect users of the library from having to deal with class-based conflicts. As test files are not user-facing, we can simply only have the rule operate on files in `src`.
> Ignore rules on certain files

- tools/eslint-plugin-azure-sdk/package-lock.json
- tools/eslint-plugin-azure-sdk/package.json
- tools/eslint-plugin-azure-sdk/src/rules/ts-doc-internal.ts
- tools/eslint-plugin-azure-sdk/src/rules/ts-modules-only-named.ts
`eslint-plugin-azure-sdk` had a dependency on [path](https://www.npmjs.com/package/path), when it could have just used the inbuilt node path module.
This PR removes the external dependency and allows for the removal of all `@ts-ignore` tags in `eslint-plugin-azure-sdk`.
Also bumps `mocha` to latest version.
> Remove dependency on path

- tools/eslint-plugin-azure-sdk/docs/rules/github-source-headers.md
- tools/eslint-plugin-azure-sdk/package.json
- tools/eslint-plugin-azure-sdk/src/rules/github-source-headers.ts
- tools/eslint-plugin-azure-sdk/tests/rules/github-source-headers.ts
`github-source-headers` previously assumed that the correct copyright header was the following:
```fundamental
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT license.
```
However, this has changed to the following:
```fundamental
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
```
This PR updates the rule definition to accommodate these changes, bumping the package version to `1.1.1`.
> Update copyright header definitions

- tools/notification-configuration/common/Services/AzureDevOpsService.cs
- tools/notification-configuration/github-codeowner-subscriber/Program.cs
This code more gracefully handles the case where a pipeline is deleted but its notification teams are not deleted. Because these applications run independently this should handle the edge case more gracefully than it currently does. 
The pipelines that run this do not complete successfully under these conditions until a fix is merged.
> skip pipelines that don't exist

- tools/eslint-plugin-azure-sdk/package.json
- tools/eslint-plugin-azure-sdk/src/rules/ts-naming-drop-noun.ts
- tools/eslint-plugin-azure-sdk/src/rules/ts-naming-subclients.ts
- tools/eslint-plugin-azure-sdk/src/rules/ts-pagination-list.ts
A few rules depend on `AST_NODE_TYPES`, an enum used in `@typescript-eslint/experimental-utils` - however, this dependency does not disappear on compilation unlike all other imports from any `@typescript-eslint` package. To resolve this, this PR uses the enum strings literally and bumps the version to `1.3.0-preview.2`
> Remove dependency on AST_NODE_TYPES

- tools/eslint-plugin-azure-sdk/package.json
- tools/eslint-plugin-azure-sdk/src/rules/ts-apisurface-supportcancellation.ts
- tools/eslint-plugin-azure-sdk/tests/rules/ts-apisurface-supportcancellation.ts
`ts-apisurface-supportcancellation` was causing runtime errors and incorrect reports, this PR fixes this issue and bumps `@azure/eslint-plugin-azure-sdk` to `1.3.0-preview.3`.
> Fix ts-apisurface-supportcancellation

- tools/eslint-plugin-azure-sdk/src/processors/index.ts
- tools/eslint-plugin-azure-sdk/src/rules/github-source-headers.ts
- tools/eslint-plugin-azure-sdk/src/utils/metadata.ts
`--fix` produces unexpected behavior, such as unexplained crashes and lint error reports where not using `--fix` would not have produced a lint error.
> Patch --fix option

- src/dotnet/Mgmt.CI.BuildTools/NugetToolsPackage/CI.Tools.Package/build/targets/common.targets
dotnet test causes restore/build implicitly, causing race conditions.
Skipping restore and build while test execution
> skipping restore and build during test execution. 

- tools/eslint-plugin-azure-sdk/package-lock.json
- tools/eslint-plugin-azure-sdk/package.json
- tools/eslint-plugin-azure-sdk/src/rules/github-source-headers.ts
ESLint autofix interactions with `Comment` nodes aren't immediately intuitive and the previous implementation didn't work properly. This PR addresses this issue and bumps the version to `1.3.0-preview.6`.
> Fix github-source-header comment interactions

- packages/python-packages/tox-monorepo/setup.py
- packages/python-packages/tox-monorepo/tox_monorepo/monorepo.py
- packages/python-packages/tox-monorepo/tox_monorepo/version.py
Missed `{cachedir}` in the config settings for the individual environment. I thought it would base it off of `{toxinidir}`, but that wasn't the case. Turns out, it's one of the automatically set environment variables that needed to be updated.
> Tox Monorepo - Ensuring {cachedir} is unique per run

- tools/eslint-plugin-azure-sdk/package-lock.json
- tools/eslint-plugin-azure-sdk/package.json
- tools/eslint-plugin-azure-sdk/src/rules/ts-use-interface-parameters.ts
Reading `method.value` on line `307` of `src/rules/ts-use-interface-parameters` results in an error where method occasionally returns undefined.
This PR patches this bug and changes `@azure/eslint-plugin-azure-sdk` to `2.0.0-preview.2`.
> Fix ts-use-interface-params

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/ContinuousIntegrationPipelineConvention.cs
I had this in a local change and forgot to push it before merging. Just putting it in now to unblock the pipeline generation automation.
> Fix an overflow error caused by not calling against base class.

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
The automated version numbering isn't working correctly. To get unblocked for my current task I'm going to bump the patch number on the tool then come back and have a closer look as to why the build number didn't increment.
> Bump version number

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
Lifted the schedule bucketing technique into the base pipeline convention class and implemented the same logic for the unified pipelines convention that is used in the integration tests (which makes sense since the unified pipelines will ultimately take over for running these live tests).
> Add scheduled triggers to unified pipelines.

- tools/eslint-plugin-azure-sdk/ci.yml
This PR fixes a typo in the artifact name. Reminder that I need to do some artifact presence checks in the PR phase to pick up these issues earlier.
> Fix a typo in artifact name.

- tools/notification-configuration/github-codeowner-subscriber/CodeOwnersParser.cs
expand scope of notifications to include all matching expressions instead of last matching expression
> expand scope of notifications 

- tools/notification-configuration/common/Services/AzureDevOpsService.cs
Turns out the Azure DevOps API returns 100 teams by default. This increases that limit.
> fetch all teams

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/RepositoryConfiguration.cs
This PR is a reaction to some of the conversations we've had about making ```enabled: true``` the default if the ```eng/CHECKENFORCER``` file is present, but it is still visible to have ```enabled: true`` or ```enabled: false```.
> Introduce a default for enabled flag.

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer.Tests/Azure.Sdk.Tools.CheckEnforcer.Tests.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer.Tests/Integrations/GitHub/GitHubWebhookSignatureValidatorTest.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/CheckEnforcerSecurityException.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/CheckEnforcerConfigurationException.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/GlobalConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IGlobalConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IRepositoryConfiguration.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IRepositoryConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfiguration.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Constants.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubClientFactory.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookFunction.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GobalConfiguration.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckRunHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckSuiteHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/HandlerContext.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/IssueCommentHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubClientProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubWebhookSignatureValidator.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/IGitHubClientProvider.cs
- tools/check-enforcer/CheckEnforcer.sln
This PR does some restructuring to the code to try and work around some of the error states we were getting into in production. It also adds the ability re-evaluate Check Enforcer. It also moves the app ID and check name into environmental configuration.
> Check Enforcer fixes.

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Missing a space after the generic type <T> on methods.
https://apiview.azurewebsites.net/Assemblies/Review/bf57bf1f08a3443bb5c66a4f56248178
> missing sapce after type parameter

- src/dotnet/APIView/APIViewWeb/wwwroot/css/site.css
I just used the styling that GitHub applied to their blockquotes to ours.
Before:
After:
> Style blockquotes in APIView comments

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
For now we are cutting out the public CI triggers and letting
the internal CI jobs handle the load to help eliminate some
of the build queuing issues.
@mitchdenny I ran this locally in, js/python/java but until this comes in they will get reset so lets get this merged and published asap
> Disable public CI triggers in our pipeline generation

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/GlobalConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IGlobalConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfigurationCacheEntry.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookFunction.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckRunHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckSuiteHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/IssueCommentHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Locking/CheckEnforcerDistributedLockException.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Locking/DistributedLock.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Locking/DistributedLockProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Locking/IDistributedLockProvider.cs
This PR adds distributed locking (via Azure Storage blob leases) to serialize operations against GitHub. This is a MVP of this approach. If this works and we don't have any further issues with GitHub getting into an inconsistent state then we can look at optimizing this more.
> Add distributed locking to Check Enforcer

- scripts/python/util/replace_relative_links.py
We wanted to also resolve absolute _folders_.
`os.path.exists` only differs from `os.path.isfile` in that the latter ensures it's not a directory.
> Fixes for Java - Resolve Paths to Folders

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs
Add Azure.AI to namespace prefixes in static analyzers.  Remove Azure.ApplicationModel.
Fixes Azure/azure-sdk-for-net#7384.
> Add and remove namespaces from .NET analyzers

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
This PR fixes a bug that triggered after a recent change where internal unified pipelines became untriggerable via an ```/azp run``` comment. The issue was the ```SettingsSourceType``` field value. Upon initial creation it was set to 1 (default), but when a change was detected it got set to 2 -- changing the way that path filters were evaluated. The fix is to make it detect when the unified pipeline convention based pipeline is set incorrectly and flick the value back to 1. When this is merged and we update the pipeline generator all the internal pipelines will be triggerable again after the next generation run.
> Fix for internal pipelines not being comment triggerable.

- packages/python-packages/doc-warden/warden/warden_common.py
@chidozieononiwu 
This is the solution we were looking for.
Lacking a return meant that for the `indexing` action, .NET wasn't finding any packages due to not _returning them_ from the function that finds them!
> Fixing a bug when generating a repo index for .net

- packages/python-packages/tox-monorepo/tox_monorepo/monorepo.py
- packages/python-packages/tox-monorepo/tox_monorepo/version.py
Ensuring that they end up in the proper location. This bugfix is a step towards ensuring that multiple `tox` invocations can run at the same time. 
> Updating Env Log Outputs

- eng/pipelines/templates/scripts/replace-relative-links.yml
This is a minor fix to the relative link replacement.
What was happening is that it wasn't correctly handling a relative link with a location.  For example: foo.md would get it's relative link replaced just fine but foo.md#bar wouldn't. The is_relative_link was checks whether or not something is a relative link by seeing if the combined path exists which would never pass due to the "#location" being part of the link. The fix here is to check if the link contains a # sign, not as the first character, and if so strip it off before checking the path.
> Fix to handle links with location

- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/warden/WardenConfiguration.py
- packages/python-packages/doc-warden/warden/cmd_entry.py
- packages/python-packages/doc-warden/warden/version.py
- Added `all` option to `--target` argument.
- Default to running operations on readmes. When `--target` is set to `changelog` run operations on changelogs, when set to `all` run operations on both readmes and changlogs.
- exit if `all` command is used on `presence` or `content` operations.
> Update warden to accommodate servicing branches

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
This fixes the problem that is preventing Check Enforcer from being made a required check. The problem manifests as **_Required statuses must pass before merging_** even though all checks show as "successful".
The root cause appears to be a bug in Azure Pipelines. Azure Pipelines is incorrectly creating/completing a check run against the **_merge_** commit of the PR (not the head commit). This happens in the scenario where no jobs get run due to there being no files in the PR that match the pipeline's PR trigger file path filters.
The fix avoids creating a new check run on every check completion because, as mentioned above, a check run is being incorrectly created against the merge commit SHA. GitHub show all checks as passed, but the check associated with the merge commit SHA is still …
> Check enforcer: fix for issue blocking PR merging

- eng/pipelines/live-test-cleanup.yml
- tools/live-test-cleanup/README.md
- tools/live-test-cleanup/cleanup.ps1
Of note: I put the pipeline yml file in eng/pipelines because this seems like a cross-cutting pipeline. However, I could see reasonable arguments for putting the pipeline yml file in the folder with the cleanup script. 
Sample run (with `-WhatIf` flag): https://dev.azure.com/azure-sdk/playground/_build/results?buildId=233831&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=8c98ab76-57b2-59d0-3d3a-18dce788f3ba
> Live test resource cleanup

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0012Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0013Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/AddConfigureAwaitAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/AsyncAnalyzerUtilities.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
Also:
- Collapse multiple tests for disabling AZC0013 into one
- Add test for non-compilable code
- Remove dependency on Microsoft.Bcl.AsyncInterfaces
> Fix #328: Analyze async using statement without braces.

- src/dotnet/APIView/APIViewWeb/Startup.cs
- src/dotnet/APIView/APIViewWeb/appsettings.json
Also add @ symbol for email lookup.
> Remove trailing slash as Url parsing code doesn't expect it.

- src/dotnet/APIView/APIViewWeb/Controllers/AccountController.cs
- src/dotnet/APIView/APIViewWeb/Pages/Unauthorized.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Unauthorized.cshtml.cs
Links to individual reviews wouldn't work if the user was prompted to login.
Relative links to comments still won't work correctly as the "#" part of Url is not sent to the server, but at least users will get directed to the correct review, instead of the default Api View page listing all reviews.
> Thread review Url through login button

- packages/python-packages/doc-warden/warden/enforce_changelog_content.py
- packages/python-packages/doc-warden/warden/enforce_target_file_presence.py
- packages/python-packages/doc-warden/warden/index_packages.py
- packages/python-packages/doc-warden/warden/warden_common.py
DocWarden needs an iOS and Android option. Its kinda strange to cause this a language value when it generally appears to map to the repository name.
> Add swift to the list of supported languages

- packages/python-packages/doc-warden/warden/version.py
This PR bumps the ```doc-warden``` version. I'm going to insta merge this one since I need to publish the new version of the package. If any pipelines break then it means that they had a bug which was not specifying the version of ```doc-warden``` that they are using ;)
> Bump doc-warden version for release.

- eng/pipelines/eng-common-sync.yml
Currently there are some script and pwsh steps that don't
work well on linux so we need to stay on windows until those
can be fixed.
Things that don't work well:
- echo commands in script blocks. On windows they don't need quotes
but on linux they do and escaping quotes is also different
- commands like mkdir on in pwsh scripts don't work consistently
on windows it will create parent directories because it does
the create recurisvely and it is just an alias to new-item. On
linux it is not an alias and you have to pass the "-p" arg to
get it to create parent directories. In general we should be careful
with using alias' for cross-platform pwsh because they are not
consistently alias' on all platforms.
FYI @heaths @mitchdenny 
cc @Azure/azure-sdk-eng
> Change back to windows host

- eng/common/InterdependencyGraph.html
Since the dependency graph is going to be common across all repos, move it from dependency-graph/index.html to eng/common and rename it to InterdependencyGraph.html. Also, change the html page title from Dependency Graph to Interdependency Graph.
> move the interdependency graph page to eng/common

- eng/pipelines/templates/scripts/replace-relative-links.yml
There was an issue with image files not correctly showing up in the HTML (https://github.com/Azure/azure-sdk-for-java/issues/7703) The problem was that the links for image files need to be pulled from /raw not /tree in order to get the raw image.
> Update to handle links to image files

- tools/feed-cleaner/Clean-Feeds.ps1
This PR includes a script that I created to remove old ```azure-sdk-{runid}``` feeds. It determines that the feed is eligible for deletion by first listing all the feeds that match that format, then using the run ID looking up the pipeline run to see whether the pipeline is still active. If the pipeline is still in-progress then it removes the feed.
This script will be run by a scheduled pipeline every day. Generally we shouldn't have too many but this will stop them accumulating.
> Feed cleaner

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
Fix for #384 where nested interfaces were not being shown in the API view when they should be, because they were defined within another interface where they are implicitly public.
Fixes #384
> Fix for #384 - missing nested interfaces

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/SdkComponent.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/SdkComponentScanner.cs
This PR adds support for variants to generated pipelines. In the Java repository we have adopted a convention of having ```ci.mgmt.yml``` and ```ci.data.yml``` files in addition to the regular ```ci.yml``` files. The additional ```.[something]``` signifies a variation to the pipeline for a particular scenario, for example building track 1 libraries or building management plane libraries where they can't co-exist within the same build (or we don't want them to for performance reasons).
What this change does is for PR and CI pipelines, it changes the search criteria to ```ci*.yml``` which picks up these variants. I am then using a regular expression to extract the variant detail and append it to the pipeline name so it is unique. This is inline with the convention that we adopted for the …
> Variant support for Pipeline Generator

- eng/common/Extract-ReleaseNotes.ps1
- scripts/powershell/create-tags-and-git-release.ps1
Move out `ExtractReleaseNotes` function into its own script
Update changelog names to CHANGELOG.md
> Move out ExtractReleaseNotes script to enable reuse.

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
In an effort to space scheduled builds/live test runs out a bit more, increasing the number of buckets that we distribute across.
/cc @danieljurek for input on whether this is the right approach.
> Create more buckets for pipeline generator

- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/setup.py
- packages/python-packages/doc-warden/warden/version.py
Packages pathlib and pathlib2 are conflicting when doc-warden and virtualenv is installed together. Fix is to update package requirement to pathlib2
> Update package requirement

- eng/pipelines/templates/scripts/verify-agent-os.yml
There is no need to set this again here as the variable is already set in the pipeline that calls the script.
> Stop Overwriting OSName value

- eng/pipelines/templates/steps/sync-directory.yml
If you pass `*.*` with the remove or copy cmdlets it doesn't copy
the nested subdirectories even if you pass the -r option. To fix
we need to just remove those wildcards as they aren't necessary.
PTAL @danieljurek @chidozieononiwu 
cc @Azure/azure-sdk-eng
> Allow nested directories in sync-directory template

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
- Bounded type parameters has extra space after.
- Private inner class should not be shown. 
Fixes: #429
> [Java-Bugs] Type parameters extra space and private inner class should not shown

- eng/common/TestResources/New-TestResources.ps1
- Cmdlet New-AzResourceGroupDeployment does not accept a "-Location" parameter
> Remove invalid "-Location" parameter

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/deploy-test-resources.yml
- eng/common/TestResources/remove-test-resources.yml
* remove the need to specify secrets/variables from the calling template
* consolidate provisioner and test application so we have to manage fewer secrets
* add support for deploying to sovereign clouds based on a variable (e.g. can be specified in matrix)
> Update resource deployment scripts to support deployments to sovereign clouds

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
fixes: #451 No default constructor in Enum 
Result: Green highlight is the bug shown. This PR resolved it.
fixes: #441 Bounded type parameter is missing space in between
Result:
> Space between bounded type parameter and no default constructor in enum

- eng/common/pipelines/templates/steps/create-pull-request.yml
This change will allow version increase PRs to be created for branches instead of only master. Since we're still in the middle of transitioning files out of the azure-sdk-build-tools repo, the same change is going to be made to the same file in that repo as well.
> Allow version increase PRs to be created on branches

- eng/pipelines/live-test-cleanup.yml
- tools/live-test-cleanup/cleanup.ps1
Sovereign clouds now have smoke tests run against them periodically, this script makes us good stewards of those resources.
> Add sovereign clouds to live test resource cleanup

- eng/common/Update-Change-Log.ps1
Version increment tool is called for all packages in case of Java due to centralized version file and update change log should new entry only if version is not present in log. so far check was against latest version title in change log and it works in most of the scenarios except below when multiple packages are getting released within short duration.
Let's say someone manually updates change log to set release date or to add new version title to prepare for release but that version is not yet updated for package in centralized version file. Meanwhile if another package is released and it triggers version increment tool. This will also call for the package that is being prepared for release and update change log script doesn't find the package version in latest version title in log and as …
> Change log should not be updated if version is already present 

- src/dotnet/APIView/APIViewWeb/Repositories/CommentsManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/NotificationManager.cs
- Don't send notifications when someone resolves a comment
- Don't include timestamp - it should be in the email and we don't have to worry about localizing the time zone.
> Don't notify on resolve; don't include timestamp

- eng/common/TestResources/New-TestResources.ps1
Now that the script is in a new folder, fix the `-ServiceDirectory` parameter resolution.
> Fix -ServiceDirectory parameter

- eng/common/TestResources/New-TestResources.ps1
Remove validation for $AdditionalParameters because it throws an error when an empty set is provided. having this validation in place makes it difficult to provide the option for additional parameters and instead either requires that the template exclude the -AdditionalParameters parameter or that it fill it with something that is effectively meaningless.
> Remove validation for $AdditionalParameters

- eng/common/scripts/SemVer.ps1
- A builtin Powershell version of SemVer exists in 'System.Management.Automation'. At this time, it does not parsing of PrereleaseNumber. It's name is also type accelerated to 'SemVer'.
- Add some additional common parsing logic
> Rename SemVer due to type conflict

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0012Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAnalyzerBase.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Descriptors.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/TypeNameAnalyzer.cs
And Management to an allowed namespace list
Fixes: https://github.com/Azure/azure-sdk-tools/issues/459
> Add single-word type name analyzer

- .azure-pipelines/apiview.yml
- .azure-pipelines/dotnet.yml
- .azure-pipelines/warden.yml
Noticed some pipelines running that don't need to based on path filter. This is an initial step in starting to clean some of this up. Ultimately we should adopt a similar practice to what we do in the other mono repos where each discrete "thing" has its own pipeline, with its own ci.yml file. That would mean we can use the pipeline generator on the SDK tools repo as well.
> Path filter improvements

- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/warden/enforce_readme_content.py
- packages/python-packages/doc-warden/warden/version.py
If we ever hit a case where we need to use the content of the code of those fences, we'll parse it separately.
If we DON'T remove code-fence blocks, the implicit hierarchy of the markdown document is broken by phantom h1 headers. Discovered this while enabling sub-header verification in .NET.
> [Doc-Warden] Remove Code Fence Blocks During Parsing

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/PullRequestHandler.cs
Up until now Check Enforcer has been listening for Check Suite and Check Run events. However I noticed that with forked PRs that the check suite event never seemed to get sent, and previous attempts to make Check Enforcer resilient to this can lead to race conditions.
This change adds an event handler for the ```pull_request``` event so that when a PR is updated that there is an opportunity for Check Enforcer to create the Check Run instance which later ```check_run``` completion events update the state on.
I'm running this in staging now and production shortly (deploying off a feature branch) and it appears to be stable.
> Check Enforcer ... listen to PR events

- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- packages/python-packages/api-stub-generator/apistub/nodes/_argtype.py
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/apistub/nodes/_enum_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_property_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_variable_node.py
Changes:
1. Generate list error report to show in console
2. Ignore return type validation for dunder methods
3. Remove invalid type error for split argument "*"
> Generate lint error report and list them on console

- eng/common/TestResources/New-TestResources.ps1
We use $serviceName for non-CI scenarios but it was set only on CI.
> Port serviceName New-TestResources fix

- eng/pipelines/pipeline-generation.yml
The yml file is unchanged from where it was in azure-sdk-build-tools. Once this merges I will update our pipeline to use this one and delete the version in azure-sdk-build-tools. I will also update that pipeline to use the service account PAT as part of that change.
> Move pipeline generation yml to azure-sdk-tools

- eng/pipelines/pipeline-generation.yml
Add generation of test pipelines for .NET, Python, and Java repos. JS repo isn't setup to have service level test pipelines they are at the package level so we cannot add them yet. 
cc @mitchdenny @danieljurek
> Generate tests pipelines for .net/java/python repos

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/IssueCommentHandler.cs
- tools/check-enforcer/README.md
Now that Check Enforcer is live and appears to be behaving itself we can remove the debug commands. I also added a section to the README that outlines the updated commands.
> Check Enforcer: remove debug commands, update docs

- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/Remove-TestResources.ps1.md
- eng/common/TestResources/remove-test-resources.yml
Since there are certain actions that might need to be taken prior to deletion of test resources, we will invoke custom scripts in the service directory named : remove-test-resources-pre.ps1
> Make Remove-TestResource invoke custom script prior to deletion of the resource group

- eng/common/pipelines/templates/steps/bypass-local-dns.yml
Common  YAML template to bypass local DNS.
> Create common yaml template to bypass local DNS

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
Without adding an explicit comment it basically keeps
the last comment which is a little misleading when looking
at the history.
> Add comment when updating pipelines

- eng/pipelines/pipeline-generation-single.yml
- eng/pipelines/pipeline-generation.yml
- eng/pipelines/templates/steps/install-pipeline-generation.yml
PTAL @mitchdenny @danieljurek 
I've setup the pipeline that wraps this at https://dev.azure.com/azure-sdk/internal/_build?definitionId=1702&_a=summary. I used to to setup the tests pipeline for the iot team earlier and we can use this to setup other one-off pipelines and perhaps even add in the logic to create the initial yml files for new pipelines also.
> Add pipeline generation template for building one pipeline

- eng/common/scripts/Submit-PullRequest.ps1
- eng/common/scripts/copy-docs-to-blobstorage.ps1
- eng/common/scripts/copy-readmes-to-docs.ps1
- eng/common/scripts/create-tags-and-git-release.ps1
- eng/common/scripts/git-branch-push.ps1
Try #2 as the first attempt https://github.com/Azure/azure-sdk-tools/pull/481 didn't work in all cases. In particular it doesn't work when you invoke the powershell script across multiple lines as `$myInvocation.Line` only gives you the first line of context. Why? I have no idea but this new approach seems to work from my limited testing. I guess time will tell if there are any other weird issues.
cc @Azure/azure-sdk-eng
> Output script name and args for debugging purposes

- eng/common/TestResources/Remove-TestResources.ps1
If the -ResourceGroupName parameter is provided, we can't specify it when we pass all parameters to the sub-scripts so we will only do that if the resource group name is a calculated parameter and not when it has been specified in the input
> Fix remove-test-resources script to provide sufficient parameters to the pre-removal script depending on the input parameters.

- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Functions/RouteWebhookFunction.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Integrations/GitHub/GitHubWebhookSignatureValidator.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/AzureDevOpsRule.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/GenericRule.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/GitHubRule.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/IRouter.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Payload.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/PayloadType.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Rule.cs
This PR adds payload validation (for GitHub webhooks) in the Webhook Router. It adds a configuration value to the app config store which specifies the secret in KeyVault. The secret is then fetched and used to validate the signature header that GitHub adds to the webhook payload.
There is a stub for AzureDevOps validation as well but at the moment it just passes through.
> Webhook router payload validation

- eng/common/TestResources/Remove-TestResources.ps1
This fixes a bug where if you have provided a resource group name in your inputs, it will try to add it again whereas it should do the opposite. 
This only affects services that are using a pre-removal script (as of today only Azure IoT)
> Fix the logic for removal script

- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Startup.cs
This PR adds a simple 60 second cache to route settings and secrets (the two most expensive calls in terms of execution time per request). This should help performance during busy times but won't do much if the system has cooled off (we would need to actively fetch this data in advance to optimize for that scenario).
This took the request duration down from 7 seconds on my local machine (factoring in route trip time for multiple calls to West US 2 down to under 100ms (except when the cache expired). This should shift the percentile lines quite a bit and then we can figure out if we want to go further from there.
> Webhook Router optmization pass

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookFunction.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookOverEventHubsFunction.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookOverHttpFunction.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubWebhookSignatureValidator.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Startup.cs
This PR cuts Check Enforcer over to using Event Hubs to receive webhook notifications (indirectly via our Webhook Router).
Cutover for staging will take place on off this feature branch for validation purposes and will be done by changing the webhook URL for the Check Enforcer (staging) app to route within Webhook Router. Messages will temporarily flowing to Check Enforcer at which point we'll deploy the update (takes a few minutes) and then Check Enforcer will start processing the events via Event Hubs instead.
A subsequent update will remove the HTTP trigger from the function (once we are sure it isn't needed anymore). We'll probably run in staging for a while just to identify any teething problems and make sure we've got all we need in terms of telemetry.
> Check Enforcer EventHubs cut-over

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
This PR makes use of the PR library to introduce some back-off logic (retry 3 times after the timeout suggested by GitHub). I'm making use of the Polly library for this. We can do this now because we aren't on the critical path for a HTTP response.
I don't know if GitHub adds jitter to their back-off suggestions.
> Check Enforcer back-off

- src/dotnet/APIView/APIViewWeb/Languages/CLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Program.cs
Upload artifact is clang JSON AST file(s) in a zip archive. **Requires clang 10**
To produce it run the following command:
```powershell
clang <inputs like az_*.h> -Xclang -ast-dump=json -I ..\..\..\core\core\inc -I "c:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28801\include\" > az_core.ast
#powershell
Compress-Archive az_core.ast -DestinationPath az_core.zip
```
Upload the resulting `.zip` file.
> Accept zipped ast files

- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Python home path is set in env variable PYTHONHOME to make sure parser is using Python 3. Run parser using python in %PYTHONHOME%.
> Run python from path set in python home

- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Run apistubgen from installed script location. sys.executable wont be python when executing "apistubgen" so we need to find python path that is configured in APIVIEW_PYTHONHOME and install package to parse using it.
> Run python parser using python configured at PYTHONPROCESSORPATH

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckRunHandler.cs
Azure Pipelines is spamming check-run completion events for old runs and its causing us to hammer GitHub and get rate limited. We don't need to process these events so we can just ignore them. I arbitrarily set it so that we only process messages for Check Runs that started a day ago or less.
> Skip stale check-run events in Check Enforcer

- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
Changes:
1. Skip any modules that doesn't start with root module name (for e.g. azure) from importing 
2. Excluded known implementation methods from lint check
3. Fix issues in typehint parsing
> Add methods to skip lint check and fix typehint regex

- eng/common/scripts/artifact-metadata-parsing.ps1
This functionality relies on having the exception thrown. we'll still take advantage of maximumretrycount for certainty though
At this point we're only holding onto the `Invoke-WebRequest-WithHandling` for the API Rate limit output details. I'm waffling. I don't mind keeping this around (it's being used in locations talking to git), but it's also fairly pointless otherwise.
@praveenkuttappan 
> Resolve Broken Package Check Logic

- eng/pipelines/templates/scripts/verify-agent-os.yml
Reverts Azure/azure-sdk-tools#603
This is breaking pipelines so we are going to revert and do it differently.
> Revert "OSName variable set at run time"

- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/host.json
This PR introduces some logging to emit the ```WEBSITE_RESOURCE_GROUP``` environment variable in our telemetry because it doesn't appear to be getting populated on all nodes.
> Emit value of WEBSITE_RESOURCE_GROUP in logs.

- eng/common/pipelines/templates/steps/docs-metadata-release.yml
- eng/common/scripts/artifact-metadata-parsing.ps1
- eng/common/scripts/copy-docs-to-blobstorage.ps1
- eng/common/scripts/create-tags-and-git-release.ps1
- eng/common/scripts/update-docs-metadata.ps1
`docs` metadata does not care about the status of the tag/release. Given this, we don't want our call of `VerifyPackages` (which also gets the package metadata) to fail with that error.
> ContinueOnError Revisions for Docs Metadata

- eng/common/TestResources/remove-test-resources.yml
Using `succeededOrFailed()` because returning agents to the pool during a mass cancelation is more important than removing resources (the daily cleanup process will handle any resources left behind). 
Strong arguments could also be made for situations where a mass-cancellation may leave behind resources that have tighter quotas. To that point we have to weigh the collective agent time spent on removing resources automatically during a mass cancelation against having to manually clean up resources that fit this criteria in the wake of a mass cancelation.
> Add condition to always run resource cleanup step

- eng/common/scripts/copy-docs-to-blobstorage.ps1
The spring starter modules won't have sources which means that their javadoc will effectively be empty. This means that there won't be an index.html (which is what the github.io docs links to for each version) and if there isn't one there, output a message saying it's not being copied and continue to the next iteration of the loop.
> change for sourceless modules

- eng/common/scripts/update-docs-metadata.ps1
Resolves the following issues:
> Docs.MS Release Script - Stability Improvements

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/PullRequestHandler.cs
This PR makes processing of pull request events conditional on whether the action was ```opened``` or ```reopened```. We narrow down to these subset of event actions because they are the ones that should logically reset the PR.
In the case of reopened, we also want to re-evaluate the request as well. This PR closes #654
> Fix for pull request issue resetting pull requests.

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/PullRequestHandler.cs
This PR (merging immediately) fixes a logic bug with the last set of changes I made to Check Enforcer where it doesn't handle updates to PRs (which are signaled via the synchronize action via a PR event).
Thanks to @kurtzeborn for asking the question that made me take a closer look at this.
> Handle synchronize events in Check Enforcer

- eng/common/scripts/git-branch-push.ps1
Extend the template to also include NEW files during rebase and patch apply.
If the patch that is applied after rebase contains new files, the following:
` commit -am "$($CommitMsg)"`
Will not pick them up.  This PR swaps it to an explicit add all to handle this situation.
> Handle new files presence in Create-Pull-Request.ps1

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAnalyzerBase.cs
Fixes the regression introduced by #650
> fix regression in AZC0004

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/IssueCommentHandler.cs
This PR closes #616. Just trimming whitespace from issue comments before seeing if it is a ```/check-enforcer [action]``` command. Makes it more resilient to folks copying the command from somewhere with a leading or trailing space.
> Handle leading and trailing whitespace for comments.

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0002Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0003Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0014Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0015Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AzureAnalyzerTest.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/AsyncAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/BannedAssembliesAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Descriptors.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/SymbolAnalyzerBase.cs
Fixes: https://github.com/Azure/azure-sdk-tools/issues/641
Fixes: https://github.com/Azure/azure-sdk-tools/issues/573
> Add banned assemblies and method return type analyzers

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/IssueCommentHandler.cs
This PR is related to #629. Basically people who are using the Check Enforcer ```/check-enforcer reset``` command don't know to do an ```evaluate``` afterwards. This change makes both commands do the same thing.
I'll be removing references in our documentation around ```reset``` since ```evaluate``` is probably the way we want people to think about it moving forward.
> Combine Check Enforcer reset and evaluate

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Azure.Sdk.Tools.PipelineWitness.csproj
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Entities/AzurePipelines/Failure.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Entities/AzurePipelines/Run.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/RunProcessor.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/FailureAnalyzer.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/FailureAnalyzerContext.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/IFailureAnalyzer.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/IFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/TimeoutClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This PR provides the basic plumbing for automated failure analysis in Pipeline Witness. The way this works is that for every failed pipeline run we execute analysis of the build and timeline to see if we can automatically bucket the failure into predefined failure states (the implication here is that when we detect a new kind of failure state that we want to look into we would need to update the service).
The way it works is that I have a FailureAnalyzer which routes the build/timeline though a series of classifiers which determine whether they can register a failure against the run. If a new kind of "unknown failure" starts appearing in our reporting we can look into the symptoms and create a classifier for it and then over time get some kind of sense of how big of a problem it is (to …
> Pipeline Witness Failure Analysis

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/TestResourcesDeploymentFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
We had some test resource deployment failures in the net-pr pipelines overnight. This classifier will pick them up across multiple pipelines so we can see if it is a common problem. In this case I think it was just that our sub doesn't have the resource provider enabled.
/cc @danieljurek
> Add test resource deployment failure classifier.

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
- eng/common/pipelines/templates/steps/docs-metadata-release.yml
- eng/common/pipelines/templates/steps/publish-blobs.yml
- eng/common/scripts/Submit-PullRequest.ps1
- eng/common/scripts/copy-docs-to-blobstorage.ps1
- eng/common/scripts/create-tags-and-git-release.ps1
- eng/common/scripts/git-branch-push.ps1
- eng/common/scripts/update-docs-metadata.ps1
- scripts/powershell/update-docrepo-from-source.ps1
In particular for cases where we are only calling a script
we want to use the Powershell filepath version instead of inline
so that we get extra logging that shows the exact command that is
being called. This helps with reproducing issues if you need to
debug.
There have been a number of attempts to add lines at the top of our
powershell script that will echo out the command line used to call it
however unfortunately all our attempts have failed for one reason or
another.
- $PSCommandPath $args -> Only shows unbound arguments
- $MyInvocation.Line -> Only shows first line so calls spread over multiple
lines fail to show the full command. See https://github.com/PowerShell/PowerShell/issues/12609
The current attempt is to simply use the DevOps task with filepath which
shows the full command …
> Update pwsh calls to follow new PS tips

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/JavaPipelineTestFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This PR adds a classifier for the Java test failures. This PR depends on changes in [this PR](https://github.com/Azure/azure-sdk-for-java/pull/12224), but it can go in safely now and not cause any problems.
> Java test failure classifier.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/JsDevFeedPublishingFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/JsSamplesExecutionFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This PR adds classifiers for two kinds of failures we are seeing in the pipelines. One is for dev feed publishing (seeing a few of these). And the other is for a relatively uncommon (from what I can tell) failure to execute samples.
> Classifiers for two new kinds of JS failures.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/DownloadSecretsFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
We were getting a bunch of failures in our internal pipelines where Azure Pipelines was failing on the _Download secrets ..._ task. This PR adds a classifier for those errors so we can keep an eye on what is going on.
> Classify recent download secrets errors.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/JsDevFeedPublishingFailureClassifier.cs
Quick fix for filtering on the wrong job name.
> Typo in JS daily dev feed classifier

- eng/common/scripts/artifact-metadata-parsing.ps1
- eng/common/scripts/update-docs-metadata.ps1
All encountered in some fashion during the last set of releases.
> Small Docs.MS Release Bugfixes

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/DownloadSecretsFailureClassifier.cs
This PR changes the download secrets failure classifier to look for that sequence anywhere in the task name. It also corrects an error in the classification name.
> Correct typo and broader applicability.

- eng/common/scripts/create-tags-and-git-release.ps1
@chidozieononiwu - Please have a look
> Remove param validation from create-tags-and-git-release.ps1 that breaks C release

- tools/CreateRuleFabricBot/CreateRuleFabricBot/CommandLine/ActionType.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/CommandLine/Options.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/CreateRuleFabricBot.csproj
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Program.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/BaseCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/IssueRouting/IssueRoutingCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/CodeOwnerEntry.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/PullRequestLabelFolderCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBotTests/LiveTests.cs
This adds support in the tool that creates tasks for the Office bot for the task that adds labels to PRs based on the folders they are in.
The tool should be pointed at a CODEOWNERS file (urls not supported) and will create a task based on those.
The following are the limitations:
- Wildcards are not supported
- A single label per folder is allowed
To specify a label, add a `%LabelName` on the same line as the folder it applies to in the CODEOWNERS file.
Next steps after this is merged:
- Update the codeowners files in the repos where we want to enable this
- Update the documentation describing what is allowed in the CODEOWNERS file and the limitations noted above
- Creating the rules in the office bot for all the repos
/cc @weshaggard @mitchdenny @alzimmermsft 
Note: The syntax for using …
> Add support for creating task to label PRs in the office bot

- tools/CreateRuleFabricBot/CreateRuleFabricBot/Program.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/CodeOwnerEntry.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/PullRequestLabelFolderCapability.cs
Move the prompt a bit later in the process to allow for the task to output messages before creating the task.
Add better logs before creating the task.
> Fix an issue where paths without a label would lead to a crash.

- eng/common/scripts/modules/Package-Properties.psm1
Fix transient failure due to installing unregistered PSGallery repository.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=453244&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ac8f4042-9b76-5db4-27b1-2a4abaa9bb3c
> Fix Transient Error prior to Module Install

- packages/python-packages/api-stub-generator/setup.py
- packages/python-packages/doc-warden/README.md
- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/warden/enforce_readme_content.py
- packages/python-packages/doc-warden/warden/version.py
Need to do some additional smoke-test on `python 2.7`. OR I drop `python 2.7` support. I'm leaning that way right now.
> Handle BoM in Doc-Warden

- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
APIStubgen is not reporting any import failure properly. Any import module exception must be a hard failure. This was soft error earlier due to import of all folders( including non modules) in code repo with init.py and was causing storm of errors. This was already changed to import modules starting with root module name only but failure was not changed from soft error to hard error.
> Treat any import error during stubgen as hard error

- eng/common/scripts/modules/Package-Properties.psm1
Powershell-yaml is only needed for the 'Get-AllPkgProperties' function which right now is only used for local dev scenarios.
So scoping module installation to the function where it is used.
> Scope module Installation to only the function where it is used

- eng/pipelines/pipeline-generation.yml
The following PR changes the configuration for pipeline generator to stop generating from the ```dev``` branch for the ios repository.
> Change iOS pipeline generation configuration.

- eng/pipelines/pipeline-generation.yml
This PR removes iOS from the automatic pipeline generation process. Because the iOS repository just has the one pipeline, it is managed manually.
> Remove iOS from pipeline generation.

- eng/common/TestResources/remove-test-resources.yml
Partial https://github.com/Azure/azure-sdk-tools/issues/754 ... The `succeededOrFailed()` returns false in the case of a canceled build. This removes that criteria so we remove the resources on a canceled build. 
Since we don't have asynchronous resource deletion yet this synchronous step trades a few minutes of extra agent time for a more clean Test Resources subscription.
> Always clean up resources (runs during cancel)

- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
Import modules starts with root namespace.
> Skip importing metafolders by apistubgen

- eng/common/scripts/artifact-metadata-parsing.ps1
Before this update, **any** execution of the `GetExistingTags` method will hard error the script. I ran into this while testing releases for the new docs ci updates.
The code as-is legitimately won't work. To test, here's a version that has apiUrl substituted.
`(Invoke-WebRequest -Method "GET" -Uri "https://api.github.com/repos/Azure/azure-sdk-for-python/git/refs/tags"  -MaximumRetryCount 3 -RetryIntervalSec 10) | % { $_.ref.Replace("refs/tags/", "") }`
Execute that, notice that it errors. We can't directly use `Content` either. It's much easier to just use `Invoke-RestMethod` and get the content back ready for action.
`(Invoke-RestMethod -Method "GET" -Uri "https://api.github.com/repos/Azure/azure-sdk-for-python/git/refs/tags"  -MaximumRetryCount 3 -RetryIntervalSec 10) | % { …
> Fix Crashing GetExistingTags

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/BaseFunction.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInBacklogMilestones.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInPastDueMilestones.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindNewGitHubIssuesAndPRs.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindStalePRs.cs
This PR wraps all the GitHub Issues reports in a Polly policy that retries report generation at least 3 times with a spacing of 30 seconds. This is a crude attempt to get over some rate limiting issues. It may not work in production but it'll give us some insights into the next steps.
> Add retry logic for rate limiting exceptions.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/AzurePowerShellModuleInstallationFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This closes #825. We see periodic failures around the installation of the Azure PowerShell module. This will help us quantify it.
> Add PowerShell module install failure classifier.

- eng/pipelines/pipeline-generation.yml
This PR switches pipeline generation to generate pipelines off master instead of dev.
> Switch Android repo to pipeline generation on master

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/AzurePowerShellModuleInstallationFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/MavenBrokenPipeFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This PR adds a new classifier which pulls the logs for failed Maven tasks to determine whether they are actually a broken pipe issue (identified by a "Connection reset" message in the log output. This is the first classifier that leverages the fact that classifiers themselves are create by the DI container and can therefore access the various services to make outbound calls (such as ```BuildHttpClient``` via ```VssConnection```).
This PR is build on top of the branch for #835 which adds a PowerShell classifier, but they are otherwise unrelated (just avoiding some merge hassle).
> Detect Maven dependency download issues (broken pipes)

- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/tests/docstring_parser_test.py
APIStubGen is failing to parse any types that has space in it due to current regex being used. Fix includes a change in regex to find the type as well as to tokenize those types properly. Previously types were tokenized with asuumption that there is no space within type itself and this is not true if a Union type has Dict[<type1>, <type2>] is present.
> Fix type parsing issue for complex types

- eng/pipelines/pipeline-generation.yml
I can do this one of two ways.
1. Keep variable groups clean, add the `notifications` group to each build (this PR)
2. Add some of the secrets to an existing variable group, maybe the github.io one (updates in the variable groups only)
> Add Notifications Group to Pipeline Def

- eng/common/scripts/add-pullrequest-reviewers.ps1
@weshaggard Last 1:1 you asked me about the errors that could be thrown from the PR tagging operation. 
I was confirming that an unknown collaborator (aka someone who doesn't have `read`) won't fail the build.
When I was working through those tests, I discovered wonky performance. Someone who SHOULD have been added on a PR, didn't. This is the bugfixes that resulted.
> PR User Additions Should Actually Add

- eng/common/scripts/Verify-Links.ps1
Adding additional error codes check for link verification and checking inner exception codes for socket exceptions
Defaults to 400, 401, 404, SocketError.HostNotFound = 11001, SocketError.NoData = 11004
> adding additional error codes

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/MavenBrokenPipeFailureClassifier.cs
I noticed some null reference exceptions occuring in the Pipeline Witness telemetry:
The underlying exception is:
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException:
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__21.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, …
```
> Fix for null reference exceptions in Pipeline Witness telemetry

- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
This PR updates all the packages that Webhook Router users. I'm doing this because our telemetry shows a lot of failed dependency calls through ```Azure.Identity.DefaultAzureCredential```. This was a known issue where identity logged errors for normal execution.
I also decided to update all the other dependencies at the same time. Experience tells me that we need to run this code in the staging slot which is why I'm doing this on a feature branch of the upstream. Sometimes functions can break due to dependency updates so I want to run this feature branch with real load for a few days to just double check that it won't cause problems.
> Updated Webhook Router dependencies.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Azure.Sdk.Tools.PipelineWitness.csproj
This PR updates dependencies for Pipeline Witness. Mostly picking this up for ```Azure.Identity``` but bumping for other dependencies too. Deploying feature branch to staging because dependency updates can sometimes break with Azure Functions on a live host.
> Update dependencies for Pipeline Witness.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/MavenBrokenPipeFailureClassifier.cs
This PR fixes a bug in Maven broken pipe classifier. I managed to snag the exception by replaying the debug consumer group and found the error in my logic. This classifier is the first instance where I'm actually interrogating the task name (as opposed to the display name) because I'm looking for failures in Maven regardless of the actual step.
Anyway .. long story short, some steps/tasks can be in a failure state without the task value being populated, and that was causing me errors. In my case I just add a clause to filter those errors out.
> Fix null ref exception in Pipeline Witness.

- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
Enabling pre-commit sync of the `eng/common` directory to all for end-to-end testing of changes.
> Enable pre-commit eng/common sync

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/BaseReport.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Services/Configuration/ConfigurationService.cs
Introducing some more telemetry for GitHub issues. One of the things I'm keen to understand is what the limit reset is once we hit a rate limiting issue. If we are running close to the wire with the ```azure-sdk-bot``` account then we might want to consider cutting over to using a GitHub App registration.
> Improve logging for GitHub Issues.

- eng/common/README.md
- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/scripts/Submit-PullRequest.ps1
- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
Update eng common workflow and sync PR Body.
> Update Eng/Common Workflow

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/pipelines/templates/steps/get-pr-owners.yml
- eng/common/scripts/add-pullrequest-reviewers.ps1
My understanding after reading the github API docs was that the assignees setting was replaced by a push. It's actually additive, forgiving of duplicates. Adjust to push 1 at a time, turning the step _yellow_ when any fail to add.
> Update PR Tagging For Release Failures

- eng/common/scripts/artifact-metadata-parsing.ps1
Hold this until after release. The appropriate changes are already in place for the C repo.
> Remove PackageId from C release

- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
Root module name is set incorrectly when apistubgen runs against wheel. Change is to find root module name from top_level.txt.
> Fix issue in finding root module name from wheel

- eng/common/scripts/SemVer.ps1
- Change to beta instead of preview by default
- Allow customization of default prerelease label
- Allow customization of prerelease separators to support python version strings
- Add sorting helpers
cc @chidozieononiwu @danieljurek
> Update SemVer script

- eng/common/pipelines/templates/steps/get-pr-owners.yml
- eng/common/scripts/get-codeowners.ps1
- tools/notification-configuration/identity-resolver/Program.cs
Suggested by @weshaggard on #868 
Loved the suggestion, so adding this here.
> Simplify Identity Variable Extrapolation

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/GlobalConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IGlobalConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookOverEventHubsFunction.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubClientProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Startup.cs
This PR shifts construction of ```CryptographyClient``` and ```SecretClient``` into ```Startup.cs``` and shifts configuration that was previously in environment variables over into Azure AppConfiguration. I've also removed some of the caching logic since the cache does not provide stampede connection, and some of the secrets we don't need to worry about rotating between function node restarts.
I've also added some locks in there to avoid rushing KeyVault and other dependencies when the function starts on a large backlog of messages from Event Hubs. This is to avoid asking for the same keys/secrets multiple times when a node first comes up after a restart (if we have been down for a longer period of time the start-up could result in unnecessary failures from either KeyVault or GitHub).
> Check Enforcer improvements for DI and AppConfig

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/GlobalConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IGlobalConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookOverEventHubsFunction.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubClientProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Startup.cs
This PR shifts construction of CryptographyClient and SecretClient into Startup.cs and shifts configuration that was previously in environment variables over into Azure AppConfiguration. I've also removed some of the caching logic since the cache does not provide stampede protection, and some of the secrets we don't need to worry about rotating between function node restarts.
I've also added some locks in there to avoid rushing KeyVault and other dependencies when the function starts on a large backlog of messages from Event Hubs. This is to avoid asking for the same keys/secrets multiple times when a node first comes up after a restart (if we have been down for a longer period of time the start-up could result in unnecessary failures from either KeyVault or GitHub).
> Check Enforcer improvements for DI and AppConfig (#940)

- eng/common/pipelines/templates/steps/publish-blobs.yml
- eng/common/scripts/artifact-metadata-parsing.ps1
- eng/common/scripts/copy-docs-to-blobstorage.ps1
- eng/common/scripts/update-docs-metadata.ps1
**.NET:** 
[test pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=521467&view=results)
[Doc.MS PR](https://github.com/Azure/azure-docs-sdk-dotnet/pull/1358)
[github io 1](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Template/1.0.2-preview.15/index.html)
[github io 2](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Template/1.0.2-preview.15/api/index.html)
**Python:**
[test pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=522149&view=results)
[Doc.MS PR](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/784)
[github io](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-template/0.0.12/index.html)
**Java:**
[test pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=521081& …
> Initial changes on replace master link with release tag.

- eng/common/pipelines/templates/steps/verify-changelog.yml
- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/Verify-ChangeLog.ps1
- eng/common/scripts/common.ps1
Restructure changelog logic to remove reliance on modules and make use of `eng\common\scripts\common.ps1`
> Restructure Changelog Logic

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
Hide "Details" label when underlying link is not present.
> Hide details label if diagnostic error doesn't have any details link

- eng/common/scripts/artifact-metadata-parsing.ps1
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=531488&view=logs&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d
Newly created tag: https://github.com/Azure/azure-sdk-for-cpp/tree/azure-template_1.0.0-beta.2
> Fixed the bug of reading package name in cpp.

- eng/common/pipelines/templates/steps/docs-metadata-release.yml
This is an ask from Doc.MS release step. We want to create pull request with automation label.
Issue: https://github.com/Azure/azure-sdk/issues/1635
Added the `auto-merge` label for testing.
PR: https://github.com/MicrosoftDocs/azure-docs-sdk-node/pull/843
> Added automation for Doc.MS release step

- eng/common/scripts/update-docs-metadata.ps1
Fixed the bug of `update-doc-metadata.ps1` script which replace the title too aggressively. 
Issue: https://github.com/Azure/azure-sdk/issues/1674
Tested in local with python storage pkg.
> Fixed the aggressive title replacements

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
Log limit data when we receive a RateLimitExceededException.
> Check Enforcer rate limit logging improvement

- src/dotnet/APIView/APIView/CodeFileHtmlRenderer.cs
- src/dotnet/APIView/APIView/CodeFileRenderer.cs
- src/dotnet/APIView/APIView/CodeLine.cs
- src/dotnet/APIView/APIViewWeb/Client/src/documentation.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
Tag entire line as documentation if all tokens are within doc range. Instead of tagging each token as documentation start a span of documentation around tokens.
Instead of hiding documentation after loading, set them as hidden by default.
> API review perf issue when loading with documentation tags

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Startup.cs
This PR updates Check Enforcer to the latest Azure SDK dependencies. It also changes the way AppConfig is used to take advantage of the new API added in the latest release of the AppConfig API (allows you to ```AddConfigurationClient``` and take advantage of the pre-configured ```DefaultAzureCredentials``` rather than having to pass it in.
> Update Azure SDK dependencies in use new AppConfig API

- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Startup.cs
This PR moves the instantiation of ```ConfigurationClient``` and ```SecretClient``` into ```Startup.cs```. This is best practices for using Azure clients in ASP.NET Core/Functions. I still have the event hubs producer clients instansiated in ```Router.cs``` because I need to have a mapping from route ID to event hub client rather than just having one shared client across the entire app.
Also updated to all the latest Azure client bits.
> Use DI for AppConfig & KeyVault in Webhook Router.

- eng/common/scripts/update-docs-metadata.ps1
Introduce a bug of missing title.
Examples: https://github.com/Azure/azure-docs-sdk-java/pull/1230/files
Expect to see title there
The PR generated from testing template pipeline:
https://github.com/Azure/azure-docs-sdk-java/pull/1255/files
> Fixed the bug of missing title

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
- eng/common/pipelines/templates/steps/docs-metadata-release.yml
- eng/common/pipelines/templates/steps/replace-relative-links.yml
As part of an effort to make our templates work in other repos, like our private repos, we have a number of places were we need to remove the hard-coded repo names as part of that I've updated our common templates to default to the repo being built.
Once this goes in we will also need to make other changes in the language repo's to stop passing in hard-coded paths for the repo, see https://github.com/Azure/azure-sdk-for-java-pr/commit/d69194e6990f45ef2994fa6d4ade1dabc02031fc for my template tests in the java repo.
> Default the repo parameters to the repo being built

- eng/common/scripts/common.ps1
- eng/common/scripts/logging.ps1
Add logging functions to common location to enable reuse.
> Add Logging commands to common location

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ConsiderFinalClassDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingJavaDocDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/RequiredBuilderMethodsDiagnosticRule.java
Add diagnostic for warning about missing JavaDoc, and improve the builder methods diagnostic to support different expected APIs for HTTP and AMQP builders, and warn when expected methods are missing.
> [APIView] Java diagnostic updates

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/GitHubWebhookOverEventHubsFunction.cs
This PR logs the processing delays between enqueue time (over on Webhook Router) and being received by Check Enforcer. I want to get a sense of the time that things are spending in the queue.
> Log processing delays in Check Enforcer.

- src/dotnet/APIView/APIView/Model/CodeDiagnosticLevel.cs
- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_DiagnosticsPartial.cshtml
Changes to show border for diag messages and to fix padding issue. Previous change was setting background color at each <p> node that has messed the layout. I have updated this to group all diagnostic messages of same type and show it as row.
Reverted background color for error and updated warning color to lightyellow.
> Fix formatting issue for diagnostic messages

- src/dotnet/APIView/APIView/CodeFileHtmlRenderer.cs
- src/dotnet/APIView/APIView/CodeFileRenderer.cs
Move documentation html rendering into html renderer class. Currently html rendering is added in text render class and this is causing false diff when comparing revisions.
> Move HTML rendering for documentation into html renderer class

- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/tests/docstring_parser_test.py
Type parsing REGEX fails when type has "_" and if type is from private module names then module name will have _
> Fix parser error when type has private name

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Helpers/GitHubHelpers.cs
This PR adds rate limiting (1 request per second) for all outbound calls from the GitHub issues function to GitHub. The GitHub Issues function is getting hit by rate limiting because it does a bunch of queries in a very short space over time across multiple repositories. This will slow it down quite a bit bit make it less likely to fail.
> Add rate limiter to GitHub calls.

- eng/common/TestResources/deploy-test-resources.yml
Fixes #1028 
Example lacking Out-Null (scroll to the bottom of the logs) -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=523905&view=logs&j=b28a1a35-334b-5681-3876-e5562b5e8062&t=ff48ff62-22a8-5437-aae5-18a32a8994ec&l=237
Example with Out-Null (scroll to the bottom of the logs) -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=543132&view=logs&j=b28a1a35-334b-5681-3876-e5562b5e8062&t=85d3da62-e026-56d3-c19c-0f96227fb514&l=160
> Out null deployment

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/BaseReport.cs
This PR adds the same rate limiting recovery logic that we use in Check Enforcer (knowing how to use the backoff details in rate limiting/abuse exceptions). This is to stop the bleeding whilst the auth logic is swapped over to GitHub apps to get an increased/dedicated rate limit.
> Add rate limit recovery to GitHub Issues.

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/BaseReport.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInBacklogMilestones.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInPastDueMilestones.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindNewGitHubIssuesAndPRs.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindStalePRs.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/ReportExecutionContext.cs
This PR moves the retry logic down to the repo level so that we can retry individual repos without retrying (and spamming) everyone if we get stuck. It introduces a ```ExecuteWithRetryAsync(int, Func<Task>)``` method which is then wrapped around each iteration over the repository configuration entries.
I also moved to the the constructor injected logger infrastructure for the reports.
> Add retries at repo level

- eng/scripts/Verify-And-Merge-PRs.ps1
Consume DevOps Logging from eng\common\scripts\logging.ps1
> Consume DevOps Logging

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindCustomerReportedIssuesInInvalidStateFunction.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindIssuesInBacklogMilestonesFunction.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindIssuesInPastDueMilestonesFunction.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindNewGitHubIssuesAndPrsAt2pmFunction.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindNewGitHubIssuesAndPrsAt7amFunction.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindPRsOlderThan3MonthsFunction.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/BaseReport.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInBacklogMilestones.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInPastDueMilestones.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindNewGitHubIssuesAndPRs.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindStalePRs.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/ReportExecutionContext.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/host.json
This PR is an alternative to [this](https://github.com/Azure/azure-sdk-tools/pull/1040) (incomplete) PR. As I was implementing the GitHub apps auth model it dawned on me that if I retried on a per repo basis, with the back-off logic it would eventually go through rather than tripping up every time. 
I've been running this code in production of a few days and it is definitely behaving more reliably. Alas there is another issue impacting mail delivery (SengGrid IP pool is blocked as a spammer) - but that is a separate issue which may require changes to the way that we actually send e-mails.
Telemetry for this change though is looking good, we aren't getting rate limiting errors stopping report transmission (it recovers cleanly).
> GitHub rate limiting fix (via retries)

- eng/scripts/Verify-And-Merge-PRs.ps1
See break at https://dev.azure.com/azure-sdk/internal/_build/results?buildId=556899&view=logs&j=f6a7114c-32c6-5cc4-d467-98fb1350225d&t=a2695e80-e975-5318-3c29-d781630e749d
> Fix bad dot include of logging script

- eng/pipelines/templates/steps/sync-directory.yml
This replaces the `EngSys` label.
Fixes #1045
> Switch to auto adding the `Central-EngSys` label

- eng/common/scripts/logging.ps1
Use the correct syntax for debug logging in DevOps.
> Fix bug in DevOps logging command

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckRunHandler.cs
This PR filters out job notifications from processing to try and reduce the volume of messages that we are processing. It is a bit of a hack to make sure that we aren't getting multi-hour delays in processing. It should dramatically reduce the vollume of requests we make to GitHub.
The reason for not doing this is that there is always a chance of a dropped message from GitHub so I was using these messages as a way of making sure that we take every chance possible to inspect the GitHub state. But it just isn't scaling so this step is necessary.
> Ignore job notifications.

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckRunHandler.cs
This PR adds a new bail-out condition for ```CheckRunHandler``` which drops the message if the conclusion is neutral. We are seeing neutral conclusion events on merge commits where Azure Pipelines puts a neutral condition for lots of pipelines in the repo. These neutral conclusion events slide straight through and trigger evaluation which consumes valuable GitHub requests when in reality no one ever sees them and we can ignore them.
> Ignore neutral conclusion events.

- eng/common/scripts/copy-docs-to-blobstorage.ps1
Updated the existing ones using azure powershell.
Update the script here to make sure we update the cache-control for newly created blobs.
Fixed issue: https://github.com/Azure/azure-sdk-tools/issues/976
> Update cache-control for newly created blobs

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/README.md
Make the script easy to use locally:
Default to Out-File in .NET repo.
Default to username + servicedirectory as a basepath
Automatically login into `Azure SDK Developer Playground` if not logged in
Suppress extra output caused by returning variable locally
Auto-create service principal
Typical usage becomes `eng\common\TestResources\New-TestResources.ps1 search`
Fixes https://github.com/Azure/azure-sdk-tools/issues/541
Fixes https://github.com/Azure/azure-sdk-tools/issues/485
> Simplify New-TestResources usage

- eng/pipelines/eng-common-sync.yml
This step was still being tested. 
It should not have been checked in.
> Remove step intended to clean up sync branches

- tools/CreateRuleFabricBot/CreateRuleFabricBot/Helpers/CodeOwnerEntry.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Helpers/CodeOwners.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Helpers/CodeOwnersFile.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Helpers/FileHelpers.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Markdown/MarkdownTable.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Program.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/IssueRouting/IssueRoutingCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/PullRequestLabelFolderCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBotTests/CodeOwnerTests.cs
This is the first step towards the unification of the data sources for issue routing and PR labels for the Azure SDK repos.
We are going to add a comment in the CODEOWNERS file above the path representing the service with the set of labels that, when present, will ensure that the owners get tagged in the issue with those labels.
> Read issue routing from codeowners

- eng/common/scripts/Delete-Remote-Branches.ps1
- eng/common/scripts/Delete-RemoteBranches.ps1
- eng/common/scripts/Invoke-GitHubAPI.ps1
- eng/pipelines/templates/jobs/tools-cleanup.yml
- Add Cleanup pipeline.
- The intention is to run this on a schedule. The first step here is for cleaning up `eng sommon sync` branches.
> Add pipeline configuration for cleaning up upstream branches

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/CodeSigningFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This PR adds a failure classifier for Pipeline Witness. We experienced a burst of code signing failures overnight and I want to pull those errors out separately in our reports so we can quantify the impact over time. This classifier looks for any instance of the _ESRP Code Signing_ task that failed and reports it.
> Add a classifier for detecting code signing failures.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/MavenBrokenPipeFailureClassifier.cs
This PR adds some other strings to search for in logs which are related to dependency download issues in Maven.
> Make broken pipe classifier cover more scenarios.

- .github/CODEOWNERS
Spare Danny some GitHub inbox spam.
> Remove Danny from CODEOWNERS

- eng/common/scripts/copy-docs-to-blobstorage.ps1
Fixed the issue: https://github.com/Azure/azure-sdk-for-js/issues/11827
JS pipeline running super slow on array object of `Get-Content`.
Tested using -Raw, replacement works correctly and the entire process speeds up.
> Switch the content from array to string.

- eng/common/pipelines/templates/steps/verify-links.yml
This is the final step of link verification epic. 
Enable the link guidance check for all Ci pipelines.
The PR is pending for all lang PRs:
java: https://github.com/Azure/azure-sdk-for-java/pull/15285
net: https://github.com/Azure/azure-sdk-for-net/pull/15223
python: https://github.com/Azure/azure-sdk-for-python/pull/13846
js: https://github.com/Azure/azure-sdk-for-js/pull/11317
ios: https://github.com/Azure/azure-sdk-for-ios/pull/433
android: https://github.com/Azure/azure-sdk-for-android/pull/348
go: https://github.com/Azure/azure-sdk-for-go/pull/12541
cpp: https://github.com/Azure/azure-sdk-for-cpp/pull/632
c: https://github.com/Azure/azure-sdk-for-c/pull/1296
> Enable the link check for link verification step.

- eng/common/scripts/copy-docs-to-blobstorage.ps1
This is a follow up PR (https://github.com/Azure/azure-sdk-tools/pull/1103) which introduced extra new line at the end of the file. 
Local testing indicates we added new line at end.
Checked the github io, and it does not bring too many differences.
E.g.
After PR,
https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-template/1.0.9-beta.22/index.html
Before PR,
https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-template/1.0.9-beta.20/index.html
> Remove extra newline at the end of the file

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/PullRequestTimeoutFunction.cs
- tools/check-enforcer/CheckEnforcer.sln
This PR adds support for timeout behaviors in Check Enforcer. The way it works is that Check Enforcer will fire a function at a regular interval and read a list of pull requests that it has seen recently from Azure Storage (tables). It will then query that pull request to determine whether it has any check-runs, and if it doesn't, and add a comment with the contents of a markdown file from the source repository.
This will require a modification to the existing ```CHECKENFORCER``` configuration file to specify the timeout period. The markdown file will be discovered by convention ... ```CHECKENFORCER-TIMEOUT.md```.
Protections will need to be in place to make sure that Check Enforcer doesn't spam PRs with comments so the rule will be that if Check Enforcer has ever added a comment to a PR, …
> Check Enforcer timeout handling (WIP)

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/PipelineGenerationContext.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
This PR adds a ```--no-schedule``` option to Pipeline Generator. This switch will impact the ```up``` and ```tests``` conventions which are the only two that have schedules. We want this feature so that we can streamline pipeline creation from within a PR, but support it in our private repos where we definitely don't want scheduled pipelines created.
> Add --no-schedule option to Pipeline Generator.

- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
- eng/common/pipelines/templates/steps/prepare-pipelines.yml
This PR fixes up a bug in pipeline preparation where we are running the tool installer in the .NET repos root directory and the dotnet tooling complaining about the invocation being ambiguous. This works around it by creating a pipeline generator path and invoking the command in that working directory rather than the source root, or the pipeline workspace.
> Fix issue with .NET pipeline preparation.

- eng/common/pipelines/templates/steps/prepare-pipelines.yml
Replicating behavior from our main pipeline generator which will opt out of generating pipelines if there are no options specified.
> Add conditions to test pipeline generation.

- eng/common/TestResources/New-TestResources.ps1
The default parameter value is 'AzureCloud' but the parameter docs use 'PublicCloud', so this change changes the latter to the former.
Related to https://github.com/Azure/azure-sdk-for-net/pull/15258
> Update New-TestResources.ps1 parameter documentation to match defaults

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/pipelines/templates/steps/docs-metadata-release.yml
- eng/common/scripts/Invoke-GitHubAPI.ps1
Fixes bug introduced in create-pull-request.yml https://dev.azure.com/azure-sdk/internal/_build/results?buildId=584970&view=logs&j=7864f8e6-ba58-5c87-08d3-fc17566432db&t=41709476-b42b-5552-e853-f2ac4a3ad9de
Depends on 
Azure/azure-sdk-for-net#16145
Azure/azure-sdk-for-js#11986
Azure/azure-sdk-for-java#16657
Azure/azure-sdk-for-python#14686
> Fix create-pull-request bug

- eng/common/pipelines/templates/steps/docs-metadata-release.yml
Have a PR submitted to the docs team that allows for non-conflicting commits. We can definitely get rid of smoke-test now.
Docs CI will also need to be updated, but that happens separately from this PR.
> Retarget master as the base branch for docs metadata release

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/Remove-TestResources.ps1.md
Changes necessary for testing against Managed HSMs and Key Vaults.
Managed HSMs require extra steps in the post-script that must run
as the provisioner.
Also some general clean up and style consistency.
Related to https://github.com/Azure/azure-sdk-for-net/pull/16204
> Always run pre- and post-scripts as provisioner

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/IRepositoryConfiguration.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfiguration.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Functions/PullRequestTimeoutFunction.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/PullRequestHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/IPullRequestTracker.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/PullRequestTracker.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/PullRequestTrackingTicket.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Startup.cs
- tools/check-enforcer/CheckEnforcer.sln
This PR adds a pull request tracker for the purpose of adding comments to PRs where a check run has not executed. This implementation does not use any durable state. I'm planning on rolling this out as is just to validate the overall flow in our production environment. Once that is validated I'll submit another PR that adds the durable state, so until that is done it may occasionally skip adding a comment.
I've validated the current approach here and ensure we don't get duplicate comments added:
https://github.com/Azure/azure-sdk-tools/pull/1141
The solution is composed of a few elements:
1. Pull Request Tracker; a component which keeps track of pull requests that we want to look at.
2. A timer function that fetches the list of pull requests we are looking at and processes them (with …
> Check Enforcer timeout

- src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
- Generate unique name for methods
- Hide methods from navigation tree
- Hide ::details namespace
- Add namespace to global methods
- Fix navigation issue by linking to correct navigateToId
> Fix issues in C++ APIview navigation and private members

- eng/common/TestResources/Remove-TestResources.ps1
Since we have background jobs that poll for zombie resource groups already, we don't need to block on resource group deletion. This should save us a couple minutes in our live test pipelines.
Example improvement on a test pipeline (the step takes 4 seconds now):
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=593112&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043
I also verified in the activity log that we had a successful deletion event.
Resolves #754
> Remove resource group asynchronously and do not wait for completion

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/PullRequestHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/PullRequestTracker.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Services/PullRequestTracking/PullRequestTrackingTicket.cs
This PR adds non-volatile state tracking to Check Enforcer. This replaces the existing in-memory implementation. The overall design of this is that we should be able to drain the list of pull requests that are being tracked in this storage pretty quickly.
> Add non-volatile state tracking to Check Enforcer

- eng/common/scripts/git-branch-push.ps1
- eng/pipelines/templates/steps/sync-directory.yml
Fix bug in git-branch-push.ps1
> Fix bug in git branch push

- eng/common/TestResources/New-TestResources.ps1
This also adds previously-required parameters back into
@PSBoundParameters to pass down to pre- and post-scripts.
> Make sure we always log in as app or provisioner

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/CodeSigningFailureClassifier.cs
I was using the display name for the code signing task not the task name itself, so it wasn't classifying correctly.
> Fix to code-signing classifier.

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/deploy-test-resources.yml
This change simplifies cloud configurations in our live test pipelines. Currently these parameters get defined per cloud in the live test template, which ends up creating a large, verbose configuration. To simplify these definitions, I'd like to move them into the subscription configuration. The resulting template usage becomes more like:
```
- name: CloudConfig
type: object
default:
Public:
SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
Preview:
SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
Canary:
SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
Location: 'eastus2euap' …
```
> Update subscription configuration schema to include new parameters

- README.md
- doc/README.md
- doc/common/common_engsys.md
- eng/common/README.md
Move Common Engineering System Doc to main README.md Doc.
Add information for how to structure unique language logic.
> Refactor eng/common/README.md

- eng/common/TestResources/New-TestResources.ps1
There are some ARM deployment errors that do not surface adequate messages for debugging in the default error output. For example issues related to template validation (that can be a result of account quotas, invalid names, etc.):
```
WARNING: Attempt 1 failed: Exception calling "Invoke" with "0" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:
07:13:02 - Error: Code=InvalidTemplateDeployment; Message=The template deployment 'benbp-foobar' is not valid according to the validation procedure. The tracking id is '182f1217-fa54-4fa8-bff3-ef74605e2fe9'. See inner errors for details.
``` 
By updating the `$DebugPreference` for the `New-AzResourceGroupDeployment` command, we print the inner error messages …
> Add debug flag to arm deployment command

- eng/common/TestResources/New-TestResources.ps1
Fixes https://github.com/Azure/azure-sdk-tools/issues/1189
This fixes a bug where a username may contain spaces or other invalid characters, e.g.
```
(py39_new) PS C:\github.com\azure-sdk-for-python> .\eng\common\TestResources\New-TestResources.ps1 'schemaregistry'
New-TestResources.ps1: The variable cannot be validated because the value Sean Kaneschemaregistry is not a valid value for the BaseName variable.
```
> Remove invalid characters in basename sourced from username

- eng/common/scripts/Verify-Links.ps1
- eng/common/scripts/get-markdown-files-from-changed-files.ps1
Test PR: https://github.com/Azure/azure-sdk-for-java/pull/17233
Test pipeline with the new scripts in Urls: https://dev.azure.com/azure-sdk/public/_build/results?buildId=610176&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0
Test pipeline with original Urls paramaters: https://dev.azure.com/azure-sdk/public/_build/results?buildId=610157&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0
> Preprocess the markdowns contain deleted or renamed files.

- eng/common/TestResources/deploy-test-resources.yml
This reduces the default from 24 hours to 8 hours. The cleanup pipeline takes only a few minutes so this shouldn't add any load: https://dev.azure.com/azure-sdk/internal/_build?definitionId=1357&_a=summary
The original 24 value was arbitrary. I'm picking 8 because it's the lowest value that's safely longer than any of our existing live tests (currently storage takes 6 hours).
Related to https://github.com/Azure/azure-sdk-tools/issues/754
> Change live test resource DeleteAfterHours tag to 8 hours

- eng/common/TestResources/New-TestResources.ps1
Available information currently gets logged on failures with ARM template provisioning, but we should provide a link to help people who want to debug further or understand what is going wrong.
> Add debugging link on resource deployment failures to log output

- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter.Administration/New-AzureDevOpsRuleCredentials.ps1
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Functions/RouteWebhookFunction.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/AzureDevOpsRule.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/RouterAuthorizationException.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Startup.cs
This PR adds ```Authorization``` header checks to the Azure DevOps routing rules. We store a hash and salt in KeyVault for each routing rule. The hash is a combination of the ```base64(username:password)``` part of the header combined with the salt which is then SHA256 hashed and base 64 encoded.
This also fixes a bug where we were validation GitHub signatures but not throwing if signature validation failed (note this is mitigated by the fact that we were also validating in Check Enforcer correctly).
Things left to do:
> Add auth header checks to DevOps rule.

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
APIStubGen is skipping classes in microsoft root namespace. PR is to check for namespace based on parsed namespace.
> Removed hardcoded root name space check for azure namespace

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/DiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ConsiderFinalClassDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/FluentSetterReturnTypeDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/IllegalMethodNamesDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/IllegalPackageAPIExportsDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ImportsDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingAnnotationsDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingJavaDocDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/NoPublicFieldsDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/PackageNameDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/RequiredBuilderMethodsDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/UpperCaseNamingDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
This PR contains improvements to the APIView tooling, including:
* Fixing an issue where module-info was duplicating definition IDs
* Adding extra review metadata to support upcoming improvements to APIView (language, package name, and package version).
* Add support for a final end-run of diagnostics, after all files have been processed. This allows for other types of diagnostics where we need to know information about all of the types in the library. This has already been used in the subtype checking, so that we don't warn about missing 'final' keywords in places where there is a known subclass in the same library. 
This **should not** be merged until APIView is ready to work with the new metadata.
> [APIView] Java improvements to APIView

- src/dotnet/APIView/APIViewWeb/Languages/CLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/ts/ts-genapi/export.ts
- src/ts/ts-genapi/models.ts
- src/ts/ts-genapi/package.json
Package name is required to find master review for each package and this needs to be set by each language. Also made a change to filter C++ review based on the namespace.
> Set Package name for C++, C and JS and filter review to namespace for C++

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- packages/python-packages/api-stub-generator/apistub/_version.py
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Change to include python package name and version in review to support finding a review for a package.
> APiView changes to add package name and version for python in review

- eng/common/pipelines/templates/steps/bypass-local-dns.yml
- eng/common/pipelines/templates/steps/verify-agent-os.yml
The bypass-local-dns check fails when running in a container (and is unnecessary since we aren't using the pipelines agent image), so this adds another step to the condition to exclude it. This requires the container being set specifically with a `Container` variable.
> Exclude bypass-local-dns step when a container variable is specified

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
> Add "weekly" convention to pipeline generator

- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/RouteConfigurationException.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
This PR changes Webhook Router so that when a payload is received that doesn't match a known route that the payload is logged so that it can be used to track down where the event is coming from. At the moment we don't have any mechanism to find sources of routed events when we are dropping them short of looking through all of our repositories to try and find them. This should make diagnosis much easier.
The reason I am doing this is that over the past week or so we've seen some routing failures and I haven't been able to find the source. I'm concerned that there is a routing rule missing that I haven't previously considered.
> Webhook Router: Payload output on routing errors

- eng/common/pipelines/templates/steps/docs-metadata-release.yml
- eng/common/scripts/update-docs-ci.ps1
- eng/common/scripts/update-docs-metadata.ps1
Current.
```
<doc repo root>/
docs-ref-services/
storage-blob-readme.md
storage-blob-readme-pre.md
```
New
```
<doc repo root>/
docs-ref-services/
latest/
storage-blob-readme.md
preview/
storage-blob-readme.md
```
This is enabled by [docfx updates](https://github.com/MicrosoftDocs/azure-docs-sdk-node/commit/a01c7619aababf83881804f4c08130075621a0f4) that change our publishing to pull from the **different folders** but write to the _same URL PATH_. 
The outcome of this + the SyncToC update + other updates to release configs is that we will be able to swap between monikers as expected!
> Support moniker specific folders for readmes (and incoming service overviews)

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/AzuriteInstallFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This PR looks for failures in the Install Azurite install task. At this point its just looking based on the task display name. Once we get enough of these occurring we might be able to write one that picks up the underlying NPM error for a broader set of tasks. The trick is to do it in an efficient way so we don't have to always pull all of the log entries for a run.
Fixes #1237
> Classifier for Azurite install failures.

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/NoLocalesInJavadocUrlDiagnosticRule.java
1. Add new diagnostic rule that checks if URLs have locale language tags in them (e.g. 'en-us').
> [APIView] Misc Java-specific improvements

- eng/common/docgeneration/Generate-DocIndex.ps1
- eng/common/docgeneration/templates/matthews/styles/main.css
- eng/common/docgeneration/templates/matthews/styles/main.js
.NET individual sdk link missed the css for version dropdown effect. Added back to make sure .NET is working as expected. The changes do not affect other langs.
The PR is pending for: https://github.com/Azure/azure-sdk-for-net/pull/17400
> Make up the css using for .net sdk github io pages

- scripts/python/docs-automation/sync_tocs.py
Currently, some of the spring boots packages do not render anything out since they are not GA.
The fix is to remove if there is no items and href under toc.
https://review.docs.microsoft.com/en-us/java/api/overview/azure/springboot/cosmosdbstarter?view=azure-java-stable&branch=master
Fixed issue: https://github.com/Azure/azure-sdk-tools/issues/1269
> Fixed the edge cases of spring boot packages.

- eng/common/pipelines/templates/steps/docs-metadata-release.yml
We did not observe OPS build issue recently. The migration actually solves the build time and build error problems at the same time. We can move forward with smoke-test deprecation work.
> Create PR to target against master

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs
Fixes #1255 
This PR adds a filter to only show issues (and not PRs) in the customer issues in an invalid state query. The key change here is setting the ```Type``` property on the search request which narrows down the scope.
> Filter PRs from search for invalid customer issues.

- eng/common/pipelines/templates/steps/docs-metadata-release.yml
Like the errors seen in [this release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=646170&view=results)
> Resolve git longpath error when applying documentation updates

- eng/common/pipelines/templates/steps/docs-metadata-release.yml
**Issue to solve**: Spring boot starter packages has no API documentations, so the Java Doc CI build failed to retrieve the documentation. Synced with Spring team, they expect to have readme only in Overview page without API. 
e.g: https://review.docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-cosmos-readme-pre?view=azure-java-preview&branch=smoke-test
Currently, we manually do the updates. 
**Purpose of the PR**: Add a variable which passes through `ci.yml` to skip updating `package.json`, so we only update readme through the release pipeline. That's how we pass the Java CI build and achieve the purpose of displaying readme only in Dos.Ms for spring boot starter packages.
Tested PR: https://github.com/Azure/azure-sdk-for-java/pull/18077
Tested in pipeline: …
> Added a step of skipping package json update for spring boot packages

- eng/common/scripts/SemVer.ps1
This PR updates the semver tooling to support our dev feed formats like:
```
5.3.0-alpha.20200928.3
2.0.0a20201208001
```
Supporting this format will enable us to sort release feeds that contain alpha releases, primarily so we can target smoke tests against the latest nightly and/or preview release, where applicable. Currently the smoke tests (at least for .net) have a bug where they are testing against very old dev releases, since they just pick the last item in the API response.
> Support alpha and azure pipeline build version formats for SemVer parsing and sorting

- eng/common/docgeneration/templates/matthews/styles/main.js
The page currently looks like:
The changes applied to all lang repo.
After apply the fix:
> Fixed the bug of replacing img src with href text

- tools/CreateRuleFabricBot/CreateRuleFabricBot/CreateRuleFabricBot.csproj
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Helpers/CodeOwnerEntry.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/BaseCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/IssueRouting/IssueRoutingCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/IssueRouting/TriageConfig.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/PathConfig.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/PullRequestLabelFolderCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Service/RequestSender.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBotTests/CreateRuleFabricBotTests.csproj
- tools/CreateRuleFabricBot/CreateRuleFabricBotTests/PayloadTests.cs
The following improvements have been made:
- Introduce a base class for the capabilities types
- This base class is responsible for calling the method to read the configuration from the configuration file. Each derived class will need to implement that method.
- Tests have been added to ensure that the payloads that we generate are in the expected shape.
- Simplify the code to generate the payload. Instead of using string templates and doing string replacement for tokens, we are now generating `JObject` objects that represent the payload
- This does mean that we are taking a dependency to Newtonsoft.Json for creating JSON objects but there isn't a good alternative to do the same using System.Text.Json
-  The code for describing an entry for the PR labeler is moved to a new file, similar …
> Improve rule bot code

- eng/common/scripts/Delete-RemoteTag.ps1
- eng/pipelines/git-tasks.yml
This PR contains the YAML and supporting script for a new pipeline called ```tools - git-tasks``` which can be used to perform privileged operations against our Git repositories. This closes the following issue: https://github.com/Azure/azure-sdk-tools/issues/1101
The approach I've taken is a single centralized pipeline in the ```azure-sdk-tools``` repository where you can select the task you want to perform (currently the only one present is _DeleteTag) then provide the appropriate arguments to support that operation (in this case the repo and tag name).
This YAML file then calls a PowerShell script which in turn makes use of the existing ```Remove-GitHubSourceReferences``` implementation in the ```Invoke-GithubAPI.ps``` script.
Finally - because this is a destructive operation, I've put …
> Creation of tools - git-tasks pipeline

- eng/common/scripts/Update-ChangeLog.ps1
- This makes sure most of behavior is same as eng\common\Update-Change-Log.ps1 with better handling for out side of normal use cases.
> Updates to Update-Changelog.ps1

- eng/pipelines/pipeline-generation.yml
This PR does two things:
1. Adds the resource provisioning secrets to the unified pipeline, in order to enable running smoke tests after release via this pipeline.
2. Adds a sanitized keyvault name mapping to the variable groups, so it's a little easier to see which pipelines need which variables (as opposed to just variable group numbers).
In support of https://github.com/Azure/azure-sdk/issues/1999
> Add resource provisioning variables to UP pipelines and improve readability

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/SemVer.ps1
- eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
- Add set of helpers to work with devops work items
- Add script to create devops release package items
- Update SemVer to support version type
@chidozieononiwu here is the helper scripts we need to use in the Prepare-Release scripts to create the release workitems.
fyi @czubair this is this script that we can start using to create the devops work items
Usage:
For existing package
```
.\eng\common\scripts\Update-DevOps-Release-WorkItem.ps1 "<language>" "<package_name>" "<package_version>" [-plannedDate 5/01/2021]
```
Language, package name, and version are all required. If the plannedDate is not set it will use today's date.
For new packages
```
.\eng\common\scripts\Update-DevOps-Release-WorkItem.ps1 "<language>" "<package_name>" "<package_version" -packageDisplayName …
```
> Add Devops Release Item scripts

- eng/common/scripts/copy-docs-to-blobstorage.ps1
We currently do not support one generic link for latest GA version doc.
The PR is to update the index.html to redirect to the latest GA version, if no GA version, then redirect to latest preview. 
The template has been updated.
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-sdk-template/latest/index.html
https://azuresdkdocs.blob.core.windows.net/$web/python/azure-template/latest/index.html
https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Template/latest/index.html
https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-template/latest/index.html
> Update latest folder with one index.html includes the redirect links

- eng/common/scripts/update-docs-ci.ps1
- eng/common/scripts/update-docs-metadata.ps1
Then, on the dotnet release specifically, I'll config the `preview` config to add `-pre`, then flatten the destination folders for both `latest/` and `preview/`.
> Allow configuration of a suffix for each config item

- eng/common/Update-Change-Log.ps1
- eng/common/scripts/Update-ChangeLog.ps1
Reverts Azure/azure-sdk-tools#1301
Update-Change-Log.ps1 is still needed for some other Repos.
> Revert "Remove old Update-Change-Log.ps1"

- eng/pipelines/pipeline-generation.yml
Because `TestOptions` was not defined as a matrix variable for all entries, it was causing the `$(TestOptions)` variable substitution to skip, and being treated as a literal argument, which was failing some pipelines. This adds TestOptions to all pipeline matrix entries, as empty for those that don't need access to the resource provisioning secrets, and as a variable group argument where needed (like the other matrix entries).
> Add missing TestOptions matrix variable in pipeline-generation.yml

- NuGet.Config
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/SdkComponentScanner.cs
This change adds variant support for our existing tests pipelines that @jsquire is trying to use to split up T1 and T2 tests in .NET eventhubs and servicebus.
> Support variants in test pipelines

- src/dotnet/APIView/APIViewWeb/Client/src/main.ts
- src/dotnet/APIView/APIViewWeb/Client/src/review.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
Some packages has huge number APIs which makes it difficult to find the diff from different revision within these files when only few lines are changed. This enhancement is to add a new checkbox in options menu so user can select this option to see difference only.
> Add new option to show only diff

- eng/common/pipelines/templates/steps/bypass-local-dns.yml
This fixes an issue where the DNS bypass workaround was not getting run for the new 1es pool ubuntu images.
FYI @mitchdenny @alzimmermsft @samvaity
> Ensure bypass conditional template gets run for 1es ubuntu image

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
Return created or pending review URL in response so it can be shown in CI logs. This will be helpful to pinpoint which review needs to be approved.
> Return review URL in response to auto API review create request

- eng/common/pipelines/templates/steps/get-pr-owners.yml
I want to update the build that generates [this release](https://github.com/Azure/azure-sdk-tools/releases/tag/azure-sdk-tools_20210106.1) to update the tag in place, but I need to run down the location.
> Docs Gen Pulls Tools from Tag

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/SemVer.ps1
- eng/common/scripts/Update-ChangeLog.ps1
This change is to accommodate parts of the changelog that does not properly indicate the release status as specified in the [changelog guideline](https://aka.ms/azsdk/changelogguide).
This also switched the logic to use Ordered HashTable so as not to rely on SemVer sorting. This allows us accommodate version that are not SemVer compliant.
> Update Changelog Logic to accommodate older entries 

- tools/notification-configuration/common/Helpers/StringHelper.cs
- tools/notification-configuration/common/Services/AzureDevOpsService.cs
- tools/notification-configuration/common/common.csproj
- tools/notification-configuration/github-codeowner-subscriber/github-codeowner-subscriber.csproj
- tools/notification-configuration/identity-resolver/identity-resolver.csproj
- tools/notification-configuration/notification-creator/NotificationConfigurator.cs
- tools/notification-configuration/notification-creator/notification-creator.csproj
Set TargetFramework netcoreapp2.0 -> netcoreapp3.1 so it builds on devops machines. There is no specific reason to keep using older versions.
> Fix notification tools

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/RequiredBuilderMethodsDiagnosticRule.java
This PR adds `AzureSasCredential` as a valid type for `credential()` method overload on the client builder.
> Include AzureSasCredential as allowed type for credential builder method

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
Fixes #1352 
This PR resolves an issue where non-scoped inner classes of public interfaces weren't included in the ApiView. In Java non-scoped inner classes, and non-scoped properties, of public interfaces are part of the public API.
> Include Non-Scoped Inner Classes from Public Interfaces

- eng/common/scripts/Create-APIReview.ps1
- eng/common/scripts/Save-Package-Properties.ps1
Java API review create step requires additional artifact sub directory param. This will help in using generic artifact path to look for config files.
> Support sub directory for artifact location

- eng/common/pipelines/templates/steps/cosmos-emulator.yml
* Updated cosmos emulator yml script to remove the existing installation, install latest version and run emulator with latest version
> Updated cosmos emulator yml script

- src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
C++ namespace has sub namespaces and class definitions at same level in some cases For e.g. Azure::Keyvault:Keys has a sub namespace ::Details as well as some class definitions. Currently code is skipping this subtree when it finds "Details" namespace. Fix in this PR is to fix only Details subtree and add remaining definitions at that level.
> Include all classes in namespace and skip only Details namespace

- eng/common/docgeneration/Generate-DocIndex.ps1
This is a follow up PR for https://github.com/Azure/azure-sdk/pull/2305/files.
If we have duplicate artifact names, we currently only check the first artifact set `Hide` to `true` or `false`. 
Expect behavior, we iterate all duplicate artifacts and leave the one with `Hide` to `false`
> Scan all duplicate artifacts which set hide to true

- src/go/cmd/api_view_test.go
- src/go/cmd/content.go
- src/go/cmd/output/testconst.json
- src/go/cmd/token_builders.go
Skip adding const type for basic literals, unary and binary expressions.
> Do not add certain const types to token list

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ModuleInfoDiagnosticRule.java
This PR adds diagnostic rules for `module-info`. This validates the following two Java guidelines:
- [Do include module-info.java for each module you ship](https://azure.github.io/azure-sdk/java_introduction.html#java-module-info)
- [ DO name your module based on the root package of the client library it represents.](https://azure.github.io/azure-sdk/java_introduction.html#java-module-name)
> Add diagnostic rules for module-info

- eng/common/docgeneration/Generate-DocIndex.ps1
We currently expose the hide package out to other page. It is supposed to be hidden from github io.
This is the fix for the feature.
> Hide the package which set to true instead of putting to Other page

- eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
- eng/common/scripts/Invoke-GitHubAPI.ps1
Extend `eng/common/scripts/Invoke-GitHubAPI.ps1:Get-GitHubPullRequest` to return files in a given pull request.
Add pipeline to prevent changes to `eng/common` that don't follow the workflow from being merged in
> Add eng/common break check

- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
Reverts Azure/azure-sdk-tools#1398
For some reason this seems to have cause the PR validations stop triggering
e.g https://github.com/Azure/azure-sdk-tools/pull/1307
> Revert "Update repos sub parameters"

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/README.md
Resolves #1388
Resolves #1407
Also ignores cached service principal if it no longer exists. I ran into this while testing since I cleaned up old SPs.
> Improve TestResources docs and logging

- eng/common/pipelines/templates/steps/create-apireview.yml
- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/Save-Package-Properties.ps1
Generate config property file using artifact name
> Create package property file using artifact name

- src/dotnet/APIView/APIViewWeb/Models/ReviewRevisionModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
- Approve automatic review when manual review is approved if they match at API surface level
- Search for approved manual reviews whenever new automatic review is created and mark it as approved automatically.
> Approve automatic reviews if approved manual review matches

- eng/pipelines/pipeline-generation-single.yml
- eng/pipelines/pipeline-generation.yml
This PR disables the security analysis warning about NuGet.config files. This is because this pipeline doesn't actually use NuGet.config to install packages. Instead it downloads from public Azure Artifacts registry (and the package is suffixed with Azure.*)
> Disable NuGet sec analysis error.

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
The default non-variant suffix is `tests` when it should be `tests-weekly` in the pipeline generator weekly convention.
> Fix non-variant default name for tests-weekly

- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Updating the pipeline install tool to use the version published for https://github.com/Azure/azure-sdk-tools/pull/1435
> Update pipeline generator version to include weekly convention name fix

- eng/common/pipelines/templates/steps/verify-agent-os.yml
- eng/common/scripts/Verify-AgentOS.ps1
The PR https://github.com/Azure/azure-sdk-tools/pull/1371 removed functionality that made the agent OS variable available to subsequent jobs in the pipeline. This variable is still used in several places for job and file display names, so this change re-introduces it.
> Restore pipeline output variable for Agent OS name

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/Prepare-Release.ps1
- eng/common/scripts/common.ps1
- eng/common/scripts/logging.ps1
- Remove BuildType parameter as we can default it from package properties
- Stop passing BuildType and GroupId and instead defaul them from package properties
- Enable StrictMode to help identify potential errors
- Start passing sdktype and isnewsdk properties to devops script
- Sync latest changes with devops work item to fix a couple bugs
Once https://github.com/Azure/azure-sdk-for-java/pull/19495 is merged and we merge this change the buildtype and groupid for java will come from the package properties.
> Update Prepare-Release script

- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Update automatic reviews also in the background. This is one time update after system restart(which is usually after new deployment)
Automatic reviews are currently attempted to update during auto review creation and this leads to longer delay and request time out. This PR has a change to update automatic reviews in background to latest parser version in the same way manual reviews are handled and avoids attempting to update again during auto review creation.
> Auto update all reviews in the background after parser is updated

- eng/common/scripts/Create-APIReview.ps1
Updated logging in create review step
> Added more logging to API view create

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Temporary work around to unblock releases. We will make a permanent solution to support these maven properties in API review
> Disable maven dependency properties from API review temporarily

- eng/common/scripts/job-matrix/job-matrix-functions.ps1
- eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
When importing a matrix from another matrix, the intended behavior is that any duplicate parameter keys favor the value in the matrix doing the import. This PR fixes a bug where this did not happen (instead the imported matrix's value is favored).
> Fix bug where imported matrix parameter duplicates are not overrided

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
Now that we have the majority of Azure SDK pipelines running on the 1ES pools and we have better capacity to scale, this PR adds back the CI triggers so that once a merge is completed that we get a CI run. This will help narrow down build failures in pipelines that occur post merge whereas at the moment it can sometimes take some digging to figure out what particular change introduced a problem.
> Add CI trigger back to pipeline generator

- eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
- eng/common/pipelines/templates/steps/sparse-checkout.yml
- eng/common/scripts/job-matrix/samples/matrix-test.yml
From a functional standpoint, the generate matrix job only takes a few seconds to run. Depending on the repository, the job can take a total time of 4 minutes before the test jobs are able to start, because azure pipelines does a clone of the entire repository (among other things). This PR makes a change to skip the azure pipelines checkout step, and add a lightweight git clone along with a sparse checkout of just the `eng` and service directory locations (which contain the matrix scripts and/or matrix configs).
This change reduces the total job runtime to around 20 seconds from 4 minutes (repo checkouts + auto-injected policy steps).
> Use sparse checkout for generate matrix job

- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Pipeline Generator has been updated to support generating CI triggers for public pipelines. This PR moves the version of pipeline generator we use to this new version. This will impact the scheduled pipeline generation job, as well as the single generation job and the prepare pipelines jobs.
> Use latest pipeline generator

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/SemVer.ps1
> Sort changelogs by date then version

- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
API stub generator includes classes in stub file only if class's module name matches module name space. This causes APIview to skip any classes defined in internal modules but added them in __all__ of public module to make it publicly accessible. Fix in this PR is to ensure module of class starts with package root name rather than namespace of module itself.
For e.g. SearchIndexerSkill is defined in `azure.search.documents.indexes._internal._generated.models._models_py3.SearchIndexerSkill` But this class is added in __all__ `azure.search.documents.indexes.models`. Currently this class is not included because comparison is between `azure.search.documents.indexes._internal._generated.models._models_py3` and `azure.search.documents.indexes.models`.
Fix in this PR will change it to ensure …
> APIStubGen skips public classes defined in internal modules

- eng/common/scripts/Collect-ChangeLogs.ps1
This fix ensure that ChangelogUrl is correct for JS (as well as Java, Python, and dotnet)
> Fix bug in Changelog URL path using packageDirectoryName

- eng/common/pipelines/templates/steps/publish-artifact.yml
This allows us to prevent duplication of an artifact upload in the case where there are build failures earlier in the `Build` stage.
> Add publish-artifact.yml

- eng/common/scripts/Package-Properties.ps1
Pull only artifacts from `ci.yml` to resolve issue with conflicting package names.
> Revert to Checking only ci.yml

- eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
- eng/common/scripts/job-matrix/Create-JobMatrix.ps1
- eng/common/scripts/job-matrix/README.md
- eng/common/scripts/job-matrix/job-matrix-functions.ps1
- eng/common/scripts/job-matrix/samples/matrix-test.yml
- eng/common/scripts/job-matrix/samples/matrix.json
- eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
- eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
- eng/common/scripts/job-matrix/tests/test-import-matrix.json
This PR adds a replace operator to the matrix config, enabling flexible ways to replace values from a matrix via a command line syntax similar to the `-filter` syntax: `<keyRegex>=<valueRegex>/<replaceWith>`, e.g.
```
MatrixReplace:
- OsVmImage=.*ubuntu.*/ubuntu-20.04
- .*Framework.*=net5.0/net5.1
```
See the [README updates](https://github.com/Azure/azure-sdk-tools/blob/d213525/eng/common/scripts/job-matrix/README.md#replace-values) for more details.
This is also a large code update due to some much-needed refactoring. In the course of this work, I found some challenges with what data structure we output the matrix as in cases where we need to do more processing on it (for replace, import, nonSparse, etc.). I had been surfacing the final matrix data structure, which was an array of …
> Add replace operation to matrix config

- eng/common/scripts/job-matrix/job-matrix-functions.ps1
- eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
- eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
There is an error handling cases where the matrix config does not include a base matrix (e.g. only an `include` like [here](https://github.com/Azure/azure-sdk-for-js/blob/1d3632650ce08121b2cc5dc51910129b33b01c42/sdk/keyvault/keyvault-keys/platform-matrix.json)). This was introduced [in this PR](https://github.com/Azure/azure-sdk-tools/pull/1463) due to a type change from `OrderedDictionary` to `[MatrixParameter[]]`, while the empty check was not changed from `$parameters.Count -eq 0` to `!$parameters`.
> [matrix] Fix null check against matrix parameter array

- eng/common/scripts/ChangeLog-Operations.ps1
Add a SemVer string to extracted changelog entries do that we can later sort by SemVer versions.
> Add ReleaseVersionSemVer to ensure version can be sorted

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
This PR makes all annotations visible on the API view by default. It filters a few known annotations that we don't want to include in the review.
> [Java API view] Show all annotations by default

- NuGet.Config
The pipeline is complaining:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=793057&view=results
All csprojes seem to build fine without it.
> Remove extra feed

- NuGet.Config
Reverts Azure/azure-sdk-tools#1509
I was wrong, it was my local nuget cache that allowed calls to succeed.
> Revert "Remove extra feed"

- eng/common/TestResources/README.md
Replaces https://github.com/Azure/azure-sdk-for-net/pull/19725
When you don't specify the subscription id it takes the default value `faa080af-c1d8-40ad-9cce-e1a450ca5b57` and then you get these errors. Took me a while to spot the default value there :(
```
WARNING: The access token is from the wrong issuer 'https://sts.windows.net/../'. It must match the tenant 'https://sts.windows.net/..47/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/..47' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
WARNING: Attempt 1 …
```
> Pass subscription id to New-TestResources.ps1

- eng/common/scripts/job-matrix/job-matrix-functions.ps1
- eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
- eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
With the latest update to generate display names more dynamically, we ended up trying to call `ToString()` on values that could be null.
> [matrix] Handle null values when generating display names

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/scripts/Invoke-GitHubAPI.ps1
- eng/common/scripts/Submit-PullRequest.ps1
Discovered while investigating [this release.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=771475&view=logs&j=60e8c907-7852-5a6b-7760-57b7bd4eaa08&t=b6cbe1c5-d502-5d92-9f97-57a6a725de18) Notice that it's _finding_ the codeowners.
We simply [don't _assign_ the reviewers.](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1251)
> Actually pass the _content_ of the reviewers or teamreviewers variable to the Submit-Pullrequest.ps1 script

- eng/common/pipelines/templates/steps/create-apireview.yml
- eng/common/scripts/Create-APIReview.ps1
Automatic review  is triggered whenever pipeline is triggered from internal project. This needs to be restricted to run from master or from other branch if version is GA.
> Skip API create step when running from feature branch with non GA version

- doc/common/common_engsys.md
- eng/common/pipelines/templates/steps/publish-blobs.yml
- eng/common/scripts/check-spelling-in-changed-files.ps1
- eng/common/scripts/copy-docs-to-blobstorage.ps1
- eng/pipelines/eng-common-sync.yml
- eng/pipelines/mirror-repos.yml
- eng/pipelines/templates/steps/ref-updater.yml
- eng/pipelines/templates/steps/sync-directory.yml
- eng/pipelines/templates/steps/sync-repo-branch.yml
- packages/python-packages/doc-warden/warden/enforce_target_file_presence.py
- src/dotnet/Mgmt.CI.BuildTools/ci.yml
- tools/CreateRuleFabricBot/ci.yml
- tools/check-enforcer/ci.yml
- tools/github-issues/ci.yml
- tools/http-fault-injector/ci.yml
- tools/notification-configuration/ci.yml
- tools/pipeline-generator/ci.yml
- tools/pipeline-witness/ci.yml
- tools/version-guard/ci.yml
Major purpose of the PR is to support master and main default branch instead of hard-coded master.
Changes includes:
1. Markdown files: description which mention master as default branch. Changed to default master.
2. Yaml files: Use set-default-branch.yml and use variables $(DefaultBranch) to replace hard code one.
3. powershell script: Try to use git command to fetch the default ones.
4. ci.yml: Added main as another trigger branch.
Test pipeline on mirror-repo:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=804414&view=logs&s=96ac2280-8cb4-5df5-99de-dd2da759617d
> Support default branch for the workflow. Part 1

- eng/common/scripts/job-matrix/README.md
- eng/common/scripts/job-matrix/job-matrix-functions.ps1
- eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
In order to generate sparse matrices, we generate an array of indices like `[ [0, 0], [1, 1], [2, 2] ]`. When a matrix consists of only rows/vectors with length 1, the index array will look like `[ [0, 0] ]`. Powershell will flatten the outer array of the return value to `[0, 0]` without an explicit array cast, which was missing in this case.
> [matrix] Fix issue where 2d index arrays with length 1 get flattened by powershell

- eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
This is a useful parameter for scenarios like CI pipelines where the test jobs make up a subset of jobs within a stage and need to depend on another job like `Build`.
> Add DependsOn parameter to matrix job generation template

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs
There was a recent change request & approval from language architects for dotnet to change the namespace guideline from  `Azure.Iot` to `Azure.IoT` to fit industry standards.
Merged PR with guideline changes: https://github.com/Azure/azure-sdk/pull/2568
> Update Azure.Iot rule to Azure.IoT

- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Delete last revision of automatic API review if it is in pending status to keep only one revision in pending status at any time. This will require a one time cleanup job to correct current revisions for all automatic review and change in this PR will ensure there is only one pending revision for each automatic API review.
> Automatic review should only have one revision in review pending state

- eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
- eng/common/scripts/job-matrix/samples/matrix-test.yml
The `replace` operator for matrix generation supports regex groupings, meaning you can pass something like `Pool=(.*)-general/$1-storage` to replace `"Pool": "ubuntu-general"` with `"Pool": "ubuntu-storage"`. However, we currently generate these command line arguments as being wrapped with double quotes, meaning the powershell script will try to interpret them as variables. On top of this, the [Azure Pipelines join operator](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#join) does not support double quotes, but I've found that we can effectively escape a single quote join value with another single quote (e.g. the join value `','` must be declared as `''','''` as opposed to `"','"`).
> Use single quotes for matrix generator command line arguments

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingJavadocCodeSnippetsRule.java
This PR adds a diagnostic rule to check existence of codesnippets in:
- javadocs of client and client builder
- javadocs of service methods
> Add diagnostic rule for checking existence of codesnippets in javadocs

- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/Update-TestResources.ps1
Initializing the BaseName with a ServiceDirectory that contains
a "/", because it is a multiple level path, causes the BaseName
initialization code to fail because it doesn't support the
validation pattern.
In all the known cases we already pass the ResourceGroupName
explicitly so don't need to set the BaseName so we can
skip the initialization in those cases.
> Fix BaseName initialization

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/Update-TestResources.ps1
When passing Complete it will remove any resources
already in the resource group that weren't part
of the current deployment. That removal breaks a
lot of assumptions, like multiple deployments when
testing things like smoke-tests or if you are reusing
an existing resource group. We don't want that to happen.
> Remove passing -Mode Complete to deployment

- eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
This PR adds the CI trigger creation logic to the internal pipelines. It also fixes an error with the live test pipeline creation where it was hardcoded to use ```master``` instead of the context that was passed in on the command-line. Adding @danieljurek and @benbp for review on this one since it impacts live test pipelines.
> Enable CI triggers on internal pipelines.

- eng/common/pipelines/templates/steps/verify-agent-os.yml
- Easy way to ensure the DNS workaround is run in (almost) all pipelines
> Call bypass-local-dns.yml from verify-agent-os.yml

- eng/common/TestResources/build-test-resource-config.yml
This PR adds a new step that will merge multiple subscription configuration objects (initially sourced as json from keyvault via devops variable groups), and output a single object as a devops variable. This will allow service owners to manage additional subscription configurations independent of the ones we maintain. For example, the communication service has the need for their own config to store strings that vary per-cloud (e.g. static testing phone number assets and connection strings), but that also must be combined with our base configs. Right now we have to keep a separate config that, since it contains our testing principal, only the azure sdk engsys team has access to. Making it easier to maintain multiple configurations will reduce our config duplication, and also lay groundwork …
> Add template to merge multiple subscription configurations

- eng/common/TestResources/build-test-resource-config.yml
The way we are setting subscription configuration values as secrets causes Azure Pipelines to exclude them from the environment variables available to tasks when they are set by the deployment script. Prefix any subscription configuration keys with an underscore to avoid this problem.
> Use underscore-prefixed variable name when setting sub config values as secrets

- eng/common/scripts/Package-Properties.ps1
- This removes the ci.yml filtering which means all projects can be discovered
- This eliminates the need for the yml parsing module for most common scenarios
- This does introduce some potential issues with duplicate package names for
languages like java. The only known case currently is azure-storage-blobs and
if there is ever a need to explicitly pick the correct one someone can pass
in the ServiceDirectory filter similar to "storage/azure*" for new and "storage/microsoft*"
for the older sdk. By default azure usually comes first so the new one gets discovered
which is likely all we need for now. If this turns out not to be true we might
need another way to disambiguate.
> Stop filtering projects by ci.yml files

- eng/common/pipelines/templates/steps/git-push-changes.yml
- eng/common/pipelines/templates/steps/set-default-branch.yml
Two changes in PR:
1. Set default branch to master if not set from git command. Add `continueOnError: true` to unblock any failed places.
E.g. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=838864&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0
Testing pipeline right here: https://dev.azure.com/azure-sdk/playground/_build/results?buildId=845015&view=logs&j=38d918fc-df5a-5870-2b80-6c17fdb13baf&t=489baed9-6f06-5266-9d0d-079a130738b4
2. `git-push-changes.yml` checked whether local has changes. Make the changes so if we need to skip checking changes somehow, we are able to execute the scripts. 
E.g: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=842830&view=logs&j=321fe29c-d6e3-5c98-996f-e7c628f12971&t=71fd3457-22c6-5475 …
> Set default branch to master if not set from git

- eng/common/pipelines/templates/steps/retain-run.yml
- eng/common/scripts/Add-RetentionLease.ps1
This PR fixes the auth on the retains run script. The mistake I was making was assuming that the token that the devops API plumbing took was a straight access token when instead it is a ```base64(username:access_token)``` string.
> Fix retain runs auth.

- eng/common/pipelines/templates/steps/verify-links.yml
- eng/common/scripts/Verify-Links.ps1
- eng/pipelines/githubio-linkcheck.yml
- Update link checking pipeline to enable caching
- Add loading cache file from a http endpoint
- Add retry logic when hitting 429
Fixes most of https://github.com/Azure/azure-sdk/issues/2403
Fixes https://github.com/Azure/azure-sdk-tools/issues/1439
> Add caching support to verify-links

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/AzureArtifactsServiceUnavailableClassifier.cs
This classifier looks for tasks with failed transfers to Azure Artifacts and logs them as an error. This will help us understand how frequently this problem is occurring:
https://github.com/Azure/azure-sdk-for-java/issues/19039
Cursory scan of recent data indicates that it isn't common (probably related to Azure Artifacts service health issues).
> Add classifier for Azure Artifacts 503 errors.

- eng/common/scripts/Verify-Links.ps1
This will allow us to point our verify-link script at a raw
MD file in a github repo and have it parsed correctly for
links.
> Parse MD files coming over http as raw markdown files

- eng/pipelines/githubio-linkcheck.yml
This changed depends on the fix in https://github.com/Azure/azure-sdk-tools/pull/1580 to fully enable caching of the MD file links in the go repo. 
This PR also increases the timeout of the pipeline because we have been very close to the default 60 mins for a while and this new caching will likely push it over the limit.
> Add Go links to cache to enable faster validation

- eng/common/pipelines/templates/steps/sparse-checkout.yml
For pipelines with many paths (e.g. core ci), it can be annoying to have so many separate jobs show up in the UI, one for each path. Additionally, sometimes git tries to do garbage collection and it can take a lot longer to run many `git sparse-checkout add` commands as opposed to a single set command. This PR changes the behavior to parse the yaml paths parameter object into the script, and run a single command to set the sparse checkout paths. I use `invoke-expression` here because otherwise powershell treats the space-separated string as a single parameter and it all ends up on the same line in the sparse checkout config file.
> Set multiple sparse checkout paths in one command/job

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
DevOps helper scripts were updated in azure-sdk repo
so syncing those changes into the tools repo so they
can be used prepare-release script.
> Sync Devops helper scripts from azure-sdk repo

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/DnsResolutionFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This classifier looks for DNS resolution failures on failed tasks. We've got a set of previously identified errors which we are using in our search patterns.
The PR also enables a previously added classifier which I had not enabled yet.
> DNS resolution failure classifier.

- eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
This PR adds a task which takes the ```SetDevVersion``` property which is local to the job and exports so it can be used across jobs and stages. Example usage:
```yaml
- stage: Integration
variables:
SetDevVersion: $[stageDependencies.Build.Build.outputs['VersioningProperties.SetDevVersion']]
```
> Allow propogation of SetDevVersion.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/CacheChunkOrderingFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This classifier looks for a chunk ordering error in our build pipelines. It was observed on this build:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=866560&view=logs&j=32afe1f3-cae1-5682-187c-9a515535777f&t=eb790175-775e-5b46-331b-d42a59e01ffd&l=107
> Chunk ordering error classifier.

- eng/pipelines/live-test-cleanup.yml
- tools/live-test-cleanup/cleanup.ps1
This adds two public cloud subscriptions managed by the ACS and Cosmos partner teams to our live test cleanup job.
> Add more partner subscriptions to live test cleanup pipeline

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/pipelines/templates/steps/sparse-checkout.yml
- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
We're spending 10+ minutes sequentially cloning repos in order to create the patch files for our sync PRs, when those files are localized to a single directory. We could eliminate ~99% of this time by doing a sparse checkout instead.
> Use sparse checkout for eng/common sync PRs

- eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
This is a super useful template, but I need to run it twice!
See example PR [over here](https://github.com/Azure/azure-sdk-for-python/pull/18478)
And example run of what I want in an example run [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=885368&view=logs&j=b4945417-8893-551a-3bcc-9c043455cb7a).
Without these changes, we run into "duplicate job id" when we attempt to run it in the same stage. Discussion for the `why` I want to run it twice in the same stage is also present on the linked PR.
> Allow Multiple Invocations of `archetype-sdk-tests-generate` within the same stage

- eng/common/pipelines/templates/steps/docs-metadata-release.yml
- eng/common/pipelines/templates/steps/sparse-checkout.yml
- eng/pipelines/templates/steps/sync-repo-branch.yml
In our release stages, we do a full git clone of the docs repo. This can add up to 4 minutes of time to the release stage. Checking out only the files we need reduces that time to around 10 seconds.
> Sparse checkout docs repository in release step

- eng/common/pipelines/templates/steps/sparse-checkout.yml
This updates the sparse checkout template to be able to be called multiple times with new paths/repositories, and handle already cloned/checked out repositories.
Running `git sparse-checkout add` multiple times, as opposed to a single time with multiple arguments, can take a significantly longer amount of time. Similarly, re-running `git sparse-checkout set` may or may not lose context from earlier pipeline steps which may have iteratively built up all required paths for a given build/test run.
The change to this script handles all above conditions, and also gets rid of all the template looping constructs. By only using powershell logic (aside from `convertToJson`), the script is easier to test locally, and also no longer adds many steps to the job output page when there are a lot of …
> Refactor sparse checkout template: idempotency and no yaml loops

- eng/common/scripts/ChangeLog-Operations.ps1
Add method to support extracting changelog entries from changelog content as string or array of strings.
> Add Get-ChangeLogEntriesFromContent

- eng/pipelines/setup-tutorial-branch.yml
Disabling the NuGet security warning since it doesn't apply to this pipeline.
> Disable NuGet warning for tutorial setup.

- eng/common/scripts/Delete-RemoteBranches.ps1
- This adds the ability to check for pull request opened from `azure-sdk/azure-sdk` repo against `Azure/azure-sdk` repo before cleaning the branch up.
> Add the ability to check for open pull request to a different repo.

- .azure-pipelines/dotnet.yml
- src/dotnet/Mgmt.CI.BuildTools/ci.yml
Switch to using net-release-feed.yml which published to the public azure-sdk-for-net DevOps feed
> Switch publishing to DevOps Feed

- src/dotnet/APIView/APIViewWeb/Models/RenderedCodeFile.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Currently skip diff range only skips when rendering text but corresponding tokens are not skipped when rendering html lines. This causes inconsistency when showing diff. Incorrect lines are shown as removed or added. We don't want to skip any ranges for UI request and diff logic should ignore these tagged lines(lines within skip diff range) only when comparing automatic review revisions.
> Enable skip difference tag only for automatic revision diff

- tools/stress-cluster/chaos/README.md
- tools/stress-cluster/chaos/examples/Dockerfile
- tools/stress-cluster/chaos/examples/testjob.yaml
This PR adds some initial information and examples for utilizing the chaos/stress testing cluster spun up in the playground subscription.
As follow-up work, I plan to move this cluster into the main testing sub, and start to add buildout/automation pieces for that cluster into another sub-directory of `stress` (so that anyone reading this could build out their own if they wanted).
This work may or may not be long-lived, but I wanted to keep it somewhere that was public and easily shareable with other members of the team who wanted to play around with things (right now it's in a personal private repo).
If `azure-sdk-devops` internal would be a better fit for now, that's another option.
> Add README and examples for using chaos testing cluster

- eng/common/scripts/git-branch-push.ps1
With recent changes to use sparse checkout in our release steps, the assumption that all remote refs will be downloaded to the local git state no longer holds. This updates our git branch push script to check for pre-existing branches via `git ls-remote` instead, and additionally constrains the `git fetch` command to only fetch relevant refs.
> Check remote refs instead of local refs when applying/pushing changes

- eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
When multiple matrix generators are used, we require passing in separate job names, but don't plumb them through to the display name. The display names could be more descriptive than they currently are:
CC @scbedd
> Use generate matrix job name parameter as display name

- eng/common/scripts/ChangeLog-Operations.ps1
Update changelog entry to match updated guidance https://azure.github.io/azure-sdk/policies_releases.html#change-logs
New Changelog entries will now look like
```
- Types to represent `GeoJson` primitives.
```
> Update format of new Changelog Entry

- tools/stress-cluster/chaos/README.md
- tools/stress-cluster/chaos/examples/Dockerfile
- tools/stress-cluster/chaos/examples/network_loss.yaml
- tools/stress-cluster/chaos/examples/testjob.yaml
Azure AKS default outbound rules do not allow ICMP, so the network loss example was always failing, as opposed to just failing when we enabled the test. This change subs out ping for wget to keep the example simple (i.e. not having to make changes to the AKS cluster).
This also adds a `network_loss.yaml` manifest to show configuring chaos tests via command line+config instead of using the chaos-mesh dashboard.
> Update network loss test example to use wget instead of ping

- tools/stress-cluster/chaos/README.md
This fixes a few more naming issues with the latest readme update to the stress tutorial.
> Fix network example names in stress README

- src/dotnet/Mgmt.CI.BuildTools/NugetToolsPackage/CI.Tools.Package/build/targets/common.Build.props
- src/dotnet/Mgmt.CI.BuildTools/NugetToolsPackage/CI.Tools.Package/build/targets/common.targets
Track 1 mgmt depends on these common props/targets. The `SymbolPackageFormat` was hardcoded.
I left the default still be snupkg to avoid breakage of any unknown reference. The .NET mgmt.proj will be updated after this to set to symbol.nupkg after this tool is updated.
> Updating the common props to respect SymbolPackageFormat

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminFunctionalityTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ModifiableRecordSession.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Add header `x-purge-inmemory-recording` with a truthy value to your call to `/playback/stop`.
@mikeharder
> Add capability to purge inmemory on playback stop

- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Azure.Sdk.Tools.HttpFaultInjector.csproj
- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Program.cs
- tools/http-fault-injector/sample-clients/java/http-fault-injector-client/src/main/java/httpfaultinjectorclient/App.java
- tools/http-fault-injector/sample-clients/java/storage-blobs/src/main/java/FaultInjectorHttpClient.java
- tools/http-fault-injector/sample-clients/java/storage-blobs/src/main/java/FaultInjectorUrlRewriterPolicy.java
- tools/http-fault-injector/sample-clients/java/storage-blobs/src/main/java/Utils.java
- tools/http-fault-injector/sample-clients/net/http-client/Program.cs
- tools/http-fault-injector/sample-clients/net/storage-blobs/Program.cs
- Allows using HTTP to fault-injector and HTTPS to upstream
> [http-fault-injector] Replace X-Upstream-Host with X-Upstream-Base-Uri

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
We want to enable ci triggers now so stop removing them.
The removal/adding was causing an invalid dirty state which means
we were always updating all the ci pipelines unnecessarily.
Also added some caching of the pipeline references to help cut down
on some of the network calls.
> Stop cleaning ci triggers

- eng/pipelines/notifications.yml
- tools/notification-configuration/common/Helpers/GitHubNameResolver.cs
- tools/notification-configuration/common/Services/AzureDevOpsService.cs
- tools/notification-configuration/common/common.csproj
- tools/notification-configuration/identity-resolver/Program.cs
- tools/notification-configuration/identity-resolver/identity-resolver.csproj
- tools/notification-configuration/notification-creator/NotificationConfigurator.cs
- Ensures that the team name as well as pipeline id match
- If the name and id don't match then update one or the other so
that we can keep updated with pipeline updates (i.e. renames or deletes)
- Ensure the pipeline in the notification settings matches the current pipeline name.
Fixes https://github.com/Azure/azure-sdk-tools/issues/1690 and the current failures in the automation.
> Fix notification checks

- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Last pending revision is removed after comparison and this causes issue if any accidental change is merged to master branch since last API approval and then reverted.
For e.g. API review has following api in revision 0 and it's approved
`void test()`
Now someone merged a PR with an additional API `void test1()`. CI will create a new revision since it mismatches from last revision.
Developer realizes the mistake and reverts changes to remove `void test1()`. Review system still find this new revision as different since comparison is against last pending revision, not approved revision.
Ideally API review should have found the match against previously approved revision and should not create a new revision and this PR is to achieve this goal.
> Auto API review should only have one pending review since last approval

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
@kristapratico  also hit an issue with this with her perftests, so I ended up bumping priority.
This PR does the following:
1. Always unzips a `response.Body` if it is `gzip`
2. Within the test-proxy, the body will be handled uncompressed.
- We do this such that our sanitizers, transforms, etc, can all work on the content itself. There is no possible way we can clean out data when we're looking at an opaque window.
3. Just prior to returning the response, check to see if Content-Encoding includes `gzip`. If it does, compress the body and send THAT back.
Now this is making me think that we need to handle this the same way for `request.Body` as well. Cross that bridge when we come to it!
> Support GZipped Responses

- src/dotnet/APIView/APIViewWeb/Models/ReviewRevisionModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Approve button is visible even when comparing diff against two unapproved revisions. This can lead to accidental approval of unwanted changes that are in diff revision. Approve button should not be shown in diff when comparing against another unapproved revision.
> Hide approve button if diff is not against approved version

- eng/common/scripts/Create-APIReview.ps1
- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/Save-Package-Properties.ps1
API review status is checked if package version is GA and this is causing issue for JA and Python packages which moves to new GA version after GA release. Any granular change in APIView forces architects to approve it even if release is weeks away to avoid build break  and this requires additional effort from approvers. This change is to validate API review status only if version is GA and release date is present in change log. So developer can set the release date(not required to be exact date) whenever they are are ready to get API review reviewed.
> Check for API review status only if release date is set in changelog

- eng/common/pipelines/templates/steps/bypass-local-dns.yml
Live test is failing on Ubuntu with local DNS error we have faced in the past on Ubuntu 1804 image. We are facing this issue again on Ubuntu 20.04 image. PR is to run bypass DNS step on Ubuntu 20.04 as well.
> Add Ubuntu 20 to local dns bypass template

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/Analyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/Diagnostics.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ModuleInfoDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ServiceVersionDiagnosticRule.java
Added a new diagnostic rule to check that a track 2 client library defines an enum that implements ServiceVersion and is used in the builder method.
> Service version diagnostics

- eng/common/scripts/Create-APIReview.ps1
- eng/common/scripts/Package-Properties.ps1
Disable release date check when enforcing API review status. Java package got released without API approval even though release date is present. As per the analysis so far, change log parser didn't find the release date even though it was present so API check didn't enforce it. As a first step, disabling this new check to enforce API approval.
Update: Identified root cause and updated PR with actual fix to get the release date in package properties file. updated change is not disabling this check.
> Disable release date check

- eng/common/scripts/Update-DocsMsMetadata.ps1
Example success with template project metadata ambiguity: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=976427&view=logs&j=ceb84d66-6af3-5d95-9875-cd812f26b59e&t=3a6002d8-5197-536e-765b-7e51c84fd258&l=144
> Update docs metadata mutation logic

- eng/common/scripts/ChangeLog-Operations.ps1
Updates based on https://github.com/Azure/azure-sdk/pull/3103
- Renamed "Key Bugs Fixed" to "Bugs Fixed"
- Renamed "Fixed" to "Other Changes"
Added a warning in validation if at lease one of the recommended
headers aren't used.
Fixes https://github.com/Azure/azure-sdk-tools/issues/1728
> Update change log headers based on guideline update

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/deploy-test-resources.yml
This adds support to our common ARM deployment script to compile and deploy [Azure bicep](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview) files.
Resolves #1712
> Support building and deploying bicep templates

- tools/stress-cluster/chaos/README.md
This PR aligns the stress test building readme with the simplified pod spec template used by the tests in the `examples` directory.
> Update readme to use from-pod template

- eng/common/pipelines/templates/steps/sparse-checkout.yml
Explicitly add '/*' '!/*/' to the list of paths so we include
the files in the root of the repo.
Added some extra command logging so we can easily repro locally without
needing to find the code that ran.
Update to '/eng' so that we only get paths that start with eng instead
of every path that has eng as a folder.
> Add root directory to list of sparse checkout paths

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
According to [.NET Source](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System/net/System/Net/Http/HttpContent.cs#L176), I believe this should be a safe cast to `MemoryStream` from `ReadAsStreamAsync`.
> Don't Double-Convert When Decompressing Body

- eng/pipelines/notifications.yml
- tools/notification-configuration/github-codeowner-subscriber/CodeOwnersParser.cs
- tools/notification-configuration/github-codeowner-subscriber/Program.cs
In order to help with special pipelines like aggregate-reports that live
in a general path we should follow standard codeowners rules and match
the path against the latest path in the codeowners file that matches
the file path of the pipeline. That way we can override specific pipelines
via full path later in the file to specify exact owners for that pipeline.
> Full path override support for code owner matching

- src/swift/Sources/APIViewManager.swift
- src/swift/Sources/CommandLineArguments.swift
- src/swift/Sources/Models/NavigationTags.swift
- src/swift/Sources/Models/TokenFile.swift
- src/swift/Sources/SourceCodeExample.swift
- src/swift/Sources/Util/Logger.swift
- src/swift/Sources/main.swift
- Runs `swiftformat` on the code to clean up style issues
- Adds support for `ConstantDeclaration` and `VariableDeclaration`
- Adds support for `FunctionDeclarations`
- Example: https://apiviewstaging.azurewebsites.net/Assemblies/Review/420f0e15db334c9d8f10f6c9b07be509
A few notes:
- This should eventually be refactored to eliminate duplicate code
- The use `SharedLogger.fail` is deliberate to ensure we get adequate coverage for chat without silently failing if a new code technique is used that we aren't explicitly supporting.
- `FunctionDeclaration` support is rough and uses a lot of `textDescription` to quickly populate something. It will need additional work.
> Swift APIView: Added support for variables and functions

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
- tools/test-proxy/ci.yml
Without a timestamp, it's hard to tell from the console logs if the app is still running.  Changes output from:
```
Recorded: 0  Played Back: 0
Recorded: 0  Played Back: 0
Recorded: 0  Played Back: 0
```
to:
```
[16:49:11] Recorded: 0  Played Back: 0
[16:49:12] Recorded: 0  Played Back: 0
[16:49:13] Recorded: 0  Played Back: 0
```
> [test-proxy] Add short timestamp to status logs

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
`AllowAnyHeader` is for the preflight `Access-Control-Allow-Headers: <requested headers>`.
`WithExposedHeaders` adds `Access-Control-Expose-Headers`. These restrictions were causing karma tests to not have access due to the xhr headers being filtered out by security restrictions.
> [Test-Proxy] Need to expose all headers, not just allow them

- eng/common/docgeneration/Generate-DocIndex.ps1
- eng/common/docgeneration/templates/matthews/partials/head.tmpl.partial
Alrighty, I think this was about the cleanest as I could find to do this.
1. Add new header template that adds GA tag.
- This header was generated by `docfx template export default` -> add my stuff -> copy into partials folder.
2. Add campaignId argument to GenerateDocFxToCConfig (which is really the function that builds the skeleton of the site)
- This will optionally inject a specific campaignId if presented
Have run a test using the java folks as a guinea pig. To take advantage of this, merely update the call in `Language-Settings.ps1` -> `Get-<language>-GithubIODocIndex()`
> Add basic ga tag w/ settable campaignid

- src/swift/Sources/Models/TokenFile.swift
- src/swift/Sources/Models/TypeModel.swift
- src/swift/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView.xcscheme
- src/swift/Tests/TestSwiftFile.swift
See API view:
https://apiviewstaging.azurewebsites.net/Assemblies/Review/29dc0e0aec33421ea7a6728eb05178e5
Diff 73 against 71.
> SwiftAPIView: Fix `Any` type not supported and remove internal labels from parameter rendering

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
1) duplicate maven output when a shaded jar is uploaded for review (we only want to see the jar related to our library, not the jar details of all shaded libraries)
2) inclusion of unintended comments into the APIView when the comment was in a certain format, notably:
```java
@Override
//TODO: enable create KeyVaultTrustManager with ManagerFactoryParameters
protected void engineInit(ManagerFactoryParameters spec) {
LOGGER.entering("KeyVaultKeyManagerFactory", "engineInit", spec);
trustManagers.add(new KeyVaultTrustManager());
}
```
> Fix two Java APIView issues

- eng/pipelines/stress-test-release.yml
In the stress test release pipeline, using sparse checkout off `$(Build.SourceVersion)` won't work for repos other than azure-sdk-tools, because the source version gets set as the HEAD commit for main on the tools repo, rather than the branch name itself.
Passing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1023812&view=results
> Set default commitish to main for stress test release

- eng/pipelines/mirror-repos.yml
changelog:
1. Enable public spec repo main to master sync, RPaaS sides needs this for their transition
2. Remove old private spec repo main branch sync, as main is now default branch, will be auto synced from public spec repo main branch
> enable public spec repo main to master sync

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Functions/FindTestIssuesFunction.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindTestIssues.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Startup.cs
This creates a report that flags issues that are labeled with test-reliability, test-sovereign-cloud and test-manual-pass.
This will help us keep an eye on the test issues in our repo.
/cc @jongio @jsquire @kurtzeborn @praveenkuttappan @weshaggard
> Add report for issues that are marked with test-* labels in the repo.

- eng/common/scripts/Invoke-DevOpsAPI.ps1
- eng/common/scripts/Queue-Pipeline.ps1
An empty string uses the default branch
> Add ability to leave SourceBranch empty when queueing a build 

- tools/test-proxy/docker/dockerfile-win
Causing failures over in go integration builds.
> Windows Docker container should dump files in the same folder within the container as Linux container

- eng/containers/ci.yml
- tools/keyvault-mock-attestation/.dockerignore
- tools/keyvault-mock-attestation/.gitignore
- tools/keyvault-mock-attestation/Dockerfile
- tools/keyvault-mock-attestation/README.md
- tools/keyvault-mock-attestation/index.js
- tools/keyvault-mock-attestation/package.json
- Add `keyvault-mock-attestation` code to the azure-sdk-tools
- Dockerize the code to prepare for adding it to the azsdktools ACR registry.
This mock service is needed to run live tests for a specific keyvault scenario. While we currently use the 
long-running test fixture that I deployed, that is not a sustainable solution. 
We want to make sure the code for this mock service is in a repo that is owned by Azure SDK team, 
and we want to enable test runs to deploy and tear down everything that need to run live tests. Depending
on a long running test fixture that is in my private repo violates both of these conditions. By moving the 
code here and ensuring that we can push updates to ACR we will be able to deploy the container for every
test run.
> Move the mock attestation service to azure-sdk-tools

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
This is the profiler graph now. @HarshaNalluru my claim is this should stabilize. However, during repros on this I DID hit a crash that resulted in the `0` outputs for each run on the js perf tests. That crash may be responsible for the hangs as well.
Looks like `(process 11048) exited with code -1073741819.` After I did some searches...
> The exit code -1073741819 in hex is 0xC0000005. If you look up this code in Microsoft's documentation (NTSTATUS Values) you will see that it indicates that your program was terminated due to an access violation. This error can occur for a variety of reasons, including de-referencing a NULL pointer or referencing an invalid address.
So I'm still tracking that. It may have been caused by AV but I doubt it.
Either way, I'm happy to have improved the …
> [Test-Proxy] Address Memory Leak 

- tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.sh
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
I can't figure out whether the `UTC` suffix is or is not valid with the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) spec, but either way, busybox won't output `Z` and powershell `DateTime` won't parse `UTC`. The date string is parsed by the resource group cleanup scripts [here](https://github.com/Azure/azure-sdk-tools/blob/e4689bdefa9511950eaf77ebd7fc710d01d4e7b2/eng/scripts/live-test-resource-cleanup.ps1#L58).
> [stress testing] Use UTC 'Z' zone designator to work with powershell DateTime parsing

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Add some checks to help catch any auth issues when calling the Devops Rest APIs.
> Add Rest Method checks to Prepare-Release

- eng/scripts/live-test-resource-cleanup.ps1
Most (>8k) of the deleted key vaults have a future purge date and we fail to delete them and we end up timing out so I'm filtering so that we only attempt to delete ones with past due purge dates.
> Filter out future purge dates resources

- tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
- tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
- tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
- tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
If any ARM template outputs or parameters container connection strings, etc. they will get printed in the container logs. This will hide stdout from the deployment.
> [stress testing] Prevent secret logging from resource group deployment results

- eng/common/scripts/Create-APIReview.ps1
API review status check is done only for GA version of client SDK packages. Java team has asked to enable api review check for spring SDK also. I will make a change to add a function in individual language function script to override standard check of sdkType client. This PR is only a temp work around until language side override function is ready.
> Enable API review approval check for Java spring packages

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/TagHelpers/ActiveIfTagHelper.cs
Python team and architects have asked for change to allow closing reviews by anyone. Currently only owner is allowed to close the reviews and this causes some stale reviews to be present in system. This change is to make it similar to github where other developers are allowed to close a PR.
Second change in this PR is to show upvote button in comments as active if at least one has upvoted it.
> APIview misc fixes

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
1. Accept a `--version` flag at tool invocation that merely returns the version. I need to double check this returns the correct version on a built package. 
2. If the user provides a test-id that includes `.json` in the name, just keep it. Otherwise, we will always store and retrieve files that end in `.json` such that the recordings are syntax highlighted at rest.
> [Test-Proxy] Allow Version Flag. Output Json files explicitly.

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/scripts/Helpers/Resource-Helpers.ps1
- eng/pipelines/live-test-cleanup.yml
- eng/scripts/live-test-resource-cleanup.ps1
Reverts #1910. Vaults and managed HSMs are automatically purged on their purge date. The point was to purge them daily to preserve capacity. The default purge date is +90 days.
> Attempt to purge all vaults, managed HSMs

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
- tools/test-proxy/docker/README.md
- tools/test-proxy/documentation/trusting-cert-per-language.md
- tools/test-proxy/documentation/using-in-devops.md
- Address some basic ordering in test-proxy readme.
- Update `trusting-cert-per-language` to reflect Java methodology.
- Update `using-in-devops` to reflect the presence of the common pattern.
> [Test-Proxy] Documentation Updates

- src/dotnet/Mgmt.CI.BuildTools/NugetToolsPackage/CI.Tools.Package/build/psModules/CodeGenerationModules/AutoRestCodeGenerationModule/AutoRestCodeGenerationModule.psm1
Since default branch for `Azure/azure-rest-api-specs` is changed from `master` to `main`, update the script to fit this changing.
> Update AutoRestCodeGenerationModule.psm1 default branch to 'main'

- src/swift/README.md
- src/swift/Sources/APIViewManager.swift
- src/swift/Sources/CommandLineArguments.swift
- src/swift/Sources/Models/TokenFile.swift
- src/swift/Sources/Models/TypeModel.swift
- src/swift/Sources/Util/Errors.swift
- src/swift/SwiftAPIView.xcodeproj/project.pbxproj
- src/swift/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView.xcscheme
Closes #1823.
Change:
- Adds support for `--package-name` when automatic detection of package name is unsuccessful.
- Adds support for generating Swift APIView from Objective-C and mixed-source (ObjC+Swift) frameworks.
- Changes language from "Json" to "Swift" for generated files.
> Swift APIView: add support for Objective-C and Mixed Source frameworks

- eng/common/scripts/stress-testing/deploy-stress-tests.ps1
- tools/stress-cluster/chaos/README.md
Updates the stress test docs to use commands from the [stress test deploy script](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/stress-testing/deploy-stress-tests.ps1) instead of the multi-step manual commands.
Updates the stress test script to handle different az subscription contexts in all scenarios, and a bug fix for auto-installing the powershell yaml module.
> [stress testing] Update docs, resiliency for deploy script

- eng/common/TestResources/New-TestResources.ps1
New-TestResources.ps1 was storing the .env file at the temp folder if the service uses bicep files. This bug fix stores the .env file at the correct service directory.
(also pushed in logging request in https://github.com/Azure/azure-sdk-tools/pull/1876)
> Bug fix: Storing .env file for bicep file at service dir

- eng/common/TestResources/New-TestResources.ps1
Now that we are automatically marking new resources for deletion, we should be able to safely ensure that the base name is unique without worrying about creating too many resources.
> Add unique id to default base name

- eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
- Condition is missing either `succeeded()` or `succeededOrFailed()` which is required to respect pipeline cancellation
- I used `succeeded()` to match the previous step in this template
> Make "Setup Versioning Properties" cancellable

- eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
Add Skip.SetTestPipelineVersion to allow overiding the `SetTestPipelineVersion` step for template pipelines.
Resolves https://github.com/Azure/azure-sdk-tools/issues/1664
> Add Skip.SetTestPipelineVersion

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/RemoveHeaderSanitizer.cs
Both the source and the test had the same braindead mistake.
@seankane-msft  this will resolve your issue.
> [Test-Proxy] Resolve RemoveHeaderSanitizer bug

- eng/common/scripts/Update-DocsMsPackages.ps1
Exit 0 so DevOps doesn't fail the build when the last command called by the domain-specific function exited with a non-zero exit code.
Specifically this mitigates issues in Java where the docindex pipeline fails because an inner `mvn` command failed during validation. The whole script succeeds because we properly handle errors but PowerShell just reads `$LASTEXITCODE`
> Update-DocsMsPackages.ps1 Explicitly exits 0 

- tools/test-proxy/docker/dockerfile
- dotnet must be run from folder containing appsettings.json
> [test-proxy] Docker image should use appsettings.json

- tools/test-proxy/docker/dockerfile-win
We...
- Eliminated pshell (convenience only, we aren't using pwsh to install the certificate so...)
- No longer building on the same image that we run. The build runs in a previous stage and is copied over now
- Now we run on `aspnet:nanoserver`. Basically smallest footprint we can get to.
- Removed unnecessary layers
Old uncompressed local size: 1419707561 == `~1419MB`
New uncompressed local size: 367880427 == `~367 MB`
@benbp take your 75% improvement 👍
> [Test-Proxy] Minimize the windows docker file

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/README.md
The focus of these changes is to revise the script to better support use by external contributors and others outside of the Azure SDK ecosystem and without access to the Microsoft AAD Tenant.
- Creation of a new Test Application service principal is now possible   from a non-Microsoft AAD tenant.
- When a new Test Application principal is created, the principle of least  privilege is now applied; the new Test Application is granted ownership of the resource group  associated with the test resources and no longer has access to any other resources in the subscription.
- If an existing Test Application principal is specified, it will be assigned ownership of the resource group created.  This supports using a Test Application principal without privileges at the subscription-level.
- When no …
> [TestResources] Doc Updates and Revisions for External Use

- eng/common/scripts/check-spelling-in-changed-files.ps1
Some exercise of eng/common synchronization scenarios revealed an interesting set of behaviors in cspell configuration: 
* cspell requires that a file be listed on the command line of `cspell lint ...` IF all of the files in the cspell config file's `file` section are excluded by `ignorePaths` from the config file. That is, when ignoring `eng/common/**/*` and all files in the PR are changes to `eng/common`, cspell will exit with an error and show help text implying that a file must be specified on the command line.
* cspell will not fail IFF the `files` configuration value includes a file which exists, is not empty, and is not excluded by `ignorePaths` 
* cspell merges configurations given with `--config <file path>` with configurations in "known" locations (e.g. `.vscode/cspell.json`) …
> Add ability to exit gracefully when all files in the diff are excluded

- eng/common/scripts/SemVer.ps1
Since we are treating v0 versions as prerelease we need to make sure
we don't accidently start to add the bogus prerelease label in cases where
we call ToString() on the version.
> Fix SemVer.ToString to handle v0 case

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Update-ChangeLog.ps1
- Move logic for removing empty sections to ChangeLog-Operations.ps1
> Move logic for removing empty sections to ChangeLog-Operations.ps1

- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Few classes in a package inherits DictMixin which is in a different namespace within same package root. Currently API view list only functions defined in same namespace as the class itself so it omits any functions defined in parent class. This PR is to ensure functions listed within same package root are listed in API View as long as it is defined in same package root.
> Include methods defined in different namespace in same package

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Prepare-Release.ps1
- eng/common/scripts/Update-ChangeLog.ps1
Should fix https://github.com/Azure/azure-sdk-for-java/issues/23908
> Add for multiple levels of Atx Headers in the CHANGELOG.md

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/Models/PullRequestModel.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
We currently do not have any API change detection using APIView as part of pull request validation. This PR is a first step towards adding this capability. Public pipeline doesn't have access to any KV to authenticate request. So instead of sending the file from pipeline, pr pipeline will send a request informing about a PR that needs to be verified for API changes. APIView will pull artifact from devops and look for any API changes and add it as comment in PR if it finds any API changes. This PR is a first step towards verifying API changes earlier in the cycle and some of these changes will be incorporated into SDK automation to support creating a connected reviews from swagger files.
> Detect any public API changes in pull request

- eng/common/pipelines/templates/steps/cache-ps-modules.yml
Containers should bake modules into the image to save on pipeline time.
> Skip PSModule caching in container jobs

- eng/common/pipelines/templates/steps/verify-changelog.yml
In cases like go where we don't pass a service name having this default to "not-specified" breaks things so we should allow for ServiceName and/or ServiceDirectory to be empty.
@chidozieononiwu we should also still go and get ServiceName cleaned up from the repos so that parameter can be removed.
> Make ServiceName optional for verify-changelog

- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/values.yaml
- tools/stress-cluster/services/Stress.Watcher/Dockerfile
- tools/stress-cluster/services/Stress.Watcher/ci.yml
- tools/stress-cluster/services/Stress.Watcher/publish.ps1
- tools/stress-cluster/services/Stress.Watcher/src/Extensions.cs
- tools/stress-cluster/services/Stress.Watcher/src/PodEventHandler.cs
- tools/stress-cluster/services/Stress.Watcher/src/Program.cs
- tools/stress-cluster/services/Stress.Watcher/src/Stress.Watcher.csproj
- tools/stress-cluster/services/Stress.Watcher/tests/PodEventHandlerTest.cs
- Add namespace filtering to stress event watcher
- Add stress watcher dockerfile
- Load in cluster config when stress watcher runs in a k8s container
- Add stress watcher ignore annotation
- Add better log handling for stress watcher
- Handle stress watcher re-connect on connection timeout/close
- Add stress watcher deployment and roles to infrastructure templates
> [stresswatcher] Improve reconnect, logging, auth, deployment

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
This is because `request.Path` implicitly _decodes_ the URI.
`/mytable(PartitionKey='aa%27%27bb')`
becomes
`/mytable(PartitionKey='aa''bb')`
However, when we fire this request upstream, that URI _matters_ as it's part of the canonicalized resource string encoded into the shared key!
We need to store this _raw_ or as close to raw as we can get it, to prevent auth failures like this in the future.
> [Test-Proxy] Need to access raw uri string instead of `request.Path` when creating upstream request

- eng/common/pipelines/templates/steps/policheck.yml
- Adding common policheck steps to enable policheck run on PR validations.
> Add common policheck steps

- eng/common/scripts/stress-testing/deploy-stress-tests.ps1
This issue has been showing up recently: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1103685&view=logs&j=38a05975-7697-5434-099a-d7b3d4012883&t=b1e71580-9408-50be-13a0-b0783b8cb008&l=57
```
Installing module az with min version 6.4.0 from https://www.powershellgallery.com/api/v2
Using module Az with version 6.4.0.
Import-Module : Assembly with same name is already loaded
At /home/vsts/.local/share/powershell/Modules/Az/6.4.0/Az.psm1:113 char:1
+ Import-Module Az.Aks -RequiredVersion 2.4.0 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
```
> Handle assembly already loaded errors in deploy stress test script

- tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
Updating stress-test-addons helm chart version with changes from https://github.com/Azure/azure-sdk-tools/pull/2039
> Bump stress-test-addons chart version to 0.1.7

- tools/github-labels/common-labels.csv
- tools/github-labels/repository-snapshots/autorest.csharp.csv
- tools/github-labels/repository-snapshots/autorest.csv
- tools/github-labels/repository-snapshots/autorest.go.csv
- tools/github-labels/repository-snapshots/autorest.java.csv
- tools/github-labels/repository-snapshots/autorest.python.csv
- tools/github-labels/repository-snapshots/autorest.swift.csv
- tools/github-labels/repository-snapshots/autorest.typescript.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-android-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-android.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-c-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-c.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-cpp.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-go-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-go.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-ios-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-ios.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-java-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-java.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-js-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-js.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-net-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-net.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-python-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-python.csv
- tools/github-labels/repository-snapshots/azure-sdk-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-tools.csv
- tools/github-labels/repository-snapshots/azure-sdk.csv
- tools/github-labels/repository-snapshots/perks.csv
The focus of these changes is to add a new "CXP Attention" label to all repositories for use in the pilot of onboarding the CXP support team to help triage/handle issues
normally marked for service attention.   Also added were common service labels for "LLC" and "Maps".
> [GitHub Labels] CXP Attention

- packages/java-packages/codesnippet-maven-plugin/pom.xml
- packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
- packages/java-packages/codesnippet-maven-plugin/src/test/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacerTests.java
- packages/java-packages/codesnippet-maven-plugin/src/test/resources/project-to-test/readme_code_fence_no_snippet_after.txt
- packages/java-packages/codesnippet-maven-plugin/src/test/resources/project-to-test/readme_code_fence_no_snippet_before.txt
Fixes a bug where the codesnippet closing tag matched on README code fences that weren't meant for injection, such as XML code fences. This accidentally removed the code fence closing, resulting in broken READMEs.
> Fix Missing README Code Fence Bug

- eng/common/scripts/Save-Package-Properties.ps1
@praveenkuttappan @weshaggard 
This change mitigates an obscure issue we ran into after the change to `Save-Package-Properties.ps1` merged. It would seem that the relative path computation will, on DevOps machines, generate relative paths with an extra `../` prepended unnecessarily. 
Mitigates https://github.com/Azure/azure-sdk-tools/issues/2094
> Mitigate relative path calculation error on multiple iterations

- scripts/python/apiview-syncdb/sync_cosmosdb.py
Azure data factory creates backup files in current date folder within storage container. Sync script needs update to restore Pull requests container to staging instance.
> Update list of cosmos containers to backup

- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Improve request processing time for python by removing unnecessary step of installing stub generator within virtual env
> Avoid installing apistubgen within virtualenv

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
We actually already treat the header `User-Agent` as volatile, so this isn't even a departure from what the test-proxy already does. Just an extension of it.
@HarshaNalluru
> [Test-Proxy] Don't match on `x-ms-useragent`

- tools/stress-cluster/chaos/README.md
- tools/stress-cluster/cluster/kubernetes/generator/README.md
- tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Program.cs
- tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Stress.Generator.csproj
- tools/stress-cluster/cluster/kubernetes/generator/ci.yml
This PR adds documentation and dotnet tool publishing for the stress test generator.
- Add output directory flag to stress test generator
- [stress test generator] Add pipeline and readme
> Add ci/publish and readme for stress test generator

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/BlobUploadProcessor.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/RunProcessor.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/BuildLogProvider.cs
Removes the cache from the log provider to reduce memory pressure.
Adds Build and BuildTimelineRecord exports to support additional tables in Kusto
> Add additional blob exports to pipeline witness

- eng/common/pipelines/templates/steps/docker-pull-image.yml
- eng/common/scripts/Update-DocsMsPackages.ps1
https://github.com/Azure/azure-sdk-for-js/pull/18405
Docs is switching the validation using docker container. Here is the common logic to pull image from Azure container register.
Testing pipeline in use with the script:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1172146&view=logs&j=dc056dfc-c0cf-5958-c8c4-8da4f91a3739&t=bfb6cede-7671-5504-0a11-79b13ef63703
> Login and Pull docker image.

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminFunctionalityTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/UriRegexSanitizer.cs
@seankane-msft I ended up spending a bunch of time in the tests. There should be _no_ visible change to the API surface with this PR, but we get a lot more explicit about a specific class of errors.
> [Test-Proxy] More explicit error handling around `Admin/Add<Sanitizer/Matcher/Transform>`

- eng/containers/ci.yml
Updating the docker release pipeline to automatically publish the dockerfile for stress test deployment container
> Automate stress test eng-common-tools dockerfile release pipeline

- packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
Fixes a bug where codesnippet boundaries would be matched even if they were missing a codesnippet ID. This happens more prevalently in READMEs as the boundaries are the generic code blocks, so before it would have matched on:
\`\`\`java
\`\`\`
And then because this is an invalid/missing snippet, as you cannot have an empty ID snippet, it would raise an error and remove the \`\`\`, breaking down stream processing.
> Don't Match Snippet Boundaries that are Missing an ID

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminFunctionalityTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/post_delete_get_content.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpException.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/TestRecordingMismatchException.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
@JoshLove-msft I will use this basis to propogate the TestMismatchExceptions back.
> [Test-Proxy] Update Exception Handling For Error Propogation, Allow No-Op BodyKeySanitizer

- eng/common/testproxy/docker-start-proxy.ps1
- eng/common/testproxy/test-proxy-docker.yml
@seankane-msft this is in reference to Azure/azure-sdk-tools#2122
> Adding conditional docker restart

- tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
- tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs
**Summary**
Our current code is not able to fallback to upper level when there is mismatch.
**User story:**
In docs auto publish process, we expect to fetch code owner on package level. e.g. `core/core-amqp`
We are able to fetch CODEOWNERS in [here](https://github.com/Azure/azure-sdk-for-js/blob/main/.github/CODEOWNERS#L15)
However, for many package, we do not offer package level codeowners, which will return nothing based on our current code.
**Expectation**
We hope if we do not find any info from package level, we have the ability to fallback to service level. E.g `keyvault/keyvault-keys`
[CODEOWNERS](https://github.com/Azure/azure-sdk-for-js/blob/main/.github/CODEOWNERS#L66) only provide service level owners, so instead of return nothing back, we expect to have service level owners …
> Added more fallback logic in code owner retriever

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
Fixes #1931
The prior logic would pick up if a method defined _inside_ another method was async and erroneously apply that to the containing method.
https://apiviewstaging.azurewebsites.net/Assemblies/Review/69e35769d0ad47f289f327cb400076ce?diffRevisionId=4a84ae61cb9e4c989c95c0ef3fd348c3&doc=False&diffOnly=True
> [APIView Python] Fix logic for determining if methods are async

- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
For cases where the stress-watcher is deployed to multiple namespaces (e.g. during development), updates to the target namespace service account of the cluster role binding would break authorization for previous deployments in other namespaces. This updates the role binding to be unique to the namespace of the helm release
> Use namespaced cluster role and binding for stress watcher

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
We have added automated review update when new parser version is present and currently this is only done for manual reviews. This change is to update automatic as well as pull request reviews. This change will also remove UI review update option.
> Remove update review option and update review automatically

- eng/common/testproxy/test-proxy-tool.yml
1. `sudo` on the mac agents is having the effect of killing the environment variables that are set. That is the origin of being unable to find the `.dylib`
2. `nohup` is no longer  necessary to invoke with `sudo` on linux
3. Removing the `use .net version`, .NET 5.0 is preloaded on the agents.
A follow-up PR is coming that installs dev certificates in a per-platform methodology.
@HarshaNalluru this unblocks you to add to CI. I just gotta push this out for you. Sorry for the delay, this PR seems simple (and it is), but it's pretty much the very last thing I checked.
> Resolve mac agent failure

- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Python parser has a new version but APIView was not updated to this version. Also change how older review files are updated by looking at correct file name.
> update python parser version and update older review files

- eng/common/testproxy/test-proxy-docker.yml
- eng/common/testproxy/test-proxy-tool.yml
Easy way to disable automatic startup/shutdown.
This was intended to be part of the mac agent PR fixes originally.
> Additional Tool Fixes

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/clouds/AzureChinaCloud.json
- eng/common/TestResources/clouds/AzureCloud.json
- eng/common/TestResources/clouds/AzureUSGovernment.json
For sovereign cloud testing, many cloud-specific arm template parameters and environment variables get passed in from an external keyvault source. This makes them hard to manage and track. This PR moves some common live testing values into source control for easier management. Some values are service-specific (like formRecognizerLocation), so perhaps we could consider a service-specific location for them, but I don't want the config layering to get too complex either.
Related:
https://github.com/Azure/azure-sdk-for-java/pull/25301
https://github.com/Azure/azure-sdk-for-net/pull/25250
https://github.com/Azure/azure-sdk-for-python/pull/21693
> Use arm template parameters as sole input for live test environment variables

- eng/common/testproxy/test-proxy-tool.yml
This is attempt #2. Failure to patch is blocking the other PR. If I can just simplify the commits and have it work, that's definitely the easiest way.
> Adding Redirection of nohup-ed tool runs so we can dump the log later

- .azure-pipelines/apiview.yml
The step where the `cd` is removed is _always_ green. My hunch is that the step only exits with code 1 if the very last command within it exited with code 1. That's why `tox` is failing but the step was green.
> [APIView] Remove trailing cd that is turning the step green

- eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Currently the sparse checkout of the service directory happens to work because it will match on the directory name, e.g.
`git sparse-checkout add keyvault` will end up checking out `sdk/keyvault`. However, some service directories (such as
in azure-sdk-for-go) are now multiple directory segments, e.g. `keyvault/azkeys`. This breaks the git sparse checkout
matching, so to fix the service directory can be updated to an exact path `sdk/<service directory>`.
> Prefix matrix generation service directory sparse checkout with 'sdk'

- eng/common/scripts/Prepare-Release.ps1
This handles cases where the package is beign released for the first time. i.e there is no previously existing versions.
> fix bug in prepare relaease 

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
Updating the outdated `dotnet tool install` command
> Fix `dotnet tool install` command for testproxy

- eng/common/testproxy/docker-start-proxy.ps1
- eng/common/testproxy/test-proxy-tool.yml
One can use script located at `eng/common/testproxy/docker-start-proxy.ps1` to start and stop a default docker configuration.
There is a second argument, `TargetFolder`, that is used to change the folder  will be bound to the volume of the new docker container.
The default used to be `"."`, so that the current folder would bind to the volume.
This PR changes the behavior so that if no target folder is provided, it will instead default to root of the containing repository. The ability to provide this context is unchanged.
> [Test-Proxy] Fix default startup location in `docker-start-proxy.ps1`, Update `windows` tool initialize

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Even if it's empty.
@JoshLove-msft
> [Test-Proxy] `/Playback/Start/` should always populate a json response body

- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Current delay is causing some reviews to be skipped if a new revision is created before existing review is updated. Reducing delay to 500ms as first solution.
> Reduce review update delay

- .azure-pipelines/apiview.yml
- .gitignore
- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/__init__.py
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_property_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_typehint_parser.py
- packages/python-packages/api-stub-generator/tests/docstring_parser_test.py
- packages/python-packages/api-stub-generator/tests/typehint_parser_test.py
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Redesign of the docstring parser logic to minimize the number and complexity of regular expressions to address edge case scenarios. 
The parser uses a heuristic to determine whether type info continues onto a second line or is fully contained on the first line. If the first line ends with a comma or the word "or", it is assumed that the type info continues onto the second line.
Additional test cases have been added to ensure this logic works.
Refactors `TypehintParser` into its own file and adds test cases.
Fixes #1765. Fixes #1616.
> [Python APIView] Fix issues with DocstringParser and TypehintParser. Add new test cases.

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyRegexSanitizer.cs
@JoshLove-msft 
@HarshaNalluru 
@seankane-msft 
I'm a bit nervous with this change. I'll fire a quick build against both the `go` tests in main as well as the latest js tests that I can find. 
EDIT1: `go` playback is just fine.
> [Test-Proxy] Address Matching issues for batch playback

- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
- tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners.Tests/CODEOWNERS
- tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs
- tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs
- tools/code-owners-parser/CodeOwnersParser/FileHelpers.cs
- tools/code-owners-parser/ci.yml
The test is in pipeline with the custom tests run.
Here is the test without custom test run: 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1203228&view=results
> Add command option for output the codeowners directly.

- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/Azure.Sdk.Tools.SnippetGenerator.Tests.csproj
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator/Azure.Sdk.Tools.SnippetGenerator.csproj
azure-sdk-for-net is moving to 3.1/6.0 testing. Downgrade the TFM to target a lower framework version
> Downgrade snippet generator to 3.1

- eng/common/testproxy/docker-start-proxy.ps1
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
- tools/test-proxy/docker/README.md
- tools/test-proxy/docker/dockerfile
- tools/test-proxy/docker/dockerfile-win
- tools/test-proxy/startup-scripts/start-server.js
- tools/test-proxy/startup-scripts/start-server.ps1
- tools/test-proxy/startup-scripts/start-server.py
`/etc` really is for configuration. In the interests of consistency, we're adjusting this so that we don't go against people's regular expectations.
I'm running a `docker-containers-publish` manually off this branch so that I can also update the the targeted docker tag _in this PR_ all in one shot.
> [Test-Proxy] Change storage directory from `/etc/testproxy` -> `/srv/testproxy`

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/CustomDefaultMatcher.cs
@JoshLove-msft This is a basic
> add these additional headers with exclude
I think that what I'll do here is add another argument, something like `extendDefaults` that defaults to `true`. If that element is `true`, then we will start you from a blank slate of excluded headers. What do you think?
@HarshaNalluru this same matcher will be extended for the `matching conditions` that you asked about last week. I need to figure out how to pull in non-string-only inputs from the sanitizer/matcher/transform Admin API, but I'll get there.
> adding simple wrapper exposing the default matcher to for customization

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- Adding explicit error handling for missing/improperly set hostname in a record request
- No more `InvalidOperationException` that doesn't get propogated back to the caller in a coherent fashion
> [Test-Proxy] Adding some additional error handling, updating all explicit exceptions to surface with coherent errors

- tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/prepare.ps1
The prepare.ps1 script will copy the items and create a nested /common directory if the /common directory already exist
> Fixing nested copy items in prepare.ps1 for stress test

- eng/common/pipelines/templates/steps/update-docsms-metadata.yml
- eng/common/scripts/Update-DocsMsMetadata.ps1
- eng/common/scripts/common.ps1
The PR is to validate whether packages are good for the Doc.MS before updating docs.
Currently, we have workaround which add docker id+secret to pipeline existing variable group: Release to Github IO secrets.
Create an issue for long term fix: https://github.com/Azure/azure-sdk-tools/issues/2373
Test pipeline on release pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1225620&view=results
Test pipeline on unified pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1225618&view=results
Test on no docker id: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1225295&view=results
> Make changes on docker validation

- eng/common/pipelines/templates/steps/write-filesystemmetrics.yml
- eng/common/scripts/Write-FileSystemMetrics.ps1
emits metrics like:
```
logmetric: {"name":"agent_driveinfo_size_bytes","value":296559366144,"timestamp":"2021-12-07T00:10:39.783592+00:00","labels":{"name":"C:\\","volumeLabel":"System","driveType":"Fixed","driveFormat":"NTFS"}}
logmetric: {"name":"agent_driveinfo_available_bytes","value":176327012352,"timestamp":"2021-12-07T00:10:39.7865546+00:00","labels":{"name":"C:\\","volumeLabel":"System","driveType":"Fixed","driveFormat":"NTFS"}}
logmetric: {"name":"agent_driveinfo_size_bytes","value":214748360704,"timestamp":"2021-12-07T00:10:39.7888924+00:00","labels":{"name":"D:\\","volumeLabel":"Data","driveType":"Fixed","driveFormat":"NTFS"}}
logmetric: {"name":"agent_driveinfo_available_bytes","value":194948788224,"timestamp":"2021-12-07T00:10:39.7912437+00:00","labels":{"name":"D:\\","volume …
```
> Add disk metrics script and template

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/scripts/stress-testing/deploy-stress-tests.ps1
- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
- eng/pipelines/stress-test-release.yml
- tools/stress-cluster/chaos/examples/network-stress-example/templates/testjob.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/Dockerfile
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/deploy-stress-test-resources.ps1
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/test-resources-post.ps1
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
- tools/stress-cluster/cluster/provision.ps1
- There's no need to have to specify the cluster resource group and subscription when we already know these values ahead of time. We still need to keep them as parameters to enable people to deploy to dev environments they've provisioned themselves.
- Fix secret logging in CI mode from New-TestResources
- Fix the stress deployment script overwriting pre-existing env variables
- Simplify stress chart image handling
- Bump addons chart to 0.1.13
> Use stress test environment defaults for group and subscription

- .azure-pipelines/apiview.yml
- src/swift/README.md
- src/swift/Sources/APIViewManager.swift
- src/swift/Sources/CommandLineArguments.swift
- src/swift/Sources/Models/TokenFile.swift
- src/swift/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView.xcscheme
https://apiviewstaging.azurewebsites.net/Assemblies/Review/94ee72d4b18845b09fe75a270d93077f
APIView now correctly allows you to put a comment on any line and does not duplicate comments.
Additionally, it will extract the package version (or allow you to specify with `--package-version`) so that the listing in APIView will include the version (Example: "AzureCommunicationCalling (version 2.0.0)")
Fixes #2254.
Fixes #2362.
Also, adds swift to the CI path so that it will run and I don't have to override check-enforcer. There aren't any Swift-specific checks at this time.
> [Swift APIView] Fix non-unique line IDs and add Package Version support

- packages/python-packages/doc-warden/README.md
- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/warden/WardenConfiguration.py
- packages/python-packages/doc-warden/warden/warden_common.py
- Add `--repo_root` argument to docwarden to enable scoping of docwarden to service directory.
> Enable Scoping of Doc-Warden Run.

- eng/common/scripts/Invoke-GitHubAPI.ps1
New API to get list of github issues based on labels and created user name. This API will be consumed by JS automation to file an issue for package deprecation and upgrade available warning if not already exists.
> Added new API to get list of github issues

- eng/common/scripts/stress-testing/find-all-stress-packages.ps1
- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Fixing a bug where passing switch parameters down from multiple functions does not actually set the value to $true...
>  [stress] Use named parameter arguments and explicitly set switch argument values

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
@seankane-msft this was super duper interesting.
Turns out, if it's a `HEAD` request, no matter WHAT the `Content-Length`  is, the spec says ignore the body. 
Easy fix once we understood. 👍
> [Test-Proxy] Address Empty-Body-Stream Error

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/request_with_subscriptionid.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/CustomDefaultMatcher.cs
@mccoyp @YalinLi0312  this will account for the different query _ordering_ between py2 and py3.
@JoshLove-msft , @seankane-msft , @HarshaNalluru I can't _think_ of any cases where this would negatively impact us (short of perf testing). You see any problems with this?
> [Test-Proxy] Match any URI Order

- tools/test-proxy/documentation/trusting-cert-per-language.md
@scbedd Resolves https://github.com/Azure/azure-sdk-for-python/issues/20932. This makes it more clear that the (fantastic) `trust_proxy_cert.py` script does almost all the work for you, and makes it more clear that the outputted environment variables need to be _persistently_ set.
> [Test Proxy] Update Python dev cert setup instructions

- eng/common/scripts/Update-DocsMsMetadata.ps1
For JS validation, we have to read package config from docs repo `ci-config` which needs to pass the docs repo location.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1239913&view=results
> Added more parameter for JS use

- eng/common/scripts/Invoke-GitHubAPI.ps1
Github issues get AI returns max of 30 issues. Long term fix is to add a new API to search for an GH issue with a given label. Work around is to increase the limit to avoid creating duplicate issues.
> Increase GitHub get issues fetch limit

- tools/mock-service-host/src/mid/coordinator.ts
- tools/mock-service-host/src/mid/models.ts
- tools/mock-service-host/src/webserver/validateAndMockController.ts
- tools/mock-service-host/test/unittest/testcoordinator.ts
.Net SDK don't send port in http header, so to use port in the request.socket.
> mock-service-host: use localPort

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Azure.Sdk.Tools.TestProxy.Tests.csproj
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
- tools/test-proxy/ci.yml
- tools/test-proxy/docker/dockerfile
- tools/test-proxy/docker/dockerfile-win
There are TLS issues when trying to communicate from .NET 6.0 to Test-Proxy compiled on 3.1.
Rather than try to workaround those issues, we agreed to just upgrade to 6.0.
> Upgrade to 6.0

- .azure-pipelines/apiview.yml
- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/apistub/_version.py
Python 3.6 is the latest version available as an extension for Azure web app. It seems Azure web app is not supporting new versions of Python as an extension. This change is to package Python 3.9 as part of deployment and APIView will use this integrated python version to generate review. This will be required only until we have sandboxing changes to offload review generation to pipeline. But Python 3.6 support needs to be dropped before 2022
> Package Python 3.9 in apiview deployment

- tools/mock-service-host/src/common/utils.ts
- tools/mock-service-host/src/mid/coordinator.ts
- tools/mock-service-host/src/mid/responser.ts
<s>1. Return {} when body is empty</s>
2. Escape query param
3. Remove null value before compare
4. Trim for example name
> Some compatible workaround for mock server

- eng/common/TestResources/New-TestResources.ps1
Resolves https://github.com/Azure/azure-sdk-tools/issues/2413
Until the AAD graph API is fully retired and we force local users to update to Az module 7.0.0, we need to support the breaking changes that come with Az 7.0.0 (detailed in the above issue).
Instead of trying to figure out which Az module is loaded and/or force a specific module version, this change creates a simple wrapper object for service principal creation that can handle the breaking changes between the AAD graph and MS graph objects. The two primary differences are:
1. The `ApplicationId` property becomes `AppId`
2. The service principal password is not created and returned on service principal create via the `Secret` property. Instead, you have to do a subsequent call to the `addPassword` MS Graph API. The best way I've …
> Support AAD graph and Microsoft Graph service principal APIs

- tools/mock-service-host/script/renew-ssh.ps1
- tools/mock-service-host/src/common/config.ts
- tools/mock-service-host/src/common/configSchema.ts
- tools/mock-service-host/src/mid/coordinator.ts
The oav exclude azurestack and dataplan path by default.
This PR make the excluded pattern as configurable and default as empty.
> mock-service-host: configurable excludedValidationPath

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingJavadocCodeSnippetsRule.java
This PR updates the Java ApiView generator to look for the new codesnippet tag when validating that classes and methods have the appropriate documentation. The old tag is still being checked for as some SDKs continue to use it, but once all tooling is transitioned to the new tag the old tag will be flagged as an error in ApiView (and likely won't allow SDKs to compile).
> Update ApiView to Check for new Codesnippet Tag

- eng/common/pipelines/templates/steps/prepare-pipelines.yml
- eng/pipelines/pipeline-generation.yml
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/ExitCondition.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/PipelineGenerationContext.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
This PR updates the weekly test pipeline to run by default for all services (which will behave like our weekday live tests). It also fixes a scheduling/bucketing problem where the weekly tests were running on both Saturday and Sunday.
Update: this PR also adds name collision detection for pipeline definitions, with a helpful log message for a workaround. Resolves https://github.com/Azure/azure-sdk-tools/issues/2474
Resolves https://github.com/Azure/azure-sdk-tools/issues/2377
> [pipeline generator] Build out weekly test pipelines for all services and fix scheduling

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
- eng/pipelines/stress-test-release.yml
The Azure Pipelines UI marks parameters that default to an empty string as "Required" which defeats the whole purpose of
having empty defaults. The overrides are only there as an option for people to use the pipeline for custom dev
environments. Since I think this scenario is pretty rare, I'm just going to remove support for it (you can still
deploy to custom dev environments via the same underlying scripts). Instead, this change simplifies the parameters
to have an environment drop-down that shows you all options to pick from.
> Remove cluster group and subscription overrides for stress test release

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/response_with_header_to_transform.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/response_with_retry_after.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/response_with_xml_body.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TransformTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ApplyCondition.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HeaderCondition.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ResponseTransform.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Transforms/ApiVersionTransform.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Transforms/ClientIdTransform.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Transforms/HeaderTransform.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Transforms/StorageRequestIdTransform.cs
Addresses https://github.com/Azure/azure-sdk-tools/issues/2482
Also, reworks Transforms to be applied on RecordEntry rather than HttpRequest/Response. This helps avoid duplicating the condition logic for sanitizers and transforms.
> Add header transform

- packages/java-packages/codesnippet-maven-plugin/pom.xml
- packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/SnippetBaseMojo.java
- packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
This PR updates `codesnippet-maven-plugin` to use a root directory and glob for finding README files to inject codesnippets. This follows the pattern currently being used by source files and allows for multiple READMEs to be injected.
> Add Root Directory and Glob for Injecting Snippets into READMEs

- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/apistub/_token_kind.py
Python reviews get a new version whenever parser version is changed even if APIs are not changed. This PS is to skip comparing parser version line.
> Skip parser version from comparison for Python reviews

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0002Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AzureAnalyzerTest.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AzureAnalyzerVerifier.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
i.e. the analyzer now regards client methods with either a CancellationToken or a RequestContext as complying with our cancellation guidance.
> Added support for RequestContext

- eng/pipelines/templates/steps/ref-updater.yml
Add link to the run that triggers a repo version update.
Should resolve https://github.com/Azure/azure-sdk-tools/issues/2501
Result of sample run https://github.com/Azure/azure-sdk/pull/3750
> Add link to triggering tools repo update run

- .azure-pipelines/apiview.yml
- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/api-stub-generator/tests/docstring_parser_test.py
- packages/python-packages/api-stub-generator/tests/function_parsing_test.py
- packages/python-packages/api-stub-generator/tox.ini
Fixes #2478.
Fixes #752.
https://apiviewstaging.azurewebsites.net/Assemblies/Review/170d3e834f4d48f28bc3d98e7c20d3d0?diffRevisionId=941daaf7bb3743c087fd6cb7a069b7e1&doc=False&diffOnly=True
Note that for Python 2 code, APIView does NOT read the typehints (except for return types). The type information comes from the docstring. Since we have dropped Python 2 support, there's no motivation to fix this.
Finally, this also updates the syntax for kwargs to match those obtained from type hints:
**old**: str = ...
**new**: Optional[str] = ...
> [Python APIView] Fix type parsing regression in Python 3.10

- packages/java-packages/codesnippet-maven-plugin/pom.xml
- packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
This PR updates `codesnippet-maven-plugin` to no-op when no Java source files and no README files for injection exist.
> Don't Fail codesnippet-maven-plugin when Sources Don't Exist

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/StringSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyStringSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/GeneralStringSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/HeaderStringSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/UriStringSanitizer.cs
@HarshaNalluru @timovv this takes care of #2504
> Adding String Literal Sanitizers

- eng/common/TestResources/New-TestResources.ps1
Az version 7.0.0 had an issue where new service principal credential creation would not automatically generate a password by default. To work around this, one had to pass in a password credential object with an empty password to get it to work.
With the update to 7.1.0, the behavior of creating a password automatically was restored, but it also appeared to change the parameter set such that the existing calls were broken (since we weren't passing a now required `ServicePrincipalId` parameter).
```
Cannot bind argument to parameter 'ServicePrincipalId' because it is an empty string.
```
This PR updates the script to handle 7.0.0 and >= 7.1.0 versions of Az. Eventually we can remove the special handling for 7.0.0 as no one should have it installed. For posterity in case anyone hits this, …
> Update test resources SP password creation to support Az >= 7.1.0

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ApplyCondition.cs
Related #2394 
Reasoning here is that `.NET 6` is not natively on our build machines. As a result of that, we will need a manual install step added to the test proxy tool version for every pipeline that consumes it. Given that most others aren't even using .NET, I feel like it's a bit of a burden on everyone's pipelines to pay the price of downloading the tool version.
The alternative is to increase the nuget size, but ship both versions. 
As the code base changes were quite simple, and tests all still check out, I feel like this may be the easiest path forward.
May need to adjust publishing ci in this PR as well. Let's see what shakes out.
> Cross-compile the test proxy to .net 5 in addition to .net 6

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_typehint_parser.py
- packages/python-packages/api-stub-generator/tests/function_parsing_test.py
- packages/python-packages/api-stub-generator/tests/typehint_parser_test.py
Fixes #2540. Fixes #2550.
**servicebus**
https://apiviewstaging.azurewebsites.net/Assemblies/Review/045e0b979aee451c936cb329c5074b82?diffRevisionId=513a37376cf74d51af0bb85f74d7a2f5&doc=False&diffOnly=True
**text-analytics**
https://apiviewstaging.azurewebsites.net/Assemblies/Review/24d470153e844ada80ced5d3f8b5ad16?diffRevisionId=a1661465606643ef8e5c66dcd2d182b4&doc=False&diffOnly=True
> [Python APIView] fix typehint parsing in Python 3.10

- packages/python-packages/api-stub-generator/tests/function_parsing_test.py
Closes #2548.
@kristapratico I couldn't replicate #2548 with the recent change, which may have fixed it. In any case, I added testcases to verify the typehint works correctly for both Python2 and 3-style typehints and prevent regressions. Thanks for filing an issue!
> [Python APIView] additional typehint tests

- eng/common/testproxy/docker-start-proxy.ps1
- eng/common/testproxy/test-proxy-tool.yml
`docker image` = `"1294199"`
`dotnet tool version` = `1.0.0-dev.20220113.1`
These versions were tested at https://github.com/Azure/azure-sdk-for-js/pull/19724.
This PR will sync all 8 repos to get the newer proxy tool everywhere.
> Update image tag and version at eng/common for proxy tool

- eng/common/scripts/artifact-metadata-parsing.ps1
As github api limit the body param length with 125000 characters, we have to truncate the release note if needed. Try to fix: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1293270&view=logs&j=6a8552c2-2ada-5ee5-a4d2-6fcf45f87c55&t=3cc31b8c-ba6f-566f-31dd-15c31084f71a
> fix: body is too long when create github release

- src/swift/SwiftAPIView/Sources/main.swift
- src/swift/SwiftAPIView/SwiftAPIView.xcodeproj/project.pbxproj
- uses discard to silence unchecked return
- replaces hardcoded binplace script phase with environment variable embed library phase
> removes SwiftAPI build warning and error on non-debug and Azure Pipelines machine

- src/swift/SwiftAPIView.xcworkspace/contents.xcworkspacedata
- src/swift/SwiftAPIViewCore/Sources/Extensions/DeclarationModifier+Extensions.swift
- src/swift/SwiftAPIViewCore/TestFiles/TestFile2.swifttxt
Ensures that the async nature of a function and whether it throws is used to generate the definition ID.
Fixes #2579
> [Swift APIView] Improve definition ID creation

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
ToString ends up decoding percent encoded URIs which is not a good representation of how the request really looks.
> Use AbsoluteUri rather than ToString

- eng/common/TestResources/New-TestResources.ps1
Currently there are some problems with the `Az.Resources` cmdlet v5.2.0 related to fetching service principals via the
graph API in private azure clouds. This manifests either as an error like below:
```
ClientSecretCredential authentication failed: AADSTS70011:
The provided request must include a 'scope' input parameter.
```
Or, if the `-MicrosoftGraphEndpointResourceId` parameter is supplied to the `Add-AzEnvironment` call, then the API
request returns a 500:
```
{"odata.error":{"code":"Request_DataContractVersionMissing","message":
{"lang":"en","value":"The specified api-version is invalid. The value must exactly match a supported version."}}}
```
I'm pretty sure there is still some missing functionality as support for non-public clouds was only recently added and
the AAD->MSGraph …
> Only fetch provision application oid via API if not supplied

- tools/identity-resolution/identity-resolution/Models/TeamMetadata.cs
- tools/identity-resolution/identity-resolution/Services/AzureDevOpsService.cs
- tools/notification-configuration/notification-creator/NotificationConfigurator.cs
We are having some issues where pipeline names that are just under the 64 character team name length limit, like `python - azure-communication-networktraversal - tests-weekly`. In these cases, they won't throw an error condition, but with the prefix separator `--` they hit the max and the team names are identical, when they need to be suffixed for either Notifications or Sync Notifications. If we move the suffix to a short prefix, it will avoid this name overlap issue altogether. Also, since the suffix often gets truncated down to a few characters anyway, I don't think we're losing any clarity of purpose, since the automation will also provide a clear description field like `purpose: ParentNotificationTeam` which gets shown in the team list view.
Trying to figure out the best way to test …
> Set notification team type as a prefix to avoid long name duplicates

- tools/notification-configuration/notification-creator/NotificationConfigurator.cs
This wasn't caught in the dry run (is there a server side validation API we could be using?)
```
Unhandled exception: Microsoft.TeamFoundation.Core.WebApi.InvalidTeamNameException: TF400472:
The following team name is not valid: [88] azure-uamqp-python - client.
Verify that the name does not exceed the maximum character limit, only contains valid characters, and is not a reserved name.
The following characters are not valid: @ ~ ;  ' + = , < > | / \ ? : & $ * " # [ ]
```
> Use valid characters for notification team name prefix

- eng/common/pipelines/templates/steps/verify-links.yml
Originally opened here: https://github.com/Azure/azure-sdk-for-c/pull/2080
note conversation here: https://github.com/Azure/azure-sdk-for-c/pull/2065#issuecomment-1019378327
The link verifier is lumping SDK urls with a suffix in with the root sdk. So "azure-sdk-for-c-**arduino**" is getting lumped in with "azure-sdk-for-c".
> remove greedy suffix on link check

- eng/common/docgeneration/Generate-DocIndex.ps1
@sima-zhu I was investigating Azure/azure-sdk-for-python#16794 and discovered this.
In the case where there is a "/" in the name it gets used directly! This means on a _browser_ that the link to the landing page won't ever render because a `/` means "next folder in" on a webserver!
So for the service `Database for MySQL/PostGreSQL`, this turns into path `databaseformysql/postgresql.html`. This is 404ing.
> fix incidentally added path addition

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordSession.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/CustomDefaultMatcher.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
I'm hoping this PR addresses:
#2612 
#2451
@kristapratico I will release a tool update once this goes in, then run your build on repeat until it either succeeds or we  get another repro on "collection".
> Lock modifiable session when adding sanitizers, return an entry AFTER we have exited the lock on Entries

- tools/stress-cluster/chaos/README.md
- tools/stress-cluster/chaos/examples/network-stress-example/templates/testjob.yaml
- tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/Job.cs
As we don't use the latest tag for images, this can cause annoying issues in local development where a tag is re-used but the image does not get updated after deploying. See [image pull policy defaults](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting).
> Update stress examples/generator to set imagePullPolicy: Always

- eng/common/scripts/Update-DocsMsMetadata.ps1
The PR is to fix the pipeline: 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1323052&view=results
The reason for the failure is track 1 package does not contain readme. We do not want to fail the pipeline in this case. Just printout message and pass the pipeline.
Pipeline got passed.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1330650&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b
> Non stop on errors.

- eng/common/scripts/Helpers/Metadata-Helpers.ps1
- eng/common/scripts/Update-DocsMsMetadata.ps1
We got several issues when enable the strict mode from scripts.
JS - mgmt pipeline: Failed at $LastExitCode not retrieved.
[Pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1343628&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=26ac1571-47fc-5d52-3897-39c8bdecf4db)
Doc msauthor failed by `Write-Error`, change to `Write-Warning`
[Pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1343627&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=4ddc76a6-85f2-526e-fa3e-b1020f31ed12)
> Fixed the failure from strict mode.

- tools/stress-cluster/cluster/azure/monitoring/stress-status-workbook.bicep
Closes #2386
Query diff:
...
StatusTable
| summarize arg_max(TimeGenerated, *) by TestName, **_Namespace_**
| join (FailTrend) on TestName, Namespace
...
Only adding a namespace on aggregation
> Stress status dashboard bug fix & double grid height

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Example output:
```
...
--> ebc92fc6db6
Successfully tagged stresstesttbiruti6oi24k.azurecr.io/ben/network-example:local
ebc92fc6db6a01318bb59c8bf8ab2eb8ca185e20e0fe06ac409bde4fca6fbc4c
Container image 'stresstesttbiruti6oi24k.azurecr.io/ben/network-example:local' successfully built. To run commands on the container locally:
docker run -it stresstesttbiruti6oi24k.azurecr.io/ben/network-example:local
docker run -it stresstesttbiruti6oi24k.azurecr.io/ben/network-example:local <shell, e.g. 'bash' 'pwsh' 'sh'>
To show installed container images:
docker image ls
To show running containers:
docker ps
```
> Print example docker commands after building stress image

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/DebugLogger.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpRequestInteractions.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/appsettings.json
This PR enables verbose logging of requests. 
- Uri/Headers for all requests (including during record/playback)
- Also dumps request bodies for parsable JSON running through the Admin controller.
As I've been digging through these "parallization" errors, A lot of the time I'm not finding real bugs, so much as test orchestration bugs. EG `python` firing admin/reset during test run, `go` doing the same.
- To enable deeper logging in CI, set build time variable `Logging__LogLevel__Default`=`Debug`
- This works the same way locally `set Logging__LogLevel__Default=Debug`
- Makes it a hard error the Admin/Reset when there are playback or recording sessions in progress.
TODO:
> [Test-Proxy] Enable Optional Verbose Logging

- src/go/cmd/content.go
- src/go/cmd/token_builders.go
Go doesn't require a name for method receivers. For example, this is valid:
```go
type Foo struct {}
// unnamed receiver of type Foo
func (Foo) Bar() {}
```
There are a couple places where apiview assumes a receiver has a name. This PR adjusts them so we get e.g. `func (AuthenticationFailedError) NonRetriable()` as output instead of a panic or malformed signature.
> Prevent panic on unnamed receiver

- tools/stress-cluster/cluster/azure/monitoring/stress-test-workbook.bicep
Added "Open external query button" for Pod/Container Events and container logs
> [stress test] add query button for dashboard

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/Update-TestResources.ps1
Updating the maximum lifespan of a resource group lease in accordance with the upcoming [resource management guidelines](https://github.com/Azure/azure-sdk-tools/pull/2663).
> [test resources] Add max value to DeleteAfter of 168 hours

- eng/common/TestResources/New-TestResources.ps1
This updates the `New-TestResources.ps1` script to not fail when extra unused parameters are passed in. This prevents the script from breaking if new keys/values are added to the subscription config object in keyvault (which gets splatted onto the script parameters [here](https://github.com/Azure/azure-sdk-tools/blob/9241b1955ba261e24ce4614fe99e99cc08f2aa95/eng/common/TestResources/deploy-test-resources.yml#L55)). Currently this is a problem with historical versions of the script that get run as part of a backport to a hotfix/release branch, where the old version of the script is not compatible with the subscription configuration parameters.
For example, the addition of `ProvisionerApplicationOid` [here](https://github.com/Azure/azure-sdk-tools/pull/2592) is causing issues for live test …
> Add catch-all parameter to test resources script

- eng/common/pipelines/templates/steps/credscan.yml
Failures: 
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1356766&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=a6c890d8-b83f-504d-afc5-f7ec178ffaaf
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1356945&view=logs&jobId=bc67675d-56bf-581f-e0a2-208848ba68ca&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=27a9db8a-8f0c-5ed5-0322-7c4d0e71b2e0
Reason: The targetbranch returns `refs/heads/main` instead of `main`. + Exclude the delete files and the renamed files.
Fix: Trim the 'refs/heads' and make the target branch as parameters.
Add common scripts for all changed files.
Testing pipelines: 
(Passed)~~https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1357479&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca~~ …
> Preprocess the target branch + Add checks on delete/rename files

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/DebugLogger.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
- tools/test-proxy/documentation/using-in-devops.md
Ended up needing the additional TestMismatch logging if a client doesn't report the mismatch error in CLI output.
> Adding another item to logging, extending devops docs

- eng/common/pipelines/templates/steps/credscan.yml
The PR is to fix the version issue. 
Aggregate-report currently using V3 which reports less errors than v2.
We clean up the errors based v3 instead of v2. 
We will use V3 for all pipelines as aggregate-report runs into OOM issue using v2.
Also, make changes to support the entire repo scanning.
> Change credscan to use v3 and enable scan entire repo

- eng/pipelines/pipeline-generation.yml
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyIntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/WeeklyUnifiedPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
This updates the pipeline generator tool to be able to generate weekly pipelines for repositories using a unified pipeline model (i.e. ci.yml runs both CI and live tests).
This also makes the pipeline variant naming consistent.
Before:
- ci - `lang - service - variant`
- pr - `lang - service - ci.variant`
- live tests - `lang - service - tests.variant`
- live tests weekly - `lang - service - tests-weekly.variant`
After:
- ci/unified - `lang - service - variant`
- weekly unified - `lang - service - variant - weekly`
- pr - `lang - service - variant - ci`
- live tests - `lang - service - variant - tests`
- live tests weekly - `lang - service - variant - tests-weekly`
Resolves #2678
> Generate weekly unified pipelines. Make variant naming consistent

- eng/common/pipelines/templates/steps/credscan.yml
The PR is to fix: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1363756&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=27a9db8a-8f0c-5ed5-0322-7c4d0e71b2e0
If the path contains special char, we scan the parent folder instead of the path
Testing pipeline:https://dev.azure.com/azure-sdk/public/_build/results?buildId=1369441&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76
command config
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1369513&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76
> Disable the config of encoding path in git

- eng/pipelines/notifications.yml
- eng/pipelines/templates/variables/globals.yml
Testing pipeline:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1366353&view=logs&s=7e5a62c6-a3ae-5561-387a-bc0babb014af
Timeout testing:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1369477&view=results
We replace kusto table with opensource API.
> Update the github-codeowner-subscriber version

- eng/common/testproxy/docker-start-proxy.ps1
- eng/common/testproxy/test-proxy-tool.yml
- Enables just the install (but our own run) of the test-proxy.
- We `dotnet tool install` to a specific path because `-g` doesn't properly register the tool shim on mac/linux platform
- Now we also prepend path so that we can use it with just the command name if we want to shell out from another process or the like
- Adding ability to specify binding URL via parameter
> [Test-Proxy] Updates to tool install parameters, bump targeted versions

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyStringSanitizer.cs
Addresses https://github.com/Azure/azure-sdk-tools/issues/2777
> Don't sanitize binary data when using BodyStringSanitizer
