Azure/azure-sdk-tools

- tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1
The version update is new, but both of the other code changes are due to my own regression and failure to test properly. Not cool.
> Resolve Issues with Transition Script

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/DebugLogger.cs
We need a cleaner way to do this, but I'm sick of seeing git output when we arent running in debug mode.
There doesn't seem to be a straightforward way to go from a ConfigurationBuilder directly to a logger that we can check `IsEnabled` against the level. Everything I find online assumes that it's actually running as part of the server. 
Probably just missing something, I'll keep looking.
Resolves #4404
> Address logging verbosity when not set to debug loglevel

- eng/scripts/Github-Project-Helpers.ps1
I missed committing one local update for #4456
> Add missing config backup when adding github status checks

- eng/pipelines/live-test-cleanup.yml
> Remove translation from resource cleanup

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
Adding in args to compare AMQP vs AMQP Websockets, and uamqp versus pyamqp
> [PerffAutomation] perf test arg updates for pyamqp

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitStoreTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationRestoreTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
> Asset-Sync only ever retrieves a single tag at a time

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
https://apiview.dev/Assemblies/Review/0862226da7d54839bb8597ee9a494ede
Suppresses all the random methods inherited from `_model_base`.
> [Python APIView] Suppress unwanted base class methods

- .azure-pipelines/apiview.yml
Fix pipeline failure; missing mandatory param to start test app
> Fix APIvIew pipeline test failure

- src/dotnet/APIView/APIViewWeb/Client/src/helpers.ts
- src/dotnet/APIView/APIViewWeb/Controllers/AccountController.cs
- src/dotnet/APIView/APIViewWeb/Controllers/UserProfileController.cs
- src/dotnet/APIView/APIViewWeb/Models/UserPreferenceModel.cs
- src/dotnet/APIView/APIViewWeb/Repositories/UserPreferenceCache.cs
- This fixes bug introduced when merging UserPreference with UserProfile.
> Tidy up UserPreference Logic

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
> Asset's clones don't store

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
> Combine approval indicator and request approval button

- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/CHANGELOG
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Program.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerAPIViewGenerator.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewDefinitions.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewRoot.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/Extension.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/SchemaCache.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/SwaggerSpec.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/SwaggerTypes.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/XMsParameterizedHost.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/SwaggerAPIViewTest.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/fixtures/ContentModerator.json
- Fix missing first property for definition
- Fix wrong "required" property in xMsParameterizedHost parameters by resolving parameter reference
- Show enum type for definition
- Support resolve reference from common types
Issue: 
- https://github.com/Azure/azure-sdk-tools/issues/4462
- https://github.com/Azure/azure-sdk-tools/issues/4463
- https://github.com/Azure/azure-sdk-tools/issues/4461
Link: https://apiviewstaging.azurewebsites.net/Assemblies/Review/4efa16b197314f9896478eeaa09cc8d2
> Swagger apiview improvement and bug fix

- tools/sdk-generation-pipeline/pipelines/steps/parse-and-publish-result.yml
Signed-off-by: Zhou Zheng <zhouzheng@microsoft.com>
> set SDK generation pr as draft

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
> [stress testing] Set default LimitRange for stress container resource requests

- src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Ensure Diff lines are calculated for revision added via DetectApiChanges codepath
> Ensure Diff lines are calculated

- src/dotnet/APIView/APIViewWeb/Pages/Error.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Error.cshtml.cs
Should fix https://github.com/Azure/azure-sdk-tools/issues/3495
> Improve Error Page

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
> [stress testing] Warn user when helm fails due to large files not being ignored

- eng/pipelines/eng-common-sync.yml
> Speed up sync eng/common pipeline

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewBadge.cshtml
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Update label name as per the feedback
> Update package name approval button label

- eng/common/scripts/Queue-Pipeline.ps1
- eng/pipelines/templates/steps/sync-directory.yml
The PR is to fix the issue of missing comments:
Expect the template pipeline information:
> Change the way of using env var

- eng/common/scripts/Create-APIReview.ps1
- eng/common/scripts/Helpers/ApiView-Helpers.ps1
- eng/common/scripts/Prepare-Release.ps1
Add new step in API check step to enforce package name approval for preview version release.
> Add new check in APIView to verify and enforce package name approval

- tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1
Minor fix for https://github.com/Azure/azure-sdk-tools/pull/4730. Things will still work either way.
> Use powershell argument syntax in test proxy transition script

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
Should fix https://github.com/Azure/azure-sdk-tools/issues/4695
> Extend GetReviewStatus to retrieve specific revies via reviewId

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
Resolves #4709 
Scenario:
1. User restores an assets.json using the `test-proxy` tool.
2. User attempts to push updates using the `test-proxy` docker image
3. The docker image encounters a conflict, as it cannot operate on the "unsafe" directory.
This is due to the fact that the docker container needs to globally configure its git to trust that dir regardless of who updated it. Because the initial restore was done by the `tool`, the portion of code that could run that trusted the assets directory was _not_ run. 
By adding `SetSafeDirectory` to `DetectPendingChanges`, we cover the the last entrypoint that could have this error scenario.
> Ensure that directory is set as "safe" in all docker cases

- tools/test-proxy/scripts/transition-scripts/generate-assets-json.ps1
Extending the transition script to allow one to PROVIDE their test-proxy exe.
> Bring Your Own Proxy Exe

- eng/common/pipelines/templates/jobs/perf.yml
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Cpp.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/ILanguage.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/JavaScript.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/LanguageBase.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Net.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Python.cs
- tools/perf-automation/tests.yml
- Rebased against main
- Taking in favor of #4034
> [Perf] Add profiling to perf automation

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Cpp.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/ILanguage.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/JavaScript.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/LanguageBase.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Net.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Python.cs
- Split long argument lists onto multiple lines
- Alphabetize members in ILanguage and LanguageBase
> [Perf] Move "profile" parameter before "context"

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
Most common that it's a directory. @heaths
> Reverse check of git folder/file

- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/CHANGELOG
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewOperation.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewParameter.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewPaths.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewResponse.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewSpec.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/SwaggerTypes.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerTokenSerializer.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/TokenSerializer.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/SwaggerAPIViewTest.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/fixtures/azureopenai.json
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/fixtures/personalizer.json
> Fix: Don't expand array reference in definition and AlwaysMultiline support for JsonSerializer

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/changelog/changelogGenerator.ts
- tools/js-sdk-release-tools/src/changelog/extractMetaData.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
also bump autorest version for swagger dpg automation script
> breaking change detection tools enhancement

- eng/common/scripts/Verify-AgentOS.ps1
This is a pre-requisite script before we migrate to win 2022 compliant pool. 
https://github.com/Azure/azure-sdk-for-cpp/pull/4064
> Update the regex to embrace more image names

- eng/pipelines/apiview-review-gen-cadl.yml
- eng/scripts/Create-Apiview-Token-Cadl.ps1
Set GitHub PAT as env variable to clone private repo
> Add github token when cloning cadl repo

- tools/sdk-generation-pipeline/documents/deployment/README.md
- tools/sdk-generation-pipeline/documents/task-engine/README.md
- tools/sdk-generation-pipeline/pipelines/steps/parse-and-publish-result.yml
1 add doc for DPG SDK Release App
2 update docker doc
3 change branchName of generated sdk PR
> Add sdk generation test changes to main

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
- eng/pipelines/pipeline-generation-single.yml
- eng/pipelines/pipeline-generation.yml
Updates the yaml to work with the new changes made in https://github.com/Azure/azure-sdk-tools/pull/4969
> Update pipeline generation yaml

- src/dotnet/APIView/APIViewWeb/Managers/OpenSourceRequestManager.cs
> Crete new HTTP client when requesting user info from opensource manager

- eng/common/pipelines/templates/jobs/perf.yml
This reverts commit 81c78afd563a32c224eb45b0cf864078d55b68eb.
> Revert "Migrate eng/common to Ubuntu 22.04" for perf.yml

- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
Addresses:
- https://github.com/Azure/azure-sdk-tools/pull/5007#discussion_r1061843571
> Minor message fix in `archetype-sdk-tool-dotnet.yml`: XOR to or

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
Resolves https://github.com/Azure/azure-sdk-tools/issues/4795.
> Support JPMS requires static for Java API review

- .azure-pipelines/apiview.yml
- eng/pipelines/apiview-review-gen-python.yml
- eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
> Update Selected APIView Python version to one in manifest

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
Add cpp to KV secrets perf tests, also added support for KV keys and certificates perf tests
> Cpp kv pipeline

- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/CHANGELOG
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerAPIViewGenerator.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/SchemaCacheTest.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/fixtures/dataPlaneTypes.json
Fix root schema circular reference issue by adding root schema ref in refChain. 
This PR is to address https://github.com/Azure/azure-sdk-tools/issues/5155
> fix root schema circular reference issue 

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
- tools/perf-automation/tests.yml
Evaluating Python 3.11 in perf automation pipeline.
> [Perf] Default to Python 3.11 in perf pipeline

- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
> Test .NET changes in multiple OSes

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
Temporarily removing the custom dropdown select due to performance issues.
Should resolve https://github.com/Azure/azure-sdk-tools/issues/5151
> Replace Revision dropdowns with default select

- eng/pipelines/templates/variables/globals.yml
Updating to deploy this PR:
- #5172
> Update ` Azure.Sdk.Tools.NotificationConfiguration` in `globals.yml` from `20230108.1` to `20230119.1`

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
- tools/perf-automation/tests.yml
- Continuation of https://github.com/Azure/azure-sdk-for-js/pull/24524
> [Perf] Upgrade Node from 14 to 18

- .azure-pipelines/apiview.yml
- eng/pipelines/templates/steps/apiview-ui-tests.yml
- src/dotnet/APIView/APIViewUITests/APIViewUITests.csproj
- src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
- Enable code coverage collection for internal APIView builds.
> Collect CodeCoverage for APIView

- eng/common/TestResources/New-TestResources.ps1
The warning message in this scenario is not the best, so I added some diagnostics for the common failure case here to try to be a bit more helpful for the user.
The specific error in question is for "The directory object quota limit for the Principal has been exceeded"
CC @kashifkhan
> Handle service principal creation quota errors

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
Fixes/adds support for running performance pipeline profiling when running with both Java 8 and Java 17.
> Fix Performance Pipeline Profiling when Using Java 17

- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/Azure.Sdk.Tools.SnippetGenerator.Tests.csproj
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/DirectoryProcessorTests.cs
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/TestData/EmptySnippet.md
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/TestData/Snippets.cs
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator/DirectoryProcessor.cs
> Check for empty snippets

- src/dotnet/APIView/APIViewWeb/README.md
Fixes https://github.com/Azure/azure-sdk-tools/issues/4665
> Add Create review instructions for swagger and CADL in APIVIew README

- tools/pylint-extensions/pylint-guidelines-checker/setup.py
this version is so that I can run the new pylint checks on pylint-next
> bump version for pylint-next pipeline

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
Use checkmark to indicate approval in Revision DropDown
> Use Approved Check Mark

- eng/label-to-project.config
- eng/scripts/Github-Project-Helpers.ps1
@maririos this should fix the action that adds issues to a project.
> Switch to ProjectV2 graphql apis for project helpers

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts
- tools/js-sdk-release-tools/src/utils/backupNodeModules.ts
it's a temp solution. We need to fix it in the sdk automation pipeline side.
> remove the node_modules set by pipeline to avoid rush build failure

- eng/pipelines/apiview-review-gen-swagger.yml
Update swagger API parser that is used for manual API review gen.
> Update Swagger parser version used for manual API review gen

- src/dotnet/APIView/apiview.yml
- tools/apiview/parsers/js-api-parser/ci.yml
- tools/apiview/parsers/js-api-parser/package.json
Updated ts-node and typescript dependency to resolve API parsing issue for JS packages
> Update JS api parser dependency

- tools/stress-cluster/cluster/provision.ps1
Adds a step to install preview features in the cluster (not available via bicep yet). First feature being added is the [image cleaner](https://learn.microsoft.com/en-us/azure/aks/image-cleaner?tabs=azure-cli) which removes stale/vulnerable images from the container image cache on cluster nodes.
> Register preview features in stress cluster

- tools/sdk-generation-pipeline/common/config/rush/pnpm-lock.yaml
- tools/sdk-generation-pipeline/packages/sdk-generation-cli/package.json
- tools/sdk-generation-pipeline/packages/sdk-generation-lib/package.json
Fix Security Issues for sdk generation pipeline
> Fix Security Issues for sdk generation pipeline

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
Add width limit to avoid showing large GitHub profile image.
> Add width property to reviewer image in API review page

- tools/sdk-generation-pipeline/Dockerfile
details: https://github.com/npm/rfcs/issues/546#issuecomment-1280967238
> upgrade npm to fix permission issue with root user

- src/dotnet/APIView/APIViewWeb/Client/css/shared/bootstraps-overrides.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Samples.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
Update color of disabled button and upload control.
> Some minor layout and css update

- eng/common/pipelines/templates/jobs/perf.yml
- tools/perf-automation/tests.yml
- Fixes #5466
- Partially reverts #5456
> [Perf] Add vmImage back to common perf.yml

- eng/common/pipelines/templates/steps/check-spelling.yml
> [check-spelling] Temporarily pin Node 18 to 18.13.0

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
Resolved https://github.com/Azure/azure-sdk-tools/issues/5470
Fix bug in Show Hidden API option.
> Resolve Hidden Api Bugs

- src/dotnet/APIView/APIViewWeb/Client/css/shared/bootstraps-overrides.scss
- src/dotnet/APIView/APIViewWeb/Client/css/shared/icons.scss
- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.ts
- src/dotnet/APIView/APIViewWeb/Client/src/shared/comments.ts
- src/dotnet/APIView/APIViewWeb/Client/src/shared/helpers.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CodeLinePartial.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_DiagnosticsPartial.cshtml
- Resolve issue with comments in swagger sections.
- Add Associated reviews for all languages.
- Improve search placeholder text.
> Resolve Associated Reviews and Comment Issues

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
Resolves https://github.com/Azure/azure-sdk-tools/issues/5364
> Add API to get status of package name Approval

- src/dotnet/APIView/APIViewUITests/SmokeTests.cs
- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- Fix bug in request reviewers
> Fix bug in request reviewers

- src/dotnet/APIView/APIViewUITests/SmokeTests.cs
- Disable test to unblock release.
> Skip Flaky UI Tests

- eng/pipelines/templates/steps/apiview-ui-tests.yml
- src/dotnet/APIView/APIViewUITests/SmokeTests.cs
> Bug fix/UI tests

- eng/pipelines/apiview-review-gen-cadl.yml
- eng/scripts/Create-Apiview-Token-Cadl.ps1
CADL package should be installed from package.json and also added a debug line to show installed packages.
> Install packages from cadl package and list installed packages

- eng/common/scripts/Test-SampleMetadata.ps1
To make sample script use correct product slug.
Related PR: https://github.com/Azure/azure-sdk-for-net/pull/34618
> Add product slug for Web PubSub

- eng/scripts/live-test-resource-cleanup.ps1
Preventing spurious pipeline warning emails when we try to tag resource groups that have been marked for deletion after we queried them. For example https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2199954&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=2ae92968-c003-547a-10d9-00fa5e34d21d&l=323
> Handle resource group deprovision race condition

- tools/test-proxy/documentation/test-proxy/trusting-cert-per-language.md
> Small updates to `trusting-cert-per-language.md`

- src/dotnet/APIView/APIViewWeb/Client/css/shared/codeline.scss
Resolves https://github.com/Azure/azure-sdk-tools/issues/5638
> Ensure hidden apis are greyed out

- tools/apiview/emitters/typespec-apiview/CHANGELOG.md
- tools/apiview/emitters/typespec-apiview/package.json
- tools/apiview/emitters/typespec-apiview/src/namespace-model.ts
- tools/apiview/emitters/typespec-apiview/src/version.ts
- tools/apiview/emitters/typespec-apiview/test/apiview.test.ts
> [TypeSpec APIView] Fix issue with Enums containing spreads

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Net.cs
- tools/perf-automation/tests.yml
Validation build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2593387&view=results
> Add dotnet-trace as profiler for Net

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
> Dump Proxy Version on every command

- eng/common/pipelines/templates/steps/check-spelling.yml
* This reverts commit 8a02e02adfc0d213509fce2764132afa74bd4ba4
* Fixes #5538
> Revert "[check-spelling] Temporarily pin Node 18 to 18.13.0 (#5537)"

- src/dotnet/APIView/APIViewUITests/APIViewUITests.csproj
Fixes https://github.com/Azure/azure-sdk-tools/issues/5765
> Update chrome driver version

- tools/test-proxy/documentation/asset-sync/README.md
Fixes outdated links to asset sync documentation.
> [Test Proxy] Update recording asset transition script links

- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
Changes in response to https://github.com/Azure/azure-sdk-tools/pull/5586#discussion_r1134316124
> Update Pull Request search to use contain rather than EndsWith

- src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewUploadHelp.cshtml
Resolves https://github.com/Azure/azure-sdk-tools/issues/5767
> Update C++ Instructions

- eng/python/assets-automation/generate_assets_report.py
Broken by code move. Updating to reflect.
> Hotfix report link

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
- tools/js-sdk-release-tools/src/llc/utils/prepareCommandToInstallDependenciesForTypeSpecProject.ts
- tools/js-sdk-release-tools/src/llc/utils/updateTypeSpecProjectYamlFile.ts
- tools/js-sdk-release-tools/src/utils/getOutputPackageInfo.ts
Update command in codegen in JS command
> Update command in codegen in JS command

- src/dotnet/APIView/APIViewWeb/Client/src/pages/revisions.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewUploadHelp.cshtml
Depend on https://github.com/Azure/azure-sdk-tools/pull/5708
> Update Instructions for uploading TypeSpec

- eng/pipelines/apiview-review-gen-python.yml
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Update Python API parser version in APIView and manual API review gen pipeline.
> Update Python API parser to 0.3.7

- tools/sdk-generation-pipeline/Dockerfile
- tools/sdk-generation-pipeline/documents/docker/README.md
- tools/sdk-generation-pipeline/documents/task-engine/schema/GenerateAndBuildInputSchema.json
- tools/sdk-generation-pipeline/packages/sdk-generation-cli/src/cli/dockerCli/core/DockerContext.ts
- tools/sdk-generation-pipeline/packages/sdk-generation-cli/src/cli/dockerCli/core/DockerTaskEngineContext.ts
- tools/sdk-generation-pipeline/packages/sdk-generation-cli/src/cli/dockerCli/core/tasks/GenerateAndBuildTask.ts
- tools/sdk-generation-pipeline/packages/sdk-generation-cli/src/cli/dockerCli/schema/dockerCliInput.ts
- tools/sdk-generation-pipeline/packages/sdk-generation-cli/test/unit/DockerTaskEngine.test.ts
- tools/sdk-generation-pipeline/packages/sdk-generation-lib/src/types/taskInputAndOuputSchemaTypes/GenerateAndBuildInput.ts
- tools/sdk-generation-pipeline/packages/sdk-generation-lib/src/types/taskInputAndOuputSchemaTypes/GenerateAndBuildInputSchema.json
- tools/sdk-generation-pipeline/pipelines/steps/generate-sdk.yml
- tools/sdk-generation-pipeline/sdk-generation-pipeline.yml
- tools/sdk-testgen/packages/autorest.testmodeler/README.md
rename cadl to typespec;
update maven binary location.
> typespec renaming

- tools/pylint-extensions/azure-pylint-guidelines-checker/ci.yml
We renamed the package. Need to update the CI to also trigger off that same directory.
> Repair checker ci.yml

- src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
- src/dotnet/APIView/APIViewUnitTests/LanguageServiceTests.cs
- src/dotnet/APIView/APIViewWeb/Client/src/pages/index.ts
- src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewUploadHelp.cshtml
- Update TypeSpec review creation instructions https://github.com/Azure/azure-sdk-tools/issues/5849 and https://github.com/Azure/azure-sdk-tools/issues/5273
- Fis bug in create review modal https://github.com/Azure/azure-sdk-tools/issues/5847
> Bug fix/type spec upload

- eng/common/scripts/TypeSpec-Project-Sync.ps1
Fix issue https://github.com/Azure/azure-sdk-tools/issues/5994
- update the sparse-checkout path every time
> update sparse checkout path every time

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ModuleInfoDiagnosticRule.java
> Diagnostic rule for exporting implementation package

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
Just a small tidbit addressing #5363
> Add small detail to test-proxy readme

- eng/scripts/python/assets-automation/generate_assets_report.py
@billwert @alzimmermsft 
`408 packages / 1% transitioned` --> `236 packages / 6% transitioned`
[Summary](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/834/Test-Proxy-Transition-Overview)
[Details](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/936/Java-Details)
> Adjust `Java` asset transition script

- src/dotnet/APIView/APIViewUITests/SmokeTests.cs
Update UI tests so it does not fail on input validation
> Update UI Tests

- eng/scripts/python/assets-automation/generate_assets_report.py
Exclude internal packages which do not have test recordings
Exclude azcore which does not use test recordings or proxy
> Add exclusions for internal packages

- src/dotnet/APIView/APIViewWeb/Hubs/NotificationHub.cs
> only create signalR group when name is not empty

- tools/test-proxy/documentation/asset-sync/README.md
Ensuring we recommend placing `assets.json` with your package.
> Update language to align with migration script

- src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
Add Retry logic to DownloadPackageArtifact
> Add Retry logic to DownloadPackageArtifact

- eng/common/scripts/Test-SampleMetadata.ps1
Want to merge feature branch to main in Java repo.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=2787962&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=b42a4c77-4205-522f-5a57-db739203b1a5
https://github.com/Azure/azure-sdk-tools/blob/main/doc/common/common_engsys.md#workflow
> Add Azure OpenAI

- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/CHANGELOG
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerAPIViewGenerator.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj
Resolves issues in https://github.com/Azure/azure-rest-api-specs/pull/23781 and https://github.com/Azure/azure-rest-api-specs/pull/23929
> Update reference used to retrieve parameter from cache

- tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
- tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_pylint_custom_plugins.py
list_ -> ItemPaged
ItemPaged - > list_
Addressses: https://github.com/Azure/azure-sdk-for-python/issues/26681
> [Pylint] Update linter iterable rule

- src/dotnet/APIView/APIViewWeb/Client/css/shared/codeline.scss
- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.module.ts
- src/dotnet/APIView/APIViewWeb/Client/tests/end-to-end/pages/review.spec.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
Resolves https://github.com/Azure/azure-sdk-tools/issues/4779
> Show comment icon on section heading

- eng/scripts/python/assets-automation/generate_assets_report.py
> Adjust assets reporting to align to feedback from java team

- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/RequestedReviews.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
Fixes [#4604](https://github.com/Azure/azure-sdk-tools/issues/4604)
> add APIView requested by 

- src/dotnet/APIView/APIViewWeb/Client/src/shared/comments.ts
Fixes [#4584](https://github.com/Azure/azure-sdk-tools/issues/4584)
> Hovering over APIView comment icon shows comment in popup 

- src/dotnet/APIView/APIViewWeb/Client/src/shared/comments.ts
> Unhide resolved comment when hovering in APIView

- src/dotnet/APIView/APIViewWeb/Managers/OpenSourceRequestManager.cs
Added retry to handle random failures when checking user authorization.
> Add retry to verify user authorization using OSS API

- src/dotnet/APIView/APIView/APIView.csproj
- src/dotnet/APIView/APIViewIntegrationTests/APIViewIntegrationTests.csproj
- src/dotnet/APIView/APIViewUITests/APIViewUITests.csproj
- src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
Update Chrome Driver to get UI Test passing.
> Update Chrome Driver and update to dotnet 7.0

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
Integrate the common script for js code gen in data-plane, https://github.com/Azure/azure-sdk-tools/blob/main/doc/common/TypeSpec-Project-Scripts.md#typespec-project-processps1.
fixes https://github.com/Azure/azure-sdk-tools/issues/5422
- Successful build is here: https://github.com/openapi-env-test/azure-rest-api-specs/pull/3657
- Failed build is here: https://github.com/openapi-env-test/azure-rest-api-specs/pull/3660
> Integration common script for js data-plane gen command

- tools/sdk-testgen/common/config/rush/pnpm-lock.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.json
- tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.md
- tools/sdk-testgen/packages/autorest.testmodeler/package.json
> Upgrade testmodeler

- src/swift/SwiftAPIView/SwiftAPIView.xcodeproj/project.pbxproj
- src/swift/SwiftAPIViewCore/SwiftAPIViewCore.xcodeproj/project.pbxproj
Fix #6324.
After pulling this change you may need to refresh your package dependencies, clean and rebuild.
> Fix Bad Depdendency

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
- src/java/apiview-java-processor/pom.xml
Increment Java API review parser to auto upgrade existing reviews.
> Update API view parser version for Java

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
Resolves https://github.com/Azure/azure-sdk-tools/issues/6254
> Disable show diff only feature for swagger reviews

- eng/pipelines/templates/steps/sync-repo-merge-branch.yml
If there is no diff then don't push the branch and create the PR.
> Check if there is any diff before for the merge branch scripts

- .github/CODEOWNERS
Updating code owners for .NET and repository tooling.
> CODEOWNERS: Add .NET owners

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Samples.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
Resolves https://github.com/Azure/azure-sdk-tools/issues/6182
> Ensure Comments show up on conversiation page regardless of comment setting on review page.

- tools/test-proxy/scripts/test-scripts/CLIIntegration.Tests.ps1
With the previous PR, I added a test (line 509 in the same file where this new test is being added) that ensures we don't accidentally discard changes. This new one is simply a sanity check to ensure we DO properly discard changes when intentionally SWITCHING tag.
> Adding an additional `restore` CLI integration test

- src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
SetDevOpsClientHeaders in constructor to prevent NullReferenceException thrown arbitrarily due to thread safety issues. 
Should resolve https://github.com/Azure/azure-sdk-tools/issues/6486
> SetDevOpsClientHeaders in constructor

- eng/pipelines/mirror-repos.yml
Add ARMCoreRPDev and InternalARMContracts long lived branches to the set of branches to keep updated.
> Add merging to more branches in specs repo

- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.module.ts
- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.ts
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Specs/Schema.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Specs/SchemaTableItem.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewDefinitions.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewOperation.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewParameter.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewPaths.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewResponse.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewRoot.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewSpec.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/TokenSerializer.cs
Change includes.
- Changes to the parser to allow Navigating to Definition
- Updates to UI to expand definition and scroll to appropriate definitions.
Example https://apiviewuat.azurewebsites.net/Assemblies/Review/60234aa82c8045e5b5d6951cfd04498f
> Add Jump links from Models to Definitions

- tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstNode.cpp
- tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstNode.hpp
- tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/ProcessorImpl.cpp
- tools/apiview/parsers/cpp-api-parser/ParseTests/TestCases/ExpressionTests.cpp
- tools/apiview/parsers/cpp-api-parser/ci.yml
- tools/apiview/parsers/cpp-api-parser/cmake-modules/AzureVcpkg.cmake
- tools/apiview/parsers/cpp-api-parser/vcpkg.json
> Fixes for cognitive services; Fixed issue #6054; Private virtual methods should be included in ApiView

- tools/assets-automation/assets-reporting/generate_assets_report.py
@benbp asked if the report had moved, due to someone asking him.
The answer is yes, it did. Reflecting in report generation.
> Update Report Link

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
Update version of github-event-processor for the following [bug fix](https://github.com/Azure/azure-sdk-tools/pull/6506)
> Update version of github-event-processor

- eng/common-tests/psmodule-helpers/Install-Module-Parallel.ps1
- eng/common-tests/psmodule-helpers/InstallModuleParallel.ps1
- eng/common/scripts/Helpers/PSModule-Helpers.ps1
> Make helper function "Install-ModuleIfNotInstalled" threadsafe

- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.module.ts
Resolves bug in comment bubbles for Swagger APIView review Pages
> Fix bug in comments bubbles for collapsible sections

- .github/CODEOWNERS
Add entries for code-owners-parser, github-event-processor and github-team-user-store,
> Add tools owners to CODEOWNERS

- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.module.ts
- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.ts
Resolves https://github.com/Azure/azure-sdk-tools/issues/4780
> Add ability to expand swagger deeplinks

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
Prevent failure in Show Diff only when there is no diff between revisions.
Resolves https://github.com/Azure/azure-sdk-tools/issues/6493
> Bugfix for ShowOnlyDiff feature

- packages/python-packages/apiview-gpt/output.json
- packages/python-packages/apiview-gpt/src/_gpt_reviewer.py
- packages/python-packages/apiview-gpt/src/_models.py
Merges multiple violations for the same line into a single violation. Assigns line numbers to each violation.
> [APIView-GPT] Combine multiple violations for the same line

- src/dotnet/APIView/APIViewIntegrationTests/TestsBaseFixture.cs
- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.module.ts
- src/dotnet/APIView/APIViewWeb/Client/src/shared/comments.ts
- src/dotnet/APIView/APIViewWeb/Client/src/shared/helpers.ts
- src/dotnet/APIView/APIViewWeb/Client/src/shared/signalr.ts
- src/dotnet/APIView/APIViewWeb/Hubs/SignalRHub.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
Replacement for https://github.com/Azure/azure-sdk-tools/pull/6547
> Resolve Bug in comment autoRefresh

- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
> Update PythonLanguageService.cs to use 0.3.8

- src/dotnet/APIView/APIViewWeb/Client/package.json
- src/dotnet/APIView/APIViewWeb/Client/src/shared/helpers.ts
> Fix user icon bug

- eng/pipelines/apiview-review-gen-python.yml
Update API parser for Python to 0.3.8
> Update Python API parser version in Sandboxing pipeline

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
> Set DOCKER_BUILDKIT to 1 in stress deploy image build

- src/dotnet/APIView/APIViewWeb/Client/src/shared/comments.module.ts
- src/dotnet/APIView/APIViewWeb/Client/src/shared/comments.ts
- src/dotnet/APIView/APIViewWeb/Client/src/shared/helpers.ts
- src/dotnet/APIView/APIViewWeb/Client/src/shared/signalr.ts
Resolves https://github.com/Azure/azure-sdk-tools/issues/6565
> Resolve bug in Comment Auto Refresh

- src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
Attempt to resolve https://github.com/Azure/azure-sdk-tools/issues/6609
> Update GetFromDevopsAsync Retry Logic

- src/dotnet/APIView/APIViewUITests/APIViewUITests.csproj
Update driver version to match version on Build Agent
> Update Selenium Driver Version

- tools/test-proxy/tests.yml
Azure.Core test framework has some excellent filename encoding tests that gotcha-ed a proxy roll-out a couple weeks ago. Adding those to our nightly integration tests so we can catch it earlier next time!
> Add Azure.Core.TestFramework tests to nightly integration

- tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstDumper.cpp
- tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstDumper.hpp
- tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/AstNode.cpp
- tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/JsonDumper.hpp
- tools/apiview/parsers/cpp-api-parser/ApiViewProcessor/TextDumper.hpp
- tools/apiview/parsers/cpp-api-parser/ParseTests/tests.cpp
Update ApiView tool to have a single DefinitionId for each type.
> Only have a single DefinitionId for each type

- .github/CODEOWNERS
> Update CodeOwners File

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/hlc/generateMgmt.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
fixes https://github.com/Azure/autorest.typescript/issues/1939
> Upgrade the autorest core version

- eng/common/scripts/TypeSpec-Project-Generate.ps1
- eng/common/scripts/common.ps1
- Use local feed view in the generated npmrc file
- Use eng/emitter-package-lock.json if present
> Use emitter-package-lock.json and @local feed view

- packages/python-packages/apiview-gpt/requirements.txt
- packages/python-packages/apiview-gpt/src/_gpt_reviewer.py
Seems like loadenv() w/o .env makes web app behave weird.
> remove loadenv

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
> Disable GPG signing on commit

- tools/pipeline-witness/infrastructure/kusto/functions/users/kojamroz/SpecsPipelinesBuildsJobLogs.kql
See the comment in the added function for details.
I followed the guidance I wrote down earlier here:
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/625/Kusto-Query-Catalog?anchor=adding-functions-to-%60azsdkengsys%60-cluster
> Add Kusto function definition of SpecsPipelinesBuildsJobLogs.kql

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpRequestInteractions.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerList.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
> Support Bulk Sanitizer Add

- packages/python-packages/apiview-gpt/.gitignore
- packages/python-packages/apiview-gpt/cli.py
- packages/python-packages/apiview-gpt/scratch/comments/python.json
- packages/python-packages/apiview-gpt/scratch/output/python/noodle.json
- packages/python-packages/apiview-gpt/src/_gpt_reviewer.py
This will allow manually playing with prompts easily in the playground in order to debug issues and tune our prompt templates.
> [APIView GPT] Add support for dumping request prompts

- packages/python-packages/apiview-gpt/scratch/apiviews/typescript/openai.txt
- packages/python-packages/apiview-gpt/scratch/apiviews/typescript/pasta.txt
- packages/python-packages/apiview-gpt/scratch/comments/typescript.json
- Part of the Hackathon project adding some good and bad samples for api view in typescript and some sample comments
> [gpt-api-view] update typescript examples for api view and comment samples

- packages/python-packages/apiview-gpt/scratch/output/typescript/pasta.json
- packages/python-packages/apiview-gpt/src/_sectioned_document.py
Also fixes the logic that splits sections of the SectionedDocuments to work with languages that use curly-braces.
> [APIView GPT] Typescript fixes

- packages/python-packages/apiview-gpt/scratch/comments/typescript.json
- packages/python-packages/apiview-gpt/scratch/output/typescript/openai.json
- packages/python-packages/apiview-gpt/scratch/output/typescript/pasta.json
Adds comments and regenerates outputs.
> [APIView GPT] TypeScript document additions

- tools/github-event-processor/README.md
I was reading through the readme to answer another question, and found a couple broken links. Figured it was easier to just submit a fix versus reporting anywhere
> Fix internal links in `github-event-processor`

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
> Add note about port utilization on MacOS

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
Just a readme update. @samvaity for FYI.
> Additional Documentation for `Matcher` and `Transform` concepts

- tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen.Tests/mergedChangelog1.md
- tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen/ChangeLogResult.cs
- tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen/Context.cs
- tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen/Report/Release.cs
- tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen/Report/ReleaseNoteGroup.cs
1. change CHANGELOG.MD to CHANGELOG.md for case-sensitive environment
2. Move spec version bump to Features Added release group
> some improvements per feedback

- tools/tsp-client/src/index.ts
- Add missing awaits in main
- Pass emitter options to all generate calls
> [tsp-client] Code fixes

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
We made a change recently to create release plan work item as parent of package work item and set release plan as child of product work item. This PR is to revert some of those changes and set package work item as the children of product work item because each package work item it created for a major-minor version of a package, but release plan will be created for each individual releases including bug fixes. Devops allows setting only one work item as parent so a package work item cannot have more than one release plan as parent.
> Set product as parent of package work item.

- doc/engsys_resource_management.md
- eng/pipelines/live-test-cleanup.yml
- eng/scripts/Remove-WormStorageAccounts.ps1
- eng/scripts/live-test-resource-cleanup.ps1
Changing our policies to set a max time ANY resources can live in a chosen subscription, if enabled.
> Add max lifespan parameter to resource groups

- tools/tsp-client/package.json
- tools/tsp-client/src/git.ts
- tools/tsp-client/src/index.ts
Changes in this PR:
- Use supported simple-git functions (Fixes #7090)
- Improve local spec support to copy files from local repo and include additional directories (PArt of #7010) 
Fixes #7045
> [tsp-client] Improve local spec support

- tools/assets-automation/asset-sync/README.md
@alzimmermsft for FYI. Here's what I mentioned I'd add to our docs for your pain :)
> Add Note about `404` due to capitalization

- tools/assets-automation/assets-reporting/generate_assets_report.py
> Fix Reporting Issue for Java

- eng/scripts/live-test-resource-cleanup.ps1
> Clean up arm deployments with secret parameters

- eng/scripts/live-test-resource-cleanup.ps1
I think the storage account cleanup script works reliably enough now that we can integrate into the main live test resource cleanup pipeline.
> Add storage account immutability cleanup to live test resources script

- eng/common/scripts/Delete-RemoteBranches.ps1
- eng/pipelines/branch-cleanup.yml
- Update to use the gh cli for github operations
- Switch to using graphql for pulling branches as the rest api starts to fail after a certain number of branches and we can also pull back all the associated data like pull request info and commit date all in one query.
Fixes https://github.com/Azure/azure-sdk-tools/issues/5091
> Update branch deletion code

- src/dotnet/APIView/APIViewUITests/APIViewUITests.csproj
> Update Chrome driver to latest for APIView UI test

- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
Search to check again revisions using exists clause instead of array_slice to improve query performance
> Update search query to use exists to verify revisions data

- eng/pipelines/templates/stages/archetype-autorest-preview.yml
- Add support for optional test stage
- Add support for PR title based on generation success
- Add initialization steps for autorest repo jobs
> Add optional test stage to autorest preview pipeline

- tools/test-proxy/tests.yml
> Repair JS Proxy Integration Tests

- tools/tsp-client/README.md
Update `tsp-client` tool README information.
> [tsp-client] Update README

- eng/common/scripts/Prepare-Release.ps1
> Avoid unnecessary CHANGELOG release date prompt

- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
Update Package version so it can be listed in API review revision
> Set Package version in API review code File for .NET

- packages/python-packages/apiview-stub-generator/CHANGELOG.md
- packages/python-packages/apiview-stub-generator/apistub/_apiview.py
- packages/python-packages/apiview-stub-generator/apistub/_stub_generator.py
- packages/python-packages/apiview-stub-generator/apistub/_version.py
- packages/python-packages/apiview-stub-generator/apiview_reqs.txt
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Update Package version for Python and upgrade existing reviews to rebuild code file.
> Set package version in API review code File for Python

- tools/apiview/parsers/js-api-parser/export.ts
- tools/apiview/parsers/js-api-parser/models.ts
- tools/apiview/parsers/js-api-parser/package.json
Update package version in code for JS
> Update package version in code file for JS

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- src/java/apiview-java-processor/pom.xml
Run upgrade of API reviews to update package version in cosmos DB
> Run upgrade of API reviews to update package version in cosmos DB

- src/dotnet/APIView/APIViewUITests/SmokeTests.cs
Skip the smoke test for APIView to find request reviewers element.
> Skip the test to find request review element

- eng/pipelines/templates/steps/apiview-ui-tests.yml
- src/dotnet/APIView/APIViewUITests/SmokeTests.cs
Skip APIView smoke test to unblock APIView release.
> Skip APIView smoketest

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
Set Package version in code file when parses the jar file so it can be included in review metadata.
> Include package version in code file for Java API review

- eng/pipelines/apiview-review-gen-python.yml
> Update python parser version in APIView sandbox pipeline

- src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
- src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosAPIRevisionsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/ICosmosAPIRevisionsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/ICosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
This add `ReviewBackgroundHostedService` for updating reviews now apiRevisoins.
Depends on merge of https://github.com/Azure/azure-sdk-tools/pull/7303/files#diff-b0398569b9b71cf1282bf6e43715139075ab4d1adfe46b7b512434b7097858ab
> Re Add ReviewBackgroundHostedService.cs

- src/dotnet/APIView/APIViewWeb/Controllers/ReviewController.cs
- src/dotnet/APIView/APIViewWeb/Helpers/ManagerHelpers.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/ICodeFileManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosAPIRevisionsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/ICosmosAPIRevisionsRepository.cs
Depends on merge (and rebase) of https://github.com/Azure/azure-sdk-tools/pull/7303 and https://github.com/Azure/azure-sdk-tools/pull/7331 and https://github.com/Azure/azure-sdk-tools/pull/7336
> Re Add Review Controller

- src/dotnet/APIView/APIViewWeb/Helpers/PageModelHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/ReviewListModels.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/ICosmosReviewRepository.cs
Adds logic to find Legacy Review from Legacy Database, resolve the current review Id of the revied and redirect to the new review page.
> Re architect/LegacyReviewSupport

- src/dotnet/APIView/APIViewWeb/HostedServices/LinesWithDiffBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- Adds Background Tasks for computing the line numbers of diffs.
> Add Task for Comuting Line numbers swagger diffs

- eng/pipelines/mirror-container-images.yml
- eng/scripts/mirror-container-image.ps1
Pipeline at https://dev.azure.com/azure-sdk/internal/_build/index?definitionId=6572
> Add mirror container image pipeline

- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
- src/dotnet/APIView/APIViewUnitTests/CodeFileBuilderTests.cs
- src/dotnet/APIView/APIViewUnitTests/ExactFormatting/Attributes.cs
- src/dotnet/APIView/APIViewUnitTests/InternalsVisibleTo/Inheritance.cs
- src/dotnet/APIView/APIViewUnitTests/InternalsVisibleTo/Properties.cs
closes https://github.com/Azure/azure-sdk-tools/issues/7344
API view with this change (showing Azure.Core)
> Show internal System.Diagnostics.CodeAnalysis attributes

- src/dotnet/APIView/CloneAPIViewDB/CloneAPIView/Program.cs
- Prevent duplicate entries for approved for first Release
> API Review DB Migration

- src/dotnet/APIView/APIViewWeb/Helpers/ChangeHistoryHelpers.cs
- src/dotnet/APIView/APIViewWeb/Helpers/PageModelHelpers.cs
- Resolve Bug in Swagger Diff
- Resolve Bug in APIRevision Deletion
> Fix bug in apiRevision deletion

- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
- src/dotnet/APIView/APIViewWeb/HostedServices/LinesWithDiffBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
- Fixes failures preventing the creation of Pull Request Reviews
> Fix Failures when Creating Pull Request Reviews

- src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- Enables the Requested Reviews Page for APIView
> Add Requested Reviews Page

- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
> PullRequest Reviews for Swagger

- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/HostedServices/LinesWithDiffBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosAPIRevisionsRepository.cs
- Compute Lines of Sections with diff in both directions
> Re architect/review revision restructure

- src/dotnet/APIView/CloneAPIViewDB/CloneAPIView/Program.cs
Date comparison was incorrectly skipping any latest manual reviews
> skip reviews only if created date is 2 years or more old

- src/dotnet/APIView/APIViewWeb/Managers/PullRequestManager.cs
Add a delay of 500ms between processing cleanup of API reviews.
> Add delay between processing cleanup of PR API review revisions

- src/dotnet/APIView/APIViewWeb/Managers/SamplesRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Samples.cshtml
This allows user to create new samples for cases where there are no existing samples.
> Enable Usage Samples for cases where there is no existing data

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
Copy approval name when approval status is copied over.
> Automatic approval copy issue

- tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
- tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_pylint_custom_plugins.py
> [Pylint] incorrect-naming-convention bug fix

- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
API review comment will include review URL if it creates a revision for the PR. Otherwise comment will state that API changes are not detected in the PR.
> Include apireview URL in comment only if API surface changes

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/src/index.ts
- tools/tsp-client/src/utils.ts
- Correct output to the `additionalDirectories` property in tsp-location.yaml
- Allow local specs with the update command
- Fix additional directory support for local specs
> [tsp-client] Improve additional directory processing

- tools/tsp-client/src/fs.ts
- tools/tsp-client/src/index.ts
- tools/tsp-client/src/npm.ts
- tools/tsp-client/src/options.ts
Fixes https://github.com/Azure/azure-sdk-tools/issues/7472
> [tsp-client] Use typespec/compiler path helpers

- tools/tsp-client/src/options.ts
Normalize and get absolute path for output dir.
> [tsp-client] fix output dir path

- tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Configuration/PostConfigureKeyVaultSettings.cs
Code change to address this s360 item (which is out of SLA now): https://msazure.visualstudio.com/One/_workitems/edit/25965784/
> Update PostConfigureKeyVaultSettings.cs with suggestion s360 

- eng/common/testproxy/scripts/tag-merge/README.md
- eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1
> Script Feedback

- tools/pylint-extensions/azure-pylint-guidelines-checker/CHANGELOG.md
- tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
- tools/pylint-extensions/azure-pylint-guidelines-checker/setup.py
- tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_pylint_custom_plugins.py
> [Pylint] bug for paramtype

- src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
> Update Contributing Docs

- eng/common/scripts/Verify-RestApiSpecLocation.ps1
The `$Language` value is set at https://github.com/Azure/azure-sdk-for-js/blob/416483373b916cd7c5f39a197da87dfec027841e/eng/scripts/Language-Settings.ps1#L1
> Fix Language value for JS

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- Resolve bug in Conversation Page for Reviews with SampleRevision comments
- Resolve bug in APIRevision Approval
> Fix Bug in Conversation Page

- tools/tsp-client/src/index.ts
Throw on errors instead of just logging them.
> [tsp-client] Fix errors

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/src/index.ts
- tools/tsp-client/src/network.ts
- tools/tsp-client/src/options.ts
Get typespec project through git to ensure folks can access their private repo specs.
> [tsp-client] Add support for private repo specs

- eng/common/TestResources/New-TestResources.ps1
Manually tested:
- Create with new SP
- Create with cached SP
- Create with user auth
> Fix role assignment for user auth

- tools/github/data/repositories.txt
- tools/github/scripts/Add-AzsdkMilestones.ps1
- tools/github/scripts/Add-AzsdkProjectIssues.ps1
- tools/github/scripts/Snapshot-AzsdkLabels.ps1
- tools/github/scripts/Sync-AzsdkLabels.ps1
Resolves Azure/azure-sdk-for-rust#1142
> Add Azure/azure-sdk-for-rust to scripts

- eng/scripts/python/apiview-syncdb/sync_cosmosdb.py
- Update Script for APIView Backup
> Update APIView Sync Pipeline

- eng/common/docgeneration/Generate-DocIndex.ps1
- eng/common/pipelines/templates/jobs/docindex.yml
This PR requires updates to `Language-Settings.ps1` also be merged before it will work properly. 
* https://github.com/Azure/azure-sdk-for-net/pull/41765
* https://github.com/Azure/azure-sdk-for-java/pull/38610
* https://github.com/Azure/azure-sdk-for-js/pull/28432
* https://github.com/Azure/azure-sdk-for-python/pull/34133
* https://github.com/Azure/azure-sdk-for-c/pull/2735
* https://github.com/Azure/azure-sdk-for-cpp/pull/5319
Partial https://github.com/Azure/azure-sdk-tools/issues/7601
> Fix BOM issue Generate-DocIndex.ps1

- src/dotnet/APIView/APIViewIntegrationTests/TestsBaseFixture.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/ReviewListModels.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/INotificationManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/NotificationManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/RequestedReviews.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/RequestedReviews.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosAPIRevisionsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/ICosmosAPIRevisionsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/ICosmosReviewRepository.cs
Move from Assigning Reviewers on Reviews to APIRevisions
> Move Approval Request to APIRevisions

- tools/pipeline-witness/ci.yml
...to the one recommended by Wes.
> Update approval groups gating `pipeline-witness` release

- eng/common/pipelines/codeowners-linter.yml
- eng/pipelines/templates/variables/globals.yml
Updates to the CodeownersLinter, NotificationConfiguration and PipelineOwnersExtractor tool versions for the case insensitive moniker comparison changes made to CodeownersUtils.
> Updates to tools for the CodeownersUtils updates

- src/dotnet/APIView/APIViewWeb/Managers/PullRequestManager.cs
Increase the delay to slowly process the cleanup of revisions created from PR.
> Increase delay between processing cleanup of revisions created from PR

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/README.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/index.ts
- tools/tsp-client/src/npm.ts
Fixes https://github.com/Azure/azure-sdk-tools/issues/7057
> [tsp-client] Add support for package-lock.json files

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/index.ts
Support reading .env file for environment variable support
> [tsp-client] Support .env file

- eng/pipelines/openapitools/repo-structure-cache-job.yml
I introduced this script in https://github.com/Azure/azure-sdk-tools/pull/7678 but forgot to update the script path in the yaml file before merging it.
> Update script path in the specs repo structure cache pipeline

- tools/pipeline-witness/infrastructure/kusto/functions/users/kojamroz/LintDiff_report.kql
Necessary after this PR got deployed:
- [Pull Request 530722](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/530722): Fix bug with AutorestResultParser not parsing any errors; add diagnostic logs; do a lot of refactoring
> Update LintDiff_report.kql: update the hardcoded strings to match code

- src/dotnet/APIView/APIViewIntegrationTests/RepositoryTests/CosmosPullRequestRepositoryTests.cs
- src/dotnet/APIView/APIViewIntegrationTests/RepositoryTests/CosmosReviewRepositoryTests.cs
- src/dotnet/APIView/APIViewIntegrationTests/TestsBaseFixture.cs
- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosAPIRevisionsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosCommentsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosSamplesRevisionsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/ICosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
- Improve CosmosPullRequestsRepository (performance bottleneck)
- Add HTML Minification
http://localhost:5000/Assemblies/Review/09de885a7c58444190fa9c9ae894d36d/632d733925b849c69c9624fdafb81d82?diffRevisionId=e70aca01c7db4226b8ec10c6e0d6a033&doc=False&diffOnly=False
Before
2.78 s server wait time
11.81 s content download time
14.59 s Total
After
3.82 s server wait time
1.35 s content download time
5.17 s Total
> Improve ServerSide Performance

- src/dotnet/APIView/APIViewWeb/Client/src/shared/comments.ts
> Link to review page in Git issue

- tools/apiview/emitters/typespec-apiview/CHANGELOG.md
- tools/apiview/emitters/typespec-apiview/package-lock.json
- tools/apiview/emitters/typespec-apiview/src/apiview.ts
- tools/apiview/emitters/typespec-apiview/src/emitter.ts
> [TypeSpec APIView] Support CrossLanguagePackageId

- eng/pipelines/apiview-review-gen-python.yml
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Enables CrossLanguagePackageId support
> Bump Python APIView version to 0.3.12

- eng/common/scripts/Create-APIReview.ps1
Add new param to pass current package version in request to create or update automatic API review request. This PR will be merged and synced after changes in [PR](https://github.com/Azure/azure-sdk-tools/pull/7819) is deployed to APIView production.
> APIView - send package version param for automatic API review request

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- Return appropriate status code based on approval status of review and/ or API Revision.
> Ensure correct response based review/ APIRevision approval status

- eng/common/pipelines/templates/steps/validate-all-packages.yml
- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Helpers/ApiView-Helpers.ps1
- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
- eng/common/scripts/Validate-All-Packages.ps1
- eng/common/scripts/Validate-Package.ps1
This PR has changes to create a new pipeline template which will run version validation, change log validation, API review status check and package name approval status and create or update this information in package work item in Azure DevOps.
> Pipeline template to validate package and update package work item

- tools/sdk-ai-bots/Embeddings/embedding/embedding.py
- tools/sdk-ai-bots/Embeddings/requirements.txt
- langchain package must be bumped to resolve security alerts.
- Updated the code to adapt the new version of azure search.
> Upgraded langchain packages per security requirement

- eng/scripts/Create-Apiview-Token-Python.ps1
- Emit Cross Language Definition ID to Allow Cross Language APIView
> emit cross language definition Id

- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
prevent null error at GetReviewsAsync by reviewIds
> Avoid null error

- eng/pipelines/templates/stages/1es-redirect.yml
- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
Need to make azure-sdk-build-tools changes to remove `- publish` aliases.
[Pending change in azure-sdk-build-tools](https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-build-tools/pullrequest/957)
> Fix Proxy Internal Build

- packages/java-packages/codesnippet-maven-plugin/README.md
- packages/java-packages/codesnippet-maven-plugin/pom.xml
- packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacer.java
- packages/java-packages/codesnippet-maven-plugin/src/test/java/com/azure/tools/codesnippetplugin/implementation/SnippetReplacerTests.java
Update dependencies used by `codesnippet-maven-plugin`
> Update Codesnippet dependencies

- eng/common/pipelines/templates/steps/detect-api-changes.yml
- eng/common/scripts/Create-APIReview.ps1
- eng/common/scripts/Detect-Api-Changes.ps1
Changes to pass correct package name in request to APIView from pipeline.
> Show review link in logs and set DevOps project name in request

- tools/sdk-ai-bots/.pipelines/build-document-embeddings.yml
- tools/sdk-ai-bots/Scripts/Build-CustomizedDocEmbeddings.ps1
- tools/sdk-ai-bots/Scripts/Build-EngHubDocEmbeddings.ps1
- tools/sdk-ai-bots/Scripts/Build-TypeSpecAzureDocEmbeddings.ps1
- tools/sdk-ai-bots/Scripts/Common.ps1
- tools/sdk-ai-bots/Scripts/Markdown-BuildIndexMetadata.ps1
Use the federated workload identity to access azure blob.
> Use azcopy to access azure blob with FWI

- tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/Dockerfile
effort in resolving s360 security issues
> stress deploy image moving to mariners

- eng/pipelines/notifications.yml
Only try to add pipelines under the "notify" folder in the public team  to get notifications.
> Add public to notification generation set

- .github/CODEOWNERS
> Update Codeowners for Proxy

- eng/pipelines/mirror-container-images.yml
> [stress] fix broken mirror container image pipeline

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerDictionary.cs
> Sanitizer Update

- eng/common/testproxy/test-proxy-tool.yml
Change suggested by a @gearama update. Couldn't take it there, but will definitely take it here.
> Properly feed the proxy output into the log on windows

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml
Resolve Bug in Conversation Page for Samples
> Resolve bug in Conversation Page

- tools/test-proxy/tests.yml
As that is what the .NET CI tests do now.
> Install .NET 8

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/fs.ts
- tools/tsp-client/test/examples/sdk/badtsplocation/tsp-location.yaml
- tools/tsp-client/test/tspLocation.spec.ts
> [tsp-client] Normalize tsp-location.yaml directories before processing

- eng/pipelines/pipeline-generation-single.yml
- eng/pipelines/pipeline-generation.yml
@weshaggard, these are the same changes you'd [fixed yesterday](https://github.com/Azure/azure-sdk-tools/pull/8434)
> Fix pipeline gen yml file line wrappings

- doc/common/matrix_generator.md
- eng/common-tests/matrix-generator/samples/matrix.json
- eng/common-tests/matrix-generator/tests/job-matrix-functions.filter.tests.ps1
- eng/common-tests/matrix-generator/tests/job-matrix-functions.tests.ps1
- eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
- eng/common/pipelines/templates/steps/run-pester-tests.yml
- eng/pipelines/agent-software-inventory.yml
- eng/pipelines/templates/variables/image.yml
> Update macos image from 11 to latest

- eng/common/pipelines/templates/steps/publish-1es-artifact.yml
Add logging and fix display name given Agent.JobStatus doesn't evaluate currently in the display name property.
> Update publish template

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
https://github.com/Azure/azure-sdk-tools/security/dependabot/137
https://github.com/Azure/azure-sdk-tools/security/dependabot/175
> Fix js-release-sdk-tool security issues

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/index.ts
- tools/tsp-client/src/utils.ts
- tools/tsp-client/test/examples/tspconfig-custom-service-dir.yaml
- tools/tsp-client/test/utils.spec.ts
Fixes https://github.com/Azure/azure-sdk-tools/issues/8379
> [tsp-client] Prefer emitter specific service-dir if specified

- src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs
- src/dotnet/APIView/ClientSPA/angular.json
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/revision.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/revisions/revisions.service.ts
Pull requests retrieved for active APIRevsion and link to associated GitHub PR created in right panel of UI.
> Get Associated Pull Requests

- tools/github/scripts/Validate-AzsdkCodeOwner.ps1
The focus of these changes is to improve the usability and user experience of the validation script.   The previous output was basic and lacked details outside of verbose mode - which included raw HTTP response payloads.   These changes include more context and clear color/symbol indications of what information is missing.
**New output:**
**Old output:**
> [Validate-AzsdkCodeOwners] UX enhancements

- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Constants/TriageLabelConstants.cs
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/ScheduledEventProcessing.cs
- tools/github-event-processor/RULES.md
- tools/github/data/common-labels.csv
This PR is providing a way to skip the Enforce Max Life of Issues
> Add the ability to manage Auto-Close on issues

- src/dotnet/APIView/APIViewWeb/Languages/CSharpLanguageService.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/CSharpAPIParser.csproj
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/Program.cs
- Moving changes added [here ](https://github.com/Azure/azure-sdk-tools/pull/8386/files#diff-8c271072c86207f719ff9be095ca81696283e83289ba60233a673645adbe5dcc)to updated CSharp Parser
> Update Parser Logic

- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/Program.cs
- Fix warning in parser causing pipeline to error.
> Resolve Pipeline build errors

- eng/pipelines/templates/stages/archetype-sdk-publish-js.yml
[Test Release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3946872&view=results)
> Node Publishing Update

- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- Improve Logging on Background Task
> Improve Background Task Logging

- src/dotnet/APIView/APIViewWeb/Startup.cs
- src/dotnet/APIView/apiview.yml
- Fix to deployment variables, use latest parser version.
> Fix deployment variables

- eng/scripts/live-test-resource-cleanup.ps1
Adding missing set firewall parameter to force network rules during cleanup
> Add set firewall flag to live test resource cleanup

- src/dotnet/APIView/APIViewWeb/Languages/LanguageProcessor.cs
- Handle error when deleting the directory.
> Handle Error when Deleting the Directory

- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/CSharpAPIParser.csproj
- Update CSharp Parser Net runtime
> Update NET version

- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/Program.cs
Troubleshooting changes in .NET APIview parser
> Remove exception catch

- src/dotnet/APIView/APIViewWeb/Helpers/PageModelHelpers.cs
- src/dotnet/APIView/APIViewWeb/Repositories/BlobCodeFileRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/IBlobCodeFileRepository.cs
- Use data in cosmos to decide deserialization style.
> Chose Deserialization Style using data in Cosmos

- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- Disable First Release (Review) Approval for non-preferred approvers.
> Disable Review Approval Button for non-prefered approvers

- src/dotnet/APIView/APIViewWeb/LeanControllers/ReviewsController.cs
- src/dotnet/APIView/apiview.yml
- Flip Diff Order
- Update CSharpParser Version
> Update Parser Version and Filp Diff Order

- src/dotnet/APIView/APIViewWeb/Languages/CSharpLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/GoLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/LanguageProcessor.cs
- src/dotnet/APIView/APIViewWeb/Languages/ProtocolLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/SwaggerLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/TypeSpecLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
Logging for Language Processor
> Add Better logging

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- Updating OcktoKit version to handle error serializing long to int.
> Update Octokit Version

- src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs
- Fix bug in `AreAPICodeFilesTheSame`
> Fix logic for AreAPICodeFilesTheSame

- src/dotnet/APIView/APIView/Model/StructuredTokenModel.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/TreeToken/CodeFileBuilder.cs
- SkippDiff for dependency version.
> Add SkipDiff for Dependency Version

- eng/common/scripts/Test-SampleMetadata.ps1
Supersedes https://github.com/Azure/azure-sdk-for-net/pull/45104
> Add Azure Health Data Service product slug

- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/TreeToken/CodeFileBuilder.cs
> Update CSharpParser Version

- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/ReviewRevisionPageModels.cs
- src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs
- src/dotnet/APIView/apiview.yml
- Enable Skipp Diff for Tree Style Parser
> Implement SkipDiff

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/fs.ts
- tools/tsp-client/src/index.ts
- tools/tsp-client/src/utils.ts
- tools/tsp-client/test/examples/tsp-location.yaml
- tools/tsp-client/test/tspLocation.spec.ts
Fixes https://github.com/Azure/azure-sdk-tools/issues/8551
> [tsp-client] Fix writing additional directory

- tools/tsp-client/src/fs.ts
> [tsp-client] log emitter version

- src/dotnet/APIView/APIViewWeb/Languages/CSharpLanguageService.cs
- src/dotnet/APIView/apiview.yml
> 072324.01/update c sharp parser version

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordSession.cs
> Reduce verbosity during matching

- tools/tsp-client/src/commands.ts
- tools/tsp-client/src/index.ts
- tools/tsp-client/test/commands.spec.ts
- tools/tsp-client/test/examples/sdk/contosowidgetmanager/contosowidgetmanager-rest/tsp-location.yaml
- tools/tsp-client/test/examples/sdk/local-spec-sdk/tsp-location.yaml
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager.Shared/main.tsp
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-11-01-preview/Widgets_CreateOrUpdateWidgetSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-11-01-preview/Widgets_DeleteWidgetSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-11-01-preview/Widgets_GetWidgetOperationStatusSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-11-01-preview/Widgets_GetWidgetSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-11-01-preview/Widgets_ListWidgetsSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/main.tsp
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml
- tools/tsp-client/test/sync.spec.ts
Adding some fixes for the yargs update + adding more comprehensive tests for various command flags
> [tsp-client] Fixes for yargs update + more testing

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SecretScanner.cs
- tools/test-proxy/tests.yml
And resolve failing `livetests` as well.
> Fix issue preventing proper secret scan

- tools/tsp-client/build-tsp-client.yml
> Install newly created `tsp-client` package

- src/dotnet/APIView/APIViewWeb/Models/UserPreferenceModel.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/userPreferenceModel.ts
- Add Page Setting for Disabling Lazy Loading of Codeines.
> Add Button for Disabling CodeLines Lazy Loading

- tools/js-sdk-release-tools/src/hlc/generateMgmt.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInTerminal/generateRLCInTerminal.ts
Fix https://github.com/Azure/azure-sdk-tools/issues/5520
Test: https://github.com/test-repo-billy/azure-rest-api-specs/pull/3469 - check the sdk automation pipeline
> Replace Global Rush

- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
1. upgrade openapi-to-typespec to 0.9.0
2. add --mgmt-debug.suppress-list-exception to .net generator dependency
> upgrade openapi-to-typespec

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
revert 310645b86bc2e71150387f20d2664297d6ffe2a2
> [tsp-client] Revert openapi-to-typespec changes

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
- tools/tsp-client/src/typespec.ts
Fixes #8815
Fixes #8777
Fixes #8555
> [tsp-client] Report diagnostic errors and exit with an error

- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/apiview.yml
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/TreeToken/CodeFileBuilder.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CSharpAPIParserTests.csproj
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CodeFileTests.cs
Fix null pointer issue when review does not have any system comments.
> Fixed issue when processing code file for metapackage

- eng/common/scripts/Test-SampleMetadata.ps1
`playwright-testing` is an approved product slug - https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies?branch=main#product
> chore(): add playwright-testing to product slugs

- src/dotnet/APIView/apiview.yml
> Add hubs URL to Build Pipeline

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
> upgrade openapi-to-typespec version to 0.9.1

- src/dotnet/APIView/apiview.yml
Update parser version to latest.
> Update default API parser version for .NET

- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- Ensures new comment thread and comment icon is updated in real time fior all clients
> Ensure all parts of comment updates in real time

- src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/ReviewsController.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/signal-r/signal-r.service.ts
- Add real time updates for reviews and ApiRevision updates
> Add real time updates for review and revisions

- src/go/cmd/api_view_test.go
- src/go/cmd/pkg_test.go
- src/go/cmd/testdata/test_major_version/go.mod
- src/go/cmd/testdata/test_major_version/subpackage/test.go
Oops, should've added this in #8856
> Test apiviewgo package naming in v2 module

- src/dotnet/APIView/APIViewWeb/Client/css/shared/theme-colors.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.scss
Improve HiddenAPI styling for light theme
> Improve Hidden API colors

- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.ts
- Allow upload of dll files for C#
> Allow uploads of dll files

- src/dotnet/APIView/ClientSPA/src/ng-prime-overrides.scss
- Adjust button color to match all themes
> Adjust button color

- eng/pipelines/templates/stages/1es-redirect.yml
- eng/pipelines/templates/stages/archetype-sdk-publish-js.yml
- src/dotnet/APIView/apiview.yml
- tools/js-sdk-release-tools/ci.yml
This should address the baseline PRs coming in for every pipeline
> Add auto-baseline main pipeline config for core

- eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Updating minimum stress addons version
> Require minimum stress addons version of 0.3.0

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/utils.ts
- tools/js-sdk-release-tools/src/hlc/generateMgmt.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInTerminal/generateRLCInTerminal.ts
Issue: autorest may hang when generation failed
Fix: add timeout to child process to avoid hang
> Fix Autorest Hang Issue

- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/CodePanelModels.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/codePanelModels.ts
- src/dotnet/APIView/ClientSPA/src/app/_workers/apitree-builder.worker.ts
Inform the user that there are hidden diffs in hidden apis.
> Show HiddenAPIs when it contains Diff

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/GitHubActions/GitHubActionProcessor.cs
- tools/pipeline-witness/infrastructure/bicep/logsResourceGroup.bicep
Also use the correct repo owner property name when pulling the workflow details for a run
> Force kusto script to run on deployment

- eng/pipelines/templates/variables/globals.yml
We need to pick-up the changes from PR https://github.com/Azure/azure-sdk-tools/pull/9004
> Update versions of tools to use new opensource api

- .github/CODEOWNERS
> Update 1espt codeowners

- .github/workflows/tsp-client-tests.yml
- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
> [tsp-client] Add @autorest/core as dependency

- .github/CODEOWNERS
> Add Wes as an owner to codeowners-linter.yml

- src/dotnet/APIView/APIViewWeb/Client/css/shared/codeline.scss
> Update Diagnostics Color

- eng/common/scripts/Generate-PR-Diff.ps1
See title. [Example failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4206221&view=logs&jobId=1dca5ef1-3811-5712-152d-1052a5815ba2&j=1dca5ef1-3811-5712-152d-1052a5815ba2&t=dc97a0fb-818d-5f5f-1f4d-c54563ea0226)
> Handle no changed files

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
> Bump openapi-to-typespec to 0.10.1

- src/dotnet/APIView/APIViewWeb/Client/css/shared/language-customizations.scss
- src/dotnet/APIView/ClientSPA/workbox-config.js
- Update Icon URL
- Version Service Worker
> Bug fix/api view cache

- src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
- src/dotnet/APIView/apiview.yml
Update JS parser version to include minor bug fix.
> Update JS API parser to 2.0.2

- .github/workflows/scheduled-event-processor.yml
Fix missing CloseAddressedIssues in gh event processor
> Fix missing CloseAddressedIssues in gh event processor

- src/dotnet/APIView/APIViewWeb/Helpers/HelperAttributes.cs
- src/dotnet/APIView/APIViewWeb/Languages/JsonLanguageService.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.ts
- Update allowed APIView files
> Resolve bug in file upload

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
> Bump openapi-to-typespec to 0.10.2

- eng/pipelines/templates/stages/1es-redirect.yml
Disable auto-baseline on non default branch. Otherwise we are getting these PRs: https://github.com/Azure/azure-sdk-tools/pull/9224
> Disable auto-baseline on non default branch

- src/dotnet/APIView/ClientSPA/src/app/_components/shared/code-editor/code-editor.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_modules/samples-page.module.ts
- src/dotnet/APIView/ClientSPA/src/app/_modules/shared/shared-app.module.ts
- Ensure Monaco Editor can load in production
> fix bug causing monaco editor not to load

- src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
- src/dotnet/APIView/apiview.yml
Update JS API parser to latest version.
> Update JS parser version

- tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen/Azure.SDK.Management.ChangelogGen.csproj
update ResourceManager to 1.13.0 for tool changelog-gen-mgmt
> update ResourceManager to 1.13.0 for tool changelog-gen-mgmt

- tools/stress-cluster/cluster/azure/cluster/workloadapproles.bicep
[stress testing] Set up storage file data contributor role for cluster test identities
> [stress testing] Set up storage file data contributor role for cluster test identities

- eng/scripts/live-test-resource-cleanup.ps1
Forgot to uncomment this line :D but probably better to isolate the change anyways to its own PR.
> Enable subscription scoped deployment cleanup

- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Program.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/ReadmeParser.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/ReadmeParserTest.cs
Update Swagger Parser to save file using the tag used for generation the APIView token
> Use Tag for Token File OutPut

- eng/scripts/live-test-resource-cleanup.ps1
Fix RG removal comment in cleanup
> Fix RG removal comment in cleanup

- eng/scripts/live-test-resource-cleanup.ps1
Fix bug skipping removal of worm storage resource groups
> Fix bug skipping removal of worm storage resource groups

- eng/common-tests/psmodule-helpers/Install-Module-Parallel.ps1
- eng/common/scripts/Cadl-Project-Generate.ps1
- eng/common/scripts/Cadl-Project-Sync.ps1
- eng/common/scripts/Helpers/Package-Helpers.ps1
- eng/common/scripts/TypeSpec-Project-Generate.ps1
- eng/common/scripts/TypeSpec-Project-Process.ps1
- eng/common/scripts/TypeSpec-Project-Sync.ps1
- eng/common/scripts/Update-DocsMsToc.ps1
- eng/common/scripts/Verify-Resource-Ref.ps1
- eng/common/scripts/Verify-RestApiSpecLocation.ps1
- eng/common/scripts/job-matrix/job-matrix-functions.ps1
- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
- tools/stress-cluster/cluster/provision.ps1
Found some pipeline failures installing 0.4.1, not sure if it was transient but figured we might as well update anyways.
I might be breaking myself into a world of hurt here 😅
> Bump powershell yaml versions to 0.4.7

- tools/github/data/common-labels.csv
Adding `Durable Task Scheduler` label to common label list.
> Adding Durable Task Scheduler Label

- eng/common/scripts/Helpers/PSModule-Helpers.ps1
Hide output from register/unregister ps module repository
> Hide output from register/unregister ps module repository

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
> Bump openapi-to-typespec to 0.10.4

- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs
Update the AI Label Service URL.
> Update the AI Label Service URL

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
Feedback from @heaths working through creating a test framework for the rust repo.
Leaving this open for other feedback as it's encountered.
> Small readme update

- eng/pipelines/templates/scripts/assemble-dotnet-standalone-exe.ps1
- eng/pipelines/templates/steps/produce-net-standalone-packs.yml
Update default to net8.0 for standalone exe script
> Update default to net8.0 for standalone exe script

- eng/pipelines/templates/steps/install-dotnet.yml
The focus of these changes is to update the .NET SDK versions used in the pipelines to include the latest. This will allow testing on the current platform.
> [Tools] Update .NET SDK Versions

- eng/pipelines/templates/steps/install-dotnet.yml
- global.json
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/Azure.Sdk.Tools.SnippetGenerator.Tests.csproj
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator/Azure.Sdk.Tools.SnippetGenerator.csproj
The focus of these changes is to update the current .NET SDK and targets to support .NET 9.
> [.NET] Updating to .NET 9

- eng/pipelines/templates/steps/install-dotnet.yml
- global.json
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/Azure.Sdk.Tools.SnippetGenerator.Tests.csproj
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator/Azure.Sdk.Tools.SnippetGenerator.csproj
Reverts Azure/azure-sdk-tools#9539
> Revert "[.NET] Updating to .NET 9"

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
> Bump openapi-to-typespec to 0.10.5

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
CC @billwert updates for clarity
> Update notes on usage of logging variables

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/entrypoint.ts
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- tools/spec-gen-sdk/src/cli/cli.ts
- tools/spec-gen-sdk/src/types/PackageData.ts
- tools/spec-gen-sdk/src/utils/readme.ts
- tools/spec-gen-sdk/src/utils/typespecUtils.ts
- tools/spec-gen-sdk/src/utils/utils.ts
- Cleaned up dependencies
- Set variables for pipeline scenarios
- Added alias for CLI parameters
- Fixed minor log issue
> Cleaned up dependencies and set pipeline variables

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
> Bump openapi-to-typespec to 0.10.6

- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/review-info/review-info.component.html
- src/dotnet/APIView/ClientSPA/src/app/_services/http-error-interceptor/http-error-interceptor.service.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/samples/samples.service.ts
- Avoid / Suppress various client-side errors.
> Suppress some client side error

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/reportStatus.ts
Set PrBranch variable consistently in all scenarios to ensure it can be consumed by same code in pipeline.
> Ensure PrBranch variable is set

- doc/common/spellcheck.md
This is to help users who have a spelling error detection in CI get to the right documentation.
> Update spellcheck.md to include a redirection 

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
- eng/pipelines/live-test-cleanup.yml
Remove sovereign cloud testing support
> Remove sovereign cloud testing support

- tools/test-proxy/typespec/main.tsp
@heaths you brought this up in a brief discussion yesterday and I'm just adding it in a tiny PR.
> Update test-proxy TSP

- src/dotnet/APIView/APIView/Model/V2/ReviewLine.cs
- src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
- src/dotnet/APIView/APIViewUnitTests/CodeFileTests.cs
- src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/app-conf-change-in-skipped-diff.json
- src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/app-conf.json
- src/dotnet/APIView/APIViewUnitTests/SampleTestFiles/app-conf_without_skip_diff.json
- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
Skip the line from diff and code file equality check if all tokens in a line are marked as skipped from diff check.
> Do not show the line as modified if all tokens in a line is skipped

- eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
- eng/common/scripts/Invoke-GitHubAPI.ps1
- eng/common/scripts/Remove-IssueLabel.ps1
- Added common script to delete label from a PR
- Two steps to process labels for spec PR, one is to add label and the other is to remove label
> Added label handle sdk-gen pipeline template

- eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
- use 'azure-sdk' forked repo for spec PR scenario
- use spec PR info for checkout and spec-gen-sdk
> Support spec PR scenario in sdk gen pipeline template

- tools/github/data/common-labels.csv
Add Database Watcher label to common labels CSV
> Add Database Watcher label to common labels CSV

- tools/github/data/common-labels.csv
Add 'AI Projects' label to common-labels.csv
> Add 'AI Projects' label to common-labels.csv

- src/dotnet/APIView/apiview.yml
Update pinned parser version in APIView CI.
> Update .NET parser version installed to APIView

- eng/pipelines/pipeline-generation.yml
- eng/scripts/Create-Package-WorkItem.ps1
> Add support for Rust to common scripts and pipelines

- eng/common/scripts/Detect-Api-Changes.ps1
- `eng/common` changes needed for https://github.com/Azure/azure-sdk-for-go/pull/24000
> Update common tool to support go

- eng/common/TestResources/New-TestResources.ps1
Addressing some initial needs from https://github.com/Azure/azure-sdk-for-js/pull/32769
> Pass arm template parameter for TME context

- eng/pipelines/templates/jobs/stress-test-release.yml
Stress release pipeline - deploy to TME storage cluster
> Stress release pipeline - deploy to TME storage cluster

- eng/common/TestResources/New-TestResources.ps1
Flip supportsSafeSecretStandard boolean condition
> Flip supportsSafeSecretStandard boolean condition

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
- eng/pipelines/devops-create-package-workitem.yml
Add rust to:
- eng/pipelines/devops-create-package-workitem.yml
- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
> Onboard Rust in more shared yaml

- tools/tsp-client/README.md
- tools/tsp-client/repo_setup.md
Add more info on the `generate-config-files` command, including configuration options.
> [tsp-client] Add more info on generate-config-files command

- tools/tsp-client/README.md
> [tsp-client] Docs improvement

- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Includes fix https://github.com/Azure/azure-sdk-tools/pull/9784
> Update pipeline generator

- src/dotnet/APIView/APIViewWeb/LeanControllers/CommentsController.cs
- src/dotnet/APIView/ClientSPA/src/app/_services/comments/comments.service.ts
Use formData for comment Updates
> Use formData for comment Updates

- eng/common/scripts/Generate-PR-Diff.ps1
@hallipr this repairs the issue found in Azure/azure-sdk-for-net#48269
> Handle defaults in `changedFiles` and `deletedFiles`

- tools/pylint-extensions/azure-pylint-guidelines-checker/CHANGELOG.md
- tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
- tools/pylint-extensions/azure-pylint-guidelines-checker/setup.py
- tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_pylint_custom_plugins.py
> [pylint] do-not-log-exceptions bug

- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- This updates the structure of output artifacts to match artifacts in language repos.
- This makes it so that other shared scripts don't need to be modified
> Update Published artifact's structure to match language repositories

- src/dotnet/APIView/apiview.yml
- Uninstall then install CSharp parser
> Force install of csharp parser

- eng/common/pipelines/templates/steps/detect-api-changes.yml
- eng/common/scripts/Detect-Api-Changes.ps1
- Update APIView scripts to support SDK Automation
- Improvements to logging
> Updates to common APIView Scripts

- src/dotnet/APIView/APIView/Model/CodeFile.cs
- src/dotnet/APIView/APIViewJsonUtility/Program.cs
- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
- src/dotnet/APIView/APIViewWeb/Languages/CLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/GoLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/JsonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/LanguageProcessor.cs
- src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/ProtocolLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/RustLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/SwaggerLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/TypeSpecLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/BlobCodeFileRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/IBlobCodeFileRepository.cs
- Needed for proper comparison of API surface.
> Update languages supporting tree style parser

- src/dotnet/APIView/APIViewWeb/Repositories/BlobCodeFileRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/BlobOriginalsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/BlobUsageSampleRepository.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
- Use dependency injection for BlobServiceClient
- More logging in Blob repository files
> APIView BlobClient

- eng/pipelines/apiview-review-gen-python.yml
Update pinned API parser version to 0.3.15.
> Update pinned python API parser version to 0.3.15

- eng/pipelines/apiview-review-gen-python.yml
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Update Python parser version in server side
> Update pinned python API parser version to 0.3.16

- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.scss
> Update Enum color for java

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/src/utils/runScript.ts
Issue link: https://github.com/Azure/azure-sdk-tools/issues/9958
> [sdk gen] Combine all log issues to one entry

- eng/containers/ci.yml
- tools/http-fault-injector/Dockerfile
- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.lock
- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/templates/stresswatcher.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
Enable auto-updates for stress images
> Enable auto-updates for stress images

- tools/stress-cluster/chaos/README.md
- tools/stress-cluster/cluster/README.md
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/file-plugin/README.md
- tools/stress-cluster/cluster/provision.ps1
Update stress provision references to new chart location
> Update stress provision references to new chart location

- src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
- src/dotnet/APIView/APIViewUnitTests/CodeFileTests.cs
- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
Mark end of context line as related line to context line so if context line is added or removed in diff view then end of context will also be displayed as added or diffed. Otherwise, comparison will find matching closing brackets that is unrelated to modified class and treat it as unchanged.
> Mark end of context line for added or removed context as related line

- src/dotnet/APIView/APIViewWeb/DTOs/PullRequestReviewDto.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/PullRequestsController.cs
- Allows for retrieval of APIRevisions created by Pull Request
> Expose Endpoint for retrieving APIRevisions created by Pull Request

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/java/apiview-java-processor/pom.xml
Update java parser version to upgrade review to resolve dependency version skip diff issue.
> Update java parser version

- src/dotnet/APIView/APIViewWeb/LeanControllers/CommentsController.cs
- src/dotnet/APIView/ClientSPA/src/app/_services/comments/comments.service.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/comments/comments.service.ts
- Resolve bug in APIView causeing comment text to disappear when edited.
> Resolve bug in apiview comment update

- eng/scripts/python/apiview-syncdb/sync_cosmosdb.py
Fix issue in Python script to load Cosmos DB records from backup json file.
> Fix issue in APIView prod to staging sync

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/entrypoint.ts
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/utils/runScript.ts
Refactor log issues to filter logs file
> [spec-gen] Refactor log issues

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/src/utils/runScript.ts
change push to log issues condition
> [SDK gen] Fix bug for correct log issues

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- saved the label artifacts in separated folder in order to publish them in separated folders
- changed the label artifact name
> Updated label artifact location

- tools/js-sdk-release-tools/package.json
release for https://github.com/Azure/azure-sdk-tools/pull/9857
> Update js sdk release tool  version to release

- tools/github/data/common-labels.csv
Add Secret Store Extension Label to common label file.
> Add Secret Store Extension Label to common label file.

- eng/common/scripts/Helpers/Resource-Helpers.ps1
Fix group prefix conditional in test resource removal
> Fix group prefix conditional in test resource removal

- tools/js-sdk-release-tools/src/common/utils.ts
- tools/js-sdk-release-tools/src/test/pipeline/sdkGeneration.test.ts
- tools/js-sdk-release-tools/src/utils/generateInputUtils.ts
> [Part 1] Add kebab case style option 'is-modular-library'

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
Updating versions from update made in PR #9964
> Update GitHubEventProcessor version to 1.0.0-dev.20250314.4

- src/dotnet/APIView/apiview.yml
- Skip installation of rust parser
> Don't install rust parser

- eng/containers/ci.yml
- eng/pipelines/prune-acr-images.yml
- eng/pipelines/publish-docker-image-isolated.yml
- eng/pipelines/publish-docker-image.yml
- eng/scripts/prune-acr-images.ps1
Add ACR image pruning to scheduled docker publish pipeline
> Add ACR image pruning to scheduled docker publish pipeline

- tools/apiview/parsers/rust-api-parser/CHANGELOG.md
- tools/apiview/parsers/rust-api-parser/package.json
Updating the release version to 1.0.0
> [rust-api-parser] 1.0.0 version update

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/entrypoint.ts
- tools/spec-gen-sdk/src/automation/logging.ts
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/cli/cli.ts
- tools/spec-gen-sdk/src/types/ExecutionReport.ts
- tools/spec-gen-sdk/src/utils/runScript.ts
- tools/spec-gen-sdk/src/utils/utils.ts
* Added new logging functions `vsoLogError`, `vsoLogWarning`, `vsoLogErrors`, and `vsoLogWarnings` to better handle errors and warnings in Azure DevOps environments (`tools/spec-gen-sdk/src/automation/entrypoint.ts`).
* Updated various functions to use the new logging methods, including `sdkAutoMain`, `generateReport`, `saveFilteredLog`, and `generateHtmlFromFilteredLog` (`tools/spec-gen-sdk/src/automation/entrypoint.ts`, `tools/spec-gen-sdk/src/automation/reportStatus.ts`).
* Removed the `generateBreakingChangeArtifact` function and related code, the logic will be moved to the runner tool (`tools/spec-gen-sdk/src/automation/reportStatus.ts`).
> refactored logging and removed label artifact

- src/dotnet/APIView/apiview.yml
Reverts Azure/azure-sdk-tools#10069
> Revert "Don't install rust parser"

- src/dotnet/APIView/apiview.yml
> [APIView] Mark apiview pipeline as release pipeline

- eng/common/scripts/job-matrix/job-matrix-functions.ps1
This time the issue appears to be after we ProcessImports
> Resolve Failing `create-prJobMatrix`

- src/dotnet/APIView/APIViewWeb/Helpers/APIHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/ReviewsController.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosAPIRevisionsRepository.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/conversation-page/conversation-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/comment-thread/comment-thread.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/editor/editor.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_services/reviews/reviews.service.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/revisions/revisions.service.ts
- Resolves https://github.com/Azure/azure-sdk-tools/issues/9835 and part of https://github.com/Azure/azure-sdk-tools/issues/10005
> Resolve misc issues

- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/codeDiagnostic.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/codeLineSearchInfo.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/codePanelModels.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/structuredToken.ts
- Resolves parts of https://github.com/Azure/azure-sdk-tools/issues/10005
> resolve issues with code line search

- tools/pipeline-witness/infrastructure/bicep/logsResourceGroup.bicep
- tools/pipeline-witness/infrastructure/bicep/main.bicep
- tools/pipeline-witness/infrastructure/bicep/tableResources.bicep
- Add managed identity to Event Grid
- Add grant for Event Grid managed identity -(Event Hubs Data Sender)-> Event Hubs namespaces
- Configure Storage -> Event Grid -> Event Hubs subscriptions to use the managed identity on Event Grid
- Disable local auth for Event Hubs namespaces
> Use MI to connect from event grid to event hub

- eng/branch-rulesets/required-pullrequest-checks.json
This assumes the following settings are coming from a shared ruleset at the org level.
- Require a pull request before merging
- Require approvals
- Required number of approvals before merging >= 1
- Require approval of the most recent reviewable push
- Require review from Code Owners (can be by-passed by our team)
> Update shared ruleset

- src/dotnet/APIView/apiview.yml
> Update Rust Parser Version

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/deploy-test-resources.yml
Add option to create self contained test resources post script
> Add option to create self contained test resources post script

- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
> Bugfix in Associated API Revisions

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- tools/spec-gen-sdk/src/types/PackageData.ts
- Ensure relative folder path works on all languages
> Update relative folder path

- .github/CODEOWNERS
Adding me so that I don't have to elevate to merge.
> [CODEOWNERS] Add Squire to stuff

- eng/common/scripts/Helpers/ApiView-Helpers.ps1
- Use Invoke-WebRequest
- Handle 204 NoContent case.
> Update APIView Helpers

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- Go used full directories as the service name
> ServiceName for go

- .github/CODEOWNERS
The focus of these changes is to fix the format of paths, ensuring they end in the expected /.
> [CODEOWNERS] Fixing path format

- eng/common/scripts/Helpers/ApiView-Helpers.ps1
- src/dotnet/APIView/APIViewWeb/LeanControllers/PullRequestsController.cs
- Ensure response content is properly converted.
> Fix error in APIView Helper

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Add handling to stress deploy script to tell users when they lack TME group permissions
> Add handling to stress deploy script to tell users when they lack TME group permissions

- eng/common-tests/matrix-generator/pr-matrix-samples/pr-matrix-generation-acceptance.tests.ps1
- eng/common/scripts/job-matrix/Create-JobMatrix.ps1
- eng/common/scripts/job-matrix/job-matrix-functions.ps1
> Add env var skip for matrix debug. Add acceptance test tag

- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- Prevent viewing of review page through the uri when the review is deleted
> Don't show page when review is deleted

- tools/issue-labeler/Directory.Build.props
- tools/issue-labeler/IssueLabeler.sln
- tools/issue-labeler/src/AzureRAGService/TriageRAG.cs
- tools/issue-labeler/src/IssueLabelerService/AzureSdkIssueLabelerService.cs
- tools/issue-labeler/src/IssueLabelerService/IssueLabelerService.csproj
- tools/issue-labeler/src/IssueLabelerService/Program.cs
- tools/issue-labeler/src/SearchIndexCreator/Program.cs
- tools/issue-labeler/src/SearchIndexCreator/SearchIndexCreator.csproj
- Cut out some of the fluff from the `SearchIndexCreator`
- Async methods
- Fixed some minor things (naming conventions, etc..) that had been mentioned in the big PR.
> Refactor AI Bot RAG service

- eng/common/scripts/Package-Properties.ps1
This PR addresses the issue that we have over in `go` with the fact that we aren't resolving the appropriate `ci.yml` for the eng/tools directory packages.
It is NOT the correct solution even in medium term. We need to adjust this to do some smarter algo that climbs up from the package directory, rather than assuming `sdk` or `eng` (which this PR does).
I want to unblock `go`, but I due to IRL commitments I can't get to that correct solution today.
I ran a full Save-Package-Properties on every repo. Clean runs. Can't see any regressions, and we are passing our integration tests.
> Stop-gap for `go` `eng/` packages

- eng/common/pipelines/templates/archetype-typespec-emitter.yml
Contributes to https://github.com/Azure/azure-sdk-for-net/issues/49240
> Use tsp-client in emitter CI

- tools/js-sdk-release-tools/package.json
The latest version is https://www.npmjs.com/package/@azure-tools/js-sdk-release-tools/v/2.7.23
So the next release version should be 2.7.24
> Change package.json version

- packages/python-packages/apiview-copilot/README.md
- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/dev_requirements.txt
- packages/python-packages/apiview-copilot/evals/run.py
- packages/python-packages/apiview-copilot/requirements.txt
- packages/python-packages/apiview-copilot/scripts/_markdown_parser.py
- packages/python-packages/apiview-copilot/scripts/deploy_app.py
- packages/python-packages/apiview-copilot/scripts/deploy_solution.py
- packages/python-packages/apiview-copilot/scripts/parse_guidelines.py
- packages/python-packages/apiview-copilot/scripts/remove_review.py
- packages/python-packages/apiview-copilot/setup.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_models.py
- packages/python-packages/apiview-copilot/src/_sectioned_document.py
Closes #10267
- Refactors `cli review generate` to `cli review local` to clarify that it uses the local code base
- Adds `cli review remote` to request a review from the deployed Flask app
- Adds `cli app deploy` to redeploy the Flask app with the current code base
Also, this does a bunch of code refactoring due to applying the black code formatter.
> [APIView Copilot] Add script/commands to deploy app to AppService

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Program.cs
- Ensure ILogger logs to application insights
> Configure Logging in APIView

- eng/common/pipelines/templates/archetype-typespec-emitter.yml
Updates to support multiple emitters in a repo.
> Updates to emitter CI

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/rushUtils.ts
- tools/js-sdk-release-tools/src/common/utils.ts
Fix issue:https://github.com/Azure/azure-rest-api-specs/pull/33840
Test result: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4756148&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692
> ignore error message for build:sample and test

- tools/apiview/parsers/apiview-treestyle-parser-schema/CodeFile.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/main.tsp
- Update TypeSpec specification documentation for cross language ids
> Update TypeSpec specification documentation for cross language ids

- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_search_manager.py
Related to #10268. 
By processing chunks in parallel, we significantly speed up the chunked execution process.
Also, this uses a visual indicator to show chunk progress rather than a bunch of terminal logs.
> [APIVIew Copilot] Parallel chunked execution

- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/prompts/review_apiview_gpt_4.1_nano.prompty
> [APIView Copilot] Add gpt-4.1-nano model support

- packages/python-packages/apiview-copilot/src/_models.py
Necessary to work with `gpt-4.1-nano` model (not an encouraging sign 😆 )
> [APIView Copilot] Set default line_no to 0 if an unparseable value is present

- packages/python-packages/apiview-copilot/scratch/output/python/image_analysis.json
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_models.py
- Makes it easier to Ctrl+C to cancel an async chunked review
- Adds logging to `error.log`
Unfortunately, when you start getting errors you still get terminal vomit but at least the error.log makes it easier to review the errors.
> [APIView Copilot] Improve async process

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- tools/spec-gen-sdk/src/templates/commentDetailNew.handlebars
This pull request includes several updates to the `tools/spec-gen-sdk` package, focusing on adding new features, improving logging, and updating the version. The most important changes include adding a new helper function for generating pull request links, updating the version in `package.json`, and enhancing the logging mechanism to capture more detailed logs.
* Added a `getPullRequestLink` helper function in `reportStatus.ts` to generate pull request links.
* Updated the `commentDetailNew.handlebars` template to include a related pull request link if available.
* Updated the version in `package.json` from `0.4.0` to `0.4.1` to reflect the new changes.
* Renamed `captureTransport` to `messageCaptureTransport` and added it to the logger in `workflow.ts` and `workflowPackage.ts` to ensure …
> [BUG] Spec-gen-sdk Generate Html 

- tools/issue-labeler/src/IssueLabeler.Shared/LabelType.cs
- tools/issue-labeler/src/IssueLabeler.Shared/Labeler.cs
- tools/issue-labeler/src/IssueLabelerService/Answers/OpenAiAnswerService.cs
- tools/issue-labeler/src/IssueLabelerService/AzureSdkIssueLabelerService.cs
- tools/issue-labeler/src/IssueLabelerService/Labelers/LabelerFactory.cs
- tools/issue-labeler/src/IssueLabelerService/Labelers/LegacyLabeler.cs
- tools/issue-labeler/src/IssueLabelerService/Labelers/OpenAiLabeler.cs
- tools/issue-labeler/src/IssueLabelerService/Program.cs
- tools/issue-labeler/src/IssueLabelerService/TraigeRag.cs
- tools/issue-labeler/src/SearchIndexCreator/LabelRetrieval.cs
- tools/issue-labeler/src/SearchIndexCreator/Program.cs
- Store the labels in storage and get them when an issue comes back.
- Used Xiangs promp and added the set of labels from storage + evaluations.
- Fixed the deleted check for EnableAnswers
> [Ai Triage] Rag Labeler

- tools/js-sdk-release-tools/src/test/pipeline/sdkGeneration.test.ts
- tools/js-sdk-release-tools/src/utils/generateInputUtils.ts
related to https://github.com/Azure/autorest.typescript/issues/3066
> Remove camel case style option

- .github/workflows/post-apiview.yml
- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IPullRequestManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/PullRequestManager.cs
- Add APICheck change comment using GitHub workflow
> Add APIView Check comment using Github workflow

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/cspell.json
- packages/python-packages/apiview-copilot/evals/run.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
Closes #10420.
The work to actually wire up the diff review logic is tracked here: https://github.com/Azure/azure-sdk-tools/issues/10421
> [APIView Copilot] Update Flask app to receive multiple APIView revs and diff

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/evals/run.py
- packages/python-packages/apiview-copilot/pyproject.toml
- packages/python-packages/apiview-copilot/scripts/_markdown_parser.py
- packages/python-packages/apiview-copilot/scripts/deploy_app.py
- packages/python-packages/apiview-copilot/scripts/parse_guidelines.py
- packages/python-packages/apiview-copilot/scripts/remove_review.py
- packages/python-packages/apiview-copilot/setup.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_models.py
- packages/python-packages/apiview-copilot/src/_search_manager.py
- packages/python-packages/apiview-copilot/src/_sectioned_document.py
Per @kristapratico's suggestion
> [APIView Copilot] Add black configuration.

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/scripts/remote_review.py
Fixes issue where the `cli review remote` command didn't wait for the service to return. Also, added logic to output the contents of error.log in the AppService streaming logs, if present, to aid in debugging.
> [APIView Copilot] Fix issues with `cli review remote`

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- tools/spec-gen-sdk/src/types/ExecutionReport.ts
- tools/spec-gen-sdk/src/types/PackageData.ts
- Move service name into the package object
> Move service name variable into the package object

- packages/python-packages/apiview-copilot/prompts/final_comments_filter.prompty
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
> [APIView Copilot] Fix filter stage

- packages/python-packages/apiview-copilot/scripts/deploy_app.py
> [APIView Copilot] Push metadata folder to app service

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Rust.cs
issues with path combination \ vs / and clarified the calculation for the average
> path issues and clarified the calculation

- src/dotnet/APIView/APIViewWeb/Client/css/shared/mixins.scss
- src/dotnet/APIView/ClientSPA/src/app/app.component.html
- src/dotnet/APIView/ClientSPA/src/app/app.component.scss
- src/dotnet/APIView/ClientSPA/src/app/app.component.ts
- Set scroll bar size from user preference.
> Set width and height for scroll bar

- src/dotnet/APIView/APIViewWeb/Client/css/shared/mixins.scss
- src/dotnet/APIView/ClientSPA/src/app/app.component.html
- src/dotnet/APIView/ClientSPA/src/app/app.component.scss
- src/dotnet/APIView/ClientSPA/src/app/app.component.ts
Reverts Azure/azure-sdk-tools#10492
> Revert "Set width and height for scroll bar"

- eng/common/pipelines/templates/steps/save-package-properties.yml
use working directory in eng\common\pipelines\templates\steps\save-package-properties.yml
> use working directory in step definition

- .github/workflows/scheduled-event-processor.yml
- Updating the event processor version to reflect changes made in PR #10435
> Update github-event-processor version

- tools/mcp/dotnet/AzureSDKMCPHub/Azure.SDK.Tools.MCP.Hub/Azure.SDK.Tools.MCP.Hub.csproj
- tools/mcp/dotnet/AzureSDKMCPHub/Azure.SDK.Tools.MCP.Hub/Program.cs
- tools/mcp/dotnet/AzureSDKMCPHub/Azure.SDK.Tools.MCP.Hub/Services/Azure/AzureService.cs
- tools/mcp/dotnet/AzureSDKMCPHub/Azure.SDK.Tools.MCP.Hub/Tools/AzurePipelinesTool/AzurePipelinesTool.cs
Porting my standalone azp mcp server over to the azsdk mcp hub.
@scbedd
> Add azure pipelines mcp tool to mcp hub

- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
The server is sending empty string for base. We need to ensure that scenario is treated as a full API review.
> [APIView Copilot] Fix issue where diff is run with an empty string base.

- eng/common/scripts/Test-SampleMetadata.ps1
- The current taxonomy is not up-to-date and still includes AAD. Updates to the latest one
- The current link points to a 404 page. Updates to the current taxonomy page
> [Tools] Update Most Current Taxonom

- tools/apiview/parsers/rust-api-parser/CHANGELOG.md
- tools/apiview/parsers/rust-api-parser/src/process-items/processAssocConst.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processAssocType.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processConstant.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processFunction.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processImpl.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStatic.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStruct.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStructField.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTrait.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTraitAlias.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTypeAlias.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUnion.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUse.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/externalReexports.ts
Updated `RenderClasses` and `NavigationDisplayName`s for various elements to improve rendering experience.
> [rust-api-parser] UI/Rendering updates

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/AIAgentService.cs
Restructure AI Agent service to connect when service is required
> Restructure AI Agent service to connect when service is required

- eng/common/mcp/azure-sdk-mcp.ps1
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/MCPToolInterface.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Azure.Sdk.Tools.Cli.csproj
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/CommandFactory.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/TypeSpecProject.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HelloWorldTool/HelloWorldTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HostServer/HostServerTool.cs
- tools/azsdk-cli/ci.yml
Resolves #10583 ....and cleans up a bunch of unused usings.
> Produce `azsdk` binary!

- tools/test-proxy/documentation/test-proxy/faq.md
I'm realizing I should mime @weshaggard  on this stuff.
> Adding `test-proxy` FAQ document

- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- Enable Copy Review Text in Diff View
> Enable copy review text in diff view

- eng/common/pipelines/templates/steps/verify-links.yml
- eng/common/scripts/Verify-Links.ps1
- eng/pipelines/githubio-linkcheck.yml
Use locally cloned repos to check github links to avoid rate-limiting.
> Improve link checking for github links

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/prompts/guidelines_diff_review.prompty
- packages/python-packages/apiview-copilot/prompts/summarize_api.prompty
- packages/python-packages/apiview-copilot/prompts/summarize_diff.prompty
- packages/python-packages/apiview-copilot/src/_sectioned_document.py
Mostly make the summary prompts more concise.
> [APIView Copilot] Tweak Prompts

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/SpecPullRequestHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/TypeSpecHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/ApiviewData.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/CommandResponse.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/GenericResponse.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/PullRequestDetails.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/ReleasePlan.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/TypeSpecProject.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/AIAgentService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/GitHubService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelinesTool/AzurePipelinesTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HelloWorldTool/HelloWorldTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HostServer/HostServerTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SDKWorkFlowTool/SDKWorkFlowTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecCommonTools/SpecCommonTools.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecPullRequestTools/SpecPullRequestTools.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecValidationTool/SpecValidationTool.cs
Merge latest MCP server changes to Azure SDK cli MCP server.
> Merge AZure SDK TypeSpec MCP to Azure SDK CLI MCP server

- src/dotnet/APIView/APIViewUnitTests/LanguageServiceHelpersTests.cs
- src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
- correctly map language to the exact case supported in APIView
> Map language Alias correctly

- tools/apiview/emitters/typespec-apiview/CHANGELOG.md
- tools/apiview/emitters/typespec-apiview/package-lock.json
- tools/apiview/emitters/typespec-apiview/package.json
- tools/apiview/emitters/typespec-apiview/src/apiview.ts
- tools/apiview/emitters/typespec-apiview/src/namespace-model.ts
- tools/apiview/emitters/typespec-apiview/src/version.ts
Partner team reported issue blocking CI.
> [TypeSpec APIView] Fix issue with HasSuffixSpace failing

- eng/common/pipelines/templates/steps/check-spelling.yml
Fixes https://github.com/Azure/azure-sdk-tools/issues/10464
> cspell: Remove node version requirement, node is already on the agent

- eng/common/TestResources/TestResources-Helpers.ps1
Some users already have `az bicep` installed. We should be able to use that if `bicep` cli isn't installed
> Support `az bicep build` in New-TestResources

- eng/common/mcp/azure-sdk-mcp.ps1
Fixes to auto-download/start azsdk mcp
> Fixes to auto-download/start azsdk mcp

- eng/common/pipelines/templates/steps/sparse-checkout.yml
Test runs: 
[test run against private repo](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4872297&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692)
[test run against public repo](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4871987&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76)
> Add option to preserve auth

- tools/js-sdk-release-tools/package.json
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4885619&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=83516c17-6666-5250-abde-63983ce72a49
> update version for new input parameters api-version and sdk-release type

- packages/python-packages/apiview-copilot/README.md
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/scratch/output/python/image_analysis.json
- packages/python-packages/apiview-copilot/scripts/search_kb.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_search_manager.py
The PR changes `--use-rag` to `--mode` and sets RAG as the default.
It also fixes issues with the context implementation that prevented proper resolution of the knowledge graph.
> [APIView Copilot] Update RAG Context Algorithm. Make RAG Default

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/dev_requirements.txt
- packages/python-packages/apiview-copilot/requirements.txt
- packages/python-packages/apiview-copilot/scripts/deploy_app.py
- packages/python-packages/apiview-copilot/start_archagent.bat
- packages/python-packages/apiview-copilot/startup.txt
FastAPI is better supported in Azure Foundry. This will better position us to deploy copilot behind MCP.
> [APIView Copilot] Convert app from Flask to FastAPI

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/rushUtils.ts
fixes https://dev.azure.com/azure-sdk/public/_build/results?buildId=4901091&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692&l=841
> [JS] fix bugs

- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
Adds some canary code to avoid calling LLMs when we can't authenticate against Search or CosmosDB.
> Logging Tweaks and Canary Code

- eng/common/pipelines/templates/archetype-typespec-emitter.yml
Fixes https://github.com/Azure/azure-sdk-for-net/issues/50291
> Use the updated config in regenerate step

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
Handles case where PackageVersion is null
> Modify logic for considering Packageversion for comparing APIRevisions

- eng/common/scripts/Helpers/ApiView-Helpers.ps1
- Send python APIView artifact path as codeFile param
> Use CodeFile for pushing Python APIView

- eng/common/scripts/Helpers/ApiView-Helpers.ps1
> Minor APIView Fix

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
I am currently executing on disabling the java CI pipelines.
> Disable `Java` CI Pipeline Generation

- packages/python-packages/apiview-copilot/scratch/apiviews/python/keyvault_secrets_4.11.0b1.txt
- packages/python-packages/apiview-copilot/scripts/remote_review.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- Updates CLI
- Tweaks search to omit documents tagged "documentation" or "vague".
> [APIView GPT] Tweak Context Parameters

- src/dotnet/APIView/APIViewUnitTests/CodeFileHelpersTest.cs
- src/dotnet/APIView/APIViewUnitTests/ManagerHelperTests.cs
- src/dotnet/APIView/APIViewWeb/Helpers/ManagerHelpers.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
https://github.com/Azure/azure-sdk-tools/issues/9796
> properly redirect diff urls

- eng/common/spelling/package-lock.json
This PR applies changes done by `npm audit fix`.
> [spelling tool] upgrade indirect dependency `brace-expansion` version to 2.0.2

- eng/common/pipelines/templates/steps/detect-api-changes.yml
-  Moving the PR APIView step condition to compile time so the step does not show up if it is not going to run.
> Condition the APIView step at compile time

- src/dotnet/APIView/APIView/Model/CodeFile.cs
- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
- src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/SwaggerLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/TypeSpecLanguageService.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/ReviewsController.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- Resolves https://github.com/Azure/azure-sdk-tools/issues/10763
> Show link to sandboxing pipeline in API review being generated

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/metadata/python/filter.yaml
- packages/python-packages/apiview-copilot/scratch/output/python/keyvault_secrets_4.11.0b1.json
- packages/python-packages/apiview-copilot/scripts/deploy_app.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_retry.py
- packages/python-packages/apiview-copilot/src/agent/_agent.py
- packages/python-packages/apiview-copilot/startup.txt
Well, GH Copilot undid this somehow int he Semantic Kernel PR, so this restores the functionality and adds CLI commands to test the functionality.
> [APIView Copilot] Overhaul LRO Review Endpoints

- eng/pipelines/mirror-repos.yml
cc @msyyc as it looks like you removed the release/v3 branch from python repo
> Remove python release/v3 branch

- src/dotnet/APIView/ClientSPA/src/app/_components/conversations/conversations.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/conversations/conversations.component.ts
- Ensure comment downvote updates immediately on conversation offcanvas view.
> Ensure thumbs down button updates on conversation off canvas

- tools/ai-evals/azure-mcp/README.md
- tools/ai-evals/azure-mcp/data.jsonl
- tools/ai-evals/azure-mcp/followup.json
- tools/ai-evals/azure-mcp/requirements.txt
- tools/ai-evals/azure-mcp/run.py
- tools/ai-evals/azure-mcp/tests.yml
Adds this pipeline which runs the evals script that collects data on tool call accuracy of azure-mcp: https://dev.azure.com/azure-sdk/internal/_build?definitionId=7782&_a=summary
> initial tool call accuracy eval for azure-mcp

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Azure.Sdk.Tools.Cli.Tests.csproj
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Helpers/SpecPullRequestHelperTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Helpers/TypeSpecHelperTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/MockServices/MockDevOpsService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/ReleasePlanToolTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/employee.tsp
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-10-01-preview/Employees_CreateOrUpdate.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-10-01-preview/Employees_Delete.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-10-01-preview/Employees_Get.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-10-01-preview/Employees_ListByResourceGroup.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-10-01-preview/Employees_ListBySubscription.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-10-01-preview/Employees_Update.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-10-01-preview/Operations_List.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-11-01/Employees_CreateOrUpdate.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-11-01/Employees_Delete.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-11-01/Employees_Get.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-11-01/Employees_ListByResourceGroup.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-11-01/Employees_ListBySubscription.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-11-01/Employees_Update.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/examples/2021-11-01/Operations_List.json
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/main.tsp
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TypeSpecTestData/specification/testcontoso/Contoso.Management/tspconfig.yaml
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/SpecPullRequestHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
This also fixes a bug in create release plan tool and marks all options in create release plan cli as required.
> Add test for release plan tool and helpers

- eng/common/mcp/azure-sdk-mcp.ps1
> Fix path in mcp installer

- .github/workflows/tsp-client-tests.yml
- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/ci.yml
- tools/tsp-client/src/commands.ts
> Log npm package versions after install

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/scratch/output/python/keyvault_secrets_4.11.0b1.json
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
Fixes #11005
- Always created a jobId when ApiViewReviewer is created.
- Adds job id to logs
- detects if run in a TTY and optimizes logging format accordingly
- ensures status messages are printed with the jobId in non-TTY mode since calls may be interleaved
> [APIView Copilot] Logging improvements

- eng/common/TestResources/deploy-test-resources.yml
Pass TestResourcesDirectory from deploy-test-resources.yml to New-TestResources.ps1
> Support TestResourcesDirectory in deploy-test-resources.yml

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/SpecWorkFlowToolTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecWorkflowTool/SpecWorkFlowTool.cs
Fixes issue #11059 Generate SDK MCP failure due to invalid work item ID.
> Fix issue in Generate SDK MCP tool

- src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Models/AIReviewModel.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/nav-bar/nav-bar.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_dtos/aiReviewJobCompletedDto.ts
- src/dotnet/APIView/ClientSPA/src/app/_helpers/common-helpers.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/notificationsModel.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/notifications/notifications.service.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/notifications/notifications.service.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/signal-r/signal-r.service.ts
- src/dotnet/APIView/ClientSPA/src/app/app.component.ts
- Always show Copilot review feedback for initiating user regardless of current page
Fixes #11076
> Improve Copilot Realtime Feedback

- src/dotnet/APIView/ClientSPA/src/app/_models/notificationsModel.ts
- Don't use createdBy in the id to avoid duplictes.
> Don't use date for notification Id

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/tsp/main.tsp
Fixes 422/500 issues with `agent/mention` endpoint.
> [APIView Copilot] Fix mention endpoint

- src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
Please let me know if there is a better place for this small documentation
> Deployment to production documentation

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_database_manager.py
- packages/python-packages/apiview-copilot/src/agent/_agent.py
- packages/python-packages/apiview-copilot/src/agent/plugins/__init__.py
- packages/python-packages/apiview-copilot/src/agent/plugins/_database_plugin.py
- packages/python-packages/apiview-copilot/src/agent/plugins/_planner_plugin.py
- This PR ensures that all database functionality is channeled through a singleton DatabaseManager
- Adds a `db get` command to the CLI as well.
> [APIView Copilot] Refactor DatabasePlugin to use DatabaseManager

- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/cspell.json
- packages/python-packages/apiview-copilot/dev_requirements.txt
- packages/python-packages/apiview-copilot/scripts/apiview_permissions.py
This script adds the necessary permissions to the logged-in user to access the staging CosmosDB for APIView. This is necessary to run `cli.bat apiview get-comments`
> [APIView Copilot] Add APIView CosmosDB permissions script

- packages/python-packages/apiview-copilot/.gitignore
- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/scripts/search_kb.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_database_manager.py
- packages/python-packages/apiview-copilot/src/_models.py
- packages/python-packages/apiview-copilot/src/_search_manager.py
- packages/python-packages/apiview-copilot/src/agent/plugins/_database_plugin.py
- packages/python-packages/apiview-copilot/src/agent/plugins/_search_plugin.py
- packages/python-packages/apiview-copilot/src/agent/plugins/_utility_plugin.py
Working on issues related to Search and Database, in support of Agent mention.
> [APIView Copilot] Updates for SearchManager and DatabaseManagers

- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/src/_models.py
Addresses (partially) #10946
**Command:**
`cli.bat metrics report -s 2025-07-10 -e 2025-07-31`
**Output:**
```json
{
"end_date": "2025-07-31",
"metrics": {
"ai_vs_manual_comment_ratio": 12.15,
"good_vs_bad_comment_ratio": 0.25
},
"start_date": "2025-07-10"
}
```
> [APIView Copilot] Add basic metrics

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/MockServices/MockGitHubService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/DownloadPromptsToolTests.cs
- Added in some mocking for the GitHub Service. (Mocking being one of those things I've rarely done so i gave it my best go)
- Used that to make tests for the Download MCP Tool.
- Still need to make tests for the Prompt Validation part but figured I wouldn't dump it all in one PR
> Mocking for GitHub Service and Download MCP Tool Tests

- tools/spec-gen-sdk/.prettierrc
- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/entrypoint.ts
- tools/spec-gen-sdk/src/automation/logging.ts
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/automation/workflowHelpers.ts
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- tools/spec-gen-sdk/src/types/PackageData.ts
- tools/spec-gen-sdk/src/types/Workflow.ts
- tools/spec-gen-sdk/src/types/validator.ts
- tools/spec-gen-sdk/src/utils/fsUtils.ts
- tools/spec-gen-sdk/src/utils/handleSuppressionLines.ts
- tools/spec-gen-sdk/src/utils/runScript.ts
- tools/spec-gen-sdk/src/utils/workflowUtils.ts
- tools/spec-gen-sdk/test/automation/entrypoint.test.ts
- tools/spec-gen-sdk/test/automation/workflow.test.ts
- tools/spec-gen-sdk/test/automation/workflowHelpers.test.ts
- tools/spec-gen-sdk/test/fixtures/specificationRepositoryConfiguration.json
- tools/spec-gen-sdk/test/fixtures/swagger_to_sdk_config.json
This pull request includes multiple changes that improve code formatting, streamline imports, and refactor functionality across several files in the `tools/spec-gen-sdk` project. The most significant changes focus on consolidating utility functions, enhancing logging capabilities, and adhering to consistent coding standards.
* Updated `.prettierrc` with new formatting rules, including `semi: true`, `trailingComma: "all"`, and `singleQuote: true`, ensuring consistent code formatting across the project.
* Applied consistent single quotes and added missing semicolons in various files, such as `entrypoint.ts` and `workflow.ts`. [[1]](diffhunk://#diff-7f95fa607cb94379896483d74c13dc304d3f5cf9d4a12e06df294b4dbbe3349eL83-R35) [[2]](diffhunk://#diff-8abb2fc1b35d9aa372c77e814cacaa598863a407057a1a798 …
> Add test for spec-gen-sdk  U1

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/FileValidationToolTests.cs
- Adding on to https://github.com/Azure/azure-sdk-tools/pull/11161#event-18626845767 with the extra file validation tests
> File Validation MCP Tool Tests

- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_models.py
- packages/python-packages/apiview-copilot/tests/review_result_test.py
> [APIView Copilot] Fix rule_id validation

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/AzurePipelines/PipelineAnalysisTool.cs
[azsdk-cli] Throw exception if user is not authorized with devops REST calls
> [azsdk-cli] Throw exception if user is not authorized with devops REST calls

- tools/azsdk-cli/ci.yml
Fix release stage conditional for azsdk cli
> Fix release stage conditional for azsdk cli

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecPullRequestTools/SpecPullRequestTools.cs
- Remove dependency on constant values for the repository so it can be used in any repository.
> [Devex Agent] Create Pull request support all repos

- tools/stress-cluster/cluster/kubernetes/stress-test-addons/deploy.ps1
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/update-charts.ps1
- tools/stress-cluster/cluster/provision.ps1
Change instances of /bin/env shebang to /usr/bin/env
> Change instances of /bin/env shebang to /usr/bin/env

- .github/CODEOWNERS
@weshaggard I think this is the right way to do it but not sure if we support this in the tools repo currently?
> Add azsdk-cli label to tools/azsdk-cli changes

- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/logging.ts
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/automation/workflowHelpers.ts
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- tools/spec-gen-sdk/src/types/PackageData.ts
- tools/spec-gen-sdk/src/utils/reportStatusUtils.ts
- tools/spec-gen-sdk/src/utils/requireJsonc.ts
- tools/spec-gen-sdk/test/automation/__snapshots__/reportStatus.test.ts.snap
- tools/spec-gen-sdk/test/automation/entrypoint.test.ts
- tools/spec-gen-sdk/test/automation/logging.test.ts
- tools/spec-gen-sdk/test/automation/reportStatus.test.ts
- tools/spec-gen-sdk/test/automation/sdkAutomationState.test.ts
- tools/spec-gen-sdk/test/automation/workflow.test.ts
- tools/spec-gen-sdk/test/automation/workflowHelpers.test.ts
- tools/spec-gen-sdk/test/automation/workflowPackage.test.ts
- tools/spec-gen-sdk/test/utils.test.ts
- tools/spec-gen-sdk/test/workflow.test.ts
This pull request refactors and modularizes code in the `tools/spec-gen-sdk` package to improve maintainability and readability. Key changes include consolidating utility functions into a new file, replacing individual imports with namespace imports for `fs` and `path`, and exporting previously internal functions for broader use.
* **Utility Functions Consolidation**: Moved Handlebars-related helper functions, templates, and rendering logic into a new file `tools/spec-gen-sdk/src/utils/reportStatusUtils.ts`. This modularizes the code and removes redundant definitions from `reportStatus.ts`. [[1]](diffhunk://#diff-692bac85db5dc0647e0c765d7c1f47d3da75cd577cd807b32ac962107c0f71e0R1-R102) [[2]](diffhunk://#diff-c1cbffd995bcfe16dc4eab593b7e0217eb8cb96689f5ab3260b25a15ea5e5a6dL338-L434)
* …
> [spec-gen-sdk] Add Unit Test

- src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/ReviewsController.cs
- src/dotnet/APIView/APIViewWeb/Models/ApprovalRequest.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/reviews/reviews.service.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/revisions/revisions.service.ts
Issue: https://github.com/Azure/azure-sdk-tools/issues/11502
> Require Intent to Approve or Unapprove a Review (Make API Idempotent) 

- src/dotnet/APIView/APIViewWeb/Languages/SwiftLanguageService.cs
This is set to false but it is actually true, fixing.
> Fix swift UsesTreeStyleParser value

- src/dotnet/APIView/APIViewUnitTests/CopilotPollingBackgroundHostedServiceTests.cs
- src/dotnet/APIView/APIViewWeb/HostedServices/CopilotJobProcessor.cs
- src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/HostedServices/ICopilotJobProcessor.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
issue: https://github.com/Azure/azure-sdk-tools/issues/11249
Fix test by doing a refactor, the code didn't change, it was just split so it was testable without the background service.
> Fix CopilotPollingBackgroundHostedService tests flakiness

- src/dotnet/APIView/APIViewWeb/Helpers/AgentHelpers.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
Fixes: https://github.com/Azure/azure-sdk-tools/issues/11167
> Send diagnostics to copilot agent

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/SpecPullRequestHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/GitHubService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecPullRequestTools/SpecPullRequestTools.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecValidationTool/SpecValidationTool.cs
- tools/azsdk-cli/README.md
Following up on the work on: https://github.com/Azure/azure-sdk-tools/pull/11631
> Improve logging practices

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Program.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/Agent/AzureAgentService.cs
Also adding more prompt instructions to enforce json for agent mode so we can de-serialize the response.
> Suppress info logging for azure clients

- src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
Part of: https://github.com/Azure/azure-sdk-tools/issues/10465
> [API View] Differentiate between java and android for agent copilot review request

- tools/azsdk-cli/README.md
Documenting where common instructions should go
> Reusable instructions guide

- tools/test-proxy/typespec/client.tsp
- tools/test-proxy/typespec/main.tsp
- tools/test-proxy/typespec/models.tsp
- tools/test-proxy/typespec/package-lock.json
- tools/test-proxy/typespec/package.json
- tools/test-proxy/typespec/tspconfig.yaml
I am generating from this in https://github.com/Azure/azure-sdk-for-net/pull/51611
> Update test-proxy TypeSpec

- tools/azsdk-cli/README.md
Reintroduced the Data Collection section and its details, including telemetry configuration, to the README.
> Data Collection and Telemetry Configuration sections

- src/dotnet/APIView/APIViewUnitTests/AzureEngSemanticVersionTests.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
> [API View] Verified if revision is not a preview before making copilot review requiered

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/GitHub/PullRequestTools.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlan/ReleasePlanTool.cs
MCP tool to get pull request details is failing because it is looking for PR in forked repo instead of upstream repo.
> Fix issue in MCP to get pull request details

- packages/python-packages/apiview-copilot/dev_requirements.txt
- packages/python-packages/apiview-copilot/requirements.txt
> [AVC] Remove asyncio

- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
I was noticing that generic comments were being rejected at a 100% rate and this was the cause.
> [AVC] Fix issue with generic judge phase

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlan/SpecWorkFlowTool.cs
Add retry when updating DevOps work item to avoid DevOps update conflict
> Add retry to resolve DevOps update conflict issue

- src/dotnet/ErrorAnalyzers/samples/basic-usage/Program.cs
- src/dotnet/ErrorAnalyzers/src/Azure.Tools.ErrorAnalyzers/AnalyzerPrompts.General.cs
- src/dotnet/ErrorAnalyzers/src/Azure.Tools.ErrorAnalyzers/AnalyzerPrompts.cs
- src/dotnet/ErrorAnalyzers/src/Azure.Tools.ErrorAnalyzers/ErrorAnalyzerService.cs
- src/dotnet/ErrorAnalyzers/tests/Azure.Tools.ErrorAnalyzers.Tests/AnalyzerPromptProviderTests.cs
- src/dotnet/ErrorAnalyzers/tests/Azure.Tools.ErrorAnalyzers.Tests/ErrorAnalyzerServiceTests.cs
This PR implements a comprehensive fallback mechanism that ensures all errors receive AI-powered assistance, even when specific rule handlers don't exist. 
The implementation adds a universal __FALLBACK__ prompt in `AnalyzerPrompts.General.cs` that provides intelligent analysis for various error sources including TypeSpec compiler errors, .NET compiler errors custom analyzer errors. The fallback uses pattern recognition to identify error sources and provides targeted solutions with step-by-step instructions.
> Fallback Mechanism for Unknown Error Types

- tools/sdk-ai-bots/azure-sdk-qa-bot-backend/Dockerfile
update the docker image to be compliant
- using the Microsoft container registry images
- simplify the stage of Dockerfile 
```
##[warning]Discovered a reference to an image from an unapproved registry that violates the security policies and standards for containers within Microsoft. Reference to image 'golang:1.23-alpine' on line 1 of tools/sdk-ai-bots/azure-sdk-qa-bot-backend/Dockerfile.
##[warning]Discovered a reference to an image from an unapproved registry that violates the security policies and standards for containers within Microsoft. Reference to image 'alpine:latest' on line 13 of tools/sdk-ai-bots/azure-sdk-qa-bot-backend/Dockerfile.
##[warning]Discovered a reference to an image from an unapproved registry that violates the security policies and standards for containers within …
```
> fix docker image

- packages/python-packages/apiview-copilot/.vscode/settings.json
- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/src/_permissions.py
> [AVC] Add permission grant/revoke commands

- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/TreeToken/CodeFileBuilder.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CodeFileTests.cs
> Fix duplicate lineIds

- src/dotnet/APIView/apiview.yml
In order to create a pipeline that resolves this issue: https://github.com/Azure/azure-sdk-tools/issues/11913
> Add control on the stages to be run 

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts
- tools/js-sdk-release-tools/src/common/devToolUtils.ts
- tools/js-sdk-release-tools/src/common/rushUtils.ts
- tools/js-sdk-release-tools/src/hlc/generateMgmt.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
fixes https://dev.azure.com/azure-sdk/public/_build/results?buildId=5316265&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692&l=2452
1200s passed in https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5316520&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692
> [JS Automation] fix lint timeout bug

- tools/sdk-ai-bots/azure-sdk-qa-bot-backend/ci.yml
1. update service connection
2. update trigger logic
> setup backend ci pipeline

- .github/CODEOWNERS
Hey @marianan , as discussed offline, I created this PR to add codeowners from Shanghai mgmt side. Thanks!
> Update CODEOWNERS for SDK Agent to include mgmt crews

- eng/common/instructions/azsdk-tools/sdk-details-in-release-plan.instructions.md
Add additional instructions to help copilot get package name using correct fields
> Add copilot instruction for package name properties in typespec config

- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
closes: https://github.com/Azure/azure-sdk-tools/issues/12151
> [APIView] TypeSpec should not have the Copilot review button

- tools/apiview/parsers/rust-api-parser/CHANGELOG.md
- tools/apiview/parsers/rust-api-parser/package-lock.json
- tools/apiview/parsers/rust-api-parser/package.json
- tools/apiview/parsers/rust-api-parser/process-all-packages.sh
- tools/apiview/parsers/rust-api-parser/src/main.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processAssocConst.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processAssocType.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processConstant.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processEnum.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processExternType.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processFunction.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processImpl.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processItem.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processMacro.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processModule.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processProcMacro.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStatic.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStruct.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStructField.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTrait.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTraitAlias.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTypeAlias.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUnion.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUse.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/externalReexports.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/generateDocReviewLine.ts
- tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts
Fixes #11860 by implementing comprehensive duplicate line ID detection and prevention in the Rust API parser.
The Rust API parser was generating duplicate line IDs, particularly for similar trait implementations like `impl TryFrom<&Url>` and `impl TryFrom<Url>`, causing Copilot reviews to fail immediately without diagnostics.
- Implemented semantic replacements that preserve meaningful distinctions (e.g., `&` → `ref_`, `<>` → `_of_/_end_`)
- Improved external re-export handling: Use full paths instead of just item names to prevent collisions
- **Defensive duplicate detection**: Added automatic counter-based fixing with comprehensive validation before JSON serialization
- Explained why deduplication is needed for re-exports and complex type scenarios
<details>
<summary>✅ Batch Processing …
> [rust-api-parser] Fix duplicate line ID generation

- eng/scripts/Approve-Eng-Common-Sync-PRs.ps1
Sometimes devops login gets blocked via conditional access (e.g. logging in from another location), so it's helpful to have the override to pass in a file.
> Add prs created override for eng sync script

- tools/apiview/parsers/js-api-parser/CHANGELOG.md
- tools/apiview/parsers/js-api-parser/designs/cross-lang-ids.md
- tools/apiview/parsers/js-api-parser/package.json
- tools/apiview/parsers/js-api-parser/readme.md
- tools/apiview/parsers/js-api-parser/src/export.ts
- tools/apiview/parsers/js-api-parser/src/generate.ts
- tools/apiview/parsers/js-api-parser/src/models.ts
- tools/apiview/parsers/js-api-parser/test/generate.spec.ts
- add a feature request doc
- add implementation by copilot
Related code generator PR: https://github.com/Azure/autorest.typescript/pull/3497
> [js-api-parser] add cross language id support

- eng/pipelines/apiview-review-gen-python.yml
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
> [python apiview] update pinned version to 0.3.23

- tools/azsdk-cli/docs/new-tool.md
[azsdk-cli] Fix TOC ordering in new-tool.md
> [azsdk-cli] Fix TOC ordering in new-tool.md

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/ProgramTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/CommandRunner.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Program.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
Fix scoping/lifetime issue with language check service
> Fix scoping/lifetime issue with language check service
