Azure/azure-sdk-tools

- README.md
Updating the reference from `README.md` to `readme.md`
> Correcting a Relative Readme Reference

- packages/python-packages/doc-warden/warden/cmd_entry.py
- packages/python-packages/doc-warden/warden/enforce_readme_content.py
* attempting to figure out why a crash is not occurring on devops test build.
> Working on Bugfixes for Current Release

- .azure-pipelines/warden.yml
quick change, but gives a bit of peace of mind prior to every package update.
> Adding Usage Tests to Warden

- packages/python-packages/doc-warden/README.md
- packages/python-packages/doc-warden/warden/enforce_readme_presence.py
- packages/python-packages/doc-warden/warden/version.py
* presence bugfix
* fix for discovering readmes for .net
> Various .NET Bugfixes

- packages/python-packages/doc-warden/warden/version.py
Release published, but the related git releases didn't. Working through that.
> VersionBump

- .azure-pipelines/warden.yml
Switch from Binaries to Artifacts directory; ensure clean up of artifacts on each build.
> Updated folder used for preparing files for GitHub release

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.sln
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs
I think sln was lost during the move.
> Add sln, fix diagnostic duplication bug, add another namespace

- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/warden/version.py
Will be used to test the release note methodology.
> ChangeLog for Warden

- src/dotnet/APIView/APIView/APIView.csproj
- src/dotnet/APIView/APIView/AssemblyAPIV.cs
- src/dotnet/APIView/APIView/EventAPIV.cs
- src/dotnet/APIView/APIView/FieldAPIV.cs
- src/dotnet/APIView/APIView/MethodAPIV.cs
- src/dotnet/APIView/APIView/NamedTypeAPIV.cs
- src/dotnet/APIView/APIView/NamespaceAPIV.cs
- src/dotnet/APIView/APIView/ParameterAPIV.cs
- src/dotnet/APIView/APIView/PropertyAPIV.cs
- src/dotnet/APIView/APIView/TreeRendererAPIV.cs
- src/dotnet/APIView/APIView/TypeParameterAPIV.cs
- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/BlobAssemblyRepository.cs
- src/dotnet/APIView/APIViewWeb/Models/AssemblyModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Delete.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
cc: @pakrym 
Added setters to type properties and default constructors to allow JSON serializing with System.Text.Json.
> Add JSON serialization support

- scripts/python/repo_labels/github_labels.txt
- scripts/python/repo_labels/github_repos.txt
- scripts/python/repo_labels/label_tool.py
*Master list of service labels
*Master list of repos
*Tool
> Tool to push labels to multiple repos

- tools/eslint-plugin-azure-sdk/ci.yml
This PR sets up the eslint-plugin-azure-sdk tool as an example of a multi-stage unified pipeline. The publishing step isn't put in yet as I'll be adding that configuration directly on master.
> Updated pipeline definition.

- tools/eslint-plugin-azure-sdk/package.json
This PR will pump the ```eslint-plugin-azure-sdk``` version to ```1.0.1-preview.1``` just to test the end to end CI workflow until we get public feeds in place.
> Bump package version to preview.

- tools/eslint-plugin-azure-sdk/package.json
Quick demo of unified pipelines with approval checks.
> Bumped version to preview.2

- tools/pipeline-generator/ci.yml
Putting in the pipeline configuration for pipeline generator (all dummy actions right now, will iterate on another PR).
> Added dummy CI for pipeline generator.

- tools/pipeline-generator/ci.yml
Quick fix to the pipeline generator CI I had a copy paste error.
> Fixed path filter for pipeline generator.

- src/dotnet/APIView/APIView/AttributeAPIV.cs
- src/dotnet/APIView/APIView/AttributeConstructArgAPIV.cs
- src/dotnet/APIView/APIView/EventAPIV.cs
- src/dotnet/APIView/APIView/FieldAPIV.cs
- src/dotnet/APIView/APIView/HTMLRendererAPIV.cs
- src/dotnet/APIView/APIView/MethodAPIV.cs
- src/dotnet/APIView/APIView/NamedTypeAPIV.cs
- src/dotnet/APIView/APIView/NamespaceAPIV.cs
- src/dotnet/APIView/APIView/ParameterAPIV.cs
- src/dotnet/APIView/APIView/PropertyAPIV.cs
- src/dotnet/APIView/APIView/TextRendererAPIV.cs
- src/dotnet/APIView/APIView/Token.cs
- src/dotnet/APIView/APIView/TokenAPIV.cs
- src/dotnet/APIView/APIView/TreeRendererAPIV.cs
- src/dotnet/APIView/APIView/TypeReference.cs
- src/dotnet/APIView/APIView/TypeReferenceAPIV.cs
- src/dotnet/APIView/APIViewTest/EventTests.cs
- src/dotnet/APIView/APIViewTest/FieldTests.cs
- src/dotnet/APIView/APIViewTest/MethodTests.cs
- src/dotnet/APIView/APIViewTest/NamedTypeTests.cs
- src/dotnet/APIView/APIViewTest/NamespaceTests.cs
- src/dotnet/APIView/APIViewTest/ParameterTests.cs
- src/dotnet/APIView/APIViewTest/PropertyTests.cs
- src/dotnet/APIView/APIViewWeb/wwwroot/css/site.css
- src/dotnet/APIView/TestLibrary/TestClass.cs
Implementation of click-based page navigation using type references.
> Type-Based Page Navigation in APIView

- tools/eslint-plugin-azure-sdk/package.json
This PR sets the package version 1.0.0.
> Set package version.

- tools/version-guard/Microsoft.Azure.Sdk.Tools.VersionGuard/Microsoft.Azure.Sdk.Tools.VersionGuard.csproj
- tools/version-guard/Microsoft.Azure.Sdk.Tools.VersionGuard/Program.cs
- tools/version-guard/VersionGuard.sln
- tools/version-guard/ci.yml
This is the basic scaffolding for CI of a version guard tool - no functionality yet.
> Initial commit of version guard for CI.

- src/dotnet/APIView/APIView/AttributeAPIV.cs
- src/dotnet/APIView/APIView/AttributeConstructArgAPIV.cs
- src/dotnet/APIView/APIView/HTMLRendererAPIV.cs
- src/dotnet/APIView/APIView/MethodAPIV.cs
- src/dotnet/APIView/APIView/NamespaceAPIV.cs
- src/dotnet/APIView/APIView/TextRendererAPIV.cs
- src/dotnet/APIView/APIView/TreeRendererAPIV.cs
- src/dotnet/APIView/APIViewTest/MethodTests.cs
- src/dotnet/APIView/APIViewTest/NamedTypeTests.cs
- src/dotnet/APIView/APIViewWeb/BlobAssemblyRepository.cs
- src/dotnet/APIView/APIViewWeb/BlobCommentRepository.cs
- src/dotnet/APIView/APIViewWeb/Models/CommentModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Upload.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
- src/dotnet/APIView/APIViewWeb/wwwroot/css/site.css
- src/dotnet/APIView/APIViewWeb/wwwroot/js/site.js
Added ability to comment on named type and method declaration tokens. Comments appear as a single thread at the bottom of the page for now, and support creation and deletion.
> Preliminary Commenting on APIView

- tools/eslint-plugin-azure-sdk/docs/rules/ts-doc-internal.md
- tools/eslint-plugin-azure-sdk/docs/rules/ts-use-interface-parameters.md
PR #109 disabled rules for specific files, but I forgot to reflect these changes in the documentation - this PR addresses that.
> Update docs to reflect file-ignore rule changes

- eng/pipelines/notifications.yml
- tools/notification-configuration/common/Services/AzureDevOpsService.cs
- tools/notification-configuration/github-codeowner-subscriber/Program.cs
- tools/notification-configuration/notification-creator/Program.cs
* Creates pipeline for notification subscription
* Updated parameter names to make for easier typing
* Running in pipelines on a linux host revealed an, in retrospect, obvious concurrency issue in `GetClientAsync`... Given that performance isn't of overwhelming concern here a lock would probably be appropriate and more readable.
> Notification pipelines

- tools/notification-configuration/notification-creator/NotificationConfigurator.cs
This oneliner has been causing problems in the java pipelines
> do not hardcode purpose

- src/dotnet/APIView/APIView/AttributeAPIV.cs
- src/dotnet/APIView/APIView/HTMLRendererAPIV.cs
- src/dotnet/APIView/APIView/MethodAPIV.cs
- src/dotnet/APIView/APIView/NamedTypeAPIV.cs
- src/dotnet/APIView/APIView/TreeRendererAPIV.cs
- src/dotnet/APIView/APIViewTest/MethodTests.cs
- src/dotnet/APIView/APIViewTest/NamedTypeTests.cs
- src/dotnet/APIView/APIViewWeb/ExtensionMethods.cs
- src/dotnet/APIView/APIViewWeb/Models/CommentThreadModel.cs
- src/dotnet/APIView/APIViewWeb/Models/PartialViewModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Upload.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
- src/dotnet/APIView/APIViewWeb/Properties/launchSettings.json
- src/dotnet/APIView/APIViewWeb/wwwroot/css/site.css
- src/dotnet/APIView/APIViewWeb/wwwroot/js/site.js
This change introduced partial page updates upon commenting actions. Rather than reloading the page upon adding or deleting a comment on a review, a partial view of the updated (or removed) comment thread is loaded.
> Partial Updates for Commenting in APIView

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/BlobAssemblyRepository.cs
- src/dotnet/APIView/APIViewWeb/BlobCommentRepository.cs
- src/dotnet/APIView/APIViewWeb/Models/AssemblyCommentsModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
This change switches from preview 1 of Azure.Storage.Blobs to preview 2, and changes how comments are stored in blobs. Rather than storing each comment as a standalone blob, comments for each review are grouped into a single blob.
> Comment Storage Update in APIView

- tools/eslint-plugin-azure-sdk/package-lock.json
- tools/eslint-plugin-azure-sdk/package.json
Bumps `@azure/eslint-plugin-azure-sdk` to `1.3.0-preview.4`.
> Bump version

- tools/eslint-plugin-azure-sdk/package.json
Bumps `@azure/eslint-plugin-azure-sdk` to `2.0.0`.
> Release @azure/eslint-plugin-azure-sdk 2.0.0

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
Discovered this inconsistency while creating and updating pipelines that required multiple variable groups.
> use correct usage documentation for pipeline generator

- src/dotnet/APIView/APIView/CodeFile.cs
- src/dotnet/APIView/APIView/CodeFileBuilder.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/Navigation.cshtml
- src/dotnet/APIView/APIViewWeb/wwwroot/css/site.css
> Assembly name as part of model, infinite level navigation

- tools/eslint-plugin-azure-sdk/ci.yml
This PR normalizes the ESLint release process to the new unified pipeline process.
> Plug ESLint plug-in into unified pipelines.

- eng/pipelines/notifications.yml
to avoid service unavailable errors
> set notification subscribing parallelism to 2

- eng/CHECKENFORCER
Removing the flag because I'm going to implement default processing as per discussion on PRs.
> Remove enabled flag to test default processing.

- README.md
- tools/check-enforcer/README.md
- tools/check-enforcer/ci.yml
This PR adds a README for Check Enforcer. Hopefully I'm striking the right tone and level of detail for external consumers of the tool. I've also slipped in a ci.yml file with this PR as I'll be starting to setup the end-to-end CI/CD pipeline for this code and I need something to build from.
> Added a README file for Check Enforcer.

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
fixes #219
display 
```
@interface 
```
and support all fields in the side of custom annotation to be public
> Add '''@interface''' support

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Respositories/ReviewManager.cs
- src/java/apiview-java-processor/pom.xml
The site has a feature where if you rev your generator version it can show you the prompt and allow you to re-generate to model. I use jar name as a generator version for Java so incrementing it as part of this PR.
> Rev java processor version and fix updater feature

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
reintroduce custom annotation feature support
> Custom annotation and its members

- src/dotnet/APIView/APIView/APIView.csproj
- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Controllers/CommentsController.cs
- src/dotnet/APIView/APIViewWeb/Models/CommentModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
- src/dotnet/APIView/APIViewWeb/Repositories/CommentsManager.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
- src/dotnet/APIView/APIViewWeb/wwwroot/css/site.css
- src/dotnet/APIView/APIViewWeb/wwwroot/js/comments.ts
> Add support for editing comments

- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
- src/dotnet/APIView/APIViewTest/ExactFormatting/Attributes.cs
> Hide the IteratorStateMachineAttribute attribute

- src/dotnet/APIView/APIView/Analysis/Analyzer.cs
- src/dotnet/APIView/APIView/CodeFileHtmlRenderer.cs
- src/dotnet/APIView/APIView/CodeFileRenderer.cs
- src/dotnet/APIView/APIView/CodeFileTokensBuilder.cs
- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
- src/dotnet/APIView/APIView/Languages/CodeFileBuilderSymbolSorter.cs
- src/dotnet/APIView/APIView/Languages/CompilationFactory.cs
- src/dotnet/APIView/APIView/Languages/ICodeFileBuilderSymbolSorter.cs
- src/dotnet/APIView/APIView/Model/CodeFile.cs
- src/dotnet/APIView/APIView/Model/CodeFileToken.cs
- src/dotnet/APIView/APIView/Model/NavigationItem.cs
- src/dotnet/APIView/APIView/StringListApiView.cs
- src/dotnet/APIView/APIView/SymbolDisplay/AbstractSymbolDisplayVisitor.cs
- src/dotnet/APIView/APIView/SymbolDisplay/EnumField.cs
- src/dotnet/APIView/APIView/SymbolDisplay/EnumUtilties.cs
- src/dotnet/APIView/APIViewTest/CodeFileBuilderTests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/DiagnosticProject.cs
Also changes one place to use the switch expression.
/cc @pakrym
> Format the document and removing usings.

- eng/pipelines/templates/scripts/replace-relative-links.yml
- scripts/python/util/replace_relative_links.py
* title
* a bugfix on the link check
> Handling Predefined Resource Definitions

- eng/pipelines/templates/scripts/replace-relative-links.yml
Second commit to my previous PR was never pushed. Need to include this change for the downstream jobs.
CC: @Azure/azure-sdk-eng
> Updating yml to reflect script

- packages/python-packages/doc-warden/warden/PackageInfo.py
- packages/python-packages/doc-warden/warden/WardenConfiguration.py
- packages/python-packages/doc-warden/warden/warden_common.py
- Add nuget package badge.
- Updated project exclude regex
cc @scbedd
https://github.com/Azure/azure-sdk-for-net/pull/8494 has the regenerated packages.md file based on these changes.
> Update warden package indexing scripts

- scripts/python/readme_tracking/update_readmes_for_tracking.py
- Fix image regex for rst files
- Generate abspath for target directory to enable passing "." as the path.
cc @scbedd
> Fix a couple issues in readme update script.

- tools/daily-dev-build-variable/daily-dev-build-variable.yml
Adding in a snippet that we can use across all pipelines. This PR is required to be merged before this PR:
https://github.com/Azure/azure-sdk-for-java/pull/6587
> Reusable script fragment for dev package builds

- packages/python-packages/tox-monorepo/README.md
I updated the code, but failed to update the readme with the real attributes being updated.
> Properly Update Tox Monorepo Readme

- scripts/python/util/reupload_python_packages.py
@Azure/azure-sdk-eng 
This allows me a one-liner to publish python docs that correctly have examples present.
> Script to blob upload SDIST as TarGZ

- eng/pipelines/templates/scripts/verify-path-length.yml
Check path length form repo root directory, so that there is no need to set an artificial checkout path.
> Update Path Length Verifier

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0003Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
Fixes https://github.com/Azure/azure-sdk-tools/issues/291
> Do not produce AZC0003 for override methods

- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/warden/version.py
- packages/python-packages/doc-warden/warden/warden_common.py
Update Logic for Java Package discovery
> Update Java Package Discovery

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Controllers/CommentsController.cs
- src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CommentsManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/NotificationManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
- src/dotnet/APIView/APIViewWeb/appsettings.Development.json
- src/dotnet/APIView/APIViewWeb/appsettings.json
Auto-subscribe users when they comment or upload a revision.
Subscribe/unsubscribe button.
Sends messages using SendGrid account to subscribers on any comments or new revisions.
Examples:
> Add notifications

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/AddConfigureAwaitAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/AsyncAnalyzerUtilities.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
Also add syntax tree checks before retrieving semantic model
> Revert previous changes

- src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
- src/dotnet/APIView/APIViewWeb/Startup.cs
It pointed to unexisting page.
> Fix AccessDeniedPath redirect

- src/dotnet/APIView/APIViewWeb/Account/ConfigureOrganizationPolicy.cs
- src/dotnet/APIView/APIViewWeb/Controllers/AccountController.cs
- src/dotnet/APIView/APIViewWeb/Pages/Login.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Login.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Unauthorized.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Unauthorized.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
Now we have 2 pages:
1. Login page you see when you are not logged in
2. Unauthorized page when you're not a member of an org
> Fix Unauthorised redirect

- .azure-pipelines/warden.yml
docsettings.yml is moved to eng folder. Updated yml path to refer new path.
> Updated doc settings yml location for python and js

- eng/common/README.md
- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
> Setup pipeline to sync common engineering directory

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/src/comments.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
> Add/edit comment on Ctrl+Enter

- eng/common/Update-Change-Log.ps1
- eng/common/Version-Parser.psm1
Fixed all review comments and updated script as per discussion.
> New Script to add/update version in change log

- scripts/python/util/reupload_python_packages.py
Related to [#9464](https://github.com/Azure/azure-sdk-for-python/issues/9464)
> Remove comments from __init__.py during repacking

- scripts/python/util/reupload_python_packages.py
> Re-upload script - replace Pkgutil

- eng/pipelines/templates/steps/sync-directory.yml
> Add new PRTitle template parameter

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
> Wrap code lines

- eng/common/Update-Change-Log.ps1
Update change log should not blindly replace the version title when version is present or version already has a date in it to avoid issue for java repo since it calls this script for all libraries with current version in it pom file passed as new version.
> Fixes required to support update change log for azure-sdk-for-java

- scripts/powershell/create-tags-and-git-release.ps1
Move script to public repo as part of [Issue 365](https://github.com/Azure/azure-sdk-tools/issues/365).
Changes to release stages in `azure-sdk-build-tools` to properly hook up to this will follow shortly.
> Add create-tags-and-git-release script

- packages/python-packages/doc-warden/warden/warden_common.py
Wanted to make forward progress on something solid. This will allow us to omit specific folders (versus everything _beneath_ that folder)
Oh. And a run of `black` over the updated file as well.
> Allow Omission of Individual Folders

- eng/common/Extract-ReleaseNotes.ps1
Update ExtractReleaseNotes Script so that it propagated to all repos
> Update Extract Release Notes Logic

- eng/common/Extract-ReleaseNotes.ps1
> Update Extract Release Notes Script

- eng/pipelines/templates/scripts/replace-relative-links.yml
- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/warden/enforce_changelog_content.py
- packages/python-packages/doc-warden/warden/enforce_readme_content.py
- packages/python-packages/doc-warden/warden/enforce_target_file_presence.py
- packages/python-packages/doc-warden/warden/index_packages.py
- packages/python-packages/doc-warden/warden/version.py
- packages/python-packages/doc-warden/warden/warden_common.py
Update imports in doc-warden to refer pathlib2 and remove unused pathlib imports
> Update reference to pathlib2 namespace

- tools/CreateRuleFabricBot/CreateRuleFabricBot.sln
- tools/CreateRuleFabricBot/CreateRuleFabricBot/CommandLine/ActionToTake.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/CommandLine/Options.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/CreateRuleFabricBot.csproj
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Markdown/MarkdownTable.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Program.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/IssueRouting/IssueRoutingCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/IssueRouting/TriageConfig.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Service/RequestSender.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBotTests/CreateRuleFabricBotTests.csproj
- tools/CreateRuleFabricBot/CreateRuleFabricBotTests/LiveTests.cs
- tools/CreateRuleFabricBot/README.md
- tools/CreateRuleFabricBot/ci.yml
/cc @weshaggard @lilyjma @maggiepint
> Add fabric bot config tool

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0002Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0006Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0010Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAnalyzerBase.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientConstructorAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientOptionsAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Descriptors.cs
Fixes https://github.com/Azure/azure-sdk-tools/issues/413
Fixes https://github.com/Azure/azure-sdk-tools/issues/396
Fixes https://github.com/Azure/azure-sdk-tools/issues/372
> Various analyzer fixes

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
Remove default constructor in interface
Upgrade Processor version to 1.2.0
> No default constructor for interfaces and upgrade processor version to 1.2.0

- eng/common/TestResources/deploy-test-resources.yml
Propagate this fix to other repositories when they start using the common resource provisioner
> apply -AllowClobber fix

- scripts/python/util/reupload_python_packages.py
> We shouldn't add whitespace to __init__

- tools/CreateRuleFabricBot/CreateRuleFabricBot/CreateRuleFabricBot.csproj
> Include other NoWarn messages in the list

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/Remove-TestResources.ps1.md
- eng/common/TestResources/deploy-test-resources.yml
- eng/common/TestResources/remove-test-resources.yml
Update test resources scripts to provision resources in different environments. These changes should propagate to other repos so multiple environment support can be easily into smoke tests.
> Dynamic Resource Provisioning in Multiple Environments

- scripts/python/util/reupload_python_packages.py
> Re-upload script is introducing newlines where it shouldn't be.

- eng/common/scripts/Submit-PullRequest.ps1
Updated the script to use the rest api for querying the pull requests
instead of using the graphql api. The rest api is more resilient with
branch aliases, such as master == refs/heads/master.
cc @chidozieononiwu @JimSuplizio
> Update Submit-PullRequest script

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
There are some cases where we need to override the path
to the scripts so added a parameter to allow for that.
> Add ScriptDirectory parameters to template

- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
Depends on https://github.com/Azure/azure-sdk-tools/pull/464
cc @chidozieononiwu
> Update sync pipeline to use public pull request scripts

- eng/common/scripts/copy-docs-to-blobstorage.ps1
Upload a copy of the docs to a latest folder if the version that's being uploaded is the latest one.
> Upload Latest Copy of Docs.

- eng/common/scripts/SemVer.ps1
Adapt logic from the following usages of SemVer and create a common class that can be then used by them.
- https://github.com/Azure/azure-sdk/blob/master/eng/scripts/Update-Release-Versions.ps1#L26-L58
- https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Update-PkgVersion.ps1#L48
- https://github.com/Azure/azure-sdk-for-cpp/blob/master/eng/Update-PkgVersion.ps1#L48
Part of #469
> Standardize PowerShell SemVer Parsing Logic

- packages/python-packages/doc-warden/changelog.md
- packages/python-packages/doc-warden/warden/index_packages.py
- packages/python-packages/doc-warden/warden/version.py
If a setup.py doesn't run appropriately, kick it out.
> Handle crashing py setup gracefully

- eng/common/scripts/Submit-PullRequest.ps1
- eng/common/scripts/copy-docs-to-blobstorage.ps1
- eng/common/scripts/create-tags-and-git-release.ps1
- eng/common/scripts/git-branch-push.ps1
For debugging/replicating command locally we have
added an echo of the script invocation at the top of
of our ps scripts
cc @Azure/azure-sdk-eng
> Echo powershell script invocation

- packages/python-packages/api-stub-generator/tests/docstring_parser_test.py
- packages/python-packages/api-stub-generator/tox.ini
Unit test cases for docstring parser and tox ini to trigger pytest
> Apireviewtool tests

- eng/pipelines/templates/stages/archetype-sdk-tool-azure-function.yml
This PR adds a pipeline template that can deploy an Azure Function. It has a few conventions baked into it and it basically extracts the template that I've created in this PR: #487 
I'll be using this template with Check Enforcer to get some rigor into its deployment process, and I can use it with any other automation that we choose to develop.
> Azure Function pipeline template

- tools/agent-time-extractor/AgentTimeExtractor.sln
- tools/agent-time-extractor/AgentTimeExtractor/AgentTimeExtractor.csproj
- tools/agent-time-extractor/AgentTimeExtractor/Program.cs
This PR contains a little utility that I've been using to extract agent times.
> Agent time extractor tool

- src/dotnet/APIView/APIView/Analysis/Analyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0011Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0012Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/TypeNameAnalyzer.cs
Also enable new analyzers in APIView.
> Ignore nested classes in single word type name check

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/EmailSender.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInBacklogMilestones.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindIssuesInPastDueMilestones.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindNewGitHubIssuesAndPRs.cs
- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindStalePRs.cs
> Improve logging and fix bug

- packages/python-packages/api-stub-generator/apistub/_diagnostic.py
Add Diagnostic class to track list of lint errors.
> Add diagnostic tracking class

- eng/common/TestResources/New-TestResources.ps1
Fixes https://github.com/Azure/azure-sdk-tools/issues/505
> Make common test resource variables always available

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
- Bucket based on id across all 24 hours
- Only add a schedule if one doesn't exist
- Don't update existing schedules because the might be modified
from other sources (manually or with a schedule balancing tool)
> Update pipeline generation scheduling

- eng/pipelines/pipeline-generation.yml
- Update version to latest pipeline generation tool
- Remove 2 hour cron schedule and use only daily schedule in web ui
- Update to use a pat for the service account pulled from keyvault
> Update pipeline generation tool

- .azure-pipelines/apiview.yml
- packages/python-packages/api-stub-generator/tox.ini
- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
Changes:
- Add python package into API view package so it will get deployed into Azure app
- Build and test python parser whenever change API view or python parser is changed
> Add Python package parser in API view build and packaging 

- eng/common/scripts/copy-readmes-to-docs.ps1
Adds script for copying library readme files to docs with added version identifiers in the title.
> add readme copy to docs script

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/IssueCommentHandler.cs
- tools/check-enforcer/README.md
This PR adds the ```/check-enforcer override``` command as well as updates the docs.
> Check Enforcer override command

- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
1. Add new lint rule to check list API returns Paged type
2. Remove false negative lint errors
3. Remove typehint check for async methods.
> Incorrect lint error

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/IntegrationTestingPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/UnifiedPipelineConvention.cs
Fixes https://github.com/Azure/azure-sdk-tools/issues/559. 
PTAL @mitchdenny
> Disable all CI triggers for generated pipelines

- .azure-pipelines/apiview.yml
- packages/python-packages/api-stub-generator/apistub/__init__.py
- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/apistubgen.py
- packages/python-packages/api-stub-generator/apistubgen.py
- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/LanguageProcessor.cs
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
- Changes to bundle python parser source in API view deployment artifact.
- Hide error report printing when running from API view
- Generate out file using given name if json file name is passed in arg to parser.
> Bundle Python parser in APIView web deployment package

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
This PR adds logic to loop over Check Enforcer check runs and mark them successful if the ```/check-enforcer override``` command is used. This is a bit of an experiment to see whether it can unstick stuck PRs that are in the pad state. If this works then this change will be integrated into the standard evaluation phase so that Check Enforcer automatically compensates for these issues.
I'm going to merge this is immediately since it isn't on the critical path for all Check Enforcer runs and then if it works submit a PR for review with broader changes. If it fails I'll rollback.
> Allow /check-enforcer override to handle duplicates.

- src/dotnet/APIView/APIViewWeb/Languages/CLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
> Fix C parameter names and Python service to not require an environment variable

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
This PR adds the minor tweaks necessary to allow the reset command to cope with SHAs that have duplicate check runs associated with them due to what I think is a race condition on the GitHub side. Compared to abuse and rate limiting exceptions this exception time is exceedingly rare, but its one of the few unrecoverable errors that we have left, you can see of all the InvalidOperationExceptions that are being thrown that this one is the most common (purple/pink line):
> Handle duplicate checks during reset command

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
> Correct boolean operator in CreateCheckAsync

- eng/pipelines/templates/scripts/verify-agent-os.yml
Revert [PR 411](https://github.com/Azure/azure-sdk-tools/commit/d8a47ba66dd03ff56a04a4ff8b75c7addc3edf7d#diff-490e5e24032629634b843a150e0857a0)
> OSName variable set at run time

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAnalyzerBase.cs
> Fix type compare issue with generic method args

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Constants.cs
/cc @mitchdenny @lilyjma @jsquire
> Update the label we use for issues that need the team's attention.

- eng/common/scripts/artifact-metadata-parsing.ps1
- eng/common/scripts/copy-docs-to-blobstorage.ps1
Changes needed to release C SDK as a single release, instead of per package
Co-authored-by: djurek@microsoft.com <djurek@microsoft.com>
> Changes needed to release C SDK as a single release

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAnalyzerBase.cs
> Handle nested generic type parameters

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
> add annotatin declaration support

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindNewGitHubIssuesAndPRs.cs
Fix #667 
/cc @mitchdenny @ramya-rao-a
> Change order in which the tables show up in the report.

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/package.json
- src/dotnet/APIView/APIViewWeb/Client/src/main.ts
- src/dotnet/APIView/APIViewWeb/Client/src/navbar.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
> Add resizable splitter between type and code panes

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
@praveenkuttappan can you provide python help message?
> Add help to Create review dialog

- eng/common/pipelines/templates/steps/mashup-doc-index.yml
- eng/common/pipelines/templates/steps/replace-relative-links.yml
- eng/common/pipelines/templates/steps/verify-path-length.yml
Move Scripts to Eng/Common Directory
> Refactor script location

- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
This PR closes #614. Sprinkles a lot more logging through the router so that if something goes wrong we get better insights into where it went wrong beyond just the exception.
> Improve Webhook Router logging.

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/CheckRunHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
This PR adds an Evaluate action button to Check Enforcer. At this point it adds the button but doesn't do anything. This is just to get some telemetry that shows how the payload changes when the action is received so that I can add it to Octokit and add appropriate tests.
> Add Evaluate action to Check Enforcer check-run.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/RunProcessor.cs
This PR adds a bunch of caching around the creation of Cosmos clients, and Azure DevOps clients used to make outbound HTTP requests. Current implementation was basically throwing away these objects on each call which means that we reach a threshold with Azure Functions fairly quickly where it wants to tear down the function instance to avoid reading max TCP connection limits.
This should help mitigate this. There is still an issue with cache stampeeding which I'm not happy about but before I try to come up with an elaborate solution for that with locking etc I want to make sure I am using caching correctly. But this change should fix these Azure Functions burps as they exist today.
Note ... I am deliberately not disposing of the VssConnection and various VssHttpClientBase objects when …
> Improve caching of clients to reduce Azure Functions burps.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/PythonPipelineTestFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This PR adds a classifier to detect Python test failures and report them.
> Adds python test run failure classifier.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/JavaScriptLiveTestFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This pipeline adds a classifier for failure in JS live tests.
> Add detection for live test failures in JS pipelines.

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/DotnetPipelineTestFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This PR adds a failure classifier for .NET test runs.
> Add failure classifier for .NET tests.

- eng/pipelines/mirror-repos.yml
- eng/pipelines/templates/steps/sync-repo-branch.yml
PTAL @NullMDR 
I know I didn't port all the mirroring but I believe I ported all that is probably needed but please let me know if I missed something that you guys need.
> Enable repo mirroring

- eng/pipelines/templates/steps/ref-updater.yml
- eng/pipelines/tools-repo-versioning.yml
- scripts/powershell/ref-updater.ps1
Automation for updating Repository resource refs across the language repos.
Pipeline [Ref-Updater]( https://dev.azure.com/azure-sdk/internal/_build?definitionId=1741&_a=summary) runs on build completion of [tools - repo-versioning](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1696&_a=summary) and [azure-sdk-build-tools - repo-versioning](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1698&_a=summary)
Sample PR generated https://github.com/Azure/azure-sdk-for-net/pull/12403/files
> Begin Implementing Ref Updater

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs
Addressing [this comment](https://github.com/Azure/azure-sdk-pr/pull/157/files#r443843150) to enable getting started turorial.
> Add Azure.Learn to allowed namespaces

- eng/pipelines/mirror-repos.yml
release/v3 branch is for python sdk track1
> Add python sdk release/v3 branch sync

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/java/apiview-java-processor/pom.xml
upgrade version for the fix in
Java api processor illegal package fix (#731)
> Upgrade version to 1.8.0 after merged PR Java api processor illegal package fix (#731)

- eng/common/scripts/artifact-metadata-parsing.ps1
> Update PackageId for C release

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/GitCheckoutFailureClassifier.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
This PR adds a classifier for Git throwing error code 128 when GitHub is rate limiting us.
> Add git checkout failure classifier.

- eng/common/pipelines/templates/steps/verify-changelog.yml
- eng/common/scripts/Verify-ChangeLog.ps1
- eng/common/scripts/modules/ChangeLog-Operations.psm1
Updated to ChangeLog Logic after testing on the language repo.
> Updates to changelog logic

- eng/common/pipelines/templates/steps/verify-changelog.yml
Add the package name to the display name to make it more descriptive.
> Make displayName more Descriptive.

- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
Had some trouble doing end-to-end tracing for Check Enforcer. This PR allows us to do some end-to-end tracing.
> Log webhook payloads

- eng/pipelines/mirror-repos.yml
@weshaggard I've setup the ```-pr``` mirrors for Android and iOS, and from what I can tell this is the necessary configuration to start replicating the master branch. Can you confirm?
/cc @mayurid @bsiegel
> Setup mirroring for Android and iOS mirrors.

- eng/common/scripts/modules/ChangeLog-Operations.psm1
Verify release date in changelog against date build was queued rather than current date at time of approval.
> Update Verify Changelog Logic

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
Show helper text for python in Create new review window.
> Add create review help link for python

- eng/common/scripts/Verify-ChangeLog.ps1
- eng/common/scripts/modules/Package-Properties.psm1
Fix bug introduce since switching to extends template in ci.yml files.
> Fix bug in Pkg props module

- eng/common/scripts/Verify-ChangeLog.ps1
- eng/common/scripts/modules/Package-Properties.psm1
Fix bug introduced in https://github.com/Azure/azure-sdk-tools/pull/762/files
> Fix SilentlyContinue Bug

- eng/common/Update-Change-Log.ps1
This fixes an issue which allows entries to be added
to empty changelog files.
> Fix issue in for empty change log files

- tools/notification-configuration/ci.yml
- tools/notification-configuration/common/Helpers/GitHubNameResolver.cs
- tools/notification-configuration/common/Models/IdentityDetail.cs
- tools/notification-configuration/common/common.csproj
- tools/notification-configuration/identity-resolver/Program.cs
- tools/notification-configuration/identity-resolver/identity-resolver.csproj
- tools/notification-configuration/notification-configuration.sln
> Add Identity Resolver

- eng/common/scripts/Verify-ChangeLog.ps1
Update Logic for retrieving repo language in Verify Changelog Script
> Update logic for retrieving repo language

- eng/common/TestResources/deploy-test-resources.yml
Quick fix to a typo in a comment.
> Quick fix to typo in test provisioner.

- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/src/main.ts
- src/dotnet/APIView/APIViewWeb/Client/src/revisions.ts
- src/dotnet/APIView/APIViewWeb/Models/ReviewCodeFileModel.cs
- src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
- src/dotnet/APIView/APIViewWeb/Models/ReviewRevisionModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Delete.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/NotificationManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
**Creating a revision:**
**Add/edit labels of existing revisions (only available for revision/review owner):**
**Creating a review:**
Fixes https://github.com/Azure/azure-sdk-tools/issues/367, https://github.com/Azure/azure-sdk-tools/issues/782, and https://github.com/Azure/azure-sdk-tools/issues/476
> Add assembly version and label

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs
> Ensure that the milestone is not null before using.

- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
- src/dotnet/APIView/APIViewTest/ExactFormatting/Attributes.cs
Fixes: https://github.com/Azure/azure-sdk-tools/issues/366
> Include EditorBrowsable in API Listing

- eng/common/pipelines/templates/steps/create-pull-request.yml
> Don't Add a PR Reviewer if there are no changes

- .github/CODEOWNERS
Reverts Azure/azure-sdk-tools#803
> Revert "Update codeowners file."

- src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
This will allow for renaming a review by renaming the Rev 0.
> Tie Review label to first revision label

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/common.ps1
Add `ChangeLog-Operations.ps1` and `Package-Properties.ps1` to common/script directory.
Add `ICommon.ps1` for importing common Language Settings.
> Add foundations for restructuring Eng Common Tools

- eng/common/TestResources/New-TestResources.ps1
The focus of these changes is to include additional environment variables in the `TestEnvironment` to allow for cross-cloud management plane operations,
such as those used by the Azure Messaging client libraries.  This is the first step in enabling cross-cloud support for Live testing in the Event Hubs and Service Bus client libraries, both T1 and T2.
The test resource creation script has been updated to populate these additional variables using the current Azure environment context.   Orthogonal, but included are some tweaks to allow local runs of the `TestResources.ps1` script using the `-WhatIf` flag, which was failing for me before changes were made.
Tuesday, July 28, 9:13am (EDT)
- [New-TestResources.ps1 should set AZURE_AUTHORITY_HOST environment …
> [Test Resources] Add Environment Variables

- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/CodeOwnerEntry.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/PullRequestLabelFolderCapability.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBotTests/CodeOwnerTests.cs
- tools/CreateRuleFabricBot/CreateRuleFabricBotTests/TestAndExpected.cs
We will specify the labels on the line directly above the line that contains the Owners.
> Change the format for how the PRLabels are specified.

- eng/common/TestResources/New-TestResources.ps1
The focus of these changes is to expose the Storage Endpoint Suffix for the active Azure environment to both the test resources template and to the execution environment for tests.  This value differs between cloud environments and there is no convenient way to query it from the data plane.
This is needed to allow for building a full connection string for a storage account within the resource template or dynamically within the scope of a test execution.
Wednesday, July 28, 3:48pm (EDT)
- [New-TestResources.ps1 should set AZURE_AUTHORITY_HOST environment variable](https://github.com/Azure/azure-sdk-tools/issues/757) (#757)
- [Event Hubs: AAD Auth failure when testing against other clouds](https://github.com/Azure/azure-sdk-for-net/issues/12964) (#12964)
- [Event Hub Live Test …
> [Test Resources] Extend with Storage Endpoint

- eng/common/scripts/artifact-metadata-parsing.ps1
- eng/common/scripts/update-docs-metadata.ps1
Will link commits of the test branch I'm using for releases + successful release when I have them.
> Update Invoke-WebRequest-WithHandling to more appropriate Invoke-RestMethod-WithHandling

- .azure-pipelines/apiview.yml
- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- src/dotnet/APIView/APIViewWeb/Client/package.json
New arg option to generate API stub only for a specific name space and it's sub modules.
> option to filter to specific namespace

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/src/comments.ts
- src/dotnet/APIView/APIViewWeb/Client/src/navbar.ts
> Add glow to selected code line

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/FindNewGitHubIssuesAndPRs.cs
Ensure that we sort the issues by the state before adding them to the report.
/cc @lmazuel @mitchdenny
> Add a column for the state of the issue (some could be closed)

- eng/pipelines/mirror-repos.yml
This PR fixes up the ```-pr``` repo sync now that the dev branch has been renamed to master.
> Fix android-pr repo sync.

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml
> Cleanup styles on conversation page

- src/dotnet/APIView/APIView/Analysis/Analyzer.cs
- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
- src/dotnet/APIView/APIViewTest/ExactFormatting/Attributes.cs
Fixes: https://github.com/Azure/azure-sdk-tools/issues/798
> Enable additional analyzer and fix a bug with attribute array parameters

- src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
Enable uploading python whl into API view tool instead of json file.
> Enable parsing python API using script

- eng/common/scripts/update-docs-ci.ps1
Synced from [this PR](https://github.com/Azure/azure-sdk-for-python/pull/12987/files).
> Python Release Hotfix

- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
Run apistubgen process to parse python wheel.
> Run apistubgen and support wheel

- tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Azure.Sdk.Tools.GitHubIssues.csproj
This PR updates the dependencies for GitHub Issues. Not expecting any issues but I will deploy it into staging to let it run for a few days.
> Update dependencies for GitHub Isssues.

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
This PR updates the dependencies for Check Enforcer. My primary goal was to eliminate dependency errors from Azure Identity but it was time to do a refresh across all our dependencies. Doing this as a feature branch so we can test in staging to make sure there are no issues on a live function host.
> Update Check Enforcer dependencies.

- eng/common/README.md
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/README.md
- eng/common/TestResources/Remove-TestResources.ps1.md
- eng/common/TestResources/deploy-test-resources.yml
- eng/common/TestResources/remove-test-resources.yml
- eng/common/pipelines/templates/steps/replace-relative-links.yml
- eng/common/pipelines/templates/steps/verify-agent-os.yml
Moving changes from https://github.com/Azure/azure-sdk-for-c/pull/1045/files into tools repo
cc @ahsonkhan
> Update typos in MD files

- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
Passing base branch during eng/common syncing.
> Pass base branch during eng syncing

- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
Adjust Eng Common Sync PR Title
> Adjust PR Title

- scripts/powershell/Fix-YamlHeaders.ps1
- src/dotnet/Mgmt.CI.BuildTools/ci.yml
- tools/CreateRuleFabricBot/ci.yml
- tools/check-enforcer/ci.yml
- tools/github-issues/ci.yml
- tools/notification-configuration/ci.yml
- tools/pipeline-generator/ci.yml
- tools/pipeline-witness/ci.yml
- tools/version-guard/ci.yml
- tools/webhook-router/ci.yml
This PR updates the ci.yml files for a given path to remove the # statements in the header and replace them with an alternative placeholder. Related to this issue: https://github.com/Azure/azure-sdk-for-js/issues/10434
> Tool to update ci.yml headers.

- eng/common/scripts/Verify-Resource-Ref.ps1
Update Code for verifying resource refs
> Update Verify Resource Ref

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/Remove-TestResources.ps1.md
- eng/common/TestResources/remove-test-resources.yml
Changes from https://github.com/Azure/azure-sdk-for-js/pull/8388
> Add TestResources changes from JS smoke test re-architecture

- eng/pipelines/tools-repo-versioning.yml
Update refs to azure-sdk-tools repository resource present in the azure-sdk-for-python repo.
> Include python in ref-updater.yml

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/scripts/Submit-PullRequest.ps1
- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
- scripts/powershell/Verify-And-Merge-PRs.ps1
Implement automatic merging of Sync and Tools Pull requests.
> Extend Eng common sync

- eng/pipelines/tools-repo-versioning.yml
Add azure-sdk to the list of repo's to update.
@chidozieononiwu I assume this will work on any repo correct?
Based on https://github.com/Azure/autorest.csharp/pull/880 we might also want to add "autorest.csharp" to the list.
> Add azure-sdk

- eng/common/README.md
Update and Move `eng/common` workflow to internal Wiki
> Update and Move eng/common

- scripts/python/apiview-syncdb/requirements.txt
- scripts/python/apiview-syncdb/sync_cosmosdb.py
Script to sync all DB containers in cosmos DB. This script will be used by a scheduled pipeline(yet to add) to sync Cosmos DB from API View production instance to API view staging instance.
> Script to to sync Azure cosmosDB from source to destination DB instance

- eng/common/Update-Change-Log.ps1
Part of https://github.com/Azure/azure-sdk-for-c/issues/1201
Discovered as part of https://github.com/Azure/azure-sdk-for-c/pull/1199
cc @danieljurek, @weshaggard
> Make sure to save the eng/common files without a UTF-8 BOM.

- eng/common/Update-Change-Log.ps1
To be used in the Prepare-Release script.
> Allow updating the release date

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/GitHubWebhookProcessor.cs
We had an incident today (and Friday, and earlier in August) where Check Enforcer has a spew of errors. After some investigation I noticed that our telemetry was reporting two different kinds of exceptions that I had incorrectly lumped together, they are AbuseException and RateLimitExceededException. I believe that the AbuseException is intended for relatively small back-offs, but the rate limit exceeded exception is a much harder exception where we just need to sit out much longer.
This PR adds handling for both exception types in the existing back-off logic.
> Improve rate limit handling.

- .azure-pipelines/apiview-sync-staging.yml
- scripts/python/apiview-syncdb/requirements.txt
- scripts/python/apiview-syncdb/sync_cosmosdb.py
Additional step to trigger sync db script
> Add steps to sync cosmos db

- src/dotnet/APIView/APIView/Model/CodeDiagnostic.cs
- src/dotnet/APIView/APIView/Model/CodeDiagnosticLevel.cs
- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
Added  levels for diagnostic messages and new style for info, warning and Error
> Support different levels of diagnostic messages in APIView

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Azure.Sdk.Tools.CheckEnforcer.csproj
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfigurationProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/IssueCommentHandler.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubClientProvider.cs
- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Integrations/GitHub/GitHubRateLimiter.cs
This PR sprinkles rate limiting calls around the codebase using the RateLimiter package.
> Add GitHub rate limiting to Check Enforcer.

- src/dotnet/APIView/APIView/CodeFileHtmlRenderer.cs
- src/dotnet/APIView/APIView/CodeFileTokensBuilder.cs
- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
- src/dotnet/APIView/APIView/Languages/CompilationFactory.cs
- src/dotnet/APIView/APIViewTest/CodeFileBuilderTests.cs
- src/dotnet/APIView/APIViewTest/DiagnosticProject.cs
- src/dotnet/APIView/APIViewWeb/Languages/CSharpLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
> Add nupkg and xml docs support

- .github/CODEOWNERS
Adding a few specific people to ```CODEOWNERS``` for our services.
> Updating code-owners for some of the services/tools.

- eng/common/scripts/copy-docs-to-blobstorage.ps1
Update dotnet docs logic in tools repo to prevent overwrite when sync happens.
> Update dotnet docs logic in tools repo

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0001Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientAssemblyNamespaceAnalyzer.cs
> Add Azure.Communication to the allowlist of namespaces

- eng/common/scripts/Submit-PullRequest.ps1
Tested in this PR: https://github.com/Azure/azure-sdk-for-c/pull/1376
The array gets printed in c Create Pull Request step: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=557006&view=logs&j=96791242-dbf3-587e-3a06-ae5af5c1a705&t=e77f5cb4-719b-54a0-4102-729e63acf003
Fixed issue: https://github.com/Azure/azure-sdk-tools/issues/1046
> Fixed the bug of removing existing labels when add pr labels

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/ASTUtils.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/MiscUtils.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ConsiderFinalClassDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MissingJavaDocDiagnosticRule.java
A bunch of small commits to improve various aspects of the APIView tooling for Java.
> [APIView] Improvements to Java APIView diagnostics and code listing generation

- eng/pipelines/create-tutorial-branch.yml
- scripts/powershell/Create-Branch.ps1
Using this PR to merge a new script and pipeline definition into the repo for testing. I'll be opening another PR for the merge onto master.
> Create tutorial branch script and pipeline.

- src/go/cmd/api_view.go
- src/go/cmd/api_view_test.go
- src/go/cmd/content.go
- src/go/cmd/models.go
- src/go/cmd/output/testconst.json
- src/go/cmd/output/testinterface.json
- src/go/cmd/output/teststruct.json
- src/go/cmd/testdata/test_interface/test.go
- src/go/cmd/token_builders.go
This PR added embedded interfaces to tokenized output for API view tool. Also fixes bug in generating output file name in local directory
> Add embedded interfaces to API view output 

- eng/common/scripts/New-ReleaseAsset.ps1
- src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
- src/dotnet/APIView/APIViewWeb/Startup.cs
> C++ support in APIView

- eng/common/scripts/ChangeLog-Operations.ps1
Add function for overwriting package changelog.md file
> Function to overwrite changelog for template/test pipelines

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/library-scripts/docker-debian.sh
- .devcontainer/library-scripts/git-lfs-debian.sh
This PR adds Codespaces confguration so that folks on the EngSys team can use it whilst hacking in the azure-sdk-tools repo.
> Add GitHub Codespaces configuration.

- eng/pipelines/eng-common-sync.yml
Fix Basebranch parameter to allow manual run of sync pipeline.
> Fix sync Basebranch

- eng/pipelines/templates/steps/sync-directory.yml
> Fix bug in sync-directory.yml

- eng/common/scripts/modules/ChangeLog-Operations.psm1
- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
Restructure `eng/common` sync to allow pull request build as well manual queuing.
> Restructure eng/common sync control flow

- eng/common/pipelines/templates/steps/prepare-pipelines.yml
Need to fix this cut-paste error in prepare pipeline where I was always creating the -pr pipelines, even on the public repo. Need to fix this to avoid 2x'ing the number of pipelines against the repo.
> Fix condition in prepare pipeline.

- eng/pipelines/setup-tutorial-branch.yml
Urgent fix to the setup pipelines to work around JS branches not being setup correctly..
> Work around issue in the JS repo.

- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/Remove-TestResources.ps1.md
- eng/common/scripts/Verify-Links.ps1
Fixed issue: https://github.com/Azure/azure-sdk-tools/issues/1020
> Add check of http link.

- eng/CHECKENFORCER
This PR adds a timeout message to the ```eng/CHECKENFORCER``` configuration file. It is implemented as a multi-line YAML comment. I am merging this in immediately so that I can validate some changes to Check Enforcer that is running in staging. Once that is validated I'll create PRs for the other repositories.
> Updated Check Enforcer with timeout message.

- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
- eng/pipelines/pipeline-generation.yml
Link to template yaml is incorrect
> Fix broken link in automated pipeline generation tool

- eng/CHECKENFORCER
Adjust the timeout message for Check Enforcer.
> Adjust timeout message.

- eng/common/pipelines/templates/steps/verify-path-length.yml
Fix `verify-path-length.yml` to report all paths longer than the allowed limit
> Fix bug in verify-path-length.yml

- eng/pipelines/live-test-cleanup.yml
- tools/live-test-cleanup/cleanup.ps1
- switch to using the subscription configurations
- add preview to list of subs to clean-up
> Update test resource clean-up scripts

- eng/common/README.md
Fix broken eng/common doc link.
> Fix broken eng/common doc link

- eng/common/scripts/Get-PullRequestCreator.ps1
- eng/common/scripts/Invoke-DevOpsAPI.ps1
- eng/common/scripts/Invoke-GitHubAPI.ps1
- eng/common/scripts/Queue-Pipeline.ps1
- eng/common/scripts/Submit-PullRequest.ps1
- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
- Add Invoke-DevOpsAPI.ps1
- Add functions for Canceling and Listing Builds
> Add Invoke-DevOpsAPI.ps1, Add functions for Canceling and Listing Builds

- tools/CreateRuleFabricBot/CreateRuleFabricBot/Service/RequestSender.cs
The domain for FabricBot has changed, this updates the URLs and cookie settings accordingly.
> Change domain for FabricBot

- eng/common/scripts/update-docs-metadata.ps1
Bugs reported by PR: https://github.com/Azure/azure-docs-sdk-java/pull/1516#discussion_r529064153
> Fixed the bug of the wrong parameter

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- src/dotnet/APIView/APIViewWeb/Filters/ApiKeyAuthorizeAsyncFilter.cs
- src/dotnet/APIView/APIViewWeb/Models/UploadModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Authenticate bot user using API Key to upload and check status of API review.
> Added support for bot user in API View

- scripts/python/docs-automation/sync_tocs.py
Need to actually assign the variable! python replace doesn't update in place
> Bugfix in Moniker HREF Update

- eng/pipelines/pipeline-generation.yml
Add new variable group to pipelines
> Adde new variable group to all pipelines

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Show Automatic reviews only if option is selected.
> Hide automatic reviews by default and show them only if selected

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
Fix build break due to incorrect nullable reference for string
> Fix build break due to nullable string ref

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
Show approval status in reviews page
> show review status in reviews page

- eng/common/pipelines/templates/steps/prepare-pipelines.yml
The condition was incorrectly referencing a variable where it should be referencing the parameter.
> Fix condition for test generation in prepare-pipelines

- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Update pipeline generation tool version to support the changes in PR https://github.com/Azure/azure-sdk-tools/pull/1311
> Update pipeline generation tool to support test variant pipelines

- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
This PR changes over to using a _tools_ environment as the approval gate for command-line tooling releases for the EngSys team. Also disabling CG in the release stage by importing globals.
> Use tools environment and disable CG.

- src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
Generate review display name using latest revision instead of first revision
> Show label from last revision

- eng/common/docgeneration/Generate-DocIndex.ps1
- eng/common/scripts/Create-APIReview.ps1
- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/artifact-metadata-parsing.ps1
- eng/common/scripts/copy-docs-to-blobstorage.ps1
- eng/common/scripts/update-docs-ci.ps1
Add more information to error messages in the tools repo.
> Update error message in tools repo

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
This PR resolves a `NullPointerException` when a POM file doesn't contain either a `groupId` or `version` XML node when it has a parent POM. Maven allows children POMs to inherit `groupId` and `version` from a parent POM.
> Handle Optional groupId and version when Parent Exists

- src/go/README.md
- src/go/cmd/root.go
This PR adds a README for the Go APIView tool and improves the command's usage description.
> Go APIVIEW: Adding README

- eng/common/pipelines/templates/steps/verify-links.yml
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=703442&view=logs&j=ad792ccc-30b2-59a1-5b53-546a79d88828&t=004b592e-cb31-5e96-4451-b7e7f6a38a50
> Run the link verification step even previous step failed.

- eng/pipelines/pipeline-generation.yml
C++ live testing needs resource provisioner
> Add provisoiner secrets to C++ pipelines that run live tests

- eng/common/scripts/Prepare-Release.ps1
Fix DateTime Bug in prepare release script.
> Fix DateTime bug

- src/go/cmd/api_view.go
- src/go/cmd/content.go
- src/go/cmd/token_builders.go
Sort navigation panel items, interface methods.
Remove test packages from packages list. 
Add some small clean up.
> Go APIView: Sort output

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/SemVer.ps1
- Sync devops helper script changes
- Fix issue in SemVer script when using strict mode with Language not set
> Update devops helper script based on changes in azure-sdk repo

- src/go/cmd/api_view.go
return write file error from command.
> Go APIView: return write file error

- src/go/cmd/content.go
Move clients up in the view and in the navigation items.
> Move clients up 

- src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
Hide label for automatic reviews in index page
> Hide SHA info from review list for automatic reviews

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- Update type hint parser to process py3 type hint format
- Fix issue in comparing type hint against docstring return type
- Ignore missing type hint for __init__
> Fix false negatives in python API review

- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
Update repos parameter to contain definition id information
> Update repo parameter for eng/common sync

- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
The values for the yml table should not contain hypens
> Update repos sub parameters

- eng/pipelines/eng-common-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
This reverts commit ba881c416daf68f989adbaba4f7cff468f415924.
For some reason this seems to have cause the PR validations stop triggering
e.g #1307
> Revert "Update repo parameter for eng/common sync (#1372)"

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Fixes https://github.com/Azure/azure-sdk-tools/issues/1379
> Enable passing devops pat for work item scripts

- eng/common/scripts/Update-ChangeLog.ps1
Change Update-ChangeLog.ps1Parameters to used Boolean.
> Change script parameters to Boolean

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
> Allow logging into specific subscription

- eng/common/pipelines/templates/steps/verify-agent-os.yml
- eng/common/scripts/Verify-AgentOS.ps1
This PR reworks the verify agent OS logic so that the agent pool and image are passed into a PowerShell script, and then is checked against a list of valid configuration entries.
> Rework verify agent OS step.

- eng/common/docgeneration/templates/matthews/styles/main.js
> Change other version to all versions

- eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Only run eng/common check when target branch is master
> Only run eng/common check when target branch is master

- eng/common/scripts/get-markdown-files-from-changed-files.ps1
CI build:
PR validation:
PR: 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=740901&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0
> Trim off the target branch

- src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
Create a background task to run update review
> Add background process to update reviews

- eng/common/scripts/common.ps1
> Fix language short typo

- src/dotnet/Mgmt.CI.BuildTools/CI/CI.BuildTasks/Mgmt.CI.BuildTasks/MS.Az.Mgmt.CI.BuildTasks.csproj
- src/dotnet/Mgmt.CI.BuildTools/ci.yml
> Import global variables from mgmt pipeline

- eng/common/scripts/SetTestPipelineVersion.ps1
Move SetTestPipelineVersion.ps1 to eng/common.
> Move SetTestPipelineVersion.ps1 to eng/common

- eng/common/pipelines/templates/steps/create-apireview.yml
Change API status check as hard error
> Enable APIView status check

- eng/common/scripts/SetTestPipelineVersion.ps1
Fixing up errors in `SetTestPipelineVersion.ps1`
> Fix logic in SetTestPipelineVersionInEngCommon

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/java/apiview-java-processor/pom.xml
Forgot to bump parser version for java so older reviews were not refreshed.
> Update java parser version to rebuild existing reviews

- eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
Create `set-test-pipeline-version.yml`
> Move SetTestPipeline into its own template

- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/Prepare-Release.ps1
- eng/common/scripts/Update-ChangeLog.ps1
- Distinguish between `PackageName` and `ArtifactName`
- Update logic to always use `Get-AllPkgProperties`
- Accommodate artifacts defined in all ci.yml files including files like ci.data.yml
> Update Package Properties Logic

- eng/common/pipelines/templates/steps/create-pull-request.yml
- eng/common/scripts/Submit-PullRequest.ps1
Give the ability to open PRs as draft.
> Add ability to open PR as draft to Submit-PullRequest.ps1

- .azure-pipelines/dotnet.yml
https://github.com/Azure/azure-sdk-for-net/blob/master/eng/pipelines/templates/variables/globals.yml#L6
> Disable the feed analysis

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/Prepare-Release.ps1
- eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Fixes https://github.com/Azure/azure-sdk-tools/issues/1462 as well as some other minor tweaks.
> Add ReleaseTrackingOnly option to Prepare-Release

- eng/common/scripts/Update-ChangeLog.ps1
- Add ChangelogPath so we don't need to run Get-PkgProperties.
> Add ChangelogPath to Update-ChangeLog.ps1

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
If a jar submitted to API view contains shaded dependencies, then the META-INF directory of the jar will contain pom.xml for each of the dependency libraries causing issues when we create the MavenGAV object. This PR adds a check to look at the pom file of the submitted artifact only. Other pom.xml files will be ignored.
> Fix issue with shaded jars that have multiple pom.xml files

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
New API to check review status from prepare release script
> New api to check status of automatic review approval

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/README.md
- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/Remove-TestResources.ps1.md
- eng/common/TestResources/Update-TestResources.cmd
- eng/common/TestResources/Update-TestResources.ps1
- eng/common/TestResources/Update-TestResources.ps1.md
Fixes https://github.com/Azure/azure-sdk-tools/pull/1454
> Use SubscriptionId throughout TestResources

- eng/common/pipelines/templates/steps/retain-run.yml
Removes a cut/paste error from the retain runs template.
> Remove condition.

- eng/common/pipelines/templates/steps/docs-metadata-release.yml
Fixed the release pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=838480&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=838731&view=results
> Onboarding branch needs to delete the step of updating target ci

- eng/common/pipelines/templates/steps/sparse-checkout.yml
> make -checkout: none an optional phase

- eng/common/pipelines/templates/steps/verify-samples.yml
- eng/common/scripts/Test-SampleMetadata.ps1
Replaces Azure/azure-sdk-for-python#17999 for use in all language repos.
> Verify samples during CIs

- eng/common/pipelines/templates/steps/verify-samples.yml
- eng/common/scripts/Test-SampleMetadata.ps1
Relates to Azure/azure-sdk-for-java#20684
> Handle empty files in Test-SampleMetadata

- tools/notification-configuration/common/Helpers/GitHubNameResolver.cs
- tools/notification-configuration/common/Services/AzureDevOpsService.cs
- tools/notification-configuration/common/common.csproj
- tools/notification-configuration/github-codeowner-subscriber/GitHubService.cs
- tools/notification-configuration/github-codeowner-subscriber/Program.cs
- tools/notification-configuration/github-codeowner-subscriber/github-codeowner-subscriber.csproj
- tools/notification-configuration/identity-resolver/Program.cs
- tools/notification-configuration/identity-resolver/identity-resolver.csproj
- tools/notification-configuration/notification-creator/NotificationConfigurator.cs
- tools/notification-configuration/notification-creator/Program.cs
- tools/notification-configuration/notification-creator/notification-creator.csproj
Also improved performance using ~MemoryCache~ caching with `ConcurrentDictionary`
> Fix notification subscriber teams

- eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
This PR reverts the SetDevVersion usage to the state it was in before I started messing around with it.
> Revert changes to SetDevVersion.

- eng/pipelines/pipeline-generation.yml
This is the merge in once the iOS ```ci.yml``` files are merged in.
> Enable iOS pipeline generation.

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
> Better highlight which tab is active

- eng/pipelines/pipeline-generation.yml
This PR adds the pipeline variable group needed for CocoaPods releases.
> Add CocoaPods release pipeline variable group.

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/OAuthResponseSanitizer.cs
Implemented as a sanitizer instead of adding another configuration setting.
> Add Oauth Session Sanitizer

- src/dotnet/APIView/APIView/CodeFileHtmlRenderer.cs
- src/dotnet/APIView/APIView/CodeFileRenderer.cs
- src/dotnet/APIView/APIView/Model/CodeFileTokenKind.cs
- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Models/RenderedCodeFile.cs
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/ASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/TokenKind.java
Skip maven metadata from comparison when revisions are diffed
> Add option to skip a range from diff comparison

- .azure-pipelines/dotnet.yml
- src/dotnet/Mgmt.CI.BuildTools/ci.yml
- Update reference to azure-sdk-build-tools
> Add Ref to azure-sdk-buld-tools

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordingType.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
@mikeharder got a set of changes on perf side to enable this as well.
> Enable In-Memory Recordings for Perftest

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Update-ChangeLog.ps1
- eng/common/scripts/Verify-ChangeLog.ps1
Fixes https://github.com/Azure/azure-sdk-tools/issues/1682
> Strict mode needs the variables initialized

- .azure-pipelines/warden.yml
- eng/pipelines/live-test-cleanup.yml
- eng/pipelines/notifications.yml
Should resolve https://github.com/Azure/azure-sdk-tools/issues/1321
> Update ubuntu VMImage to ubuntu-20.04

- eng/common/scripts/ChangeLog-Operations.ps1
- Add logic for verifying that there is not empty changelog sections before releasing.
> Add verification of changelog sections

- eng/common/pipelines/templates/steps/set-default-branch.yml
- eng/common/scripts/update-docs-metadata.ps1
> Fix hard-coded master

- tools/test-proxy/startup-scripts/README.md
- tools/test-proxy/startup-scripts/start-server.js
- tools/test-proxy/startup-scripts/start-server.ps1
- tools/test-proxy/startup-scripts/start-server.py
> Example Startup Scripts

- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
- eng/pipelines/pipeline-generation.yml
Consume latest changes from pipeline generation tool in https://github.com/Azure/azure-sdk-tools/pull/1708
> Update pipeline generation tool version

- src/go/cmd/content.go
- src/go/cmd/output/teststruct.json
Fixes https://github.com/Azure/azure-sdk-for-go/issues/14343
> Go APIView: misc fixes

- src/dotnet/APIView/APIViewWeb/Languages/ProtocolLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Startup.cs
This is initial set of changes to support APIView integration for LLC
> LLCsupport in APIView

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Was copying an empty stream.
Fixed naming elsewhere
> GZip Bugfixes

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
- Removed status column and added green check mark for approved reviews.
- Included changes from @JonathanGiles
> UI changes

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- Switch to using rest instead of cli for querying work items
as cli is limited to 1000 items only.
- Fix issues with Generated fields not being set.
- Correctly sort older workitems by version instead of string.
Changes ported from https://github.com/Azure/azure-sdk/commits/main/eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
> Update devops workitem helpers

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminFunctionalityTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordedTestSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyRegexSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/RemoveHeaderSanitizer.cs
> Add BodyRegexSanitizer and HeaderRemoverSanitizer

- eng/pipelines/mirror-repos.yml
To support following sync flows:
- public spec repo master -> public spec repo main 
- private spec repo master -> private spec repo main
> update mirror repo pipeline to sync spec repo master to main branch

- eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Update Ubuntu VM image from 18 to 20
> Switch ubuntu 18 to ubuntu 20

- tools/test-proxy/docker/README.md
@scbedd feel free to reject this PR if the edits are incorrect - this is just what I found while running it
> test proxy docker readme edits

- src/swift/Sources/APIViewManager.swift
- src/swift/Sources/Models/NavigationItem.swift
- src/swift/Sources/Models/NavigationTags.swift
- src/swift/Sources/Models/TokenFile.swift
- src/swift/Sources/Models/TokenItem.swift
- src/swift/Sources/main.swift
- Updates the boilerplate models to properly serialize
- Adds convenience methods on `TokenFile` for adding tokens
- Implements some simple iterative stubs to generate tokens.
> Swift APIView Updates

- .azure-pipelines/apiview.yml
- packages/python-packages/protocol-stub-generator/protocol/parse_yml.py
- packages/python-packages/protocol-stub-generator/setup.py
- src/dotnet/APIView/APIViewWeb/Languages/ProtocolLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
Integrate parser so APIView can take yaml as input file to generate protocol reviews.
> LL parser support to create protocol API review from autorest yaml 

- src/swift/Sources/APIViewManager.swift
- src/swift/Sources/Models/NavigationItem.swift
- src/swift/Sources/Models/TokenFile.swift
- src/swift/Sources/main.swift
- Simplifies the API
- Adds rudimentary navigation
- Adds automatic indentation
> Swift: Refactoring and streamlining

- src/swift/Sources/APIViewManager.swift
- src/swift/Sources/Models/TokenFile.swift
- src/swift/Sources/main.swift
- src/swift/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView.xcscheme
Fixes up some of the simple style issues identified during review.
> Swift APIView: Clean up style issues.

- src/swift/Sources/Models/TokenFile.swift
> Swift APIView: sort navigation list

- src/swift/Sources/APIViewManager.swift
Fixes the dest URL not working
> Fixed the dest URL problem

- eng/common/scripts/FilterPoliCheckResults.ps1
- This file will work with PoliCheck tool that runs in each repo.
- It filters out from data specified in an AllowList from PoliCheck.
> Add FilterPoliCheckResult.ps1

- src/swift/README.md
- src/swift/Sources/APIViewManager.swift
- src/swift/Sources/Extensions/DeclarationModifier+Extensions.swift
- src/swift/Sources/Models/TokenFile.swift
This will enable generation of Swift APIView for Objective-C-based libraries.
> Swift APIView: support generation of APIView from swiftinterface files

- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
> Update Ubuntu 18 to 20

- dotnet.proj
- src/dotnet/SnippetGenerator/SnippetGenerator.csproj
- Add all files needed to run SnippetGenerator to the tools directory of the package.
> Add tools directory to nuget package

- .azure-pipelines/apiview.yml
- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
Interim solution until we have package version available for all languages to compare  within semver ranges. Currently this check will only be done when package is ready for release.
> hotfix release should check all approved revisions

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
Update help text to make it clear on what needs to be uploaded for go package
> Update help text for go API review

- eng/common/scripts/Create-APIReview.ps1
Update caller create review script to pass new parameter when release status is set to a date
> Verify API surface level against all approved revisions for GA releases

- src/swift/Sources/Models/TokenFile.swift
Unblocks MeetingUIClient folks
> Swift APIView: Fix display bug

- README.md
> Remove random line in main readme

- src/dotnet/APIView/APIViewWeb/Languages/SwiftLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Startup.cs
Add filter for Swift reviews and help text on how to create Swift reviews.
> Swift filter button and create review help text for swift reviews

- src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Startup.cs
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/Analyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/XMLASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/ModuleInfoDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/ChildItem.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Gav.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Pom.java
Demo available here: https://apiview.dev/Assemblies/Review/f7b789284b604d89bdbba0c8b82aece2
> Initial support for parsing and displaying XML files in APIView

- tools/github-labels/README.md
- tools/github-labels/deploy-labels.ps1
- tools/github-labels/diff-repo-labels.ps1
- tools/github-labels/refresh-snapshots.ps1
- tools/github-labels/repository-snapshots/autorest.csv
- tools/github-labels/repository-snapshots/autorest.go.csv
- tools/github-labels/repository-snapshots/autorest.java.csv
- tools/github-labels/repository-snapshots/autorest.python.csv
- tools/github-labels/repository-snapshots/autorest.swift.csv
- tools/github-labels/repository-snapshots/autorest.typescript.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-c.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-cpp.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-go-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-go.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-java-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-java.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-js.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-net-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-net.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-python-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-python.csv
- tools/github-labels/repository-snapshots/perks.csv
- tools/github-labels/scan-new-labels.ps1
The focus of these changes is to introduce a new script that will diff the labels in a given repository against the common set.   Also included are refreshes to the current snapshots for each repository and some minor formatting tweaks to existing scripts.
> [GitHub Labels] Diff-vs-Common

- tools/github-labels/repositories.txt
- tools/github-labels/repository-snapshots/autorest.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-c.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-cpp.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-go.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-java.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-js.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-net.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-python.csv
- tools/github-labels/repository-snapshots/azure-sdk-tools.csv
- tools/github-labels/repository-snapshots/azure-sdk.csv
The focus of these changes is to onboard the Azure SDK main and tools repositories into common label management.
> [GitHub Labels] Onboarding Tools and Main

- eng/pipelines/live-test-cleanup.yml
- eng/scripts/live-test-resource-cleanup.ps1
Also fixes date parsing errors. If there is a DeleteAfter tag and we cannot parse the date then we attempt to delete it. 
fyi @heaths
> Add playground to cleanup

- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/scripts/Helpers/Resource-Helpers.ps1
- eng/scripts/live-test-resource-cleanup.ps1
Fixed "rg.Name" to "rg.ResourceGroupName" and added some extra logging.
> Fix resource clean-up script

- tools/github-labels/common-labels.csv
- tools/github-labels/repositories.txt
- tools/github-labels/repository-snapshots/autorest.csharp.csv
- tools/github-labels/repository-snapshots/autorest.csv
- tools/github-labels/repository-snapshots/autorest.go.csv
- tools/github-labels/repository-snapshots/autorest.java.csv
- tools/github-labels/repository-snapshots/autorest.python.csv
- tools/github-labels/repository-snapshots/autorest.swift.csv
- tools/github-labels/repository-snapshots/autorest.typescript.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-android-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-android.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-c-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-c.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-cpp.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-go-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-go.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-ios-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-ios.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-java-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-java.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-js-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-js.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-net-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-net.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-python-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-for-python.csv
- tools/github-labels/repository-snapshots/azure-sdk-pr.csv
- tools/github-labels/repository-snapshots/azure-sdk-tools.csv
- tools/github-labels/repository-snapshots/perks.csv
The focus of these changes is to add the following repositories:
- Azure\azure-sdk-for-ios
- Azure\azure-sdk-for-ios-pr
- Azure\azure-sdk-for-android
- Azure\azure-sdk-for-android-pr
- Azure\azure-sdk-pr
The "Stress" label has also been added back into the common set, by agreement in the working group thread.
> [GitHub Labels] More Repositories

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Fixes https://github.com/Azure/azure-sdk-tools/issues/1923
fyi @pakrym
> Fix query batch processing

- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
Hide AsyncIteratorStateMachine attribute as per suggestion from .Net API reviewers.
> Hide AsyncIteratorStateMachine attribute for 

- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- src/dotnet/APIView/APIViewWeb/Languages/SwiftLanguageService.cs
Windows dependency package installation is stuck waiting for a lock based when installing as global user. Installing it in user mode succeeds.
> Swift parser should not process uploaded json file

- eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
- Skip eng/common workflow enforcer for private repos.
> Skip eng common workflow enforcer for private repos

- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator/Program.cs
Resolves Azure/azure-sdk-for-net#22347 and is a port of Azure/azure-sdk-for-net#23210
> Do not print red success message

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
- Allow untrusted SSL certs from upstream server
> [Test-Proxy] Add "--insecure" option

- tools/daily-dev-build-variable/daily-dev-build-variable.yml
- I'm not sure if this is file is still used, but it should align with my changes in #1967
> Make "Setup Versioning Properties" cancellable

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/appsettings.json
> Minimize Logging.

- eng/pipelines/templates/steps/ref-updater.yml
- eng/pipelines/tools-repo-versioning.yml
- Add support for updating tools repo refs on repositiory branches.
- Depends on https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-build-tools/pullrequest/201
> Update tools versioning

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.csproj
Reverts breaking change in PR #1807
> Fix binding issue for .NET analyzers  in SDK

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
Just need to ensure that it is a passthrough when there is no work to be done. @seankane-msft
> [Test-Proxy] BodyKeySanitizer update

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/BodilessMatcher.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/ActiveMetadataModel.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/RunTimeMetadataModel.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/ActiveExtensions.cshtml
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/MetadataDump.cshtml
`/Info/Active/` Before:
`/Info/Active/` After:
> [Test-Proxy] Show Customization Details on `/Info/Active`

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
If we have no `body`, we can't simply assume that the ctor has no params. It is handled by just ensuring we don't attempt to access the empty body, and then passing an empty array for parameter-less constructors. Much cleaner.
@seankane-msft
> [Test-Proxy] Changing ordering of how we set the constructors

- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Scheduled CI build is removing last revision and creating new revision for automatic reviews even if it matches with latest review revision. So this PR is to delete pending revision only if it doesn't match with current one that's being processed. We are deleting revisions to keep the pending list lean.
> Delete last pending revision only if it doesn't match 

- eng/common/pipelines/templates/steps/detect-api-changes.yml
- eng/common/scripts/Detect-Api-Changes.ps1
Common changes to  detect API changes from PR pipelines.
> Common pipeline template and script to detect API changes

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Prepare-Release.ps1
- eng/common/scripts/Update-ChangeLog.ps1
Remove empty sections from changelog entry in prepare release run.
> Remove empty sections in changelog entry as part of prepare release

- src/dotnet/APIView/APIViewWeb/Account/AutoReviewModifierRequirementHandler.cs
- src/dotnet/APIView/APIViewWeb/Account/PullRequestPermissionRequirement.cs
- src/dotnet/APIView/APIViewWeb/Account/PullRequestPermissionRequirementHandler.cs
- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/HostedServices/PullRequestBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/Models/PullRequestModel.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
Create persistent API review diff for pull request
> Create persistent review diff and cleanup

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/XMLASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/maven/Pom.java
Miscellaneous improvements to the Java APIView processor related to XML parsing.
> Improvements to the Java APIView processor

- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
Updated package extension for .Net
> Update .Net package file extension in validation list

- packages/java-packages/codesnippet-maven-plugin/pom.xml
- packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/SnippetBaseMojo.java
This PR adds the missing Maven plugins that are needed to produce the artifacts needed for a release to Maven
> Update Codesnippet Build to Produce Artifacts for Release

- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
- src/dotnet/APIView/APIViewTest/CodeFileBuilderTests.cs
- src/dotnet/APIView/APIViewTest/ExactFormatting/Accessibility.cs
> Hide `private protected` members

- .azure-pipelines/apiview.yml
- src/ts/ts-genapi/export.ts
JS api file name is renamed to have version info when uploaded manually. So this PR is to show version if it is present
> Show version in JS review name if version is present in file name

- src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
Format bot comment based on the feedback for this feature.
> API view pull request comment changes

- src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
Pull request document is not retrieved correctly from enumerator.
> Existing pull request model is not fetched correctly

- eng/common/testproxy/docker-start-proxy.ps1
Reverts back to a version that does not have mysterious Credential Issue
> Revert change back

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/RunTimeMetadataModel.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyRegexSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/ContinuationSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/HeaderRegexSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/RemoveHeaderSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/UriSubscriptionIdSanitizer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Views/Info/MetadataDump.cshtml
An attempt at clarifying what caused some issues for @HarshaNalluru  and @mccoyp this past Monday/Tuesday.
Bug Fix:
> Test-Proxy Feedback Inspired Documentation Updates

- eng/common/scripts/Invoke-GitHubAPI.ps1
Docs workflow actually do sanity check on each individual package. If failed the check, then we'd better to file an issue tracking the error. The PR is a script to create an issue.  
Testing issues: https://github.com/Azure/azure-sdk-tools/issues/2195
> Create an issue template

- tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Handlers/Handler.cs
Skip all neutral checks from final checks status.
> Skip neutral checks from outstanding check run calculation

- eng/common/scripts/stress-testing/deploy-stress-tests.ps1
- eng/common/scripts/stress-testing/find-all-stress-packages.ps1
- eng/pipelines/stress-test-release.yml
- tools/stress-cluster/chaos/README.md
- tools/stress-cluster/chaos/examples/network-stress-example/templates/testjob.yaml
- tools/stress-cluster/chaos/examples/stress-deployment-example/parameters.json
- tools/stress-cluster/cluster/kubernetes/generator/README.md
- tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator.Tests/GeneratorTest.cs
- tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Program.cs
- tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/Chaos/NetworkChaos.cs
- tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/Job.cs
- tools/stress-cluster/cluster/kubernetes/generator/Stress.Generator/Resources/StressTestPackage.cs
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_deploy_configmap.tpl
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_deploy_volumes.tpl
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_init_deploy.tpl
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/templates/_stress_test.tpl
- Stress test usability feedback
- Add schedule and duration to network chaos
> Stress test usability updates

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Prepare-Release.ps1
Should resolve https://github.com/Azure/azure-sdk-tools/issues/1542
> Add prompt before replacing latest release title on  prepare release run

- .gitignore
- tools/oav-traffic-converter/.gitignore
- tools/oav-traffic-converter/LICENSE
- tools/oav-traffic-converter/README.md
- tools/oav-traffic-converter/ci.yml
- tools/oav-traffic-converter/input-example/input-example.json
- tools/oav-traffic-converter/input-example/test_retry.pyTestStorageRetrytest_retry_on_server_error.json
- tools/oav-traffic-converter/output-example/output-example.json
- tools/oav-traffic-converter/output-example/test_retry.pyTestStorageRetrytest_retry_on_server_error0.json
- tools/oav-traffic-converter/package.json
- tools/oav-traffic-converter/src/cli.ts
- tools/oav-traffic-converter/tsconfig.json
Submitting this here. Intent is to publish a dev version to our feed such that Ray can consume it directly instead of installing via  local `npm install`.
Pulled across from [personal repo](https://github.com/scbedd/oav-traffic-converter).
> [OAV] Converter Prototype

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
> [Test-Proxy] BodyKeySanitizer - Handle NonJSON Request/Response Bodies

- tools/sdk-testgen/packages/autorest.gotest/src/generator/generateContext.ts
- tools/sdk-testgen/packages/autorest.gotest/src/generator/mockTestGenerator.ts
- tools/sdk-testgen/packages/autorest.gotest/src/util/goHelper.ts
- tools/sdk-testgen/packages/autorest.gotest/test/unittest/generator/__snapshots__/testGoTester.ts.snap
fix: array element ptr judegement problem for first layer call
chore: add default package name for corner case
fix: first layer object ptr lost
fix: handle array value to string
fix: first layer ptr judgement problem
> fix testgen bug

- tools/sdk-testgen/packages/autorest.gotest/src/generator/mockTestGenerator.ts
- tools/sdk-testgen/packages/autorest.gotest/src/template/mockTest.go.njk
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/compute/golang/ze_generated_example_availabilitysets_client_test.go
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/compute/golang/zt_generated_mock_test.go
- tools/sdk-testgen/packages/autorest.gotest/test/swagger/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/compute.json
- tools/sdk-testgen/packages/autorest.gotest/test/swagger/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/examples/CreateAnAvailabilitySet.json
- tools/sdk-testgen/packages/autorest.testmodeler/src/core/model.ts
- tools/sdk-testgen/packages/autorest.testmodeler/src/util/helper.ts
- tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/compute/model/__debug/test-modeler-pre.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/test/unittest/core/__snapshots__/testModel.ts.snap
- tools/sdk-testgen/packages/autorest.testmodeler/test/unittest/core/testModel.ts
1. add operation/operationGroup in ExampleGroup
2. exclude properties from parent if already handled in subclass
> for sdk-testgen/testmodeler

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
https://apiviewstaging.azurewebsites.net/Assemblies/Review/43f1adb3241a4136aa09c751d804c22a
Fixes #2189, #1528, #1529.
> [APIView Python] Eliminate duplicate kwargs

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
https://apiviewstaging.azurewebsites.net/Assemblies/Review/7be14d8532a54257aa664c91272292ea?diffRevisionId=237593112ea0488d88c9786c109d504f&doc=False&diffOnly=False
Fixes #1738 and #826.
> [APIView Python] Fix truncated return types

- eng/common/scripts/get-codeowners.ps1
Re-Adding `get-codeowners.ps1` to unblock cpp. https://github.com/Azure/azure-sdk-for-cpp/blob/main/eng/pipelines/templates/stages/archetype-cpp-release.yml#L197
> Re-add get-codeowners.ps1

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/BlobUploadProcessor.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Functions/RunStateChangedFunction.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
- Add additional blob upload method for test runs
- Update function trigger attribute to support parameterized consumer group
> Add TestRun blob support

- eng/containers/ci.yml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/deploy-stress-test-resources.ps1
Updating the container ci trigger to the directory, not just the dockerfile.
Removing template.json dependency in stress test resource deploy script.
> updating container ci trigger

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/BodilessMatcher.cs
> [Test-Proxy] Exclude `content-length` from BodilessMatcher matching

- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/tests/docstring_parser_test.py
Verified with Search:
https://apiviewstaging.azurewebsites.net/Assemblies/Review/aada52adf8234620806960712526728a?diffRevisionId=7739be475c244bf09ef728f9bcb093ad&doc=False&diffOnly=True
> [Python APIView] Fix KeyError issue

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Azure.Sdk.Tools.TestProxy.Tests.csproj
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/if_none_match_present.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/HeaderlessMatcher.cs
@HarshaNalluru This should address both issues you encountered yesterday afternoon.
And:
> [Test-Proxy] Header Exclusion Updates

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
> [Test-Proxy] Set Explicit Header on TestRecorderMismatchException

- tools/mock-service-host/package.json
- tools/mock-service-host/src/mid/coordinator.ts
- tools/mock-service-host/src/mid/oav/swaggerMocker.ts
- tools/mock-service-host/src/mid/responser.ts
1. disable cache
2. fix x-ms-path
3. fix lro for null body
> mock-service-host v 0.1.6

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
Ran into an issue while trying to use the custom matcher API - the matcher method expects a bool, but we were assuming that all JSON values would be strings.
> Fix custom matcher bug

- tools/sdk-testgen/common/changes/@autorest/gotest/fix_gotest_2021-11-30-09-29.json
- tools/sdk-testgen/common/changes/@autorest/gotest/fix_gotest_2021-11-30-09-30.json
- tools/sdk-testgen/common/changes/@autorest/gotest/fix_gotest_2021-11-30-09-31.json
- tools/sdk-testgen/packages/autorest.gotest/src/common/model.ts
- tools/sdk-testgen/packages/autorest.gotest/src/generator/mockTestGenerator.ts
- tools/sdk-testgen/packages/autorest.gotest/src/template/exampleTest.go.njk
- tools/sdk-testgen/packages/autorest.gotest/src/template/mockTest.go.njk
- tools/sdk-testgen/packages/autorest.gotest/src/template/scenarioContent.go.njk
- tools/sdk-testgen/packages/autorest.gotest/src/util/codegenBridge.ts
1. LRO operation with pageable config
2. Multi-response result log
3. Custom item name for pageable operation
> gotest corner case fix

- eng/common/pipelines/templates/steps/check-spelling.yml
- eng/common/scripts/check-spelling-in-changed-files.ps1
- eng/common/spelling/Invoke-Cspell.ps1
- eng/common/spelling/package-lock.json
- eng/common/spelling/package.json
Changes from PR: https://github.com/Azure/azure-sdk-for-js/pull/17142/checks
> Add spell check pin changes

- eng/common/scripts/Verify-Readme.ps1
This PR adds a standard script for validating READMEs.
> Add PowerShell Script for Validating READMEs

- tools/mock-service-host/package.json
- tools/mock-service-host/src/common/constants.ts
- tools/mock-service-host/src/mid/coordinator.ts
- tools/mock-service-host/src/mid/models.ts
- tools/mock-service-host/src/mid/oav/mocker.ts
- tools/mock-service-host/src/mid/responser.ts
- tools/mock-service-host/src/webserver/validateAndMockController.ts
- tools/mock-service-host/test/unittest/testcoordinator.ts
1. fix lro finding
2. fix text response
3. fix date-time-rfc1123 format
> mock-service-host: fix lro finding

- tools/mock-service-host/package.json
- tools/mock-service-host/src/mid/coordinator.ts
- tools/mock-service-host/test/unittest/testcoordinator.ts
use liveValidator.operationSearcher.search() to check whether operation exists
> mock-service-host: fix-find-lro

- eng/common/scripts/Update-DocsMsPackages.ps1
Prerequisites:
Need to change language repo first
Python: https://github.com/Azure/azure-sdk-for-python/pull/22047
JS: https://github.com/Azure/azure-sdk-for-js/pull/19009
.NET: https://github.com/Azure/azure-sdk-for-net/pull/25781
Java:https://github.com/Azure/azure-sdk-for-java/pull/25878
> Taking the parameter literally

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Added new APIs to accept requests to generate review using published preprocessed API file. Existing APIs are not removed for backward compatibility for other languages.
> Preprocess api file in devops pipeline for Python

- eng/common/TestResources/New-TestResources.ps1
The focus of these changes is to ensure that the service principal is explicitly granted the "Owner" role on the active resource group, whether the principal was newly created or a cached instance was used.
- [[New-TestResources] ServicePrincipal is not assigned as a resource group owner (#2399)](https://github.com/Azure/azure-sdk-tools/issues/2399)
> [TestResources] Ensure ownership grant

- tools/code-owners-parser/CodeOwnersParser/CodeOwnerEntry.cs
We used to call the github users api but we often got 403 returned
due to rate limiting. So instead, we are approximating the check
by checking for a slash in the name if there is one then we will consider
it to be a team instead of a user.
> Simplify user check for codeowners parser

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/response_with_retry_after.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
Addresses https://github.com/Azure/azure-sdk-tools/issues/2435
> Set retry-after to 0 in playback response

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Some stress cluster users set a default namespace for the kubectl context in order to make commands shorter (i.e. not
having to type `-n <namespace>`. When the stress test deployment script is run with `-Login`, it will overwrite the
existing kubectl context entry for the cluster, therefore removing the default namespace setting. This change preserves
the default namespace if it has been set for the stress cluster. We still want to re-download the cluster config for
simplicity in case the endpoint has been migrated.
> Preserve kubectl context namespace if set for active stress cluster

- tools/mock-service-host/package-lock.json
- tools/mock-service-host/package.json
- tools/mock-service-host/src/common/configSchema.ts
set excluded jsons refer to: https://github.com/Azure/oav/blob/develop/lib/util/constants.ts#L163
> mock-service-host: exclude example json

- tools/mock-service-host/src/mid/coordinator.ts
- tools/mock-service-host/src/mid/responser.ts
- tools/sdk-testgen/common/changes/@autorest/gotest/fix_string_enum_problem_2021-12-23-05-47.json
1. x-ms-paths description lost
2. rfc3339 datetime comparison
3. 'nextLink' removal in inner object
> Fix mock server corner case

- web/pixel-server/README.md
> [pixel-server] Remove query string param ?path=, add example query

- src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
Fix parameter query to download artifact
> Fix PR detection bad request issue

- CONTRIBUTING.md
> Changes on tool readmes

- src/swift/SwiftAPIView/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView.xcscheme
- src/swift/SwiftAPIViewCore/Sources/Extensions/DeclarationModifier+Extensions.swift
- src/swift/SwiftAPIViewCore/Sources/Extensions/PatternInitializer+Extensions.swift
- src/swift/SwiftAPIViewCore/Sources/Models/NavigationItem.swift
- src/swift/SwiftAPIViewCore/Sources/Models/TokenFile.swift
- src/swift/SwiftAPIViewCore/Sources/Models/TypeModel.swift
- src/swift/SwiftAPIViewCore/Sources/TokenGeneration/NavigationTokens.swift
- src/swift/SwiftAPIViewCore/Sources/Util/URL+Extensions.swift
- src/swift/SwiftAPIViewCore/SwiftAPIViewCore.xcodeproj/project.pbxproj
- src/swift/SwiftAPIViewCore/TestFiles/ExpectFile1.txt
- src/swift/SwiftAPIViewCore/TestFiles/TestFile1.swifttxt
- src/swift/SwiftAPIViewCore/TestFiles/TestFile2.swifttxt
- src/swift/SwiftAPIViewCore/Tests/SwiftAPIViewCoreTests.swift
https://apiviewstaging.azurewebsites.net/Assemblies/Review/343ca92d0b354e25aa5e12788fdaae1e
Fixes #2528.
A number of parsing improvement. Adds tests.  When #2532 is merged this will help prevent regressions to Swift APIView.
> [Swift APIView] Parsing fixes and improvements

- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
- samesite moded needs to be updated to Lax
- Updated Python parser version to 0.2.8
> APIView debug instance is failing to run on latest browser

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Controllers/ReviewController.cs
- src/dotnet/APIView/APIViewWeb/Models/PackageGroupMdel.cs
- src/dotnet/APIView/APIViewWeb/Models/PackageModel.cs
- src/dotnet/APIView/APIViewWeb/Models/ReviewDisplayModel.cs
- src/dotnet/APIView/APIViewWeb/Models/ReviewModel.cs
- src/dotnet/APIView/APIViewWeb/Models/ServiceGroupModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/PackageNameManager.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
- Changes to set service name, package display name if not present in review metadata.
- Added new entry point `/Review/GetReviews` to return grouped json review details.
> Changes to return json grouped review details

- .gitignore
- src/swift/.gitignore
- src/swift/SwiftAPIView.xcworkspace/contents.xcworkspacedata
- src/swift/SwiftAPIView.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Previous PRs failed to commit the SwiftAPIView.xcworkspace that is needed to run SwiftAPIView locally.
> Force add SwiftAPIView.xcworkspace and tweak gitignore

- src/dotnet/APIView/APIViewWeb/README.md
Initial version of readme. I will link contributing guide to this page once that's created.
> Apiview readme

- src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
Initial version of contributing guide for APIView tool
> Contributing guide for APIView

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordSessionTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
> [Test-Proxy] Ignore `x-ms-client-id`

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
- packages/python-packages/api-stub-generator/setup.py
- packages/python-packages/api-stub-generator/tests/apiview_test.py
Fixes #2588.
https://apiviewstaging.azurewebsites.net/Assemblies/Review/a6a1647c45ae4a978c328b5fa57c9d11?diffRevisionId=2dfabe6fcf6144ada7d5aef015285fb9&doc=False&diffOnly=False
> [Python APIView] Fix inconsistent line spacing issues

- eng/common/testproxy/docker-start-proxy.ps1
- eng/common/testproxy/test-proxy-tool.yml
This is the PR that will reflect breaking change coming from [this PR](https://github.com/Azure/azure-sdk-tools/pull/2557).
I am willing to patch everyone's tooling myself, but I may reach out to you if it ends up being complicated :P 
- @billwert Just a heads up, this may affect your current experimentation, though I'm not certain where you're at right now.
- @vhvb1989 I know you were asking me some test-proxy questions earlier today. This is a **breaking change** that could affect your current experimentation. I'll sync with you on the sdk-for-c/cpp auto-prs to see if I need to patch anything there!
> [Test-Proxy] Update targeted version of test-proxy

- eng/common/pipelines/templates/steps/retain-run.yml
- eng/common/scripts/Add-RetentionLease.ps1
- eng/common/scripts/Invoke-DevOpsAPI.ps1
Based on some new guidelines we are updating our release retention to 2 years.
> Update our retention time to 2 years

- src/dotnet/APIView/APIView/Languages/CodeFileBuilder.cs
- src/dotnet/APIView/APIView/Languages/DependencyInfo.cs
- src/dotnet/APIView/APIView/Program.cs
- src/dotnet/APIView/APIViewTest/CodeFileBuilderTests.cs
- src/dotnet/APIView/APIViewWeb/Languages/CSharpLanguageService.cs
Contributes to https://github.com/Azure/azure-sdk-tools/issues/1409
> Add dependencies for C# to review

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/request_with_binary_content.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyRegexSanitizer.cs
Fixes https://github.com/Azure/azure-sdk-tools/issues/2616
> Don't attempt to sanitize binary data

- eng/common/scripts/job-matrix/README.md
Make it a little more clear and easier to discover that you can append to values rather than just replace them entirely.
> Update matrix doc header titles for replace/modify/append

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
> [Test-Proxy] Add mismatch error to a header, additional information in generic exception handling

- scripts/powershell/sub-cleanup/sub-cleanup.ps1
Added parameter handling and rewrote a bunch of other stuff.
Old PR: https://github.com/Azure/azure-sdk-tools/pull/533
> Subscription cleanup script

- .gitignore
> Update gitignore to exclude Python packages folder

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/nodes/__init__.py
- packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_key_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_property_node.py
- packages/python-packages/api-stub-generator/tests/class_parsing_test.py
Fix #2568.
https://apiviewstaging.azurewebsites.net/Assemblies/Review/5e455e3a04cc4a25b5926a602cd98da3/231d2bb07ce7417f835164d39d7ce9fd?diffRevisionId=114158e62a5248f6b86c6048897609e9&doc=False&diffOnly=False
> [Python APIView] Support TypedDict

- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/tests/class_parsing_test.py
Follow-up PR will add test cases.
> [Python APIView] Fix issue with OpenCensus

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordSessionTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/CustomDefaultMatcher.cs
Addresses https://github.com/Azure/azure-sdk-tools/issues/2644
> Add ignoredQueryParameters to CustomDefaultMatcher

- eng/common/scripts/stress-testing/find-all-stress-packages.ps1
If multiple people develop and deploy stress tests from a codespaces environment, they will end up in the same
`codespaces` namespace based on the USER env variable. To support different user namespaces, look for the GITHUB_USER
env variable first.
> [stress testing] Support github user namespaces for codespaces environments

- eng/common/scripts/Helpers/Metadata-Helpers.ps1
- eng/common/scripts/Update-DocsMsMetadata.ps1
Failed pipeline from query:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1345943&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=95157bd4-d7ec-5ed7-b303-68e386ec5302
Testing on failed pipeline:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1346386&view=results
> Fixed the no IsPrerelease property issue and retry 3 times on API call.

- eng/common/pipelines/templates/steps/credscan.yml
The PR is to extract common logic of credscan step into eng/common.
Here is the testing pipeline in .NET
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1346890&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=00617558-a7e1-589a-0f6a-8a21d47640f0
> Add common template for credscan step

- doc/engsys_resource_management.md
This PR adds a draft of our guidance for (primarily) development resources created by members of the SDK team, as well
as testing resources created by automation.
> Add subscription resource management guidelines

- src/dotnet/APIView/apiview_token_gist.json
Moved apiview token gist file to tools repo and added new property field for cross language ID
> Added APIView json token gist file

- eng/common/pipelines/templates/steps/credscan.yml
Fixed the failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1360045&view=logs&j=90227089-9f51-5ecc-566c-84e1f2918394&t=0bfbd951-3ae9-5af7-a8d0-fd7a58328df7
Testing the changes:
1. https://github.com/Azure/azure-sdk-for-java/pull/27022
2. https://github.com/Azure/azure-sdk-for-net/pull/26945
> Fixed the regex of the target branch

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml
- Wrap code-line in conversation.
> Wrap code-line in Conversation

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Matchers/CustomDefaultMatcher.cs
@HarshaNalluru extremely low pri when you have a couple minutes :)
> [Test-Proxy] Improve descriptions for `excludedHeaders` and `ignoredHeaders` fields in CustomDefaultMatcher

- src/dotnet/APIView/APIView/Model/CodeFileToken.cs
Added new Cross language ID filed in token entity.
> Added new property for cross language ID

- .azure-pipelines/apiview.yml
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/dev_requirements.txt
- packages/python-packages/api-stub-generator/setup.py
- packages/python-packages/api-stub-generator/tests/class_parsing_test.py
- packages/python-packages/api-stub-generator/tox.ini
Closes #2713.
APIView: https://apiviewstaging.azurewebsites.net/Assemblies/Review/00adead293274a5e8845d7468200c4bf
(Note that dataclasses do not yet display correctly. That will be the subject of a forthcoming PR)
> [Python APIView] Update tests to use apistubgentest package

- eng/common/pipelines/templates/steps/credscan.yml
4 lang PRs:
Java: https://github.com/Azure/azure-sdk-for-java/pull/27152
.NET: https://github.com/Azure/azure-sdk-for-net/pull/27054
Python: https://github.com/Azure/azure-sdk-for-python/pull/23090
JS: https://github.com/Azure/azure-sdk-for-js/pull/20413
The PR includes the link of all testing.
> Update credscan tool version

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
- tools/test-proxy/docker/dockerfile
- tools/test-proxy/documentation/using-in-devops.md
> [Test-Proxy] Fix docker build, ensure docker logging, update generic error responses

- .azure-pipelines/apiview.yml
- packages/python-packages/api-stub-generator/tox.ini
> Run stubgen on api test package to run same step as CI on actual package

- src/swift/CHANGELOG.md
- src/swift/SwiftAPIViewCore/Sources/Extensions/PatternInitializer+Extensions.swift
- src/swift/SwiftAPIViewCore/Sources/Models/TokenFile.swift
- src/swift/SwiftAPIViewCore/Sources/Models/TypeModel.swift
- src/swift/SwiftAPIViewCore/TestFiles/TestFile2.swifttxt
> [Swift APIView] Add support for Getter/Setter variable types

- tools/stress-cluster/chaos/README.md
* Link to the location of the example, just to make life easier.
> Updating stress testing readme

- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
@sima-zhu  apologies for the inconvience.
> Ensure Tools w/ no docker deployments don't fail

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/__init__.py
- packages/python-packages/api-stub-generator/apistub/_apiview.py
- packages/python-packages/api-stub-generator/apistub/_diagnostic.py
- packages/python-packages/api-stub-generator/apistub/_metadata_map.py
- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- packages/python-packages/api-stub-generator/apistub/_token.py
- packages/python-packages/api-stub-generator/apistub/nodes/_argtype.py
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
- packages/python-packages/api-stub-generator/apistubgen.py
- packages/python-packages/api-stub-generator/tests/apiview_test.py
- packages/python-packages/apistubgentest/apiview_mapping.json
https://apiviewstaging.azurewebsites.net/Assemblies/Review/cd637895f39e43e2ad18c1837744b6a0
> [Python APIView] CrossLangugageDefintionId implementation

- eng/common/pipelines/templates/steps/cosmos-emulator.yml
- eng/common/scripts/Cosmos-Emulator.ps1
- Add retry logic to downloading of cosmos emulator.
- Move logic into a script file.
Should resolve https://github.com/Azure/azure-sdk-for-java/issues/9473
> Improve Cosmos Emulator logic

- src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Automatically archive manual reviews if last updated revision is 4 months or more older.
> Auto archive API reviews

- src/dotnet/APIView/APIView/Model/CodeFile.cs
- src/dotnet/APIView/apiview_token_gist.json
New fields in token code file.
> Code file token changes for package display name

- src/dotnet/APIView/APIViewWeb/Languages/SwaggerLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
Support uploading json token file for swagger review.
> Swagger review json upload support in APIView

- src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
Update existing comment for the package by APIVIew when a API is changed in new commit.
> Update existing comment from APIView bot

- tools/test-proxy/README.md
> [Test Proxy] Misspelling correction

- .azure-pipelines/apiview.yml
- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_stub_generator.py
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_argtype.py
- packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_module_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_variable_node.py
- packages/python-packages/api-stub-generator/tests/class_parsing_test.py
- packages/python-packages/api-stub-generator/tests/docstring_parser_test.py
- packages/python-packages/api-stub-generator/tests/function_parsing_test.py
- packages/python-packages/apistubgentest/apistubgentest/models/__init__.py
- packages/python-packages/apistubgentest/apistubgentest/models/_models.py
Fixes #2797.
Fixes #2802.
Fixes #2844.
https://apiviewstaging.azurewebsites.net/Assemblies/Review/5a7c82e40a64497fae8984f26209f70d
> [Python APIView] Fix ItemPaged/AsyncItemPaged warning and Required kwargs

- packages/python-packages/api-stub-generator/CHANGELOG.md
After this is merged I'll tag this release.
> [Python APIView] Add release date for APIView 0.2.10.

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
@JoshLove-msft @mccoyp @HarshaNalluru @timovv @seankane-msft How does this impact your existing assumptions? If at all?
> [Test-Proxy] Add OAuthResponseSanitizer to set of default sanitizers

- eng/common/scripts/ChangeLog-Operations.ps1
- Verify changelog like a release is about to take place if the changelog has a valid release date set.
- Should resolve https://github.com/Azure/azure-sdk/issues/3690
> Verify ChangeLog as ForRelease

- eng/common/scripts/ChangeLog-Operations.ps1
Reverts Azure/azure-sdk-tools#2836
> Revert "Verify ChangeLog as ForRelease"

- packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/apistubgentest/apistubgentest/models/__init__.py
- packages/python-packages/apistubgentest/apistubgentest/models/_models.py
- packages/python-packages/apistubgentest/requirements.txt
- packages/python-packages/apistubgentest/setup.py
> [Python APIView] Add more enum tests and tests for Metaclasses

- packages/java-packages/codesnippet-maven-plugin/pom.xml
- packages/java-packages/codesnippet-maven-plugin/src/main/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetReplacement.java
- packages/java-packages/codesnippet-maven-plugin/src/test/java/com/azure/tools/codesnippetplugin/implementation/CodesnippetReplacementBenchmark.java
Adds benchmarks to `codesnippet-maven-plugin`. Additionally, includes further updates to codesnippet replacements based on the results found in the benchmark.
> Adds Benchmarks to codesnippet-maven-plugin

- eng/pipelines/azuresdkpartnerdrops-to-devops.yml
- eng/pipelines/azuresdkpartnerdrops-to-nuget.yml
- Change parameter name to BlobPath, add ability to publish to private preview feed
> Update to public interface of partner release pipelines

- eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
- eng/common/scripts/job-matrix/README.md
@benbp 
This extension will allow the python regression testing to dynamically update it's matrix.
Related to Azure/azure-sdk-for-python#23519
> [Matrix-Generation] Support additional customized steps before matrix generation

- eng/common/scripts/Update-DocsMsToc.ps1
To fix the issue which caused by group id
Failed updates: https://github.com/Azure/azure-docs-sdk-java/blob/daily/2022-03-14-ci-succeeded/docs-ref-mapping/reference-unified.yml#L361
> Fix toc which need to add group id property

- tools/sdk-testgen/packages/autorest.gotest/package.json
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/appplatform/test/__debug/go-tester-pre.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/appplatform/test/__debug/go-tester.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/appplatform/test/__debug/test-modeler-pre.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/appplatform/test/__debug/test-modeler.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/signalr/test/__debug/go-tester-pre.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/signalr/test/__debug/go-tester.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/signalr/test/__debug/test-modeler-pre.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/signalr/test/__debug/test-modeler.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.json
- tools/sdk-testgen/packages/autorest.testmodeler/CHANGELOG.md
- tools/sdk-testgen/packages/autorest.testmodeler/README.md
- tools/sdk-testgen/packages/autorest.testmodeler/package.json
- tools/sdk-testgen/packages/autorest.testmodeler/src/common/constant.ts
- tools/sdk-testgen/packages/autorest.testmodeler/src/core/model.ts
- tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/appplatform/model/__debug/test-modeler.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/signalr/model/__debug/test-modeler.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/testAutorest.ts
the field is designed for .Net test generation
> [sdk-testgen] add armTemplatePayloadString in testmodeler

- doc/engsys_resource_management.md
Documentation follow-up for some of the additions made in https://github.com/Azure/azure-sdk-tools/pull/2847
> Add github alias rules to resource management guidelines

- eng/common/scripts/Update-DocsMsToc.ps1
Java toc currently get one package from `Get-Unique`
Fixed the problem on checking all columns. Since the packages with same service name are not that many, the call does not take that many time.
Before fix:
core service only returns 'azure-core'
After fix:
core service returns all core packages, e.g. 'azure-core-okhttp', 'azure-core-test' etc
> Fixed the place having duplicates

- eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
- eng/common/scripts/Helpers/git-helpers.ps1
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1458044&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=c9190431-7417-53a5-3fc1-7c7e026cd79d
Testing pipeline on eng/common changes in lang-repo: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1458809&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76
Testing on no eng/common changes in lang-repo:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1458993&view=logs&j=76992fd1-2312-5fae-7c45-7baba86b87ae
Testing on manually triggers:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1458994&view=results
> Fix the target branch setting and validation

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/src/comments.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
- Add buttons for navigate to next or previous comment in the review page.
- Made Improvements to the comments UI
- Part of resolving https://github.com/Azure/azure-sdk-tools/issues/1205
> Add navigation buttons to next and previous comments

- src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
Improved the overall quality of the APIView code handling templated types.
Issues #2973 #2974 #2976
> Improved C++ Language Service handling of templates and ServiceVersion constants

- eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
- Fix bug in `azuresdkpartnerdrops-to-nugetfeed.yml`
> Update PartnerDropsBlobDestPrefix path

- src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
> Add Help link to APIView

- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/Repositories/PullRequestManager.cs
PR pipelines send request to APIVIew to create a review. APIView should send a link to the generated APIView as response.
> Send link to generated API review to PR pipeline caller

- eng/pipelines/pipeline-generation.yml
New variable group based on the engsys vault instead of the test vault.
> Use updated variable group

- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/util/MiscUtils.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/diagnostics/rules/MavenPackageAndDescriptionDiagnosticRule.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/Diagnostic.java
- src/java/apiview-java-processor/src/test/java/com/azure/tools/apiview/processor/diagnostics/rules/MavenPackageAndDescriptionDiagnosticRuleTests.java
This PR adds tests for the Maven package name and description diagnostic rule.
> Add Tests to Java ApiView

- src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
Update C++ parser version to automatically update all existing C++ reviews using latest parser.
> Update APIView C++ parser version

- eng/pipelines/pipeline-generation-single.yml
- eng/pipelines/pipeline-generation.yml
Validation build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1475164&view=results
> Move pipeline-generation to azsdk pool

- eng/pipelines/notifications.yml
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1475665&view=results
> Move notifications to azsdk pool

- eng/pipelines/githubio-linkcheck.yml
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1475615&view=results
> Move githubio-linkcheck to azsdk pool

- eng/common/TestResources/New-TestResources.ps1
> Support nested service directories for local test resources resource group names

- src/dotnet/APIView/APIView/CodeFileRenderer.cs
- src/dotnet/APIView/APIView/CodeLine.cs
- src/dotnet/APIView/APIView/Model/CodeFileTokenKind.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
- src/dotnet/APIView/apiview_token_gist.json
Server side changes to add new token types for collapsible panel and to generate classes based on these token types. This change is required for swagger API review.
> Server-side changes to support collapsible panel in APIVIew

- eng/pipelines/mirror-repos.yml
- eng/pipelines/tools-repo-versioning.yml
Needed to add autorest.csharp to list of repos to update tags for and while I was in there updated to use our 1ES machine pools on that pipeline and the mirroring pipeline.
> Update machine pool and add autorest.csharp to list

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.RecordEntries/request_with_accept_commas.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
@JoshLove-msft @Mohit-Chakraborty follow-up to our discussion.
Resolves #3060
> [Test-Proxy] Normalize `Parameter` and `Header` values both during matching

- eng/pipelines/templates/stages/apiview-python-ci.yml
- eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
- eng/pipelines/templates/steps/use-python-version.yml
- packages/python-packages/api-stub-generator/ci.yml
New pipeline to build, test and release python apiview parser
> New pipeline to release api-stub-generator to devops feed

- tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
- tools/stress-cluster/cluster/provision.ps1
> Do not rotate SP credential if it already exists when deploying stress clusters

- .azure-pipelines/apiview.yml
Remove python parser paths from from apiview pipeline triggers
> Remove Python APi-stub-generator packaging and CI triggers

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_argtype.py
- packages/python-packages/api-stub-generator/apistub/nodes/_base_node.py
- packages/python-packages/api-stub-generator/apistub/nodes/_variable_node.py
- packages/python-packages/api-stub-generator/tests/function_parsing_test.py
- packages/python-packages/apistubgentest/apistubgentest/__init__.py
- packages/python-packages/apistubgentest/apistubgentest/_client.py
> [Python APIView] Fix typehint parsing issues

- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
- eng/common/pipelines/templates/steps/prepare-pipelines.yml
- eng/pipelines/pipeline-generation.yml
Setting managed variables in generated pipelines will allow us to filter pipelines in telemetry dashboards.
> Update pipeline-generator pipelines to set managed variables in generated pipelines

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
@JoshLove-msft apologies. This PR is apparently a black hole in my short-term memory.
> [Test-Proxy] Allow skip of recording save when hitting `/Record/Stop `

- eng/common/pipelines/templates/steps/credscan.yml
Failed pipeline: https://github.com/Azure/azure-sdk-for-js/pull/21216
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1497101&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=7eee3a58-6120-518b-7fcb-7e943712aa81
The test is based on move the variable out of if condition and check the syntax.
> Fixed to use the right variable syntax

- eng/common/docgeneration/Generate-DocIndex.ps1
Issue: https://github.com/Azure/azure-sdk/issues/3282
Current look:
https://azure.github.io/azure-sdk-for-net/keyvault.html
After change:
> Github io docs sort by client, mgmt, track2, track1

- eng/pipelines/notifications.yml
- eng/pipelines/templates/variables/globals.yml
Testing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1507282&view=logs&s=7e5a62c6-a3ae-5561-387a-bc0babb014af
> Update the notification creator version.

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/hlc/generateMgmt.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
- tools/js-sdk-release-tools/src/llc/utils/generateChangelog.ts
- tools/js-sdk-release-tools/src/utils/addApiViewInfo.ts
1. It can work with latest codegen.
1. add field ​apiViewArtifact​ and ​language​ to generateOutput.json for apiview integration.
> add apiview info and adapt tool to latest codegen

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/src/api.ts
- src/dotnet/APIView/APIViewWeb/Client/src/review.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
- Allow the line details section sto accomodate more features.
- Add UI features for collapsing/expanding code sections.
> Restructure line details section to accomodate more features

- eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
- packages/python-packages/api-stub-generator/ci.yml
- tools/pylint-extensions/pylint-guidelines-checker/README.md
- tools/pylint-extensions/pylint-guidelines-checker/ci.yml
- tools/pylint-extensions/pylint-guidelines-checker/dev_requirements.txt
- tools/pylint-extensions/pylint-guidelines-checker/pylint_guidelines_checker.py
- tools/pylint-extensions/pylint-guidelines-checker/setup.py
- tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/__init__.py
- tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/api_version_checker_acceptable_class.py
- tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/api_version_checker_acceptable_init.py
- tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/api_version_checker_violation.py
- tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/copyright_header_acceptable.py
- tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/copyright_header_violation.py
- tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/enum_checker_acceptable.py
- tools/pylint-extensions/pylint-guidelines-checker/tests/test_files/enum_checker_violation.py
- tools/pylint-extensions/pylint-guidelines-checker/tests/test_pylint_custom_plugins.py
@tjprescott just FYI
Can you please try using the external package (instead of the inserted into path as seen in `rcfile` usage?)
> Moving Pylint guidelines checker from sdk-for-python to here

- tools/pylint-extensions/pylint-guidelines-checker/setup.py
To reflect the updates from @l0lawrence
> [pylint-custom-plugin] Bump Version

- tools/pylint-extensions/pylint-guidelines-checker/pylint_guidelines_checker.py
... to remain consistent with other checkers
> [pylint] Fixing pylint warning format 

- src/go/go.mod
- tools/js-sdk-release-tools/package.json
- Update dependencies flagged by component governance
> Fix component governance issues

- tools/http-fault-injector/README.md
- Add "--prerelease" to install command
- Update path to .NET sample
> [http-fault-injector] Update README

- eng/common/scripts/get-codeowners.ps1
Update the tool version to the latest.
> Update the get-codeowner tool to the latest

- NuGet.Config
- eng/pipelines/templates/variables/globals.yml
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
- tools/keyvault-mock-attestation/Dockerfile
- tools/stress-cluster/chaos/examples/network-stress-example/Dockerfile
Testing pipeline: 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1546448&view=logs&j=6d7966cd-0423-5022-78e0-a1ae4dd99f62&t=6d7966cd-0423-5022-78e0-a1ae4dd99f62
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1546396&view=results
Fixed the security step.
> Fixed the security supply chain warnings for tools repo

- tools/mock-service-host/package.json
> Fix issues raised by Component Governance

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- Resolves https://github.com/Azure/azure-sdk-tools/issues/3082
- Duplicate https://github.com/Azure/azure-sdk-tools/issues/2815
> Fix Issues of CodeLines Hiding Under the Navigation Bar

- tools/sdk-testgen/packages/autorest.gotest/doc/gotest_howto.md
This document mainly focuses on the usage of @autorest/gotest. It will show step by step the auto generation of examples/mock tests/scenario tests/samples for Azure SDK for Go.
Resolve: https://github.com/Azure/azure-sdk-tools/issues/3314
> doc: how to use gotest

- tools/test-proxy/sample-clients/net/http-client/README.md
- tools/test-proxy/sample-clients/net/http-pipeline/README.md
- tools/test-proxy/sample-clients/net/storage-blob/README.md
- tools/test-proxy/sample-clients/python/pytest-httpsresponse/README.md
> Update Test Proxy Sample Client Readmes

- tools/test-proxy/sample-clients/net/http-pipeline/README.md
- tools/test-proxy/sample-clients/net/storage-blob/README.md
We put the addendum about environment variable setting in the wrong readme.
> [Test-Proxy] Update Blob Client Sample Readme

- tools/mock-service-host/npm-shrinkwrap.json
- tools/mock-service-host/package.json
- tools/sdk-generation-pipeline/common/config/rush/pnpm-lock.yaml
- tools/sdk-generation-pipeline/packages/sdk-generation-cli/package.json
- tools/sdk-generation-pipeline/packages/sdk-generation-lib/package.json
Fix Component Governance Issues
> Bug fix/cg issues

- tools/stress-cluster/cluster/README.md
Testing auto-merge and check enforcer with an innocent change.
> Simple readme update test

- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
> Remove unused import

- eng/scripts/live-test-resource-cleanup.ps1
We are seeing occasional timeouts during login against the china cloud ([for example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1620537&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=71b47ba2-822c-5669-3297-76bbc5d002b7)).
Attempting to bump the retry count as a workaround to alleviate service side issues.
> Bump retry count on test resource script login

- eng/pipelines/mirror-repos.yml
Until @jiasli can fix this syncing removing azure-cli-pr from sync
> Remove azure-cli-pr mirroring

- .github/workflows/label-to-project.yml
- eng/label-to-project.config
- eng/scripts/Add-IssueToProject.ps1
- eng/scripts/Add-IssuesWithLabelToProject.ps1
- eng/scripts/Github-Project-Helpers.ps1
This github workflow will add issues to projects when a particular label is applied. It will also remove it from the project when the label is removed.
> Add label-to-project workflow

- eng/scripts/live-test-resource-cleanup.ps1
Addressing comment https://github.com/Azure/azure-sdk-tools/pull/3405#discussion_r891369015
> Remove backoff in live test cleanup retry

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/src/comments.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadPartial.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewsPartial.cshtml
- Fixes issues flagged by Microsoft Accessibility Tools Fast Pass.
> Resolve Accesibility issues

- packages/python-packages/api-stub-generator/CHANGELOG.md
- packages/python-packages/api-stub-generator/apistub/_version.py
- packages/python-packages/api-stub-generator/apistub/nodes/_function_node.py
- packages/python-packages/apistubgentest/apistubgentest/_client.py
Fix #3409.
https://apiview.dev/Assemblies/Review/bbbec19e047147beb7ef96cb75d49027#apistubgentest.models.SomethingWithOverloads
Scroll down and see the individual comments on each line of the overloads.
> [Python APIView] Fix overload comment bug

- eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
- Add flag for skipping Component Governance steps
> Disable CG Check for Partner Release Pipelines

- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- Bug in cosmos query leading to internal server errors
> Fix Bug in Cosmos Query

- eng/common/scripts/Verify-Resource-Ref.ps1
- Fix bug in [eng/common/scripts/Verify-Resource-Ref.ps1](https://github.com/Azure/azure-sdk-tools/compare/main...chidozieononiwu:bugFix/ResourceRefVerifier?expand=1#diff-cc0dada0b261e5b5d0bd53f105529131abf0e67052ba76c3ef983c6bdeef644e)
> Fix Bug in Resource Ref Verifier

- eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
- Publish to Pipeline Artifact Rather that Blob Storage
> Publish Signed Packages for Partner Release

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
InitialRAMPercentage and MaxRAMPercentage are expected to be floating point numbers.
> Fix heap params format.

- tools/mock-service-host/CHANGELOG.md
- tools/mock-service-host/ci.yml
- tools/mock-service-host/jest.config.js
- tools/mock-service-host/npm-shrinkwrap.json
- tools/mock-service-host/package.json
- tools/mock-service-host/src/mid/coordinator.ts
- tools/mock-service-host/src/mid/oav/mocker.ts
- tools/mock-service-host/src/mid/oav/swaggerMocker.ts
- tools/mock-service-host/src/mid/responser.ts
- tools/mock-service-host/test/unittest/__snapshots__/testMock.ts.snap
- tools/mock-service-host/test/unittest/__snapshots__/testcoordinator.ts.snap
- tools/mock-service-host/test/unittest/testMock.ts
- tools/mock-service-host/test/unittest/testcoordinator.ts
- tools/mock-service-host/testSequencer.js
1. fix a bug for failed to set `status: Succeeded` for lro-callback GET.
2.  find resource type with pattern"/providers/microsoft.xxx", (originally with pattern "microsoft.xxx" )
Part of efforts to fixes https://github.com/Azure/autorest.csharp/issues/2226
> [mock-service-host] fix lro status

- eng/pipelines/templates/jobs/stress-test-release.yml
- tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
- tools/stress-cluster/chaos/examples/network-stress-example/Chart.yaml
- tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
- tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.yaml
- tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
- tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.yaml
- tools/stress-cluster/ci.yml
- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
- tools/stress-cluster/cluster/provision.ps1
Updating CI to match changes in https://github.com/Azure/azure-sdk-tools/pull/3491
> Deploy stress CI to pg environment

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
Related Java PR:
https://github.com/Azure/azure-sdk-for-java/pull/29770
Run:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1682090&view=results
> Java Core perf tests.

- tools/sdk-testgen/common/changes/@autorest/testmodeler/20220705-securitydefinition_2022-07-05-05-14.json
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/appplatform/armappplatform/__debug/go-tester-pre.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/appplatform/armappplatform/__debug/go-tester.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/appplatform/armappplatform/__debug/test-modeler-pre.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/appplatform/armappplatform/__debug/test-modeler.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/compute/armcompute/cloudservices_client_example_test.go
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/compute/armcompute/cloudservicesupdatedomain_client_example_test.go
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/compute/armcompute/mock_test.go
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/machinelearningservices/armmachinelearningservices/__debug/test-modeler-pre.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/signalr/armsignalr/__debug/go-tester-pre.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/signalr/armsignalr/__debug/go-tester.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/signalr/armsignalr/__debug/test-modeler-pre.yaml
- tools/sdk-testgen/packages/autorest.gotest/test/integrationtest/output/signalr/armsignalr/__debug/test-modeler.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/README.md
- tools/sdk-testgen/packages/autorest.testmodeler/src/core/model.ts
- tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/appplatform/model/__debug/test-modeler-pre.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/appplatform/model/__debug/test-modeler.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/compute/model/__debug/test-modeler-pre.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/signalr/model/__debug/test-modeler-pre.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/test/integrationtest/output/signalr/model/__debug/test-modeler.yaml
- tools/sdk-testgen/swagger/specification/signalr/resource-manager/Microsoft.SignalRService/preview/2021-06-01-preview/examples/SignalR_CheckNameAvailability.json
- tools/sdk-testgen/swagger/specification/signalr/resource-manager/Microsoft.SignalRService/preview/2021-06-01-preview/signalr.json
Add securityParameters in ExampleModel for ApiKey securityDefinitions.
> [testmodeler] support api key as securityParameters

- eng/common/pipelines/templates/steps/validate-filename.yml
Resolve: https://github.com/Azure/azure-sdk-tools/issues/3109
Testing pipeline without dup: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1690159&view=logs&j=80f7b2d8-9c8c-53b8-36c5-63dcddd43cb4&t=871345b3-a9f0-5330-c181-158984948211
Testing pipeline with dup:  https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1686575&view=logs&j=80f7b2d8-9c8c-53b8-36c5-63dcddd43cb4&t=871345b3-a9f0-5330-c181-158984948211
> Do not allow check in the files only differ in case

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
- Required to run new perf tests on latest preview packages
> [Perf] Add azure-storage-blob-cryptography package

- tools/test-proxy/sample-clients/net/storage-blob/Program.cs
… so http will work properly if the user changes it
> [TestProxy] Update Sample TestProxyTransport in StorageBlobSample

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
- LineClass is null in some cases
> Fix bug in CodeLines

- eng/common/scripts/Update-DocsMsMetadata.ps1
> Update casing for 'verison'

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
Add upload and download file to the mix.
Test run
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1726219&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=1c1d21ee-87c3-56e5-9bff-a84d921988f6
related https://github.com/Azure/azure-sdk-for-java/pull/30088
> Add upload/download file blobs.

- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
Need this version change in APIView to auto upgrade all existing revies to use latest pylint  guidelines checker 0.0.5
> Update python version to 0.3.2

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts
- tools/js-sdk-release-tools/src/hlc/generateMgmt.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
- tools/js-sdk-release-tools/src/utils/git.ts
- tools/js-sdk-release-tools/src/utils/logger.ts
Mgmt:
- validate output folder
- validate package name
- add install instructions
Besides the change, the pr adds a new function to skip generating codes, which will be used in powerapp grow up story.
> Enhance sdk automation

- eng/common/pipelines/templates/steps/sparse-checkout.yml
Reverts Azure/azure-sdk-tools#3661
This is causing issues with the publish to nightly docs step. Reverting until I can work on a fix.
> Revert "Add full clone fallback to sparse checkout"

- src/dotnet/APIView/APIViewWeb/Client/src/reviews.ts
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
**Improvements to APIView search allowing**
package: *Exact match search against PackageName*
author: *Exact match search against Author*
service: *Exact match search against ServiceName*
pr: *Exact match search against Pull Request Number*
name: *Search against Revision Name*
> Improvements to APIView Search

- eng/common/scripts/job-matrix/README.md
- eng/common/scripts/job-matrix/samples/matrix.json
- eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
- eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
- eng/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
Resolve https://github.com/Azure/azure-sdk-tools/issues/3715
Tracking issue: https://github.com/actions/virtual-environments/issues/5583
> Bump MacOs version to macos-11

- eng/pipelines/templates/steps/apiview-review-gen.yml
- eng/scripts/Apiview-Update-Generated-Review.ps1
Added a new script file to send request to API view once code file is generated by pipeline. This change avoids having inline-script in yaml that makes it easy to integrate.
> Update sandboxing pipeline to send request to APIView

- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
> Fix issue when uploading json file to APIView

- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
> Fetch all reviews when running background tasks

- .azure-pipelines/apiview.yml
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosReviewRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/ReviewManager.cs
Hotfix to deploy to APIView server to auto upgrade all existing reviews to 0.3.3
> Cherry pick python fix and review upgrade on top of current deployment

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
Update Markdig to latest version
> Update Markdig version

- eng/pipelines/apiview-review-gen-javascript.yml
- eng/scripts/Create-Apiview-Token-Javascript.ps1
Sandboxing changes to process manual API reviews for JS.
Fixes: #3925
> Sandboxing: Pipeline to covert manual JS reviews to code file

- src/dotnet/APIView/APIViewWeb/Client/src/navbar.ts
- src/dotnet/APIView/APIViewWeb/Client/src/review.ts
- src/dotnet/APIView/APIViewWeb/Client/webpack.config.js
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/ReviewLayout.cshtml
> Remove Duplicate Event Listener Code

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_Layout.cshtml
Working off the new theme system in place to add an alternative solarized dark theme that looks similar to IntelliJ.
> Adding Solarized Dark theme

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/Azure.Sdk.Tools.PerfAutomation.Tests.csproj
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/JavaTests.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/stdout/java.txt
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
> [Perf] Extract Java runtime package versions

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitStoreTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationResetTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationRestoreTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
This contains the changes necessary for the Integration push tests.
> Initial changes for push tests

- CONTRIBUTING.md
- doc/development/powershell.md
> Add powershell coding guidelines

- eng/pipelines/merge-docs-main-to-live.yml
- eng/scripts/create-tag-for-current-branch.ps1
- eng/scripts/sync-base-branch-to-target.ps1
- eng/scripts/validate-changes-on-allowed-path.ps1
The issue is to resolve https://github.com/Azure/azure-sdk-tools/issues/3980
Testing pipeline (sima-zhu fork) with validation: 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1836051&view=logs&j=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f
Skip validation: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1835915&view=logs&j=196c4937-6990-58b5-7d18-234ac2f0888b&t=bbb6a4ac-bf68-5196-5d2e-62c25cade418
The pipeline current designed to merge main branch on top of live branch, as totally replace live with main will break the OPS trigger.
Pending work:
1. Have some tests?
2. ~~Move the allowlist?~~
> Merge main to live automation pipeline.

- tools/stress-cluster/cluster/azure/cluster/cluster.bicep
This will be enforced soon. My plan is to deploy this to playground and understand the impact, then roll it out to our prod CI cluster.
> [stress testing] Enable azure policy for stress clusters

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Cpp.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/ILanguage.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/JavaScript.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/LanguageBase.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Net.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Python.cs
> [Perf] [Python] Only run "pip install -e ." for primaryPackage

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/src/comments.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
- Fix navigation between comment. (Skip resolved and hidden comment threads during navigation).
- Add comment icon shown when comments are hidden
- Should resolve https://github.com/Azure/azure-sdk-tools/issues/3470
> Bug fix/issues in comments

- src/dotnet/APIView/APIViewWeb/Repositories/CosmosPullRequestsRepository.cs
Verify Review status to fetch only pull request models for open reviews to avoid having duplicate links on GitHub comment.
Bot finds multiple entries in pull request model table but only one of them is linked to open reviews and rest all are linked to closed reviews.
Unfortunately cosmos DB doesn't allow join across two containers.
> Fetch pull request model for reviews in open state

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/src/comments.ts
- src/dotnet/APIView/APIViewWeb/Client/src/review.ts
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentThreadInnerPartial.cshtml
- Fix dotnet branding. https://github.com/Azure/azure-sdk-tools/issues/3487
- Add button for finding first comment. https://github.com/Azure/azure-sdk-tools/issues/4085
- Independent scrollbars between left and right review pane. https://github.com/Azure/azure-sdk-tools/issues/3639, https://github.com/Azure/azure-sdk-tools/issues/3410
- Improve Show Documentation Button. https://github.com/Azure/azure-sdk-tools/issues/4195
> Bug fix/miscellaneous improvements

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
Removing merge conflict that was left in tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
> Fix YAML merge conflict

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
Reverts Azure/azure-sdk-tools#4219
> Revert "Fix YAML merge conflict"

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml
This reverts commit 21890c9a6d707f5cecab2e13cba82df8d70cd233.
> Revert "Adding usage samples feature into APIView "

- tools/stress-cluster/cluster/azure/cluster/cluster.bicep
- tools/stress-cluster/cluster/azure/parameters/pg.json
- tools/stress-cluster/cluster/azure/parameters/prod.json
- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.lock
- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
- tools/stress-cluster/cluster/provision.ps1
- Upgrade stress cluster versions and tags
> Upgrade stress cluster versions and tags

- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiParser.csproj
Updated swagger APIView parser version
> Update Swagger Parser version

- .azure-pipelines/apiview.yml
> Fix pathto apiview test script

- tools/test-proxy/transition-scripts/generate-assets-json.ps1
The regular expression was broken but even with the syntax error fixed the match wasn't correct. Fix the Regex, update the comments to include the regex101 playground link.
> Fix broken regular expression

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Languages/JavaLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/XmlLanguageService.cs
- src/java/apiview-java-processor/pom.xml
Upgrade Java APIView parser version
> Upgrade Java parser version

- tools/github/Add-AzsdkMilestones.ps1
- tools/github/Add-AzsdkProjectIssues.ps1
Added scripts I created for specific use to general, shared repo.
Original sources:
- https://gist.github.com/heaths/8d83624cf358d23abdbbf429148ed633
- https://gist.github.com/heaths/cdcece1dbb892cf7feb3b455886960b9
> Add useful GitHub scripts

- tools/identity-resolution/Helpers/GitHubToAADConverter.cs
open source management update their audience scope.
The PR is to update our field accordingly.
Testing in Postman the new audience field works.
> Update the new audience scope.

- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
If comment thread does not have any comments then review link is not loading. This is possible if we create and delete comment,
> Handle all comments resolved scenario

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
Change the call from IsNullOrEmpty to IssNullOrWhiteSpace.
> Change call to IsNullOrWhiteSpace

- src/dotnet/APIView/APIViewWeb/Client/src/review.ts
Navigation node in left side panel cannot be expanded once it's collapsed
> fix navigation collapsible issue

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
Instead of the new Tag being the TagPrefix+GUID, grab the first 10 character of the commit SHA and use that instead of the GUID. The new Tag will be TagPrefix + _<First 10 digits of the commit SHA>.
Resolves #4299
> Change Tag from GUID to commit SHA

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
- tools/test-proxy/transition-scripts/README.md
Add a readme for the transition script which explains how to use it and what it does.
> Add readme for integration script

- tools/stress-cluster/chaos/README.md
- tools/stress-cluster/chaos/examples/stress-deployment-example/templates/deploy-job.yaml
- tools/stress-cluster/services/Stress.Watcher/src/PodEventHandler.cs
- tools/stress-cluster/services/Stress.Watcher/src/Program.cs
- tools/stress-cluster/services/Stress.Watcher/tests/PodEventHandlerTest.cs
> Add Skip.RemoveTestResources label support to stress watcher

- .azure-pipelines/apiview.yml
- src/dotnet/APIView/APIViewWeb/Startup.cs
- Prevent test authentication from activating in Staging.
> Update Test Authentication Scheme

- src/dotnet/APIView/APIViewWeb/TagHelpers/AvatarTagHelper.cs
- Download the exact size of avatar needed for comments, to improve page load.
> Download small size Github avartar

- src/dotnet/APIView/APIViewWeb/Client/css/site.scss
- src/dotnet/APIView/APIViewWeb/Client/css/usageSample.scss
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Samples.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_CommentFormPartial.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewBadge.cshtml
- Remove Multiple Scrollbars.
- Add Command Bar to Conversation, Revision, and Usage Sample Pages.
- Switch to Circle Button for Adding Samples.
- Adjust Resolution Checkbox.
> Recent features/UI improvements

- eng/common/scripts/get-codeowners.ps1
- eng/pipelines/templates/variables/globals.yml
docs.ms version update: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1910861&view=results
pipeline notification update: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1913635&view=results
pipeline owner extraction: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1913637&view=results
> Bump the code owner retriver version.

- tools/apiview/emitters/cadl-apiview/CHANGELOG.md
- tools/apiview/emitters/cadl-apiview/package.json
- tools/apiview/emitters/cadl-apiview/src/emitter.ts
- tools/apiview/emitters/cadl-apiview/src/lib.ts
- tools/apiview/emitters/cadl-apiview/src/version.ts
- tools/apiview/emitters/cadl-apiview/test/apiview.test.ts
> [Cadl APIView] Support --output-dir and compiler-level noEmit

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/stdout/js.txt
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/JavaScript.cs
- Improve regex to match first package on line
- Prevents matching packages under pnpm folders
> [Perf] Improve JS runtime package detection
