Azure/azure-sdk-tools

- .github/CODEOWNERS
@jsquire removed this directory with https://github.com/Azure/azure-sdk-tools/pull/7777 so making codeowners update as well given the linting pipeline failed for it last night https://dev.azure.com/azure-sdk/public/_build/results?buildId=3542559&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=259e4be2-1fd3-5c65-f373-9da11bbaf3b4&l=23
> Remove github-issues from CODEOWNERS

- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Azure.Sdk.Tools.HttpFaultInjector.csproj
- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/FaultInjectingMiddleware.cs
- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Program.cs
- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Utils.cs
- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/appsettings.json
Fixes some issues:
1. Allows to pass `urls` in cmd line to ASP.NET Core (`settings.IgnoreUnknownArguments = true;`)
2. Allows to use appsettings.json when fault-injector runs as global CLI (`ContentRootPath = Directory.GetParent(Assembly.GetExecutingAssembly().Location)?.FullName`), stolen from https://github.com/dotnet/sdk/issues/9730#issuecomment-1279845747
3. Fixes exception when request without body is being proxied (`if (Utils.HasBody(request))`)
> Fault-injector: yet another port fix, also make bodyless requests work again

- doc/common/matrix_generator.md
- eng/common-tests/matrix-generator/tests/job-matrix-functions.modification.tests.ps1
- eng/common-tests/matrix-generator/tests/job-matrix-functions.tests.ps1
- eng/common/scripts/job-matrix/job-matrix-functions.ps1
_sorry for all the formatting updates, vscode got more opinionated this time and I don't want to fight it_
This adds the ability to reference environment variables to be resolved at runtime for matrix values, for example:
```
"matrix": {
"foo": "env:bar"
}
```
The primary use case is so we can reference common values like `LinuxPool` that we define as top level variables in an azure pipelines context, so we don't need to repetitively hardcode them in all the matrix configs like we do today.
> Support resolving environment variable references in matrix config

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
This update to the event processor is due to changes in the following [PR](https://github.com/Azure/azure-sdk-tools/pull/7794).
> Update github-event-processor ver to 1.0.0-dev.20240229.2

- tools/github/data/common-labels.csv
The focus of these changes is to add a new label for the "Defender EASM" service.
> [GitHub] Add ESAM label

- eng/pipelines/mirror-repos.yml
cspell.json file gets edited often enough on both public and private and causes conflicts which we currently have just been overwriting with the changes on the public side. This has cause a few issues so instead I'm going to stop auto-syncing this file and so folks might need to make similar changes on both  sides similar to spec changes.
> Exclude cspell.json from auto-sync

- eng/common/scripts/job-matrix/job-matrix-functions.ps1
Some null handling differences are causing pipeline tests to fail.
> Fix matrix CI tests

- .github/workflows/scheduled-event-processor.yml
There was an error in the yml file, setting up the payload for EnforceMaxLifeOfIssues. Also, we wanted to run this at 10am PST, and the cron is UTC which had to be modified.
> Fix EnforceMaxLifeOfIssues event and run time

- tools/github-event-processor/YmlAndConfigFiles/scheduled-event-processor.yml
- tools/github-event-processor/ci.yml
The sample yml file for the scheduled events was old and used the old, and incorrect, way to create the payload file. The change to use `cat` to create a payload file instead of the environment variable was made last year.
I'm also adding excludes to the ci.yml to exclude to YmlAndConfigFiles directory as well as markdown files in the root. Changes only to the samples and/or markdown files shouldn't cause a built and publish of the event processor.
> Update sample yml

- eng/common/pipelines/templates/jobs/generate-job-matrix.yml
- eng/common/pipelines/templates/steps/publish-1es-artifact.yml
- eng/common/pipelines/templates/steps/publish-artifact.yml
Adding these files as separate copies of their originals so we can do a rollout more easily.
1. Update `archetype-sdk-tests-generate.yml` to `generate-job-matrix.yml`. Changes to this file include generating a matrix with corresponding env vars for OS pools/agents, and passing in the now required `OSName` parameter which cannot be set as a variable for the 1es templates.
2. Moving `publish-artifact.yml` to `publish-1es-artifact.yml` to use the 1es publishing wrapper task. I don't think this task is available in a backwards compatible way without the repo reference and/or onboarding we're having to do, see https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3503459&view=logs&j=96791242-dbf3-587e-3a06-ae5af5c1a705&t=8e5c4a57-b21e-59c3-59e8-95279bb1be65&l=16 for example.
> Add 1es changes for job/matrix generation and publish

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
Update package version on API revision even if API surface matches to reflect correct package version info. This change along with tagging a revision after package release will ensure that package version is updated correctly(A separate change from updating package version).
> Update package version on automatic API revision

- eng/pipelines/devops-create-package-workitem.yml
This will fix one of the issues which was the wrong case of the package type. 
We should however not reenable this pipeline until we can get a correct repo path as well.
> Fix package type in pipeline

- tools/github/data/common-labels.csv
The focus of these changes is to a new service label for `Code Signing` to the common label set in support of the client library under development.
> [GitHub] Add Code Signing service label

- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/MockGitHubEventClient.cs
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/ScheduledEventProcessingTests.cs
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Constants/RateLimitConstants.cs
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/ScheduledEventProcessing.cs
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs
The new rule, EnforceMaxLifeOfIssues, creates a comment, closes and locks issues. As it turns out, when the rule first ran in azure-sdk-for-net, it was there were several hundred issues that matched the criteria. When the rule started processing this backlog, it hit a SecondaryRateLimitExceededException while creating comments due to the fact it tried to update more than 80 in a 60 second period. Theoretically, can happen with any API that "creates content" which includes creating comments, closing and locking. _Though we already know that locking 1000 issues never hits this._ The reason we've never previously seen this is that the existing Scheduled events is because those events are all caught up and just processing a small handful if they process anything at all.
While the per-minute …
> Scheduled event processing update

- eng/common/scripts/Test-SampleMetadata.ps1
Based on offline discussion, we believe `dotnet-api` is the best product slug for System.ClientModel samples added in https://github.com/Azure/azure-sdk-for-net/pull/42369.
This is because the [BinaryData](https://learn.microsoft.com/en-us/dotnet/api/system.binarydata?view=dotnet-plat-ext-8.0) type, also in the `System.` namespace uses the `ms.service=dotnet-api` and `ms.subservice=system`.  These were identified as well in the [msprod docs metadata-taxonomies](https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies?branch=main#msprod).
> Add dotnet-api product slug to sample metadata script

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
Add new option param to get review status for a given package version. If exact match is not for input version, then check will look for latest matching revision with same major and minor version number. If there is still no match then it will return latest automatic API review revision status.
> Get api review approval status for a given package version

- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/IssueProcessingTests.cs
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/IssueProcessing.cs
This enables the new InitialIssueTriage Rule, that uses AzureSdkOwners, in preparation for enabling the rule on 03/11/2024.
This PR swaps the old rule with the rule and enables the tests that were updated for the new rule. Getting this merged today will allow the new version to be published to the dev feed so the only change necessary on Monday will be updating the version in the workflow yml files.
> Enable the new InitialIssueTriage Rule that uses AzureSdkOwners

- src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/ReviewListModels.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
Server-side changes to tag a revision as released.
> APIView server changes to tag a revision as released

- eng/common/scripts/Prepare-Release.ps1
In the case there is exactly one previous release PS will return the single object and thus the Count property will not exist. Instead this change ensures that we always have a list.
> Update Prepare-Release.ps1 to handle only one previous release

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
This change will NOT be merged or pushed out to the repositories until Monday, 03/11/2024.
The first update is to update the github-event-processor version which includes the new InitialIssueTriage rule that uses the AzureSdkOwners.
The second update is to the cron for EnforceMaxLifeOfIssues. Instead of running on just Mondays at 10am PST, it'll run on Monday, Wednesday and Friday. The reason for this for this is explained in the [PR](https://github.com/Azure/azure-sdk-tools/pull/7839) with the changes.
> Update github-event-processor version

- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/IssueProcessing.cs
This [Issue in azure-sdk-for-java](https://github.com/Azure/azure-sdk-for-java/issues/39154) was processed using the new InitialIssueTriage rule and incorrectly had needs-team-triage added to it.
needs-team-triage should only be added in the case of no AzureSdkOwners and no ServiceOwners and is correctly done in that case but there looks to be a stray call to `gitHubEventClient.AddLabel(TriageLabelConstants.NeedsTeamTriage);` which was after the check to see if needs-team-attention was being added.
> Initial Issue Triage was adding needs-team-triage incorrectly

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
Update GitHubEventProcessor to 20240311.2 for the following [fix](https://github.com/Azure/azure-sdk-tools/pull/7852).
> Update GitHubEventProcessor to 20240311.2

- eng/common-tests/matrix-generator/tests/job-matrix-functions.modification.tests.ps1
- eng/common-tests/matrix-generator/tests/test-import-matrix-env.json
- eng/common/scripts/job-matrix/job-matrix-functions.ps1
Matrix filters are intended to work against the environment variable key, not the resolved value. There is a bug where resolve environment variables on an imported matrix, before processing any matrix filters passed in from the top level. This PR changes import behavior to skip env var lookup until after the imported matrix has been combined with the parent matrix.
> Skip env processing on matrix import step

- src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- Update Contributing Document
> Add CosmosDBName to documented config settings

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
> Add an additional timeout handler for mac-errors

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
- src/dotnet/APIView/APIViewWeb/Startup.cs
- Reverts some of the changes introduced in https://github.com/Azure/azure-sdk-tools/pull/7807
- HTML Minification improves performance but introduces some other issues in the codelines.
- Ultimately, we need to resolve performance issues by reducing DOM size via lazy loading
> Revert HTML Minification Changes

- packages/python-packages/tox-monorepo/README.md
- packages/python-packages/tox-monorepo/setup.py
- packages/python-packages/tox-monorepo/tox_monorepo/version.py
And associated docs, per issue #4917
> Deprecate `tox-monorepo`

- eng/common/pipelines/templates/steps/create-apireview.yml
- eng/common/scripts/Create-APIReview.ps1
- eng/common/scripts/Helpers/ApiView-Helpers.ps1
Send a new param in request to APIView to tag a revision as released.
> Create api review script changes to add a param to set release tag

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/OptionsGenerator.cs
I noticed using `-U` alias of `--universalOutput` would erroneously activate the config dump, not universal output.
> Fix issue with universal output short form clobbering the dump option

- tools/stress-cluster/services/otelcollector/Dockerfile
- tools/stress-cluster/services/otelcollector/README.md
- tools/stress-cluster/services/otelcollector/localtest.sh
- tools/stress-cluster/services/otelcollector/otel-builder.yml
- tools/stress-cluster/services/otelcollector/otel-collector-config.yml
- tools/stress-cluster/services/otelcollector/startup.sh
Build our own custom otel distribution using their official `otb` tool.
It reduces the amount of code significantly by cutting it down to azure monitor and removing all other contrib components. As a bonus we can also control the Docker images used, which is helpful for other things.
> Stress: build our own custom otel collector

- tools/tsp-client/README.md
- tools/tsp-client/src/index.ts
- tools/tsp-client/src/log.ts
- tools/tsp-client/src/options.ts
Facilitate generating an `emitter-package-lock.json` file from an `emitter-package.json` for the language repositories. 
Fixes: https://github.com/Azure/azure-sdk-tools/issues/7691
> [tsp-client] Support generating a lock file from emitter-package.json

- eng/containers/ci.yml
- eng/pipelines/mirror-container-images.yml
- eng/pipelines/publish-docker-image-isolated.yml
- eng/pipelines/publish-docker-image.yml
- eng/pipelines/templates/stages/1es-redirect.yml
- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
- eng/pipelines/templates/variables/image.yml
- tools/http-fault-injector/ci.yml
Migrates the docker publish pipelines and the dotnet tool pipeline to 1es pipeline templates. Also includes base 1es-redirect.yml and image.yml files that will be foundational for further migrations. This PR depends on an update to azure-sdk-build-tools which I will merge and update the tag for before completing this PR.
> Migrate image and dotnet tool publish to 1es pipelines

- eng/pipelines/templates/stages/1es-redirect.yml
- eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
- eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
- eng/pipelines/templates/variables/image.yml
- tools/apiview/emitters/typespec-apiview/ci.yml
- tools/apiview/parsers/js-api-parser/ci.yml
- tools/tsp-client/build-tsp-client.yml
- tools/tsp-client/ci.yml
Additional update: only auth to ACR on internal builds (not sure if this is necessary but just in case)
Pipelines:
tools - apiview-stub-generator
tools - apiview-typespec-emitter
tools - azure-pylint-guidelines-checker
tools - js - apiview-parser
tools - swaggerapiparser
tools - tsp-client
> Migrate more tools pipelines to 1es pipeline templates

- tools/apiview/emitters/typespec-apiview/CHANGELOG.md
- tools/apiview/emitters/typespec-apiview/package-lock.json
- tools/apiview/emitters/typespec-apiview/package.json
- tools/apiview/emitters/typespec-apiview/src/apiview.ts
- tools/apiview/emitters/typespec-apiview/src/version.ts
- tools/apiview/emitters/typespec-apiview/test/apiview.test.ts
Fixes: https://github.com/Azure/azure-sdk-tools/issues/7930
Also, ensures that future failures will say the name of the case, rather than the number.
> Support templated strings in APIView

- src/dotnet/APIView/APIView/Properties/launchSettings.json
- src/dotnet/APIView/APIViewWeb/Helpers/PageModelHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/ReviewRevisionPageModels.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Samples.cshtml
Changed "Conversiations" to "Conversations" 
Changed "Revisons" to "Revisions"
Changed onclick display for "Conversations" tooltip from "API" to "Conversations"
> Fixed spelling and click display errors in sidebar

- tools/assets-automation/asset-sync/README.md
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
- tools/test-proxy/documentation/asset-sync/README.md
1. Notification that the proxy is retrying a git clone
2. Further removal of docs referring to `docker`
3. Added section in `asset-sync` readme to talk about fresh `assets.json` creation per discussions I had with @richardpark-msft
> Test-Proxy Documentation updates

- eng/common/scripts/Update-DocsMsMetadata.ps1
The GetDocsMsDevLanguageSpecificPackageInfoFn pointer was only being called if the DevVersion was set and should have been being called all the time, if the function pointer was defined. The reason for this is because the only language that had the function defined was Javascript and it only needed to be called if the DevVersion was set. As such, the fix to this file is to call it all the time and, for Javascript, the Get-javascript-DocsMsDevLanguageSpecificPackageInfo, needs to be updated to only process if the DevVersion is set.
> Call GetDocsMsDevLanguageSpecificPackageInfoFn if it's defined

- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.ts
- src/dotnet/APIView/APIViewWeb/LeanModels/ReviewListModels.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
Added "Viewed" slider to mark files as read in APIView.
> Create viewed slider

- eng/common/scripts/Create-APIReview.ps1
Package name approval check is enforced for management plane package also due to a recent bug that got introduced as part of recent script restructure to consolidate language specific script into common script.
This PR has changes to skip package name check for management plane libraries.
> Skip API review package name approval for management plane packages

- eng/common/scripts/Validate-Package.ps1
Java packages contains `group name:` as a prefix in APIView.  API status request should pass full package name including group name when it's present for a language to get correct status.
> Pass Group in request to get package status

- eng/common/scripts/Helpers/git-helpers.ps1
- `git show head:sdk\storage\Azure.Storage.Blob\assets.json` no longer results in visible output.
- The script grabs the tag from the **left** side of the merge, holds it constant, and merges the incoming branch tag _into_ the assets. If we aren't able to properly utilize `git show`, we can't generate the `left` or `right` side of the assets.json, and end up setting the `assets.json` to **empty**.
- `git show head:sdk/storage/Azure.Storage.Blob/assets.json` does still work, so amending the command
> A pshell update (7.4?) caused `git show` to stop working

- eng/common/scripts/Create-APIReview.ps1
Original file path is incorrect in request to APIView when token file is already generated. This will become an issue when attempting to rebuild existing reviews after the parser is upgraded to a newer version. Common script also uses incorrect path to find the token file if artifact name and package name are different. For e.g. JS package name is @azure/core-http and artifact name is azure-core-http. Currently we are looking for file within in the path @azure/core-http instead of azure-core-http.
> Pass valid original artifact file name in request to APIView

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Create-APIReview.ps1
Validation step in pipeline ignores any failures in change log verification but DevOps still report it as error which confuses users to think that pipeline has failed. This change is to suppress error logs when a status object is passed.
> Remove soft errors in validation step from Devops pipeline

- eng/common/pipelines/templates/steps/docker-pull-image.yml
- eng/common/pipelines/templates/steps/update-docsms-metadata.yml
Updates docker pulls from internal ACR to use a different service connection and auth strategy.
Example release pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3662553&view=logs&j=19b87903-f8bc-5cbb-22d9-4f6eb3469d8e&t=789ec5f9-c426-56bf-c6a5-d85b141abeda 
Changes in Java and Python pipelines will require this change: 
* https://github.com/Azure/azure-sdk-for-java/pull/39535
* https://github.com/Azure/azure-sdk-for-python/pull/35048
> Use different service connection and az CLI for ACR auth

- eng/pipelines/templates/steps/produce-net-standalone-packs.yml
This has the knock on effect of fixing the proxy build.
- `produce-net-standalone-packs` only used in archetype-tool-dotnet.yml
- `archetype-tool-dotnet` is an `extends` on top of 1es-redirect.
- Because it's only ever used in 1es context we're safe to swap the artifact publishing.
> Use `publish-1es-artifact` instead of `publish-artifact` in `archetype-tool-dotnet`

- tools/test-proxy/tests.yml
Somehow placing the arguments in a variable is causing maven to not honor it.
[The latest version is actually working in livetest run with these changes](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3666152&view=results).
> Resolve Errrors with test-proxy recorded tests against java repo

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/GitStoreTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
@weshaggard  I'm extremely pleased with this little diff methodology. Let me know what you think.
- This was failing due to a case that should only really ever occur in our test cases, where we _force_ a failed auth by setting an invalid GIT_TOKEN. This meant that we failed to retrieve remote `main` for the patch. The weird error we were seeing on CLI integration for windows, is that a soft reset with _uncommitted changes_ resulted in a weird error state that git couldn't understand how to resolve automatically. (`unable to retrieve promisor remote`) By placing the soft reset behind the changes actually being committed, we totally sidestep the entire problem.
> Merge `eng/` from `main` on assets push

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/utils/changeConfigOfTestAndSample.ts
fix https://github.com/Azure/autorest.typescript/issues/2404
> Fix build error for easm sdk

- eng/scripts/Create-Apiview-Token-Python.ps1
Reverts Azure/azure-sdk-tools#7961
argument is not yet available in published version of python
> Revert "emit cross language definition Id"

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
Handling all the "reset" error messages that we've seen in proxy livetests over the past 14 days.
> Handle Connection Resets

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Validate-Package.ps1
SuppressErrors flag was incorrectly set as true when verifying change log for releases.
> Pass flag to suppress errors correctly when verifying release change log

- src/dotnet/APIView/APIViewWeb/CommentMarkdownExtensions.cs
- src/dotnet/APIView/APIViewWeb/Program.cs
Added logic to open clicked links in new tab in APIView comments.
> Clicking link in comment opens in new tab

- doc/common/TypeSpec-Project-Scripts.md
Removing seemingly deprecated flag from code snippet example.
In order to achieve the same one must pass the `-SaveInputs` flag instead. This is mentioned later in the document, but it might be a good idea to draw more attention to it.
```pwsh
pwsh ..\..\..\eng\common\scripts\TypeSpec-Project-Generate.ps1 -SaveInputs .
```
> Removed `cleanup` flag from code snippet

- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
Adds `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` to the Java command line when running profiling to capture richer profiling details.
> Add debug non-safe points to Java profiling

- tools/secret-management/Azure.Sdk.Tools.SecretManagement.Cli/Commands/StatusCommand.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Configuration/PlanConfiguration.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Configuration/RotationConfiguration.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Core/RotationPlan.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Core/RotationPlanStatus.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Core/RotationState.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Tests/CoreTests/RotationPlanTests.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Tests/TestConfigurations/Valid/random-string.json
- tools/secret-management/schema/1.0.0/plan.json
This change allows for a secret to be in a warning state (should have been rotated previously and is close to expiration) and replaces the state booleans `Expired`, `ThresholdExpired`, and now `WarningExpired` with a single state enum:
```
Error,
UpToDate,
Rotate,
Warning,
Expired,
```
If any secret enters the WarningThreshold, the cli will categorize it as Expiring and the status command will return a non-zero exit code.
The WarningThreshold for plans should be configured so there is reasonable time past the RotationThreshold to allow for rotation and prevent unnecessary warnings.
> Add warning state to rotation

- eng/common/pipelines/templates/steps/policheck.yml
Moving away from SAS tokens for connecting to storage so switching to using a Workload Identity Federation connection to the container to download the needed files.
Test this in the JS repo in PR https://github.com/Azure/azure-sdk-for-js/pull/29284
Tried a few options and the AzurePS option seemed to be the most efficient until AzCopy directly supports this auth mode, tracked by https://github.com/Azure/azure-storage-azcopy/issues/2545
> Use WIF to connect storage container

- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
Changes to authenticate requests to DevOps using managed identity.
> Authenticate requests from APIView to DevOps using managed Identity

- tools/sdk-ai-bots/Embeddings/settings/metadata_customized_docs.json
A follow-up to:
- https://github.com/Azure/azure-rest-api-specs/pull/28464#discussion_r1552415208
Plus remove obsolete `avocado` doc.
> Update metadata_customized_docs.json: add spec dir sturcture, api versions and branches, breaking changes deep dive; remove avocado as it is obsolete

- src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs
Request to get artifact URL is still failing with 404 error. Adding polly retry to get URL.URL is working fine when attempted again.
> Add polly retry to get artifact URL from DevOps

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
Adds `indentedBlock` to handle indenting and unindenting a section of tokens rather than relying on the methods indent and unindent to be called before and after. Also changes indentation handling to be based on the indentation level in case we want to offer different indentation size (right now it's always 4 whitespaces). Lastly, added a cache for common indentation levels so they can be reused.
> Add indentation handling method in Java ApiView tool

- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
- src/java/apiview-java-processor/src/test/java/com/azure/tools/apiview/TestExpectedOutputs.java
Introducing a test framework for Java APIView processor to compare output for published libraries against their known-good representations, to help avoid regrettable regressions. So far there are no tests included - this is just the framework.
> Introducing a test framework for Java APIView processor

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/OptionsGenerator.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
1. Universal option wasn't being properly enabled, so we couldn't run the .NET tests properly
2. After fixing bug from 1), even w/ LogLevel set to 0, having the standard console would output _something_ to stderr, breaking the .NET tests
3. Fix the problem by only including the additional console if universal is set to true
> Universal Output wasn't actually universal

- eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Step to update an existing work item fails with null index error if the package work item is unassigned. 
Error: Cannot index into a null array.
> Handle the failures when package work item is unassigned

- .github/workflows/event-processor.yml
There was a [recent announcement](https://github.com/Azure/login/issues/424) that the default runtime of azure/login is being updated from Node 16 to Note 20 due to the deprecation of Node 16. This is a breaking change and does require an extra variable being added to the step. `enable-AzPSSession: true`.
I've already t[ested this change in github-event-processor-test](https://github.com/azure-sdk/github-event-processor-test/blob/main/.github/workflows/event-processor.yml#L36) repository and things look fine.
> Update to azure/login@v2

- tools/sdk-ai-bots/Embeddings/embedding/embedding.py
The new `langchain` azure search library needs to have a 'search profile' when create a new search index.
> Added search profile to fix index creation error

- tools/azure-rest-api-specs-examples-automation/js/lint.py
The new eslint 9.0.0 appears to have breaking changes/behaviors.
Also our major libs is still using 0.8.57
https://github.com/microsoft/typespec/blob/main/package.json#L46
Loop Mary from typescript/javascript for advice as well.
> examples automation, pin eslint to 0.8.57

- eng/common/scripts/Update-DocsMsMetadata.ps1
Update-DocsMsMetadata.ps1 is the entry point for MS Docs updates in our pipelines. 
Hoist the `$packageInfo = GetPackageInfoJson $packageInfoLocation` out of the `if ($ValidateDocsMsPackagesFn...` if check and pass the packageInfo into the UpdateDocsMsMetadataForPackage call. The reason for this is that UpdateDocsMsMetadataForPackage also calls GetPackageInfo and if the $GetDocsMsDevLanguageSpecificPackageInfoFn function pointer is defined, like it is for Java, JavaScript and Python, it ends up making calls across the network to get pieces to add to the packageInfo Json. In the cases of Java and Python, it's pulling the javadoc or .whl to crack open to get the namespaces. For JavaScript, it's invoking a rest method. Hoisting the call out of the if statement and passing in the structure to …
> Only make one call to GetPackageInfoJson

- src/dotnet/APIView/APIView/Model/CodeDiagnosticLevel.cs
- src/dotnet/APIView/APIViewWeb/Client/css/pages/review.scss
- src/dotnet/APIView/APIViewWeb/Client/css/shared/bootstraps-overrides.scss
- src/dotnet/APIView/APIViewWeb/LeanModels/ChangeHistory.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Program.cs
Added display to APIView to show the approval status history for the currently active revision. Included corresponding icons, date/time and reviewers who changed approval status.
> Add api approval history

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Controllers/DevopsEventsController.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Program.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.json
- tools/pipeline-witness/infrastructure/Assign-StoragePermissions.ps1
- tools/pipeline-witness/infrastructure/bicep/logsResourceGroup.bicep
Because the StorageQueue hook in Azure DevOps depends on a storage key, we need to migrate to a hook type that doesn't use a storage account.
This PR adds an HTTP POST endpoint to the app that receives a message from devops and pushes it to the storage queue, acting as an enqueue proxy.
> Add webapi controller for devops POST webhook

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts
- tools/js-sdk-release-tools/src/utils/backupNodeModules.ts
fixes https://github.com/Azure/azure-sdk-tools/issues/7631
> fix the ci stuck issue

- src/dotnet/APIView/APIView/Analysis/Analyzer.cs
- src/dotnet/APIView/APIViewIntegrationTests/RepositoryTests/CosmosPullRequestRepositoryTests.cs
- src/dotnet/APIView/APIViewIntegrationTests/RepositoryTests/CosmosReviewRepositoryTests.cs
- Remove `ClientAssemblyNamespaceAnalyzer` since the logic has been removed in https://github.com/Azure/azure-sdk-tools/pull/8164
> Resolve bug in APIView

- .github/CODEOWNERS
Changes were made in azure-sdk-tools which now require PRs to be signed off by owners of the code defined in CODEOWNERS. I'm adding @jsquire and @ronniegeraghty as owners of github-event-processor since they're the major stakeholders and the primary sources driving rules changes (with me tending to be the developer).
> Add jsquire and ronniegeraghty as owners of github-event-processor

- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/ScheduledEventProcessing.cs
@ronniegeraghty 
Update the comment added to the issue via EnforceMaxLifeOfIssues as per the email discussion.
> Update the EnforceMaxLifeOfIssues comment that is added to the issue.

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
This update is being done because of changes in the following [PR](https://github.com/Azure/azure-sdk-tools/pull/8185) and the newly published version of Azure.Sdk.Tools.GitHubEventProcessor for that change is 1.0.0-dev.20240502.2.
> Update version of github-event-processor to 1.0.0-dev.20240502.2

- src/dotnet/APIView/APIViewWeb/Client/css/pages/review.scss
- src/dotnet/APIView/APIViewWeb/Client/css/shared/language-customizations.scss
- src/dotnet/APIView/APIViewWeb/Client/css/shared/mixins.scss
- src/dotnet/APIView/APIViewWeb/Client/css/shared/off-canvas.scss
- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.module.ts
- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.ts
- src/dotnet/APIView/APIViewWeb/LeanModels/ReviewRevisionPageModels.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Conversation.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Revisions.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Samples.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewBadge.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_RevisionSelectPickerPartial.cshtml
> Bug fix/re enable revision DropDown

- src/dotnet/APIView/APIView/Model/CodeDiagnosticLevel.cs
- src/dotnet/APIView/APIViewWeb/Client/css/pages/review.scss
- src/dotnet/APIView/APIViewWeb/Client/css/shared/codeline.scss
- src/dotnet/APIView/APIViewWeb/Client/css/shared/theme-colors.scss
- src/dotnet/APIView/APIViewWeb/Client/src/pages/review.ts
- src/dotnet/APIView/APIViewWeb/Helpers/PageModelHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/ReviewRevisionPageModels.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml
- src/dotnet/APIView/APIViewWeb/Pages/Shared/_DiagnosticsPartial.cshtml
User will be notified via popup if Fatal diagnostics or open conversations are present when attempting approval. Issue checkboxes must be checked to override and continue approval.
> Prevent release with critical failures

- eng/pipelines/pipeline-owners-extraction.yml
- tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/GitHubEventClient.cs
- tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/GitHubTeamUserStore.csproj
- tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/Program.cs
Use azure credentials instead of the SAS token for the team/user store.
In the pipeline use the AzureCLI task to authenticate to the Azure SDK Artifacts, which has already been setup. As mentioned in the comments, we can't use the DefaultAzureCredential. The reason for this is because, in CI pipelines, it picks up the ManagedIdentityCredential over the AzureCliCredential and the AzureCliCredential is what we need to be using.
> SAS token removal from team/user store

- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter/Program.cs
As per instructions:
The codeowners-linter pipeline, for PRs, suffers from the problem that if the base branch has errors the PR will effectively be stuck until those errors are fixed and the updated CODEOWNERS file is merged into the PR branch. This happens when people leave the company or Azure. The plan is to create a base branch baseline file from the base branch CODEOWNERS and use that to further filter any errors in the PR. This way, only errors in the PR will prevent the PR check in.
This fix comes in two parts and this is the first. The linter has a new option, -bbl, which takes a path, including the filename, to the base branch baseline file. If generating the baseline, with the -gbl option, it'll create the file. If filtering errors, with the -fbl option, it'll use the base …
> Add base branch baseline file for additional PR filtering

- eng/common/pipelines/templates/steps/verify-restapi-spec-location.yml
Storage team is blocked for the GA release which depends on a legacy version spec in non-main branch. Service team needs more time to use the latest stable version specs from the main branch of Azure spec repo. As discussed with Scott, we decided to allow the check to be skipped by pipeline variable to unblock the release.
This is the [dotnet test pipeline run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3789610&view=logs&j=7bb69cc7-6f52-585e-8b13-5bae7c4a9fa4&t=7abbbe6b-d005-5c95-feb6-99ffe4e699e1) which skips this check after set the variable when triggered the run.
> Added variable to skip spec location check

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/OptionsGenerator.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/PushOptions.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/IAssetsStore.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/NullStore.cs
Getting a simple feature in ahead of the need.
I can definitely see us doing something more specific, like an internal suppression mechanism or the like, but I want to be able to unblock folks on their machines if they absolutely need it.
> Support Scan Breakglass

- eng/pipelines/templates/jobs/azuresdkpartnerdrops-to-nugetfeed.yml
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ModifiableRecordSession.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerDictionary.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
- tools/test-proxy/tests.yml
> Feedback from `Java` Integration

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/Remove-TestResources.ps1.md
- eng/common/TestResources/deploy-test-resources.yml
- eng/common/TestResources/remove-test-resources.yml
> Add support for Federated Auth to test resources scripts

- eng/scripts/Verify-And-Merge-PRs.ps1
We were hitting an error caused by some recent GH changes. Based on https://github.com/orgs/community/discussions/110246 you now need to explicitly set Content-Type in the headers to avoid the error:
The given key 'Content-Type' was not present in the dictionary.
Fixes https://github.com/Azure/azure-sdk-tools/issues/8269
> Add Content-Type to the GH PR api call

- eng/common/pipelines/templates/steps/create-apireview.yml
Release job for Java packages does not have azure-sdk-for-java in default source repo path.  This change is required so release job can use this common template to mark a package as shipped by overriding source repo path.
> Make create apireview runnable from non default working directory

- eng/common/pipelines/codeowners-linter.yml
These is the yml changes for the [linter update](https://github.com/Azure/azure-sdk-tools/pull/8264).
Testing was done by pushing test commits with errors in their CODEOWNERS files that were removed from the baseline errors as part of their PRs. This means that only by using the generated base branch baseline file would they have passed.
[PR](https://github.com/Azure/azure-sdk-for-java/pull/40153) with main as the base branch and its [codeowners-linter run](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3787959&view=results)
[PR](https://github.com/Azure/azure-sdk-for-java/pull/40161) with a feature branch as the base branch and its [codeowners-linter run](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3788427&view=results)
These cases were necessary to test …
> CODEOWNERS linter yml updates

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerDictionary.cs
Brought to my attention by @chlowell
> Remove a duplicate sanitizer from the proxy config

- .github/CODEOWNERS
Given we are moving to requiring codeowners to approve PRs I'm expanding the eng folder to the entire eng team. 
@benbp we are going to need to do that at least for eng/common in all the sync repos as well otherwise no one but you and I can merge approve a sync PR for merge.
> use azure-sdk-eng for codeowner for everything under eng folder

- eng/common/pipelines/templates/steps/create-apireview.yml
Use absolute path with parameter root path as prefix to run create api review script so that this template can be used in Java release pipeline.
> Update APIView script path to absolute path

- eng/common/pipelines/templates/steps/publish-blobs.yml
- eng/common/scripts/copy-docs-to-blobstorage.ps1
GitHubIO versioned docs are published to blob storage which required the SAS key to write.
As part of this work, I did have to give Storage Blob Data Contributor access to azuresdkdocs to the service principal. This is in the same resource group as azure-sdk-artifacts. The replacement of the SAS usage in the eng/common code was pretty straightforward and the language repositories will continue to work without issue. Once this is in, I'll have to go through each language repository to remove usage of azure-sdk-docs-prod-sas and then I'll be able to remove this from the variable group and, ultimately, the keyvault.
The changes were tested via [temporary PR in Java](https://github.com/Azure/azure-sdk-for-java/pull/40214) and this is the [pipeline …
> Remove SAS token from GitHubIO blob storage docs publish

- eng/common/testproxy/test-proxy-tool.yml
So we can avoid situations like [this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3798805&view=logs&j=ba3dad2b-ce90-52d5-0c84-4172d8b9d063&t=23b3eb06-0e1d-52c0-ea78-4a25bce86ae9).
> Write linux proxy logs to mount folder

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/README.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/log.ts
- tools/tsp-client/src/options.ts
Support `--no-prompt` flag to skip the output directory confirmation prompt.
> [tsp-client] Add no-prompt flag

- src/dotnet/APIView/apiview-sync-staging.yml
Replace the SAS token usage.
Because this pipeline is a standalone pipeline once these changes are tested and merged the SAS tokens (apiview-production-storage-sas and apiview-staging-storage-sas) can be removed from the [APIView daily Prod to staging sync](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-distributed-task.hub-library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=86&path=APIView%20sync%20Staging%20variable) and from the keyvault. 
Also, both storage accounts will need to have their access by SAS turned off.
> Remove SAS token usage from apiview-sync-staging

- eng/pipelines/templates/steps/apiview-review-gen.yml
- eng/scripts/Create-Apiview-Token-Files.ps1
SAS token removal. 
The [APIView-Sandboxing](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-distributed-task.hub-library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=124&path=APIView-Sandboxing) variable group only has two SAS tokens in it, apiview-originals-sas and apiview-staging-originals-sas. The apiview-staging-originals-sas was setup, but ultimately never used, and the only use of apiview-originals-sas is being removed in this PR. In theory, the variable group can be removed once we know which pipelines it's linked to.
The above being said, APIView-Sandboxing isn't the only VG with apiview-originals-sas in it.
> Remove SAS token usage from apiview-review-gen

- tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/Program.cs
- tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/TeamUserGenerator.cs
The SAS token is no longer needed and was removed in a previous [PR](https://github.com/Azure/azure-sdk-tools/pull/8246) but it looks like I missed a couple of comments and the help for the arguments that used to require it.
> Remove SAS from comments and option help

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs
So many exceptions is quite costly. No reason to be throwing them when we can very simply check for json in the Content-Type before attempting to parse prior to applying the bodykeysanitizer.
> Minimize exceptions thrown from `BodyKeySanitizer`

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerDictionary.cs
Given that the existing value is `Sanitized` and we apply the sanitizers to recordings when loaded for playback, I expect 0 downstream impact from this change.
> Update AZSDK1001 to replace the value with a base64 one

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/Remove-TestResources.ps1.md
- eng/common/TestResources/deploy-test-resources.yml
- eng/common/TestResources/remove-test-resources.yml
- eng/common/TestResources/sub-config/AzurePublicMsft.json
Example successful pipeline run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3825341&view=results
Example wiring up in `tests.yml` https://github.com/Azure/azure-sdk-for-net/compare/main...djurek%2Fworkload-identity-live-tests-sub-config-files?body=&expand=1#diff-a38d5bba40ecff60e025723b70c9a682e464bcadf5e87e6571a641ca8659dee3R9-R12
Testing .NET appconfig in its current state (no federated auth) to ensure no wider regression: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3811807&view=logs&j=d1b595c4-8536-5d61-1a0c-a149c6a83c63&t=20c529b1-7692-5b7f-3681-519a295cdefc
> Add static file secret-less sub-config support

- eng/common/scripts/Add-RetentionLease.ps1
- eng/common/scripts/Invoke-DevOpsAPI.ps1
- eng/common/scripts/Queue-Pipeline.ps1
- eng/pipelines/pipeline-queue-test.yml
- eng/pipelines/templates/steps/sync-directory.yml
Update the scripts that deal with DevOps runs to be able to handle a PAT or an access token from azure.
> Changes to scripts to deal with PATs and AccessTokens

- tools/identity-resolution/Helpers/GitHubToAADConverter.cs
`api://66b6ea26-954d-4b68-8f48-71e3faec7ad1` isn't a supported audience
`66b6ea26-954d-4b68-8f48-71e3faec7ad1` is supported
> Change scope used for OSS portal client

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/index.ts
- tools/tsp-client/src/utils.ts
In order to use tsp-client in parallel to generate multiple libraries, we cannot modify the shared sparse-spec/ directory. This PR changes the tool so that we create unique sparse spec directories per typespec project.
Fixes #8352
> [tsp-client] Create unique sparse spec directories

- eng/pipelines/pipeline-generation.yml
As part of secret clean-up we need to remove variable group 56 from the pipelines we generate so we can delete it.
> Remove deleted notification variable group from pipeline-generation

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerDictionary.cs
See title
@mccoyp I dunno if this is a good plan, but I can't disagree that this will help folks a lot. Not a secret, and traditionally I wouldn't want to sanitize it by default....but it's part of a SAS url. It shouldn't break anything.
> Add `sv` to `SAS` URL default sanitizer

- eng/pipelines/pipeline-generation.yml
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/CommandParserOptions/DefaultOptions.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/PipelineGenerationContext.cs
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
This is part of the PAT removal effort. The PAT being removed is azuresdk-azure-sdk-devops-pipeline-generation-pat. This PR is the first of two, the second PR will update the yml files remove the usage of azuresdk-azure-sdk-devops-pipeline-generation-pat. The second PR requires this to be published first so the version of pipeline-generator in install-pipeline-generator.yml can be updated.
There was a hacked up version of pipeline-generation.yml that was used to test these changes, this was the [successful run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3845151&view=results) after updates. The hacked up yml file has been removed from this PR.
The second PR will use an `AzureCLI@2` task to authenticate and call pipeline-generation within the task's inlinescript.
> Remove PATVAR from PipelineGenerator

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
- eng/pipelines/pipeline-generation-single.yml
- eng/pipelines/pipeline-generation.yml
This is the second PR, the one that removes the usage of azuresdk-azure-sdk-devops-pipeline-generation-pat. 
Note: As of right now, this PR is incomplete. This PR relies on another [PR](https://github.com/Azure/azure-sdk-tools/pull/8369) being merged, publishing a new version of the pipeline-generator and the version of [install-pipeline-generation.yml](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/install-pipeline-generation.yml) being updated to the published version. That needs to be part of this PR and will be updated once the other one is removed.
> PAT Removal from pipeline generation yml

- eng/common/TestResources/deploy-test-resources.yml
- eng/common/TestResources/remove-test-resources.yml
This will allow us to pass OIDC token env and possibly other values through to deploy pre/post scripts.
> Plumb env vars through deploy test resources

- eng/common/testproxy/test-proxy-tool.yml
The macos-14 agent does not currently include .NET 6.x: https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
> .NET Core SDK: 7.0.102, 7.0.202, 7.0.306, 7.0.409, 8.0.101, 8.0.204, 8.0.300
Setting this variable ensures that test-proxy will run in environments which have later major versions of .NET Core.
> Use DOTNET_ROLL_FORWARD: 'Major' for test-proxy

- eng/common/pipelines/templates/steps/run-pester-tests.yml
The explanation of the problem is in the [issue tracking the unpinning once the version on Windows is 5.6.0 or higher](https://github.com/Azure/azure-sdk-tools/issues/8395).
> Pin pester version to 5.5.0

- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Azure.Sdk.Tools.GitHubEventProcessor.csproj
In the afternoon on 06/04/2024 the issue_comment ID was changed from an int to a long and issue_comment processing has been broken since then. Version 12.0.0 of Octokit.net was released this morning, 06/10/2024, and fixes this issue. I've verified using a payload that had an ID > int max and all of the automated tests for the github-event-processor have passed.
> Update github-event-processor's Octokit version to 12.0.0

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
This updates the version of the github-event-processor with the fix for issue_comment Ids being changed to long from int. 
The version was updated in this [tools PR](https://github.com/Azure/azure-sdk-tools/pull/8411)
> Update github-event-processor to 1.0.0-dev.20240610.2

- eng/pipelines/devops-create-package-workitem.yml
- eng/scripts/Create-Package-WorkItem.ps1
Create package work item uses param `$Language` and this collides with `$Language` in eng/common.ps1. This works in most cases but .NET repo his this value set to `dotnet` instead of `.NET` so create package work item request fails with invalid language value error.
> Update language param name to avoid collision with common eng variable

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Switch to older line wrapping because some cases fail if there is no extra parameters on the last line.
See example https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3866634&view=logs&j=7f42699e-eeb0-56c8-40c2-c88ae4093e4f&t=82d183d4-b652-5968-0d60-46aa50150c79&l=59
> Fix prepare-pipelines line wrapping

- eng/common/pipelines/templates/steps/validate-all-packages.yml
- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
- eng/common/scripts/Validate-All-Packages.ps1
- eng/common/scripts/Validate-Package.ps1
- eng/pipelines/devops-create-package-workitem.yml
- eng/scripts/Create-Package-WorkItem.ps1
**This PR won't be merged until Thursday 6/13 as to not interfere with releases.**
These are the code changes to remove the devops release PAT. Use the AzureCLI task and get the token from azure. The other AZ commands that the scripts use should be fine with the azureSubscription. 
The LoginToAzureDevops function in DevOps-WorkItem-Helpers.ps1 is no longer necessary. The scenario for using this is that we passed the PAT to the pipeline and the variable was being used to log into azure. Being that this now needs to be run in an environment that's already logged into azure this function is completely moot.
The validate packages and update work items steps are part of the Build for Java, JS and NET. For Python these steps are in Analyze.
- [Java …
> Removal of the devops release PAT

- tools/github/data/repositories.txt
The GitHubTeamUserStore uses the repositories.txt, the file which holds the list of repositories that we sync common labels, as the list of repositories to get labels for. The label information is used by several tools, including the CODEOWNERS linter. We need to add Azure/azure-rest-api-specs here so we'll get the repo/label data. This will also cause the common labels to get added to the Azure/azure-rest-api-specs repository but considering that many of them are already there, this shouldn't be a problem.
> Add Azure/azure-rest-api-specs to the list of repositories to sync common labels

- tools/codeowners-utils/README.md
Add information about azure-sdk-partners and linking to the access page.
> Update some docs on codeowners linter

- eng/branch-rulesets/require-codeowner-approval.json
- eng/branch-rulesets/required-pullrequest-checks.json
These are the exported branch rulesets that we can use when configuring other repos to have a consistent set of required checks across the azure-sdk-for-<lang> repos.
> Add common branch rulesets we use

- eng/branch-rulesets/require-one-pullrequest-approval.json
- eng/branch-rulesets/required-pullrequest-checks-specs-full.json
FYI @konrad-jamrozik @mikeharder 
These are rulesets I applied to the public and private specs repos. We can maintain these and use them to import and share in both of the repos as needed.
> Add branch ruleset files used for the specs repo

- eng/common/spelling/package-lock.json
This is the result of `npm audit fix` to address vulnerability in older versions
of `braces`.
> Update spelling dependencies

- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter.Tests/Verification/OwnersTests.cs
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Constants/ErrorMessageConstants.cs
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Verification/CodeownersLinter.cs
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Verification/Owners.cs
The problem right now is that the missing owners error, `There are no owners defined for CODEOWNERS entry.`, is too generic. At the moment, the only missing owners in any of the repositories running the linter are for source path/owner lines. The fix here is to add the path to the error in order to make it distinct.
**There is one big issue here:** 
Monikers can also have missing owners but because we can't put line numbers into the baseline file, for obvious reasons, there's no good differentiation for monikers missing errors.
**The mitigation for the issue:**
The only repositories that have this error in their baseline files are azure-sdk-for-java and azure-sdk-for-js. For Java, this error is actually because of two source path/owner lines lacking owners. For JS, this error was …
> Fix missing owners for path error to include path

- eng/common/TestResources/New-TestResources.ps1
Some azure resources (sql) cannot be accessed by VMs in a vnet even if they have public access enabled. In these cases we have to set up the vnet rules in the arm template at deploy time (instead of via azure policy).
See for example: https://github.com/Azure/azure-sdk-for-java/pull/40639
> Pass pipeline vnet to live test arm templates

- src/dotnet/APIView/ClientSPA/angular.json
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
Added functionality to Line Numbers switch in right navigation panel to hide/show code line numbers in center panel.
> Hide Line Numbers switch connected and working

- eng/common/scripts/ChangeLog-Operations.ps1
Fixing case were we didn't correctly fail the build see example https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3875412&view=logs&j=f8db92a5-5aa2-5af0-abb0-b907727011d6&t=69c0dc6a-7dc9-5030-86c4-e7a70f356a18
```
[debug]Verifying as a release build because ForRelease parameter is set to true
##[error]The changelog entry did not contain any of the recommended sections (Features Added, Breaking Changes, Bugs Fixed, Other Changes), please add at least one. See https://aka.ms/azsdk/guideline/changelogs for more info.
Finishing: Verify ChangeLogEntry for azure-ai-translation-document
```
> Fix case where changelog wasn't marked as invalid

- eng/common/TestResources/SubConfig-Helpers.ps1
- eng/common/TestResources/build-test-resource-config.yml
- eng/common/TestResources/deploy-test-resources.yml
- eng/common/TestResources/remove-test-resources.yml
- eng/common/TestResources/sub-config/AzurePublicMsft.json
Tests: 
* No change: 
* Federated auth with sub config file: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3863734&view=results
* Federated auth with sub config variables and file: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3860968&view=results (note, `Int` stage does not have a working service connection) 
Latest test runs on eng/common PRs: 
* Java App Config (federated auth) -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3879391&view=results
* .NET App Config (not federated auth) -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3879390&view=results
This includes a breaking change, these PRs fix the break: 
* https://github.com/Azure/azure-sdk-for-python/pull/36126
* …
> Merge subscription configuration file values with the supplied subscription config

- tools/sdk-testgen/common/config/rush/.pnpmfile.cjs
- tools/sdk-testgen/common/config/rush/pnpm-lock.yaml
- tools/sdk-testgen/packages/autorest.testmodeler/src/core/model.ts
Fixed security alerts:
- https://github.com/Azure/azure-sdk-tools/security/dependabot/177
- https://github.com/Azure/azure-sdk-tools/security/dependabot/181
> Fixed high security alerts for sdk-testgen codes

- .github/CODEOWNERS
- .gitmodules
- package-lock.json
- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/hlc/utils/automaticGenerateChangeLogAndBumpVersion.ts
- tools/js-sdk-release-tools/src/llc/utils/generateChangelog.ts
- tools/js-sdk-release-tools/src/llc/utils/utils.ts
- tools/js-sdk-release-tools/src/utils/version.ts
- tools/js-sdk-release-tools/tsconfig.json
https://github.com/Azure/azure-sdk-tools/security/dependabot/137
https://github.com/Azure/azure-sdk-tools/security/dependabot/175
> Fix  high sev security issue

- .gitmodules
- package-lock.json
- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/hlc/utils/automaticGenerateChangeLogAndBumpVersion.ts
- tools/js-sdk-release-tools/src/llc/utils/generateChangelog.ts
- tools/js-sdk-release-tools/src/llc/utils/utils.ts
- tools/js-sdk-release-tools/src/utils/version.ts
- tools/js-sdk-release-tools/tsconfig.json
Reverts Azure/azure-sdk-tools#8471
@wanlwanl @raych1 @qiaozha I had to revert this as it is breaking a number of pipelines that aren't setup to correctly sync submodules. We should not be using submodules in our repos because a number of these issues.
> Revert "Fix  high sev security issue"

- tools/js-sdk-release-tools/src/common/utils.ts
- tools/js-sdk-release-tools/src/hlc/utils/automaticGenerateChangeLogAndBumpVersion.ts
- tools/js-sdk-release-tools/src/hlc/utils/modifyChangelogFileAndBumpVersion.ts
- tools/js-sdk-release-tools/src/llc/utils/generateChangelog.ts
> Update old changelog format

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Without this building and pushing from ARM Mac's (or any ARM platform) produce images that just fail with mysterious errors because AKS and your local arch don't match.
> [stress testing]: Force amd64 as the build platform for images we push

- eng/pipelines/templates/stages/archetype-sdk-publish-js.yml
- eng/scripts/determine-js-release-tag.ps1
- tools/apiview/emitters/typespec-apiview/ci.yml
- tools/js-sdk-release-tools/ci.yml
- tools/mock-service-host/ci.yml
- tools/oav-traffic-converter/ci.yml
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
- tools/tsp-client/ci.yml
Looks like when I tested an actual release, I tested the only case that would actually work when merging #8460 
@catalinaperalta  hit issues this past Friday with this as a result. I unblocked her, but wanted to make an adjustment to re-use the `SemVer` package before merging.
Unfortunately, it looks like if I use `SemVer`, it marks packages < 1.0.0 (even if if GA-marked) as `Prerelease`. While I agree with this for our production packages, our internal tooling conflicts with this bar.
Specifically, the typespec-emitter `latest` version is `0.4.8`. If we used `SemVer` and `IsPrerelease` property to determine whether to set `latest` or `beta` tag, we would erroneously mark the latest version of `typespec-emitter` with `beta`. At least until 1.0.0. For now I'm leaving the simple tag check …
> Node Publishing Update

- tools/js-sdk-release-tools/src/hlc/utils/modifyChangelogFileAndBumpVersion.ts
fix https://github.com/Azure/azure-sdk-for-js/issues/30156
> Fix Changelog Verification CI failed issue for First GA packages

- tools/test-proxy/documentation/asset-sync/README.md
FYI @billwert thanks for the suggestion
> Add note recording recording file growth

- tools/github/scripts/Validate-AzsdkCodeOwner.ps1
The focus of these changes is to fix a mistake when displaying required permissions that are missing.   The current implementation displays the permission held by the user rather than the required permission that is missing, causing it to be unclear what permission is needed.
> [Validate-AzsdkCodeOwner] Missing permission display

- src/dotnet/APIView/APIViewIntegrationTests/APIViewIntegrationTests.csproj
- src/dotnet/APIView/APIViewIntegrationTests/RepositoryTests/CosmosPullRequestRepositoryTests.cs
- src/dotnet/APIView/APIViewIntegrationTests/RepositoryTests/CosmosReviewRepositoryTests.cs
- src/dotnet/APIView/APIViewIntegrationTests/TestsBaseFixture.cs
- src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
- src/dotnet/APIView/APIViewWeb/APIViewWeb.csproj
- src/dotnet/APIView/APIViewWeb/MiddleWare/UITestsMiddleWare.cs
- src/dotnet/APIView/APIViewWeb/Repositories/BlobCodeFileRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/BlobOriginalsRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/BlobUsageSampleRepository.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
Changes to connect to Cosmos and Storage using managed identity instead of using connection strings.
> APIView - Connect to cosmos and storage using managed identity

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/build-test-resource-config.yml
- eng/common/TestResources/deploy-test-resources.yml
Not quite sure about the ordering here, if we want to set networks rules before or after post-script/deployment removal or not.
This adds a step to our deployment script that sets any deployed storage accounts to a network deny state, but punches a hole through for the client's IP. A medium term solution until better ones come online (reach out for details).
> Restrict live test storage account access to client IP

- tools/github/README.md
- tools/github/scripts/Add-AzsdkMilestones.ps1
- tools/github/scripts/Add-AzsdkProjectIssues.ps1
- tools/github/scripts/Snapshot-AzsdkLabels.ps1
- tools/github/scripts/Sync-AzsdkLabels.ps1
- tools/github/scripts/Validate-AzsdkCodeOwner.ps1
The default UX shouldn't change: to override any default values for disambiguating parameters, you had to pass values. If we change the default parameter set (or, for a couple scripts, leave it) to use the file we can remove the duplicate repo and language information from the `-Repositories` and `-Languages` parameters because to override those - even if they were the default parameter - you had to specify a different value. The end result should be no change.
Also cleans up warnings in the README and a couple other scripts using their respective linters I have enabled in VSCode.
> Use repositories file by default for GH scripts

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/typespec.ts
- tools/tsp-client/test/examples/specification/diagnostics/main.tsp
- tools/tsp-client/test/examples/specification/diagnostics/tspconfig.yaml
- tools/tsp-client/test/typespec.spec.ts
Use logger for diagnostics and exit if there are diagnostics reported during the tsp `compile` call
Fixes https://github.com/Azure/azure-sdk-tools/issues/8523
> [tsp-client] Fix tsp compile diagnostics logging

- tools/tsp-client/src/index.ts
- tools/tsp-client/src/typespec.ts
More fixes related to diagnostic reporting. Return boolean from compileTsp to exit after file clean up in case of diagnostics.
> [tsp-client] Fix compiler diagnostic reporting

- tools/github/data/common-labels.csv
The focus of these changes is to add a common label for the "AI Model Inference" service.
> [GitHub] Update common labels

- .github/CODEOWNERS
The focus of these changes is to update the GitHub scripts + common data area ownership.
> [CODEOWNERS] Update GH script owners

- eng/common/TestResources/build-test-resource-config.yml
- eng/scripts/live-test-resource-cleanup.ps1
The null default breaks any pipelines that don't specify env vars
> Fix default value for env vars in build-test-resource-config template

- eng/common/TestResources/build-test-resource-config.yml
Fixes https://github.com/Azure/azure-sdk-tools/issues/8507
Tests: 
* No changes: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3932581&view=logs&j=43701d7e-216c-59bf-08d1-1efd0c7ac90a&t=b6d99d7a-c889-583c-28b5-43c35affcd50&l=234
* CloudConfig with SubscriptionConfigurationFilePaths set -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3932609&view=logs&j=43701d7e-216c-59bf-08d1-1efd0c7ac90a&t=b6d99d7a-c889-583c-28b5-43c35affcd50&l=234
* CloudConfig with NO SubscriptionConfigurationFilePaths set (used to produce errors) -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3932621&view=logs&j=efd63400-1b36-5c22-495f-5e04b5698008&t=04da24dd-1265-5b7d-577b-fed9b6b497d0&l=231
> Ensure subConfigFiles is not an empty string

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/index.ts
Exiting with `exit(1)` after a tsp compile returns diagnostics is not always correct since some diagnostics are at the warning vs error level. 
Tracking issue to fix this logic: #8555
Reverting now to unblock automation pipelines. Fixes #8553
> [tsp-client] Revert exit after compile

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
This is the GitHubEventProcessor update for @RickWinter's tools [PR](https://github.com/Azure/azure-sdk-tools/pull/8546) which provides a way to skip the Enforce Max Life of Issues.
> Update GitHubEventProcessor version to 1.0.0-dev.20240708.1

- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- handle error in GitHub API, this prevent the pipeline from failing until they (GitHub) have this fixed.
> handle error in GitHub API

- tools/apiview/emitters/typespec-apiview/CHANGELOG.md
- tools/apiview/emitters/typespec-apiview/package-lock.json
- tools/apiview/emitters/typespec-apiview/src/apiview.ts
- tools/apiview/emitters/typespec-apiview/src/namespace-model.ts
- tools/apiview/emitters/typespec-apiview/test/apiview.test.ts
> [TSP APIView] Support constant statements

- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/Program.cs
- Prevent Parser from breaking when there are no dependencies.
> Resolve bug in CSharp Parser

- eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
- eng/common/pipelines/templates/steps/verify-changelog.yml
- eng/common/pipelines/templates/steps/verify-path-length.yml
- eng/common/pipelines/templates/steps/verify-readme.yml
Python had a nightly `analyze` failure that had me really confused. The issue was that one of the eng/common steps which set the daily dev build variable skipped due to a default `succeeded()` condition when a step above it unexpectedly failed.
I walked the rest of the `analyze` steps in Python, and identified a few more where a custom condition can be provided to allow `succeededOrFailed()` to be passed. This way all the enforcement runs on a given analyze job.
Once this PR merges I'll take advantage of it on python side and ensure the issue that hit @kristapratico is avoided in the future.
> Pass condition to a few `analyze` eng/common checks

- eng/common/scripts/stress-testing/find-all-stress-packages.ps1
- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
- eng/pipelines/stress-test-release-storage.yml
- eng/pipelines/templates/jobs/stress-test-release.yml
- tools/stress-cluster/chaos/README.md
- tools/stress-cluster/cluster/README.md
- tools/stress-cluster/cluster/azure/cluster/cluster.bicep
- tools/stress-cluster/cluster/azure/parameters/storage.json
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
I have built out a new default stress cluster in the storage partner team subscription that they can use. Adding it to the config defaults so they can use it out of the box.
Also updating the documentation to reflect the changes made in https://github.com/Azure/azure-sdk-tools/pull/8278 to support workload identity as the auth mode for the stress clusters.
> Add storage cluster to stress environments. Update federated auth documentation.

- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/build-test-resource-config.yml
- eng/common/scripts/Helpers/Resource-Helpers.ps1
This will disable this by default as an override.
There are several places where we have this marked as `true` in live test ARM templates, but I'm not convinced those are necessary. Will do testing against these changes before merging.
EDIT: Also removing the pieces that add the network firewall by default on resource creation. This is causing a whole host of issues that we aren't getting much value from, and aren't required to do in the near term.
> Set storage account test resources to disable blob public access. Disable network firewall.

- src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
Contributing guide changes to include required RBAC roles for APIVIew.
> Update contributing guide to add required RBAC roles

- src/dotnet/APIView/APIViewWeb/Languages/LanguageProcessor.cs
- This is to avoid the bug where two processes are attempting to use the process at the same time.
> Update FileStream Code in LanguageProcessor

- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/CSharpAPIParser.csproj
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/Program.cs
Token file is created using incorrect file name even when a path is passed, and this leads to file not found error.
> Create token file using file name given as param

- src/dotnet/APIView/ClientSPA/src/app/_components/index-page/index-page.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/index-page/index-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/reviews-list/reviews-list.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/reviews-list/reviews-list.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/reviews-list/reviews-list.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/review-info/review-info.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_modules/review-page/review-page.module.ts
- src/dotnet/APIView/ClientSPA/src/app/_modules/shared/shared-app.module.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/revisions/revisions.service.ts
- src/dotnet/APIView/ClientSPA/src/app/app.module.ts
- This adds API-Revision view showing API Revision in detail, and ability to add APIRevisions from the review page.
> 071624.05/api revisions

- eng/common/pipelines/templates/steps/set-default-branch.yml
- eng/common/pipelines/templates/steps/verify-links.yml
See title, [discovered in build failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3967720&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=a880e989-7d1a-5c96-a41f-d540b383cc43).
The build failed correctly, but we should have invoked the SetDefaultBranch regardless of cspell failing.
> Missing a condition passthrough on `verify-links.yml`

- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/revision.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/revisions/revisions.service.ts
- Condition revision link based Parser Style.
- Properly handle sidebar closing.
> 071824.03/revision links

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SecretScanner.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
We use `DetectPendingChanges` to generate the file list of files to scan. I had a bit of a brainfart and filtered out `Deleted` files because why would we credscan those? The problem is that made it so we don't detect that we need to **push** when it's only deleted files.
I even _had the protection to not attempt to open a file that doesn't exist for scanning_ but I still left the dumb filter logic.
This PR adds an integration test for only-delete scenario.
> Fix broken `push` scenario with only deleted files

- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/ReviewRevisionPageModels.cs
Use Concurrent Dictionary to avoid race conditions
> Use Concurrent Dictionary

- src/go/cmd/api_view.go
- src/go/cmd/api_view_test.go
- src/go/cmd/module.go
- src/go/cmd/pkg.go
- src/go/cmd/review.go
- src/go/cmd/review_test.go
- src/go/cmd/testdata/test_alias_export/go.mod
- src/go/cmd/testdata/test_alias_export/test.go
- src/go/cmd/testdata/test_external_alias_exporter/go.mod
- src/go/cmd/testdata/test_external_alias_exporter/test.go
- src/go/cmd/testdata/test_external_alias_source/go.mod
- src/go/cmd/testdata/test_service_group/group/internal/go.mod
- src/go/cmd/testdata/test_service_group/group/test_alias_export/go.mod
- src/go/cmd/testdata/test_service_group/group/test_alias_export/test.go
Part of #7866. Main goal here is to create a spot (the TODO in `Review.resolveAliases`) to handle type aliases (`type Event = log.Event`) referring to non-SDK modules.
- new `TypeAlias` type carries data about aliases, hoists the definition to the aliasing package when given a `typeDef`
- new `Review` type collects modules implicated in the review, resolves cross-module references, computes output
- `Module` now surfaces its cross-module type aliases for `Review` to resolve instead of resolving them itself
- removed assumption that all modules implicated in a review are in the same repo
Along the way I appear to have incidentally fixed a bug that omitted type aliases referring to underlying types. For example, [ExpiryTypeAbsolute](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/st …
> Refactor apiviewgo type definition hoisting

- tools/js-sdk-release-tools/src/common/utils.ts
- tools/js-sdk-release-tools/src/hlc/utils/automaticGenerateChangeLogAndBumpVersion.ts
- tools/js-sdk-release-tools/src/llc/utils/generateChangelog.ts
- tools/js-sdk-release-tools/src/test/changelog/changelogGenerator.test.ts
Some published package doesn't contain changelog.md, it breaks the current changelog tool by throwing error when it try to append new content to changelog.
Stop throwing error, but output warning log instead. Output "" by default.
> Improvement: stop depending on NPM changelog

- eng/common/pipelines/templates/steps/set-daily-docs-branch-name.yml
Still in draft because I'm still investigating the entirety of the changes required.
The problem being looked at is that committing to a docs branch will automatically kick off runs. Adding the -ignore-build suffix will prevent this. The doc-index runs for java, js, net and python, already run a content CI docs run which will, in turn, create the nightly docs branch and this already happens today.
 
Fixes #6569
> Change the daily docs branch name

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/LoggingTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordSessionTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordSession.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
We pay next to nothing for stability. The failing test is the one that I think is actually going wrong on Java side.
Relevant to #8729
> Updates to `HandlePlaybackRequest` to force synchronous handling

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
Issue, `test-proxy --version` started returning `20240730.2+7b8a6a1ce5de8012452620aa1969dc549ed0b190` ...aka the version with source revision attached.
This is due to a new sourcelink version: https://stackoverflow.com/questions/77050814/fileversioninfo-productversion-suddenly-contains-git-commit-hash (cheers @weshaggard for the link)
We want this to be a nice clean: `1.0.0-dev.20240731.1` which is the better user experience and will unblock broken go tests.
> ensure that sourceversion doesn't appear in the informationalversion

- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/APITreeNode.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/APITreeNodeId.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/APITreeNodeProperties.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/APITreeNodeTags.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/CodeDiagnostic.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/CodeDiagnosticLevel.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/CodeFile.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/StructuredToken.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/StructuredTokenId.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/StructuredTokenKind.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/StructuredTokenProperties.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/StructuredTokenRenderClasses.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/json-schema/StructuredTokenTags.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/models.tsp
- TypeSpec Definition for APIView TreeStyle Parser
> Add TypeSpec Definition for APIView TreeStyle Parser

- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/comment-thread/comment-thread.component.ts
Selecting a language from the three dot menu within a comment's panel in APIView creates a pre-populated GitHub issue with the language, comment content and URL of the revision.
> Create GitHub Issue

- eng/pipelines/mirror-pypi-to-dev-feed.yml
- eng/scripts/download_targeted_packages.py
Old change, but needed to get this in so I don't forget it for later. Before changes build was [on the floor.](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3942428&view=results)
> Fix pypi mirror job

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/InfoTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/LoggingTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordSessionTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ModifiableRecordSession.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordSession.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordTransport.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerDictionary.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Models/ActiveMetadataModel.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Record.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
This cuts out all `lock` usage for `await SemaphorSlim.WaitAsync()` to synchronize resource access.
Originally, we had 3 possible locks
- object SessionSanitizerLock
- Session.Entries
- object Session.SanitizerLock
This moves to using a semaphore for these. Unfortunately this has the impact of forcing `async` in a lot of places that _didn't_ use it before, so I've got some test pain to resolve as a result.
@mikeharder I'm very pleased with this one!
> All semaphor all the time

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package.json
The following PR added a call to `import.meta.resolve()`, which is only available starting with Node 18.19.0 and 20.6.0:
https://github.com/Azure/azure-sdk-tools/commit/f5d595557cdcba4c32612d8082505f88dba423e9#diff-6f62171ec5df7a0f474274b3d6aed40ffebe0ff3f78c0ef749dc8f315b777107R58
On older Node versions, tsp-client now fails with this error:
```
TypeError: (intermediate value).resolve is not a function
```
To address this, the minimum node versions should be incremented, so consumers get a better error message:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure-tools/typespec-client-generator-cli@0.9.4',
npm WARN EBADENGINE   required: { node: '^18.19.0 || >=20.6.0' },
npm WARN EBADENGINE   current: { node: 'v18.18.2', npm: '9.8.1' }
npm WARN EBADENGINE } …
```
> [tsp-client] Upgrade minimum node versions for import.meta.resolve()

- tools/tsp-client/src/typespec.ts
Instead of always logging the diagnostics, only log if the user passes the --debug flag.
> [tsp-client] Log diagnostics with --debug flag

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
> [tsp-client] Update @typespec/compiler dep

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerDictionary.cs
Title is awkward. Basically, if you've already requested that sanitizer `AZSDK0001` be gone, if you send another request it'll just respond with 200.
> Allow already-removed sanitizers to not error when removed

- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
File name is not updated in cosmos DB when updating API revision if a new commit has more API changes. This causes issue when upgrading a revision due to parser version changes. Filename is required to upgrade revisions.
> Update file name when updating revision from PR

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/AdminTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/PlaybackTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordSessionTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordingHandlerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/TestHelpers.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Audit.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/AuditLogItem.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/DebugLogger.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/ModifiableRecordSession.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordSession.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerDictionary.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
This PR
@mikeharder I need to add audit items to the `record` pathway, but I was laser focused on getting `playback` concurrency issues resolved for the java folks. Please take a look, see how I'm retaining the various locks on resources (by reducing to a single access lock to each playback session). I _think_ I've nailed most of the edge cases. 
@alzimmermsft looking at the latest `java - core` failures running with this version of the test-proxy, I don't think the proxy is related to those. I'm not declaring total victory with this PR but the issues are seriously reduced.
This version is standing up to multiple storage runs:
> Add proxy audit log and other assorted fixes

- src/dotnet/APIView/APIViewWeb/LeanControllers/ReviewsController.cs
- src/dotnet/APIView/APIViewWeb/Repositories/BlobCodeFileRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/IBlobCodeFileRepository.cs
- Disable cache when retrieving compressed files.
- Should resolve https://github.com/Azure/azure-sdk-tools/issues/8724
> Disable Caching When Pulling Compressed Files

- src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
- src/dotnet/APIView/ClientSPA/CONTRIBUTING.md
- Contribuiting Guide for APIView SPA Client
> 080624.02/Update Contributing Doc

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/src/index.ts
After the yargs migration, seems we arent getting the right reference to the package version. Fixing in this PR.
Fixes #8814
> [tsp-client] Fix tool version

- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- This ensure that comments are added to the correct line when docs are expanded.
> Ensure Commets are added in correct line when docs are expanded

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/utils.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
Fix: https://github.com/Azure/azure-sdk-tools/issues/8057
Test pipeline: https://github.com/test-repo-billy/azure-rest-api-specs/pull/3473
> Clear Package Folder Before Generation

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/pnpm-lock.yaml
- tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts
- tools/js-sdk-release-tools/src/changelog/changelogGenerator.ts
- tools/js-sdk-release-tools/src/changelog/extractMetaData.ts
- tools/js-sdk-release-tools/src/changelogToolCli.ts
- tools/js-sdk-release-tools/src/common/utils.ts
- tools/js-sdk-release-tools/src/hlc/generateMgmt.ts
- tools/js-sdk-release-tools/src/hlc/utils/automaticGenerateChangeLogAndBumpVersion.ts
- tools/js-sdk-release-tools/src/hlcCodeGenCli.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInTerminal/generateRLCInTerminal.ts
- tools/js-sdk-release-tools/src/llc/utils/generateChangelog.ts
- tools/js-sdk-release-tools/src/llc/utils/generateSampleReadmeMd.ts
- tools/js-sdk-release-tools/src/llc/utils/utils.ts
- tools/js-sdk-release-tools/src/rlcCodegenCli.ts
- tools/js-sdk-release-tools/src/utils/backupNodeModules.ts
- tools/js-sdk-release-tools/src/utils/git.ts
- tools/js-sdk-release-tools/src/utils/logger.ts
- tools/js-sdk-release-tools/src/utils/version.ts
1. Hide useless logs for npm pack
2. Make log prefix consistent
3. Add error summary and details when command failed
- https://github.com/Azure/azure-sdk-tools/issues/8058
- https://github.com/Azure/azure-sdk-tools/issues/8098
- Add TSG (looks like we don't have suitable TSG)
> Improve Logging

- tools/github/data/common-labels.csv
The focus of these changes is to add the common service label for the "Compute - Fleet" resource provider.
> [GitHub] Add common service label

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/index.ts
- Fix version printing in banner
- Show banner in the sort-swagger command
- Update supported typespec-autorest versions
Follow up issue to support output directory in `sort-swagger`: https://github.com/Azure/azure-sdk-tools/issues/8824
> [tsp-client] Miscellaneous fixes

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0014Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/BannedAssembliesAnalyzer.cs
We have now enabled [JsonModelWriteCore](https://github.com/microsoft/typespec/blob/745b4f97229e128f61e35b725d4ae3adb436424a/packages/http-client-csharp/generator/TestProjects/Local/Unbranded-TypeSpec/src/Generated/Models/ProjectedNameModelRequest.Serialization.cs#L39) and [JsonModelCreateCore](https://github.com/microsoft/typespec/blob/745b4f97229e128f61e35b725d4ae3adb436424a/packages/http-client-csharp/generator/TestProjects/Local/Unbranded-TypeSpec/src/Generated/Models/ProjectedNameModelRequest.Serialization.cs#L69) in MGC. Now we are adding this WriteCore/CreateCore feature to autorest.csharp, because some customers are asking this. However, these two methods are violating “AZC0014: Types from System.Text.Json, Newtonsoft.Json, System.Collections.Immutable assemblies should not be …
> Add exception for Utf8JsonReader/Writer to AZC0014

- eng/common/scripts/Delete-RemoteBranches.ps1
- eng/common/scripts/Helpers/git-helpers.ps1
- eng/pipelines/branch-cleanup.yml
1. Add MicrosoftDocs/AzureRestPreview to the cleanup scripts. There were about 130k branches that were deleted prior to this change. The number of branches in the repository is now at a manageable level.
2. We have a lot of repositories we're deleting branches from and we're also making gh API calls other than branch cleanup. Output some telemetry.
3. If one of the API commands fails, exit the script, don't continue to try and process. The reason being is that if we hit a rate limit we can't continue processing. 
The changes in here, right now, are going to be used for information gathering. There's currently no data of how many API calls are being made when the pipeline runs. Further updates will probably be made depending on the findings.
> Add RestAPISpecsDocsRepos to branch cleanup and update the delete scripts to output limits and telemetry data

- eng/common/pipelines/templates/steps/publish-blobs.yml
- eng/common/scripts/copy-docs-to-blobstorage.ps1
Cleaning this up in order to remove azure-sdk-docs-prod-blob-name from the keyvault. Need to do this first and then I can remove all the references to that value in all the language repos.
> Clean-up publish-blobs.yml to have better defaults

- eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1
Basically, when we're merging a commit into another, we need there to be a "change" in a file so that `test-proxy push` works without any weirdness.
When the first file discovered contained `[` or `]` powershell will break when attempting to add content to the file path. You have to call it out with `LiteralPath` to honor paths with these characters in it.
Sorry for for the inconvenience @jalauzon-msft !
> Ensure assets resolution script handles special-case file paths

- eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
- eng/pipelines/eng-workflows-sync.yml
- eng/pipelines/templates/stages/archetype-sdk-tool-repo-sync.yml
- eng/pipelines/templates/steps/sync-directory.yml
Given we cannot create subfolders under .github\workflow folder and we have repos that want additional workflows then we have in the tools repo we need to setup a file pattern matching for the sync processing to only sync the ones we want to be common.
For now just use the existing *event* pattern but we can move them to another pattern similar to *common* or *sync* in the future as we add more common workflows.
> Add FilePattern support for .github\workflow sync

- src/dotnet/APIView/APIView.sln
- src/dotnet/APIView/APIView/Model/CodeFile.cs
- src/dotnet/APIView/APIView/Model/V2/ReviewLine.cs
- src/dotnet/APIView/APIView/Model/V2/ReviewToken.cs
- src/dotnet/APIView/APIView/Model/V2/TokenKind.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/Program.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/TreeToken/CodeFileBuilder.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CSharpAPIParserTests.csproj
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CodeFileTests.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/PackageDetailsTests.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/ProgramTests.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/TestData.cs
This PR is to modify .NET API review parser to create tokens based on new schema that's outlined in the PR https://github.com/Azure/azure-sdk-tools/pull/8816
Goal is to simplify token schema structure. Above PR also has sample token JSON file created as per the schema.
PR for changes to token models: https://github.com/Azure/azure-sdk-tools/pull/8852
> .NET API review parser changes to use new token schema

- src/dotnet/APIView/APIViewWeb/LeanControllers/ReviewsController.cs
- src/dotnet/APIView/APIViewWeb/Repositories/BlobCodeFileRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/Interfaces/IBlobCodeFileRepository.cs
Code file object is cached that gets altered when rendering the diff. We cannot use the cache as it is when code file is using tree style parser. This issue was already fixed in the production by my recent change broke this due to added caching. Removing the caching logic to resolve processing corrupted code files.
> Avoid code file caching when for new tree style code files

- src/dotnet/APIView/APIView/Model/V2/ReviewToken.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CodeFileTests.cs
RenderClasses were not included in serialized code file due to missing get and set. PR also has the added test case to verify render class is set for all navigation nodes.
> Include RenderClasses in serialized JSON code file

- src/go/cmd/download.go
- src/go/cmd/module.go
- src/go/cmd/pkg.go
- src/go/cmd/pkg_test.go
- src/go/cmd/testdata/test_package_name/test_package_name@v1.0.0/go.mod
- src/go/cmd/testdata/test_package_name/test_package_name@v1.0.0/subpackage/test.go
- src/go/cmd/testdata/test_package_name/test_package_name@v1.0.0/test.go
This fixes a couple problems causing `apiviewgo` to fail when run by APIView:
- `os.UserHomeDir` returns an unwriteable path on APIView's production VMs. Fixed this by instead (trying to) write to `os.TempDir` (%TMPDIR% is writeable on those VMs)
- Code for computing a package's name relative to its module (e.g. "azcore/log") assumed the module name appears exactly once in the module's disk path and that the disk path includes the module path verbatim. Neither assumption holds true for downloaded code, and in general disk and module paths are unrelated. Fixed this by making module and disk path separate parameters of `NewPkg()` (this is much simpler than having `NewPkg()` figure out the difference)
> Fix apiviewgo download paths

- eng/common/scripts/Save-Package-Properties.ps1
Allow save-package-properties to exit 0 when PRs produce no package changes
> Allow save-package-properties to exit 0

- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
Doc nodes are removed incorrectly from collected document map when remapping node id hashed for documents lines in diff view. We don't need to update the map if old and new hash ids are same. This bug was incorrectly removing entries from map.
> Skip documentation node id remapping if node is not changed

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/JsonComparer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordSession.cs
> Compare json object values instead of byte streams when matching bodies that are content-type `json`

- tools/pylint-extensions/azure-pylint-guidelines-checker/CHANGELOG.md
- tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
- tools/pylint-extensions/azure-pylint-guidelines-checker/tests/test_pylint_custom_plugins.py
This pull request extends code `C4749` of `azure-pylint-guidelines-checker` to also disallow imports of the [`httpx`](https://pypi.org/project/httpx/) package, "a fully featured HTTP client library for Python 3".
This change should have **no** impact on any SDK currently in the azure-sdk-for-python (as of commit [99bfd773](https://github.com/Azure/azure-sdk-for-python/tree/99bfd773d83b7e4d3155781ac432e3bc1c2d9fb8)), since no SDK directly imports `httpx`.
My team is currently working on adding a new SDK to azure-sdk-for-python, and I noticed that `C4749` wasn't flagging our use of `httpx` that would need to be changed per the Azure SDK guidelines around networking imports.
cc: @l0lawrence
> feat(pylint): Add httpx as a blocked networking import

- src/go/cmd/download.go
- src/go/cmd/module.go
- src/go/cmd/pkg.go
- src/go/cmd/pkg_test.go
- src/go/cmd/testdata/test_package_name/test_package_name@v1.0.0/go.mod
- src/go/cmd/testdata/test_package_name/test_package_name@v1.0.0/subpackage/test.go
- src/go/cmd/testdata/test_package_name/test_package_name@v1.0.0/test.go
* apiviewgo downloads to os.TempDir instead of os.UserHomeDir
PR to move changes to main branch from hotfix branch for Go parser fix in the PR https://github.com/Azure/azure-sdk-tools/pull/8856
> Fix apiviewgo download paths (#8856)

- src/dotnet/APIView/ClientSPA/src/app/_workers/apitree-builder.worker.spec.ts
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CodeFileTests.cs
More automated testing for .NET API review parser.
> .NET API review parser tests

- src/dotnet/APIView/APIViewWeb/HostedServices/ReviewBackgroundHostedService.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
Changes to run update of a revision code file to new parser in read only mode so it will run the test to verify if a revision can be upgraded without actually modifying the metadata.
> Apiview revision upgradability to new parser version test

- src/dotnet/APIView/APIViewWeb/Languages/CSharpLanguageService.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/TreeToken/CodeFileBuilder.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CSharpAPIParserTests.csproj
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CodeFileTests.cs
Fixes following issue in attribute line 
Attribute line is shown as `[AttributeUsage(AttributeTargets . Class ) ]` instead of `[AttributeUsage(AttributeTargets.Class )]`
> Fix issue in attribute line with attribute class name

- src/dotnet/APIView/APIViewWeb/DTOs/CommentUpdatesDto.cs
- src/dotnet/APIView/APIViewWeb/Helpers/APIHelpers.cs
- src/dotnet/APIView/APIViewWeb/Hubs/SignalRHub.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/CommentsController.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/ChangeHistory.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/CommentItemModel.cs
- src/dotnet/APIView/ClientSPA/package-lock.json
- src/dotnet/APIView/ClientSPA/package.json
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/conversations/conversations.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/comment-thread/comment-thread.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_dtos/commentThreadUpdateDto.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/commentItemModel.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/config/config.service.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/revisions/revisions.service.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/revisions/revisions.service.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/signal-r/signal-r.service.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/signal-r/signal-r.service.ts
- src/dotnet/APIView/ClientSPA/src/app/app.component.ts
- src/dotnet/APIView/ClientSPA/src/assets/config.json
- src/dotnet/APIView/ClientSPA/src/development.proxy.conf.json
- Add RealTime Comment Updates
> Add RealTime Comment Updates

- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/common.ps1
From @hallipr dealing with rust implementation.
> Pull Request automation feedback

- src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/PullRequestsController.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/ReviewsController.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/pullRequestModel.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/pull-requests/pull-requests.service.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/pull-requests/pull-requests.service.ts
- Show Associated Pull Request Information
> Surface Associated Pull Request Information

- eng/common/pipelines/templates/steps/save-package-properties.yml
when ServiceDirectory is empty, powershell doesn't parse this command correctly
```
filePath: ${{ parameters.ScriptDirectory }}/Save-Package-Properties.ps1
arguments: >
-ServiceDirectory ${{parameters.ServiceDirectory}}
-OutDirectory ${{ parameters.PackageInfoDirectory }}
```
It's parsed like
```
Save-Package-Properties.ps1 -ServiceDirectory -OutDirectory ...
```
> add quotes to powershell args

- eng/common/scripts/Package-Properties.ps1
Get-PrPkgProperties was adding a package to $packagesWithChanges for every matched file in the pr diff.   To prevent duplicate entries, we break the for loop on the first matched file.
If the input path didn't start with $RepoRoot, the key function `<path>.Replace($RepoRoot, "").SubString(1)` was removing the first character of a relative path.
`sdk/some/package` => `dk/some/package`
`.TrimStart('\/')` will remove the starting path separator only if it exists.
> Avoid adding the same package twice, use TrimStart instead of substring

- src/dotnet/APIView/APIViewWeb/LeanControllers/ReviewsController.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/INotificationManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/NotificationManager.cs
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/review.ts
- src/dotnet/APIView/ClientSPA/src/app/_services/reviews/reviews.service.ts
- Add Subscribe Switch to Review Page
> 073124.02/subscribe

- eng/pipelines/tools-repo-versioning.yml
The default branch for autorest.csharp is being renamed from feature/v3 to main
> Rename autorest.csharp branch feature/v3 to main

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/AzurePipelines/AzurePipelinesProcessor.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/AzurePipelines/MissingAzurePipelineRunsWorker.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Configuration/PeriodicProcessSettings.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Configuration/PipelineWitnessSettings.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Configuration/PostConfigureSettings.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Controllers/GitHubEventsController.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/GitHubActions/GitHubActionProcessor.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/GitHubActions/MissingGitHubActionsWorker.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.development.json
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.json
- tools/pipeline-witness/monitored-repos.json
This creates the `PeriodicLockingBackgroundService` class to encapsulate the logic of periodically running a process in a single worker instance only if the worker is able to establish a lock on a central cosmos document.  It continually renews the lock while the processing is handled by a  ProcessAsync implementation. 
This change also starts paving the way for GitHub Actions logging by moving the Azure Pipelines related classes into 
their own namespace.
> Add support for missing build processing

- eng/common/TestResources/SubConfig-Helpers.ps1
- eng/common/TestResources/build-test-resource-config.yml
- eng/common/TestResources/deploy-test-resources.yml
These errors are annoying to debug because we just see indirect null object failures when expecting a json string and receiving the `$(<var name>)` literal from devops.
CC @deyaaeldeen
> Add descriptive error when variable groups are not added to pipeline

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
Removed dependency of @autorest/csharp for @autorest/openapi-to-typespec
> Remove dependency of @autorest/csharp

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/utils.ts
- tools/js-sdk-release-tools/src/hlc/utils/automaticGenerateChangeLogAndBumpVersion.ts
- tools/js-sdk-release-tools/src/test/changelog/changelogGenerator.test.ts
Problem: always read stable version's changelog
Fix: read beta version's changelog if the current package is beta
> Fix read original changelog content issue

- src/dotnet/APIView/ClientSPA/angular.json
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/comment-thread/comment-thread.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/comment-thread/comment-thread.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/comment-thread/comment-thread.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_helpers/common-helpers.ts
- src/dotnet/APIView/ClientSPA/src/app/_modules/shared/shared-app.module.ts
- src/dotnet/APIView/ClientSPA/src/app/_workers/apitree-builder.worker.ts
- src/dotnet/APIView/ClientSPA/src/app/app.component.html
- src/dotnet/APIView/ClientSPA/src/app/app.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/app.module.ts
- src/dotnet/APIView/ClientSPA/src/ng-prime-overrides.scss
- Add feature for navigating comments and diffs on the review page.
> 080624.01/comment and diff navigation

- eng/scripts/github-statistics.ps1
Adding a script to track github statistics across our repositories
> Add github statistics script

- tools/pipeline-witness/infrastructure/bicep/logsResourceGroup.bicep
If the requestMessage property isn't included on the managed private endpoint resource, the resource provider interprets that as setting the requestMessage to null.    The requestMessage property can't be changed after creation, so you must include the property and it must match the existing value if the resource already exists.
> Include empty requestMessage for private endpoint

- eng/common/pipelines/templates/steps/publish-1es-artifact.yml
Disabling this to avoid a bunch of warnings during these builds
> Disable sbom generation for forked PR builds

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/GitHubActions/MissingGitHubActionsWorker.cs
- tools/pipeline-witness/ci.yml
Currently, GitHub gap filling processes repos in a foreach loop without any exception handling.  This causes the process to break on the first missing repo or repo with auth issues.   Adding a try/catch with error logging ensures that all of the repos are attempted while still reporting failures to App Insights.
> Put repo processing in try/catch

- eng/common/scripts/Package-Properties.ps1
This PR does two things:
1) Makes us able to discern when a package is directly included or included as a validation package (`IncludedForValidation`, defaults to `false`)
2) ~~Add `BuildDocs` property, which is calculated when a package props class is instantiated.~~
- ~~I have a fairly strong suspicion, because of the necessary inclusion of `Install-ModuleIfNotInstalled "powershell-yaml" "0.4.1" | Import-Module`, that we will just want to put this artifact parsing in the [docs namespace update directly.]~~(https://github.com/Azure/azure-sdk-for-python/blob/main/eng/scripts/Save-Package-Namespaces-Property.ps1)
I ripped out `BuildDocs` because it implies that `powershell-yaml` will become a base requirement of our `Save-Package-Properties` namespace. We ALREADY see some failures to …
> Add basic reason why package has been included to Package-Properties

- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter.Tests/Azure.Sdk.Tools.CodeownersUtils.Tests.csproj
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter/Azure.Sdk.Tools.CodeownersLinter.csproj
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Azure.Sdk.Tools.CodeownersUtils.csproj
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Azure.Sdk.Tools.GitHubEventProcessor.Tests.csproj
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/Azure.Sdk.Tools.GitHubEventProcessor.csproj
- tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore/GitHubTeamUserStore.csproj
- tools/identity-resolution/identity-resolution.csproj
- tools/notification-configuration/notification-creator.Tests/Azure.Sdk.Tools.NotificationConfiguration.Tests.csproj
- tools/notification-configuration/notification-creator/Azure.Sdk.Tools.NotificationConfiguration.csproj
- tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Azure.Sdk.Tools.PipelineOwnersExtractor.csproj
net6 hits EOL in November, 2024 and this is to update things to net8. This is only the first round of projects. This particular set is related because of the use of CodeownersUtils. None of these projects required code changes from the runtime update from 6->8
Contributes to https://github.com/Azure/azure-sdk-tools/issues/8606
> Update projects targeting net6 to net8 - part 1

- eng/pipelines/templates/variables/globals.yml
This was the [PR](https://github.com/Azure/azure-sdk-tools/pull/8991) that updated the tools and caused new versions to be processed. This PR updates the versions Azure.Sdk.Tools.NotificationConfiguration and Azure.Sdk.Tools.PipelineOwnersExtractor to install based the publish from the first PR.
> Tool version updates for net6 to net8 updates part 1

- eng/common/pipelines/codeowners-linter.yml
This was the [PR](https://github.com/Azure/azure-sdk-tools/pull/8991) that updated the tools and caused new versions to be processed. This just updates the linter pipeline to use the new published version.
> Update CodeownersLinter for net6 to net8 update

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
This was the [PR](https://github.com/Azure/azure-sdk-tools/pull/8991) that updated the tools and caused new versions to be processed. This just updates the github event processor yml files to use the new published version.
> Update installed event processor version for net6 to net8 update

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/npmUtils.ts
- tools/js-sdk-release-tools/src/common/utils.ts
- tools/js-sdk-release-tools/src/hlc/utils/automaticGenerateChangeLogAndBumpVersion.ts
- tools/js-sdk-release-tools/src/llc/utils/generateChangelog.ts
- tools/js-sdk-release-tools/src/llc/utils/utils.ts
- tools/js-sdk-release-tools/src/test/npm/npm.test.ts
- tools/js-sdk-release-tools/src/utils/version.ts
Fix: https://github.com/Azure/azure-sdk-tools/security/dependabot/137
> Remove ts-common/azure-js-dev-tools to solve security issue

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/Azure.ClientSdk.Analyzers.Tests.csproj
Azure.ClientSdk.Analyzers.Tests was still using net6 as one of its targets which hits EOL in November of 2024. After updating the net6 target to net8 all of the tests targeting net8, and the others targeting net472, ran without issue. The other projects in the solution target netstandard2.0 but the test project cannot.
> Update Azure.ClientSdk.Analyzers.Tests from net6 to net8

- tools/assets-automation/assets-maintenance-tool/Azure.Sdk.Tools.Assets.MaintenanceTool.Tests/Azure.Sdk.Tools.Assets.MaintenanceTool.Tests.csproj
- tools/assets-automation/assets-maintenance-tool/Azure.Sdk.Tools.Assets.MaintenanceTool/Azure.Sdk.Tools.Assets.MaintenanceTool.csproj
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Azure.Sdk.Tools.TestProxy.Tests.csproj
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/MatcherTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/RecordTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Azure.Sdk.Tools.TestProxy.csproj
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/Exceptions/HttpException.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SecretScanner.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/TestRecordingMismatchException.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
- tools/test-proxy/ci.yml
- tools/test-proxy/sample-clients/net/http-client/Azure.Sdk.Tools.TestProxy.HttpClientSample.csproj
- tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineSample/Azure.Sdk.Tools.TestProxy.HttpPipelineSample.csproj
- tools/test-proxy/sample-clients/net/http-pipeline/Azure.Sdk.Tools.TestProxy.HttpPipelineTestsExample/Azure.Sdk.Tools.TestProxy.HttpPipelineTestsExample.csproj
- tools/test-proxy/sample-clients/net/storage-blob/Azure.Sdk.Tools.TestProxy.StorageBlobSample.csproj
I was going to update TestProxy by itself in its own PR but, unfortunately, Azure.Sdk.Tools.Assets.MaintenanceTool.sln has a dependency on TestProxy which required both projects to be updated.
I removed the conditional includes from the TestProxy since net5 is deader than disco. When upgrading the framework to Net8 I also updated Azure.Core and Microsoft.VisualStudio.Web.CodeGeneration.Design to their latest RTM versions.
- `using Microsoft.Build.Tasks;` was removed because it no longer exists but was also a superfluous using.
- response.Headers.Add is now response.Headers.Append
- ['Exception.Exception(SerializationInfo, StreamingContext)' is now obsolete](https://github.com/dotnet/docs/issues/34893)
I also updated the version of Azure.Code and Azure.Storage.Blobs …
> Update TestProxy from Net6 to Net8

- eng/common/pipelines/templates/steps/verify-readmes.yml
What happens if a task above the call to `verify-readmes` fails? Well before this change we would SKIP populating the scan paths, which would then also cause the call to verify readmes to _always_ fail because of no populated ScanPath argument.
This PR matches up the condition to avoid this issue.
> Ensure that ScanPaths are always populated in `verify-readmes`

- eng/common/scripts/Package-Properties.ps1
What happens when we don't have metadata for a package that we want to include? Welp we're screwed! I don't want to call Get-AllPkgProperties in my custom function when we CAN PASS IT IN.
> Discovered another issue with `AdditionalValidationPackagesFromPackageSetFn`

- tools/version-guard/Microsoft.Azure.Sdk.Tools.VersionGuard/Microsoft.Azure.Sdk.Tools.VersionGuard.csproj
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter.Tests/Azure.Sdk.Tools.WebhookRouter.Tests.csproj
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Azure.Sdk.Tools.WebhookRouter.csproj
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/RouteConfigurationException.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/Router.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/RouterAuthorizationException.cs
- tools/webhook-router/Azure.Sdk.Tools.WebhookRouter/Routing/RouterException.cs
net6 hits EOL in November, 2024 and this is to update things to net8. This is the third round of projects. 
Contributes to https://github.com/Azure/azure-sdk-tools/issues/8606
> Update projects targeting net6 to net8 - part3

- tools/agent-time-extractor/AgentTimeExtractor/AgentTimeExtractor.csproj
- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Azure.Sdk.Tools.HttpFaultInjector.csproj
- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/FaultInjectingMiddleware.cs
- tools/http-fault-injector/sample-clients/net/storage-blobs/Azure.Sdk.Tools.HttpFaultInjector.StorageBlobsSample.csproj
- tools/http-fault-injector/sample-servers/net/http-server/Azure.Sdk.Tools.HttpFaultInjector.HttpServerSample.csproj
- tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen.Tests/Azure.SDK.Management.ChangelogGen.Tests.csproj
- tools/net-changelog-gen-mgmt/Azure.SDK.Management.ChangelogGen/Azure.SDK.Management.ChangelogGen.csproj
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation.Tests/Azure.Sdk.Tools.PerfAutomation.Tests.csproj
- tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Azure.Sdk.Tools.PerfAutomation.csproj
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Azure.Sdk.Tools.PipelineGenerator.csproj
- tools/pixel-server/PixelServer/PixelServer.csproj
- tools/pixel-server/PixelServer/Startup.cs
- tools/secret-management/Azure.Sdk.Tools.AccessManagement.Tests/Azure.Sdk.Tools.AccessManagement.Tests.csproj
- tools/secret-management/Azure.Sdk.Tools.AccessManagement/Azure.Sdk.Tools.AccessManagement.csproj
- tools/secret-management/Azure.Sdk.Tools.SecretManagement.Cli/Azure.Sdk.Tools.SecretManagement.Cli.csproj
- tools/secret-management/Azure.Sdk.Tools.SecretManagement.Cli/Commands/RotateCommand.cs
- tools/secret-management/Azure.Sdk.Tools.SecretManagement.Cli/Commands/StatusCommand.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Azure/Azure.Sdk.Tools.SecretRotation.Azure.csproj
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Configuration/Azure.Sdk.Tools.SecretRotation.Configuration.csproj
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Configuration/RotationConfiguration.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Core/Azure.Sdk.Tools.SecretRotation.Core.csproj
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Core/RotationPlan.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Core/TimeProvider.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Tests/Azure.Sdk.Tools.SecretRotation.Tests.csproj
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Tests/CoreTests/RotationConfigurationTests.cs
- tools/secret-management/Azure.Sdk.Tools.SecretRotation.Tests/CoreTests/RotationPlanTests.cs
- tools/secret-management/Directory.Build.props
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator.Tests/Azure.Sdk.Tools.SnippetGenerator.Tests.csproj
- tools/snippet-generator/Azure.Sdk.Tools.SnippetGenerator/Azure.Sdk.Tools.SnippetGenerator.csproj
net6 hits EOL in November, 2024 and this is to update things to net8. This is the second round of projects. 
About tools/pixel-server/PixelServer/Startup.cs: These warnings should have been fixed when the project was upgraded to Net6 and weren't. I'm fixing them now.
- using Microsoft.Extensions.Hosting; was required to use IsDevelopment()
- The UseMVC now requires options => options.EnableEndpointRouting = false set in the services.AddMvcCore call
Contributes to https://github.com/Azure/azure-sdk-tools/issues/8606
> Update projects targeting net6 to net8 - part 2

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
- eng/pipelines/pipeline-generation-single.yml
- eng/pipelines/pipeline-generation.yml
When using the template in prepare-pipelines we need to use `$(Build.SourceVersion)` as our checkout so that people can trigger on their pull requests. 
For the pipeline generation automation pipelines we want to default those to the main branches in the sdk repos.
> Fix sparse-checkout commit

- tools/azure-rest-api-specs-examples-automation/go/validate.py
Get it work first.
Task to upgrade the golang runtime to 1.22.0 https://github.com/Azure/azure-sdk-tools/issues/9019
> examples-automation, use goimports 0.24.0

- tools/http-fault-injector/sample-clients/net/http-client/Azure.Sdk.Tools.HttpFaultInjector.HttpClientSample.csproj
net6 hits EOL in November of 2024, this updates the project to net8.
Note: This was apparently missed when I'd updated the http-fault-injector's other projects last week.
Contributes to https://github.com/Azure/azure-sdk-tools/issues/8606.
> Update http-fault-injector's HttpClientSample from Net6 to Net8

- tools/stress-cluster/services/Stress.Watcher/src/Stress.Watcher.csproj
- tools/stress-cluster/services/Stress.Watcher/tests/Stress.Watcher.Tests.csproj
net6 hits EOL in November, 2024 and this is to update things to net8.
Contributes to https://github.com/Azure/azure-sdk-tools/issues/8606
> Update Stress.Watcher from net6 to net8

- eng/common/pipelines/templates/steps/verify-changelogs.yml
- eng/common/scripts/Verify-ChangeLogs.ps1
Last blocker :tm: for pipelinev3 in the python repo. Got clean runs other than failing changelog verification against packages that are no longer published.
~~Along the lines of this PR...should we have a `ShouldInvokeCHeck` function that takes an `artifacts` property to check for? EG `skipVerifyChangelog` not true, `publishDocs` not `false. It's not necessarily common for each repo.~~
- ~~If in `CI`, `yq` will be present. `yq` a discovered `ci.yml` on the fly~~
- ~~If not in CI, use PSModules and install the powershell module for yml~~
~~If folks are good with above algo, I'll move the `ShouldInvokeCheck` to `common.ps1`. Otherwise this PR should work as-is.~~
The above may still stand, but we're just calling `yq` and erroring if not present on invoking machine in this PR now.
> Don't verify changelogs for packages not present in Artifacts

- .github/dependabot.yml
bugfix for dependabot updates errors for rushjs https://github.com/Azure/azure-sdk-tools/actions/workflows/dependabot/dependabot-updates
> [dependabot-updates] Overriding the default behavior with dependabot.yml

- tools/pipeline-witness/monitored-repos.json
It was added as Azure/typespec
> Fix naming for Azure/typespec-azure

- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter/Program.cs
> Improve DevOps logging for code owners linter

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Azure.Sdk.Tools.PipelineWitness.csproj
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/AzurePipelines/AzurePipelinesProcessor.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Startup.cs
Backround workers are persistent and hold a reference to a Processor.
Processors hold VssConnections and VssConnections hold a reference to a credential.  When that credential is baked around a token, the whole token -> credential -> connection -> processor -> worker chain needs to be recreated when the token expires.
We weren't doing this and the service would throw vss unauthorized exceptions when the token expired after 24 hours.  Rather than reconstruct the whole chain or shim factories in the mix, we can use the preview version of the ado client libraries that support Azure Identity credentials and dynamic token requests.
> Use new ADO credential type for connections over azure credentials

- eng/common/pipelines/codeowners-linter.yml
This updated version of the CodeownersLinter is for the following [PR](https://github.com/Azure/azure-sdk-tools/pull/9040) which improves DevOps logging for the linter in the following ways:
1. Add the linter error messages to the run errors so they're immediately available when someone looks at the run instead of having to open the step.
2. DevOps will show the first few errors as annotations (4 but the first error with the aka.ms link means it'll only show the first 3 as annotations)
> Update CodeownersLinter to 1.0.0-dev.20240926.2

- eng/common/scripts/Update-DocsMsPackages.ps1
There was a `ValidatePackageForOnboarding` declared in a `Language-Settings.ps1` file at the time of the onboarding refactor. This uses a different name for the function which doesn't end in "2": `PackageIsValidForDocsOnboarding` 
Code search of potentially impacted repositories shows no collisions: 
* https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-net%20PackageIsValidForDocsOnboarding&type=code
* https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-net%20PackageIsValidForDocsOnboarding&type=code
* https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-js%20PackageIsValidForDocsOnboarding&type=code
* https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-python%20PackageIsValidForDocsOnboarding&type=code
* https://github.com/search?q=repo%3AAzure%2Fazure-sdk-tools%20Packa …
> Docs onboarding cleanup final: Rename ValidatePackageForOnboarding2

- tools/pipeline-witness/infrastructure/kusto/tables/GitHubActionsLogLine.kql
The field has already been updated in the database.  This will prevent reverting the field to text on deployment.
> Timestamp should be a date field

- eng/common/TestResources/New-TestResources.ps1
Environment variable values that have semicolons get cut off at the ;. Adding quotes around the values ensures that the entire value is set correctly + can easily be copy/pasted.
> Update New-TestResources.ps1 to add quotes around shell envvar

- tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
- tools/stress-cluster/cluster/azure/cluster/cluster.bicep
- tools/stress-cluster/services/Stress.Watcher/Dockerfile
- tools/stress-cluster/services/Stress.Watcher/src/NamespaceEventHandler.cs
- tools/stress-cluster/services/Stress.Watcher/src/Program.cs
The original implementation was skipping lookups to see if credentials already existed, on the assumption that deletion was always being handled. This resulted in multiple credentials being created for the same namespace.
Instead we can simply poll to make sure deleted namespaces don't continue to take up a federated identity credential slot as a failsafe. We also sync credential state on startup and keep an in-memory cache, so that namespace deletions/creations re-use existing credentials. There could be some edge cases here with the cache, but I think it's a better trade-off than always querying the managed identity pool every time a namespace is created, as the operation is slow and can increase stress deploy times (we need to wait on completion before deploying otherwise there is a …
> [stress] Sync namespace federated credentials periodically and on startup

- tools/stress-cluster/cluster/azure/cluster/storage.bicep
- tools/stress-cluster/cluster/azure/main.bicep
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/images/test-resource-deployer/Dockerfile
- tools/stress-cluster/services/Stress.Watcher/Dockerfile
Run yum update in stress images
> Run yum update in stress images. Remove account key from bicep

- eng/common/TestResources/deploy-test-resources.yml
This will allow us to not need to provide static subscription data files and keep them in sync with the service connection. 
Once we adopt this new method, we can delete all the sub config files we have.
> Export the subscription data from the service connection

- tools/http-fault-injector/Azure.Sdk.Tools.HttpFaultInjector/Azure.Sdk.Tools.HttpFaultInjector.csproj
- tools/http-fault-injector/Dockerfile
- tools/stress-cluster/services/otelcollector/Dockerfile
- tools/stress-cluster/services/otelcollector/otel-builder.yml
Fix image builds for http fault injector and otel collector
> Fix container image builds for http fault injector and otel collector

- eng/common/TestResources/deploy-test-resources.yml
Example usage: https://github.com/Azure/azure-sdk-for-go/pull/23549
> Persist oidc env vars in deploy template

- eng/common/TestResources/deploy-test-resources.yml
Use equality function check for persist oidc token step
This is breaking the conditional evaluation of `${{ if parameters.PersistOidcToken }}` because it is getting stringified.
> Use equality function check for persist oidc token step

- tools/apiview/parsers/apiview-treestyle-parser-schema/CodeFile.json
- tools/apiview/parsers/apiview-treestyle-parser-schema/main.tsp
APIView Token schema changes to support custom navigation panel
> Include optional navigation tree in JSON token schema to support custom navigation panel

- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Utils.cs
- Resovle bug in swagger when some definitions are deserialized as schema.
> Swagger APIView Bugfix

- src/dotnet/APIView/APIView/Model/CodeFile.cs
- src/dotnet/APIView/ClientSPA/src/app/_models/navigationTreeModels.ts
- src/dotnet/APIView/ClientSPA/src/app/_workers/apitree-builder.worker.ts
Hive the nodes if a corresponding code line is not visible in case of custom navigation tree. This PR also has the changes to exclude documentation when converting tokens from old model to streamline the token structure. Old token model has incorrect documentation line with partial code line.
> Hide the navigation nodes for unmodified nodes in diff

- tools/azure-rest-api-specs-examples-automation/directory/examples_dir.py
- tools/azure-rest-api-specs-examples-automation/directory/test_examples_dir.py
fix https://github.com/Azure/azure-sdk-tools/issues/9150
1. raise Error, if no tsp-location.yaml found (it happens to 1 js package, it is their problem but we need to guard against this)
2. fix bug that automation didn't scope the api-version when searching the typespec example JSON
> sample-automation, bug fix on wrong api version folder

- src/dotnet/APIView/APIViewWeb/Controllers/AccountController.cs
- src/dotnet/APIView/APIViewWeb/Helpers/APIHelpers.cs
- src/dotnet/APIView/APIViewWeb/Helpers/URlHelpers.cs
- src/dotnet/APIView/APIViewWeb/Startup.cs
- src/dotnet/APIView/ClientSPA/src/app/_guards/auth.guard.ts
Resolves https://github.com/Azure/azure-sdk-tools/issues/8762
> Add redirect URL to login requests

- eng/scripts/live-test-resource-cleanup.ps1
Currently we are hitting an error in the clean-up which is preventing any clean-up from happening.
This update handles the empty/null alias.
> Handle empty/null alias in function

- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
Changes to upgrade reviews on the fly for two more main entry points from old model.
> Upgrade the revisions on the fly

- tools/apiview/parsers/js-api-parser/CHANGELOG.md
- tools/apiview/parsers/js-api-parser/package.json
- tools/apiview/parsers/js-api-parser/src/generate.ts
- tools/apiview/parsers/js-api-parser/src/jstokens.ts
- add missing `type` keyword
- set `IsContextEndLine: true` for closing brace
> [apiview-js-parser] fix some bugs

- eng/common/TestResources/New-TestResources.ps1
Set resource group env variable early so remove always works
> Set resource group env variable early so remove always works

- eng/common/scripts/Package-Properties.ps1
Eliminating messages like [this one](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4230273&view=logs&j=1dca5ef1-3811-5712-152d-1052a5815ba2&t=ec532db5-809f-5036-2be0-84730b472e44&l=192)
> Handle non-presence of artifacts without exception

- eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
Includes whitespace changes
Fixes https://github.com/Azure/azure-sdk-tools/issues/5433
Testing. Left is the live site, right is the same page with escaped parentheses in the filename:
> Escape parentheses in includes to fix issues in publishing

- eng/common/pipelines/templates/steps/save-package-properties.yml
It has been really nice in the `python` repo to maintain the _same_ package properties code, but only activate the new diff logic if the service directory is one we expect.
EG: sdk/pullrequest.yml -> passes servicedirectory `auto`, we call `Save-Package-Properties.yml` with the ServiceDirectoryFilter of `auto`. This ensures the new logic will only trigger if running from a specific servicedirectory.
In the case where we are running _both_ alongside each other for integration checks, this will allow us to use the save-package-properties template while still merging to `main`. Any of the `<language> - <service> - ci` jobs will resolve the same targeted set that they _currently_ do if we set this to `auto` or some other value that only the `pullrequest` build will provide.
> Add ability to not trigger `PR` diff generation if the incoming service isn't `auto`

- doc/common/matrix_generator.md
- eng/common-tests/matrix-generator/samples/matrix-test.yml
- eng/common/TestResources/build-test-resource-config.yml
- eng/common/TestResources/deploy-test-resources.yml
- eng/common/TestResources/remove-test-resources.yml
- eng/pipelines/live-test-cleanup.yml
We no longer want to default the configuration and instead default from the service connection which had the info we need.
> Remove default sub config sub-config-azure-cloud-test-resources

- eng/common/pipelines/templates/steps/create-apireview.yml
Fix the issue in apiview pipeline step when branch name has &.
> Support branch name with special char in create review step

- eng/common/scripts/Helpers/Package-Helpers.ps1
- eng/common/scripts/Package-Properties.ps1
All I'm doing here is refactoring some of the code that was in PackageProps, specifically around Yaml loading and processing, hoisting it out to be common and usable outside of that class. Specifically, I'm going to be using the yaml loading and processing for the Get-AllPackageInfoFromRepo I'm implementing for Java.
The changes are as follows:
1.  LoadAndCompatibleConvertFrom-Yaml (this was renamed to LoadFrom-Yaml as per feedback) - this was originally part of the PackageProps::ParseYmlForArtifact function. I moved the Test-Path verification of the yml file and try/catch surrounding the call to CompatibleConvertFrom-Yaml into a common function. That way anyone using the CompatibleConvertFrom-Yaml doesn't have to dupe the checks or the try catch.
2. GetValueSafelyFrom-Yaml - this was …
> Refactor PackageProps to make the Yaml loading and processing methods common

- .github/CODEOWNERS
Update the code owner of sdk-testgen to enable more effective code merge.
Remove Ray as he no longer works in this area.
> Update CODEOWNERS of sdk-testgen

- tools/azure-rest-api-specs-examples-automation/directory/examples_dir.py
- tools/azure-rest-api-specs-examples-automation/directory/test_examples_dir.py
1. "directory" in tsp-location could be windows format (with `\`)
2. golang has invalid path like `D:/w/Azure/azure-sdk-for-go/sdk/resourcemanager/computefleet/armcomputefleet/TempTypeSpecFiles/AzureFleet.Management/examples/2024-11-01/Fleets_Update.json` in file, due to bug in codegen -- this result in pipeline failure on doc site
They had fixed, but we'd better to have more protection.
ref https://github.com/Azure/azure-rest-api-specs-examples/pull/5066
> examples-automation, handle corner cases and invalid cases from upstream

- eng/common/scripts/stress-testing/find-all-stress-packages.ps1
- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
- tools/stress-cluster/chaos/README.md
Allow default matrix selection override
> [stress testing] Allow default matrix selection override

- eng/common/pipelines/templates/jobs/perf.yml
Run the tests under the same federated auth used to deploy the tests and setup the variables needed to configure AzurePipelineCredential.
> Run perf tests under federated auth

- eng/common/pipelines/templates/jobs/generate-job-matrix.yml
- eng/common/scripts/Helpers/Package-Helpers.ps1
- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
This PR addresses a lot of the boilerplate code that would be necessary to distribute packages to one or multiple matrix files.
We allow our users to customize their platform using `ci.yml -> MatrixConfigs` params, but we _don't_ honor those in the PR build (which is a single unified matrix).
This PR allows the PR build to automatically use the correct matrix. Here it is [in use.](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4283836&view=results)
Pardon the long runtime, I have further fixes from my other sdk-for-js branch that aren't there, which is why the builds are timing out. Nothing to do with this matrix logic 👍
> `Create-PrJobMatrix`

- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
- eng/common/scripts/job-matrix/job-matrix-functions.ps1
Resolving: https://github.com/Azure/azure-sdk-tools/pull/9281/commits/2c03facb7fd54a5888cb4e7c20aee6b6c6bebf18#r1823660311
And due to the fact that because we were nulling out the matrix configs, we weren't iterating over it and calling GenerateMatrixForConfig.
If not using this PR, we get: https://dev.azure.com/azure-sdk/public/_build/results?buildId=4284719&view=logs&j=76992fd1-2312-5fae-7c45-7baba86b87ae&t=6c294a88-3151-521e-fcd8-a6c587ba9418
> Fix Integration Issue w/ `Create-PRJobMatrix`

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/README.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
- tools/tsp-client/src/index.ts
> Expose fullyCompatible parameter of converter

- eng/common/scripts/Helpers/Resource-Helpers.ps1
- eng/pipelines/live-test-cleanup-template.yml
Reduce unnecessary delete calls to ARM for storage accounts
> Reduce unnecessary delete calls to ARM for storage accounts

- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
I was separating package names by `-`. How did I even introduce that bug.
> Update batch title, set variable with appropriate separation

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/AzurePipelines/AzurePipelinesProcessor.cs
- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/AzurePipelines/BuildCompleteQueueWorker.cs
Because public builds don't have permission to edit their own tags but they can add build attachments, we use an attachment to hold "additional tags" and process them in Pipeline Witness
> Add AdditionalTags processing

- eng/common/scripts/Package-Properties.ps1
This PR will enable PR invocations of `generate-job-matrix` won't crash when the files don't actually exist on disk.
My only concern is the following scenario:
I have some FUD around a scenario where a `PkgProps` file is generated on `windows` and then we check `-like PkgProps.DirectoryPath` against a path checked out on a different OS.
> Remove a resolve-path from `Get-PrPkgProperties`

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
- eng/pipelines/templates/jobs/stress-cluster-provision.yml
- eng/pipelines/templates/jobs/stress-test-release.yml
- tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
- tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Chart.lock
- tools/stress-cluster/chaos/examples/parallel-pod-example/Chart.lock
- tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
- tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
- tools/stress-cluster/cluster/azure/cluster/acr.bicep
- tools/stress-cluster/cluster/azure/cluster/cluster.bicep
- tools/stress-cluster/cluster/azure/cluster/workloadapproles.bicep
- tools/stress-cluster/cluster/azure/main.bicep
- tools/stress-cluster/cluster/azure/parameters/prod.json
- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.lock
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
- tools/stress-cluster/cluster/provision.ps1
[stress testing] Move prod cluster to TME subscription
> [stress testing] Move prod cluster to TME subscription

- eng/common/scripts/Package-Properties.ps1
Until we fix up the loop for usage of `yq` vs `ConvertFrom-Yaml` within `Package-Properties.ps1`.
> Disable `InitializeCIArtifacts` on Non-CI Builds

- tools/tsp-client/src/typespec.ts
fix https://github.com/microsoft/typespec/issues/5007
This cause an issue where we load the version of formatDiagnostic which expect typespec types to have new properties not availaible in the currently loaded version
> Use local version of format diagnostic for tsp-client

- eng/common/scripts/Helpers/Resource-Helpers.ps1
- eng/scripts/live-test-resource-cleanup.ps1
Live test cleanup - sub deployments, immutable containers, purge skip
> Live test cleanup - sub deployments, immutable containers, purge skip

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.json
Adaptive Sampling was causing PipelineWitness to drop a large portion of its happy-path telemetry before sending it to AppInsights.  This made it difficult to search for trace messages related to specific build processing as there was a good chance that the trace logs from processing the build were sampled away.
By disabling adaptive sampling, we're telling the app to send all emitted telemetry to the AppInsights collector for processing.
> Disable adaptive sampling to AppInsights

- tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/appsettings.json
Removing adaptive sampling caused a 10x increase in our telemetry ingestion rate and cost.   The largest category of telemetry is our automatic dependency tracing (azure blob / queue, etc).  This change will stop the automatic collection of dependency telemetry.
> Reduce ingestion costs by disabling auto dependency call tracing

- eng/common/pipelines/templates/steps/save-package-properties.yml
- eng/common/scripts/Generate-PR-Diff.ps1
Enabling service tags on `<language - pullrequest` builds.
Thank you @hallipr for adding this feature!
> Upload ChangedServices as an `attachment` for later processing by `Pipeline-Witness` 

- eng/common/pipelines/templates/archetype-typespec-emitter.yml
For http-client-csharp typespec emitter, we have needs to sparse-checkout extra paths while applying archetype-typespec-emitter.yml.
The detailed usage can be found in https://github.com/Azure/azure-sdk-for-net/pull/47136
> Add SparseCheckoutPaths to archetype-typespec-emitter.yml

- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Fix missing stress matrix display name filter
> Fix missing stress matrix display name filter

- src/dotnet/APIView/APIViewUnitTests/APIViewUnitTests.csproj
- src/dotnet/APIView/APIViewUnitTests/CodeFileHelpersTest.cs
- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
Fix the bug when processing review lines at top level and if top level contains documentation.
> Fix the bug when package level review line had documentation

- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
- eng/common/scripts/job-matrix/job-matrix-functions.ps1
I noticed something _odd_ about how my PR to use the common create-prmatrix instead of custom `distribute-packages-to-matrix` over in Azure/azure-sdk-for-python#38324 
It looked like only the second batch ran?
This PR resolves the oddness.
Details as to what this fixes:
- batches are stomping on each other.
> Batching adjustments for Create-PRJobMatrix

- eng/common/scripts/Verify-ChangeLogs.ps1
[Exhibit A](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4331354&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ac8f4042-9b76-5db4-27b1-2a4abaa9bb3c)
FYI @benbp
> Utilize `ArtifactDetails` to avoid parsing issues in Verify-Changelogs.ps1

- src/dotnet/APIView/APIViewWeb/Helpers/CodeFileHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanModels/CodePanelModels.cs
Diff is showing added line as removed when diff is in end of context line. Empty lines from untouched classes are not removed from node and tree view if parser doesn't set empty lines as related to the node line.
> Fix issues in diff when end of context line has diff

- eng/common/scripts/Helpers/PSModule-Helpers.ps1
Adding an override list of ps modules we want to redirect to our devops mirror feed.
Also simplified the module existence check (still thread safe), but I'm thinking that maybe the double existence check was there so we wouldn't have a giant lock request backlog if a ton of threads all do a module check at the same time (given it takes 1 sec to do the check if it's behind the lock). @mikeharder any recollection on this? From https://github.com/Azure/azure-sdk-tools/pull/6521
> Support override of powershell module feeds

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
I'm chasing a hidden `GitProcessException` in #9208 . I have a hunch that that combined with a failure to properly get the target repo is causing `git` to get into an irreconcilable state. When that happens, and `git remote set` runs, it escapes the `<languagerepo>/.assets/sliceId/` folder because there _isn't_  a real git repo initialized there.
when that occurs, and we still invoke `git remote set-url`, that'll override the language repo origin. @alzimmermsft this should at least reduce the impact when something goes wrong. I'm still chasing the real origin of it all though.
> Avoid destructive language-repo origin updates

- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Program.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/ReadmeParser.cs
- tools/apiview/parsers/swagger-api-parser/SwaggerApiParserTest/ReadmeParserTest.cs
Reverts Azure/azure-sdk-tools#9274
Am no longer making use of this
> Revert "Use Tag for Token File OutPut"

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationRestoreTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/Exceptions/GitProcessException.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/IAssetsStore.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/NullStore.cs
- tools/test-proxy/scripts/test-scripts/CLIIntegration.Tests.ps1
Don't infinitely loop. Resolves #9208
> Properly handle when `git` encounters an unrecoverable error

- src/dotnet/APIView/apiview.yml
- Update api parser installation to use DevOps feed local view.
- Enable test for Go parser
> Install JS API parser from local feed view

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
- eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Update to use new features in https://github.com/Azure/azure-sdk-tools/pull/9462
Also opt JS and Python out of making public pipelines given we have moved to the new pullrequest model for those.
> Use new generation tool that supports service connections

- src/swift/SwiftAPIView/SwiftAPIView.xcodeproj/xcshareddata/xcschemes/SwiftAPIView.xcscheme
- src/swift/SwiftAPIViewCore/Sources/Models/APIViewModel.swift
- src/swift/SwiftAPIViewCore/Sources/Models/DeclarationModel.swift
- src/swift/SwiftAPIViewCore/Sources/SwiftSyntax+Extensions/SyntaxProtocol+Extensions.swift
- src/swift/SwiftAPIViewCore/Sources/SwiftSyntax+Extensions/TokenKind+Extensions.swift
- src/swift/SwiftAPIViewCore/SwiftAPIViewCore.xcodeproj/project.pbxproj
- src/swift/SwiftAPIViewCore/SwiftAPIViewCore.xcodeproj/xcshareddata/xcschemes/SwiftAPIViewCore.xcscheme
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/AttributesExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/EnumerationsExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/ExtensionExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/FunctionsExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/GenericsExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/InitializersExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/OperatorExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/PrivateInternalExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/PropertiesExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/ProtocolExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/ExpectFiles/SwiftUIExpectFile.txt
- src/swift/SwiftAPIViewCore/Tests/SwiftAPIViewCoreTests.swift
- src/swift/SwiftAPIViewCore/Tests/TestFiles/AttributesTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/EnumerationsTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/ExtensionTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/FunctionsTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/GenericsTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/InitializersTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/OperatorTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/PrivateInternalTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/PropertiesTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/ProtocolTestFile.swifttxt
- src/swift/SwiftAPIViewCore/Tests/TestFiles/SwiftUITestFile.swifttxt
Previously these were only manual tests contained in a separate package. This organizes them as unit tests as a precursor to converting to the TreeToken model.
> [Swift APIView] Add automated tests

- eng/pipelines/eng-workflows-sync.yml
The [azure-sdk-tools - sync - eng-workflows pipeline is failing](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4392109&view=logs&j=96791242-dbf3-587e-3a06-ae5af5c1a705&t=7d32c8b0-9463-5ee1-8584-402dd23c6c1c&l=63) because Rust was added to the list of repositories. At this time, Rust does not have a .github/workflows directory nor do they have CheckEnforcer or Actions enabled. Remove Rust from the list until they're ready to enable them both.
> Don't try and sync .github/workflows to Rust yet

- .github/workflows/event-processor.yml
- .github/workflows/scheduled-event-processor.yml
Update GitHubEventProcessor version to 1.0.0-dev.20241206.2 for the AI Label Service Update done in this [PR](https://github.com/Azure/azure-sdk-tools/pull/9489)
> Update GitHubEventProcessor version to 1.0.0-dev.20241206.2

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs
- tools/test-proxy/typespec/main.tsp
This is actually a revert of the tiny change in #9451 
I don't want to deal with the API change for this release, as there are some `git exception` fixes that I want to get out into the wild in this version.
There are some unified breaking changes that I want to make to the test-proxy API that I'll work through later this month. Nothing _huge_, but some QoL and design fixes to make the API a bit more model driven, versus the organic growth that it's experienced so far.
> Hotfix `test-proxy` Error Response

- src/swift/SwiftAPIViewCore/SwiftAPIViewCore.xcodeproj/project.pbxproj
Convert folders to groups for recently added testing files. By just right clicking on those testing folders and clicking "Convert to Group" apparently using that folder `PBXFileSystemSynchronizedBuildFileExceptionSet` cause versions before Xcode 16 to think that project format is invalid therefore failing the build on our ACS Calling pipelines.
> [Swift][ApiView] Convert folders to groups for recently added testing files

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0004Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
Fixes https://github.com/Azure/azure-sdk-tools/issues/6845
Currently, the analyzer does not ensure that both equivalent sync and async methods have the same return type and parameters. This PR adds a check for the return type and parameters of both methods to ensure that they match.
> AZC0004 ensure that method signatures match

- eng/common/scripts/Helpers/PSModule-Helpers.ps1
- eng/common/scripts/Helpers/Package-Helpers.ps1
Attempt dos. Creating this PR to avoid the merge conflicts on the original PR: #9332
> Optimize Yml Extraction

- tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts
- tools/js-sdk-release-tools/src/common/ciYamlUtils.ts
- tools/js-sdk-release-tools/src/mlc/clientGenerator/modularClientPackageGenerator.ts
Bug: Falied to resolve correct path in windows
Fix: Use posix path as it is supported in all platforms
> Fix Windows Path Issue in js-sdk-release-tool

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/OptionsGenerator.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/CommandOptions/StartOptions.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/AutoShutdown/ShutdownConfiguration.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/AutoShutdown/ShutdownTimer.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/AutoShutdown/ShutdownTimerMiddleware.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs
Resolves #9467 
If a user provides `--auto-shutdown-in-seconds` to the proxy, the proxy will automatically shut down after the specified number of seconds if any route isn't contacted. We reset this on _any_ handled request via middleware, so we should have 100% coverage.
> [TestProxy] Add auto-shutdown to the proxy

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/migration.ts
- tools/js-sdk-release-tools/src/common/rushUtils.ts
- tools/js-sdk-release-tools/src/hlc/generateMgmt.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
- tools/js-sdk-release-tools/src/mlc/clientGenerator/modularClientPackageGenerator.ts
- tools/js-sdk-release-tools/src/mlc/clientGenerator/utils/typeSpecUtils.ts
Fix: https://github.com/Azure/azure-sdk-tools/issues/9510
> Migrate JS Package

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs
This should fix the issues with some pipelines not having the correct permissions to some service connections.
> Fix incorrect variable name

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/migration.ts
Root Cause: use `pnpm` which is not available in pipeline
Solution: Use `npm` instead
Test: (Migration Success) https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4455904&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=2020
> Fix Migration Command Failure

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
Update to modern .NET recommendation, and simplify instructions with the `--prerelease` switch I asked for and was implemented a couple years ago.
> Update Test-Proxy install instructions

- tools/test-proxy/tests.yml
.NET 6.0 isn't on the machines (this change occurred early/mid December), so this should get it off the floor. I want clean nightly livetests if possible 👍 
[Proving Build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4461356&view=logs&j=bf74e942-6840-5835-1ce0-37a6d60262e3) (ignore skipped jobs I deliberately `condition: false`-d working steps to avoid agent wastage.)
> Fix `test-proxy` integration tests for .NET

- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/revision-options/revision-options.component.html
- Add labels to revision dropdown and allow only full diff for TypeSpec reviews
> TypeSpec specific conditions

- eng/common/scripts/Package-Properties.ps1
The example I'll use. When we feed this as the file change:  `sdk/keyvault/azure-keyvault-keys/pyproject.toml`
We will match this to `azure-keyvault` AND `azure-keyvault-keys` packages. This change ensures a full match.
> Fix for overaggressive inclusion in `Get-PrPackageProperties`

- eng/common/scripts/Package-Properties.ps1
The issue this PR is resolving is highlighted [in this pr step](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4473778&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f&l=91)
Note that we're saying
> for this stage, only look at the `indirect` included packages
However, due to the order of operations, we resolve the set of `direct` changed packages _first_, then we walk each of them checking to see if there are additional packages that they should also include if they are changed. In the example PR above, we directly changed `azure-core-opencensus`, but because it was _also_ an `additionalValidationPackage` for `azure-core`, it was getting marked as an `indirect` package. This PR fixes our logic so that if a package is directly changed, …
> Ensure that packages that are both changed AND part of the AdditionalValidationPackages set are handled properly

- eng/common/TestResources/New-TestResources.ps1
For TME accounts, the `-UserPrincipalName` does not match the email (e.g. `foobar@microsoft.com`) and is instead like `foobar_microsoft.com#EXT#@<tenant>`), so the local user id/oid lookup is broken for TME testing. Using `-Mail` works as the value is the same across tenants.
So for local TME testing, one can do:
```
Set-AzContext -Subscription '<tme subscription>' -Tenant '<tme tenant>'
./eng/common/TestResources/New-TestResources.ps1 -ServiceDirectory <dir> -SubscriptionId '<tme subscription>'
```
At a certain point we will switch the default off playground and the `-Subscription` override won't be necessary, but we'll have to add more UX handling to help people make sure they are on the right az context.
CC @catalinaperalta
> Use -Mail for test resources local user lookup to support TME

- eng/common/pipelines/templates/steps/save-package-properties.yml
- eng/common/scripts/Generate-PR-Diff.ps1
- eng/common/scripts/Package-Properties.ps1
@scbedd and @weshaggard 
These are the common changes required to filter out PackageInfo generation by what should be excluded from the pull request pipelines. This is the example in [Python](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/pullrequest.yml#L14), which excludes `sdk/cosmos`. The unfortunate thing here is that we can't access the pr->paths->exclude meaning this needs to be duplicated. Because of the default in the save-package-properties.yml nothing will break if the ExcludePaths aren't plumbed through. The only downside here is that wildcards aren't accepted but then again, most excludes in yml files aren't wildcarded.
I'd created a [draft PR in Python to test these changes](https://github.com/Azure/azure-sdk-for-python/pull/39185). Notice that the PR had …
> Filter out Exclude Paths for PR Pipelines

- eng/common/pipelines/templates/jobs/generate-job-matrix.yml
- eng/common/pipelines/templates/steps/verify-readmes.yml
- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
See specific usage [here](https://github.com/Azure/azure-sdk-for-net/blob/b3b51845a8f54ff8fab0ae44cdc0d6dc77ac8818/eng/pipelines/templates/jobs/ci.yml#L355) for why the additional filter is useful. We use the _same_ matrix, but filter it down using the IndirectMatrixFilters. [How it looks](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4457738&view=logs&j=bf2461f0-018c-56e3-12cd-1c3d6735490e)
> Updates to `PullRequest` matrix generation

- eng/common/scripts/Test-SampleMetadata.ps1
Resolves broken link references that were discovered in Python's nightly link checker: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4466891&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=038ef773-2c87-526e-5636-46093602ba59
> Fix broken link to Learn docs

- src/dotnet/APIView/ClientSPA/src/app/_services/http-error-interceptor/http-error-interceptor.service.ts
Allow http interceptor to return errors in production as its needed for other functioning of the app
> Bubble up server errors to client.

- eng/common/scripts/Generate-PR-Diff.ps1
- eng/common/scripts/Package-Properties.ps1
[In action](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4488546&view=results)
I think the only real discussion item here is whether to fold the deleted files directly under `ChangedFiles`. I prefer it to be separate, as we can rely on `ChangedFiles` actually resolving to a reference on disk. However for this usage it doesn't actually matter, as we don't rely on them existing on disk to check which package they belong to in `Get-PrPackageProperties`.
Pending feedback from @weshaggard or @benbp , I have an opinion but I know ya'll will have one as well 👍 
@kristapratico when I merge this (regardless of implementation detail) this PR will resolve the issue you saw over [here.](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4484095&view=logs&jobId=22aa3ba4-644c …
> handle only deleted files in a <language> - pullrequest build

- eng/common/scripts/SemVer.ps1
- Remove the artificial `PrereleaseLabel` and `PrereleaseNumber` values from non-prerelease versions
- Add support for bumping Major, Minor or Patch versions using `IncrementAndSetToPrerelease($segment)`
- The default segment is still `minor`
- Fix support for "zero" versions in `HasValidPrereleaseLabel`
- previously, `[AzureEngSemanticVersion]::new("0.1.2").HasValidPrereleaseLabel()` would return
```
Unexpected pre-release identifier 'zzz',  should be 'beta' or 'alpha'
False
```
Parse results before:
| Property         | `0.1.2`  | `1.2.3`  | `1.2.3-alpha.1` | `1.2.3-alpha.20250121.10` |
| ---------------- | -------- | -------- | --------------- | ------------------------- |
| Major            | 0        | 1        | 1               | 1                         |
| Minor            | 1 …
> Support incrementing semver prereleases with 'zero' versions

- tools/apiview/parsers/csharp-api-parser/CSharpAPIParser/TreeToken/CodeFileBuilder.cs
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CSharpAPIParserTests.csproj
- tools/apiview/parsers/csharp-api-parser/CSharpAPIParserTests/CodeFileTests.cs
Update the list of attributes that are skipped from APIView for .NET
> Update dotnet parser to skip RequiresUnreferencedCode attribute

- tools/pylint-extensions/azure-pylint-guidelines-checker/CHANGELOG.md
- tools/pylint-extensions/azure-pylint-guidelines-checker/pylint_guidelines_checker.py
- tools/pylint-extensions/azure-pylint-guidelines-checker/setup.py
Student pylint checkers were missing try/except which when a function was missing say a type or was incorrectly formatted instead of peacefully failing we were erroring.
> [pylint] wrap excepts

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/entrypoint.ts
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/types/sdks.ts
- Deprecated 'azure-sdk-for-net-track2' and repurposed 'azure-sdk-for-net' for the .NET track2 SDK
- Added functionality to generate an HTML file for the filtered log
- Refined code for PR scenario
> deprecate track2 and refine code for PR scenario

- tools/tsp-client/README.md
Update docs for `generate-config-files` command.
> [tsp-client] Update docs

- eng/common/pipelines/templates/steps/sparse-checkout.yml
1es pt scripts normally try to download this file remotely using the pipeline gh token, but they will also honor the file on the machine. In some cases the remote fetch will fail or be unauthorized, so we should always check out 1espt config files for consistency/reliability.
> Sparse checkout 1espt auto-baselining file by default

- eng/common/scripts/stress-testing/deploy-stress-tests.ps1
- eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
- tools/stress-cluster/chaos/examples/network-stress-example/Chart.lock
- tools/stress-cluster/chaos/examples/network-stress-scenarios-example/Chart.lock
- tools/stress-cluster/chaos/examples/parallel-pod-example/Chart.lock
- tools/stress-cluster/chaos/examples/stress-debug-share-example/Chart.lock
- tools/stress-cluster/chaos/examples/stress-deployment-example/Chart.lock
- tools/stress-cluster/cluster/azure/cluster/acr.bicep
- tools/stress-cluster/cluster/azure/cluster/cluster.bicep
- tools/stress-cluster/cluster/azure/main.bicep
- tools/stress-cluster/cluster/azure/parameters/storage.json
- tools/stress-cluster/cluster/kubernetes/stress-infrastructure/Chart.lock
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/CHANGELOG.md
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/Chart.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/index.yaml
- tools/stress-cluster/cluster/kubernetes/stress-test-addons/values.yaml
- tools/stress-cluster/cluster/provision.ps1
Update lock file versions for stress addons 0.3.5
> Migrate stress storage cluster to TME

- src/dotnet/APIView/APIViewWeb/Client/css/shared/theme-colors.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.scss
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_helpers/doubly-linkedlist.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/codeLineSearchInfo.ts
- src/dotnet/APIView/ClientSPA/src/app/_modules/shared/review-page-layout.module.ts
- src/dotnet/APIView/ClientSPA/src/app/_modules/shared/shared-app.module.ts
- src/dotnet/APIView/ClientSPA/src/ng-prime-overrides.scss
- Add codeline search feature to APIView.
- Allows search across lazy loaded items.
> Codeline Search

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/entrypoint.ts
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
* Introduced a root folder to save all logs and artifacts
* Updated file paths to use the new `out/logs` and `out/generatedSdkArtifacts` directories
> Introduce a root folder to save the logs and artifacts

- eng/common/pipelines/templates/jobs/generate-job-matrix.yml
- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
js team needs the full (or at least MORE full) matrix as they want the indirectly changed packages to run both `node` and `browser` tests.
This code change, alone, would return them to the full matrix for indirect changes. However, I'm going to pair it with setting arguments to `IndirectFilters` to filter the full matrix down a bit to only `Ubuntu` platforms.
This is in response to feedback from @jeremymeng WRT [this pipeline](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4504825&view=logs&j=69104f8e-b88e-5d11-595c-90fd5e8e65ca&t=4ba20f2a-6568-5c82-27d3-3f34c36a0661). We need common changes to also run against browser (which it's not as evidenced by the linked PR).
> Non-Sparse Indirect Packages

- eng/common/TestResources/New-TestResources.ps1
Add fallback user id lookup for test resource deployment
> Add fallback user id lookup for test resource deployment

- src/dotnet/APIView/APIViewWeb/CONTRIBUTING.md
- src/dotnet/APIView/APIViewWeb/Program.cs
Connect to Azure app config using managed identity so we can disable key based access to app config resource.
> Connect to APIView app config using managed identity

- eng/common/pipelines/templates/archetype-typespec-emitter.yml
Adding a common step to upload spector coverage from azure-sdk-for-[lang] repos.
Supports https://github.com/Azure/azure-sdk-for-net/issues/47071
Tested with a temp change in this pr https://github.com/Azure/azure-sdk-for-net/pull/48006
> Update emitter template

- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page/review-page.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_helpers/doubly-linkedlist.ts
- src/dotnet/APIView/ClientSPA/src/app/_models/codeLineSearchInfo.ts
- Improve component communication logic for codeline search
> Improve Component Communication Logic

- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
- eng/common/scripts/Helpers/PSModule-Helpers.ps1
Fix issue where we are over 10000 work items so we aren't finding the newer ones. This updates to 100000, hopefully we don't hit that anytime soon.
Also made some of the common logging verbose to remove noise in steps like prepare-release where we don't need to see that once per yml file we parse.
> Update query count to fix automation

- eng/common/pipelines/templates/jobs/prepare-pipelines.yml
- eng/common/pipelines/templates/steps/sparse-checkout.yml
- eng/common/pipelines/templates/steps/validate-all-packages.yml
Pipeline generation for the private repos no longer works after my recent refactoring. The reason is because sparse-checkout doesn't support cloning them without a key. I've hacked together a proof of concept to unblock folks but I'm not sure how I like this implementation. 
I'm curious of your thoughts @benbp
> Fix pipeline generation for private repos

- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
- eng/common/scripts/job-matrix/job-matrix-functions.ps1
@JimSuplizio and I were trying to figure out why the new `java - pullrequest` matrix generation was short a couple jobs from the `java - core - ci` matrix. I found that we aren't plumbing through `NonSparseParameters` from the matrix config.
@scbedd I wasn't sure if this was intended to be skipped or not. If it should be skipped I can change this PR to just add a comment explaining why.
> Pass non sparse parameters through to PR job matrix generator

- src/dotnet/APIView/ClientSPA/src/app/_components/code-panel/code-panel.component.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/shared/comment-thread/comment-thread.component.html
Resolves https://github.com/Azure/azure-sdk-tools/issues/9706
Allow `Ctrl + Enter` to save comment.
> Add keyboard event for saving comment

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
During restore, make this an explicit error.
@heaths was getting badrequests due to improperly joining paths. Let's make it explicit so he isn't surprised.
> Disallow absolute recording file paths when an assets.json is provided

- eng/common/scripts/Package-Properties.ps1
Credit where credit is due, @scbedd made and tested these changes in Java in a [PR](https://github.com/Azure/azure-sdk-for-java/pull/44046) against my pull request testing branch.
GetValueSafelyFrom-Yaml is victim to array unrolling, so our previous use case was accidentally changing type, and adding the additionalMatrix config to it was causing issues.
For Java this PR fixes that + optionally parses the AdditionalMatrixConfigs param. We are now seeing version_override generate correctly for azure-core in the [pull request pipeline run](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4537995&view=results) against the test PR.
> Add AdditionalMatrixConfigs the CIMatrixConfigs

- tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/SdkComponentScanner.cs
Fixing https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4537511&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=f627a99b-3dfd-52f6-3228-32c29542eb4a
Apparently our pipeline generator currently restricts to lower case chars for variants in the pipeline names. This enables it to be all word characters and thus enables the java "v2" variants.
fyi @JimSuplizio @alzimmermsft
> Like variants in pipeline files to be any word char

- tools/apiview/parsers/js-api-parser/package.json
- tools/apiview/parsers/js-api-parser/src/generate.ts
- tools/apiview/parsers/js-api-parser/src/jstokens.ts
- tools/apiview/parsers/js-api-parser/test/data/renamedEnum.json
- tools/apiview/parsers/js-api-parser/test/generate.spec.ts
- tools/apiview/parsers/js-api-parser/vitest.config.ts
Adds support for re-exported enums, ensuring APIView shows the correct (i.e. exported and customer-visible) name for an enum.
I scoped this just to enums for now, but we can expand if we find other usages.
I also went ahead and added a basic test with a basic test fixture. Future PR will work with @praveenkuttappan to ideally add this to CI builds for the parser.
Resolves #9768
> [js-parser] Support re-exported enums

- eng/common-tests/helpers/Package-Helpers.tests.ps1
- eng/common/scripts/Helpers/Package-Helpers.ps1
This PR enhances the `Group-ByObjectKey` function to coalesce boolean-like values to their true boolean representation before getting a hashcode for them.
We use this grouping function to group a list of packages by which matrix config they belong to. The issue is that due to devops shenanigans, these matrix configs are getting their booleans a bit changed. The "default" matrix that is fed into `Create-PrJobMatrix` is a result of a devops json conversion of the static yaml parameter. Due to this, the booleans are getting messed up.
```yml
MatrixConfigs:
- Name: NET_ci_test_base
Path: eng/pipelines/templates/stages/platform-matrix.json
Selection: sparse
GenerateVMJobs: true
```
But devops _converts_ this to:
```json
{
"Name": "NET_ci_test_base",
"Path": …
```
> Get-ObjectKey converts boolean values

- eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
- eng/common/scripts/SetTestPipelineVersion.ps1
Rust crates use snake case for packages.  "Get-${Language}-PackageInfoFromPackageFile" in LanguageSettings.ps1 allows the language to choose its tag naming scheme.  When package names contain underscores, a dash is a better separator. 
It appears that SetTestPipelineVersion is the only script that cares about the structure of the repo tags.
> Parameterize test-pipeline version separator

- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
We need a way to make a few `ci.yml` parameters available to the `package-properties` class. We need to do this for a couple of the .NET parameterized checks. Specifically:
- `AOTCompat: boolean`
- `CheckSnippets: boolean`
These are opt-in, so anyone forwarding `CheckSnippets: false` _aren't_ expecting check snippets to run. We can't currently honor this scenario in `net - pullrequest`.
This PR does two things:
My intent is to utilize `GetCIYmlForArtifact` within the `Get-AllPackageInformationFromRepo` function in `.NET`. From there, I'll add key-value pairs representing these values to the `CIParameters` hashtable.
The reason I'm offering it this way, is that `Save-Package-Properties.ps1` doesn't currently offer customizations as an argument, we rely on each individual repo to implement …
> Replace `CIMatrixConfigs` with generalized `CIParameters` within `Package-Properties`

- eng/common/pipelines/templates/steps/save-package-properties.yml
- eng/common/scripts/Save-Package-Properties.ps1
Save package properties add DEV version only if `AddDevVersion` switch is passed and currently this is incorrectly set in yaml. Script also needs a change since this is wrapped in a yaml to pass `AddDevVersion` a bool to avoid duplicate step in the pipeline yaml.
> Fix the expression used for AddDevVersion param in save package properties

- src/dotnet/APIView/APIViewWeb/Languages/CLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/CppLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/JsonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/LanguageProcessor.cs
- src/dotnet/APIView/APIViewWeb/Languages/LanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/SwiftLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Models/APICodeFileModel.cs
Update version string property in Cosmos DB to current parser version when converting to tree token model. Also mark  revision as converted when converting from flat model.
> Update parser version in Cosmos when converting code file to tree model

- eng/common/pipelines/templates/steps/save-package-properties.yml
- eng/common/scripts/Save-Package-Properties.ps1
Environment variable SETDEVVERSION is not accessed correctly so it is empty on Unix machines.
> Fix the issue in adding dev version in package info

- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Specifically when a package belongs to multiple matrices.
For everyone else's benefit, this change was tested as part of this [PR](https://github.com/Azure/azure-sdk-for-java/pull/44190) in Java, where the issue was originally found.
> Adjustments to PR Matrix generation

- src/dotnet/APIView/APIViewUnitTests/APIRevisionsManagerTests.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
> [APIView] Disable auto upgrade of APIView review

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
Fix: https://github.com/Azure/azure-sdk-tools/issues/9829
Solution: remove the check to limit the number of changed folders more than one (while the the old tool pass only one `readmeMd` already, no need to check the number)
> Remove requirement of only modifying 1 folder

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/src/automation/entrypoint.ts
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/sdkAutomationState.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/utils/runScript.ts
- tools/spec-gen-sdk/src/utils/utils.ts
- tools/spec-gen-sdk/test/utils.test.ts
- Format error log which has ANSI code that garbled characters are displayed on github checks
- Add new state `NotEnabled` when missing language config in readme.md or tspconfig.yaml
> [sdk-gen] add new state & format script line code

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- Removed several methods and refactored the workflow to streamline SDK generation. 
- Modified the `specConfigPath` to replace slashes with dashes to ensure compatibility.
- Updated variable name for consistency in API view artifact logging.
> Unify the SDK generation process

- eng/common-tests/helpers/Package-Helpers.tests.ps1
- eng/common/scripts/Helpers/Package-Helpers.ps1
- eng/common/scripts/Package-Properties.ps1
FYI @benbp @JimSuplizio 
This PR:
This covers the "if eng/ changes add this package purely for validation".
The issue I discovered is that if we honor the default `trigger` from each `ci.yml`, we would end up causing `pullrequest` builds to just target the entire `servicedirectory` again. We need the inclusion to be at the _artifact_ level.
So for instances like `eventhub` for .NET. Where a given service directory contains multiple `ci.yml` that all target different artifact lists. This enables specific coverage of packages that depend on a specific directory path that might not even be a valid package. So for eventhub, that looks like this:
```
- name: Azure.Messaging.EventHubs.Processor
safeName: AzureMessagingEventHubsProcessor
triggeringPaths:
- …
```
> Relying on `CIParameters` for storage of trigger information

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
Root cause: forget to set package path (declared in line 42, 43) after code generation
Test: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4578488&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=6927
> Fix: failed to get package path

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- tools/spec-gen-sdk/src/utils/utils.ts
- tools/spec-gen-sdk/test/utils.test.ts
- Changed the message from error level to warning level when SDK configuration is not enabled in the configuration file.
- Updated the regex to get the prefix of spec folder path
> Log warning when SDK configuration is not enabled in the configuration

- eng/common/scripts/Package-Properties.ps1
We were adding a trailing slash to ExcludePaths. The problem with doing this it that it only allowed paths to be excluded and disallowed excluding specific files. For Java, this was a problem because we need to exclude the centralized versioning files from the PR pipeline, otherwise, anything changing these would get azure-core added as an indirect package which would cause the PR pipeline to run when it shouldn't. For example, Java Cosmos had [PR](https://github.com/Azure/azure-sdk-for-java/pull/44306) yesterday to prepare for their release which changed version_client.txt but every other change was in sdk/cosmos.
This change will allow the ExcludePaths to include specific files. PRs in [Java](https://github.com/Azure/azure-sdk-for-java/pull/44330), …
> Remove trailing slash addition to ExcludePaths

- eng/common/scripts/Verify-Links.ps1
This resolves a problem we found with Azure/azure-sdk-for-rust#2200. We already had special handling for crates/users/teams *under* crates.io, but this "fixes" support for other links e.g., "https://crates.io".
> Fix support for crates.io links

- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs
@benbp @weshaggard I'm interested to get your opinion on this.
The storage team (and others merging recordings) sometimes get errors in their `git add` commands that pan out to something along the lines of:
```
Unhandled exception: Azure.Sdk.Tools.TestProxy.Common.Exceptions.HttpException: Invocation of "git add -A ." had a non-zero exit code -1.
fatal: LF would be replaced by CRLF in net/sdk/storage/Azure.Storage.Blobs/tests/SessionRecords/AppendBlobClientOpenReadTests/OpenReadAsync_AccessConditions.json
```
Best I can tell, this occurs when copying files from a tag on your machine, when the files were generated on an opposite platform. It's a fairly uncommon issue, but one that does happen.
The fix is to cd into the directory and add the file yourself, accepting the conversion to …
> Disable SafeCRLF

- eng/common/scripts/Package-Properties.ps1
This PR handles service-level changes without language-specific settings.
- Just add the artifacts within the `ci.yml` to the set of artifacts for testing
This approach is working the way I expect in: Azure/azure-sdk-for-net#48379
> Moving more discovery into `Get-PrPkgProperties`

- tools/apiview/parsers/js-api-parser/CHANGELOG.md
- tools/apiview/parsers/js-api-parser/package.json
- tools/apiview/parsers/js-api-parser/src/export.ts
- tools/apiview/parsers/js-api-parser/src/generate.ts
- tools/apiview/parsers/js-api-parser/test/generate.spec.ts
and tslib.  This allows us to see third-party dependency changes.
> [apiview][js parser] skip diff'ing for @Azure dependencies 

- packages/python-packages/apistubgentest/apistubgentest/__init__.py
- packages/python-packages/apistubgentest/apistubgentest/_client.py
- packages/python-packages/apiview-stub-generator/CHANGELOG.md
- packages/python-packages/apiview-stub-generator/apistub/_parsing_helpers.py
- packages/python-packages/apiview-stub-generator/apistub/_stub_generator.py
- packages/python-packages/apiview-stub-generator/apistub/_version.py
- packages/python-packages/apiview-stub-generator/apistub/nodes/_class_node.py
- packages/python-packages/apiview-stub-generator/apistub/nodes/_module_node.py
- packages/python-packages/apiview-stub-generator/tests/module_parsing_test.py
fixes: #9587
* Also updated timeout value during package installation step, for Windows.
* Remove unused get_navigation method
> [APIView] parse module level function overloads

- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.ts
- Disable delete and restore button for revisions that are not manual and not created by logged In user
- Resolves https://github.com/Azure/azure-sdk-tools/issues/8888
> Improve Revisions list context menu

- eng/pipelines/templates/steps/sync-repo-merge-branch.yml
- eng/pipelines/update-release-branch-in-specs.yml
Created a helper [pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=7487) that will enable teams to generate a PR with a merge from the main in the specs repo that only includes things outside of the specification folder such as infrastructure.
> Add update-release-branch-in-specs pipeline

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0007Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0008Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/SymbolAnalyzerBase.cs
This PR introduces a fix for AZC0007, where this analyzer was incorrectly firing for clients even when the expected constructors were present. Rather than trying to load the `Azure.Core.ClientOption` type during compilation start, and using this loaded type to validate if a constructor's last parameter matches it, we now simply just check the parameter's base type's name to see if it matches `Azure.Core.ClientOption`.
sdk-for-net pr:  https://github.com/Azure/azure-sdk-for-net/pull/48474
> fix: use full type name when checking for ClientOptions type

- eng/common/pipelines/templates/steps/detect-api-changes.yml
This solves a problem in the go repo where we have tools in `eng/` that run pipelines with no artifacts generated. Paired with https://github.com/Azure/azure-sdk-for-go/pull/24166
> Add condition parameter to detect-api-changes template

- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
APIView updates review metadata but it's not updating revision metadata when processing successful upgrade of revisions using new parser. This will prompt APIView to reprocess those revisions again unnecessarily when restarting the server.
> Update API revision metadata when processing update requests from sandboxing pipeline

- packages/python-packages/apiview-stub-generator/CHANGELOG.md
- packages/python-packages/apiview-stub-generator/apistub/_stub_generator.py
- packages/python-packages/apiview-stub-generator/apistub/_version.py
- packages/python-packages/apiview-stub-generator/tests/apiview_test.py
API parser has a new change to get package name and version using pkginfo and this only works when gnerating review file from wheel or sdist. But python CI generates token from package source hence pkginfo is not available and as a result review token file is generated with wrong version and wrong token file name.
Parser also iterates all directories including tests and build and include those paths in package modules.
> Python API review is not generated using correct package name

- eng/common/scripts/Detect-Api-Changes.ps1
Some languages generate API review token file in CI side and some languages passes source only to APIView. When both code file and original source file are passed to APIView then it downloads package directory as zip and iterate over the zip to identify the files. But if original file only is passed to APIview then it downloads just that file. 
Script was sending full path for original file along with code file and APIView ignores the original file when it does not match the file name in zip.
> Update original file path value in detect change request to APIView

- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
See title!
I'm thinking I see some interesting test cases around if we want to force the addition of a suffix. I don't think so.
> Allow Targeted Disable of PRBatching

- eng/common/pipelines/templates/steps/sparse-checkout.yml
It's nice to see where the repos are being checked out.  The native `checkout:` step shows the target path in the step display name:
```
Starting: Checkout Azure/azure-sdk-for-net@users/pahallis/1es-deployment to s
```
> Add path logging to sparse-checkout

- tools/typespec-bump-deps/CHANGELOG.md
- tools/typespec-bump-deps/package-lock.json
- tools/typespec-bump-deps/package.json
I've (mistakenly) added the stream libs in the "move" PR https://github.com/Azure/azure-sdk-tools/pull/9967
https://github.com/weidongxu-microsoft/azure-sdk-tools/blob/811761c09eff43ec5f7738a4092e6615436221c3/tools/typespec-bump-deps/src/cli/typespec-bump-deps.ts#L13-L15
I've done a local test to package.json includes the 3 stream libs.
> typespec-bump-deps, prepare release 0.9.7

- eng/common/TestResources/New-TestResources.ps1
The `.Tenant.Name` property is null in the pipeline's login context.
I'm not a fan of this approach, but it's either subscription name checking or hardcoded tenant id checking.
> Use subscription name to assign supportsSafeSecretStandard

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
Bugs:
- Failed to update package path and relative path which are used to generate some other files for the package for TSP
- Failed to get autorest config in sdk repo
- Get the first autorest config even if the swagger file is NOT the one in generating.
Test: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4578488&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2 (Type `Read temp file azure-sdk-for-js_tmp/generateOutput.json` to check result summay)
Issue Fix: https://github.com/Azure/azure-sdk-tools/issues/9829
> Support `input-file` in autorest config to recognize RP

- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/ModelName/AZC0030OptionsTest.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/ModelName/AZC0030Tests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/ModelName/SuffixAnalyzerBaseTests.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/Descriptors.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs
- src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/OptionsSuffixAnalyzer.cs
This PR introduces fixes for these items:
- [Refine AZC0030 Error Message Regarding Options Suffix](https://github.com/Azure/azure-sdk-tools/issues/9469)
- The analyzer that was validating models with the Options suffix was updated to include a general diagnostic message which links to our guidelines regarding naming models. It will no longer suggest a name to use as a replacement.
- [Update AZC0030 so that it doesn't prevent clients from having serializable models with the Options suffix](https://github.com/Azure/azure-sdk-tools/issues/9335).
- The analyzer that was validating models with the Options suffix was scoped down to management plane models.
sdk-for-net test pr: https://github.com/Azure/azure-sdk-for-net/pull/48597
> [Azure.ClientSdk.Analyzers] Refine AZC0030

- eng/common/scripts/Package-Properties.ps1
We got a diff that had ~24k files. We have a lot to check, but still need to optimize best we can.
> Early exit non-service changes, cache getchilditem results

- eng/common/pipelines/templates/steps/detect-api-changes.yml
- `$(Build.SourceVersion)` is a commit created during the DevOps pipeline run. `$(System.PullRequest.SourceCommitId)` is the actual HeadCommitSHA of the pull request.
> use the pull request head sha for APIView PR runs

- eng/common-tests/matrix-generator/pr-matrix-samples/net_scenarios.json
- eng/common-tests/matrix-generator/pr-matrix-samples/pr-matrix-generation-acceptance.helpers.ps1
- eng/common-tests/matrix-generator/pr-matrix-samples/pr-matrix-generation-acceptance.tests.ps1
- eng/common-tests/matrix-generator/pr-matrix-samples/python_scenarios.json
- eng/common/scripts/Package-Properties.ps1
Unfortunately I needed them to work because that PR yesterday did have an impact on python.
On a follow-up where I more samples for js and java, I will add the tests to the `eng-common` tests that are run. For now I need to get this through.
> Fixing an issue with `ExcludePaths`, Adding Acceptance Tests for PRMatrix Generation

- eng/common/TestResources/New-TestResources.ps1
- eng/scripts/live-test-resource-cleanup.ps1
Add the prefix to identify RGs that we are creating in our TME tenant to identify them as potentially using local auth and violating our safe secret standards.
> Add resource prefix for safe secret standard alerts

- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
See title.
Would prefer to avoid that.
> Ensure that direct batches have an underscore in front of them

- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
And ensure that we don't try to process a bare `null`. Which is what the source of the issue was before.
> Handle no indirect matrices

- src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs
- src/dotnet/APIView/apiview.yml
Update JS API parser version to 2.0.5 and update .NET parser version in the pipeline to latest released version.
> Update JS API parser version

- tools/apiview/parsers/rust-api-parser/src/main.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processAssocConst.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processAssocType.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processConstant.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processEnum.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processExternType.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processFunction.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processImpl.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processModule.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStatic.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStruct.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStructField.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTrait.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTraitAlias.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTypeAlias.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUnion.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUse.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/externalReexports.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/processGenerics.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/typeToReviewTokens.ts
Follow up of https://github.com/Azure/azure-sdk-tools/pull/9592
1. assoc_const aesthetics
2. func spaces
3. trait - remove extra punctuation
4. null check in processGenerics
5. "unsafe" traits
6. Negative implementations 
7. impl generics and where predicates
8. generics for assoc_type
9. qualified_path#generics_args
10. processGenericArgs for type.qualified_path.trait.args
11. Update RenderClasses with existing classes for now
And refactoring
> [API View] Extending rust-api-parser support 

- tools/apiview/emitters/typespec-apiview/CHANGELOG.md
- tools/apiview/emitters/typespec-apiview/package-lock.json
- tools/apiview/emitters/typespec-apiview/package.json
- tools/apiview/emitters/typespec-apiview/src/apiview.ts
- tools/apiview/emitters/typespec-apiview/src/emitter.ts
- tools/apiview/emitters/typespec-apiview/src/lib.ts
- tools/apiview/emitters/typespec-apiview/src/namespace-model.ts
- tools/apiview/emitters/typespec-apiview/src/schemas.ts
- tools/apiview/emitters/typespec-apiview/src/version.ts
- tools/apiview/emitters/typespec-apiview/test/apiview-options.test.ts
- tools/apiview/emitters/typespec-apiview/test/apiview.test.ts
- tools/apiview/emitters/typespec-apiview/test/test-host.ts
Removes `--version` option that isn't compatible with TSP 0.67 and wasn't used anyways. Updates for breaking changes in TSP 0.67.
> [TypeSpec APIView] Update for TypeSpec 0.67

- eng/common/scripts/Package-Properties.ps1
- eng/common/scripts/Save-Package-Properties.ps1
There are a few changes in here
1. Save-Package-Properties.ps1 - The $configFilePrefix is actually what will become the package properties json name for a given artifact however this was always being set to the ArtifactName. This was done because was JS which has Names that start with "@azure/". The problem with this is that it effectively eliminated the ability to change the package properties json name. The solution for JS (and any future language that might need to do this) is to declare a Get-PackageInfoNameOverride in the respective Language-Settings file to override this.
2. Package-Properties.ps1 - Change the PackageProps that takes in the Group to also take in the ArtifactName and set the Group and ArtifactName on the object _before_ calling Initialize. The reason for this is that …
> Package Properties processing updates

- .github/CODEOWNERS
Mostly because we are having stricter merge requirement soon.
Is it preferrable we try to have 2 (or more) persons in CODEOWNERS for the tool (so if owner raise a PR, the other owner can review and approve)?
> eng, codeowner, weidxu to azure-rest-api-specs-examples-automation

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/src/automation/entrypoint.ts
- tools/spec-gen-sdk/src/automation/logging.ts
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/cli/cli.ts
- tools/spec-gen-sdk/src/types/Message.ts
- tools/spec-gen-sdk/src/types/validator.ts
- tools/spec-gen-sdk/src/utils/fsUtils.ts
- tools/spec-gen-sdk/src/utils/runScript.ts
* Added `specConfigPath` property to `WorkflowContext` and used it to record the configuration path used for sdk generation
* Updated various error messages to remove trailing periods for consistency
* Removed setting pipeline variables of SDK pull request, and they will be set in the runner tool
> Refine error messages and specConfigPath

- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
The issue [occurring here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4675062&view=logs&j=76992fd1-2312-5fae-7c45-7baba86b87ae&t=936713e1-120b-5cc3-5ba6-7d192d0ede9d&l=195) is resolved in this PR.
The issue was that in the case of PR batching, we don't want to blindly add the matrix results as due to additional filters we may _have no_ items to add.
> Identify and Fix issue with non-pr-batched matrixResults in `Create-PRJobMatrix`

- eng/common/TestResources/deploy-test-resources.yml
Without this, existing post scripts can fail if they use az powershell cmdlets, similar to how we do this same thing for the above deploy task. The az import doesn't take any extra time since we've already done it there.
We still have to use the AzureCLI task because of its exclusive `addSpnToEnvironment` support.
> Import Az powershell module in self contained post script task

- eng/common/pipelines/templates/jobs/generate-job-matrix.yml
- eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
@JimSuplizio this should unblock you.
For everyone's benefit: I created a [draft PR](https://github.com/Azure/azure-sdk-for-java/pull/44813) with these changes in azure-sdk-for-java and I set the [PRMatrixKey to 'Name'](https://github.com/Azure/azure-sdk-for-java/pull/44813/files#diff-23849bb529451be6bf226bc895f60373a9181f673e6273d84474158a912d795bR457) with the expectation that since Name and ArtifactName are currently the same that the behavior would be the same. Looking at the generated [ArtifactPackageNames, it was](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4696989&view=logs&j=76992fd1-2312-5fae-7c45-7baba86b87ae&t=6c294a88-3151-521e-fcd8-a6c587ba9418&l=188).
> Support Accessing a Specific `key` for ArtifactName value in `Create-PrJobMatrix`

- src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs
- src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
- src/dotnet/APIView/APIViewWeb/Languages/JsonLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Managers/CodeFileManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/ICodeFileManager.cs
- Enusre language variable is passed down to GetCodeFileAsync
- Ensure JsonLanguage service is not selected in place of RustLanguageService
> Properly support Rust language

- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.html
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
- Allow approval regardless of age of diff revision.
- Properly manage diff revision state
> Update Approval Button tooltip

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/entrypoint.ts
* [`tools/spec-gen-sdk/src/automation/entrypoint.ts`]: Modified the configuration logic to read the corresponding SDK repository configuration for private repositories. Added error handling for missing SDK repository mappings.
> Read sdk repo config for private repo case

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/test/commands.spec.ts
- tools/tsp-client/test/examples/sdk/alternate-entrypoint/tsp-location.yaml
- tools/tsp-client/test/examples/sdk/contosowidgetmanager/contosowidgetmanager-rest/tsp-location.yaml
- tools/tsp-client/test/examples/sdk/local-spec-sdk/tsp-location.yaml
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/client.tsp
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-12-01/Widgets_CreateOrUpdateWidgetSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-12-01/Widgets_DeleteWidgetSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-12-01/Widgets_GetWidgetOperationStatusSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-12-01/Widgets_GetWidgetSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/examples/2022-12-01/Widgets_ListWidgetsSample.json
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/main.tsp
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml
- tools/tsp-client/test/examples/specification/diagnostics/main.tsp
- tools/tsp-client/test/typespec.spec.ts
- tools/tsp-client/test/utils/emitter-package-lock.json
- tools/tsp-client/test/utils/emitter-package.json
Unblocking support for `@typespec/compiler` v1.0. Still supporting 0.66.0 and later for a bit longer to give time for folks to move forward to the stable compiler version.
> [tsp-client] Unblock compiler 1.0 support

- tools/tsp-client/src/commands.ts
- tools/tsp-client/src/index.ts
- tools/tsp-client/src/typespec.ts
- tools/tsp-client/src/utils.ts
- tools/tsp-client/test/commands.spec.ts
Fixes https://github.com/Azure/azure-sdk-tools/issues/10173
> [tsp-client] Allow an alternate path for emitter-package.json

- eng/common/TestResources/New-TestResources.ps1
This is used by identity, for example: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/test-resources-post.ps1#L34
> Add AdditionalParameters global variable to dynamic post script

- tools/test-proxy/tests.yml
Elsewhere, dotnet tests run one at a time for a specific framework. In the test-proxy integration tests, we ran them in _parallel_. I'm just splitting this up so that this [error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4719358&view=logs&j=fab08167-d63b-51ff-cd93-7068dc91610b&t=07c6419c-06a1-542d-26b6-b036293b8068) doesn't occur anymore.
> Fix failing `test-proxy` .NET integration tests

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
- tools/tsp-client/test/examples/specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml
- tools/tsp-client/test/examples/tspconfig-custom-service-dir.yaml
Given the recent changes in typespec validation for the tspconfig.yaml file, move configuration options specific to tsp-client under an entry in the `options` property of tspconfig.yaml. This change affects the way additionalDirectories will be specified.
> [tsp-client] Fix additional directory implementation

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
- tools/tsp-client/src/fs.ts
- tools/tsp-client/src/index.ts
- tools/tsp-client/test/commands.spec.ts
- tools/tsp-client/test/utils/alternate-emitter-package-lock.json
- tools/tsp-client/test/utils/alternate-emitter-package.json
- Use repo root for emitter-package path and match package-lock naming with specified emitter path
- include azure-typespec scope in emitter list
- Update generate-config/generate-lockfile commands
Contributes to https://github.com/Azure/azure-sdk-for-net/issues/49240
> EmitterPackageJsonPath fixes

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/entrypoint.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/cli/cli.ts
- tools/spec-gen-sdk/src/types/GenerateInput.ts
- tools/spec-gen-sdk/src/types/GenerateInputSchema.json
- tools/spec-gen-sdk/src/utils/utils.ts
- tools/spec-gen-sdk/test/utils.test.ts
* Added `runMode` input parameter and deprecated `isTriggeredByPipeline` parameter in various files, including `entrypoint.ts`, `cli.ts`, and `GenerateInput.ts`. This new parameter will be used by the downstream automation script to determine the right steps to run for different scenarios.
* Simplified the error message in `sdkAutoMain` function to remove redundant information.
> Pass scenario type to downstream language scripts

- .github/CODEOWNERS
- CODEOWNERS is read bottom to top, /tools/issue-labeler/ and /tools/github/ entries were above the /tools/ catch all and were setting the owners to engsys instead of @jeo02 and @jsquire
> [CODEOWNERS] Fixing codeowners for issue-labeler and github tools

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/SanitizerTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/SanitizerDictionary.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/README.md
It doesn't seem like we're going to create unbranded or productized version of the proxy _as of yet_, but this will definitely help the unbranded effort for now.
Continuing the vein of `TEST_PROXY_X` like the only other config value that is allowable right now.
FYI @HarshaNalluru you were who I was discussing this with .
> Allow `TestProxy` to start without default sanitizers

- eng/common/pipelines/templates/archetype-typespec-emitter.yml
- tsp-client generation of the config files needs to happen when regenerating, not when publishing. 
- get the emitterVersion output from the correct stage
- Add Do Not Merge label to PR only when triggered manually or not against main.
Tested in https://github.com/Azure/azure-sdk-for-net/pull/49409
> Move tsp-client to regenerate stage

- packages/python-packages/apiview-copilot/evals/run.py
writes results to results/language/.log (ignored by gitignore)
> [apiview-copilot] always log results for evals

- eng/common/scripts/Helpers/ApiView-Helpers.ps1
- Don't add comment to the pull request if no API change is found.
- The helps address the problem of adding comments even when the API check change did not actually occur even though its pipeline was run
> Exit early if no API changes are found

- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_search_manager.py
Ensures that, by default, general guidelines aren't used either in RAG or static mode.
> [APIView Copilot] Disable use of general guidelines by default.

- tools/issue-labeler/src/IssueLabeler.Shared/TriageOutput.cs
- tools/issue-labeler/src/IssueLabelerService/Answers/IAnswerService.cs
- tools/issue-labeler/src/IssueLabelerService/Answers/OpenAiAnswerService.cs
- tools/issue-labeler/src/IssueLabelerService/AzureSdkIssueLabelerService.cs
- tools/issue-labeler/src/IssueLabelerService/Configuration/RepositoryConfiguration.cs
- tools/issue-labeler/src/IssueLabelerService/Labelers/ILabeler.cs
- tools/issue-labeler/src/IssueLabelerService/Labelers/LegacyLabeler.cs
- tools/issue-labeler/src/IssueLabelerService/Labelers/OpenAiLabeler.cs
- tools/issue-labeler/src/IssueLabelerService/TraigeRag.cs
- tools/issue-labeler/src/SearchIndexCreator/IssueIndex.cs
- Filter through issues based on labels.
- Switched around the `OpenAiLabeler` output order since it was wrong.
- ~~Not filtering labels for Documents until dotnet documents have Service and Category labels.~~
- Added Filtering to Service and Category labels
> [AI Triage] Utilizing Labels for Answer Service

- tools/spec-gen-sdk/src/templates/commentDetailNew.handlebars
This pull request includes a minor fix to the `tools/spec-gen-sdk/src/templates/commentDetailNew.handlebars` file. The change corrects a misplaced closing brace in the template syntax to properly reference `config.version`.
> [spec-gen] bugfix for missing closing brace

- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/evals/run.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
Previously configuration was split between the ApiViewReviewer constructor and the get_response method. This PR moves all of that configuration to the constructor, making it easier to understand and maintain.
Also `evals\run.py` adjusted to use the defaults, the same as the app-service.
> [APIView Copilot] Move all configuration to ApiViewReviewer constructor

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/templates/commentDetailNew.handlebars
This pull request updates the `spec-gen-sdk` tool to version 0.4.2 and removes references to the SDK suppressions file from the codebase. Key changes include refactoring file handling logic, removing suppression-related templates, and updating versioning metadata.
* Updated the version of the `spec-gen-sdk` tool from 0.4.1 to 0.4.2 in `package.json` and `package-lock.json` to reflect the new release. 
* Removed the `sdkSuppressionFilePath` variable from file parsing logic in `workflow.ts` to simplify file handling by directly referencing the file path.
* Deleted all suppression-related rendering logic from the `commentDetailNew.handlebars` template, including links to suppression files and associated error messages.
* Added a changelog entry for version 0.4.2, documenting the removal of …
> Spec-Gen-SDK for Suppressions File Link

- eng/common-tests/matrix-generator/pr-matrix-samples/js_scenarios.json
- eng/common-tests/matrix-generator/pr-matrix-samples/net_scenarios.json
- eng/common/scripts/Package-Properties.ps1
Badly placed break. This will jump out at you when you see the change. This came up because I added `eng/` to the `triggeringPaths` for `Azure.Core` in the .NET repo and the nothing changed as far as generated package props.
> Accidental Early-Exit on additional `triggeringPaths` in `Get-PrPkgProperties`

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- tools/spec-gen-sdk/src/types/ExecutionReport.ts
Instead of writing a pipeline variable, return the services as part of the execution report.
> Return services as part of execution report

- packages/python-packages/apiview-copilot/prompts/generic_result_schema.json
- packages/python-packages/apiview-copilot/prompts/guideline_result_schema.json
- packages/python-packages/apiview-copilot/scratch/apiviews/ios/AzureCommunicationCalling.txt
- packages/python-packages/apiview-copilot/scratch/output/ios/AzureCommunicationCalling.json
- packages/python-packages/apiview-copilot/src/_models.py
Fixes the bug that would putting unmatched lines on a blank line instead of throwing them away. However, now instead of throwing the comment away, it will simply default to the original line_no since this often occurs when the "bad_code" isn't actually code because the issue is more general. 
These comments are mark to end with "(general comment)" so we can evaluate them and, if we hate them, go back to tossing them out. 
Fixes #10443
> [APIView Copilot] Fix line number heuristics 

- packages/python-packages/apiview-copilot/scratch/output/ios/AzureCommunicationCalling.json
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
Without this, we would be populating the prompts with things like 
- "Be idiomatic for ios developers"
- "Be idiomatic for cpp developers"
Instead these SHOULD read:
- "Be idiomatic for Swift developers"
- "Be idiomatic for C++ developers"
Etc.
> [APIView Copilot] Ensure templates are populated with the "pretty" language name

- eng/scripts/Create-Apiview-Token-Python.ps1
Reverting this PR for now: https://github.com/Azure/azure-sdk-tools/pull/10357/files
Originally changed "apistub" to "apistubgen" since that's the command used everywhere else, and thought it might account for discrepancy we're seeing between local generation and CI. However, the "apistubgen" command seems to not even be recognized in the pipeline. Need to investigate + test more.
> [Python APIView] fix manual upload command

- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/MockGitHubEventClient.cs
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor.Tests/Static/IssueProcessingTests.cs
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/IssueProcessing.cs
- tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs
- Added in `DisableAnswers` and `DisableLabels` to turn off either service through here.
- When issue is not customer reported we will disable answers and not add `needs-team-attention`
> Adding additional parameters to AI Triage Service

- eng/scripts/Approve-Eng-Common-Sync-PRs.ps1
Make eng/common sync PR approve script runnable from bash
> Make eng/common sync PR approve script runnable from bash

- tools/apiview/parsers/rust-api-parser/CHANGELOG.md
- tools/apiview/parsers/rust-api-parser/package.json
- tools/apiview/parsers/rust-api-parser/src/main.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processAssocConst.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processEnum.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processItem.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processMacro.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processModule.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStruct.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUnion.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUse.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/cratePathUtils.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/externalReexports.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/generateDocReviewLine.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/models.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/pathUtils.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/sorting.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/typeToReviewTokens.ts
The primary objective is to enhance the rendering of `use` items, to keep it closer to the rustdoc (docs.rs) HTML view.
1. **Refactor of `processUse` & Consolidation of Reexport Logic**:
- The previous approach used `reexportLines` for managing internal and external reexports. 
- The function `processUse` has been restructured to handle various complex cases of `use` items, including glob imports, module references, differentiating between items in `apiJson.index` and `apiJson.paths`, and external paths.
- And a more streamlined structure for external references using `registerExternalItemReference`.
2. **Refactor of `processModule`**:
- Enhanced logic to handle sibling modules and child items more effectively, with clearer separation of concerns.
- Refactored `processModule` to split …
> [rust-api-parser] Enhance `use` item rendering

- eng/common/TestResources/New-TestResources.ps1
Given we are using the tenantId to determine to add the prefix or not we need to make sure we have it set before we check it. For the pipelines it is set at the script calling time, so it was working there but for some local scenarios it is not set yet, so we need to do it a little later in the script.
> Set the resource group prefix after we get the tenantId

- eng/common/scripts/Helpers/ApiView-Helpers.ps1
- Properly handle error for case where no issue (pr) is found for specified commit.
- Log `OperationId` to enable location of trace data in App Insights
> Properly handle error for case where no issue (pr) is found for specified commit

- packages/python-packages/apiview-copilot/metadata/python/filter.yaml
- packages/python-packages/apiview-copilot/prompts/filtered_result_schema.json
- packages/python-packages/apiview-copilot/prompts/final_comments_filter.prompty
- packages/python-packages/apiview-copilot/prompts/generic_result_schema.json
- packages/python-packages/apiview-copilot/prompts/generic_review.prompty
- packages/python-packages/apiview-copilot/prompts/guideline_result_schema.json
- packages/python-packages/apiview-copilot/prompts/guidelines_review_reasoning.prompty
- packages/python-packages/apiview-copilot/prompts/guidelines_review_regular.prompty
- packages/python-packages/apiview-copilot/prompts/merge_comments.prompty
- packages/python-packages/apiview-copilot/scratch/output/python/content_understanding.json
- packages/python-packages/apiview-copilot/scratch/output/python/image_analysis.json
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- packages/python-packages/apiview-copilot/src/_models.py
- packages/python-packages/apiview-copilot/src/_search_manager.py
Closes #10444.
Closes #10429.
This pull request does work to better ensure that suggestions are only code, not prose. It also uses a gpt-4o prompt to intelligently (I hope) merge multiple comments on the same line instead of programmatically doing so.
> [APIView Copilot] Ensure that suggestions are ONLY code

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
There are conflicts due to the rest-api-diff tool pulling in dev versions of certain packages when installing tsp-client.
> Update typespec/compiler dep

- eng/common/pipelines/templates/archetype-typespec-emitter.yml
This PR fixes a dependency issue with installing & using the `tsp-client` with node v18.x.
Tested in : https://github.com/Azure/azure-sdk-for-net/pull/49789
> fix: bump node version in emitter pipeline

- packages/python-packages/apiview-copilot/prompts/filtered_result_schema_single.json
- packages/python-packages/apiview-copilot/prompts/final_comment_filter_single.prompty
- packages/python-packages/apiview-copilot/prompts/merge_comments.prompty
- packages/python-packages/apiview-copilot/scratch/output/python/clinical_matching.json
- packages/python-packages/apiview-copilot/scratch/output/python/image_analysis.json
- packages/python-packages/apiview-copilot/scratch/output/python/keyvault_secrets_4.10.0b1.json
- packages/python-packages/apiview-copilot/scratch/output/python/keyvault_secrets_4._2.0_10.0b1.json
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- Runs the de-duplication prompts in parallel
- Coverts the filtering stage to use one prompt per comment with a gpt-4.1 model, running in parallel, to significantly reduce the runtime of this stage
- Adds more logging to show how long each of the three stages takes
> [APIView Copilot] Run de-duplication and filtering with multiple, parallel prompts

- tools/apiview/parsers/rust-api-parser/CHANGELOG.md
- tools/apiview/parsers/rust-api-parser/src/main.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processAssocConst.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processAssocType.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processConstant.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processEnum.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processExternType.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processFunction.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processImpl.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processMacro.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processModule.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processProcMacro.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStatic.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStruct.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processStructField.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTrait.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTraitAlias.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processTypeAlias.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUnion.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/processUse.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/externalReexports.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/generateDocReviewLine.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/pathUtils.ts
- tools/apiview/parsers/rust-api-parser/src/process-items/utils/typeToReviewTokens.ts
- tools/apiview/parsers/rust-api-parser/src/utils/lineIdUtils.ts
- Introduced `lineIdMap` to map item IDs to stable, meaningful identifiers rather than relying on the dynamic rustdoc ids.
- Updated `updateReviewLinesWithStableLineIds` to ensure consistent review line IDs across modules and external references.
- Preserved the linking between items in the api view rendering
- This is required to show meaningful diff between api views
- Other changes include formatting and minor refactoring
New diff
- azure_identity
- azure_core
- azure_messaging_eventhubs
- azure_security_keyvault_certificates
> [rust-api-parser] Update parser to have Stable Line IDs

- packages/python-packages/apiview-copilot/evals/results/python/small.json
- packages/python-packages/apiview-copilot/evals/run.py
- packages/python-packages/apiview-copilot/metadata/python/filter.yaml
- packages/python-packages/apiview-copilot/prompts/code_to_text.prompty
- packages/python-packages/apiview-copilot/prompts/eval_judge_prompt.prompty
- packages/python-packages/apiview-copilot/prompts/final_comment_filter_single.prompty
- packages/python-packages/apiview-copilot/prompts/final_comments_filter.prompty
- packages/python-packages/apiview-copilot/prompts/generate_outline.prompty
- packages/python-packages/apiview-copilot/prompts/generic_diff_review.prompty
- packages/python-packages/apiview-copilot/prompts/generic_review.prompty
- packages/python-packages/apiview-copilot/prompts/guidelines_diff_review.prompty
- packages/python-packages/apiview-copilot/prompts/guidelines_review.prompty
- packages/python-packages/apiview-copilot/prompts/merge_comments.prompty
- packages/python-packages/apiview-copilot/prompts/summarize_api.prompty
- packages/python-packages/apiview-copilot/prompts/summarize_diff.prompty
- packages/python-packages/apiview-copilot/scratch/output/python/content_understanding.json
- packages/python-packages/apiview-copilot/scratch/output/python/image_analysis.json
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
- This PR adds an outline prompt that generates an API skeleton as a placeholder until we can get a deterministic one passed in. 
- It then uses this outline in the filter to filter out comments that result from chunking that can be verified invalid by referencing the outline. 
- Tunes the gpt4.x prompts to be deterministic (unfortunately this isn't really possible with the reasoning models!)
- Updates evals to use a prompty file for the generic comment judge instead of a direct openAI call
**TODO**
> [APIView Copilot] Add outline generation and filtration

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/reportStatus.ts
- tools/spec-gen-sdk/src/automation/workflow.ts
- tools/spec-gen-sdk/src/types/ExecutionReport.ts
- tools/spec-gen-sdk/src/types/PackageData.ts
This pull request introduces updates to the `spec-gen-sdk` tool, focusing on improving SDK generation workflows, enhancing error handling, and updating versioning. The most significant changes include turning certain errors into warnings to allow SDK generation to proceed, adding a new `language` field to the `PackageData` object, and updating version information to `0.6.1`.
* Changed duplicated SDK configuration errors into warnings, enabling SDK generation to continue despite configuration issues.
* Updated warning messages for unsupported emitter configurations and missing `swagger-to-sdk` sections to improve clarity and guidance.
* Added a `language` property to the `PackageData` object to capture the programming language of the SDK being generated.
> Continue SDK generation even if having duplicated SDK config

- eng/common/scripts/ChangeLog-Operations.ps1
- eng/common/scripts/Package-Properties.ps1
This eliminates the noisy changelog lines and add output helping to understand why a particular package was included in a PR validation build.
> Improve logging for package detection for pullrequests

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/New-TestResources.ps1.md
- eng/common/TestResources/README.md
- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/TestResources-Helpers.ps1
- eng/common/scripts/common.ps1
If a language repo opts into it *and* if a `test-resources.bicep` file exists and lints clean of writing secrets *and* if the `.env` file is gitignore'd, write a `.env` file next to `test-resources.bicep`.
> Support writing .env files from Test Resources

- eng/scripts/Approve-Eng-Common-Sync-PRs.ps1
This updates the approval script to pull the sync PR data from the pipeline and then use that. This will enable us to use it for both eng/common and workflow syncs and even PRs that have both.
> Update approve script to work with both sync PR types

- packages/python-packages/apiview-copilot/app.py
- packages/python-packages/apiview-copilot/src/_apiview_reviewer.py
Closes #10623.
Adding "outline" will allow us to get rid of the workaround "generate_outline" prompt once it is being sent.
Adding "target_id" will allow us to post comments to APIView directly instead of returning a JSON payload that it uses to post the comments. This is desired because the APIView web side is sometimes failing when the Flask service is successful.
> [APIView Copilot] Add outline and target_id to request payload

- eng/common/scripts/Verify-Links.ps1
fixes #10601
In html, attribute values are encoded and should be decoded before use.  If not decoded using `[HttpUtility]::HtmlDecode()`, the url is incorrect and the server should not be expected to process it correctly.
In powershell, the markdown
```md
[example](https://dev.azure.com/azure-sdk/public/_build?view=branches&definitionId=7050)
```
is converted to the html
```html
<a href="https://dev.azure.com/azure-sdk/public/_build?view=branches&amp;definitionId=7050">Example</a>
```
which is regex parsed to 
```
https://dev.azure.com/azure-sdk/public/_build?view=branches&amp;definitionId=7050
```
and needs to be HtmlDecoded to
```
https://dev.azure.com/azure-sdk/public/_build?view=branches&definitionId=7050
```
> HtmlDecode hrefs in Verify-Links.ps1

- eng/common/TestResources/New-TestResources.ps1
- eng/common/TestResources/Remove-TestResources.ps1
- eng/common/TestResources/SubConfig-Helpers.ps1
- eng/common/TestResources/deploy-test-resources.yml
azure-mcp needs to deploy test resource and doesn't use the `sdk/<ServiceDirectory>` repo structure
> Allow for empty serviceDirectory in deploy-test-resources

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SDKWorkFlowTool/SDKWorkFlowTool.cs
Allow SDK gen for data plane only if api stewardship approval is present or if spec PR is in merged status
> Allow SDK gen for data plane only if api stewardship approval is present

- eng/pipelines/branch-cleanup.yml
- eng/pipelines/merge-docs-main-to-live.yml
Fixes #10067
Fixes #10599
Original instructions say to keep Azure/* repos around but the whole repo is changing orgs so those repos would get redirected from Azure to MicrosoftDocs and the work would be duplicated
> [Branch Cleanup, main-to-live] Migrate docs repos

- eng/scripts/Verify-And-Merge-PRs.ps1
If one PR wasn't ready to merge then after a retry we lost all the other PRData so we only end up trying to merge the one.
See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4866203&view=logs&j=f6a7114c-32c6-5cc4-d467-98fb1350225d&t=92d3002b-c214-53f7-faf6-6294b17e07f4&s=b0f91f5f-86bb-51b4-905a-b77da63d1728
> Check status on all PRs on retry not just the ones that failed.

- src/go/cmd/pkg.go
Ensure that they're all using the same path separator character.
> Canonicalize directory paths

- src/java/apiview-java-processor/pom.xml
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/Main.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/JavaASTAnalyser.java
- src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/analysers/models/Constants.java
- src/java/apiview-java-processor/src/main/resources/CodeFile.json
This is the first iteration of improving perf for Java API view parser.
- Updated the JavaASTAnalyser to use parallelstream() for scanning types. 
- Using local schema file for validation instead of downloading the schema each time 
Used **ARM Compute library** for testing this as it has quite a large API surface.
**Before:**
Total time for 5 iterations: 27.283 seconds
Average time per iteration: 5.457 seconds
**After:**
Total time for 5 iterations: 19.043 seconds
Average time per iteration: 3.809 seconds
> First iteration of perf improvements

- eng/common/pipelines/templates/steps/save-package-properties.yml
for `go` especially the `ServiceDirectory` of each package doesn't necessarily align with the `sdk/<X>` pattern that we currently fill for `ChangedServices`.
Just updating this to use the generated package props Service Directories, which WILL reflect this reality.
FYI @benbp doing the needful from our convo.
> Ensure that we log the actual `serviceDirectories` when tagging a PR build

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/automation/workflow.ts
This pull request includes updates to the `spec-gen-sdk` tool, addressing a bug in suppression file parsing logic and incrementing the version to `0.7.1`. These changes ensure better handling of empty suppression files and align the versioning across relevant files.
* [`tools/spec-gen-sdk/src/automation/workflow.ts`](diffhunk://#diff-8abb2fc1b35d9aa372c77e814cacaa598863a407057a1a79877222cb57ab9f0eL277-R277): Fixed the logic to correctly handle cases where suppression files are empty by updating the condition to check for a falsy `suppressionFileParseResult`.
* [`tools/spec-gen-sdk/package.json`](diffhunk://#diff-5532e95511ec7c2d2c5fdbb91be5dab5521875c1e5d0206b4fc66ee25e0596eaL8-R8): Updated the version from `0.7.0` to `0.7.1`.
* [`tools/spec-gen-sdk/package-lock.json`](diffhunk://#diff-30b …
> [spec-gen-sdk] bugfix for sdk-suppressions content judgement

- .gitignore
- src/dotnet/APIView/APIViewWeb/Languages/GoLanguageService.cs
- src/dotnet/APIView/APIViewWeb/Languages/LanguageProcessor.cs
- src/dotnet/APIView/APIViewWeb/Languages/PythonLanguageService.cs
- Refactor methods for running child process
- Use `UseShellExecute = false` and read output streams before calling `WaitForExit` to avoid deadlocks.
Replaces https://github.com/Azure/azure-sdk-tools/pull/10676
> Api view sub processing

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Program.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HelloWorldTool/HelloWorldTool.cs
And we have an extremely easy way to make this work. The only concern is if tests run in Debug or Release mode to have the tool available.
> Ensure debugging tool isn't visible to end users

- tools/spec-gen-sdk/CHANGELOG.md
- tools/spec-gen-sdk/package-lock.json
- tools/spec-gen-sdk/package.json
- tools/spec-gen-sdk/src/types/PackageData.ts
* Corrected the key used in the suppression files map within the `getPackageData` function to include `/tspconfig.yaml` for `typespecProject` entries. Also removed special logic for Go for the suppression map key because now Go result returns the correct readme path with 'specification' prefix.
> Corrected the key when match the suppression file in the map

- eng/common/pipelines/templates/steps/detect-api-changes.yml
- eng/common/scripts/Detect-Api-Changes.ps1
- eng/common/scripts/Helpers/ApiView-Helpers.ps1
- src/dotnet/APIView/APIViewWeb/Helpers/APIHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/PullRequestsController.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IPullRequestManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/PullRequestManager.cs
- Converts PullRequestController to API controller
- Return object that include actions taken in APIView data to give user better insight on how APIView was created or updated.
- Use correlation Id in API call headers to allow for easier location of telemetry
- Update calls to PullRequestController API
- Deploy these changes before merging
Sample response
```json
{
"apiRevisionUrl": "https://localhost:5000/Assemblies/Review/2b6aa77e83404f5fa60cf9aa5a8f771c?revisionId=dc3807c473ed4ed9bed34193283d7015",
"actionsTaken": [
"Pull Request data for PR updated with new CommitSha '61c3ba9a94bc54df2593189af7153b947f82af00'",
"Pull Request has changes in the API surface when compared to the last updated existing APIRevision.",
"Created New APIRevision with id 'dc3807c473ed4ed9bed34193283d7015'."
]
} …
```
> Make MVC controllers API Controllers

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/ReleasePlan.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/GitHubService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecValidationTool/SpecValidationTool.cs
- Add support to create test release plan
- Include SDK release type in release plan
- Change TypeSpec validation to use call back to get output from process
- Get release plan using work item id or release plan number.
> Release plan mcp changes

- tools/sdk-testgen/src/index.ts
autorest.go rely on this package. in order to upgrade to latest version, it needs to export some types used in autorest.go
> [testmodeler] export type

- eng/common/mcp/azure-sdk-mcp.ps1
Specify run directory as repo root for mcp runner
> Specify run directory as repo root for mcp runner

- eng/common/scripts/common.ps1
Use correct leading slash in common.ps1 repo root resolution. You need a leading slash after $PSScriptRoot, hence why the current code has to use 4 `..` instead of 3 (the first ends up getting ignored).
> Use correct leading slash in common.ps1 repo root resolution

- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/changelog/automaticGenerateChangeLogAndBumpVersion.ts
- tools/js-sdk-release-tools/src/common/changelog/modifyChangelogFileAndBumpVersion.ts
- tools/js-sdk-release-tools/src/common/interfaces.ts
- tools/js-sdk-release-tools/src/llc/apiVersion/apiVersionTypeExtractor.ts
- tools/js-sdk-release-tools/src/mlc/apiVersion/apiVersionTypeExtractor.ts
- tools/js-sdk-release-tools/src/xlc/apiVersion/apiVersionTypeExtractor.ts
- tools/js-sdk-release-tools/src/xlc/apiVersion/utils.ts
- tools/js-sdk-release-tools/src/xlc/codeUpdate/updateUserAgent.ts
https://github.com/Azure/azure-sdk-tools/issues/10798
simply check for parameters.ts - its absence indicates a model-only service
test: https://dev.azure.com/azure-sdk/public/_build/results?buildId=4943502&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692&l=857
> [Part 2] detect parameters.ts for model only

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Analyzer/EnforceToolsExceptionHandling.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Analyzer/EnforceToolsList.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Commands/SharedOptions.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecValidationTool/SpecValidationTool.cs
in the previous PR #10861  we removed reflection from `azsdk-cli` so that we could massively improve our startup times.
This PR adds a compilation-end analyzer that _checks_ this static ToolsList against the newly created assembly. If the toolslist doesn't match up, throw an error!
The actually hilarious part is that this immediately caught an issue with my previous PR:
So this PR also resolves that issue.
> Add compile-time enforcement ensuring static ToolsList is correctly populated

- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IUserProfileManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/UserProfileManager.cs
- src/dotnet/APIView/APIViewWeb/Models/UserPreferenceModel.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Index.cshtml.cs
- src/dotnet/APIView/APIViewWeb/Repositories/CosmosUserProfileRepository.cs
- src/dotnet/APIView/APIViewWeb/Repositories/UserProfileCache.cs
This is a follow up on https://github.com/Azure/azure-sdk-tools/pull/10498
We need to have only one path for updating user preferences, which is through the cache.
> Ensure all updates to user preference happens from the cache

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/GitHubService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecPullRequestTools/SpecPullRequestTools.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecWorkflowTool/SpecWorkFlowTool.cs
This PR renames asynchronous methods to include the 'Async' suffix, following C# naming conventions.
> Rename methods to include 'Async' suffix

- .github/CODEOWNERS
The focus of these changes is to add the Azure SDK for .NET team to the paths associated with the .NET tooling and utilities.
> [CODEOWNERS] Add .NET team to tools paths

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/typespec.ts
- tools/tsp-client/test/typespec.spec.ts
tsp support options of object type but currently tsp-client only pass key/value string pairs as additional emitter options to tsp.  This PR tries to parse the value string first. If the result is a non-null and non-array object, pass the parsed object; otherwise pass the original string.
Resolves https://github.com/Azure/azure-sdk-tools/issues/10821
> [tsp-client] Allow emitter option of object type 

- eng/common/TestResources/New-TestResources.ps1
Path.Combine will allow for fully qualified paths to override the combination. For example `Path.Combine("a","b","c:\test")` will resolve to `c:\test'. We have depended on such behavior in a few places like https://github.com/Azure/azure-sdk-for-python/blob/d66b5160f2fb9a3ca03e833a65b1c429993b2bc2/eng/pipelines/templates/steps/smoke-test-steps.yml#L99 so I'm reverting back to Path.Combine.
> Use Path.Combine for create directory

- eng/common-tests/matrix-generator/samples/matrix-test.yml
- eng/common-tests/matrix-generator/samples/matrix.json
- eng/pipelines/agent-software-inventory.yml
- eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
- eng/pipelines/templates/steps/inventory-steps.yml
- eng/pipelines/templates/variables/image.yml
- packages/python-packages/apiview-copilot/tests.yml
- tools/apiview/emitters/typespec-apiview/ci.yml
- tools/apiview/parsers/js-api-parser/ci.yml
- tools/apiview/parsers/rust-api-parser/ci.yml
- tools/js-sdk-release-tools/ci.yml
As well as swapping on to `azsdk-pool` wherever I made this update.
Manually invoked:
- ~~Discovered a failure in `windows` invocation. `Get-WmiObject` is crashing on `windows-2022` for some reason.~~
- ~~It's not assigning to a windows machine. Trying to understand why.~~
- Solved the windows machine conflict, now the same `demands` methodology that works for `windows` isn't properly assigning `ubuntu 22.04` instead of `ubuntu 24.04`.
As well as running a test run for `test-proxy` that should exercise the new platform.
> Convert azure-sdk-tools to use `ubuntu-24.04` instead of `20.04`

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/README.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
- tools/tsp-client/src/index.ts
- tools/tsp-client/test/run_commands.ts
Removing this command as `rest-api-diff` is no longer being developed, so partners should not rely on this command.
> Remove "tsp-client compare"

- packages/python-packages/apiview-copilot/src/agent/plugins/_api_review_plugin.py
`mode` cannot be passed here - as the constructor derives it from the value of `base`.
> [ApiviewCopilot] Unexpected kwarg

- eng/common/pipelines/codeowners-linter.yml
For this common pipeline we can rely on the version of .NET installed on the agent as we are only installing and running an existing tool. 
There are some repositories that have a global.json file at the root of the repository (tools and .NET) that specifies a version of .NET SDK that conflicts with this command so in order to workaround we are running the install command outside of the source directory.
> Update codeowner linter so it works on ubuntu24 and when there is root global.json

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/GitHubService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
Return work item ID instead of release plan ID to provide unique value among the different env
> Update response to include work item 

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
- Rename ValidateCreateReleasePlanInputAsync to follow .NET naming conventions
- Async methods should have 'Async' suffix for better code readability
> Fix async method naming convention in ReleasePlanTool

- src/dotnet/APIView/APIViewWeb/Account/AutoAPIRevisionModifierRequirementHandler.cs
- src/dotnet/APIView/APIViewWeb/Account/CommentOwnerRequirementHandler.cs
- src/dotnet/APIView/APIViewWeb/Filters/ApiKeyAuthorizeAsyncFilter.cs
- src/dotnet/APIView/APIViewWeb/Helpers/ApiViewConstants.cs
- src/dotnet/APIView/APIViewWeb/Managers/APIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/Interfaces/IAPIRevisionsManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/PullRequestManager.cs
- src/dotnet/APIView/APIViewWeb/Managers/ReviewManager.cs
- src/dotnet/APIView/APIViewWeb/Pages/Assemblies/Review.cshtml
There are multiple places in where we have the string "azure-sdk" so replacing this, if we feel more comfortable having this on a cofig, also happy to do that change instead, I just think we need to have a place where this is defined
> Refactor: Just pointing out to a single location for bot name 

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/SpecWorkFlowToolTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecWorkflowTool/SpecWorkFlowTool.cs
- Change pull request and release plan as optional when generating SDK
- Update API status as approved when checking API readiness
- Tests to verify SDK generation without release plan and spec pull request
> Support SDK generation without release plan and pull request

- eng/common-tests/ci.yml
- eng/common/scripts/job-matrix/Create-JobMatrix.ps1
To help debug matrix filters and other generation issues add additional logging.
> Add additional create matrix logging

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Program.cs
Azure SDK MCP server cannot be started on two vs code instances because both instances are trying to use port 5000. If user has Azure SDK MCP configured in more than one repo, then it's throwing exception when starting MCP server.
This change will use available port instead of 5000 to start MCP server.
> Start MCP server using available port instead of 5000

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecWorkflowTool/SpecWorkFlowTool.cs
Added further guidance for agents when sdk details are not present in the release plan. Resolves: https://github.com/Azure/azure-sdk-tools/pull/11036#discussion_r2178873704
> Add better description for insufficient sdk details error 

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/GitHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/SpecPullRequestTools/SpecPullRequestTools.cs
`CreatePullRequest` Tool could only be used in azure-rest-api-specs repository since it was using `TypeSpecProject` path to find repo root. Find repo root through `Repository.Discover` instead and added repo root parameter.
Resolves #10985
> [SDK Release Agent] Changed CreatePullRequest MCP to support all repos

- src/dotnet/APIView/APIViewWeb/HostedServices/CopilotPollingBackgroundHostedService.cs
Issue: https://github.com/Azure/azure-sdk-tools/issues/11098
> [APIView] Change display of multiple guidelines

- packages/python-packages/apiview-copilot/cli.py
Adds a command to the CLI:
`cli apiview get-comments --revision-id [ID]`
It returns a list of key value pairs where the key is the element or line ID of the thing in APIView and the value is the list of comments, sorted by CreatedOn time. Deleted and resolved comments are omitted from results, as are fields with null values and special internal keys.
> [APIView Copilot] Add `cli apiview get-comments` command

- eng/common/pipelines/codeowners-linter.yml
We don't need codeql running randomly on our linter pipelines as it isn't interesting there, so I'm skipping it.
See https://dev.azure.com/azure-sdk/public/_build/results?buildId=5071971&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=5348fcfc-3752-5d67-089f-bab4d1181c52
> Disable codeql for linter pipeline

- src/dotnet/APIView/APIViewWeb/Helpers/AgentHelpers.cs
- src/dotnet/APIView/APIViewWeb/LeanControllers/APIRevisionsController.cs
- src/dotnet/APIView/APIViewWeb/Managers/NotificationManager.cs
Copilot is writing some comments when reviewing the API, and in some cases are written and not elementId is assigned to them.
issue: https://github.com/Azure/azure-sdk-tools/issues/11170
> Fix scenario where elemendId, for comments, is null

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
Azure CLI token chain fails with a time out error when using chained token credentials when running in MCP context. Adding Interactive browser credentials as a fallback mechanism to fix auth issue. Adding this interactive token into chained token credentials is not resolving this issue and credential is not attempting all the types in the chain.
> Fallback to interactive credentials when chained token cred fail

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/typespec.ts
- tools/tsp-client/test/examples/specification/unexpected-entrypoint-name/fooclient.tsp
- tools/tsp-client/test/examples/specification/unexpected-entrypoint-name/foomain.tsp
- tools/tsp-client/test/typespec.spec.ts
Bug fix so that the tool doesnt take into account names aside from main.tsp and client.tsp. We already have support for alternate entrypoints through tsp-location.yaml
Fixes #11225
> [tsp-client] Fix entrypoint check

- eng/common/mcp/azure-sdk-mcp.ps1
- eng/common/scripts/Helpers/AzSdkTool-Helpers.ps1
It seems like `/usr/bin/env` is more conventional than `/bin/env` and not all users have the latter.
> [azsdk-cli] Fixes for mac install

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlanTool/ReleasePlanTool.cs
- Currently if no email address is provided by copilot to the tool, we retrieve the users email address. Instead, we by default retrieve the users email address and fall back on email provided. 
- Make sure not to use the azure sdk bot email address. 
- Resolves #11331
> [Devex Agent] Default to finding user email for create release plan

- tools/test-proxy/documentation/test-proxy/faq.md
- tools/test-proxy/documentation/test-proxy/trusting-cert-per-language.md
I will still update the dev cert every month (automation as recommended by @weshaggard), but this was a bit of my day yesterday helping debug various situations.
> Update FAQ for handling `dotnet devcert` expiry

- .github/event-processor.config
Enable PullRequestTriage for auto-labeling, follow-on to https://github.com/Azure/azure-sdk-tools/pull/11499 which was incomplete.
@weshaggard I missed a spot.
> Enable PullRequestTriage for auto-labeling

- tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/InfoTests.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
- tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs
As soon as I saw the error I thought I had missed something.
> Force entrylock on `matcher` value

- tools/test-proxy/ci.yml
At some point there was a change to make a parameter named `SkipReleaseStage` default to `true`. There are other conditions that will prevent that stage showing up on public builds, so I'm just setting this parameter to unblock shipping the test-proxy.
[test run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5180939&view=results)
> Ensure that `test-proxy` can actually release

- eng/common/TestResources/New-TestResources.ps1
Source user object id directly instead of with graph
> Source user object id directly instead of with graph

- eng/scripts/download_targeted_packages_requirements.txt
See title. [This is what the error looked like](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5189371&view=logs&j=e60f60ac-19f1-58f4-25c4-e0922cc9db5a&t=a7abd3c0-bbcb-558c-c16a-c6916ea0ce6e&l=4138)
[This is what it _should_ look like](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5189467&view=logs&j=e60f60ac-19f1-58f4-25c4-e0922cc9db5a)
> Bump `twine` requirement used by `mirror-pypi-to-dev-feed`

- tools/sdk-sample-generator/README.md
- tools/sdk-sample-generator/example-user-prompt.md
- tools/sdk-sample-generator/genaisrc/generate.genai.mts
- tools/sdk-sample-generator/genaisrc/src/parseUserPrompt.ts
- tools/sdk-sample-generator/test/internal/utils/parseUserPrompt.spec.ts
Adds support for supplying a user-authored prompt from a Markdown file to drive sample generation directly, bypassing the “idea generation” step when provided.
- With client API docs (Storage example):
```bash
npx genaiscript run generate --apply-edits --vars \
client-api=.artifacts/azure-sdk-for-js/sdk/storage/storage-blob/review \
language=TypeScript \
user-prompt=.artifacts/test/test-user-prompt.md \
out=.artifacts/test/ts-output \
skip-review=true
```
> [sdk-sample-generator] Add support for user prompts

- eng/common/pipelines/templates/steps/mark-release-completion.yml
- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
New template that will be plugged in release stage to mark package as released.
Tested this change for azure-python package.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5241649&view=logs&j=fa3624e2-400d-536b-43d3-bbed08ab0689&t=8abdbc0f-57ac-57a8-011c-ba46c0035f42&l=61
> Add a pipeline template to mark SDK package as released

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts
- tools/js-sdk-release-tools/src/llc/generateRLCInPipeline/generateRLCInPipeline.ts
fixes https://github.com/Azure/azure-sdk-tools/issues/11721
test in pipeline, this fix works
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5243274&view=logs&j=83516c17-6666-5250-abde-63983ce72a49
generated sdk pr doesn't remove any customized files: https://github.com/Azure/azure-sdk-for-js/pull/35647/files#diff-0111f42fe80149f65e9b3cc9e235d4c7136fa4fbcc2408c8a29aade634d775b2
> improve rlc typespec generation

- eng/common/pipelines/templates/steps/mark-release-completion.yml
- eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Fix the issue in select statement when fetching release plans.
> Fix wiql issue in getting release plan work items

- packages/python-packages/apiview-copilot/evals/run.py
- packages/python-packages/apiview-copilot/prompts/api_review/comment_filter.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/context_diff_review.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/context_review.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/existing_comment_filter.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/generic_comment_judge.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/generic_diff_review.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/generic_review.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/guidelines_diff_review.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/guidelines_review.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/merge_comments.prompty
- packages/python-packages/apiview-copilot/prompts/evals/eval_judge_prompt.prompty
- packages/python-packages/apiview-copilot/prompts/mention/parse_conversation_action.prompty
- packages/python-packages/apiview-copilot/prompts/mention/parse_conversation_to_memory.prompty
- packages/python-packages/apiview-copilot/prompts/mention/summarize_parse_conversation_to_memory.prompty
- packages/python-packages/apiview-copilot/prompts/other/summarize_metrics.prompty
- packages/python-packages/apiview-copilot/prompts/summarize/summarize_api.prompty
- packages/python-packages/apiview-copilot/prompts/summarize/summarize_diff.prompty
Closes #11637.
Initial draft follows the guidance here: https://platform.openai.com/docs/guides/latest-model#migrating-from-other-models-to-gpt-5
> o3: gpt-5 with medium or high reasoning is a great replacement. Start with medium reasoning with prompt tuning, then increasing to high if you aren't getting the results you want.
Since we were using o3-mini, I converted that to gpt-5 with "medium" reasoning
> gpt-4.1: gpt-5 with minimal or low reasoning is a strong alternative. Start with minimal and tune your prompts; increase to low if you need better performance.
Converted to GPT-5 with "minimal" reasoning
For evals, I converted it to use GPT-5-mini
> [AVC] Update models to GPT-5

- eng/common/scripts/ChangeLog-Operations.ps1
This will enable some customization of the header section that some usages need like the mcp changlog.
See https://github.com/microsoft/mcp/pull/33
> Update changelog parsing to round-trip header

- packages/python-packages/apiview-copilot/metadata/android/filter.yaml
- packages/python-packages/apiview-copilot/metadata/dotnet/filter.yaml
- packages/python-packages/apiview-copilot/metadata/golang/filter.yaml
- packages/python-packages/apiview-copilot/metadata/ios/filter.yaml
- packages/python-packages/apiview-copilot/metadata/java/filter.yaml
- packages/python-packages/apiview-copilot/metadata/python/filter.yaml
- packages/python-packages/apiview-copilot/metadata/rust/filter.yaml
- packages/python-packages/apiview-copilot/metadata/typescript/filter.yaml
- packages/python-packages/apiview-copilot/prompts/api_review/comment_filter.prompty
Fixes #11732.
Adds a line to every language's filter to remove comments that don't identify a problem.
> [AVC] Filter out comments that don't identify a problem

- tools/azsdk-cli/README.md
Based on a few conversations I've had, our current philosophy is that tools should be available in both the CLI and MCP where possible (granted, sometimes this can't be done). I'd like to start a conversation about what our stance is on this and clarify the guidelines, hence this PR. This is just a starting point, please share your thoughts :)
> Update guidelines around when tools should be MCP tools vs. CLI tools

- eng/common/instructions/azsdk-tools/validate-codeowners.instructions.md
- eng/common/instructions/azsdk-tools/validate-service-label.instructions.md
Related issue: https://github.com/Azure/azure-sdk-tools/issues/11843
Changes:
- Added information about the role of service labels before proceeding with validation process
- Provided more guidance for naming new service labels
- Updated minor grammatical mistakes in CODEOWNERS instructions
> Additional Service Label Information for Users

- eng/common/TestResources/New-TestResources.ps1
My previous PR #11531 seemed to fix the issue only partially, but RBAC assignments with the user's home account ID did not appear to be working in TME. Apparently graph api calls still work in TME and I found a cmdlet that only requires `User.Read` and not `User.ReadAll`.
CC @alzimmermsft
> Source user ID from graph api in TME

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/SpecWorkFlowToolTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/InputSanitizer.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/ReleasePlanHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/ReleasePlan/SpecWorkFlowTool.cs
Add a sanitizer helper class to sanitize language name. I have found an issue when agent says generate SDK for `csharp` and three is no pipeline to support it or sometimes it says language is Dotnet
> Fix language name issue when generating SDK from copilot

- packages/python-packages/apiview-copilot/cli.py
- packages/python-packages/apiview-copilot/src/_apiview.py
- packages/python-packages/apiview-copilot/src/_metrics.py
- packages/python-packages/apiview-copilot/tests/metrics_test.py
- Refactors APIView functionality and metrics into dedicated files. 
- Remove `--use-api` from `avc apiview get-comments`. You can only query the API and can no longer query the CosmosDB directly.
- Adds an `avc apiview get-active-reviews` command to list which reviews were considered "active" for the metrics period.
Example usage:
```bash
avc apiview get-active-reviews -l python -s 2025-08-01 -e 2025-08-31
[
{
"PackageName": "azure-identity",
"id": "f020a2e326444ae2acc406846e39dc48"
},
{
"PackageName": "azure-storage-blob",
"id": "0bc7af0b718b4db19ba1875758aa5d9a"
},
{
"PackageName": "azure-storage-file-datalake",
"id": "44182315aa5f4b0fbd91945ac955eb22"
}
]
```
> [AVC] Refactor metrics

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/DevOpsService.cs
PR has changes to pass release plan work item ID to SDK generation pipeline so pipeline will update generated SDK link in the release plan.
> Pass work item ID to SDK generation pipeline

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/TestHelpers/TestOutputHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/Generators/ReadMeGeneratorToolTests.cs
This updates the readme generator tests to not use the service provider for setup, which was causing a lot of logs to get printed out when tests are passing. Instead we now inject `TestLogger` manually.
FYI @richardpark-msft
> Simplify readme generator test services and remove noisy test logging

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/CodeownersToolsTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/EngSys/CodeownersTools/CodeownersTools.cs
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter.Tests/TestHelpers.cs
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter.Tests/Utils/BaselineUtilsTests.cs
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter/Azure.Sdk.Tools.CodeownersLinter.csproj
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersLinter/Program.cs
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Azure.Sdk.Tools.CodeownersUtils.csproj
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Caches/TeamUserCache.cs
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Utils/FileHelpers.cs
- tools/codeowners-utils/Azure.Sdk.Tools.CodeownersUtils/Utils/Log.cs
The codeowners tests were adding a bunch of logging that was coming out of the codeowners utils library, which was annoying me. As a library it should not be using `Console.WriteLine` so this refactors it to follow the guidance at https://learn.microsoft.com/en-us/dotnet/core/extensions/logging-library-authors
> Use logger factory instead of console for codeowners library logging

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Azure.Sdk.Tools.Cli.csproj
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Configuration/AzSdkToolsMcpServerConfiguration.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Extensions/OpenTelemetryExtensions.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/ITelemetryService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/InformationProvider/DefaultMachineInformationProvider.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/InformationProvider/IMachineInformationProvider.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/InformationProvider/LinuxMachineInformationProvider.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/InformationProvider/MacOSXMachineInformationProvider.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/InformationProvider/MachineInformationProviderBase.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/InformationProvider/UnixMachineInformationProvider.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/InformationProvider/WindowsMachineInformationProvider.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/TelemetryConstants.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/TelemetryLogRecordEraser.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Telemetry/TelemetryService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/HostServer/TelemetryWrapper.cs
Add Open telemetry changes to push MCP server telemetry and logs to app insights
> Add telemetry for AzSdk MCP server tool calls

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/TypeSpec/TspClientUpdateToolTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/ITspClientHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/TspClientHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Models/Responses/TspClientUpdateResponse.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/TypeSpec/TspClientUpdateTool.cs
- Extended ITspClientHelper with UpdateGenerationAsync
- Implemented update command in TspClientHelper invokes [tsp-client update --tspPath ... --output-dir ...]
- Injected ITspClientHelper into TspClientUpdateTool and replaced placeholder regenerate step with real call to generate new code at provided newGen path location if provided.
> Add Regenerate feature to Update workflow using shared helper 

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Contract/MCPTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Microagents/MicroagentHostServiceTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Tools/ExampleToolTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Helpers/TokenUsageHelper.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Microagents/MicroagentHostService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Program.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/Agent/AzureAgentService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/Agent/AzureAgentServiceFactory.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/ServiceRegistrations.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/Example/ExampleTool.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/Pipeline/PipelineAnalysisTool.cs
Making all the MCP tools injected via `AddScoped` instead of as singletons. This will allow us to inject other classes that can manage state for the request scope. In this PR the token usage helper is made scoped so that we can track agent token usage across the code for an entire request, and then later consume it from multiple places like our telemetry service (FYI @praveenkuttappan).
Also updating the backend foundry project endpoint for the agent service, since the legacy project has started breaking for API calls.
To play around with the scoped token usage helper, I added an example tool/cli command for the micro agent service which computes fibonacci.
Finally, this fixes an issue from last month where logs coming out of any `Azure.Sdk.Tools.*` namespace were not printed to console.
> [azsdk-cli] Use scoped tools and helpers, add micro agent example

- packages/python-packages/apiview-copilot/prompts/api_review/comment_filter.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/existing_comment_filter.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/generic_comment_judge.prompty
- packages/python-packages/apiview-copilot/prompts/api_review/merge_comments.prompty
- packages/python-packages/apiview-copilot/prompts/evals/eval_judge_prompt.prompty
- packages/python-packages/apiview-copilot/prompts/mention/parse_conversation_action.prompty
- packages/python-packages/apiview-copilot/prompts/mention/parse_conversation_to_memory.prompty
- packages/python-packages/apiview-copilot/prompts/mention/summarize_actions.prompty
- packages/python-packages/apiview-copilot/prompts/thread_resolution/parse_thread_resolution_action.prompty
- packages/python-packages/apiview-copilot/prompts/thread_resolution/parse_thread_resolution_to_memory.prompty
- packages/python-packages/apiview-copilot/prompts/thread_resolution/summarize_actions.prompty
We migrated all non-reasoning prompts from GPT-4.1 to GPT-5 with "minimal" reasoning. However, we have observed that these migrated prompts have run into rate limits and can take much longer to complete than their GPT-4.1 equivalent, and the results cannot be made deterministic through parameter tuning.
Since the goal of these prompts is to be fast (and deterministic) this PR reverts back to the earlier model.
> [AVC] Revert non-reasoning prompt to GPT-4.1

- tools/tsp-client/CHANGELOG.md
- tools/tsp-client/package-lock.json
- tools/tsp-client/package.json
- tools/tsp-client/src/commands.ts
- tools/tsp-client/test/commands.spec.ts
- tools/tsp-client/test/examples/specification/contosowidgetmanager-legacy-package-dir/Contoso.WidgetManager/tspconfig.yaml
Go and Rust have historically recommended folks add an emitter-output-dir variable in their tspconfig.yaml files for their libraries, but relied on tsp-client ignoring emitter-output-dir when generating client libraries. The 0.28.0 version of tsp-client which added support for emitter-output-dir broke these languages because we give preference to emitter-output-dir over package-dir in tspconfig.yaml. Having both `package-dir` and `emitter-output-dir` should be an error going forward (tracking issue TBD), we have also merged updates to the tspconfig.yaml files for Go and Rust libraries so the latest versions of all tsp projects are clean and indeed only have emitter-output-dir. However, since Go has many libraries that will eventually need to be updated to the latest commit in the specs …
> [tsp-client] Make emitter-output-dir support less breaking

- tools/js-sdk-release-tools/package-lock.json
- tools/js-sdk-release-tools/package.json
- tools/js-sdk-release-tools/src/common/utils.ts
emitter-output-dir: "{output-dir}/{service-dir}/{your-package-dir-name} "
test pipeline:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5338718&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692&l=158
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5342996&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692
> Add outputDir override to resolveOptions for current directory usage

- tools/spec-gen-sdk/src/automation/workflowPackage.ts
- tools/spec-gen-sdk/test/automation/workflowPackage.test.ts
This pull request introduces a conditional check to skip the build script execution in the workflow automation logic if a `generateScript` option is configured. This change ensures that when `generateScript` is set, the build script is not redundantly run, improving the workflow's efficiency and clarity.
Build script execution logic:
* Added a check in `workflowPkgCallBuildScript` to skip running the build script if `generateScript` is configured in `swagger_to_sdk_config.json`, with a corresponding log message for visibility.
> Support build command in swagger config

- .github/dependabot.yml
The folder needs to be exact folder of `package.json` and lock file and a parent folder of them doesn't work.
> Update dependabot config for npm directories

- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.spec.ts
- src/dotnet/APIView/ClientSPA/src/app/_components/review-page-options/review-page-options.component.ts
The copilot review is requested everywhere, ignoring what is filtered by language, or GA, this is only happening on staging.
I think there was an issue resolving merge conflicts that caused this code removed
> [ApiView] Fix copilot required for approval - regression

- tools/apiview/parsers/csharp-api-parser/ci.yml
The csharp parser is not getting release because the change on this condition on the main template, changing this to resume the release. 
Pipeline: https://dev.azure.com/azure-sdk/internal/_build?definitionId=7044&_a=summary
Last Release: July 1st
> Set different condition for csharp-api-parser-release

- eng/common/scripts/Get-PullRequestCreator.ps1
- eng/common/scripts/Submit-PullRequest.ps1
Now we have `dependabot` enabled in `azure-sdk-tools` repo, and [the sync PRs](https://github.com/Azure/azure-sdk-tools/pull/12188) failed in assigning to the bot.
The cause could be GitHub doesn't allow to assign an issue to someone which don't have the write permission.
> Set pr creator to empty when it's bot

- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Microagents/MicroagentHostServiceTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli.Tests/Services/Languages/GoLanguageSpecificChecksTests.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Azure.Sdk.Tools.Cli.csproj
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Azure/Agent/AzureAgentService.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Services/Languages/GoLanguageSpecificChecks.cs
- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Tools/Pipeline/PipelineAnalysisTool.cs
- Support custom prompts from the command line and MCP clients for log analysis
- Only delete used agent resources
- Bump ai sdk dependencies
- Fix bug where ctrl-c in the agent tool does return exit code 1 (if a tool calls another method that has a try/catch => response error handler then the operation canceled exception will get swallowed).
Resolves #11655
> [azsdk-cli] Support custom log analysis prompts

- tools/azsdk-cli/Azure.Sdk.Tools.Cli/Microagents/MicroagentHostService.cs
debugging with @l0lawrence we found that the agent sometimes returns null to the exit tool which it really shouldn't do. This is because the root property in the result was not marked as `required`.
> [azsdk-cli] fix microagent returning null result

- src/dotnet/APIView/APIViewWeb/Models/AIReviewModel.cs
A typo in the name here results in correlation id not being parsed from copilot output.
> [APIView] Fix incorrect JSON property name casing in CorrelationId

- eng/common/pipelines/templates/steps/set-vcpkg-cache-vars.yml
- eng/common/scripts/Set-VcpkgWriteModeCache.ps1
- tools/apiview/parsers/cpp-api-parser/ci.yml
Fixes: https://github.com/Azure/azure-sdk-tools/issues/12291
A recent change to vcpkg broke caching scenarios. It's a matter of time before those breaks spread to other parts of our EngSys. Consolidating vcpkg cache configurations in a single place will make it easier to roll out fixes.
The two important steps for setting vcpkg cache variables are: 
1. Setting the initial variables for read-only access (not required but helpful in almost all situations) 
2. Setting variables for write access in `internal` builds
This template performs steps that will work in existing invocations. Some implementations like Rust include extra steps. Those steps can be taken in other places when migrating to eng/common vcpkg. 
Places where something like this is used: 
* C - …
> Set up vcpkg cache variables in eng/common
